### ISSUE TITLE
View cube features

### ISSUE THREAD

**Issue by objorke** [helix-toolkit/helix-toolkit#1]
**This issue was imported from [CodePlex](http://helixtoolkit.codeplex.com/workitem/9954)**

**[objo](http://www.codeplex.com/site/users/view/objo)** wrote 2012-06-09 at 22:47
Each of edge, corner and side of cube can change type of view. And most important, after turning you can see at least 2-3 sides of cube.

(moved from issue 9953)

**Comment by JeremyAnsel** [comment]
This issue was solved in #320 (`HelixViewport3D.IsViewCubeEdgeClicksEnabled` property).

**Comment by JeremyAnsel** [comment]
The new features are present in `HelixViewport3D` (WPF) but not in `HelixViewport3DX` (SharpDX).

**Comment by holance** [comment]
@JeremyAnsel I think the edge click also available for HelixViewport3DX. Set IsViewCubeEdgeClicksEnabled = true to enable this feature.

**Comment by JeremyAnsel** [comment]
You're right. It's present in both HelixViewport3D and HelixViewport3DX.
