### ISSUE TITLE
Camera Target Positioning

### ISSUE THREAD

**Issue by dcalmes** [helix-toolkit/helix-toolkit#1000]
I am currently working with the Viewport3DX and am trying to figure out how to set the camera target position.  I am trying to get it so the target position stays at 0,0,0 in order to allow the camera rotate around the object.  Is there any way to do this?

**Comment by holance** [comment]
Set camera look dir = -camera position. And disable Panning.

**Comment by holance** [comment]
Close this for now. If you have further question, please ask at [Gitter](https://gitter.im/helix-toolkit/helix-toolkit)
