### ISSUE TITLE
Loading Additional Elements needs change in zoom, to render newly added elements on ViewPort

### ISSUE THREAD

**Issue by manojsakhare** [helix-toolkit/helix-toolkit#1005]
I have binded ViewPort ItemsSource property to ObservableElement3DCollection... 
Whenever I add new item to the collection dynamically, I have to change zoom to see the newly added objects on ViewPort.
What is the best way to refresh the viewport when a new element is added.

**Comment by holance** [comment]
Are you using WPF version or SharpDX version? Viewport3DX does not have the ItemsSource property.

**Comment by manojsakhare** [comment]
So I am binding ViewPort as...

_viewPortObject.SetBinding(ItemsControl.ItemsSourceProperty, nameof(ViewPortObjects));

**Comment by holance** [comment]
Are you using WPF version or SharpDX version?

**Comment by manojsakhare** [comment]
Yes.. ViewPort3DX object from namespace HelixToolkit.Wpf.SharpDX

**Comment by manojsakhare** [comment]
You are right... there is not ItemsControl property... I am using Items property to update the items... but at the same time I forgot to remove the line where I am setting the bindings... is this might be an issue with the updates? I removed this line... it seems to be working, but I need to do some more tests before confirming. PLease provide your comments.

**Comment by holance** [comment]
Maybe it is the binding error. Another way is to use a GroupModel3D and uses its items source to bind to your collection.

**Comment by manojsakhare** [comment]
Okay... I removed unnecessary binding code... but issue still persist...
What I found is... it is happening for arrows... so I am adding arrows using MeshBuilder... once the arrows are added to builder then adding the geometry, created by using ToMeshGeometry3D() method in ObservableElement3DCollection... viewport doesn't update the elements until i change it either by zoom or pan... is there a limit to MeshBuilder? or to ViewPort to update the items immedieately??

**Comment by manojsakhare** [comment]
One more information: The arrows getting added in a iterative loop, locked block,

**Comment by holance** [comment]
Try to use GroupModel3D to bind the ObservableElement3DCollection

**Comment by holance** [comment]
Have you solve your problem? If not, try to upload a demo project so we can debug the issue.

**Comment by manojsakhare** [comment]
No... Now I have added ZoomForce of 0.001 which internally calling InvalidateRender... I tried call it directly but it did not worked... so for now adding ZoomForce is one of the workaround. I will upload a demo.

**Comment by manojsakhare** [comment]
[SharpDxArrowDemo.zip](https://github.com/helix-toolkit/helix-toolkit/files/2711461/SharpDxArrowDemo.zip)

**Comment by manojsakhare** [comment]
![2018-12-27_10h24_50](https://user-images.githubusercontent.com/4363487/50466133-b4502480-09c1-11e9-8111-dd802cdd0448.gif)
Demo version and vedio for reference.

**Comment by holance** [comment]
Seems like your function freeze the UI thread too long. Try to use a task to generate your arrow mesh instead of using UI thread.
`
Task.Run<MeshGeometry3D>(() =>
            {
                var points = mPointGeometry3D.Positions.Select(c => new Point3D(c.X, c.Y, c.Z)).ToList();
                var vectors = new List<Vector3D>();
                var rnd = new Random();
                foreach (var point in points)
                {
                    vectors.Add(new Vector3D(rnd.NextDouble(0, 10000), rnd.NextDouble(0, 10000), rnd.NextDouble(0, point.Z)));
                }

                var geo = GenerateVelocityVectorGeometry(points, vectors);
                return geo;
            }).ContinueWith(x =>
            {
                var model = new MeshGeometryModel3D
                {
                    Geometry = x.Result,
                    Material = PhongMaterials.Red
                };
                mGroupModel3D.Children.Add(model);
            }, TaskScheduler.FromCurrentSynchronizationContext());
`
