### ISSUE TITLE
What is the difference between HelixToolkit.WPF and HelixToolkit.WPF.SharpDX?

### ISSUE THREAD

**Issue by WangWeiQiang230** [helix-toolkit/helix-toolkit#1012]
1. Does HelixToolkit.WPF.SharpDX render better?
2. What can't HelixToolkit.WPF do that HelixToolkit.WPF.SharpDX can?

**Comment by holance** [comment]
[WPF vs WPF.SharpDX](https://github.com/helix-toolkit/helix-toolkit/wiki/WPF-vs-WPF.SharpDX)

**Comment by WangWeiQiang230** [comment]
Thanks for your reply.
