### ISSUE TITLE
Scene load slow (SharpDX)

### ISSUE THREAD

**Issue by gregorsGit** [helix-toolkit/helix-toolkit#1013]
Hi,
its more a question than a bug.
I compare the startup performance between WPF and SHARPDX.
It seems that the SHARPDX-Project takes longer to switch between two views, than the WPF version.
I have a tabcontrol with two tabitems and each have a viewport3dx. So when I switch between this views, it takes a while.
I profile this and it looks like the dispose of the viewer. 
![grafik](https://user-images.githubusercontent.com/34306200/49156798-90e07e00-f31e-11e8-9dda-df3bed41b134.png)
Is there something I can do to speed up such a view switch?
Thanks.

**Comment by holance** [comment]
Yes, this is a unfortunate drawback from WPF design. When you switch the tab, the unloaded event triggered and all scene resources are disposed. WPF only has this event to notify when a visual is removed from visual tree. There is no other event can be use to notify if the viewport is removed or not. 
Currently `Loaded/Unloaded` event calls `StartD3D` and `EndD3D` inside `DPFCanvas`.
`RenderHost` has `StartRendering` and `StopRendering` functions, calling these two can solve your problem, but then there is no way to call EndD3D when viewport is removed.

Suggestion is welcome.
