### ISSUE TITLE
Love the Project, a few Include errors....

### ISSUE THREAD

**Issue by mattsphone7** [helix-toolkit/helix-toolkit#1023]
Originally, I had 96 build errors. Most were due to missing .cso files. From a previous build I copied the "Resources" dir over. That took care of many errors; reduced it to 20'ish errors.

I've searched my drive (new helixtoolkit master/w examples and old downloads). Still, I'm missing:

\Source\HelixToolkit.UWP\Resources\vsVolume.cso" because it was not found.	HelixToolkit.UWP			
\Source\HelixToolkit.UWP\Resources\vsSSAO.cso" because it was not found.	HelixToolkit.UWP			
\Source\HelixToolkit.UWP\Resources\vsMeshBatchedSSAO.cso" because it was not found.	HelixToolkit.UWP		\Source\HelixToolkit.UWP\Resources\psSSAOBlur.cso" because it was not found.	HelixToolkit.UWP			
\Source\HelixToolkit.UWP\Resources\psEffectOutlineSmooth.cso" because it was not found.	HelixToolkit.UWP		\Source\HelixToolkit.UWP\Resources\psMeshPBR.cso" because it was not found.	HelixToolkit.UWP			
\Source\HelixToolkit.UWP\Resources\psVolume.cso" because it was not found.	HelixToolkit.UWP			
\Source\HelixToolkit.UWP\Resources\psMeshPBROIT.cso" because it was not found.	HelixToolkit.UWP			
\Source\HelixToolkit.UWP\Resources\vsSprite.cso" because it was not found.	HelixToolkit.UWP			
\Source\HelixToolkit.UWP\Resources\psSSAO.cso" because it was not found.	HelixToolkit.UWP			
\Source\HelixToolkit.UWP\Resources\psVolumeDiffuse.cso" because it was not found.	HelixToolkit.UWP		\Source\HelixToolkit.UWP\Resources\psVolumeCube.cso" because it was not found.	HelixToolkit.UWP			
\Source\HelixToolkit.UWP\Resources\psSSAOP1.cso" because it was not found.	HelixToolkit.UWP			
\Source\HelixToolkit.UWP\Resources\vsMeshSSAO.cso" because it was not found.	HelixToolkit.UWP			
\Source\HelixToolkit.UWP\Resources\vsScreenQuad.cso" because it was not found.	HelixToolkit.UWP			
\Source\HelixToolkit.UWP\Resources\vsMeshDepth.cso" because it was not found.	HelixToolkit.UWP			
\Source\HelixToolkit.UWP\Resources\psSprite.cso" because it was not found.	HelixToolkit.UWP

Any update/solution/advice would be great. 

Thanks,

Matt

**Comment by holance** [comment]
Windows 10 SDK Ver.10.0.10586.0 can be selected and installed using Visual Studio 2017 installer.If you installed the higher version only, please change the target version in HelixToolkit.Native.ShaderBuilder property to the proper version installed on your machine.

**Comment by holance** [comment]
Solved the issue yet?

**Comment by mattsphone7** [comment]
I apologize for this delayed response.

Changing the SDK version as you suggested cured/fixed the issue I was having regarding my post.

After doing so, I have had other build issues. I attribute them to my own machine/setup at this time. 

In short, the solution you offered regarding the *.cso files worked. 

Thank You,

Matt
