### ISSUE TITLE
Zooming at small look directions

### ISSUE THREAD

**Issue by ChaosSorcerer** [helix-toolkit/helix-toolkit#1032]
I would suggest that the zooming functionality limits the size of the look directions or gets fixed to work with small look directions. When the camera's look direction is small enough (e.g. vector length of 0.001), zooming causes noticable camera shaking that gets worse as the look direction's length gets smaller. 

It does this regardless of whether one zooms with ZoomAroundMouseDownPoint on or off, but the problem mostly occurs when ZoomAroundMouseDownPoint is on as it can change the look direction to arbitrarily small values. (When ZoomAroundMouseDownPoint is off, one would need to manually select such small look directions whilst most people would simply put in unit vectors).

Easiest workaround I've found is binding to the actual camera and normalizing it, but ideally the zoom handler should prevent the camera shake on its own.

**Comment by holance** [comment]
Yes, have not yet had time to fix this issue.

**Comment by ArieRiezebos** [comment]
@holance same problem happens when the look direction is very large, camera starts shaking then too. For me this happens on the SharpDX version after zooming in very far and then extending the view. I saw your solution to normalize the look direction, could we normalize it when the look direction gets very large too?

![image](https://github.com/helix-toolkit/helix-toolkit/assets/105909808/e7e1baae-e96a-46be-aa62-5c082e9a2f9e)

**Comment by holance** [comment]
You need to scale your scene to be relatively reasonable size, otherwise it causes floating point errors.

**Comment by ArieRiezebos** [comment]
> You need to scale your scene to be relatively reasonable size, otherwise it causes floating point errors.

I understand but I would expect them to be resolved when zooming out again (or when extending). In my case I do a box select zoom to region to zoom in to a very specific detail <1mm then zoom out to view the entire viewport with an orthographic camera and the camera starts shaking. A Reset() of the camera resolves the issue, so I might add an automatic reset when extending, but it would be nice if it could be handled automatically.

Very big fan of your project btw!

**Comment by holance** [comment]
Do you know the width of the orthographic camera value?  What's the size of your entire scene?

**Comment by holance** [comment]
It could be a bug causing these huge numbers.

**Comment by ArieRiezebos** [comment]
Below please find an animation of the problem.
![Animation02](https://github.com/helix-toolkit/helix-toolkit/assets/105909808/37f41336-b0a7-4755-a431-1d3161bee1e7)

You can see mee zooming in, using a box selection camera.ZoomToRectangle(), multiple times to a crazy level as a user could do. Everyone will understand that at some point that stops to be reasonable, but one would expect that when extending the viewport again (CTRL+E) the camera would somehow be reset and everything acts normal again. However, as you can see in this example, the lookdirection values become increasingly large and after repeating this a few times, even with more normal zoom levels, the camera starts acting weird.

Example of camera weirdness:
![Animation03](https://github.com/helix-toolkit/helix-toolkit/assets/105909808/373b1fc2-1845-4bd8-93bb-bcaa892b0cb1)

Once again, I think I can work around it, but if it could be avoided altogether that would be awesome.

_I know I'm hijacking @ChaosSorcerer's post, he'll understand, we work together. :)_

**Comment by holance** [comment]
Which version of the Helix toolkit are you using?  I recently fixed the zoom extent issue in the develop branch. You can try the nightly build.

**Comment by ArieRiezebos** [comment]
Thanks for your quick response. I tried it with the nightly builds (2.24.0-alpha-0002) but the problem persists.

You can see the artifacts in the visualization and moving the camera does not work anymore. Look direction and position become very large:
![image](https://github.com/helix-toolkit/helix-toolkit/assets/105909808/4998f75b-d22a-4919-a262-53b2d224004e)

Low priority, I can work around it.

**Comment by holance** [comment]
You need to install this version: 2.25.0-alpha.31.build.94

**Comment by ArieRiezebos** [comment]
@holance tested and verified. That version indeed solves the issue. Thanks again!
