### ISSUE TITLE
Adding BeginAnimation function to SharpDX Camera

### ISSUE THREAD

**Issue by AliFlux** [helix-toolkit/helix-toolkit#1039]
Hi.

Animating a camera is a common use-case. Unfortunately, the SharpDX camera `AnimateTo` function uses a linear easing method, and takes in a lot of unnecessary arguments.

I suggest adding a [`BeginAnimation`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.uielement.beginanimation?view=netframework-4.7.2) function, so that we can animate any of its properties using WPF's built-in animation framework. 

The WPF camera [already](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.media3d.perspectivecamera?view=netframework-4.7.2) has this function, and it would suit well in SharpDX as well.

Here's a nice tutorial about [animating a DependencyProperty in WPF](https://docs.microsoft.com/en-us/dotnet/framework/wpf/graphics-multimedia/how-to-animate-a-property-without-using-a-storyboard).

**Comment by holance** [comment]
You can still use storyboard externally to do animation on camera property without begin animation from camera.

**Comment by AliFlux** [comment]
BeginAnimation is required when triggering animation from code behind, without using any storyboard. Here's an example of how to animate a width property of a button c#:

```cs
DoubleAnimation myDoubleAnimation = new DoubleAnimation();
myDoubleAnimation.From = 75;
myDoubleAnimation.To = 300;
myDoubleAnimation.Duration =  new Duration(TimeSpan.FromSeconds(5));
myDoubleAnimation.AutoReverse = true;
myDoubleAnimation.RepeatBehavior = RepeatBehavior.Forever;

// Apply the animation to the button's Width property.
button.BeginAnimation(Button.WidthProperty, myDoubleAnimation);    
```
