### ISSUE TITLE
D3D Counter is negative (SharpDX)

### ISSUE THREAD

**Issue by gregorsGit** [helix-toolkit/helix-toolkit#1040]
Hi,

with the current Version I get this exception.
This happens when a viewport3DX was closed/reopened. (sometimes)

System.IndexOutOfRangeException: D3DCounter is negative.
   bei HelixToolkit.Wpf.SharpDX.ModelContainer3DX.Detach() in C:\Projects\Base_Tools\HelixToolkitSharpDX\Source\HelixToolkit.SharpDX.SharedModel\Controls\ModelContainer3DX.cs:Zeile 535.
   bei HelixToolkit.Wpf.SharpDX.Viewport3DX.Detach() in C:\Projects\Base_Tools\HelixToolkitSharpDX\Source\HelixToolkit.Wpf.SharpDX\Controls\Viewport3DX.cs:Zeile 930.
   bei HelixToolkit.Wpf.SharpDX.Render.DX11RenderHostBase.DetachRenderable() in C:\Projects\Base_Tools\HelixToolkitSharpDX\Source\HelixToolkit.SharpDX.Shared\Render\RenderHost\RenderHostBase.cs:Zeile 963.
   bei HelixToolkit.Wpf.SharpDX.Render.DX11RenderHostBase.EndD3D() in C:\Projects\Base_Tools\HelixToolkitSharpDX\Source\HelixToolkit.SharpDX.Shared\Render\RenderHost\RenderHostBase.cs:Zeile 918.
   bei HelixToolkit.Wpf.SharpDX.Render.DX11RenderHostBase.Restart(Boolean hotRestart) in C:\Projects\Base_Tools\HelixToolkitSharpDX\Source\HelixToolkit.SharpDX.Shared\Render\RenderHost\RenderHostBase.cs:Zeile 761.
   bei HelixToolkit.Wpf.SharpDX.Render.DX11RenderHostBase.set_EffectsManager(IEffectsManager value) in C:\Projects\Base_Tools\HelixToolkitSharpDX\Source\HelixToolkit.SharpDX.Shared\Render\RenderHost\RenderHostBase.cs:Zeile 212.
   bei HelixToolkit.Wpf.SharpDX.Viewport3DX.<>c.<.cctor>b__52_7(DependencyObject s, DependencyPropertyChangedEventArgs e) in C:\Projects\Base_Tools\HelixToolkitSharpDX\Source\HelixToolkit.Wpf.SharpDX\Controls\Viewport3DX.Properties.cs:Zeile 251.
   bei System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   bei System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   bei System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   bei System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   bei System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   bei System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   bei HelixToolkit.Wpf.SharpDX.Viewport3DX.set_EffectsManager(IEffectsManager value) in C:\Projects\Base_Tools\HelixToolkitSharpDX\Source\HelixToolkit.Wpf.SharpDX\Controls\Viewport3DX.Properties.cs:Zeile 1474.
   bei HelixToolkit.Wpf.SharpDX.ModelContainer3DX.AttachViewport3DX(IViewport3DX viewport) in C:\Projects\Base_Tools\HelixToolkitSharpDX\Source\HelixToolkit.SharpDX.SharedModel\Controls\ModelContainer3DX.cs:Zeile 202.
   bei HelixToolkit.Wpf.SharpDX.Viewport3DX.<>c.<.cctor>b__52_51(DependencyObject d, DependencyPropertyChangedEventArgs e) in C:\Projects\Base_Tools\HelixToolkitSharpDX\Source\HelixToolkit.Wpf.SharpDX\Controls\Viewport3DX.Properties.cs:Zeile 951.
   bei System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   bei System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   bei System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   bei System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   bei System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   bei System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   bei System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   bei System.Windows.Data.BindingExpression.Activate(Object item)
   bei System.Windows.Data.BindingExpression.OnDataContextChanged(DependencyObject contextElement)
   bei System.Windows.Data.BindingExpression.HandlePropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   bei System.Windows.Data.BindingExpressionBase.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   bei System.Windows.Data.BindingExpression.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   bei System.Windows.DependentList.InvalidateDependents(DependencyObject source, DependencyPropertyChangedEventArgs sourceArgs)
   bei System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)

**Comment by holance** [comment]
Try not to close and reopen viewport for now. You can just hide it if possible.
