### ISSUE TITLE
geometry3Sharp

### ISSUE THREAD

**Issue by Genn4dental** [helix-toolkit/helix-toolkit#1042]
it is not possible to implement geometry3Sharp

**Comment by holance** [comment]
Not sure what you mean.

**Comment by jotschgl** [comment]
I think this project is meant https://github.com/gradientspace/geometry3Sharp

**Comment by holance** [comment]
geometry3Sharp is a separate meshing library. You only need to convert its vector class to SharpDX math vector classes to use it in HelixToolkit.
