### ISSUE TITLE
Dispose unmanaged memory (SharpDX)

### ISSUE THREAD

**Issue by gregorsGit** [helix-toolkit/helix-toolkit#1061]
Hi,
OnDispose() the memory of a viewer is not freed. (BaseViewModel.cs are some TODO´s)
Using your ExampleBrowser and starting/closing demos for example.
The unmanaged memory is growing.
Is there a way to fix this?
Thanks.

**Comment by holance** [comment]
You need to manually call EffectsManager.Dispose() while closing the window if you don't need the viewmodel anymore. In examples, some of the samples uses Window.Closed event to dispose the ViewModel. Some have not yet updated to dispose it. 

BaseViewModel is just a sample code, it is not designed to be used in production code. 

You better create your own base view model and manage the EffectsManager life cycle by yourself. 

Please refer to [Use EffectsManager](https://github.com/helix-toolkit/helix-toolkit/wiki/EffectsManager-Usage) for details.

**Comment by gregorsGit** [comment]
I do exactly this on Dispose.
`EffectsManager.Dispose();`
or 
```
var effectManager = EffectsManager as IDisposable;
Disposer.RemoveAndDispose(ref effectManager);
```
I use "jetBrains dotMemory" to find Memory-Leaks.
And it looks like in your ExampleBrowser. A lot of unmanged memory was not disposed on closing the window.
Is there something else I can free?

**Comment by JohanLarsson** [comment]
[Here](https://www.nuget.org/packages/IDisposableAnalyzers/) is an analyzer that checks for missing dispose and other things. Not perfect but it finds things.

**Comment by holance** [comment]
I don't see there is an unmanaged memory leaks from HelixToolkit side after repeating open/close window. I added following code to dispose the viewmodel in all `MainWindow.cs` in ExampleBrowser.

```
        public MainWindow()
        {
            this.InitializeComponent();
            Closed += MainWindow_Closed;
        }

        private void MainWindow_Closed(object sender, System.EventArgs e)
        {
            if(DataContext is IDisposable d)
            {
                d.Dispose();
            }
        }
```

Are you running the latest code base? Could you attach your memory snapshot?

![image](https://user-images.githubusercontent.com/905577/50785294-06683400-1265-11e9-87ab-74504a2fb54c.png)

**Comment by gregorsGit** [comment]
Hi,
I try it with the latest version and with the code above.
Now it´s all ok. 
The unmanaged memory keeps standing on ~160MB
It can be that my source was not up to date.
Here a screenshot from the memprofiler.
![mem1](https://user-images.githubusercontent.com/34306200/50788800-b451fd80-12ba-11e9-818a-11b7f656256d.png)
Sorry and Thanks.

**Comment by holance** [comment]
Good to know :)
