### ISSUE TITLE
Blurry viewport image

### ISSUE THREAD

**Issue by atuladhar** [helix-toolkit/helix-toolkit#1063]
I have used Viewport3DHelper class to save the viewport image using Helix, The image shown during runtime in the viewport is of good quality while the image locally saved using Viewport3DHelper.SaveBitmap or Viewport3DHelper.Export is very blurry. 
Sample screenshot of viewport during runtime:
![image](https://user-images.githubusercontent.com/2435555/51030652-321b4f00-15c2-11e9-817d-6f261be769d1.png)

Sample output  of image saved as file is as below:
![image](https://user-images.githubusercontent.com/2435555/51030667-42332e80-15c2-11e9-8f1e-767351e246ec.png)

What would be the solution to this issue?

**Comment by atuladhar** [comment]
No, I haven't specified any resolution during export. As seen in first image, there's a 'Save' button which executes the following:

 private void Save_Click(object sender, RoutedEventArgs e)
        {
            string filePath = "D:\\screen.jpg";
            Viewport3DHelper.SaveBitmap(viewPort3d.Viewport, filePath);
            Viewport3DHelper.Copy(viewPort3d.Viewport);
            Viewport3DHelper.Export(viewPort3d.Viewport, filePath);
        }
I've tried saving bitmap using three methods above, all of which gives the blurry output. Is there any other specification I need to include?

**Comment by holance** [comment]
Hmm, mine works fine. You can take a look the source code in Viewport3DHelper line 716 and copy into your own project, then you can debug it.

**Comment by atuladhar** [comment]
Yes, the output image resolution is the same as the Viewport size. I was assuming Helix uses some other functions to output the image. I had tried WPF rendertargetbitmap earlier, which I dropped because of the same issue.

**Comment by atuladhar** [comment]
No.. it appears in other machine too.

**Comment by holance** [comment]
You may need to change the DPI setting on Render target Bitmap.
https://stackoverflow.com/questions/48396161/rendertargetbitmap-low-image-quality-issue

**Comment by atuladhar** [comment]
Thanks... I've tried that too but it appears RenderTargetBitmap has some quality issues during export as found in other articles too: https://csharp.wekeepcoding.com/article/23336963/RenderTargetBitmap+and+Viewport3D+-+Quality+Issues
Maybe DirectX, SharpDX could provide some solution, which I am yet to explore.

**Comment by haruby511** [comment]
Try this.

    byte[] data;
    int w, h, stride;

    SharpDX.Direct3D11.DeviceContext context = Viewport.EffectsManager.Device.ImmediateContext;
    ScreenCapture.CaptureTexture(context, Viewport.RenderHost.RenderBuffer.ColorBuffer.TextureView.ResourceAs<SharpDX.Direct3D11.Texture2D>(), out SharpDX.Direct3D11.Texture2D staging);
    using (staging)
    {
        w = staging.Description.Width;
        h = staging.Description.Height;
        stride = w * 4;

        DataBox dataBox = context.MapSubresource(staging, 0, 0, SharpDX.Direct3D11.MapMode.Read, SharpDX.Direct3D11.MapFlags.None, out DataStream sourceStream);
        using (sourceStream)
        {
            if (staging.Description.Format != SharpDX.DXGI.Format.B8G8R8A8_UNorm)
            {
                MessageBox.Show("Unsupported pixel format.");
                return;
            }
            IntPtr ptr = dataBox.DataPointer;
            data = new byte[stride * h];
            for (int y = 0; y < h; y++)
            {
                Marshal.Copy(ptr, data, stride * y, stride);
                ptr += dataBox.RowPitch;
            }
        }
        context.UnmapSubresource(staging, 0);
    }

    using (System.Drawing.Bitmap bitmap = new System.Drawing.Bitmap(w, h))
    {
        BitmapData bitmapData = bitmap.LockBits(new System.Drawing.Rectangle(0, 0, w, h), ImageLockMode.WriteOnly, PixelFormat.Format32bppArgb);
        IntPtr ptr = bitmapData.Scan0;
        for (int y = 0; y < h; y++)
        {
            int scanAt = y * stride;
            for (int x = 0; x < w; x++)
            {
                int pixelOffset = x * 4;
                int pixelAt = scanAt + pixelOffset;
                int pixel = BitConverter.ToInt32(data, pixelAt);
                Marshal.WriteInt32(ptr, pixelOffset, pixel);
            }
            ptr += bitmapData.Stride;
        }
        bitmap.UnlockBits(bitmapData);

        bitmap.Save(dialog.FileName);
    }

This snippet needs `System.Drawing.Bitmap`. It is not available on .NET standard.

This method is very clear. Copying 32-bpp back buffer pixels to a bitmap without any of deformations.

Additionally, if you are enabled AA, the back buffer should be [resolved](https://docs.microsoft.com/en-us/windows/win32/api/d3d11/nf-d3d11-id3d11devicecontext-resolvesubresource) before copying to the staging texture. The Helix toolkit actually [doing](https://github.com/helix-toolkit/helix-toolkit/blob/51455a5286179a225841f1d4630763a4403c2b85/Source/HelixToolkit.SharpDX.Shared/Utilities/ScreenCapture.cs#L51) that. Maybe this can cause the issue.
