### ISSUE TITLE
Camera Rotation with ZoomAroundMouseDownpoint=true (SharpDX)

### ISSUE THREAD

**Issue by gregorsGit** [helix-toolkit/helix-toolkit#1068]
Hi,
when I have a simple box and zoom out, the camera.Target point is changed.
I use your SimpleDemo with only one element.
![grafik](https://user-images.githubusercontent.com/34306200/51178779-f33c1080-18c3-11e9-9d03-06d3cd46fe75.png)

So if i zoom out in z (factor 4-10x) with the mouse-wheel on the box
![grafik](https://user-images.githubusercontent.com/34306200/51178820-0ea71b80-18c4-11e9-9a12-20e3ebb55a5a.png)

and rotate the box in y or x with cursor up or down.
I see the rotate-point is not in the box. 
![grafik](https://user-images.githubusercontent.com/34306200/51179028-b15f9a00-18c4-11e9-8b05-d4fb503b4f23.png)

I rotate around a point outside the box.
Farther zooming and rotate can now cases a empty view.
As I told in the chat, I think, the camera.Target Point must be inside the box!
Thanks.

**Comment by smischke** [comment]
I'm also experiencing this problem. "RotateAroundMouseDownPoint" doesn't work in 2.6 anymore. In 2.5 it's ok. Possible culprit: https://github.com/helix-toolkit/helix-toolkit/commit/7f3b3e68e7996fc4fae2ecadc1af43e45b71cb63#diff-03ef3e5473ee81ab5fc2360a460a07c7

**Comment by smischke** [comment]
I have found a way to solve it:
![](https://i.imgur.com/yG2IGH6.png)

**Comment by holance** [comment]
I will fix it later.

**Comment by gregorsGit** [comment]
Hi,

your fix is not perfect. 




![grafik](https://user-images.githubusercontent.com/34306200/55873650-7e116c00-5b90-11e9-946a-45fda48f337e.png)

I calculate a new position in the method below. Depends on the look direction.



 ```
        /// <summary>
        /// changes in lookdirection set the rotation point to wrong position
        /// </summary>
        /// <param name="newRelativeTarget"></param>
        /// <param name="relativeTarget"></param>
        /// <returns></returns>
        private Vector3 CalcNewRelativeTargetOrthogonalToLookDirection(Vector3 newRelativeTarget, Vector3 relativeTarget)
        {
            var relativeTargetDiff = newRelativeTarget - relativeTarget;
            var lookDir = Camera.CameraInternal.LookDirection;

            var crossProduct = SharedFunctions.CrossProduct(ref lookDir, ref relativeTargetDiff);
            var orthogonalRelativeTargetDiff = SharedFunctions.CrossProduct(ref crossProduct, ref lookDir).Normalized();

            // correct length
            var angle = orthogonalRelativeTargetDiff.AngleBetween(relativeTargetDiff);
            orthogonalRelativeTargetDiff *= (float) (Math.Cos(angle) * relativeTargetDiff.Length());
            newRelativeTarget = relativeTarget + orthogonalRelativeTargetDiff;

            return newRelativeTarget;
        }
```

I insert in line 280 (ZoomHandler.cs)  following code.
`   newRelativeTarget = CalcNewRelativeTargetOrthogonalToLookDirection(newRelativeTarget, relativeTarget);`

With this code it works.

Please take a minute.

Thanks.

**Comment by holance** [comment]
Current implementation always zoom to the mouse point even if mouse button is not pressed, which is not the correct behavior as the property states "ZoomAroundMouseDownPoint".

More implementation needs to be done to fix this issue. Will try to fix it in this weekend.

**Comment by gregorsGit** [comment]
Hi,
I think the name ZoomAroundMouseDownPoint is wrong.
I expect ZoomAroundMousePoint.

Even when the mouse Button is not pressed!

Please don´t change it. 
Fix only the bug with the target-position.

Thanks.

**Comment by smischke** [comment]
There is a problem with `CalcNewRelativeTargetOrthogonalToLookDirection()` that sometimes causes the look direction to flip (i. e. -Z => Z). It does not occur when not calling `CalcNewRelativeTargetOrthogonalToLookDirection()`. Is it necessary to set `this.Camera.LookDirection` in `ZoomHandler.ChangeCameraDistance()` at all? My quick tests show that `ZoomAroundMouseDownPoint="True"` works without altering the camera look direction.

**Comment by holance** [comment]
Remove CalcNewRelativeTargetOrthogonalToLookDirection for now. Does not seem there is any differences except introducing look direction bugs. Let me know if you have any example to use CalcNewRelativeTargetOrthogonalToLookDirection, then we need to fix the look direction reverting bug before put it back.
