### ISSUE TITLE
SharpDX. I draw line among 3D objects. Is it possible to make it visible always. (Bring to front)

### ISSUE THREAD

**Issue by Dmitrii2018** [helix-toolkit/helix-toolkit#1071]
SharpDX. 
I draw line among 3D objects. Is it possible to make it visible always. (Bring to front)
![2](https://user-images.githubusercontent.com/38795704/51530374-77057800-1e43-11e9-8f0f-5d288d24bc92.png)
![1](https://user-images.githubusercontent.com/38795704/51530375-77057800-1e43-11e9-915f-41cdde8d3d40.png)

**Comment by smischke** [comment]
Please take a look at the property `DepthOffset`.

**Comment by holance** [comment]
You can try to use x-ray effect on line model.

**Comment by holance** [comment]
If you still not able to solve the issue using x-ray effect, you can leave me an message in chat.
