### ISSUE TITLE
Performance issue on certain hardware, framerate drop while zooming in. 

### ISSUE THREAD

**Issue by gamerpaddy** [helix-toolkit/helix-toolkit#1072]
This is related to a OpenCNCProject* (see bottom) issue, where as zooming into the viewport causes the framerate to drop significantly. 
Theres no obvious issue in the OCNCP code that oculd cause this, so i assume its a issue of helixtoolkit and its wpf version.
https://github.com/martin2250/OpenCNCPilot/issues/89

The viewport consists of a HelixViewport3D with a few subparts. 
When zooming in, the framerates drop, even without a model loaded in.
(loaded in models consist of many lines of the Point3DCollection)

See video of the issue here: https://streamable.com/khw6i
This problem is much worse on my much stronger computer, compared to my weak one.

Test Rig 1:
1920x1080@60hz
i7 8700k @ 4.6ghz
32gb ddr4-3200 ram
gtx 980ti
OS and program on 3gb/s|2gb/s r/w SSD
windows 10.

Test rig 2:
1920x1080@60hz
i5 3427u
4gb ddr3-1333
intel integrated graphics
OS and program on 0.4gb/s|0.2gb/s ssd.
windows 10.

On Test Rig 1, even with the bare scene it drops below 1fps when zoomed in a lot. unuseable.
On Test rig 2, the framerate doesnt change much, its still useable.

Any ideas whats causing it?
Is this a issue related to helixtoolkit?

*EDIT:
can confirm its a helixtoolkit issue, this also applies to the WPF examples!
SimpleDemo runs at 60fps when zoomed out, but as soon as i get close to an edge it drops to 6fps when the scene view updates. when i stop moving / zooming it returns back to 60fps.
But when i drag it (middle mouse button) the fps counter jumps to 500+ but its still laggy as with 6fps.
https://i.imgur.com/Bz828QM.png

**Comment by holance** [comment]
WPF version is using WPF internal 3D engine for rendering. It does not supports GPU line/point drawing, all line/points are drawn using CPU.

I would suggest you to try the SharpDX version and see if performance issue still happens.

**Comment by holance** [comment]
One more note, 8700k has integrated graphics card, which means if your problem did not enable to use external graphic card, it may run on the integrated graphics card, which may be the root cause of your performance issue. You may want to use following code at program startup or manually run the program using external graphics card.

https://github.com/helix-toolkit/helix-toolkit/blob/develop/Source/HelixToolkit.SharpDX.Shared/Utilities/NVOptimusEnabler.cs

**Comment by gamerpaddy** [comment]
I disabled the integrated graphics on my 8700k. 
and as i said, i runs better on the computer with the integrated graphics only.


i tried pinning it down by removing all elementss of the viewport one by one.
lighting...grid..everything.
as soon as the viewport had just one element, even if its just a simple line. the issue was present.

**this problem also exists on the examples provided by helixtoolkit, its not a opencncpilot issue.**
the WPF SImpleDemo example has bad fps on my "strong" computer, but runs without problem even when zoomed in as far as i can on my weak one.

**Comment by holance** [comment]
Seems like it maybe the WPF issue or the graphic card driver issue.
