### ISSUE TITLE
BillboardTextVisual3D causes Crash

### ISSUE THREAD

**Issue by Reaper90** [helix-toolkit/helix-toolkit#1075]
I'm using Helixtoolkit.Wpf for displaying rather simple 3D models. I mostly use LinesVisual3D, PointsVisual3D and BillboardTextVisual3D for this, but there are cases, when the number of BillboardTextVisual3D objects exceeds about 4800 to 4900, the application crashes with the following error message.

System.Runtime.Interop.Serices.COMException:
"MILERR_WIN32ERROR (Ausnahme von HRESULT: 0x88980003)"

It does even happen, when just generating the amount of BillboardTextVisual3D objects without displaying them inside of a HelixViewPort3D. I'm not that experienced in coding, so i couldn't find a working solution myself. Any way to fix this issue?

Thanks in Advance

**Comment by Reaper90** [comment]
Thanks for the info and sorry for the late answer.
I started reading on the topic GDI objects and i did some more testing on this. Normally for what i use the BillboardTextVisual3D, i'm staying way below those numbers, so no problems there. But also if i'm using my application to modify the base data, the text of the BillboardTextVisual3D needs to be updated sometimes. And if this is happens too often, the application crashes too although there are maybe only 1000 BillboardTextVisual3D objects or less. so Maybe the created GDI objects are not disposed correctly by BillboardTextVisual3D class?

**Comment by holance** [comment]
Could you provide a sample code you use to update the BillboardTextVisual3D. If you can create a simple demo program to reproduce the crash, it will be really helpful.

**Comment by Reaper90** [comment]
Weird...
I couldn't reproduce this behaviour in a simple demo now, so maybe there's something else going on in my application. But thanks for your help!
Since having so many BillboardTextVisual3D objects is just a rare case, i'm now trying to rework my code to get more control over the number of visuals existing at the same time before thinking about trying Helixtoolkit.Wpf.SharpDX

**Comment by sanderweltje** [comment]
I had the same problem and it only happend when I add a specific text.
Looking at the code I found there is a rounding issue in TextGroupVisual3D CreateTextMaterial. The elementPositions returned by that function contains rectangles with values > 1 due to the size of the text that needs to be rendered. The BillboardTextGroupVisual3D uses this function and when the rectangle bottom > 1 it does not add the billboard resulting in an endless loop. I will create a pull request with a solution.

**Comment by holance** [comment]
Please try the new 2.6.1 version. If the crash still happens, reopen this issue.

**Comment by talapoin** [comment]
Hi, it's still crashing. Using version 2.8.0

**Comment by KonradZaremba** [comment]
2.24  same error
