### ISSUE TITLE
SceneNodeGroupModel3D transformation not working

### ISSUE THREAD

**Issue by Jamaslab** [helix-toolkit/helix-toolkit#1080]
Hello,
I'm creating multiple SceneNodeGroupModel3D, importing them using Assimp. 
This list of SceneNodeGroupModel3D is then includend in a generic GroupModel3D, which is then added to the Viewport3DX. 
I'd like to apply a relative transformation between the SceneNodeGroupModel3D elements, and then apply a transformation to the whole GroupModel3D. 

However, it appears that the relative transformation is applied only to the first element added to the GroupModel3D and all the others get the same transformation. When instead I try to assign a Transformation3D to a SceneNodeGroupModel3D (which is not the first children of the GroupModel3D), this transformation is not considered. 

Could you please help me?

You can find here below the code

     class Element {
        public SceneNodeGroupModel3D Model { get; private set; }
        
        private Transform3D _transform;
        public Transform3D Transform {
            get {
                return _transform;
            }
            set {
                _transform = value.Clone();
                _transform.Freeze();

                Model.Dispatcher.Invoke(new Action(() => { Model.Transform = new MatrixTransform3D((_transform.ToMatrix() * _localTransform.ToMatrix()).ToMatrix3D()); }));

                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Transform)));
            }
        }

        private Transform3D _localTransform;
        public Transform3D LocalTransform {
            get {
                return _localTransform;
            }

            set {
                _localTransform = value.Clone();
                _localTransform.Freeze();

                Model.Dispatcher.Invoke(new Action(() => { Model.Transform = new MatrixTransform3D((_transform.ToMatrix()*_localTransform.ToMatrix()).ToMatrix3D()); }));

                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(LocalTransform)));
            }
        }
    }

    class Part {
         public GroupModel3D Model { get; private set; }

        private List<Element> _Children;
        public ReadOnlyCollection<Element> Children { get { return _Children.AsReadOnly(); } }

        private Transform3D _transform;

        public Transform3D Transform
        {
            get {
                return _transform;
            }
            set {
                _transform = value.Clone();
                _transform.Freeze();

                Model.Dispatcher.BeginInvoke(DispatcherPriority.Background, new Action(() => { Model.Transform = _transform; }));
                
                foreach (Element element in Children) {
                    element.Transform = _transform;
                }
            }
        }
    }

**Comment by holance** [comment]
If you already assign the Transform on GroupModel3D, you don't need to do _transform.ToMatrix()*_localTransform.ToMatrix(). Only need to assign LocalTransform to each SceneNodeGroupModel3D.
Let me know if it still not working.

**Comment by Jamaslab** [comment]
Thanks for your answer. I simplified the Element class code like suggested:

public SceneNodeGroupModel3D Model { get; private set; }
        
        private Transform3D _transform;
        public Transform3D Transform {
            get {
                return _transform;
            }
            set {
                _transform = value.Clone();
                _transform.Freeze();

                Model.Dispatcher.Invoke(new Action(() => { Model.Transform = _transform; }));

                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Transform)));
            }
        }

What is weird is that if, for example, I have two Element objects inside a Part object, if I apply a transformation to the first Element inserted in the Part (first in order of insertion), both Element objects are transformed, while if apply the transformation to the second, the transformation is not applied.

**Comment by holance** [comment]
I think you should get rid of the for loop in your Part class Transform setter. You basically setting the same transform to all the children but you already set the transform to the parent.

**Comment by Jamaslab** [comment]
Hi, this didn't solve it. 
I wrote a simple executable creating everything manually, and it actually works, displaying the two scene nodes properly transformed.

            SceneNodeGroupModel3D Model1 = new SceneNodeGroupModel3D();
            SceneNodeGroupModel3D Model2 = new SceneNodeGroupModel3D();
            GroupModel3D Group = new GroupModel3D();

            Load(Model1, @"D:\wheel.3ds");
            Load(Model2, @"D:\wheel.3ds");

            Matrix3D Model1Tranform = Matrix3D.Identity;
            Model1Tranform.OffsetY = 1;
            Model1.Transform = new MatrixTransform3D(Model1Tranform);
            Group.Children.Add(Model1);

            Matrix3D Model2Tranform = Matrix3D.Identity;
            Model2Tranform.OffsetY = -1;
            Model2.Transform = new MatrixTransform3D(Model2Tranform);            
            Group.Children.Add(Model2);

            ViewportDX.Items.Add(Group);

By placing a breakpoint on the Items.Add(Group) line and navigating on the GroupModel3D children, I can see that the transformation of each SceneNode is correct.

If I do the same on the other code, I see as well with a break point that the Transformation of each child of the Part model is correct. However, the second child is displayed always with the same transformation of the first child.

**Comment by Jamaslab** [comment]
I found the problem, it was (of course) a typo. I was loading the model always in the same scene. Sorry for the disturb and thanks for the help.
