### ISSUE TITLE
Button gets disabled if I bind ViewportCommand to it

### ISSUE THREAD

**Issue by MrJox** [helix-toolkit/helix-toolkit#1081]
If I bind one of the static ViewportCommands to my button's command, button is set to disabled and I can't do anything about it.

The idea was to have a toolbar where each tool has it's own command, including some of viewport commands such as pan and zoom and having an ActiveCommand public property bound to viewport like this:

`<MouseBinding Command="{Binding SelectedCommand}" Gesture="LeftClick"/>`

However as described above this does not work.

**Comment by MrJox** [comment]
Any help?

**Comment by holance** [comment]
Try to upload a sample program with this issue.

**Comment by MrJox** [comment]
Here's the demo: https://github.com/MrJox/HelixTestProject

**Comment by holance** [comment]
You cannot bind to a static routed command directly. You can pass your viewport into your view model and directly call `Viewport3DX.AddPanForce` etc. functions.

**Comment by MrJox** [comment]
Okay, will try, thanks you.
