### ISSUE TITLE
ViewportExtensions.Project does not get correct projection 

### ISSUE THREAD

**Issue by vvs551** [helix-toolkit/helix-toolkit#1090]
ViewportExtensions.Project(viewport, point_3d) does not get correct projection point in any case
f.e. if we will call it from viewport3dx.OnRendered event

**Comment by vvs551** [comment]
Is it correct for 3d point {1,46239995956421;0;-98,5376000404358} ViewportExtensions.Project will get positive 2d point: {1128;279} ?
In previous version the result was: {786,083555463761;450,561361992651}

**Comment by holance** [comment]
It has been fixed in 2.6.1 branch, which will be released soon.

**Comment by holance** [comment]
And you don't really need to wait for the release, since the Project is extension function, you can create your own function to do the projection. You can see the fix is only one line of change.
