### ISSUE TITLE
Viewport3dx FindHits does not return the result 

### ISSUE THREAD

**Issue by vvs551** [helix-toolkit/helix-toolkit#1094]
Viewport3dx FindHits does not return the result for MeshGeometryModel3D if Material was not assigned

**Comment by holance** [comment]
Find hit only return the object is rendered. It doesn't make sense to return an item invisible to the user. If you really need to hit the invisible object, you can call Geometry3D.HitTest to manually do Hit test

**Comment by vvs551** [comment]
Thank you!
The fact is that it worked in first version of toolkit
There are a lot of Geometry3D in the viewport  in my case and I could not like to check each of that
I found the solution of this problem in the transparency of PhongMaterial
It is working for me
