### ISSUE TITLE
How to add customized ViewCube? SharpDx

### ISSUE THREAD

**Issue by santosh-bhosale** [helix-toolkit/helix-toolkit#1095]
I am adding customized SharpDx ViewCube in my WPF application.  But whenever I am trying to rotate ViewPort its not rotating in 3D. Its rotating in XY axis only. But If I used inbuilt ViewCube then all working fine.
For adding ViewCube I am using sharpDx code which is available in Git.

One more issue I am facing whenever I click on view cube it will not rotate viewport(Means nothing is changing).

I want to customized ViewCube as attached image. Kindly let me know if there is any inbuilt code is available. 
![navigation cube](https://user-images.githubusercontent.com/33144567/51884670-41fea580-23ae-11e9-9756-5db839b7556a.png)

**Comment by holance** [comment]
If you only need to change the ViewCube texture, you can create a texture like this:
![image](https://user-images.githubusercontent.com/905577/52825682-835fa800-3072-11e9-94d7-bc4ce8cdb85c.png)

And set it to Viewport3DX.ViewCubeTexuture.

**Comment by santosh-bhosale** [comment]
I can able to create texture as per attached image but when I clicked on viewcube its not rotating and also viewport is not rotating along z axis.

**Comment by holance** [comment]
Are you using a custom viewcube model? Or using the internal one?

**Comment by santosh-bhosale** [comment]
Custom one....

**Comment by holance** [comment]
Maybe if you can share a simple demo project.

**Comment by santosh-bhosale** [comment]
Sorry for late reply. The sample code is attached. The cube is not customized in that but the cube is not rotating after clicking on it.
[SimpleDemo.zip](https://github.com/helix-toolkit/helix-toolkit/files/2900782/SimpleDemo.zip)

**Comment by santosh-bhosale** [comment]
Do you have any updates on this?

**Comment by holance** [comment]
You need to implement the hit test your self. I will create a demo in this week.

**Comment by santosh-bhosale** [comment]
Kindly provide demo ASAP.

**Comment by holance** [comment]
If you don't want to use the nightly build, you may need to put the updated `ScreenSpacedNode` with hit test implemented from develop branch into your own project and use it for your custom view cube.

**Comment by santosh-bhosale** [comment]
Thank you very much.... I will try to implement that in our project....

**Comment by holance** [comment]
Close for now.
