### ISSUE TITLE
Missing File in Source Download

### ISSUE THREAD

**Issue by xxxGURUxxx** [helix-toolkit/helix-toolkit#1102]
all Resource Files in Project HelixToolkit.Wpf.SharpDX\Resources are missing!

![image](https://user-images.githubusercontent.com/6140381/52961988-70174a00-339c-11e9-9da8-cf7e852665f6.png)

**Comment by holance** [comment]
Visual Studio 2017. Windows 10 SDK (Min Ver.10.0.10586.0).

Missing .cso error during the build? Windows 10 SDK Ver.10.0.10586.0 can be selected and installed using Visual Studio 2017 installer. If you already installed the higher SDK version, please change the target version in HelixToolkit.Native.ShaderBuilder property to the version installed on your machine.
