### ISSUE TITLE
SharpDX Line disappear.

### ISSUE THREAD

**Issue by Dmitrii2018** [helix-toolkit/helix-toolkit#1105]
Hello.
I use rubber line in my project.
There is unclear problem.
This line disappear when I make pan or zoom.
It looks like there are limits of visiblle.
Though other objects and lines are visible.

![3](https://user-images.githubusercontent.com/38795704/53163177-303ba700-35d6-11e9-98dd-b6a9696fc638.jpg)
![4](https://user-images.githubusercontent.com/38795704/53163184-3467c480-35d6-11e9-9e55-66a9ab3dd8da.jpg)

I tried to change camera options. It's works for other objects but not for rubber line.

Camera = new HelixToolkit.Wpf.SharpDX.OrthographicCamera { Position = new Point3D(3, 3, 5), LookDirection = new Vector3D(-3, -3, -5), UpDirection = new Vector3D(0, 1, 0), FarPlaneDistance = 5000000,NearPlaneDistance=-10000 };

code:
    public class RubberLine : ObservableObject
    {
        public double Length { get; set; }

        private Vector3 rubberLineStart;
        public Vector3 RubberLineStart
        {
            set
            {
                SetValue<Vector3>(ref rubberLineStart, value, nameof(RubberLineStart));
                this.RLine.Positions[0] = RubberLineStart;
                this.RLine.UpdateVertices();
                this.Length = this.LengthCalc();
            }

            get { return rubberLineStart; }
        }

        private Vector3 rubberLineEnd;
        public Vector3 RubberLineEnd
        {
            set
            {
                SetValue<Vector3>(ref rubberLineEnd, value, nameof(RubberLineEnd));
                this.RLine.Positions[1] = RubberLineEnd;
                this.RLine.UpdateVertices();
                this.Length = this.LengthCalc();
            }

            get { return rubberLineEnd; }
        }

        public LineGeometry3D RLine { get; set; }
       

        public RubberLine()
        {
            var e1 = new LineBuilder();
            e1.AddLine(new Vector3(0, 0, 0), new Vector3(0, 0, 0));
            this.RLine = e1.ToLineGeometry3D(true);
        }

        public double LengthCalc()
        {
            Vector3 v = RubberLineStart - RubberLineEnd;
            return Math.Abs(v.Length());
        }
    }

xaml:
<hx:LineGeometryModel3D 
                x:Name="lines1"
                Geometry="{Binding  RLine}"
                IsRendering="True"
                Smoothness="{Binding LineSmoothness}"
                Thickness="{Binding LineThickness}"
                Color="{Binding RLColor}"/>

**Comment by holance** [comment]
Try to set Viewport3dx.EnableViewFrustum = false, let me know if it solves the issue.

**Comment by Dmitrii2018** [comment]
Thanks a lot. It's working.

**Comment by Dmitrii2018** [comment]
There is not property EnableViewFrustum in object Viewport3dx.

I solved problem by this:

"Try to call Geometry3D.UpdateBound after Geometry3D.UpdateVertices."



>Четверг, 21 февраля 2019, 19:29 +03:00 от Lunci <notifications@github.com>:
>
>Try to set Viewport3dx.EnableViewFrustum = false, let me know if it solves the issue.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

С уважением,
Dmitry Porfiriev
pde@mail.ru

**Comment by madfisht3** [comment]
> Try to call Geometry3D.UpdateBound after Geometry3D.UpdateVertices.

It works fine. Thanks a lot.
