### ISSUE TITLE
Viewport3DX is black

### ISSUE THREAD

**Issue by MiroslavJ** [helix-toolkit/helix-toolkit#1107]
Hey guys, I am pretty new with SharpDX and helix. I want to use SharpDX in WPF but when I create a Vieport3DX I can see just black window (no even orientation cube). I just create a new project in WPF, download NuGet packages (HelixToolkit.Wpf.SharpDX with dependencies) and in XAML create a simple instance of Viewport3DX. What I am doing wrong ?

**Comment by holance** [comment]
You need to create a default effects manager. Please refers to the demos for details.

**Comment by MiroslavJ** [comment]
Brilliant! Works perfect. Thanks a lot @holance !
