### ISSUE TITLE
SharpDX "FindNearest" function 

### ISSUE THREAD

**Issue by Dmitrii2018** [helix-toolkit/helix-toolkit#1109]
Hello.
I use "FindNearest" function to select model objects.
Sometimes some objects obscure the object I need to choise.
Is it possible to make any model objects unsensitive to this function,
to exclude it from choice.

**Comment by holance** [comment]
Set is hit test visible to false for those you don't want them to get hit

**Comment by Dmitrii2018** [comment]
Ok.
Thank you.
