### ISSUE TITLE
Point Cloud geometric objects

### ISSUE THREAD

**Issue by robertstefan** [helix-toolkit/helix-toolkit#111]
Hey guys, 

First of all, "Happy new Year!" :tada: and great work with this library :+1: 

What I am going to post, is not an issue, just a question for information gathering:
Can you create in WPF using this library, geometric objects generated with Point Cloud ?

Asking as I have a WPF desktop app, and I want to implement something like described in the question.

Thank you in advance. :smile:

**Comment by objorke** [comment]
Please use the forum for questions! :)
