### ISSUE TITLE
ShadowMap3D

### ISSUE THREAD

**Issue by MiroslavJ** [helix-toolkit/helix-toolkit#1110]
Hey guys,
I have a question about ShadowMap3D. I am exporting Revit building model with topography (as a plane ground). I have directional and ambient light and I am using PhongMaterials. I can see the direction of my light, but there is no shadow. My simple XAML code is:

<dx:Viewport3DX x:Name="viewportDX"  ZoomExtentsWhenLoaded="True" 
             IsShadowMappingEnabled="True" >

		<dx:ShadowMap3D x:Name="shade" Resolution="2048, 2048" />
		<dx:AmbientLight3D x:Name="ambientLightDX" Color="White"/>
		<dx:DirectionalLight3D x:Name="directionalLightDX1" Color="White" Direction="{Binding 
                                       Camera.LookDirection, ElementName=viewportDX}"/>
		<dx:MeshGeometryModel3D x:Name="buildingGeometryDX"/>
		<dx:MeshGeometryModel3D x:Name="topographyGeometryDX"/>

</dx:Viewport3DX>

Do I have to do something more to enable the shading? I have your demo sample but the shadow is working there (even when I put there my building exported from Revit) and I can't really find any documentation about this. Thanks in advance for help.

**Comment by holance** [comment]
In phong material, there is a property render shadow map, you need to set it to true, then for all models you want them to cast shadow, you need to set GeometryModel3D.IsThrowingShadow to true

**Comment by MiroslavJ** [comment]
Great, works! Thanks @holance
