### ISSUE TITLE
SharpDX. Find 3d point on 3d line.

### ISSUE THREAD

**Issue by Dmitrii2018** [helix-toolkit/helix-toolkit#1114]
Hello.

Could you give me advice.
I need to find 3d point on 3d line by mouse cursor.
I think to implement it by getting intersection between the cursor ray and line.
But not sure.
May be there is example?

**Comment by holance** [comment]
LineGeometryModel3D already has hit test implemented. The detailed hit test implementation is in LineGeometry3D.

**Comment by Dmitrii2018** [comment]
I'm trying to figure this out in the HitTest function.
What is wrong with this code?
Which object should I use in the sixth position (", object originalSource,")?

LineGeometry3D lines = new LineGeometry3D();




List<HelixToolkit.Wpf.SharpDX.HitTestResult> hits = new 
            List<HelixToolkit.Wpf.SharpDX.HitTestResult>();
            SharpDX.Matrix mx = new SharpDX.Matrix();
            Ray ray = new Ray();

            lines.HitTest(viewport.RenderContext, mx, ref ray, ref hits, null, 1);
            Vector3 pt = hits[0].PointHit;

**Comment by holance** [comment]
Why not just go through the Viewport3DX.FindHits?

**Comment by Dmitrii2018** [comment]
I tried this code:

        private Vector3 SelectPoinOnLine(Viewport3DX vp, System.Windows.Input.MouseEventArgs e)
        {
            LineGeometryModel3D line = null;
            Vector3 hitPt = new Vector3(0,0,0) ;
            System.Windows.Point mpt = Mouse.GetPosition(vp);

            var hitTests = vp.FindHits(e.GetPosition(vp));
            if (hitTests.Count == 0) return hitPt;

            if (hitTests != null && hitTests.Count > 0)
            {
                foreach (var hit in hitTests)
                {
                    line = hit.ModelHit as LineGeometryModel3D;
                    if (line != null)
                        { 
                           hitPt = hit.PointHit;
                           continue;
                        }
                    
                }
            }
            return hitPt;
        }

It's working but return wrong  hit point (hitPt). This point don't lay on the hitted line.

**Comment by Dmitrii2018** [comment]
I'm sorry. It's working correct. My be you have some comments?

**Comment by holance** [comment]
If you know your `LineGeometryModel3D`, you can hook up the `LineGeometry3D.Mouse3DDown` event directly instead of using `Viewport3DX.FindHits`.

**Comment by Dmitrii2018** [comment]
Thank you.
