### ISSUE TITLE
Shadow Geometry

### ISSUE THREAD

**Issue by MiroslavJ** [helix-toolkit/helix-toolkit#1115]
Hey guys,
I am working with SharpDX in WPF. I am getting shadow from ShadowMap3D. The question is: Is there any way to get shadow geometry? 
Thanks in advance for help.

**Comment by holance** [comment]
What do you mean by "get shadow geometry"?

**Comment by MiroslavJ** [comment]
Hi @holance ,
Let's imagine that I have this building construction:
![building](https://user-images.githubusercontent.com/35563931/54022019-71f94f80-4189-11e9-8947-60f8b45dc77a.png)

In red rectangle you can see that the wall is covered by shadow. I have to calculate what percentage of wall is covered by shadow. If I had a shadow shape (geometry) like 2D or 3D points, I would check the intersection or something like this. Do you know what I mean? Thanks.

**Comment by holance** [comment]
You may need to implement your own algorithm or special shader to calculate the shadow area. I don't think there is an easy way to do it. You need rasterization to accurately get the shadow area.

**Comment by MiroslavJ** [comment]
Ok I will. Thanks for you help.
