### ISSUE TITLE
Can I extract List<Object3D> from HelixToolkitScene?

### ISSUE THREAD

**Issue by Super169** [helix-toolkit/helix-toolkit#1116]
I just updated to v2.6.1 and I learn that there has a new importer for loading models, and I get the message for StudioReader in my code:
'StudioReader' is obsolete: 'Suggest to use HelixToolkit.SharpDX.Assimp'

I also find that the FileLoadDemo can load any 3DS file correctly, which is must better than the StudioReader, so I'd like to change from StudioReader to Importer.

Currently, I have the objects with data in memory (as a byte[]), and I will load each of them into a List of Object3D via the following code, which will be used as part of the whole model,

```
                Stream stream = new MemoryStream(data);
                var reader = new StudioReader();
                List<Object3D> part = reader.Read(stream);
```

I have modified the program as below,                

```
                Stream stream = new MemoryStream(data);
                Importer importer = new Importer();
                HelixToolkitScene scene;
                var result = importer.Load(stream, null, ".3ds", out scene);
```
                
And it returned result as Succeed.

However, the output is a HelixToolkitScene object, and my existing program is working on List of Object3D, is there any way to extract the List of Object3D from HelixToolkitScene?

**Comment by holance** [comment]
Object3D is basically contains MeshGeometry3D, Material and Transform. You can simply use 
```
var list = new List<Object3D>();
foreach(var node in scene.Root.Traverse())
{
     if(node is MeshNode m)
     {
            var object3D = new Object3D(){Geometry = m.Geometry, Material = m.Material, Transform = new List<Matrix>()};
            object3D.Transform.Add(m.Transform);
            list.Add(object3D);
     }
}
```

**Comment by Super169** [comment]
> Object3D is basically contains MeshGeometry3D, Material and Transform. You can simply use
> 
> ```
> var list = new List<Object3D>();
> foreach(var node in scene.Root.Traverse())
> {
>      if(node is MeshNode m)
>      {
>             var object3D = new Object3D(){Geometry = m.Geometry, Material = m.Material, Transform = new List<Matrix>()};
>             object3D.Transform.Add(m.Transform);
>             list.Add(object3D);
>      }
> }
> ```

Thanks a lot.

I have modified the program using the suggested code, nut unfortunately, in my case, node is  not MeshNode, so there has nothing added to the list.

Moreover, m.Transform cannot be added to object3D.Transform : cannot convert from 'method group' to 'Matrix'.

**Comment by holance** [comment]
The transform should be `m.ModelMatrix`. What's the node type from your model?

**Comment by Super169** [comment]
Oh, sorry, I have make a mistake before, it should have some meshNode, but just cannot be shown.  

I have changed the code as below,

```
                    foreach (var node in scene.Root.Traverse())
                    {

                        if (node is MeshNode m)
                        {
                            Object3D object3D = new Object3D() { Geometry = m.Geometry, Material = m.Material, Transform = new List<Matrix>() };
                            object3D.Transform.Add(m.ModelMatrix);
                            objList.Add(object3D);
                        }
                    }
```

I use debug to check, it has some object added into objList, but nothing displayed in my program, which works fine using StudioReader as below,

                var reader = new StudioReader();
                objList = reader.Read(stream);

I don't know if it's because I'm still using some old method to display (converted from v1), The following step is what I have been done for display:
1) convert all 3ds model data in byte[] into List<Object3D> 
2) then convert them to List<MeshGeometryModel3D>
3) Add those MeshGeometryModel3D to ObservableElement3DCollection

Is seems that the objList created in this way still have something missing.  Maybe I need to debug to compare the List<Object3D> build from StudioReader and Importer one by one.

**Comment by Super169** [comment]
I just try to build a simple objList using StudioReader and Importer, and save the objList as json.

You can find the original 3ds and the json file of both objList in 
https://raw.githubusercontent.com/Super169/images/master/Others/assimp.zip

The X Y Z position seems not exact matched, but I have searched on the screen for long time, still cannot find the object (this is just a ball).  I guess there may have some other difference which cause the display issue.

**Comment by holance** [comment]
The studio reader did not consider the scene graph from 3DS. It only reads the model local transform. 
Assimp importer imports complete scene graph. 

If you don't need the original scene graph from 3DS, you need to do following:
```
foreach (var node in scene.Root.Traverse())
                    {
                        node.ComputeTransformMatrix();
                        if (node is MeshNode m)
                        {
                            Object3D object3D = new Object3D() { Geometry = m.Geometry, Material = m.Material, Transform = new List<Matrix>() };
                            object3D.Transform.Add(m.TotalModelMatrix);
                            objList.Add(object3D);
                        }
                    }
```

**Comment by holance** [comment]
Also, seems like the normal data in your model are not normalized, that's why there are differences between studio reader and assimp importer. 
Assimp importer imports normal data directly from model file. Studio reader always recalculate the normals.

**Comment by Super169** [comment]
Thanks again for your help.

But it still cannot display the object after adding ComputeTransformMatrix, and changed to use TotalModelMatrix.
I found that, besides of the geometry, the Material is incomplete, I have tested by build the objList with StudioReader and Importer, then copy the Material from StudioReader to Importer, it can show the ball with incorrect size and position.
It seems that they may still have some converstion to get the list of Object3D from scene.

For the 3ds file, actually, it's not build by myself.  
The file is provided by other parties, which is extracted from a FBX file.  Sometime, it may be converted from other 3d format (e.g. Solidworks file), since 3DS is well supported in v1, we have convert object files to 3ds.
In fact, it just need to display the main object, and there has no need to show the scene graph from those 3ds files.

Besdies, I have some 3DS whcih has incorrect display in studioReader, and I need to convert them first.
But now with Importer, they can be opened in proper position directly, so I'd like to use Importer even StudioReader is still available.

**Comment by holance** [comment]
If your model file didn't specify the material type, you may want to set importer.configuration.ImportMaterialType to be the type you want to use.

**Comment by Super169** [comment]
Thanks a lot.

But it seems that it cannot extract the Obejct3D in such simple way, the material information in imported object seems stored in other format, and the Geometry and Transform information is not as expected.  It's not easy for me to build a conversion program on it.  Please let me know if I have missed anything in the conversion.

As my code was developed in v1 years ago, which just make some simple change and migrate to v2 before.  And it's the time for me to study the new features in v2, and I just followed FileLoadDemo to load all related 3ds to build the complete model in SceneNodeGroupModel3D using Importer, it can properly displayed.

However, as I have used Media3D.RotateTransform3D to rotate objects at run-time, it need to study how to convert those logic and apply to the group model.

**Comment by holance** [comment]
You only need to do `SceneNode.ModelMatrix = Media3D.Transform3D.Matrix()` to convert if you still want to use Media3D.Transform3D classes.

**Comment by Super169** [comment]
I am very grateful for your help.  I can now just modify less than 10% of codes, and changed to use the new importer.

However, it seems that the drawing speed is a little bit slower than using Object3D before, is it because scene containing much more information than Object3D.

I have also studied the examples, it seems that assimp importer is not commonly used in the demo, and most of them still using StudioReader to load into the list of Object3D.
Will those demo be converted to use importer later as StudioReader will be obsolete?  If so, maybe I can wait for the new demo as reference.  ^_^

Besides, in our situation, we just need to display the 3ds file as part of the model (a robot), and those 3ds parts need to be transform frequently in run-time.  Will Object3D be better than SceneNode in this case?

**Comment by holance** [comment]
Usually the drawing speed should be the same. Object3D is a pure container, it doesn't do anything except output the mesh and material for MeshGeometry3D or mesh node to use.

If you don't use MVVM to manipulate your model, directly using scene node will have better performance. [Here](https://github.com/helix-toolkit/helix-toolkit/wiki/Use-Element3D-or-SceneNode-under-WPF.SharpDX-or-UWP) explains the difference between scene node and element3D.

Some demos are still using old reader because I don't have time to change them yet.

**Comment by Super169** [comment]
Thanks a lot.
We understand that you're busy on those new features, and it takes time to rewrite those demo.  

But I'd like to ask a silly question, will there be a demo program using assimp importer to load the 3D model and convert it into list of Object3D?   

Although we can easily display and transform using the SceneNode, but there still have many features need to be explored.  For example, when we attempt to display the boundary of a part, we used the Object3D.Geometry.Bound before, but we have checked those bounds-like properties of the SceneNode as well as the MeshNode from Traverse(), we still cannot find the correct boundary.  We concerned that there may have some feature cannot be applied directly.  

It'd be better if there has a sample using assimp importer to load into the list of Object3D, so that we can work with the Object3D as before.

**Comment by holance** [comment]
You can get all geometries after loading your model by using
```
var meshes = root.Traverse().where(x=>x is MeshNode).select(x=>(x as MeshNode).Geometry).ToArray();
```
I am not sure why you need Object3D. It does nothing but contains all geometries after loading the model.

**Comment by Super169** [comment]
Thanks again for your help.

I'm not familiar with graphic programming, in fact, this is my first project on it.  And the project is used to simulate the robot for a robot control system project.
I just start the project from the demo program in v1, and it use StudioReader to load the 3ds into list of Object3D, and then build the ObservableElement3DCollection which has binding to a GroupModel3D in Viewport3DX.  
And I just following this flow to build the project.  As I only know how to use Object3D on it, so I try to convert the SceneNode to Object3D.

I have try getting the boundary from those Bound-like properties, including the BoundsWithTransform, I can only get the size of object, but the position is incorrect even before transformation.
I have also tested the code above, it has the same result as I already tested with the MeshNode from Traverse.

Maybe I have to study the node objects and related demo again to see if I can get the correct boundary or transformed boundary from it.

**Comment by holance** [comment]
Some bounds are updated only after being rendered. You may want to hook up MeshNode.OnBoundChanged event before drawing the bounds

**Comment by Super169** [comment]
Actually, the bounds are used when user requested to show the reference object, it's always checked after rendered.  In fact, the original boundary is good enough for our requirement.

Currently, we use the original Geometry, and then apply the same transform as the object to display its boundary (see red box below).  The boundary box is just displayed for reference, but we need the boundary information to calculate the size of the rotation axis.

![BoundaryAndAxis](https://user-images.githubusercontent.com/3852502/54335474-09681200-4664-11e9-9bf7-31e83c5645c9.png)


The transformed boundary may not be suitable in this case if the object has been rotated.  

Besides, we still investigating how to add a transparent object with SceneNode, although we can put both Element3DPresenter and GroupModel3D at the same Viewport3DX for display, but the transparency object in GroupModel3D is not transparent to objects in Element3DPresenter.

**Comment by holance** [comment]
Transparent object is order dependant. You need to make sure all transparent objects are rendered after opaque objects.

Two ways you can try:
1 mark MeshGeometryModel3D(or meshnode).IsTransparent =true.

2 Manually set RenderOrder property and set Viewport3DX.EnableRenderOrder = true

**Comment by Super169** [comment]
Oh, thanks a lot.
I use to set Material color to make transparent objects (by setting alpha value of DiffuseColor), and I don't know there has such a simple option ^_^.  By setting the IsTransparent, it can be transparent to the SceneNode object now.  
The only outstanding thing is the boundary of object, we may need to study all bounds-like variable in SceneNode, maybe it's hidden inside some variables.

**Comment by Super169** [comment]
You are right that only MeshNode.BoundsWithTransform can provide the correct bound; however, as I need to have the boundary in original position, it must be retrieved right after initial render.  All other bounds-like attributes cannot provide required information.

And I followed your suggestion to obtain the correct boundary from MeshNode.TransformBoundChanged event.  It works fine.

Now we can use SceneNode for all operation we have done using Object3D
1) load the model in 3ds format with Importer (and it support more file format now)
2) transform parts with Transform3D as before 
3) get boundary from MeshNode.BoundsWithTransform, for showing bounds and rotation axis
4) highlight selected parts: cannot assign PostEffects string directly to node, just follow BatchedMeshNodes.cs to convert the string to EffectAttribute, then call AddPostEffect.

As there has no more outstanding issues, it can be closed.

Thanks you very much for developing such a great library!
