### ISSUE TITLE
Undocking and re-docking a panel with a Viewport3DX control demages rendering

### ISSUE THREAD

**Issue by climber03** [helix-toolkit/helix-toolkit#1120]
Hi, i have a dock-window-layout where one panel contains a Viewport3DX control. When the application starts, rendering is working well. When i undock the panel, rendering still works. When i re-dock the panel, the rendering is not working anymore. These are the logs i got from helix-toolkit:

Undocking: 
DX11RenderHostBase.StopRendering: 
DX11RenderHostBase.StartD3D: Width = 1147; Height = 989;
DX11RenderHostBase.StartD3D: RenderHost already Initialized.
DX11RenderHostBase.StartRendering:
DX11RenderHostBase.Resize: Width = 1146; Height = 995;
DX11RenderHostBase.StopRendering:
DX11RenderHostBase.StartRendering:

Re-docking:
DX11RenderHostBase.EndD3D:
DX11RenderHostBase.StopRendering:
DefaultRenderHost.OnEndingD3D:
DX11RenderHostBase.DetachRenderable:
DX11RenderHostBase.DisposeBuffers:
DX11RenderHostBase.EndD3D:
DX11RenderHostBase.StopRendering:
DefaultRenderHost.OnEndingD3D:
DX11RenderHostBase.DetachRenderable:
DX11RenderHostBase.DisposeBuffers:

Has anyone an idea how i can fix this problem or where i should start searching?

Thanks,
Michael

**Comment by holance** [comment]
Are you be able to create a simple demo project to show this issue?

**Comment by climber03** [comment]
Hi, we are using a docking-manager which is in a proprietary library, so i can't give you an exact example. I tried to repro the issue with AvalonDock from xceed, but without success. So i am not sure if this is a bug in our implementation, in the docking-system or in helix toolkit. Do you have any suggestions where i can start searching?

Thanks!

**Comment by holance** [comment]
After docking, try to check if the data context is still correct.

**Comment by climber03** [comment]
The data context is still correct, its a singleton viewmodel which is not destroyed (e.g. Dispose is not called when a docking-operation occurred). When i do a docking-operation i get the unloaded and loaded event of the Viewport3DX control. Is there any possibility where i can re-initialize the viewport3dx control?

**Comment by holance** [comment]
You may want to download the source code and do some debugging.  From the log, it happens only when Viewport3DX is unloaded and its datacontext = null. You can try to put a break point on HelixToolkit.Wpf.SharpDX\Controls\DPFCanvas.cs line 156.

**Comment by climber03** [comment]
Now i have some more information from the dock-manager manufacturer, does this help?

"When a panel is undocked it's moved from one visual tree part to another. Moreover, if you are using the Desktop floating mode, panels will be moved to a separate visual tree once you undock them. It's impossible to prevent a control from being unloaded when such operations are performed."

**Comment by holance** [comment]
I checked in a fix, let me know if it works or not.

**Comment by climber03** [comment]
Hi, thanks for your help! I tried your solution, but without success. I got the same logs as before. I put a break point in the method EndD3D to see from where the method is called. Here is the call-stack:
![grafik](https://user-images.githubusercontent.com/18352639/57213533-65597200-6fe7-11e9-984a-6f06a4b5374f.png)

EndD3D is called from ParentWindow_Closed...

**Comment by holance** [comment]
Seems like the docking changes its parent window?

**Comment by PChristophe** [comment]
I'd like to reopen this topic, would it be alright if I suggest a merge request that brings an option to let us manage what happens if the "first" parent window closes? 
I'm facing the same issue, I'm working on a app that has docking mechanisms and this behavior that calls EndD3D turns out as a real issue in this configuration.

**Comment by holance** [comment]
Welcome to do PR if you want to change the behavior.
