### ISSUE TITLE
BatchedMeshGeometry not working with ColorStripeMaterial and VertColorMaterial

### ISSUE THREAD

**Issue by mathcalvo** [helix-toolkit/helix-toolkit#1122]
I am trying to represent a 3D structural calculation model of a building. Each beam is an extruded section (like a pipe, hollow section, I beam...) and should have a color gradient representing some calculation results. There are around 10000 beams, each of them made of ~10-20 triangles with unique color representation.

I am new with Helix (SharpDX) and tried different things:
 - GroupModel3D with a ObservableElement3DCollection of MeshGeometryModel3D for each beam with its own ColorStripeMaterial / VertColorMaterial => slow
 - ItemsModel3D with a ObservalbeCollection of Element3D (MeshGeometryModel3D) for each beam with its own ColorStripeMaterial / VertColorMaterial => slow
 - BatchedMeshGeometryModel3D is quick but seems not to support neither ColorStripeMaterial nor VertColorMaterial
![image](https://user-images.githubusercontent.com/23194589/54489596-33ad1000-48ae-11e9-944e-97f7ae83a192.png)
[Example.zip](https://github.com/helix-toolkit/helix-toolkit/files/2975057/Example.zip)

Maybe BatchedMeshGeometryModel3D is not adapted for this task? I must admit that I don't really check the difference between all the GroupModel3D / ItemsModel3D / BatchedMeshGeometryModel3D. 3D rendering is a new topic to me. 

Is there another way to perform this task with better performance? One unique material for all meshes with one texture representing the color map of the ratio, and use texture coordinates?
I must implement an hit test as well. Between GroupModel3D / ItemsModel3D / BatchedMeshGeometryModel3D, is one of them better for this?

Thanks!

**Comment by holance** [comment]
BatchedMeshGeometryModel3D only works for PhongMaterial for now.
You can create a separate module to merge your model into single one and keep a map with the range of indices for each sub mesh. After you get the hit test, you can get the triangle index from hit test and search the map to get which sub mesh is hitted.

**Comment by mathcalvo** [comment]
OK thank you I will try to implement this.
