### ISSUE TITLE
[SharpDX] Surface normals estimation from point cloud

### ISSUE THREAD

**Issue by Jamaslab** [helix-toolkit/helix-toolkit#1123]
Hello,
is it possible with Helix+SharpDX to estimate surface normals from a PointGeometry3D?

Thank you!

**Comment by holance** [comment]
What exactly do you want to achieve?

**Comment by Jamaslab** [comment]
I'd like to obtain something like this

http://pointclouds.org/documentation/tutorials/normal_estimation.php

**Comment by holance** [comment]
You can implement [this](http://pointclouds.org/documentation/tutorials/normal_estimation.php) algorithm yourself. It is pure CPU calculation, does not related to rendering at all. You don't really need HelixToolkit for normal calculation.
