### ISSUE TITLE
2DControl crash with SharpDX

### ISSUE THREAD

**Issue by gregorsGit** [helix-toolkit/helix-toolkit#1125]
Hi,
I use a Content2D over the viewport and add/change a Canvas2D on it.
(latest nuget-package)

Sometimes i get this exception.
SharpDX.SharpDXException: HRESULT: [0x88990001], Module: [SharpDX.Direct2D1], ApiCode: [D2DERR_WRONG_STATE/WrongState], Message: Das Objekt befand sich nicht im richtigen Status, um die Methode zu verarbeiten.
   bei SharpDX.Result.CheckError()
   bei HelixToolkit.Wpf.SharpDX.Render.DefaultRenderHost.OnRender2D(TimeSpan time)
   bei HelixToolkit.Wpf.SharpDX.Render.DX11RenderHostBase.UpdateAndRender()

Can you see anything in this dump?
Thanks.

**Comment by holance** [comment]
Are you be able to create a sample demo to reproduce this issue?

**Comment by gregorsGit** [comment]
Hi, 
a sample demo is not so easy. 
![grafik](https://user-images.githubusercontent.com/34306200/57682818-db3a8a80-7632-11e9-87bb-59cdad1066c9.png)
I my project there is an "overview" using SharedModelContainer.
I can reproduce it on my system with version 2.7.0.0.

**Comment by gregorsGit** [comment]
Hi,
it happens when the hx2D-Control is outside the viewer. A negative Margin (-200,-200,....).....
To reproduce it:
change in generic.xaml 
 <hx2D:StackPanel2D
                                x:Name="PART_TitleView"
                                Margin="-1000,-1000,0,0"

and start octreedemo.
