### ISSUE TITLE
Domain name expiring

### ISSUE THREAD

**Issue by objorke** [helix-toolkit/helix-toolkit#1126]
The domain name https://www.helix-toolkit.org/ is expiring April 7. 
The custom domain is currently pointing to https://helix-toolkit.github.io

1. Does someone want to renew the domain name? Or should we let it expire and use github.io instead?
2. Could the content be moved to the github wiki instead?

**Comment by holance** [comment]
I will take care of the domain. How would you like to proceed?

**Comment by objorke** [comment]
Great! I will unlock the domain and send you an auth/EPP code.

**Comment by holance** [comment]
Transfer pending, thanks.
