### ISSUE TITLE
Nuget package version issue

### ISSUE THREAD

**Issue by twsI** [helix-toolkit/helix-toolkit#1127]
Version 2.7.0-alpha0362 was published on 14.02.2019 to myget, yet there is 2.7.0-alpha0115 pushlished today (20.03.2019). Seems to be an issue with GitVersion. This is quite confusing, since I doesn't get the latest update news automatically, so please investigate.

**Comment by holance** [comment]
Seems like this issue is caused by the hotfix.
@objorke Are you be able to delete the old packages from myget feed? From alpha0310 to alpha0362.
Thanks.

**Comment by objorke** [comment]
I deleted all packages in the range alpha0310-0362
