### ISSUE TITLE
GroupNodeBase.AddChildNode(SceneNode) doesn't add childs

### ISSUE THREAD

**Issue by twsI** [helix-toolkit/helix-toolkit#1129]
I'm using the same code as in the [FileLoad Demo](https://github.com/helix-toolkit/helix-toolkit/blob/develop/Source/Examples/WPF.SharpDX/FileLoadDemo/MainViewModel.cs), yet when using the latest nuget package v2.7.0-alpha0115, there is nothing added to `GroupModel.GroupNode`
 [here](https://github.com/helix-toolkit/helix-toolkit/blob/develop/Source/Examples/WPF.SharpDX/FileLoadDemo/MainViewModel.cs#L230), eventho `Scene.Root` is of Type `HelixToolkit.Wpf.SharpDX.Model.Scene.GroupNode`. Both GroupNode and SceneNode have a child count of zero afterwards. The very same code is working with v2.6.1

**Comment by holance** [comment]
I don't think there is any changes from 2.6.1 to 2.7.0 on GroupNode. And the demo works fine for me. Are you be able to load model using the FileLoad Demo?
