### ISSUE TITLE
Reducing SharpDX idle load.

### ISSUE THREAD

**Issue by smischke** [helix-toolkit/helix-toolkit#113]
I'd like to reduce the idle CPU / GPU load of Viewport3DX by only rendering if something actually changed, i.e making it more event driven like the WPF3D version. The idle load can be quite high with large scenes. I'd make it selective via something like "Viewport3DX.IsRenderingEventDriven" which would be false by default (at first).

Would you accept such a change?

**Comment by przem321** [comment]
I would agree---I guess you know what you are doing. P.

**Comment by objorke** [comment]
Sounds good to me!

**Comment by smischke** [comment]
The pull request is a "minimally invasive" version. I don't want to make too many changes at a time. The main difference is the separation of Update() and Render(). As far as I can see, this has no impact on the engine. 

I have a more invasive version which makes Viweport3DX and DPFCanvas use the same (weak) RenderingEventListener and use the same timestamp as WPF from RenderingEventArgs (no separate StopWatch). 

In the most invasive version, I even unregister from rendering events if nothing changes. This breaks the game engine like design because Update() is not called in a "game loop" but on invalidation. This version also works, but I don't know if you want that. The benefit is only noticeable on large scene graphs without animation.
