### ISSUE TITLE
Rotating object

### ISSUE THREAD

**Issue by kdraper1961** [helix-toolkit/helix-toolkit#1131]
I've download a couple of examples and built my own projects. I start the program. The object renders and then I try to rotate it using the control in the bottom right hand corner. It rotates once and then will not rotate again. This is happening on all the projects I've tried. I fill like I'm missing something simple.

**Comment by holance** [comment]
You mean the view cube? It rotate the cube face you clicked to screen. If you keep clicking the same face again, nothing will happen because the face already facing the screen.

**Comment by kdraper1961** [comment]
Thanks. I figured it out. I new it was user error. I tried for an hour and could figure out how o do it.
