### ISSUE TITLE
Different Figure for each point in PointGeometryModel3D

### ISSUE THREAD

**Issue by manojsakhare** [helix-toolkit/helix-toolkit#1132]
How we can add different figures (ellipse, rectangle, cross) for individual points within a single geometry or geometry model?

Currently I need to create different geometries for different shape of the point.

**Comment by smischke** [comment]
This would only be possible if Figure(Ratio) was a per vertex variable (buffer) rather than a material variable.

**Comment by manojsakhare** [comment]
Do we have any sample application/code for custom shader?

**Comment by holance** [comment]
Do you need to display these figures always facing the camera or with constant size? Or just a piece of geometry in space.

If you only need to display figure like a piece of geometry in space, you can use texture with all the figures in it and uses quads to display figures in space.

Otherwise you can also try to use billboardImage3D with figure texture to display different figures if you need to display them always facing camera.

**Comment by manojsakhare** [comment]
If you only need to display figure like a piece of geometry in space, you can use texture with all the figures in it and uses quads to display figures in space.
-->
Yes, its a piece of geometry in space... could you please explain more about texture, figures and quads? Do you have any sample app?

**Comment by holance** [comment]
Many demos with texture are using Texture coordinates. You may want to understand how texture coordinate works first. There are many materials online.

**Comment by donggas90** [comment]
I think, this issue needs custom input layout to specify what vertex should be(ellipse, rectangle, cross etc.) and metadata(radius of ellipses etc.). This cannot covered by the constant buffer and geometry shader needed to generate meshes from a vertex.

This approach is pretty rare, so many high-level APIs do not provide them to implement. I think, implement custom renderer from `SharpDX` can be better than just using `Helix toolkit` if you need more rare approaches.

**Comment by haruby511** [comment]
I think, this issue needs custom input layout to specify what vertex should be(ellipse, rectangle, cross etc.) and metadata(radius of ellipses etc.). This cannot covered by the constant buffer and geometry shader needed to generate meshes from a vertex.

This approach is pretty rare, so many high-level APIs do not provide them to implement. I think, implement custom renderer from SharpDX can be better than just using Helix toolkit if you need more rare approaches.
