### ISSUE TITLE
Changes applied to viewer event

### ISSUE THREAD

**Issue by MiroslavJ** [helix-toolkit/helix-toolkit#1134]
Hi guys,
I am working with SharpDX in WPF. Is there any event that will tell me when the viewer is updated? I saw that if I change something like camera position for example the new value in camera's property "Position" is there but on the viewer my camera is still on the same position. I think it's working asynchronously. I tried "Rendered" and "LayoutUpdated" events but I've seen that even when my viewer is updated these events are still triggering. Thanks for help.

**Comment by holance** [comment]
Usually you can use Rendered event. Or you can try to use a dispatcher.beginInvoke with a background priority.

**Comment by MiroslavJ** [comment]
Thank you Holance.
