### ISSUE TITLE
More winform examples

### ISSUE THREAD

**Issue by XuequanZhang** [helix-toolkit/helix-toolkit#1135]
Hello! Since the main 3d classes are packaged into the Core library, the tool should also apply to winform programming. I hope more winform examples can be provided, which will be helpful for those who want to apply helix-toolkit in winform software. Thank you!

**Comment by holance** [comment]
Usage for winform should be the same as other platforms. The core tester is using winform. Most of the functionalities are included in the tester already. If you have any questions, please feel free to ask in the chat room.

**Comment by XuequanZhang** [comment]
> Usage for winform should be the same as other platforms. The [core tester](https://github.com/helix-toolkit/helix-toolkit/tree/develop/Source/Examples/SharpDX.Core/CoreTest) is using winform. Most of the functionalities are included in the tester already. If you have any questions, please feel free to ask in the chat room.

Thank you very much for your prompt reply. I wrote a 3d virtual globe software with winform using sharpdx, and I want to integrate it with helix-toolkit now. The core tester has some simple examples using winform, but most complex features (such as volume rendering) are based on WPF.SharpDX. Would you like to ask, is there any good advice? How to integrate them with the least amount of work? Thanks again!

**Comment by holance** [comment]
You can also use similar code to do volume in Core. All WPF.SharpDX models are just a wrapper to the core projects. So anything WPF.SharpDX can do, it can do in Core project.
For example, for volume rendering, you can use `VolumeTextureNode` with `VolumeTextureDDS3DMaterialCore` or `VolumeTextureRawDataMaterialCore` materials in your winform project.

**Comment by XuequanZhang** [comment]
> You can also use similar code to do volume in Core. All WPF.SharpDX models are just a wrapper to the core projects. So anything WPF.SharpDX can do, it can be done in Core project.
> 
> For example, for volume rendering, you can use `VolumeTextureNode` with `VolumeTextureDDS3DMaterialCore` or `VolumeTextureRawDataMaterialCore` materials in your winform project.

I see. Thank you very much for your detailed reply!
