### ISSUE TITLE
.NET Core 3 WPF Support

### ISSUE THREAD

**Issue by inf9144** [helix-toolkit/helix-toolkit#1137]
Hey,
are there plans to support .NET Core 3 as it supports WPF now?
Would be really great. I am porting a few of my projects.

Thanks!

**Comment by holance** [comment]
Currently core 3 is still in preview. Will support it once stable release comes out.

**Comment by MagicUrban** [comment]
Thank you! Can you recommand 3D procedual geometry modeling library in .net core for Linux? Best wishes.
