### ISSUE TITLE
No Rendering Definition Helixtoolkit WPF SharpDX

### ISSUE THREAD

**Issue by bVess12** [helix-toolkit/helix-toolkit#1138]
![Example02](https://user-images.githubusercontent.com/43218369/56157956-c664cb80-5f8e-11e9-9228-4bc5862461ff.PNG)
![Example01](https://user-images.githubusercontent.com/43218369/56157957-c664cb80-5f8e-11e9-9841-31aeaa6e8007.PNG)

I'm creating a MeshGeometry3D and a Material.  The problem I am having is that it is always rendered as a flat plane.  The MeshGeometry3D is a raised flat section on a flat plane, as I have tried to highlight in the example images.

The material I am using is PhongMaterials.Blue, and I am using a DirectionalLight3D.  I experience no change when using ambient lighting.  After creating the MeshGeometry3D, I call CalculateNormals, though this seems to have no effect.  I have been unsuccessful in finding this online.  Does anyone know what's going on?

Thank you

**Comment by bVess12** [comment]
This is in HelixToolkit WPF SharpDX

**Comment by bVess12** [comment]
<hx:Viewport3DX  x:Name="Viewport3Dx" Grid.Row="1" Grid.Column="0" ShowCameraInfo="True" BackgroundColor="SlateGray" EffectsManager="{Binding EffectsManager}" UseDefaultGestures="False" >

            
            <hx:Viewport3DX.InputBindings>
                <MouseBinding Gesture="RightClick" Command="hx:ViewportCommands.Rotate"/>
                <MouseBinding Gesture="MiddleClick" Command="hx:ViewportCommands.Pan"/>
                <MouseBinding Gesture="Shift+RightClick"  Command="hx:ViewportCommands.Zoom"/>
            </hx:Viewport3DX.InputBindings>

            
            <hx:Viewport3DX.ModelUpDirection>
                <Vector3D X="0" Y="0" Z="1"/>
            </hx:Viewport3DX.ModelUpDirection>
            <hx:AmbientLight3D Color="White"/>
            <hx:DirectionalLight3D Color="White" Direction="-10,-10,-10"/>

            
            <hx:MeshGeometryModel3D 
                FillMode="Solid"
                Geometry="{Binding MeshModel}"
                Material="{Binding MeshMaterial}"
                WireframeColor="AliceBlue"/>

**Comment by bVess12** [comment]
Here's how I'm creating the model:

//Called in the viewport viewmodel
{
            //Create the Material
            this.MeshMaterial = PhongMaterials.Blue;
            float[,] Test = new float[250, 250];
            for (int x = 85; x < 200; x++)
                for (int y = 85; y < 200; y++)
                    Test[x, y] = 1.5f;
            CreateFromArray(Test, 0.025f, 0.025f);
}
private static int ReturnAsIndex(int x, int y, int width)
        {
            return x + y * width;
        }
        private void CreateFromArray(float[,] Heights, float xSpacing, float ySpacing)
        {
            Vector3Collection PolygonPoints = new Vector3Collection();
            Vector3Collection Normals = new Vector3Collection();
            int width = Heights.GetLength(0), height = Heights.GetLength(1);
            for (int y = 0; y < height; y++)
            {
                float yOffset = y * xSpacing;
                for (int x = 0; x < width; x++)
                {
                    PolygonPoints.Add(new Point3D(x * xSpacing, yOffset, Heights[x, y]));
                    Normals.Add(new Point3D(0, 1, 0));
                }
            }

            List<int> Indices = new List<int>();
            for (int y = 0; y < height - 1; y++)
                for (int x = 0; x < width - 1; x++)
                {
                    //Add the top-left triangle
                    Indices.Add(ReturnAsIndex(x, y, width));
                    Indices.Add(ReturnAsIndex(x + 1, y + 1, width));
                    Indices.Add(ReturnAsIndex(x, y + 1, width));

                    //Add the bottom-right triangle
                    Indices.Add(ReturnAsIndex(x, y, width));
                    Indices.Add(ReturnAsIndex(x + 1, y, width));
                    Indices.Add(ReturnAsIndex(x + 1, y + 1, width));
                }
            
            // Generate the Output
            var geometry = new HelixToolkit.Wpf.SharpDX.MeshGeometry3D();

            //geometry.PreDefinedIndexCount = Indices.Count;
            //geometry.PreDefinedVertexCount = PolygonPoints.Count;

            geometry.IsDynamic = true;
            geometry.Positions = PolygonPoints;
            geometry.Normals = Normals;
            geometry.Indices = new IntCollection(Indices);

            geometry.TextureCoordinates = new Vector2Collection(PolygonPoints.Count);
            
            MeshModel = geometry;
        }

**Comment by holance** [comment]
If you can upload a demo project, will be more helpful.

**Comment by holance** [comment]
Did you try `MeshModel.Normals = MeshModel.CalculateNormals();`

**Comment by bVess12** [comment]
I am a complete idiot. I thought CalculateNormals() was void. I tried the solution and it fixed it like a charm.  ...I've been staring at my screen without realizing this for far longer than I'd like to admit.
![Example03](https://user-images.githubusercontent.com/43218369/56168212-70048680-5fa8-11e9-89c6-ae0c630023bf.PNG)


Thank you very much, and sorry to bother you!
