### ISSUE TITLE
Get the corner coordinates of cube created by LineBuilder.AddCube().

### ISSUE THREAD

**Issue by manojsakhare** [helix-toolkit/helix-toolkit#1139]
The cube is transformed and rotated after the creation. LineGeometryModel3D is added to view port. This geometry is transformed using Trasform property, both rotation and translation transform is used. Once the transformation is done, I would like to get the corner co-ordinates values. 
I tried BoundsWithTransform.GetCorners() and Bounds.GetCorners(), but they are not the correct values.

**Comment by holance** [comment]
`WorldCoordinate = LocalCoordinate * Model3D.SceneNode.TotalModelTransform`.
