### ISSUE TITLE
Zoom in is locked at certain distance

### ISSUE THREAD

**Issue by manojsakhare** [helix-toolkit/helix-toolkit#1144]
I am not setting ZoomDistanceLimitNear property... when I zoom in, at certain zoom level, zooming in stops. I am not what caused this behavior. It started happening after I upgraded SharpDx version to 4.2.0

**Comment by holance** [comment]
Zoom always have a limit due to floating point accuracy. If your model is too small, you may want to use transform to scale it. Or try to change camera mode to walk around.
