### ISSUE TITLE
PInvokeStackImbalance

### ISSUE THREAD

**Issue by EmTschi** [helix-toolkit/helix-toolkit#1149]
Hi!

I had an exeption when i start my program:

_Assistent für verwaltetes Debuggen "PInvokeStackImbalance" 
Nachricht = Assistent für verwaltetes Debuggen "PInvokeStackImbalance" : "Ein Aufruf an die PInvoke-Funktion "HelixToolkit.Wpf.SharpDX!HelixToolkit.Wpf.SharpDX.VirtualTouchDevice::RegisterTouchWindow" hat das Gleichgewicht des Stapels gestört. Wahrscheinlich stimmt die verwaltete PInvoke-Signatur nicht mit der nicht verwalteten Zielsignatur überein. Überprüfen Sie, ob die Aufrufkonvention und die Parameter der PInvoke-Signatur mit der nicht verwalteten Zielsignatur übereinstimmen."_

The exeption was throwed in RenderControl.cs at:
```c#
78        protected override void OnHandleCreated(EventArgs e)
79        {
80            base.OnHandleCreated(e);
81            if (this.hostVisual != null)
82            {
83                VirtualTouchDevice.RegisterTouchWindow(this.Handle, 0);   <--- Exeption
84            }
85        }
```

To eliminate the exeption i changed in VirtualTouchDevice.cs:
```c#
31        [DllImport("user32")]
32        [return: MarshalAs(UnmanagedType.Bool)]
33        public static extern bool RegisterTouchWindow(IntPtr hWnd, ulong ulFlags);
```
to:
```c#
31        [DllImport("user32")]
32        [return: MarshalAs(UnmanagedType.Bool)]
33        public static extern bool RegisterTouchWindow(IntPtr hWnd, int ulFlags);
```

In the examples i dont had exeptions...

specs: Windows10, VS2019 Community, Net 4.5.2
The viewport is hosted in an User Control which will be loaded in the MainWindow.

**Comment by smischke** [comment]
It should be uint since ulong is always 64 bit in c#. Thanks for reporting this bug.
