### ISSUE TITLE
Reduce Sharp-DX version touch input lag

### ISSUE THREAD

**Issue by mortalV** [helix-toolkit/helix-toolkit#115]
Hello. 

I've load complex obj model. 
When rotate, move or zoom model I see input lag. 
Sometimes all is OK but more frequently model not smooth moving but jumping.
When run LookAt method animation good - so GPU can render with needed FPS.
Manipulations by mouse more comfortable and close to LookAt method but not the same.
Sometimes mouse also have lag but at start (around 500 ms) and than continue working .

Is it possible to make the touch control more responsive? It's so important for me because all my soft using touch control.

Many thanks for great library and sorry for ugly english.

P.S. I've see some solution for SharpDXElement - https://github.com/sharpdx/SharpDX/issues/97
Maybe problem the same.

**Comment by objorke** [comment]
thanks for the link to the SharpDX issue!

**Comment by smischke** [comment]
Nice finding!

**Comment by smischke** [comment]
The solution that @mortalV pointed out (using BeginInvoke()) made LightingDemo stutter when running at 60 fps, so I took a different approach. You can simulate a big scene by putting Thread.Sleep(30) in the Render() method.

**Comment by objorke** [comment]
@mortalV can you test the latest version with the changes from @smischke? does this solve the issue?

**Comment by mortalV** [comment]
I've look latest version. 
Mouse working good - very close to LookAt method but Touch still jumping (better than previous version but jumping)
Maybe make some video for demonstration touch problem?

**Comment by smischke** [comment]
@mortalV: Could you please explain what you mean by "LookAt method". How / where is LookAt() invoked?

The problem is: If a single Render() call takes long, we can't do anything about it. All we can do is making sure the next Render() call will return immediately to give input some time. I'll make the Threshold for "immediate return" accessible (20 ms hard coded atm).

**Comment by mortalV** [comment]
I have button which return obj model to start coords by call LookAt Camera method with animation.
I see animation is smooth so render on GPU fast enough and mouse now working  good
But touch manipulation sometimes ok sometimes jumps.

I can make video how it works if it help.
P.S. CPU is Core i5, GPU Intel HD4000

**Comment by smischke** [comment]
@mortalV: I've created a pull request. Please check if the changes improve / fix your issue. 
https://github.com/helix-toolkit/helix-toolkit/pull/119

**Comment by mortalV** [comment]
Stefan, I'll try your fix when it will be available in repository.
I've make all Render calls over BeginInvoke and with this solution was problems with Camera position synchronization - model moved but Camera obj return coords with lag.
Maybe your complex solution will be better.
Anyway thanks for your help.

**Comment by ALavallee** [comment]
Is a fix or a workaround available for the Viewport3DX?  On a Intel chipset, a simple mouse rotation can make a very simple scene (a cube with a light) laggy has hell. (10 fps and below)
