### ISSUE TITLE
Manual Hit Test for binded commands

### ISSUE THREAD

**Issue by MrJox** [helix-toolkit/helix-toolkit#1159]
I have a toolbar with a list of tools. Each tool has it's own command (can be defined anywhere in code). This command binds to left mouse click of viewport:
`<MouseBinding Gesture="LeftClick"/>`

In a way like this:
`viewport.InputBindings[4].Command = tool.Command;`

I know this is kind of weird but this MVVM architecture sometimes messy when you try to make different VM work together (example toolbar VM, viewport VM, sidebar VM etc).

So the problem is that my command looks like this:
```
       public void SelectCell() {
            int index = PASSED_PARAMETER;
            HexGridGeometry.Colors[index + 0] = new SharpDX.Color4(0, 0, 0, 1);
            HexGridGeometry.Colors[index + 1] = new SharpDX.Color4(0, 0, 0, 1);
            HexGridGeometry.Colors[index + 2] = new SharpDX.Color4(0, 0, 0, 1);
            HexGridGeometry.Colors[index + 3] = new SharpDX.Color4(0, 0, 0, 1);
            HexGridGeometry.Colors[index + 4] = new SharpDX.Color4(0, 0, 0, 1);
            HexGridGeometry.Colors[index + 5] = new SharpDX.Color4(0, 0, 0, 1);
            OnPropertyChanged(nameof(HexGridGeometry));
        }
```

And the idea was to pass the mouse click position in world coordinates to find the cell index and then change that cell's colour to black. However I don't have any ideas how to tie everything together and this feels like it needs a total refractoring.

What would you suggest me to do/how to fix it?
The goal is to attach different viewport actions to different toolbar tools so I can paint over my hex grid, select grid cells etc (using left mouse click)

**Comment by holance** [comment]
If you are having trouble using MVVM, then don't use it. To find hit, use Viewport3DX.FindHit with your mouse position in viewport. You can use e.GetPosition(viewport) in MouseButtonEvent to get the 2D coordinate of the mouse in viewport, then pass into FindHit.
