### ISSUE TITLE
Directly changing vertex color does not have any effect

### ISSUE THREAD

**Issue by MrJox** [helix-toolkit/helix-toolkit#1160]
I'm using vertex colour material to render the hexmap.
Here's a code snippet how I directly attempt to change vertex colours:
```
        public void UpdateGridColour(Color4 newColour, int index) {
            HexGridGeometry.Colors[index + 0] = newColour;
            HexGridGeometry.Colors[index + 1] = newColour;
            HexGridGeometry.Colors[index + 2] = newColour;
            HexGridGeometry.Colors[index + 3] = newColour;
            HexGridGeometry.Colors[index + 4] = newColour;
            HexGridGeometry.Colors[index + 5] = newColour;
            OnPropertyChanged(nameof(HexGridGeometry));
        }
```
Calling UpdateColors() explicitly does not make any effect either.
Is this a bug?

**Comment by holance** [comment]
Call Geometry3D.UpdateColors() works fine for me. If you are still having trouble, create a simple demo, so I can check why it is not working on your side.

**Comment by MrJox** [comment]
So I received help which helped me to fix it by applying a "hack" by locally storing the colours array and setting geometry.colours to null, then doing my modification over the local array and assigning it back to geometry.colours.
This is caused due to references comparison in this code chunk:

```
protected bool Set<T>(ref T backingField, T value, [CallerMemberName] string propertyName = "")
            {
                if (EqualityComparer<T>.Default.Equals(backingField, value))
                {
                    return false;
                }

                backingField = value;
                this.RaisePropertyChanged(propertyName);
                return true;
            }
```

EqualityComparer compares references, so whether its one item or 99% of items were changed, the memory address remains still hence code thinks nothing's changed.
Forcing to update colours without "the hack" does the job, though.

**Comment by holance** [comment]
This will work as well.
