### ISSUE TITLE
Camera "teleports" huge distance when panning/rotating

### ISSUE THREAD

**Issue by GaroRobe** [helix-toolkit/helix-toolkit#1161]
Hello,

In Helix Toolkit 2.6.0 I'm having an issue in Viewport3DX containing (relatively) large point cloud (~30'000 points): 

When actively panning/rotating/zooming, at some point I'm having a huge spike in camera shift - it moves for around 99 units (in absolute values), when usual position change is around fractions of 1.
As a result, all the points disappear from view.

Does anyone have any idea why I could have this?

**Comment by holance** [comment]
Try to set Viewport3DX.IsInertiaEnabled = false. Test if this issue is still happening.

**Comment by GaroRobe** [comment]
Thanks for reply.

I tried. It didn't help.

I just tried to show you what it's like but it really is unreliable. Like, at one moment I'm close to a red cube (it marks an origin in our case):
![image](https://user-images.githubusercontent.com/2609826/58008916-0bcc6980-7af6-11e9-84b7-4407f77570ea.png)

And then everything is white and camera flew away:
![image](https://user-images.githubusercontent.com/2609826/58008882-fce5b700-7af5-11e9-8b42-8e23247b5aa5.png)

Any more ideas?

**Comment by holance** [comment]
Upload a demo, so I can take a look the view port setup. Also, are you getting frame rate drop while this issue happening?

**Comment by GaroRobe** [comment]
Hi,

Here's the demo:
[SharpDxApp.zip](https://github.com/helix-toolkit/helix-toolkit/files/3208013/SharpDxApp.zip)

The issue is not numerically equal to what  I get on production data, but otherwise similar and esily reproduced if we do zoom, pan and rotate operations in combination. 

Here are some screencasts as illustrations:
[HelixCameraIssue_WithoutZoomLimits.mp4](http://cloud.garorobe.win/index.php/s/FT9NtXnexaMy49r)
[HelixCameraIssue_WithZoomLimits.mp4](http://cloud.garorobe.win/index.php/s/jpkXCFrnPkrwgj9)

P.S.: My hunch is that I'm missing something regarding how ortho cam works and what reasonable limitations I must introduce when using it. Is there some good source of information on the topic you could've recommend?

**Comment by holance** [comment]
Should be fixed in 6c031d0.

There is another issues I noticed in your code. First, the point range is way too big. Keep in mind of the floating point precision. Range should be limited. Use scale transform to limit your point range into smaller range. Limit the camera near plane and far plane distance.

There is bug in default near plane distance to be negative, which has been fixed in 6c031d0 as well. You can manually set the near plane distance to a reasonable value.
