### ISSUE TITLE
SharpDX. Image of my own coordinate systems.

### ISSUE THREAD

**Issue by Dmitrii2018** [helix-toolkit/helix-toolkit#1165]
Hi. I am working in HelixToolkit.Wpf.SharpDX. I need to display users coordinate systems in HelixToolkit style. For example: there are several coordinate systems in 3D space. I want to display their on its own positions. And images of coordinate systems should not change size, but change their positions when zooming. Does anyone have any idea how to implement this. I think, I have to manage projection of 3D vectors (users coordinates system) to 2D screen.

**Comment by holance** [comment]
Let me know if this is what you want. You can refer to custom view cube demo for details. 
Reopen this issue if necessary.

**Comment by Dmitrii2018** [comment]
No. I want to see something like this:
![1](https://user-images.githubusercontent.com/38795704/58545765-9efb5280-820c-11e9-8d0e-25b762ea7220.png)

**Comment by holance** [comment]
Take a look the coordinate inside the demo, I believe it is exactly what you want.

**Comment by Dmitrii2018** [comment]
Thank you very much. It's exactly what I need.
