### ISSUE TITLE
Viewport3DX is black, EffectManger throw null reference exception

### ISSUE THREAD

**Issue by MexicanMan** [helix-toolkit/helix-toolkit#1168]
Hello,
I try to use SharpDX and when I add to WPF a Viewport3DX I see only black screen. If I add default event manager to it as it was done in demos, it also start to throw something like the next exception:
```
DPFCanvas: Error during rendering: Object reference not set to an instance of an object:
StackTrace: 
in HelixToolkit.Wpf.SharpDX.Render.DX11RenderHostBaseResize(Int32 width, Int32 height)
in HelixToolkit.Wpf.SharpDX.DPFCanvas<OnRenderSizeChanged>b__22_0()
```
What's wrong?

**Comment by holance** [comment]
Upload a demo would be very helpful.

**Comment by MexicanMan** [comment]
Sure: https://github.com/MexicanMan/SharpDXTest
This is actually SimpleDemo without image and placed all in one project
