### ISSUE TITLE
Change ObjReader for big smoothing groups

### ISSUE THREAD

**Issue by mortalV** [helix-toolkit/helix-toolkit#117]
Some exported obj models for smoothing groups using too big values for int variable
I've changed to 
private readonly Dictionary<long, Dictionary<int, int>> smoothingGroupMaps;

My models now fine loading.
Can you make this modification for ObjReader.cs?
SharpDX version if it's important.
Thanks.

**Comment by objorke** [comment]
Yes, please create a PR
