### ISSUE TITLE
Manipulation with RightMouse not expected

### ISSUE THREAD

**Issue by gregorsGit** [helix-toolkit/helix-toolkit#1175]
Hi,

I use the UITranslateManipulator3D like in the SharpDX-Manipulation-Demo.
Now when I try to rotate/zoom with the middel- or right-mouse the objects are moved/manipulated too.
This is not what I expect.
Is it possible to disable events on middel and right mouse on a UITranslateManipulator3D.

What is the best way for disable this?
Thanks.

**Comment by holance** [comment]
Copy the source code in your own project, implement the mouse button test.
