### ISSUE TITLE
c++ application

### ISSUE THREAD

**Issue by goldv72** [helix-toolkit/helix-toolkit#1186]
Hello!
I created c++ CLR console application for manadged code and unmanadged legacy code
installation helixtoolkit.wpf.sharpdx nuget pack failed with message
"Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'HelixToolkit 2.8.0'. You are trying to install this package into a project that targets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."	
what I sould to do with my app?

**Comment by holance** [comment]
You need dot net 4.5 project with WPF support to use HelixToolkit. You need to create a CLR library or use PInvoke to wrap your c++ function and create a separate WPF project to call your library.

**Comment by goldv72** [comment]
Thanks for answer.
i solved it
1.  create clr c++ application/DLL
2. Add to project file packages.config  like this
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Cyotek.Drawing.BitmapFont" version="1.3.4" targetFramework="net472" />
  <package id="HelixToolkit.SharpDX.Assimp" version="2.8.0" targetFramework="net472" />
  <package id="HelixToolkit.Wpf.SharpDX" version="2.8.0" targetFramework="net472" />
  <package id="SharpDX" version="4.2.0" targetFramework="net472" />
  <package id="SharpDX.Mathematics" version="4.2.0" targetFramework="net472" />
</packages>
3. "manage nuget pakages..." and reload - all packages will be downloaded to folder {Solution}\packages
4. click "add reference...", tab "browse"
5. add each package manually

Code
`#include "pch.h"

using namespace System;
using namespace System::Collections;
using namespace HelixToolkit::Wpf::SharpDX;
using namespace HelixToolkit::Wpf::SharpDX;

int main(array<System::String ^> ^args)
{
	Generic::List<int>^ list = gcnew Generic::List<int>();
	list->Add(2);
	for each (auto e in list)
	{
		Console::WriteLine("e={0}", e);
	}
	Model::Scene::GroupNode^ r = gcnew Model::Scene::GroupNode();
	r->Name = "Wow wow wow";
	Assimp::HelixToolkitScene^ f = gcnew Assimp::HelixToolkitScene(r);

    return 0;
}
`

**Comment by goldv72** [comment]
oups! markup error
this packages.config file looks like normal packages.config
