### ISSUE TITLE
InstancingMeshGeometryModel3D SharpDX question

### ISSUE THREAD

**Issue by gregorsGit** [helix-toolkit/helix-toolkit#1187]
Hi,

I can´t understand the performace with instancing models.

For example:
1) Loading 20 complex models (each 1.000.000 triangles) without instancing. I get 20.000.000 triangles in my view and it is very slow. (expected)
2) Loading 20 complex models  (each 1.000.000 triangles) with instancing. I get about 1.000.000 triangles in my view and it is very slow. 

I would expect that the 2nd try with inctaning, have nearly the same performance as using only one complex model.

In your instancing-demo, I add 10 more boxes to the "Model" and the performace was poor.

Is this normal?
Thanks.

**Comment by holance** [comment]
Instancing is used to reduced draw call related performance issue, not number of triangles.

For example, if you want to draw 5000 simple box, you can use only one draw call instead of 5000 draw call.
