### ISSUE TITLE
Viewport support for WPFnetCore 3.0 SwapChainPanel

### ISSUE THREAD

**Issue by KrabatTilt** [helix-toolkit/helix-toolkit#1188]
Is ist planned to provide a Viewport control based on the UWP SwapChainPanel that will become available in WPF starting with .netCore3.0?
As the [documentation ](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.swapchainpanel) states the SwapChainPanel allows to place controls over the Panel like a Grid control does. This would be a major benefit as Viewport3DX with swapchain enabled does not work very well when controls are placed over the viewport.

**Comment by holance** [comment]
I couldn't find the news mentioned it will be available on Wpf.

**Comment by KrabatTilt** [comment]
I forgott to add some further links^^

It will be part of the upcomming[ XAML Islands](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/xaml-islands) for win 10 1903. It will be included in the Windows Community toolkit 6. Check point 2 under 'How do XAML Islands work?'.  But version 6 is actually in preview stage.

Here a link to the [roadmap](https://blogs.windows.com/windowsdeveloper/2019/06/13/xaml-islands-v1-updates-and-roadmap/).

**Comment by holance** [comment]
Xaml island is not the same as wpf supports Swapchain panel.

If you want to use xaml island, you can already try it with Helix toolkit UWP.

**Comment by KrabatTilt** [comment]
I thought that XAML Islands is an option when you go for WPF as a  .NET Core 3.0 Project (and win10 1903). This will allow you to host a SwapChainPanel inside of an WPF App.

Is the Helix toolkit UWP Viewport based on the UWP SwapChainPanel?

> If you want to use xaml island, you can already try it with Helix toolkit UWP.
Does that mean I can host the Helix toolkit UWP Viewport inside a WPF App using XAML Islands?

**Comment by holance** [comment]
Is the Helix toolkit UWP Viewport based on the UWP SwapChainPanel? Yes

Does that mean I can host the Helix toolkit UWP Viewport inside a WPF App using XAML Islands?

This is what xaml island supposed to do. You can try it, I haven't had time to experiment with it yet.
