### ISSUE TITLE
Is there any way to set different Material for each face?

### ISSUE THREAD

**Issue by maetiskou** [helix-toolkit/helix-toolkit#1189]
I need to set different material created from BitmapImage for each face on Helix3D´s BoxVisual3D box..

I am currently assingning material which is used on every face of the box.

```
// creating box and adding him into viewport

var box = new BoxVisual3D();
box.Width = width;
box.Height = height;
box.Length = length;
box.Material = MaterialHelper.CreateImageMaterial(boxTexture, boxOpacity);
box.Center = new Point3D(length / 2, width / 2, height / 2);
box.Transform = new TranslateTransform3D(posX, posY, posZ);
helixViewport3D.Children.Add(box);
```

is there a way to make different materials and assign them for different faces or to make one material which will stretch over all faces ?

**Comment by holance** [comment]
You need to use one material and use texture coordinate to sample different part of your texture.

**Comment by maetiskou** [comment]
> You need to use one material and use texture coordinate to sample different part of your texture.

Thanks for advice, but could you provide some kind of snippet where you do this ?

**Comment by holance** [comment]
http://ilkinulas.github.io/development/unity/2016/05/06/uv-mapping.html
Here is an example of a cube UV mapping. You need to merge your images into a single image, then provide your own texture coordinates into geometry3D.TextureCoordinates property.
