### ISSUE TITLE
MeshGeometry3D Drop event not fired

### ISSUE THREAD

**Issue by kvasnevskiy** [helix-toolkit/helix-toolkit#1197]
`                   <hx:ItemsModel3D ItemsSource="{Binding Items}">
                    <hx:ItemsModel3D.ItemTemplate>
                        <DataTemplate>
                            <hx:MeshGeometryModel3D
                                AllowDrop="True"
                                Geometry="{Binding Geometry}" 
                                Transform="{Binding Transform}" 
                                Drop="ContentElement_OnDrop"
                                Material="{Binding Material}"
                                IsThrowingShadow="True"
                                RenderWireframe="{Binding IsRenderWireframeEnabled}"/>
                        </DataTemplate>
                    </hx:ItemsModel3D.ItemTemplate>
                </hx:ItemsModel3D>`
ContentElement_OnDrop not fired

**Comment by holance** [comment]
This is wpf 2D UI event. Will not support it 3D world. You can use mouse down 3d and mouse up 3d to mimic the drag/drop yourself.
