### ISSUE TITLE
[WPF] HelixViewport3D.CameraController is null in Loaded event - no way to set initial zoom or camera position

### ISSUE THREAD

**Issue by Jinjinov** [helix-toolkit/helix-toolkit#1198]
Using HelixViewport3D in WPF, there is no way to set the initial zoom of the loaded model or to set the camera position, because HelixViewport3D.CameraController is null in the HelixViewport3D_Loaded event.

(also as a side note: setting the initial zoom or camera position from XAML would be very useful)

**Comment by holance** [comment]
You need to set camera properties instead of using camera controller

**Comment by witkowski01** [comment]
Just do not use Camera controller use instead : 
```c#
Viewport3D.Camera.LookAt(new Point3D(0, -1, 0), 0.1);
Viewport3D.Camera.Position = new Point3D(-7, -1, 174);
Viewport3D.Camera.LookDirection = new Vector3D(8, 0, -174);
Viewport3D.Camera.UpDirection = new Vector3D(1, 0, 1);
...
```
I wonder why CameraController work properly when I use only one simple view with one viewport and model and I had to use above workaround when I start using two viewports?

**Comment by holance** [comment]
Camercontroller is created during template applying, maybe there's some timing issue.
