### ISSUE TITLE
ExtrudedVisual3D in WPF.Sharpdx

### ISSUE THREAD

**Issue by sinaone1** [helix-toolkit/helix-toolkit#1201]
We have ExtrudedVisual3D in of HelixToolkit.Wpf and it's really useful to create extruded 3D models but I can't find it in HelixToolkit.Wpf.SharpDX.
Could you give me an idea that how can I create and extruded 3D model like that in HelixToolkit.Wpf.SharpDX?
This is my test for create a polygon:
`  List<Vector2> lstPnt2 = new List<Vector2>();
    lstPnt2.Add(new Vector2(60, 130));
    lstPnt2.Add(new Vector2(0, 130));
    lstPnt2.Add(new Vector2(0, 0));
    lstPnt2.Add(new Vector2(50, 0));
    lstPnt2.Add(new Vector2(60, 10));
}
`

**Comment by holance** [comment]
Use the source code from ExtrudedVisual3D. Create the mesh from the code, and pass into MeshGeometryModel3D.Geometry3D in WPF.SharpDX.

Example:

```
            // See also "The GLE Tubing and Extrusion Library":
            // http://linas.org/gle/
            // http://sharpmap.codeplex.com/Thread/View.aspx?ThreadId=18864
            var builder = new MeshBuilder(false, this.TextureCoordinates != null);

            var sectionXAxis = this.SectionXAxis;
            if (sectionXAxis.Length < 1e-6)
            {
                sectionXAxis = new Vector3D(1, 0, 0);
            }

            var forward = this.Path[1] - this.Path[0];
            var up = Vector3D.CrossProduct(forward, sectionXAxis);
            if (up.LengthSquared < 1e-6)
            {
                sectionXAxis = forward.FindAnyPerpendicular();
            }

            builder.AddTube(
                this.Path,
                this.Angles,
                this.TextureCoordinates,
                this.Diameters,
                this.Section,
                sectionXAxis,
                this.IsPathClosed,
                this.IsSectionClosed);
            return builder.ToMesh();
```
