### ISSUE TITLE
How to load a Wavefront Obj (.obj) with the associated per vertex color

### ISSUE THREAD

**Issue by hopaa** [helix-toolkit/helix-toolkit#1210]
Hi everyone,
Would you mind if I ask you to give me some hints on how to deal with vertex color obj files, how to load and show them properly? Actually I'm new to helix toolkit and I'm going to show a colored mesh using helix. I just don't know how to do it.
I have a Wavefront Obj file that looks like the following:

> v x y z r g b

> v -0.125977 -0.759931 2.147461 0.345098 0.262745 0.223529
v -0.127998 -0.758789 2.147461 0.345098 0.262745 0.227451
v -0.131836 -0.764648 2.152964 0.345098 0.239216 0.196078
v -0.125977 -0.764648 2.150153 0.341176 0.250980 0.207843

Although this issue has been discussed in #885 among @holance , @JeremyAnsel  and @privet56 , it's still unclear to me what should I do to be able to load a colored mesh (.obj or .ply if possible) using helix.
Any help would be appreciated.

Thanks in advance

**Comment by holance** [comment]
Only Sharpdx version supports it. Are you using Wpf version or Wpf.Sharpdx?

**Comment by hopaa** [comment]
I was using Wpf version and after reading the mentioned issue decided to use Wpf.SharpDX! To be honest, I don't know what's the difference between these two! And I don't know how to do it!

**Comment by hopaa** [comment]
Is the following snippet what I need to do?
>HelixToolkit.Wpf.SharpDX.Assimp.ImporterConfiguration config = new HelixToolkit.Wpf.SharpDX.Assimp.ImporterConfiguration();
config.ImportMaterialType = HelixToolkit.Wpf.SharpDX.Assimp.MaterialType.VertexColor;
HelixToolkit.Wpf.SharpDX.Assimp.Importer CurrentHelixObjReader = new HelixToolkit.Wpf.SharpDX.Assimp.Importer();
HelixToolkit.Wpf.SharpDX.Assimp.HelixToolkitScene objs = CurrentHelixObjReader.Load(@".\meshname.obj", config);

I can't find an example of how to use Wpf.SharpDX and cloudn't run the examples of this repo!

**Comment by hopaa** [comment]
Finally I could rewrite the code of FileLoadDemo example to be able to run it in Visual Studio 2015 :\ Since it didn't load the per vertex color, I added the above piece of code (I mean the customized config) and it worked :)
