### ISSUE TITLE
Exceptions when trying to run the UWP Example

### ISSUE THREAD

**Issue by JuandreG** [helix-toolkit/helix-toolkit#1214]
Exception thrown: 'System.Reflection.AmbiguousMatchException' in System.Private.CoreLib.dll
Exception thrown: 'Windows.UI.Xaml.Markup.XamlParseException' in SimpleDemoW10.exe
WinRT information: Cannot deserialize XBF metadata property list as 'ItemsSource' was not found in type 'HelixToolkit.UWP.ItemsModel3D'. [Line: 0 Position: 0]
Exception thrown: 'System.Reflection.TargetInvocationException' in System.Private.CoreLib.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in SimpleDemoW10.exe

These are the exceptions I get when trying to run the UWP SimpleDemo.

The project builds fine but when I try to run it fails.

**Comment by holance** [comment]
Are you running windows RT?

**Comment by JuandreG** [comment]
This is when trying to run the SimpleDemo provided by you. How can I check this?

**Comment by JuandreG** [comment]
I get different

**Comment by holance** [comment]
https://developercommunity.visualstudio.com/content/problem/470099/uwp-cannot-deserialize-xbf-metadata-crash.html

Maybe related to this?

**Comment by JuandreG** [comment]
I'll give it a try. So just update my Visual Studio 2019 to the latest. I really want to use your package in my UWP app, hope it works. And thanks for the reply!

**Comment by sergey-ko** [comment]
same error.
VS2019 latest updates installed
