### ISSUE TITLE
Test if Point is Visible in Camera

### ISSUE THREAD

**Issue by davidbirchwork** [helix-toolkit/helix-toolkit#1216]
How can I test whether a point is visible (e.g. renderable) within the view of a given Camera?

I'd like to write an extension method on the Camera object to test this as there doesn't appear to be one at the moment.

**Comment by holance** [comment]
Create a frustum from camera parameter, then test each point with the frustum.

**Comment by DimplesHei** [comment]
how  create a frustum from camera parameter?
