### ISSUE TITLE
MVVM

### ISSUE THREAD

**Issue by JuandreG** [helix-toolkit/helix-toolkit#1227]
I have 3 projects in a solution.

Project 1 (Data) holds SQLite integration using EntityFramework. This project is a NETStandard library project, I want to reuse it eventually.

Project 2 (ViewModels) holds all the Models and ViewModels for each class that I have. It holds all the application's logic in a service based manner using. This project is also a NETStandard library project, I also want to reuse it eventually.

Project 3 (App) holds all the views for the application as well as the application's startup configuration. It also configures the application's services using Microsoft's DependencyInjection nuget package. The registers the 'Singleton' classes, 'Scoped' classes and 'Transient' classes.

I would like to configure model groups in the ViewModels project but I cannot add  the HelixToolkit.UWP nuget package to it because it is a NetStandard library project. This means I cannot create collections that hold HelixToolkit.UWP.Geometry3D type in the ViewModels project. I can however create collections that hold HelixToolkit.SharpDX.Core.Geometry3D type but when I bind to this collection nothing shows up in the Viewport3DX.

I follow the UWP example that is provided as best I can, so I do create a model class that holds the Geometry3D type and the Material type but these types come from the HelixToolkit.SharpDX.Core namespace.

My question is this: How can I bind to HelixToolkit.SharpDX.Core types instead of HelixToolkit.UWP types? Is this possible? Is there any collection type in the HelixToolkit.SharpDX.Core namespace that I can dynamically add and remove models from?

**Comment by holance** [comment]
This is kind of legacy issue. But MVVM usually only applies to Wpf or UWP, you can use shared project to include viewmodels and try to bypass the name space issue.

In future, once Dotnet core 3.0 released, helixtoolkit Sharpdx will be using the core project as dependency and solve the issue you are getting.

**Comment by JuandreG** [comment]
Thanks for the reply and clearing that up for me.

I understand that I can add reference a reference to the UI layer of y solution but then when I won't be able to reuse it without the broken dependencies.

Is there no way for me to rather bind to the HelixToolkit.SharpDX.Core types instead of the HelixToolkit.UWP types?

And again thanks for the reply, I enjoy working with Helix Toolkit a lot.

**Comment by holance** [comment]
I don't think currently there is a way to do it. That's why I suggest using shared project and bypass this problem.

**Comment by JuandreG** [comment]
Thank you very much for your help, I appreciate it! I will give it a try.
