### ISSUE TITLE
Display PointCloud with different colored points

### ISSUE THREAD

**Issue by coczero** [helix-toolkit/helix-toolkit#1231]
I'm currently displaying a .ply point cloud using the PointsVisual3D class, which works fine.
I was just wondering how I would go about coloring points individually, e.g based on Z-Value?
PointsVisual3D only supports one color for all points.
I am using HelixToolkit.WPF.
Cheers

**Comment by holance** [comment]
You need to use Sharpdx version

**Comment by coczero** [comment]
No way with WPF version?

**Comment by holance** [comment]
Helix Wpf uses Wpf internal 3d engine. Wpf internal 3d engine does not provide direct point rendering.
