### ISSUE TITLE
Broken Rendering with NearPlaneDistance = 0

### ISSUE THREAD

**Issue by taoyouh** [helix-toolkit/helix-toolkit#1232]
If the camera of `HelixToolkit.Wpf.SharpDX.Viewport3DX` has its `NearPlaneDistance` set to 0, the rendering is broken. The faces at the bottm will cover the faces at the top, and the lighting become weird.

# To reproduce

Add this line of code to the end of method `Button_Click_Initialize` in Source\Examples\WPF.SharpDX\Viewport3DXCodeBehindTester\MainWindow.xaml.cs
```
// Other codes here
(viewport.Camera as PerspectiveCamera).NearPlaneDistance = 0;
```

# Expected result
![图片](https://user-images.githubusercontent.com/11157438/65745435-45f5e980-e12e-11e9-9bde-a44021a41499.png)

# Actual result
![图片](https://user-images.githubusercontent.com/11157438/65745368-0c24e300-e12e-11e9-8349-d1e0b6d5332e.png)

# Remarks
Setting the value to some small value like float.Epsilon causes the same problem.

**Comment by holance** [comment]
https://computergraphics.stackexchange.com/questions/5116/how-am-i-able-to-perform-perspective-projection-without-a-near-plane

I don't think this is useful to set near plane to 0.

**Comment by taoyouh** [comment]
So the near plane distance affects the non-linear distance calculating, and setting it to 0 causes all distances to be the same. Thank you for your response.
