### ISSUE TITLE
[UWP] Transparent Background or fixed Background in ViewPort3DX

### ISSUE THREAD

**Issue by ruben0909** [helix-toolkit/helix-toolkit#1233]
Hi,

I know this issue has been answered several times (#867, #877, #717, #961 and #579), but none of the solutions I found here seem to work for UWP.

The perfect solution for me would be Transparent Background
I tried this :

1. Solution 1

`<Grid Background="Green">
        <hx:Viewport3DX Background="#000000FF" BackgroundColor="#000000FF">
        </hx:Viewport3DX>
</Grid>`
But the background is Blue

2. Solution 2

`<Grid Background="Green">
        <hx:Viewport3DX Background="#000000FF" BackgroundColor="#000000FF"
                        FXAALevel="Ultra" MSAA="Maximum"
                        EnableSwapChainRendering="False">
        </hx:Viewport3DX>
    </Grid>`
But EnableSwapChainRendering is not valid in UWP and the background is Blue
3. Solution 3
`<Grid> <Grid.Background> <SolidColorBrush Color="Red"/> </Grid.Background> <hx:Viewport3DX x:Name="view3D" Background="Transparent" BackgroundColor="Transparent" > </hx:Viewport3DX> </Grid>`
I tried, but I dont remember if Background was White or Black no Red
4. Solution 4
```
   <Grid Background="Green">
        <hx:Viewport3DX BackgroundColor="0 0 0 0">
        </hx:Viewport3DX>
    </Grid>
```
Is not valid XAML
5. Solution 5
```
public void ClearRenderTarget(DeviceContextProxy context, Color4 color, bool clearBackBuffer, bool clearDepthStencilBuffer)
            {
                if (clearBackBuffer)
                {
                    color = new Color4(0, 0, 0, 0);
                    context.ClearRenderTargetView(colorBuffer, color);
                }

                if (clearDepthStencilBuffer)
                {
                    context.ClearDepthStencilView(depthStencilBuffer, DepthStencilClearFlags.Depth | DepthStencilClearFlags.Stencil, 1.0f, 0);
                }
            }
```
Black Background

Solution for Image as Background
1. Solution 1
```
//XAML
<hx:ScreenQuadModel3D Texture="{Binding BackgroundTexture}" />
//C#
BackgroundTexture = BitmapExtensions.CreateLinearGradientBitmapStream(EffectsManager, 128, 128, Direct2DImageFormat.Bmp,
                   new Vector2(0, 0), new Vector2(0, 128), new SharpDX.Direct2D1.GradientStop[]
                    {
                            new SharpDX.Direct2D1.GradientStop(){ Color = Color.White.ToColor4(), Position = 0f },
                            new SharpDX.Direct2D1.GradientStop(){ Color = Color.DarkGray.ToColor4(), Position = 1f }
                    }); 
```
Background from ViewPort3DX

Any idea?

Thx

**Comment by holance** [comment]
Swapchain doesn't support transparent background. UWP is using swapchain.

**Comment by ruben0909** [comment]
And what about ScreenQuadModel3D ? 
To have a Fixed image?
It doesn`t work either, right?
Thx

**Comment by holance** [comment]
ScreenQuadModel3D is working fine. Try to change the BackgroundTexture to TextureModel instead of stream, not sure why UWP implicit conversion does not work properly.

You can do like this:
```
BackgroundTexture = new TextureModel(
         BitmapExtensions.CreateLinearGradientBitmapStream(EffectsManager, 128, 128, 
         Direct2DImageFormat.Bmp,
                   new Vector2(0, 0), new Vector2(0, 128), new SharpDX.Direct2D1.GradientStop[]
                    {
                            new SharpDX.Direct2D1.GradientStop(){ Color = Color.White.ToColor4(), Position = 0f },
                            new SharpDX.Direct2D1.GradientStop(){ Color = Color.DarkGray.ToColor4(), Position = 1f }
                    }));
```

**Comment by ruben0909** [comment]
It Works!!
Thank you so much @holance 😄
