### ISSUE TITLE
NET Core Nuget Problems

### ISSUE THREAD

**Issue by inf9144** [helix-toolkit/helix-toolkit#1234]
Hey,
i saw you added support for .NET Core 3 WPF.
Very happy about it but i have problems using the Nuget Packages:

warning NU1701: Das Paket "HelixToolkit.Wpf 2.9.0" wurde nicht mit dem Projektzielframework ".NETCoreApp,Version=v3.0", sondern mit ".NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8" wiederhergestellt. Dieses Paket ist mit Ihrem Projekt möglicherweise nicht vollständig kompatibel.

warning NU1701: Das Paket "HelixToolkit.Wpf.SharpDX 2.9.0" wurde nicht mit dem Projektzielframework ".NETCoreApp,Version=v3.0", sondern mit ".NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8" wiederhergestellt. Dieses Paket ist mit Ihrem Projekt möglicherweise nicht vollständig kompatibel.

Could you please take a look at it? Thank you very much!

**Comment by holance** [comment]
.Net Core 3 support has not been release yet.

**Comment by holance** [comment]
.Net Core 3 support has been merged in #1235 
You can use HelixToolkit.Core.Wpf or HelixToolkit.SharpDX.Core.Wpf from myget pre-release build.

**Comment by bergi9** [comment]
Still no sight of pre-release builds on nuget.

**Comment by garzajp93** [comment]
I cannot seem to download it from Myget

Install-Package HelixToolkit.Core.Wpf -Version 2.10.0-alpha0084 -Source https://www.myget.org/F/helix-toolkit/api/v3/index.json
The 'Source' parameter is not respected for the transitive package management based project(s) MyProject.UI. The enabled sources in your NuGet configuration will be used. 
Restoring packages for C:\MyProject\MyProject\MyProject.UI.csproj...

Install-Package : The local source 'C:\MyProject\packages\Helix.Toolkit.Core.WPF.2.10.0' doesn't exist.
At line:1 char:1
+ Install-Package HelixToolkit.Core.Wpf -Version 2.10.0-alpha0084 -Sour ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by holance** [comment]
Seems like you are trying to install from your local folder instead of from myget. You need to add the myget link into nuget source and select the source to download.
