### ISSUE TITLE
FindHits returns always zero for .fbx models

### ISSUE THREAD

**Issue by vvs551** [helix-toolkit/helix-toolkit#1238]
There is impossible to get any result from FindHits() in case of .fbx model
I tried to use FindHits with BoneSkinDemo example and always get zero (

**Comment by holance** [comment]
Bone skin model doesn't support hit test yet.

**Comment by vvs551** [comment]
How do you propose to hit Bone Skin Model in the game?
Is it possible to get bounders and compare with 3d point?

**Comment by holance** [comment]
In game, they use separate bounding box or bounding spheres for rough estimated hit test instead of doing hit test on mesh directly.

Usually the editor will help you generate these bounds automatically.

**Comment by vvs551** [comment]
I am not sure, that the bounding sphere is enough to detect a hit test for Bone skin model )
For example in the case of the running soldier, I would like to detect different hits to the head, body, arms and legs (

**Comment by holance** [comment]
I didn't mean it uses single bounding sphere for whole mesh.

You can search collision mesh for details.

**Comment by vvs551** [comment]
> You can search collision mesh for details.
Could you give a link to any sample?

**Comment by holance** [comment]
Bone skin model hit test has been implemented in #1250
