### ISSUE TITLE
Bounds don't match positions

### ISSUE THREAD

**Issue by taoyouh** [helix-toolkit/helix-toolkit#1242]
WPF SharpDX

After changing the geometry of a mesh model from null to some newly created mesh geometry, its bounds don't match the positions of the mesh. The X values of the positions range from 0 to 0.009667, but the bounds has minimum X value -0.1 and maximum X value 0.109667. Where does this 0.1 offset come from?

There are no transforms in the whole visual tree.

![图片](https://user-images.githubusercontent.com/11157438/66757363-9b701b80-eece-11e9-95f7-f78499de7b06.png)

**Comment by taoyouh** [comment]
I think the problem is due to the following code at [https://github.com/helix-toolkit/helix-toolkit/blob/6dda81d9a8a09f8ce32f2a05269cf7736fba27b8/Source/HelixToolkit.SharpDX.Shared/Extensions/BoundingBoxExtensions.cs#L46]()

But my bounding box is really that small at all directions. This "fixing" does not make sense.
```
            if (diff.AnySmallerOrEqual(0.0001f)) // Avoid bound too small on one dimension.
            {
                return new BoundingBox(min - new Vector3(0.1f), max + new Vector3(0.1f));
            }
            else
            {
                return new BoundingBox(min, max);
            }
```

**Comment by holance** [comment]
Bounding box is used for hit test, only used as rough estimation. If bounding box is too small, it causes floating point precision issue. 

You can always calculate the bounding box yourself to accommodate your need if you need accurate bounding box.
