### ISSUE TITLE
GroupNode Metadata return null after Import Assbin file

### ISSUE THREAD

**Issue by slad38** [helix-toolkit/helix-toolkit#1243]
GroupNode Metadata return null after Export/Import Assbin file
How to use Metadata Import/Export correctly ?
Ref : Add assimp metadata support for import/export. Ref #1195 #1200

using HxModel = HelixToolkit.Wpf.SharpDX.Model;

.....Export
// Create Metadata
string name "XXXX";
var gn = new HxScene.GroupNode();
gn.Metadata = new Metadata();
var hmde = new HxModel.Metadata.Entry(HxModel.MetaDataType.String, name);
gn.Metadata.Add("Name", hmde);

......Import
 if ( n is GroupNode gn)
{
  if (gn.Metadata != null)
  {
    foreach (var d in gn.Metadata)
    {
       var key = d.Key;
       Trace.WriteLine(string.Format("Metadata Key {0}", key));
     }
}

But **gn.Metadata** return null for all nodes

**Comment by holance** [comment]
From my test, it is working fine. Could you upload an example project to show this issue?

**Comment by slad38** [comment]
I have found the problem with wrong id for Exporter. Geometry works fine but metadata fail.
Thanks for your help.
