### ISSUE TITLE
Question : how to find the debug log generated with HT.Wpf.SharpDX.Assimp ?

### ISSUE THREAD

**Issue by mwymwy** [helix-toolkit/helix-toolkit#1244]
Hi, 

Calling method **Load(sFileName)** from an HelixToolkit.Wpf.SharpDX.Assimp.Importer on some ifc files sometimes fail (importer.ErrorCode = Failed) and I wonder why.

I saw that a DebugLog may exist, and that looks like a good way of investigating further but I just can't find it. 
Is a log file generated ? If so where it is located ? Is a log database generated ? If so how can I get its content ?

I must precise that I did not touched any log configuration, so maybe no log is produced at all ? Or is there a default log conf for the HelixToolkit assimp importer ?

**Comment by bergi9** [comment]
There are no logs generated. You have to implement/proxy the logging.

Example logger for Debug.WriteLine
```c#
// ILogger is from HelixToolkit.Logger.ILogger
class DebugLogger : ILogger
{
    public static DebugLogger Default { get; } = new DebugLogger();

    public void Log<TMsgType>(LogLevel logLevel, TMsgType msg, string className, string methodName, int lineNumber)
    {
        Debug.WriteLine($"[{logLevel.ToString()}] {msg.ToString()} | {className}.{methodName}:{lineNumber}");
    }
}
...
var importer = new Importer();
importer.Configuration.Logger = DebugLogger.Default; // or call new DebugLogger()
importer.Load(...)
```

**Comment by mwymwy** [comment]
ok, thanks for the answer.
