### ISSUE TITLE
OIT Semi-Transparent Material

### ISSUE THREAD

**Issue by bergi9** [helix-toolkit/helix-toolkit#1245]
I'm importing many `.x` files into the scene. For now each model are using Instancing by using traverse through the scene, create `InstancingMesh` (some with additional/cloned `Node` with `InvertNormals`), populate the instances using `SceneNodeExtensions.UpdateAllTransformMatrix` and put into a `GroupNode`.
Some materials are semi-transparent (either alpha 0 or 1, nothing between) like trees (leaf), window and I set the `IsTransparent` to true. The OIT makes it transparent where the pixel color alpha value was 1 which it shouldn't.
Using the non-OIT method was sorting the nodes with `SortingGroupNode`. Since I use Instancing the meshes the sorting of `SortingGroupNode` doesn't work as expected because it goes to flicker when some instances are out of frustum view.
Are there a way to use Instancing with properly rendering the transparency?

**Comment by holance** [comment]
I don't think there's a way to render transparent with instancing correctly without huge performance penalty.

**Comment by bergi9** [comment]
i have invited you into my repository.
