### ISSUE TITLE
Meshbuilder.AddPolygon() throws ArgumentNullException

### ISSUE THREAD

**Issue by Reaper90** [helix-toolkit/helix-toolkit#1246]
Hey guys,
i'm trying to genereate meshes for 3D planar polygons using MeshBuilder, but when i'm using .AddPolygon() method with a list of more than four Vector3 objects (three or four works perfectly fine) for the polygon vertices, it throws an ArgumentNullException.
ParamName: fanNormals
StackTrace: HelixToolkit.Wpf.SharpDX.MeshBuilder.AddTriangleFan

So is this normal behavior? Am i using this wrong? Also i'm not quite sure how to use the .AddPolygonByTriangulation() method because it only accepts a List of int as parameter. Assuming my understanding is wrong, whats the best way to create 3D polygon meshes when just having the polygon vertices (in the right order)?

Thanks in advance

**Comment by JeremyAnsel** [comment]
Hello,
Instead of 
```csharp
var builder = new MeshBuilder();
```
you can try
```csharp
var builder = new MeshBuilder(false, false, false);
```

**Comment by Reaper90** [comment]
Thank you!
The Error seems to be gone. But i found another problem now: When trying to create meshes of concave polygons, the triangles that are generated by the meshbuilder are occupying space outside of the polygon borders... 
Any way to triangulate concave polygons correctly?
