### ISSUE TITLE
With PointGeometryModel3D in SharpDX how do I update a single point ?

### ISSUE THREAD

**Issue by ifdog** [helix-toolkit/helix-toolkit#1247]
Hi. With the code below I can display my cloudpoint on wpf,

` var cloudpoints = new PointGeometryModel3D { Color = Colors.White, Size = new Size(1, 1) };
  cloudpoints.Geometry = new PointGeometry3D() { Positions = MY_POINTS, Indices = MY_IDS };
   viewport.Items.Add(cloudpoints);`

Then I can update the cloud point by reassign all positions :

`cloudpoints.Geometry.Positions = MY_NEW_POINTS` 

But is it posible to update Z value for only one of points in MY_POINTS?

Thank you !

**Comment by holance** [comment]
You need to call geometry.UpdateVertices() after you modified the vertices inside positions.

**Comment by ifdog** [comment]
OK.Thank you.

**Comment by mjkkirschner** [comment]
Hi @holance - I am using 2.9.0 and encountering an issue where calling `PointGeometryModel3d.Geometry. UpdateVertices()` does not seem to update the points.
It also does not updates lines.
It works fine when using MeshGeometry3dModels.

Should there be any difference in usage between these methods for the different Model types?

**Comment by holance** [comment]
@mjkkirschner Try to add a GroupModel in Viewport3DX.Items, then add your PointGeometry3D into the GroupModel. Let me know if it fixes your issue.

**Comment by mjkkirschner** [comment]
Hi @holance this did not seem to fix my issue - added a GroupModel to the ViewPort children in the xaml - then I bound an `ObservableElement3dCollection` to the itemsSource for groupModel - then I have the same issue - but maybe it's becoming more clear what happening...

When I first initialize the pointGeometry I do something like this:

```
 var pointGeometry3D = new DynamoPointGeometryModel3D
            {
                Geometry = HelixRenderPackage.InitPointGeometry(),
                Transform = new MatrixTransform3D(rp.Transform.ToMatrix3D()),
                Color = Colors.White,
                Figure = PointFigure.Ellipse,
                Size = defaultPointSize,
                IsHitTestVisible = true,
                IsSelected = rp.IsSelected
            };
            return pointGeometry3D;
        }

 internal static PointGeometry3D InitPointGeometry()
        {
            var points = new PointGeometry3D()
            {
                Positions = new Vector3Collection(),
                Indices = new IntCollection(),
                Colors = new Color4Collection()
            };

            return points;
        }
```

Then I soon after modify and/ or reassign the Geometry property.

This does not work.

On the other hand, it seems that to get it to work all I need to do is that when initializing the `PointGeometryModel3D` the `Geometry` property should not be initialized, instead If I assign it later - everything seems to work...

Please let me know if I should file a separate issue for this.

**Comment by holance** [comment]
Hmm, maybe some event is not being hook up properly. You can keep the this open, I will do some debugging later.

**Comment by holance** [comment]
Fixed. Also make sure to call `Geometry3D.UpdateBounds` if necessary, otherwise the bound may not match the model after updating vertices.
