### ISSUE TITLE
AMD driver update and empty screen

### ISSUE THREAD

**Issue by CBenghi** [helix-toolkit/helix-toolkit#1256]
Hello all,

I hope this is not off topic;
I've recently updated the AMD drivers of a macbook and since the update Helix does not display anything in the canvas.
All 3D content in the example browser is empty just like a custom viewer that I've developed on top of the toolkit.

![image](https://user-images.githubusercontent.com/5476273/68703652-f86cf900-0582-11ea-9e8c-ff74fdba63e8.png)

Reverting to the old driver restores the Helix toolkit functionality, but then I get random BSOD on the system, so I cannot go back.

Is there a driver setting that you'd suggest I could look at?
Or a particular code section in helix that I should try to debug?

Thanks in advance for any hints,
Claudio

**Comment by holance** [comment]
Are you using Sharpdx version or wpf version

**Comment by CBenghi** [comment]
Hi Holance,
this happens in the WPF version. 
Thanks for your reply.
Claudio

**Comment by holance** [comment]
If you are using wpf version, then it is the driver bug, not related to helixtoolkit at all. Wpf version is using wpf framework for rendering.

**Comment by CBenghi** [comment]
Thanks,

I expected something like this.

Any idea about driver settings that I could investigate?
All other 3D viewers seem to work.

Any hints welcome.

Best,
Claudio

Il Mer 13 Nov 2019, 08:22 Lunci <notifications@github.com> ha scritto:

**Comment by holance** [comment]
Since wpf is using directx 9, you may want to check the driver compatibly with directx9

**Comment by CBenghi** [comment]
Just two lines to close the issue, if anyone should need it in the future.

After digging around a bit I've found that the recommended version is 19.3.1, which indeed fixes the problem with all WPF 3D rendering.

Thanks for your help.
Claudio
