### ISSUE TITLE
Setting HitTest Sensivity for LineGeometryModel3D and PointGeometryModel3D

### ISSUE THREAD

**Issue by slad38** [helix-toolkit/helix-toolkit#1257]
How to control HitTest Sensivity (Tolerance in pixels) for LineGeometryModel3D and PointGeometryModel3D ?

**Comment by holance** [comment]
Hit thickness property

**Comment by slad38** [comment]
It works after fixing two bugs
LineMaterialGeometryModel3D.cs line 46

       DependencyProperty.Register("HitTestThickness", typeof(double), typeof(**PointMaterialGeometryModel3D**), new PropertyMetadata(1.0, (d, e) =>
            { ((d as Element3DCore).SceneNode as LineNode).HitTestThickness = (double)e.NewValue; }));

replaced to  **LineMaterialGeometryModel3D**

same error in PointMaterialGeometryModel3D.cs line 46

public static readonly DependencyProperty HitTestThicknessProperty =
            DependencyProperty.Register("HitTestThickness", typeof(double), typeof(**LineMaterialGeometryModel3D**), new PropertyMetadata(1.0, (d, e) =>
            { ((d as Element3DCore).SceneNode as PointNode).HitTestThickness = (double)e.NewValue; }));
