### ISSUE TITLE
D3DImage.Lock() deadlock occurring on Helixtoolkit.Wpf.SharpDX 2.9.0

### ISSUE THREAD

**Issue by adscott1982** [helix-toolkit/helix-toolkit#1259]
After several hours of use our application can experience a permanent UI freeze that is apparently caused by a deadlock when the **RenderHost** is performing **UpdateAndRender()**.

It appears that during that method, **InvalidateD3DImage()** is called on the **DX11ImageSource**, which then attempts to gain a **Lock()** on the **D3DImage**.

Once this occurs the application UI will be completely frozen until it is killed from the Task Manager - even after several hours. Other background threads continue to run normally.

We have only started seeing this happen in the last 2-3 weeks. On September 17th we upgraded HelixToolkit.Wpf.SharpDX from **2.1.0** to **2.9.0**. We never saw this issue on 2.1.0.

This issue has been seen in the following circumstances:
- Application running for many hours (e.g. > 12 hours)
- Dialog box appearing on top of the renderer
- Workstation being accessed via Windows Remote Desktop (only on a single development machine) 
- Viewport changing from Visibility.Hidden to Visibility.Visible

Despite the above occurrences it is incredibly hard to reproduce. I have not been able to reproduce  it on my own dev machine.

This past weekend we had 6 test systems running automated testing for around 60 hours on each machine. The issue was only seen on two of them.

A little information on the environment:
- Windows 10 Professional (Version 10.0.18362 Build 18362)
- Nvidia Quadro K620 GPU - driver 26.21.14.3170 - 24/07/2019

Any help on this would be greatly appreciated. What could cause the Lock() to call to hang indefinitely? Could it be other UI issues outside of DirectX?

We are rolling back to 2.1.0 or 2.2.0 to try and test whether it makes the issue go away.

A stack trace is attached.

[stacktrace.txt](https://github.com/helix-toolkit/helix-toolkit/files/3841424/stacktrace.txt)

**Comment by smischke** [comment]
It seems to be an unfixed bug in D3DImage (.NET Framework/WPF version). 
See [#963](https://github.com/helix-toolkit/helix-toolkit/issues/963)

**Comment by adscott1982** [comment]
Thank you, I will take a look at that issue.

**Comment by smischke** [comment]
If you don't need wpf controls overlapping the viewport, you can switch to swap chain rendering.

**Comment by adscott1982** [comment]
Thanks - unfortunately we do require them. 

I am unsure if this is the same issue - when I run the directx command you mention in the original ticket, I get different behaviour than we are experiencing for this current issue.

with 'dxcap -forcetdr', the viewport simply stops displaying the 3D objects, the rest of the UI continues normally.

On hiding / unhiding the viewport the exception is surfaced.

![image](https://user-images.githubusercontent.com/12865303/68773010-b3989f00-0622-11ea-863e-083a38e2c714.png)

**Comment by adscott1982** [comment]
Also the application doesn't turn white as you describe in #963 - in our application everything is frozen but still visible.

**Comment by adscott1982** [comment]
Unfortunately we just had the issue occur on **2.1.0**. I am not sure why we have not seen this issue before. :(

**Comment by holance** [comment]
Can you run a sample demo and see if it has same issue?
Is the test machine environment changed recently?
Can you run the test without the viewport and see if freeze occurs?

I suspect maybe your system has a dead lock in UI thread causes helixtoolkit unable to obtain the lock from render thread.

**Comment by adscott1982** [comment]
Thanks @holance. It actually looks like the issue with 2.1 may be spurious - the UI did freeze, but there was no evidence of an issue with D3DImage in the call stack, and we had an OutOfMemoryException in the logs. There was a memory leak in 2.1 which you fixed for 2.2. 

We are going to run another test with 2.2 over the next couple of days to see if the issue is still present. If the issue is still there I will set about attempting to create a test application, and provide you with more information.

**Comment by adscott1982** [comment]
Just an update - we ran some testing on multiple systems at the end of last week and over the weekend using v2.2 and the UI 'freeze' issue did not occur on any of them. So it remains a possibility there is a genuine issue introduced some time between 2.2 and 2.9.

I will see if I can create a test application that reproduces the issue on 2.9.

**Comment by adscott1982** [comment]
Unfortunately (for us!) the UI freeze has now been seen while using HelixToolkit 2.2, so it seems likely there is no issue in HelixToolkit. Thanks for the help provided so far. When we do find what is happening I will update this ticket if it affects HelixToolkit.

**Comment by holance** [comment]
Which dot net framework you are using?

**Comment by adscott1982** [comment]
.NET Framework 4.7 (not 4.7.2 or 4.7.1)

**Comment by holance** [comment]
Have you tried newer version? I remember 4.7 had some bug

**Comment by adscott1982** [comment]
Thanks - I think we will give 4.8 it a try once we are done with the current attempt at fixing it. We already did try a workaround for the bug mentioned in this blog post, by adding the setting in app.config, but it did not fix it:

https://weblog.west-wind.com/posts/2019/Feb/14/WPF-Hanging-in-Infinite-Rendering-Loop

**Comment by adscott1982** [comment]
I think we have managed to track down the issue now - was nothing to do with HelixToolkit, but a deeper issue with WPF and having UI on a background thread. I raised an issue for Microsoft here: 

https://github.com/dotnet/core/issues/3948

**Comment by kthyholdt** [comment]
Did you find a workaround or solution for this issue @adscott1982 ?

**Comment by adscott1982** [comment]
@kthyholdt - the issue was not HelixToolkit, but rather the BackgroundVisualHost implementation. Once we removed that, we no longer saw the issue. In my comment above you can see I raised the issue on the dotnet repo, but I am unaware if anything is being done about it.
