### ISSUE TITLE
How to get MeshGeometry3D after applying ScaleTransform3D

### ISSUE THREAD

**Issue by KotNitro** [helix-toolkit/helix-toolkit#126]
Hello!

First of all, many thanks for the great toolkit!

My app is simple STL viewer and it also could transform 3d models and apply cutting planes.
So, I make a trnasform:
`model.Transform = new ScaleTransform3D(1, 1, 1 / compression);`
How can I get an updated MeshGeometry3D? I need it to call `MeshGeometryHelper.Cut()`

Thank you!

**Comment by objorke** [comment]
Please use the forum for questions, I only want bugs and new feature requests here! :-)
