### ISSUE TITLE
IFC rendering issue.

### ISSUE THREAD

**Issue by nuggen6** [helix-toolkit/helix-toolkit#1260]
Hi!
I have an issue with the attached ifc model.
It's not rendering correctly.

[Sample.zip](https://github.com/helix-toolkit/helix-toolkit/files/3866047/Sample.zip)

**FileLoadDemo**
![FileLoadDemo](https://user-images.githubusercontent.com/47356598/69184894-05a35e00-0b16-11ea-84fe-93206d21f5ef.PNG)

**My application based on HelixToolkit.SharpDX.Assimp**
![Sample1](https://user-images.githubusercontent.com/47356598/69185493-261fe800-0b17-11ea-83c9-e804b2450180.PNG)

**Assimp open3mod** (looks ok but a bit twitchy when rotating)
![Assimp_Open3DModelViewer](https://user-images.githubusercontent.com/47356598/69186291-8ebb9480-0b18-11ea-9e11-b4420f6e643e.PNG)

Can anybody help me understand what the problem is?

Thanks
nuggen

**Comment by holance** [comment]
I tested with IFC models from http://openifcmodel.cs.auckland.ac.nz/, it is working fine. 
Is all your IFC model having the same issue?

**Comment by nuggen6** [comment]
Hi!
Thank you for testing. Did you test the sample model I attached?
No, not all my models have this issue, most are working fine, but I got a batch of models from a client and they all suffer from this issue. I've tested these models in other IFC software without a problem.

Thanks!
nuggen

**Comment by holance** [comment]
I tried your file, seems like the model is way off the origin. Maybe it causes floating point accuracy issue. You may want to try to move the model near the origin and try to load it again.

**Comment by nuggen6** [comment]
Using transformation I got from loading the file with xBim Geometry it's loading fine.
Assimp's transformation doesn't seem to align with xBim.

```
var oneMeter =  (float)IfcModel.ModelFactors.OneMeter; //1000.0
var centerOffset = new Vector3(8.445f, 9.660f, -157.675f);
var translationVector = Vector3.Multiply(centerOffset, oneMeter);
var scaleVector = new Vector3(1 / oneMeter);
var trans = new System.Windows.Media.Media3D.TranslateTransform3D(translationVector.ToVector3D());
var scale = new System.Windows.Media.Media3D.ScaleTransform3D(scaleVector.ToVector3D());
scene.Root.ModelMatrix = trans.ToMatrix() * scale.ToMatrix();
```

Thanks!
nuggen
