### ISSUE TITLE
OBJ and STL importer issue

### ISSUE THREAD

**Issue by josejonasj** [helix-toolkit/helix-toolkit#1266]
Hi guys, I tried to load a couple of objects and they weren't displayed correctly in the `FileLoadDemo`.

For example, the following OBJ file [Eyeball.zip](https://github.com/helix-toolkit/helix-toolkit/files/3887571/Eyeball.zip) was displayed like this:

<img width="740" alt="01" src="https://user-images.githubusercontent.com/58182481/69558088-a14d2800-0f75-11ea-8c07-52812422d91e.png">
<img width="740" alt="02" src="https://user-images.githubusercontent.com/58182481/69558145-bcb83300-0f75-11ea-9538-b7227efa65d0.png">

So I added the following line to the loader:

`loader.Configuration.AssimpPostProcessSteps |= Assimp.PostProcessSteps.PreTransformVertices;`

and I got the following:

<img width="740" alt="03" src="https://user-images.githubusercontent.com/58182481/69558281-eec99500-0f75-11ea-8516-574f6cdaa21b.png">

That was the best that I got after testing several combinations of Assimp post-process steps. But if I load the same file in other viewers like [Open 3D Model Viewer](http://www.open3mod.com) (which is based on Assimp) I got this:

<img width="790" alt="04" src="https://user-images.githubusercontent.com/58182481/69558678-a2328980-0f76-11ea-9ae4-1879ffd2a03d.png">

And if I load **any** STL file like this one: [pin.zip](https://github.com/helix-toolkit/helix-toolkit/files/3887573/pin.zip) I got the following:

<img width="740" alt="05" src="https://user-images.githubusercontent.com/58182481/69558929-13723c80-0f77-11ea-935c-98573e9f8f24.png">
<img width="740" alt="06" src="https://user-images.githubusercontent.com/58182481/69558938-1705c380-0f77-11ea-82ce-441a3bacf096.png">

While it should be like this:

<img width="790" alt="07" src="https://user-images.githubusercontent.com/58182481/69558969-2127c200-0f77-11ea-9a4a-0c613e3bebb2.png">

Then after testing several combinations of Assimp post-process steps, I didn't find a solution so it looks like a bug to me in both cases but I have no idea if it's caused by **AssimpNet** library or **Helix Toolkit**.

It would be nice if you can take a look at that...

Greetings!

**Comment by holance** [comment]
For the eye, you can try to set
`loader.Configuration.ImportMaterialType = MaterialType.BlinnPhong;` to force using BlinnPhong material. Then set mesh to IsTransparent if alpha value is smaller than 1.
```
                            foreach (var node in scene.Root.Traverse())
                            {
                                if (node is MaterialGeometryNode m)
                                {
                                    if (m.Material is PBRMaterialCore pbr)
                                    {
                                        pbr.RenderEnvironmentMap = RenderEnvironmentMap;
                                        if(pbr.AlbedoColor.Alpha < 1)
                                        {
                                            m.IsTransparent = true;
                                        }
                                    }
                                    else if(m.Material is PhongMaterialCore phong)
                                    {
                                        phong.RenderEnvironmentMap = RenderEnvironmentMap;
                                        if(phong.DiffuseColor.Alpha < 1)
                                        {
                                            m.IsTransparent = true;
                                        }
                                    }
                                    //var bound = node.BoundsWithTransform;
                                    //node.ModelMatrix *= global::SharpDX.Matrix.Translation(-bound.Center);
                                }
                            }
```

For pin, use `loader.Configuration.ImportMaterialType = MaterialType.PBR;`

**Comment by josejonasj** [comment]
Thanks a lot, @holance , that did the trick. Any ideas on how to remove the gray area in the back of the eyeball (second image) to render it like the fourth image?

**Comment by holance** [comment]
Seems like the model tangent space has null values. You can use:
`loader.Configuration.AssimpPostProcessSteps |= Assimp.PostProcessSteps.CalculateTangentSpace;`
to fix the gray area.
Or use `phong.EnableAutoTangent = true;` can also fix it as well.

**Comment by josejonasj** [comment]
Thanks, that worked:

<img width="256" alt="02" src="https://user-images.githubusercontent.com/58182481/69735217-5dd1f580-10fe-11ea-938d-8b3c46441c09.png">

But if you apply zoom out it shows some unnecessary gray lines:

<img width="123" alt="01" src="https://user-images.githubusercontent.com/58182481/69735287-78a46a00-10fe-11ea-8b8b-b83fe6e78ae0.png">

Just to let you know.

**Comment by holance** [comment]
This artifacts may be caused by the duplicate UV coordinates in same triangle.
