### ISSUE TITLE
Error importing file: vector<T> too long on AssimpContext.ImportFile

### ISSUE THREAD

**Issue by JordanOlivet** [helix-toolkit/helix-toolkit#1269]
Hey guys,

I'm trying to load IFC files using the HelixToolkit.Wpf.SharpDX.Assimp Importer class, in order to display the building in 3D.

So far, it was working pretty great but I'm having trouble with a particular file.

Below is my code to load a file from a path.

```csharp
private void Load(string sFileName)
{
    Importer imp = new Importer();

    try
    {
        var conf = imp.Configuration;

        conf.AssimpPostProcessSteps = Assimp.PostProcessSteps.Triangulate | Assimp.PostProcessSteps.ValidateDataStructure | Assimp.PostProcessSteps.RemoveRedundantMaterials;
        conf.CullMode = SharpDX.Direct3D11.CullMode.None;
        conf.ForceCullMode = true;
        conf.ImportMaterialType = Viewport.EnableSSAO ? HelixToolkit.Wpf.SharpDX.Assimp.MaterialType.BlinnPhong : HelixToolkit.Wpf.SharpDX.Assimp.MaterialType.Diffuse;

        HelixToolkitScene imported = imp.Load(sFileName, conf);
 
        if (imp.ErrorCode == ErrorCode.Succeed)
        {
            // Do something
        }
    }
    catch (Exception e)
    {
        string message = e.Message;
        string stack = e.StackTrace;
        string breakPoint = "";
    }
}
```
The line ```imp.Load(sFileName, conf);``` give me an exception.

So, I searched deeper to see where was the problem.

And I end up in the ```Load(string filePath, out HelixToolkitScene scene)``` method of the Importer class.

Below is a screenshot of the exception :

![Sans titre2](https://user-images.githubusercontent.com/46482319/69820673-f3a27900-1201-11ea-8d16-2b4805abe741.png)

I don't know exactly why but the attached file is the only file raising the exception.

Is someone have an idea or a clue on how to make this file loading correctly ?

It will make me very happy ! =)

Thanks in advance for any response.

[ifc_file.zip](https://github.com/helix-toolkit/helix-toolkit/files/3902481/ifc_file.zip)

**Comment by holance** [comment]
Are you able to use assimp viewer to import this file? This error is from assimp.net, not a helixtoolkit issue.

**Comment by JordanOlivet** [comment]
First of all, thanks for your response.

I have just tried to load my file in the Assimp viewer but I got an exception :

![assimpviewer](https://user-images.githubusercontent.com/46482319/70224806-2e4e6900-174e-11ea-94a2-641e1925d96f.png)

So, I suppose that it's an Assimp problem.

I should probablity open an issue on the Assimp github.

Thanks.

**Comment by JordanOlivet** [comment]
Quick note : It was indeed a bug in Assimp.
Issue : https://github.com/assimp/assimp/issues/2809
