### ISSUE TITLE
Helix-toolkit and WebRTC. How to access native SharpDX.Direct3D11.Texture2D

### ISSUE THREAD

**Issue by SebastianKunz** [helix-toolkit/helix-toolkit#1271]
Hello everyone.
I want to share the rendered scene over the internet. For that I want to use WebRTC. Don't worry too much about the WebRTC part, because that is mostly working. The WebRTC pipline expects a SharpDX.Direct3D11.Texture2D, which then gets encoded on the GPU and send to the remote peer.
I am completely new to WPF 3D/helix-toolkit, so please be patient with me. The following code is not writte by me, but by a colleague.
The application is a Viewer, to look at various image formats.
Here is the Code how the image is loaded.

```
 public async Task Load(Rect area, double scale, CancellationToken ct, int zLayer)
        {
            if (_isLoaded)
                return;

            var model = new MeshNode();

            var meshBuilder = new MeshBuilder(true, true, false);
            meshBuilder.AddBox(new Rect3D(0, 0, 0, _bitmapFrame.PixelWidth, _bitmapFrame.PixelHeight, 0.0), BoxFaces.PositiveZ);
            MeshGeometry3D geometry = meshBuilder.ToMeshGeometry3D();
            model.Geometry = geometry;

            model.Material = new PhongMaterialCore
            {
                DiffuseAlphaMap = _bitmapFrame.AsMemoryStream(FileExtension == ".png"),
                SpecularColor = Color.Black,
                DiffuseMap = _bitmapFrame.AsMemoryStream(FileExtension == ".png")
            };

            ModelGroup.AddNode(model);

            _isLoaded = true;
        }
```

And is then rendered like this

```
<hx:Element3DPresenter x:Name="MainContent" Content="{Binding ImageDataProvider.ModelGroup}" 
                                   IsHitTestVisible="False"/>
```

I went through the classes and was looking for a place where I could catch a Texture2D right before or after it is rendered. But without success.

This is the function I would call to send a videoframe to the encoder. Where the IntPtr is the nativePointer of Texture2D.
`public void SendVideoFrame(IntPtr rgbaPixels, int stride, int width, int height, VideoFrameFormat videoFrameFormat);`

In this example I use windows `DesktopDuplicationApi` to capture my desktop. And send it to the WebRTC pipeline.

```
while (IsRunning)
{
  // Try to get duplicated frame within given time is ms
  var res = duplicatedOutput.TryAcquireNextFrame(_options.TimeOut, out var frameInfo, out var screenResource);

  if (res.Success)
  {
    if (frameInfo.AccumulatedFrames == 0)
    {
      duplicatedOutput.ReleaseFrame();
      continue;
    }

    using (var screenTexture2D = screenResource.QueryInterface<Texture2D>())
    {
      videoTrack.SendVideoFrame(screenTexture2D.NativePointer, 0, screenTexture2D.Description.Width, screenTexture2D.Description.Height, WebRtc.VideoFrameFormat.GpuTextureD3D11);
    }
    screenResource.Dispose();
  }
}
```

So my question is. Is it possible to catch the currently rendered frame or about to be rendered frame, and can that be used as Texture2D? Otherwise is it possible to convert a `MeshNode` into a Texture2D ? Please keep in mind that I am developing a low latency application, so performance is very important. I don't want unnecessary copies between RAM and GPU memory.

Please let me know if you need more information about my problem. I will respond asap.

Thank you

**Comment by holance** [comment]
You may want to create a custom render host like [DX11ImageSourceRenderHost](https://github.com/helix-toolkit/helix-toolkit/blob/develop/Source/HelixToolkit.Wpf.SharpDX.Shared/Controls/DX11ImageSourceRenderHost.cs) used in wpf.sharpdx.

You can directly get the Texture2D from default render host events.

**Comment by SebastianKunz** [comment]
Thats great news! Thank you. Is there an example on how to attach the custom render host to the Viewport? When I create the renderhost the SharpDX device is uninitalized. Attaching that renderhost results in an exception. Attaching the renderhost later, doesn't seem to have an effect.

**Comment by holance** [comment]
Sharpdx device is in effects manager, you need to set the effects manager.

**Comment by SebastianKunz** [comment]
Thats what I do.

```
Viewport3Dx.EffectsManager = new DefaultEffectsManager(0);
var customRenderHost = new DX11ImageSourceRenderHost();
Viewport3Dx.Attach(customRenderHost);
```

And here is a [screenshot](http://prntscr.com/q86poi) of the exceptions.

**Comment by holance** [comment]
Currently helixtoolkit doesn't support custom render host, you need to modify the source code to test.

I will add some code to support it, or you can do a PR, should be straight forward.

**Comment by holance** [comment]
Actually you don't really need to use custom render host.
Following code is used to do viewport capture, which you can modify for your need:
```
        public static System.IO.MemoryStream RenderToBitmapStream(this IViewport3DX view)
        {
            if (view.RenderHost != null && view.RenderHost.IsRendering)
            {
                view.RenderHost.UpdateAndRender();              
                if (view.RenderHost != null && view.RenderHost.IsRendering)
                {
                    var memoryStream = new System.IO.MemoryStream();
                    Utilities.ScreenCapture.SaveWICTextureToBitmapStream(view.RenderHost.EffectsManager, 
                        view.RenderHost.RenderBuffer.BackBuffer.Resource as global::SharpDX.Direct3D11.Texture2D, memoryStream);
                    return memoryStream;
                }
            }
            return null;
        }
```

**Comment by SebastianKunz** [comment]
Thank you! This solves my problem. One last question: How do I lock the backbuffer? I need to copy the backbuffer into an internal buffer of the hardware encoder. While copying I don't want other threads to manipulate the buffer.

**Comment by holance** [comment]
Rendered event is a synchronized call.
