### ISSUE TITLE
QUESTION: Modifying the geometry of an existing model at runtime.

### ISSUE THREAD

**Issue by LongNguyenP** [helix-toolkit/helix-toolkit#1272]
Hello

When I modify the geometry of a model that is already in Viewport3DX.Items (e.g. changing vertex position, vertex colors), it does not seem to have any effect, UNLESS I remove the model and then add it back to Viewport3DX.Items. Can you please confirm that this is the CORRECT way to modify the geometry of an existing model at runtime

What is the cost of removing/adding model to Viewport3DX.Items? I can see the source that adding will invoke Attach on the model and removing will invoke Detach. Are these expensive operations?

**Comment by holance** [comment]
You need to call following if you updated vertex/triangle/colors.
```
        geometry.UpdateVertices();

        geometry.UpdateTriangles();

        geometry.UpdateColors();
```
