### ISSUE TITLE
Model blinking with Perspective Camera

### ISSUE THREAD

**Issue by slad38** [helix-toolkit/helix-toolkit#1278]
Large model blinking with Perspective Camera Setup.
OrthographicCamera works fine.

![helix](https://user-images.githubusercontent.com/36540486/70772022-447aab80-1d84-11ea-90b1-f4de4c88429d.JPG)
FileLoadDemo     Car.3DS
  
Camera = new PerspectiveCamera
            {
                LookDirection = new System.Windows.Media.Media3D.Vector3D(0, -10, -10),
                Position = new System.Windows.Media.Media3D.Point3D(0, 10, 10),
                UpDirection = new System.Windows.Media.Media3D.Vector3D(0, 1, 0),
                FarPlaneDistance = 5000,
                NearPlaneDistance = 0.1f
            };

**Comment by holance** [comment]
This is caused by z-fighting. You can either set the `MeshNode.CullMode = CullMode.Back` or adjust depth bias.
