### ISSUE TITLE
Techniques for handling large amounts of mesh?

### ISSUE THREAD

**Issue by maharada2** [helix-toolkit/helix-toolkit#1279]
I am creating a tool for modeling buildings.

The requirement definition is as follows,
·Capable of handling up to 40 million mesh.
 （6~7 millions cube）
·Shapes handled are cubes, cylinders, and tubes. However, there are many types depending on the size.
·Boolean operations are possible.
·Be selectable.
·Comfortable operability

I want to create this using helix-toolkit WPF or SharpDX.

As a benchmark, I made 5 million mesh with helix-toolkit WPF and SharpDX,
Both consumed several gigabytes of memory and were not very comfortable.

Please let me know if there are techniques to comfortably handle more meshes and polygons with helix-toolkit WPF or SharpDX.

**Comment by holance** [comment]
You may want to try instancing

**Comment by maharada2** [comment]
Thank you for the advice.

Refer to InstancingDemo in HelixToolkit.Wpf.SharpDX.
When tested with the InstancingMeshGeometryModel3D class,
It was comfortable to operate at 3 million instances.(It's amazing...)

I will check if other my requirement definitions can be satisfied.
Thank you.

**Comment by maharada2** [comment]
I know,
I should make 3 InstancingMeshGeometryModel3Ds Inctance For cubes, cylinders, and tubes,
And
After moving, rotating, or scaling the instance, I should add instances according to the shape.

Is this allright?

**Comment by holance** [comment]
How many shapes do you have? Usually a thousand geometries should be okay.

**Comment by maharada2** [comment]
I need About ten thousand shapes,or more.

One InstancingMeshGeometryModel3D can only have one model set, right?
If so, When I want to use a shape like “H” and a shape like “□”, I need two InstancingMeshGeometryModel3Ds?
→If it is ten thousand shape, need I ten thousand InstancingMeshGeometryModel3Ds?

**Comment by holance** [comment]
I think you need to render layer by layer instead of putting everything in one scene, since most of the models are not going to be visible at all.

**Comment by maharada2** [comment]
Does it mean that the IsRendering property of GeometryModel3D should be used to divide by drawing unit?

**Comment by holance** [comment]
You can try. But I think you may want to merge meshes at some point. Or have your own mesh builder to build meshes. I don't think loading 10 thousand meshes at once is a feasible solution.

**Comment by holance** [comment]
You can also try to watch some tutorials on how to build a minecraft game and have a general idea of how minecraft is rendered with millions of blocks.

Here is one tutorial example if you don't mind to pay. It is using Unity though: https://www.udemy.com/course/unityminecraft/

**Comment by maharada2** [comment]
thank you for the advice.

It seems to be possible by using multiple InstancingMeshGeometryModel3Ds.
I'll try a little more.

Thank you for answering.

**Comment by smischke** [comment]
HelixToolkit is more or less for presentation. You might need a CAD/CAM kernel like [Open CASCADE Technology (OCCT)](https://www.opencascade.com/content/overview) (see [Boolean Operations](https://www.opencascade.com/doc/occt-7.0.0/overview/html/occt_user_guides__boolean_operations.html)) or [OpenCamLib](https://www.freecadweb.org/wiki/OpenCamLib) (see [demo](https://www.youtube.com/watch?v=SjUJYmrdbAw)). 

If you are keen, you could also implement [Cubical Marching Squares](https://www.youtube.com/watch?v=8sf9soKi7j4) (see [paper](https://graphics.cmlab.csie.ntu.edu.tw/CMS/)).

You could still use HelixToolkit for presentation.
