### ISSUE TITLE
Some questions about coloring and mesh operations

### ISSUE THREAD

**Issue by Mansterteddy** [helix-toolkit/helix-toolkit#128]
I am working on the work which combine Kinect v2.0 with helix-toolkit. I complete some works like load and rotate a model using hands with the help of Kinect. But I do not know how to coloring a model (not change illumination to color whole model but color part of the model ). Can you give me some advises? And I also want to know some basic mesh operations and demos? And can I load several models in one scene?

Sorry for ugly English.

**Comment by objorke** [comment]
The forum should be used for questions! :-) For enhancements, please create one issue for each new feature.

1. WPF: Changing color should be possible by simply replacing the material of the model, but if you want to change a part of a model you must split the geometry (positions and texture coordinates) into two models...
2. WPF: Yes, it should be possible to load multiple models in one scene.

**Comment by objorke** [comment]
Can we close this issue?

**Comment by Mansterteddy** [comment]
Thanks a lot! Sorry for my wrong actions, this is my first time to use issue on github,

**Comment by objorke** [comment]
No problem :)
