### ISSUE TITLE
Camera target point highlighting

### ISSUE THREAD

**Issue by Forester-** [helix-toolkit/helix-toolkit#1291]
Hi!
Please, help me solve the problem.
I use HelixToolkit.Wpf.SharpDX. There are two semitransparent surfaces on the scene, one over another. The OrthographicCamera is used. In the Viewport3DX window, a color spot is displayed on the surfaces.

![image](https://user-images.githubusercontent.com/1488127/72661503-e462cf00-39eb-11ea-89e9-b08506c00a66.png)
What is the color spot? As I understand this spot is related to the camera target point. How is it possible to remove the spot?
The source code for this case is here - https://github.com/Forester-/HTKX/tree/master/HxRflc

Thanks in advance!

**Comment by holance** [comment]
Don't use diffuse material, diffuse material uses fake lighting, which causes this effects

**Comment by Forester-** [comment]
I've applied recomended changes (https://github.com/Forester-/HTKX/blob/master/HxRflc/MainWindow.xaml.cs), but the spot is still here.
![image](https://user-images.githubusercontent.com/1488127/72687509-6861a780-3b0f-11ea-80a3-7ad11f53bf23.png)

**Comment by holance** [comment]
Your nearplane distance is -10, it should be > 0 value.

**Comment by Forester-** [comment]
Set NearPlaneDistance = 1, it has not helped.

After setting up LookDirection length equal to the camera width the spot has disappeared. But I think it is not a solution, it is just a concealment of the problem. Because as we zoom the color changes.
![image](https://user-images.githubusercontent.com/1488127/72707268-181b3180-3b71-11ea-914d-ba6172075992.png)
![image](https://user-images.githubusercontent.com/1488127/72707289-1f423f80-3b71-11ea-87d3-6d637a294e59.png)
![image](https://user-images.githubusercontent.com/1488127/72707305-26694d80-3b71-11ea-84e1-b4f5a7d2b468.png)

The last changes as usual is here https://github.com/Forester-/HTKX/tree/master/HxRflc

**Comment by holance** [comment]
You can set `Viewport3DX.EnableOITRendering = false`.

**Comment by Forester-** [comment]
Setting Viewport3DX.EnableOITRendering = false (I set it in XAML) helped a little. But the spot still is here.
![image](https://user-images.githubusercontent.com/1488127/72786952-ee7d0b80-3c3f-11ea-8388-395bc0f3a6da.png)
The spot is much smaller and faintly distinguishable, but it is here. 
And I need OIT. OIT is a cause I changed HelixToolkit.Wpf on HelixToolkit.Wpf.SharpDX.

**Comment by holance** [comment]
Try to set `OITWeightMode = NonLinear`

**Comment by Forester-** [comment]
```EnableUnLit = true``` had solved the problem.

But...
As I understand (I may be wrong) the spot appearing cause is diffuse light calculation. Diffuse light calculation uses an angle between the plane normal and the camera direction. As the angle changes from point to point as the point color also changes.
But the first example did not use diffuse light source, only ambient light source. And PhongMaterial was used. I expected that according Phong lighting model (https://en.wikipedia.org/wiki/Phong_reflection_model) only ambient part on lighting would be calculated. 
So I don't understand why the diffuse lighting calculation is used when the scene does not contains diffuse light sources?

**Comment by holance** [comment]
Like I said previously, this diffuse material is using fake lighting for specific use case, like rendering the view cube. If you need Phong lighting, why not use Phong material?
