### ISSUE TITLE
Bug suspicion in MipMap generation

### ISSUE THREAD

**Issue by Forester-** [helix-toolkit/helix-toolkit#1295]
I suspect that in class ```HelixToolkit.Wpf.SharpDX.Utilities.ShaderResourceViewProxy```, method ```public void CreateView(TextureModel texture, bool disableAutoGenMipMap = false)``` it is neccessary to invert ```disableAutoGenMipMap``` in ```CreateView``` calls, because all called ```CreateView``` methods expect ```generateMipMaps``` parameter.

**Comment by holance** [comment]
What's the problem you are having with mipmap?

**Comment by Forester-** [comment]
I draw to a bitmap and use the bitmap as texture. Your implementation works correct when ```TextureModel``` contains ```Stream```. But when ```TextureModel``` contains ```NonCompressedData``` the implementation does not generate the mipmap.

**Comment by JeremyAnsel** [comment]
@Forester- is right, there is a bug with the calls to the `CreateView` function.

In `public void CreateView(TextureModel texture, bool disableAutoGenMipMap = false)`, there is a `disableAutoGenMipMap` parameter which, when true, disables the generation of the mipmaps.
This parameter is transmitted to the calls of `CreateView`.

But in the functions, `public void CreateView<T>(T[] array, global::SharpDX.DXGI.Format format, bool createSRV = true, bool generateMipMaps = true) where T : struct`,
 `public void CreateView<T>(T[] array, int length, global::SharpDX.DXGI.Format format, bool createSRV = true, bool generateMipMaps = true) where T : struct` and `public void CreateView<T>(T[] array, int width, int height, global::SharpDX.DXGI.Format format, bool createSRV = true, bool generateMipMaps = true) where T : struct`, there is a `generateMipMaps` parameter which, when true, enables the generation of the mipmaps.

As you can see, the logic is inverted.

**Comment by holance** [comment]
Ha, will fix it
