### ISSUE TITLE
PointMaterial - possible to change PointGeometryColor and Material color blend?

### ISSUE THREAD

**Issue by mjkkirschner** [helix-toolkit/helix-toolkit#1299]
I have a use case where sometimes I need to display points using vertex colors (individual points colors from the `PointGeometry3d.Colors`. ) And sometimes I need to change all point colors to a single color.

I could do this by swapping back and forth between two color collections but there might be many points (millions) and I'd like to avoid keeping the second collection of colors around, the colors would also need to be kept in sync to the changing size of the point geometry.

What I was trying to work out was the ability to switch the blending between the PointGeomtryModel.Color property and PointGeometry.Colors - right now it appears that using the default PointGeometry3dModel or PointMaterial - that a multiply is done between the colors - ideally I would be able to switch the PointMaterial to a different material that uses only the PointMaterial.Color - then switch it back to the material which displays the individual point colors.

Any guidance appreciated.

**Comment by holance** [comment]
Added two new properties for the point geometry model 3D. You can set `EnableColorBlending=true` and tune the `ColorBlendingFactor` to satisfy your needs.

**Comment by mjkkirschner** [comment]
thanks @holance! Will test it out.
