### ISSUE TITLE
DirectionalLight3D without reflexion

### ISSUE THREAD

**Issue by riegaz** [helix-toolkit/helix-toolkit#1309]
I use the directionallight3d and there is a reflexion visible on my 3D object. Depending on the SpecularShininess this reflexion changes in size.

I understand why it is there, however, is there a possibility to remove it completely? I tried other light sources already but none seemed to work right.

Any ideas for me?

**Comment by holance** [comment]
Try to set specular color to black

**Comment by riegaz** [comment]
That works! Great, Thank you.
