### ISSUE TITLE
Failed to assign to property HelixToolkit.UWP.CoordinateSystemModel3D.LabelColor in version 2.11.0

### ISSUE THREAD

**Issue by sdanev** [helix-toolkit/helix-toolkit#1310]
Windows.UI.Xaml.Markup.XamlParseException: The text associated with this error code could not be found.
Failed to assign to property 'HelixToolkit.UWP.CoordinateSystemModel3D.LabelColor'. [Line: 0 Position: 0]

The bug exist in in version 2.11.0 and do not exist in in version 2.10.0.

**Comment by holance** [comment]
Interesting, I don't think we change anything on UWP between 2.10 and 2.11.

**Comment by sdanev** [comment]
I am using UWP SDK 1809. Not sure if exist at other UWP SDK versions. 
The exception appear when you try to make the the Viewport3DX Visible. 
The bug exist in in version 2.11.0, but do not exist in in version 2.10.0 and previous.
It is very easy to reproduce.

**Comment by JeremyAnsel** [comment]
Hello,
Between version 2.10 and 2.11, the TargetPlatformVersion has been updated.
See eba84be5ab5cc496a42c94482d25c4f3804d6085

**Comment by JeremyAnsel** [comment]
Related:
#1213
#1214

It seems that newer versions of the UWP sdk break the UWP demo.

**Comment by JeremyAnsel** [comment]
microsoft/microsoft-ui-xaml#1935

**Comment by JeremyAnsel** [comment]
The above error does not appear in Release mode.

**Comment by sdanev** [comment]
For me it appear on Release, Debug and .Net Native Compilation.

**Comment by SnowyWreath** [comment]
I just encountered this too. Similar to @sdanev, my app targets Windows 10 version 1809 (build 17763). After rolling back to 2.10, it's back to working fine.

**Comment by clothesfee** [comment]
+1. I just encountered the same thing. App targets Windows 10 1809-1909, Visual Studio 2019. @JeremyAnsel , Thank You for the great work on Helix anyway.  Right now Helix is the only 3D engine which I can find working smoothly on UWP, suitable for our project, and future promising!
