### ISSUE TITLE
Pixel Shaders and Viewport3DX

### ISSUE THREAD

**Issue by ChrisHonsinger** [helix-toolkit/helix-toolkit#1315]
BACKGROUND
I am creating software to display true 3D scenes on a 2D screen.  The screen has special reflective properties. No special glasses or any special gadgets are needed.  We use 22 projectors that emit light onto the screen. As you look around at the screen, the screen and imagery are calibrated to provide your eyes the part of a scene as you would see when viewing a physical 3D scene.  I am using 22 Helix.WPF.SharpDX instances, one for each projector. Each projector (a Helix.WPF.SharpDX instance) uses the same model, but a different camera.   

(Background on WPF pixel shaders: https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.effects.shadereffect?view=netframework-4.8 )

The light emitted from a given projector needs to be corrected for a multitude of physical distortions.  Without the correction, the 3D display is highly distoted to the viewer. We can correct for the distortion by measuring the distortion and by inverting the measured distortion by using a 3rd order polyomial. This polynomial is third order in both X and in Y. Everything works fine -- except for the speed -- it is too slow.  

To overcome the speed of using a polynomial, we wish to use "pixel shaders".  We have developed the "pixel shaders" and they work fine for WPF elements like canvas, image, grid, etc.:

THIS WORKS
<image>
  <image.Effect>
      <local:ProjectorCorrectorEffect Input2="{StaticResource imageLut}"   />
   </image.Effect>
</image> 

However, using the Viewport3DX with the same shader as above, it doesn't work:

THIS DOESN'T WORK
<hx:Viewport3DX Visibility="Visible"  EnableSwapChainRendering="True"   Camera="{Binding TDTCAM}"  ShowViewCube="False"       BackgroundColor="Black"  CameraMode="Inspect"                                       EffectsManager="{Binding EffectsManager}"    FXAALevel="Low">
            <hx:AmbientLight3D Color="#363636" />
           <hx:DirectionalLight3D Direction="{Binding Camera.LookDirection}" Color="#D6D6D6" />
            <hx:EnvironmentMap3D IsRendering="{Binding RenderEnvironmentMap}"          Texture="{Binding EnvironmentMap}" />
            <hx:Element3DPresenter Content="{Binding GroupModel}" />
            <hx:PostEffectMeshBorderHighlight EffectName="highlight" />
            **<hx:Viewport3DX.Effect>
		     <local:ProjectorCorrectorEffect Input2="{StaticResource imageLut}"   />
             </hx:Viewport3DX.Effect>**
  </hx:Viewport3DX>

QUESTION:

Should this work? That is, should a Viewport3DX enable wpf pixel shaders?

If not, is there a way I can achieve the same effect using some other technique? Perhaps a RenderTargetBitmap using Viewport3DX in code behind or within my view model?

Thank you - and I hope this is clear.

Chris

**Comment by holance** [comment]
Wpf pixel shader will not work on Viewport3DX. Viewport3DX is using custom rendering engine, not Wpf one. You can write your own pixel shader to be used in Viewport3DX. We have a example [here](https://github.com/helix-toolkit/helix-toolkit/tree/develop/Source/Examples/WPF.SharpDX/CustomShaderDemo)

**Comment by ChrisHonsinger** [comment]
Holance -- I appreciate the information more than you know.  I am struggling with the increased complexity of DX 11 shaders, but believe the revised custom DX 11 shaders will be as simple as the WPF DX 9 based shaders.

Thanks.

**Comment by Noemata** [comment]
Is there a specific reason this is a WPF app?  You would have more control with a UWP/DirectX combo.

**Comment by ChrisHonsinger** [comment]
*We'll have to look in to it. Ironically, I just became aware of that
yesterday. Unfortunately, we don't have much time to explore new
technologies.*

**Comment by ChrisHonsinger** [comment]
Holance helped us get this done. If anyone needs help on this let me know. Holance is the expert though.
