### ISSUE TITLE
Weird 3D mesh geometry lighting

### ISSUE THREAD

**Issue by TheSpixxyQ** [helix-toolkit/helix-toolkit#1323]
Hello, I have a problem with lighting of my generated 3D polygon. It depends on "generation axis", only if one of the axes is negative value, see below in `GetBasePolygon()`.
I have rotation transform around X axis by 90 degrees on all of my models so I have switched Y and Z axes (if that matters in this case).
I am generating L profiles like this:
```
public static MeshGeometryModel3D GetLeg(LegPosition legPosition, float width, float thickness, float height)
{
    var mb = new MeshBuilder(false, false);

    var basePolygon = GetBasePolygon(legPosition, width, thickness, 0);
    var topPolygon = GetBasePolygon(legPosition, width, thickness, height);

    mb.AddPolygon(basePolygon);
    mb.AddPolygon(topPolygon);

    GetSidePolygons(basePolygon, topPolygon)
        .ForEach(s => mb.AddPolygon(s));

    mb.ComputeNormalsAndTangents(MeshFaces.Default);

    return new MeshGeometryModel3D
    {
        Geometry = mb.ToMeshGeometry3D(),
        Material = PhongMaterials.Yellow,
    };
}

private static List<Vector3> GetBasePolygon(LegPosition legPosition, float width, float thickness, float z)
{
    return legPosition switch
    {
        LegPosition.FrontLeft => new List<Vector3>
        {
            new Vector3(0, 0, z),
            new Vector3(0, -width, z),
            new Vector3(-thickness, -width, z),
            new Vector3(-thickness, -thickness, z),
            new Vector3(-width, -thickness, z),
            new Vector3(-width, 0, z)
        },
        LegPosition.FrontRight => new List<Vector3>
        {
            new Vector3(0, 0, z),
            new Vector3(0, width, z),
            new Vector3(-thickness, width, z),
            new Vector3(-thickness, thickness, z),
            new Vector3(-width, thickness, z),
            new Vector3(-width, 0, z)
        },
        LegPosition.BackLeft => new List<Vector3>
        {
            new Vector3(0, 0, z),
            new Vector3(0, -width, z),
            new Vector3(thickness, -width, z),
            new Vector3(thickness, -thickness, z),
            new Vector3(width, -thickness, z),
            new Vector3(width, 0, z)
        },
        LegPosition.BackRight => new List<Vector3>
        {
            new Vector3(0, 0, z),
            new Vector3(0, width, z),
            new Vector3(thickness, width, z),
            new Vector3(thickness, thickness, z),
            new Vector3(width, thickness, z),
            new Vector3(width, 0, z)
        },
        _ => throw new ArgumentOutOfRangeException(nameof(legPosition))
    };
}

private static List<List<Vector3>> GetSidePolygons(List<Vector3> bottomPolygon, List<Vector3> topPolygon)
{
    var sides = new List<List<Vector3>>();

    for (int i = 0; i < 6; i++)
    {
        var side = new List<Vector3>();
        side.Add(bottomPolygon[i < 5 ? i + 1 : 0]);
        side.Add(bottomPolygon[i]);
        side.Add(topPolygon[i]);
        side.Add(topPolygon[i < 5 ? i + 1 : 0]);
        sides.Add(side);
    }

    return sides;
}
```
And my lights:
```
<helix:AmbientLight3D/>
<helix:DirectionalLight3D Direction="-1,1,-1"/>
<helix:DirectionalLight3D Direction="-1,1, 1"/>
<helix:DirectionalLight3D Direction=" 1,1,-1"/>
<helix:DirectionalLight3D Direction=" 1,1, 1"/>
<helix:DirectionalLight3D Direction="{Binding CameraRackPreview.LookDirection}"/>
```
Generated models are good, but there is some weird lighting happening on them ![screenshot](https://i.imgur.com/cTLAVWa.png)
Front left and back right are working well, but front right and back left are not.
Same thing happens when I apply rotation transform on that "not working" model, so it's not depending on rotation but directly on generation.
By the way, I know I can use rotation transform on the first one to get the others, but I'd still like to know why this is happening and hopefully how to fix it.
I am using latest SharpDX version of Helix with .NET Core.
EDIT: I am moving those models to their position by translate transform.
Thank you in advance!

**Comment by holance** [comment]
Check the normal values. Also you are using too many directional lights.

**Comment by TheSpixxyQ** [comment]
I've read seen those lights somewhere (somebody used four directional), what lights should I only need then?

And yes, it looks like normals are wrong. How does order of polygon points matter? I tried to create just 2D L polygon from only 6 points and used `ComputeNormalsAndTangents()` and if I added those points counter clockwise, it generated good normals, on the other hand if I added them clockwise (both starting from 0, 0), it generated inverted normals. How can I "normalize" this so I don't have to experiment on point order?

Also is my approach even good? Isn't there any better solution for generating my object?

**Comment by holance** [comment]
You only need one directional light if you only have single viewport.

On the other hand, you need to make sure the triangle winding order yourself. Or provide your own correct normal. HelixToolkit calculates the normal based on winding order.

**Comment by TheSpixxyQ** [comment]
Sorry for late response. I got it now, I've played with points order and I've managed to get it working.
Thank you very much!
