### ISSUE TITLE
"CursorOnElementPosition" has deviation.

### ISSUE THREAD

**Issue by J-YingHuang** [helix-toolkit/helix-toolkit#1327]
Hi, I tried to make a measurement tool by helix-toolkit, and used the CursorOnElementPosition function to snap point.
But, this function was snap the error position, such as the following photo...

![SnapPointError](https://user-images.githubusercontent.com/15519334/77029855-e4755000-69d7-11ea-8971-ff96c5a5a7fd.PNG)

Is any idea to solve this problem?
Thanks very much, 
Jing.

**Comment by chrkon** [comment]
Dear Jing,
how do you have realized the snaping function to the elements?

As you can see in the WPF Example Browser - CursorPositionDemo, the OnElementPosition is calculated from the Element surface, but the coordinate is not snaped to the element.

If you put the mouse over the sphere in the mentioned demo, the OnElementPosition is changing in all three dimensions when you move the mouse. So you get a point from the sphere surface, but not a special one. The cursor position is just projected to the surface of the element. 

I take a look on your picture and I assume, that you want to get the distance between the two boxes. If you have used the OnElementPosition from each of the two boxes, you get two positions that are on the surface of boxes, but from theese positions you don't get the shortest distance between the boxes.

You need the center of the boxes to calculate the distance between them. Just calculate the vector from center 1 to center 2 and then calculate the Intersection Points of this vector with box1 and box2. The distance between these intersetion points is the distance of the two boxes.

Kind regards,
Christof (Author of the CursorPositionDemo)

**Comment by chrkon** [comment]
Hi @J-YingHuang have you read my answer?

**Comment by holance** [comment]
Close this issue for now. Reopen if needed.
