### ISSUE TITLE
Viewport black

### ISSUE THREAD

**Issue by KlaskSkovby** [helix-toolkit/helix-toolkit#1330]
If I get the source code, i have no problem debugging the program.

However if i get the package from nuget. 
and set up a basic WPF program as explained here: https://github.com/helix-toolkit/helix-toolkit/wiki/Viewport3DX-Basics"
I get the viewport  when i debug the program and if i click right mouse button it shows the circle in the middle.
But there is no viewcube, and i also tried to add a basic object as explained in "https://github.com/helix-toolkit/helix-toolkit/wiki/Adding-Contents-into-Viewport3DX" without luck

I even tried to add the code from the source code examples.
I have 10.0.17763.0 & 10.0.18362.0 installed
 
I can't get it to work. Any idea what I'm doing wrong/missing?

**Comment by holance** [comment]
You may want to upload a sample code. Make sure you setup `DefaultEffectsManager` binding correctly.

**Comment by KlaskSkovby** [comment]
`using HelixToolkit.Wpf.SharpDX;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System;

public class MainViewModel : INotifyPropertyChanged
{
    private IEffectsManager effectsManager;
    public const string Orthographic = "Orthographic Camera";
    public const string Perspective = "Perspective Camera";
    private string cameraModel;
    private Camera camera;
    public Geometry3D CubeMesh { get; }
    public Material Red { get; }

    public MainViewModel()
    {
        EffectsManager = new DefaultEffectsManager();
        Camera = new PerspectiveCamera();
        var builder = new MeshBuilder();
        builder.AddCube();
        CubeMesh = builder.ToMesh();
        Red = PhongMaterials.Red;

    }
    public IEffectsManager EffectsManager
    {
        get { return effectsManager; }
        protected set
        {
            SetValue(ref effectsManager, value);
        }
    }

    public string CameraModel
    {
        get
        {
            return cameraModel;
        }
        set
        {
            if (SetValue(ref cameraModel, value, "CameraModel"))
            {
                OnCameraModelChanged();
            }
        }
    }

    public event EventHandler CameraModelChanged;
    protected virtual void OnCameraModelChanged()
    {
        var eh = CameraModelChanged;
        if (eh != null)
        {
            eh(this, new EventArgs());
        }
    }


    public Camera Camera
    {
        get
        {
            return camera;
        }

        protected set
        {
            SetValue(ref camera, value, "Camera");
            CameraModel = value is PerspectiveCamera
                                   ? Perspective
                                   : value is OrthographicCamera ? Orthographic : null;
        }
    }

    #region INotifyPropertyChanged
    public event PropertyChangedEventHandler PropertyChanged;

    protected void OnPropertyChanged([CallerMemberName]string info = "")
    {
        if (this.PropertyChanged != null)
        {
            this.PropertyChanged(this, new PropertyChangedEventArgs(info));
        }
    }
    protected bool SetValue<T>(ref T backingField, T value, [CallerMemberName]string propertyName = "")
    {
        if (object.Equals(backingField, value))
        {
            return false;
        }

        backingField = value;
        this.OnPropertyChanged(propertyName);
        return true;
    }`




`<Window x:Class="HelixFun.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:hx="http://helix-toolkit.org/wpf/SharpDX"
        xmlns:local="clr-namespace:HelixFun"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <hx:Viewport3DX Camera="{Binding Camera}" EffectsManager="{Binding EffectsManager}">
            <hx:GroupModel3D>
                <hx:DirectionalLight3D Direction="0, 0, -1" Color="White" />
                <hx:DirectionalLight3D Direction="0, -1, 0" Color="White"/>
            </hx:GroupModel3D>
            <hx:GroupModel3D>
                <hx:SpotLight3D Direction="0, 1, 0" Color="Red" Position="0, -2, 0"/>
                <hx:PointLight3D Position="3, 0, 0" Color="Green"/>
            </hx:GroupModel3D>
            <hx:MeshGeometryModel3D Geometry="{Binding CubeMesh1}" Material="{Binding Red}" />
            <hx:GroupModel3D>
                <hx:MeshGeometryModel3D Geometry="{Binding CubeMesh2}" Material="{Binding Material1}" />
                <hx:MeshGeometryModel3D Geometry="{Binding CubeMesh3}" Material="{Binding Material2}" />
                <hx:MeshGeometryModel3D Geometry="{Binding CubeMesh4}" Material="{Binding Material3}" />
            </hx:GroupModel3D>
        </hx:Viewport3DX>
    </Grid>
</Window>`

**Comment by JeremyAnsel** [comment]
Hello,
Does it work if you get the latest package from the MyGet feed:
https://www.myget.org/F/helix-toolkit/

**Comment by KlaskSkovby** [comment]
@JeremyAnsel I have the latest package from NuGet package manager

**Comment by JeremyAnsel** [comment]
I mean pre-release version 2.12.0-alpha0078

**Comment by holance** [comment]
In your code, where did you bind your view model to your view.

**Comment by KlaskSkovby** [comment]
isn't that what i have done in the Xaml   EffectsManager="{Binding EffectsManager}" ?

**Comment by KlaskSkovby** [comment]
I found the issue.

i needed to add 
DataContext = new MainViewModel();
in the MainWindow.xaml.cs

Thanks for the help guys :D
