### ISSUE TITLE
Camera position 

### ISSUE THREAD

**Issue by KlaskSkovby** [helix-toolkit/helix-toolkit#1335]
Okay so I'm trying to create my own controls for moving around the camera.
However the camera stays at the same position and the model gets clipped instead. 

My code simplifyed is that I get the position and the look direction of the camera. 
Then ill add the normalized lookdirection to the position and change the camera position.
The point is to move it forward in the lookdirection.

public MainViewModel()
    {
        view1 = this;
    }

Point3D getPosition = MainViewModel.view1.Camera.Position;
Vector3D getLookDirection = MainViewModel.view1.Camera.LookDirection;
Point3D newPosition = Point3D.Add(getPosition, LookNormal*10);

MainViewModel.view1.Camera.AnimateTo(newPosition, LookNormal, new Vector3D(0, 1, 0), 100);

The newPosition point changes and the camara changes position when i get the position, however in the viewpoint the camara is still at the same position as seen on the two pictures below.

![image](https://user-images.githubusercontent.com/33638395/78687708-bf983c80-78f4-11ea-83ca-db4ddb0ccc6d.png)

![image](https://user-images.githubusercontent.com/33638395/78687750-ccb52b80-78f4-11ea-834a-bc5c342a5371.png)

**Comment by KlaskSkovby** [comment]
Okay, this took me ages to find out why. 
It was due to using the "Orthographic Camera", by changing to the "Perspective Camera" i was able to create my own keydown events to call the Camera.AnimateTo method and simulate a FirstPerson controller.

But now get screen/model tearing which i don't get with the default keycommands.  
What can the issue be for that?

**Comment by taoyouh** [comment]
An orthographic camera does not change the output (except the clipping) when you move the camera forward or backward. If you want to zoom an orthographic camera, you need to change its width.

**Comment by holance** [comment]
Orthographic Camera width needs to be set correctly.

**Comment by zhaokuohaha** [comment]
@holance It's there any way to change the wheel scroll event to change Camera width , instead the origin action (move camera position)
