### ISSUE TITLE
Example for Viewport3DX.ViewCubeTexture = BitmapExtensions.CreateViewBoxTexture(xxx)

### ISSUE THREAD

**Issue by bhairav-thakkar** [helix-toolkit/helix-toolkit#1336]
When we set left handed coordinate system in Helixtoolkit.wpf.sharpdx, the viewcube (as known) has unchanged texts... One way to rectify that would be to use a custom view cube..

But I guess, a more appropriate way would be to use: Viewport3DX.ViewCubeTexture = BitmapExtensions.CreateViewBoxTexture(xxx). However, I could not find an example of the usage or an example on setting the first parameter : IDevice2DResources.

Could you please help?

**Comment by holance** [comment]
You can get it from effects manager

**Comment by bhairav-thakkar** [comment]
Got it. Thanks :)
