### ISSUE TITLE
Importing Custom Mesh in HelixToolkit.WPF.SharpDX

### ISSUE THREAD

**Issue by McallyD74** [helix-toolkit/helix-toolkit#1339]
I'm trying to make the switch from helix wpf to helix wpf sharpdx in order to make use of the environment map feature. Importing a model in helix wpf seemed to be much easier since I didn't need to understand MVVM to do it, so I feel a bit lost after struggling for the past couple days unsuccessfully.

I took a look at the file load demo and tried to add what I thought was the relevant section of code to my project:
`                    var loader = new Importer();
                    var scene = loader.Load(filepath);
                    GroupModel.AddNode(scene.Root);`
but I don't see anything loaded when I execute the program. Is there a way to get this running easily without diving into MVVM? I'm having trouble wrapping my head around everything in the FileLoadDemo, and I can't get it to build to experiment.

**Comment by holance** [comment]
You don't need MVVM to use helixtoolkit. You can do it all code behind. Just move all things from XAML into code behind and it will work.
