### ISSUE TITLE
Ortographic Camera and Zoom : Tremors

### ISSUE THREAD

**Issue by jeandelarue** [helix-toolkit/helix-toolkit#134]
Hello,

Sorry for my english.

When I use an Ortographic Camera and use zoom by rectangle followed by zoom with mouse wheel, the scene is shaking and there are few graphicals problems.
I made a video for you to see the problem : [Sphere tremors](http://fr.tinypic.com/player.php?v=25i6ql3&s=8#.VRE9V_mG-30)
(don't pay attention to isolated points, it's video encoding problem)

And for you to test, this is the code :  [Source file](http://pastebin.com/tzm4m4ru)
To reproduce the problem, you must :
1) select a region of the viewport. The program will use zoomtorectangle to zoom.
2) then try to zoom out with the middle button of the mouse to come back to previous state
3) repeat the previous operations (1 and 2) multiple times 
You will see :
a) Coordinates of lookDirection and Position increasing in a weird way -> why ?
b) The sphere trembling -> thi should not
c) The rectangle selection drawn triangle by triangle

NB : The problem is not present when using Perspective Camera.

Can you help me ?

Thank you.

**Comment by jeandelarue** [comment]
I tried to figure out where does come from these bugs. I think the method ZoomToRectangle is erroneous. Please refer to the method : "public static void ZoomToRectangle(this ProjectionCamera camera, Viewport3D viewport, Rect zoomRectangle)" in "helix-toolkit/Source/HelixToolkit.Wpf/Helpers/CameraHelper.cs" (line 754).

I made a "fix" (if we can call this a fix..) : I changed line 803 of CameraHelper.cs.
Original one : orthographicCamera.LookDirection = w * distance;
Replacement : orthographicCamera.LookDirection = w * distance * zoomRectangle.Width / viewport.ActualWidth;
With this fix, the LookDirection and Position are proportionate to the Camera width.
But the fix don't solve all bugs. The "c)" (refer to my precedent post) is still there.
Futhermore, with my fix, the position of the camera is not really good, the position of the camera is a little beyond the target.
Therefore it's not really a fix but it's close.

Do you have any workaround that could help ?
Thank you.

**Comment by jeandelarue** [comment]
Correction : My fix (see previous post) is "good". According to my tests, it preserves what the original programmer wanted to do and fix the problem of LookDirection/Position. Is there any expert who can verify that the fix is correct ?

If I'm not mistaken, if we have a rectangle in which an object  is inscribed, then the zoom using this rectangle should give the entire object magnified ?
Even with the perspective camera, the zoom by rectangle don't give always the expected result.
Am I wrong or did I miss something ?
(you can try my program in my second post to check what I mean)
If I am right, then the ZoomToRectangle is completely bugged both in the sense and in the code.

**Comment by jeandelarue** [comment]
I made a new ZoomToRectangle meanwhile someone better than me make the good fix. Here it is :

    public void ZoomToRectangle(OrthographicCamera camera, Viewport3D viewport, Rect zoomRectangle)
    {
        Point center = new Point((zoomRectangle.Left + zoomRectangle.Right) * 0.5, (zoomRectangle.Top + zoomRectangle.Bottom) * 0.5);

        Point3D centerNear, centerFar;
        viewport.Point2DtoPoint3D(center, out centerNear, out centerFar);

        Point curCenter = viewport.Point3DtoPoint2D(camera.Position);

        Point3D curCenterNear, curCenterFar;
        viewport.Point2DtoPoint3D(curCenter, out curCenterNear, out curCenterFar);

        camera.Position = new Point3D(camera.Position.X - (curCenterFar.X - centerFar.X), camera.Position.Y - (curCenterFar.Y - centerFar.Y), camera.Position.Z - (curCenterFar.Z - centerFar.Z));

        double ratio = ((viewport.ActualWidth > viewport.ActualHeight) ? (viewport.ActualWidth / viewport.ActualHeight) : (viewport.ActualHeight / viewport.ActualWidth)) * Math.Sqrt(((zoomRectangle.Width * zoomRectangle.Width) + (zoomRectangle.Height * zoomRectangle.Height)) / ((viewport.ActualWidth * viewport.ActualWidth) + (viewport.ActualHeight * viewport.ActualHeight)));

        if ((camera.Width * ratio) < 0.1)
            return;

        camera.Width *= ratio;

        Vector3D centerNormal = new Vector3D(camera.Position.X - centerFar.X, camera.Position.Y - centerFar.Y, camera.Position.Z - centerFar.Z);
        centerNormal.Normalize();

        double distToRemove = camera.LookDirection.Length * (1 - ratio);
        camera.LookDirection *= ratio;
        camera.Position -= (centerNormal * distToRemove);
    }

NB : As you can see, it's only for OrtographicCamera.

**Comment by chrkon** [comment]
Hello jeandelarue,

To include the method into the CameraHelper Class I had to change it  to `public static void`! 
Then I have used the CameraControlDemo from the examples to test the method.

I have switched the camera to orthographic mode and started with the default values:
LookDirection = -100;-100;-100, Position= 100;100;100, Width = _204.051_
1: ZoomToRectangle > new Width = 28.972
2: ZoomOut by mouse to LookDirection ~ -100;-100;-100 > new Width = _239.298_
3: ZoomToRectangle > new Width = 34.659
4: ZoomOut by mouse to LookDirection ~ -100;-100;-100 > new Width = _280.635_
...
11: ZoomOut by mouse to LookDirection ~ -100;-100;-100 > new Width = _607.949_

It seems, that this code is not working correctly. The width is increasing.

Kind regards,
Christof

**Comment by chrkon** [comment]
Of course the original code has a problem, too.

**Comment by jeandelarue** [comment]
Yes, my ZoomToRectangle is bugged too. It works a bit better than the original but it's bugged.
I'm not a mathematician and I made my ZoomToRectangle with my old math memories.
If there is an expert among us, it will be helpful :)

**Comment by jeandelarue** [comment]
Can you send me your test program ? I used CameraControlDemo but I don't have the same results.

**Comment by chrkon** [comment]
I have just added your code into the file `CameraHelper.cs`. This is the direct link https://github.com/chrkon/helix-toolkit/blob/%23134/Source/HelixToolkit.Wpf/Helpers/CameraHelper.cs. into my Helix-Toolkit Fork. Take a look into lines 797 and 798 of this file. If you remove the comment markers in theese lines your code will be called. 

Kind regards,
Christof

**Comment by jeandelarue** [comment]
Do you think a better way to do the ZoomToRectangle ?
I am doing some research but it leads nowhere.

**Comment by chrkon** [comment]
Sorry, up to now I have no better solution.

**Comment by jeandelarue** [comment]
I made a new ZoomToRectangle, way better. There is no errors in this new method and is a lot faster.

		public void ZoomToRectangle(OrthographicCamera camera, Viewport3D viewport, Rect zoomRectangle)
        {
            Ray3D centerRectangleRay = viewport.GetRay(new Point((zoomRectangle.Left + zoomRectangle.Right) * 0.5, (zoomRectangle.Top + zoomRectangle.Bottom) * 0.5));
            double ratio = ((viewport.ActualWidth > viewport.ActualHeight) ? (viewport.ActualWidth / viewport.ActualHeight) : (viewport.ActualHeight / viewport.ActualWidth)) * Math.Sqrt(((zoomRectangle.Width * zoomRectangle.Width) + (zoomRectangle.Height * zoomRectangle.Height)) / ((viewport.ActualWidth * viewport.ActualWidth) + (viewport.ActualHeight * viewport.ActualHeight)));
            
            if ((centerRectangleRay == null) || ((camera.Width * ratio) < 0.1))
                return;

            camera.Width *= ratio;

            double lenghtToRemove = camera.LookDirection.Length * (1 - ratio);
            camera.LookDirection *= ratio;

            Vector3D normalRay = centerRectangleRay.Direction;
            normalRay.Normalize();

            camera.Position = OrthogonalProjectionPointToLine(camera.Position, centerRectangleRay.Origin, centerRectangleRay.Origin + centerRectangleRay.Direction) + (normalRay * lenghtToRemove);
        }

        private Point3D OrthogonalProjectionPointToLine(Point3D toProject, Point3D p1, Point3D p2)
        {
            double normalX = p2.X - p1.X, normalY = p2.Y - p1.Y, normalZ = p2.Z - p1.Z;
            double dn = (normalX * normalX) + (normalY * normalY) + (normalZ * normalZ);

            if (dn == 0)    // p1 == p2
                return p1;

            double u = ((normalX * (toProject.X - p1.X)) + (normalY * (toProject.Y - p1.Y)) + (normalZ * (toProject.Z - p1.Z))) / dn;

            return new Point3D(p1.X + (u * normalX), p1.Y + (u * normalY), p1.Z + (u * normalZ));
        }

NB : It works only for Ortographic Camera. I will make soon a ZoomToRectangle for all type of Camera.

I was analyzing the source of helix toolkit about Zoom, and I think there are others problems with the mouse Zoom management. There are lack of precisions, e.g : When you zoom in and zoom out with the mouse, you won't return to exactly the same scene. And I think there is one more problem of imprecise calculations with Ortographic Camera when you use mouse gesture (lookDirection and Position are not well calculated).

And finally, the ZoomAroundMouseDownPoint property of Helix Viewport3D should not be called ZoomAroundMouseDownPoint because when you enable it, it zoom when the user scroll with the mouse (OnMouseWheel in helix-toolkit/Source/HelixToolkit.Wpf/Controls/CameraController/CameraController.cs at Line 2261).
It should be called : ZoomToCursorPosition, ZoomToCursor or something like that.
Moreover, when this property is enabled the zoom is not correctly centered relative to cursor position.
I will work on it this weekend.

If you ever experienced some zoom problem, please tell me.
If there is anybody who wants to help me with this, he's welcome.

**Comment by objorke** [comment]
This sounds great! I am looking forward to see a PR :-)

**Comment by chrkon** [comment]
Hi jeandelarue,
nice work :-)

If you work on this issue take a look on my changes #133 / #138  regarding the cursor position properties.

Kind regards,
Christof

**Comment by holance** [comment]
Fixed
