### ISSUE TITLE
PointsVisual3D and LinesVisual3D invisible if applied a mirrored transformation

### ISSUE THREAD

**Issue by markkonst** [helix-toolkit/helix-toolkit#1340]
PointsVisual3D and LinesVisual3D are both invisible if a mirrored transformation is applied to them. In this context a mirrored transformation seems to be any transformation which would change the coordinate system from right to left-handed.

To reproduce:
Create some points in a Points3DCollection and show them in a PointsVisual3D object. No problem so far. Then apply for example a ScaleTransform3D(-1,1,1) and you'll notice the points are not being shown anymore.

**Comment by chrkon** [comment]
@holance - Dear Lunci,
I have added some test code to the WPF "Points and Lines" example ([link to my fork - PointsAnLines Example Source](https://github.com/chrkon/helix-toolkit/tree/issue/%231340-PointsAndLines-Invisible-on-mirrored-transformation/Source/Examples/WPF/ExampleBrowser/Examples/PointsAndLines)) and I can confirm this behaviour.
