### ISSUE TITLE
Problem integrating helix-toolkit into WinForms

### ISSUE THREAD

**Issue by eagle275** [helix-toolkit/helix-toolkit#1341]
Hi,

My teammate found a nice extension to helix toolkit called HelixPlot which basically extends the HelixViewport3D class to draw 3D curves from 3D-point data. 
Now the goal of current development is to put the 3D "world" which is WPF inside a Windows Forms form.
Going from an original Microsoft example I managed that - but I fail with the combination of helix toolkit and this helixplot. When I open the solution in VS (2019) I can even see the 3D world (HelixControl - open the MyControl.xaml) - but upon start and breakpoint / debugging I see that the objects are created - but I don't see anything drawn. 
Did I miss anything important or what can be the reason for my observation?

[Hosting2.zip](https://github.com/helix-toolkit/helix-toolkit/files/4516326/Hosting2.zip)

**Comment by mbreckon** [comment]
Ok. This problem isn't a problem with the Helix Toolkit. The are two fundamental problems (amongst quite a lot of strangeness) in your code...

1) Your class MyControl is missing the constructor and InitializeComponent required for a WPF UserControl...

        public MyControl()
        {
            InitializeComponent();
        }

2) The following code in your Init() method is wrong and should be removed.

            HelixPlot Plot = new HelixPlot() { ShowViewCube = false };
            plot=Plot;

If you do this you will see the graphics display working fine...

![image](https://user-images.githubusercontent.com/4028595/84798666-21f77280-aff3-11ea-87a1-9d10970c7a6a.png)

I believe this issue can be closed.
