### ISSUE TITLE
WPF help wanted with PipeVisual3D and SphereVisual3D

### ISSUE THREAD

**Issue by sandris-b** [helix-toolkit/helix-toolkit#1342]
Hello, see attached. Problem is that sometimes is drawn incorrectly and not filled with color.

Code is only in xaml.
`    
            
            <HelixToolkit:RectangleVisual3D Width="10000" Length="80000" Origin="0,0,8275" LengthDirection="1,0,0" Normal="0,-1,0" Fill="#136d15"/>        
            <HelixToolkit:PipeVisual3D Point1="0 -0 10000" Point2="0 -1000 10000" Diameter="800" InnerDiameter="0" Material="{HelixToolkit:Material Brown}"/>
            <HelixToolkit:SphereVisual3D Center="0 -2000 10000" Radius="1500" Material="{HelixToolkit:Material DarkGreen}"/>`

![Capture](https://user-images.githubusercontent.com/38318458/80494715-a7ee2a00-896f-11ea-8c14-0e06ba12f60e.PNG)

**Comment by sandris-b** [comment]
Also in begining
` <HelixToolkit:HelixViewport3D Grid.Row="1"
                                      Grid.Column="1"
                                      LimitFPS="True"
                                      ZoomExtentsWhenLoaded="True"
                                      ShowViewCube="False"
                                      ShowFrameRate="True"
                                      ShowCoordinateSystem="True"
                                      ModelUpDirection="0 -1 0"
                                      Background="DarkGray"
                                      Margin="5">

            <HelixToolkit:HelixViewport3D.DefaultCamera>
                <PerspectiveCamera FieldOfView="40" LookDirection="2,2,2" UpDirection="0,-1,0"/>
            </HelixToolkit:HelixViewport3D.DefaultCamera>

            <HelixToolkit:SunLight/>`

**Comment by sandris-b** [comment]
It seems like its only happening when you zoom in a lot..

**Comment by holance** [comment]
Try to set those model diameter to a smaller value/range. I suspect it is caused by floating point precision error.

**Comment by sandris-b** [comment]
Hi @holance, thank you for your answer, I was also thinking about floating point, but if it's the case it is not acceptable, by framework like this, this is very disappointing, I hope, I will not be forced to change helix to something else only by this issue...I did a quick diameter shrink to 100 and it's still the same, but it's only appearing when camera is zooming in a lot, maybe it could be camera issue?

**Comment by sandris-b** [comment]
![Capture](https://user-images.githubusercontent.com/38318458/80873498-a0a58400-8cc1-11ea-9084-0f8e56d5524c.PNG)

**Comment by sandris-b** [comment]
![Capture](https://user-images.githubusercontent.com/38318458/80873656-cc753980-8cc2-11ea-96f6-4a023eda37ee.PNG)
Like whole picture...

**Comment by holance** [comment]
It seems more like z fighting issue.

**Comment by sandris-b** [comment]
its 50 difference between road and whites and it's still displayed incorrectly, any advice?

**Comment by sandris-b** [comment]
![Capture](https://user-images.githubusercontent.com/38318458/80969805-d9a93a00-8e22-11ea-8fe4-f0a8cc2783c4.PNG)

**Comment by sandris-b** [comment]
Anyone?

**Comment by sandris-b** [comment]
Here is another test - 
`<Window x:Class="WpfApp1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApp1"
        xmlns:HelixToolkit="clr-namespace:HelixToolkit.Wpf;assembly=HelixToolkit.Wpf"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>

        <HelixToolkit:HelixViewport3D Grid.Row="1"
                                      Grid.Column="1"
                                      LimitFPS="True"
                                      ZoomExtentsWhenLoaded="True"
                                      ShowViewCube="True"
                                      ShowFrameRate="True"
                                      ShowCoordinateSystem="True"
                                      ModelUpDirection="0 -1 0"
                                      Background="SkyBlue"
                                      Margin="5">

            <HelixToolkit:HelixViewport3D.DefaultCamera>

                <PerspectiveCamera FieldOfView="60"                                                                      
                                   LookDirection="-34391,44059,51959"
                                   UpDirection="0,-1,0"
                                   Position="2238 0 815"/>

            </HelixToolkit:HelixViewport3D.DefaultCamera>

            <HelixToolkit:SunLight/>

            <HelixToolkit:RectangleVisual3D Width="6550" Length="80000" Origin="0,0,0" LengthDirection="1,0,0" Normal="0,-1,0" Material="{HelixToolkit:Material Gray}"/>
            <HelixToolkit:RectangleVisual3D Width="10000" Length="80000" Origin="0,0,8275" LengthDirection="1,0,0" Normal="0,-1,0" Fill="#136d15"/>

            <HelixToolkit:PipeVisual3D Point1="0 -0 1000" Point2="0 -100 1000" Diameter="800" InnerDiameter="0" Material="{HelixToolkit:Material Brown}"/>
            <HelixToolkit:SphereVisual3D Center="0 -200 1000" Radius="150" Material="{HelixToolkit:Material DarkGreen}"/>

        </HelixToolkit:HelixViewport3D>
    </Grid>
</Window>`
![Capture](https://user-images.githubusercontent.com/38318458/81532406-fdadd380-936c-11ea-8018-db721356f6e0.PNG)

**Comment by sandris-b** [comment]
And it works fine if I remove those two "backgrounds", so where is the issue, how to fix it?
` <HelixToolkit:RectangleVisual3D Width="6550" Length="80000" Origin="0,0,0" LengthDirection="1,0,0" Normal="0,-1,0" Material="{HelixToolkit:Material Gray}"/>
        <HelixToolkit:RectangleVisual3D Width="10000" Length="80000" Origin="0,0,8275" LengthDirection="1,0,0" Normal="0,-1,0" Fill="#136d15"/>`

**Comment by sandris-b** [comment]
Ok, I fixed it by adding ` FarPlaneDistance="800000"
                                   NearPlaneDistance="2000"`
