### ISSUE TITLE
How i can make a Bitmap from 3D Viewport

### ISSUE THREAD

**Issue by Dokman** [helix-toolkit/helix-toolkit#1346]
Hi guys i need to make a thumbnail from my viewport instead of a window, the thumbnail has only to contain the 3D model loaded, how i can do it? i can't with ScreenCapture because it takes a shot from the Window

**Comment by holance** [comment]
Viewport.SaveBitmap

**Comment by Dokman** [comment]
sorry for beign a jerk XD
