### ISSUE TITLE
BillboardText3D is not shown, if origin (0;0;0) is not visible in the view.

### ISSUE THREAD

**Issue by chrkon** [helix-toolkit/helix-toolkit#1349]
I think I have found a bug in the BilboardText3D rendering. 
In my project I use WPF.SharpDX and I try to create some Billboard texts with the BillboardTextModel3D type. I bind the Geometry property to a BillboardText3D object and add some TextInfo objects. Like in the BillboardDemo.

Then I set the Camera position and the ViewDirection in that way, that the origin (point 0;0;0) is not visible. Now the Billboard texts will not be rendered. But if the origin is visible in the view, all Billboard texts are visible immediately. Even when I rotate or pan the view the Billboard texts become visible when the origin is comming into sight.

I try to create a small example to reproduce the bug. Has anybody an idea how I can fix this? Suggestions are highly requested.

**Comment by holance** [comment]
Set enable frustum to false

**Comment by chrkon** [comment]
Hi Lunci, 
many thanks for the fast answer. I have changed the setting and it has solved the problem.

So setting *EnableRenderFrustum="False"* is a possible solution. But I don't understand this behaviour. The billboard text will also be hidden, if there is no text at the origin position. So all Billboard Text is the view, but the billboards are not visible until the origin point comes into sight, 

But I wonder if I do something wrong. I have multiple (200) boxes placed at different positions. Now I want to put a label at each of the boxes. So should I use one *BillboardTextModel3D* with a *BillboardText3D* containing 200 *TextInfo* instances or should I use 200  *BillboardTextModel3D* with each have one *BillboardSingleText3D* in it?

**Comment by holance** [comment]
Maybe it is a bug on calculating the boundary.
Prefer to use single model to contain all billboards. Unless individual billboard is being changed frequently.
