### ISSUE TITLE
Accuracy on Hit Tests of Small Models

### ISSUE THREAD

**Issue by taoyouh** [helix-toolkit/helix-toolkit#1353]
When I try to perform hit test on a very small model (sizes about 0.001), the result seems inaccurate. The objects at the bottom are clicked rather than the objects on top commonly. When the same model was scaled up into sizes of about 50, the problem no longer exists.

I think this may be relative to the way that bounding box was created: https://github.com/helix-toolkit/helix-toolkit/blob/c8533f1dd70966ef5768ea689f97a3d011360a79/Source/HelixToolkit.SharpDX.Shared/Extensions/BoundingBoxExtensions.cs#L46

As CAD models being extremely large or extremely small is common, is it possible that these codes are changed to a more relative way, like changing the 0.0001f into a portion of the coordinates of "max" and "min"?

Version: HelixToolkit.Wpf.SharpDX 2.11.0

**Comment by holance** [comment]
Which version are you using?

**Comment by taoyouh** [comment]
Sorry for forgetting that.
I'm using HelixToolkit.Wpf.SharpDX 2.11.0

**Comment by holance** [comment]
I don't think it is the bound issue, the actual hit test is per triangle based.
Are you able to create a sample to show this issue? Another possibility is the floating point losses accuracy on small object.

**Comment by taoyouh** [comment]
It seems that triangles smaller than 0.001f can't be clicked. My experiments show that it is only relative to the size of the triangle but not the size of the model.

## Sample code
### Project
WPF on .NET Framework 4.8.
HelixToolkit.Wpf.SharpDX 2.12.0
### MainWindow.xaml.cs
The namespace is not included for simplicity.
```
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();

            {
                MeshBuilder builder = new MeshBuilder();
                builder.AddTriangle(
                    new Vector3(-0.0005f, 0, 0.0001f),
                    new Vector3(0, 0.0005f, 0.0001f),
                    new Vector3(0.0005f, 0, 0.0001f));
                builder.AddTriangle(
                    new Vector3(0.0005f, 0, 0.0001f),
                    new Vector3(0, 0.0005f, 0.0001f),
                    new Vector3(0.0005f, 0, 0.0001f));
                builder.AddTriangle(
                    new Vector3(0.0005f, 0, 0.0001f),
                    new Vector3(0, -0.0005f, 0.0001f),
                    new Vector3(0.0005f, 0, 0.0001f));
                builder.AddTriangle(
                    new Vector3(0.0005f, 0, 0.0001f),
                    new Vector3(0, -0.0005f, 0.0001f),
                    new Vector3(-0.0005f, 0, 0.0001f));

                model1.Geometry = builder.ToMeshGeometry3D();
            }

            {
                MeshBuilder builder = new MeshBuilder();
                builder.AddTriangle(
                    new Vector3(-0.002f, 0, 0),
                    new Vector3(0, 0.002f, 0),
                    new Vector3(0.002f, 0, 0));
                model2.Geometry = builder.ToMeshGeometry3D();
            }
        }

        private void viewport_MouseDown(object sender, MouseButtonEventArgs e)
        {
            var position = e.GetPosition(viewport).ToVector2();

            if (viewport.FindNearest(position, out Vector3 point, out Vector3 normal, out object model))
            {
                if (model == model1)
                {
                    Debug.WriteLine("Model 1 clicked.");
                }
                else if (model == model2)
                {
                    Debug.WriteLine("Model 2 clicked.");
                }
            }
        }
    }
```

### MainWindow.xaml
The top-level Window node is not included for simplicity.
```
    <Grid xmlns:hx="http://helix-toolkit.org/wpf/SharpDX">
        <hx:Viewport3DX x:Name="viewport" MouseDown="viewport_MouseDown">
            <hx:Viewport3DX.EffectsManager>
                <hx:DefaultEffectsManager />
            </hx:Viewport3DX.EffectsManager>
            <hx:Viewport3DX.Camera>
                <hx:OrthographicCamera x:Name="camera"
                                       Position="0,0,0.02"
                                       LookDirection="0,0,-0.02"
                                       Width="0.01"/>
            </hx:Viewport3DX.Camera>
            <hx:MeshGeometryModel3D x:Name="model2">
                <hx:MeshGeometryModel3D.Material>
                    <hx:DiffuseMaterial DiffuseColor="Red"/>
                </hx:MeshGeometryModel3D.Material>
            </hx:MeshGeometryModel3D>
            <hx:MeshGeometryModel3D x:Name="model1">
                <hx:MeshGeometryModel3D.Material>
                    <hx:DiffuseMaterial DiffuseColor="Blue" />
                </hx:MeshGeometryModel3D.Material>
            </hx:MeshGeometryModel3D>
        </hx:Viewport3DX>
    </Grid>
```

## Reproduce Steps
1. Debug in Visual Studio
2. Click on the blue square (model 1)
3. Click on the red triangle (model 2)

No matter where you click, the debug output will never show "model 1 clicked". If you clicked on the red triangle or the region above the red triangle, the debug output will show "model 2 clicked".

Expected: When I click on the blue square, the debug output should say "model 1 clicked".

**Comment by holance** [comment]
Fixed.
