### ISSUE TITLE
Viewport doesn't update until clicking in it

### ISSUE THREAD

**Issue by messyprogrames** [helix-toolkit/helix-toolkit#1354]
I have some meshes in a Viewport3DX with bindings for their geometry and material. Elsewhere in the WPF form, you can update the property that is bound to the material, but the material won't update until you click in the viewport. Is there a way to make the viewport update once the property is updated?

**Comment by holance** [comment]
It should update automatically. Are you able to create a sample?

**Comment by messyprogrames** [comment]
Sure, I've put a sample project here as close to the original. If it matters, this is ultimately being used for a plugin in Revit. I thought it would work once we pulled it out of the Revit context, but the same problem persists, so now I suspect it's something silly :) 
In a similar vein, we've been trying to create a PhongMaterial with an image for the Diffuse map but we haven't been able to get the image to apply. Any chance you could tell us what we're doing wrong there as well?
thanks in advance!

https://github.com/messyprogrames/HelixTest

**Comment by holance** [comment]
Well, when you use mesh builder to generate cubes, you disable the normal and texture coordinates. That's why your image is not showing up.

**Comment by messyprogrames** [comment]
Sweet, now the image is showing in that sample project, but even after we made the updates to the MeshBuilders in our Revit plugin, there's still no image showing on either Phong or Diffuse materials.  Do you know what might be causing the problem once this is loaded from Revit?

**Comment by holance** [comment]
You need to make sure your model has correct texture coordinates.
