### ISSUE TITLE
Loading animation 

### ISSUE THREAD

**Issue by Pprop11** [helix-toolkit/helix-toolkit#1355]
Hello, I'm working on my university project now using WPF and helix toolkit. I have animated door model in .blend and I can load this model to my project but I don't know how to play animation from file e.g. by button click.   So, I have a question, can I run an animation from file using helix toolkit or it is impossible?

Thanks in advance!

**Comment by holance** [comment]
If you are using helixtookit.assimp for loader, if assimp supports loading .blend animation, then it will work. Otherwise animation is not loaded.

**Comment by Pprop11** [comment]
> If you are using helixtookit.assimp for loader, and assimp supports loading .blend animation, then it will work. Otherwise animation is not loaded.
Is there function or class to import fbx or blend file in helixtoolkit.assimp? I found only obj and 3ds readers.

**Comment by holance** [comment]
Helixtoolkit assimp is only available for helixtoolkit SharpDX version.
