### ISSUE TITLE
Using custom material variable to pass parameters to PointLine shaders

### ISSUE THREAD

**Issue by aparajit-pratap** [helix-toolkit/helix-toolkit#1358]
I am trying to pass custom parameters (state) to my own point and line shaders, so that I can color the geometry depending on whether it is in a selected/unselected state, etc. For this I tried to use the `pfParams` field from the `PointLineMaterialStruct` in the shader for which I did the following steps:
1. Overrode `PointNode.OnCreateRenderCore` to create a custom `PointLineRenderCore` 
2. Defined a render technique using my custom .hlsl shaders and added to a custom `EffectsManager` class
3. Defined a custom `MaterialCore` class with an overridden `CreateMaterialVariables` method to initialize ...
4. A custom `MaterialVariable` class in which I overrode the `OnInitialPropertyBindings` method to add my custom property bindings for the above states

However, this doesn't seem to work. The `CreateMaterialVariables` does not seem to be getting invoked in the first place. The above changes can be found here: https://github.com/DynamoDS/Dynamo/pull/10709

Any advice on whether the above approach is correct or any documentation on how to write a custom material variable to pass additional data to the pointline shaders would be really useful.

**Comment by holance** [comment]
I think you don't need to create separate shader to do this. You can create a separate mesh and model to render selected points and lines.

**Comment by aparajit-pratap** [comment]
@holance could you elaborate on what you mean by creating a separate model. We already have custom mesh shaders that work with different rendering states. 

We wanted to achieve the same performance with point and line shaders to be able to uniformly apply a selection color, for example, to all points rather than set a single color on each vertex individually. I guess the alternative solution would be is to apply the selection color to the Point3D model after enabling point blending. Is that correct?

**Comment by holance** [comment]
Point line models already have a global color property. Why not just set the global property to be the selection color?

**Comment by mjkkirschner** [comment]
Hi @holance - yes we can use Color to set the selection color.

Unfortunately we have around 6 states we need to support that all effect the color of line and point geometry in various ways, some in combination with each other.

We can likely solve the issue for points with the blending and enable/disable blending params that were added to the helix point shader - but we would need the same mechanism for line rendering.

This is also of course, not as flexible as possible and ideally we would just be able to add a pixel shader to the end of the pipeline for lines and points.

I cannot even get points to display when I completely recreate the `points` technique from the buitli-n helix shaders and try to attach it as my own shader with a new name.

Any help would be appreciated, I can create a small sample reproing the issue if needed.

**Comment by holance** [comment]
A sample code will be very helpful.

**Comment by mjkkirschner** [comment]
Hi @holance we actually figured out how to get the points displaying atleast when using our own `PointLineRenderCore`  `PointGeometry3d` and `PointSceneNode` classes to hook up the custom shader.

What we were missing was when creating the `PointNode` - we needed to set the `material` in the initializer like:

```
 protected override SceneNode OnCreateSceneNode()
        {
            return new DynamoPointNode() { Material = material };
        }
```
we now have a working example with a vertex shader, geometry shader, and pixel shader. But we cannot figure out how to pass data to the material or to attach our own materialVariable.

**Comment by mjkkirschner** [comment]
if we want to add our own constant buffer for a specific geometry type is this the best existing example?

https://github.com/helix-toolkit/helix-toolkit/blob/develop/Source/HelixToolkit.SharpDX.Shared/Core/CrossSectionMeshRenderCore.cs

**Comment by holance** [comment]
It depends on whether you want to create a special scene node or material. 
The point line constant buffer still have 2 empty padding slots you can use.
Simply change the padding slots to your own variable and set the value in a custom LineMaterialVariable.
Use those two variables in your own pixel shader. It should work.

**Comment by mjkkirschner** [comment]
@holance thank you for your reply - for approach 1 - using the padding slots, it appears they are not public fields of the struct, did you mean using reflection? Or is there some other way?

for approach 2 - creating a constant buffer and binding it, I am very interested in understanding how do do that correctly.

**Comment by holance** [comment]
If you want to use the padding slot, you need to create a custom `PointLineRenderCore` with your own `PointLineModelStruct` with those two fields customized. You can still use same point line materials.

**Comment by holance** [comment]
I added an example to show how to use your own constant buffer. #1360
You may need to use the nightly build, otherwise you may have to duplicate the codes for PointMaterialCore/PointMaterialVariables/PointMaterial.
