### ISSUE TITLE
Bug? in GridLinesVisual3D - NormalVector = 1;0;0 will not work

### ISSUE THREAD

**Issue by chrkon** [helix-toolkit/helix-toolkit#136]
I wanted to create a GridLines Visual in the YZ plane). I used the following XAML code for this:
`<helix:GridLinesVisual3D Normal="1,0,0" />`

Unfortunatedly nothing is shown on the screen. I have take a look into the sources and found the following code in file `GridLinesVisual3D.cs`
```    
protected override MeshGeometry3D Tessellate()
    {
        this.lengthDirection = this.LengthDirection;
        this.lengthDirection.Normalize();
        this.widthDirection = Vector3D.CrossProduct(this.Normal, this.lengthDirection);
        this.widthDirection.Normalize();
```

If I use the XAML line as above, the CrossProduct of *this.Normal* and *this.LengthDirection* will be [0;0;0]! That seems to be the reason for the issue.  

If I change the XAML code this way 
`<helix:GridLinesVisual3D Normal="1,0,0" LengthDirection="0,0,1" />`
everything is OK.

I think this is a little Bug, because setting just the NormalVector is the normal way to use this Item.

Kind regards,
Christof

**Comment by objorke** [comment]
I think the length direction could be overridden if it is coincident with the normal.
It should be possible to set normal to (0,0,1), (0,1,0) or (1,0,0) without changing the length direction.

**Comment by chrkon** [comment]
OK, I will fix this.

**Comment by chrkon** [comment]
Uuuups, this is a bigger bug. 
I have solved the Issue for NormalVector (1,0,0) but the NormalVector (1,0,1) is still buggy. 
(1,0,1) looks equal to (0,0,1) if the Grid is drawn.
