### ISSUE TITLE
Start animation by button click

### ISSUE THREAD

**Issue by Pprop11** [helix-toolkit/helix-toolkit#1364]
Hi again, im trying to start animation of my fbx model by button click. I use ObservableCollection<Animation> Animations. What is the easiest way to do it ,better in c# code? 
I tried to use code from FileLoadDemo example but it gives an error in SetValue(ref ..) and honestly i dont understand what to do with that.

**Comment by holance** [comment]
What's the error you get? Could you provide an sample fbx you are trying to load?

**Comment by Pprop11** [comment]
> What's the error you get? Could you provide an sample fbx you are trying to load?

I think the problem was in XAML code.I've deleted bindings in xaml and bind everything in c# code. After that everything worked fine.  Now all animations of my fbx model is in combobox, but i don't now how to start animation, because checkbox from sample isnt working .

**Comment by Pprop11** [comment]
> What's the error you get? Could you provide an sample fbx you are trying to load?

I still don't know what is wrong in my code. Everything except starting animation is working. In FileLoadDemo animation starts when i click on checkbox, am i right? Maybe the problem in my 3d model? Can you check it, please?

[doormodel1.zip](https://github.com/helix-toolkit/helix-toolkit/files/4742264/doormodel1.zip)

**Comment by holance** [comment]
There is a check box to enable animation in FileLoadDemo. You need to enable it to start animation.

**Comment by mbreckon** [comment]
Loading this in the FileLoadDemo, checking the "Enable animation" checkbox and then selecting an animation using the dropdown works fine. I've also opened the file in Autodesk FBX review and the animation plays there too. 

It sounds like this is a WPF databinding or general application code problem rather than a Helix issue.

**Comment by Pprop11** [comment]
> Loading this in the FileLoadDemo, checking the "Enable animation" checkbox and then selecting an animation using the dropdown works fine. I've also opened the file in Autodesk FBX review and the animation plays there too.
> 
> It sounds like this is a WPF databinding or general application code problem rather than a Helix issue.

Yes, problem was in bindings. I think it was because i bound datacontext in XAML code, when i bound it in c# all started to work.
