### ISSUE TITLE
HelixToolkit.UWP (version: 2.12 or 2.11) Failed to assign to property

### ISSUE THREAD

**Issue by sdanev** [helix-toolkit/helix-toolkit#1365]
I am getting the followed error:
Failed to assign to property 'HelixToolkit.UWP.Element3D.IsRendering'. [Line: 0 Position: 0]  
(some times the error is different, but similar) 
UWP Target Framework: Windows 2004 (19041) or Windows 1903 (18362)
UWP Min Framework: Windows 1903 (18362)
HelixToolkit.UWP version: 2.12 or 2.11
The error do not exist in version : 2.10 or previous

namespace Test3DApp1 {
    public sealed partial class MainPage : Page {

        public MainPage() {
            this.InitializeComponent();

            //var effectsManager = new HelixToolkit.UWP.DefaultEffectsManager();
            //var modelContainer3D = new HelixToolkit.UWP.ModelContainer3DX() { Name = "modelContainer3D", EffectsManager = effectsManager };

            var viewport3DX = new HelixToolkit.UWP.Viewport3DX();
            viewport3DX.Name = "Viewport3DX";

            //viewport3DX.SharedModelContainer = modelContainer3D;

            gGrid.Children.Add(viewport3DX);
        }
    }
}

**Comment by holance** [comment]
Could you upload a sample test app for this issue?

**Comment by sdanev** [comment]
Please find attached sample test app.
@
[Test3DApp1.zip](https://github.com/helix-toolkit/helix-toolkit/files/4742931/Test3DApp1.zip)

**Comment by holance** [comment]
Could you try the latest nightly build from myget?

**Comment by sdanev** [comment]
> Could you try the latest nightly build from myget?

Same error in 2.13.0-alpha0049 as in 2.12.

**Comment by holance** [comment]
I am able to run the sample if linking the helixtoolkit source directly. Not sure why nuget package fails. Maybe there are some differences on the appveyor build system.

**Comment by sdanev** [comment]
It is possible the problem can be related to the: Helixtoolkit Reference Runtime Directives 
https://docs.microsoft.com/en-us/dotnet/framework/net-native/runtime-directives-rd-xml-configuration-file-reference?redirectedfrom=MSDN

**Comment by SnowyWreath** [comment]
@holance, @JeremyAnsel, or @sdanev, has anyone developed a workaround for this issue and #1310, which seems related? I'm stuck back on 2.10 because of this. My machine is running 1809 and that's what my app targets. I can get the UWP sample working in Release configuration, but I encounter the exception in Debug configuration. I tried playing with the configuration settings to see what made the difference, and I wasn't successful.

**Comment by holance** [comment]
Not sure what is the issue yet, haven't had time to investigate.

**Comment by holance** [comment]
The issue seems to be caused by property conflicts.
In order to fix the issue, we renamed `Transform3D` to `HxTransform3D` in all models.
Please try with latest nightly build.

**Comment by holance** [comment]
Following breaking changes have been made to fix the DP conflict issue:
- Transform3D renames to HxTransform3D. The Transform3D is a DP in UWP UIElement, which is not able to override.
- Gesture bindings for UWP Viewport3DX have been moved into Viewport3DX.ManipulationBindings from Viewport3DX.InputBindings.

**Comment by SnowyWreath** [comment]
@holance excellent, yes the UWP demo is now working for me when targeting Win10 1809, using the current develop branch

**Comment by holance** [comment]
Cool, I will try to release a new version this weekend.
