### ISSUE TITLE
Load 3d model and then cut hole on the surface of model 

### ISSUE THREAD

**Issue by muhndkalil** [helix-toolkit/helix-toolkit#1372]
Hi I used the helixtoolkit in my wpf project and its very good tool I learned how to load stl file of the 3d model and use the cut plane to cut the 3d model but I wonder if I can make my cut by circle shape or making holes on the 3d model or make my cut by another 3d body how to do that please

**Comment by holance** [comment]
You need to use other meshing library. Helixtoolkit is more used for rendering instead of manipulation.

**Comment by muhndkalil** [comment]
Ok I will use csg library
