### ISSUE TITLE
ShadowMap3D resolution issue

### ISSUE THREAD

**Issue by rapidengineering** [helix-toolkit/helix-toolkit#1377]
Hello,

I am using HelixToolkit.Wpf.SharpDX, but I am having an issue displaying the shadowmap.  The shadowmap is not covering the whole scene. I already tried to change the resolution but the shadowmap does not get any bigger.

`        <hx:DirectionalLight3D Name="light1" Color="White"  Direction="0,-1,-10"></hx:DirectionalLight3D>
                              
  <hx:ShadowMap3D  Name="shadowmap"  Resolution="2048,2048"></hx:ShadowMap3D>
                            </hx:Viewport3DX>`

Are there any solutions for this issue?

Thanks in advance!

![image](https://user-images.githubusercontent.com/46933603/87417549-a75d4b00-c5d0-11ea-8732-eef34e393bb5.png)

**Comment by rapidengineering** [comment]
> Try to increase the distance property in ShadowMap3D.

Tried this without result.  I played around with all the properties of shadowmap3D but I cant get shadows when the model is away from the origin.

I made a small example program to test shadowmapping, same problem. 

See below code.

![image](https://user-images.githubusercontent.com/46933603/87512690-c367f780-c677-11ea-9dd0-5e17925dd3a9.png)

```
     <hx:AmbientLight3D Color="DarkGray"></hx:AmbientLight3D>
        <hx:DirectionalLight3D  Direction="1,1,-10"></hx:DirectionalLight3D>
        <hx:ShadowMap3D Distance="100" Intensity="0.1" Resolution="2048,2048"></hx:ShadowMap3D>
```

```
 //floor
            var mesh = new MeshBuilder();
            mesh.AddBox(new Vector3(0, 0, 0), 1000, 1000, 10);
            var floormodel = new MeshGeometryModel3D();
            var mat = PhongMaterials.Blue;
            mat.RenderShadowMap = true;
            floormodel.Material = mat;
            floormodel.Geometry = mesh.ToMeshGeometry3D();
            viewport.Items.Add(floormodel);

            //boxes
            AddBox(new Vector3(0, 0, 50), 50);
            AddBox(new Vector3(0, 100, 50), 50);
            AddBox(new Vector3(0, 200, 50), 50);
            AddBox(new Vector3(0, 300, 50), 50);


        }

        private void AddBox(Vector3 pos,float size)
        {        
            var mesh = new MeshBuilder();
            mesh.AddBox(pos, size, size, size);

            var model = new MeshGeometryModel3D();
            model.IsThrowingShadow = true;

            var mat = PhongMaterials.Red;
            model.Material = mat;
            model.Geometry = mesh.ToMeshGeometry3D();
            viewport.Items.Add(model);
        }
```

**Comment by holance** [comment]
Shadow map is rendered by an orthographic camera, there are multiple properties to setup this camera in ShadowMap3D.
Or you can specify your own LightCamera to render the shadow. The camera has to cover your whole scene to be able to show the shadow.

**Comment by rapidengineering** [comment]
Got it working by setting the LightCamera, thanks.
