### ISSUE TITLE
How to Manage Multiple Scenes Imported

### ISSUE THREAD

**Issue by McallyD74** [helix-toolkit/helix-toolkit#1382]
I am importing multiple models into helixtoolkit, but I don't know the proper way to handle them. Should I keep them all as separate scenes, or is there a way to merge the nodes into a single scene? My use case involves importing objects separately for ease of life, but after they're in, I don't need to store them as separate scenes for any reason that I'm aware of, and it would make traversing the nodes easier if I only had one root. 

For object selection, is it possible to select a complete object or will objects always be separated by materials? For instance if I import a cube with a separate material for each face into the fileload demo, it treats each of the faces as a separate node. I want to handle selection of the cube as a whole.

**Comment by holance** [comment]
You can add multiple scene root under same group model, then you can show multiple scene together.

Helixtoolkit has no idea what complete model means. You have to figure out the complete model yourself by your scene structure.
