### ISSUE TITLE
How to implement simple 3D geometry function?

### ISSUE THREAD

**Issue by WangWeiQiang230** [helix-toolkit/helix-toolkit#1392]
Like CAD or Revit, data is geometry description, instead of mesh data, so user can modify later.
For example: A circle curve on XOY, described as center point p and radius r.
To implement above:
Which class should be inherited?
How to render?
Or anything else?

**Comment by holance** [comment]
You may want to create your own view model to convert the parameters into geometry. Helixtoolkit is a presentation layer, what you described seems to be business logic.
