### ISSUE TITLE
How to Implement Interaction Capable Volumes

### ISSUE THREAD

**Issue by McallyD74** [helix-toolkit/helix-toolkit#1393]
I am trying to create invisible volumes made from an image texture applied to a MeshGeometryModel3D containing a flattened cube. I want the volume to remain invisible until the cursor hovers above it, at which point the image texture becomes visible. I have run into two problems: If I make the volume invisible by setting the diffuse color to transparent, then the Mouse3DDown doesn't trigger. Secondly, the Mouse3DMove event doesn't occur unless the mouse button is down. 

So is there a good way to make a MeshGeometryModel3D invisible yet still trigger the Mouse3DDown event? Is there an efficient way to fire an event whenever the cursor hovers over the MeshGeometryModel3D?

![image](https://user-images.githubusercontent.com/63072224/91176207-8bf15f80-e6a7-11ea-9441-215ab919995f.png)
In the above image you can see the best answer I have come up with so far. I set the flattened cube diffuse material's DiffuseColor = Color.FromAbgr(00999999) when the volume is unselected, and set it to white when it is. This causes the diffuse map to show completely when clicked rather than just a shadow.

**Comment by holance** [comment]
Are you using wpf or SharpDX version?
