### ISSUE TITLE
Please provide a way to access exceptions from the Assimp Importer

### ISSUE THREAD

**Issue by dfraska-ftl** [helix-toolkit/helix-toolkit#1394]
The ErrorCode enum returned from Importer.Load hides the exceptions thrown from Assimp, which are far more descriptive than a simple "Failed" code.

**Comment by holance** [comment]
The exception message is logged. You can attach your own log by implementing the ILog interface and provided it in AssimpImporter.Configuration.Logger.

**Comment by dfraska-ftl** [comment]
Thank you for the response. I would still consider that a workaround, though. The exception itself could easily be exposed without breaking existing code.

**Comment by holance** [comment]
Added `AssimpImporter.AssimpExceptionOccurred` handler in case you want to handle the exception yourself.
