### ISSUE TITLE
Can I get 3D Model's silhouette edge by helixtoolkit?

### ISSUE THREAD

**Issue by ghost** [helix-toolkit/helix-toolkit#1397]

**Comment by holance** [comment]
Helix toolkit Sharp dx version supports this.

**Comment by thienmenh294** [comment]
Can you give me an example?
PostEffectMeshBorderHighlight ?
but I couldn't get the visible line and the hidden line from it because it was light
can you help me?

**Comment by thienmenh294** [comment]
![vidu](https://user-images.githubusercontent.com/67280714/92920082-a92a7a00-f46c-11ea-807b-025a45f0587b.png)

**Comment by thienmenh294** [comment]
![Capture](https://user-images.githubusercontent.com/67280714/92921241-a9c41000-f46e-11ea-8c9e-7eb1c9594997.PNG)

**Comment by thienmenh294** [comment]
![Untitled](https://user-images.githubusercontent.com/67280714/92921679-7930a600-f46f-11ea-9c49-2cb14c90f076.png)

but I want
![Capture - Copy](https://user-images.githubusercontent.com/67280714/92921709-8c437600-f46f-11ea-9831-c8c48480cf64.PNG)

**Comment by holance** [comment]
Currently there's no support for such advanced edge detection

**Comment by thienmenh294** [comment]
![Capture](https://user-images.githubusercontent.com/67280714/93410282-aea41c00-f8d3-11ea-9e23-66a2ba257ad7.PNG)
Can I change color parts of the tube?

**Comment by holance** [comment]
You need to apply a texture mapping on your tube to show color on different parts. Or separate the tube into different parts.

**Comment by thienmenh294** [comment]
![Untitled](https://user-images.githubusercontent.com/67280714/94647499-84b71480-032b-11eb-973a-fbdd174f1701.png)
With my points, I get only the left one

**Comment by thienmenh294** [comment]
![Capture](https://user-images.githubusercontent.com/67280714/94647651-e24b6100-032b-11eb-81cd-e08e9c7d4ff3.PNG)
IsTransparent = true, I can see backside points but I cannot select them. Is there any way?

**Comment by holance** [comment]
Hit test returns a list of hit results sorted by distance. You need to find your point model from the list

**Comment by thienmenh294** [comment]
Cannot use point model mousedown3d event?

**Comment by holance** [comment]
Because you are trying to hit a model behind another model, the mouse down will not be triggered on the model behind. 
Or you can set the front model `HitTestVisible = false` to disable the hit test, then the event on point model will be triggered.

**Comment by thienmenh294** [comment]
HitTestVisible = false is great! Thank you very much!

**Comment by thienmenh294** [comment]
This is my Obj file
![Capture](https://user-images.githubusercontent.com/67280714/94872755-60bd1580-0488-11eb-9b62-5a50cc504ff4.PNG)
with assimp, I cannot read "\". Is there any way?

**Comment by thienmenh294** [comment]
![Capture](https://user-images.githubusercontent.com/67280714/94928947-6144c300-04ff-11eb-8135-37e7028673e2.PNG)
I want to zoom fit in helixtoolkit.wpf.sharpdx. Can I do that?
![Uploading Capture2.PNG…]()

**Comment by holance** [comment]
We only have zoom extend, which uses the approximate bound to fix the viewport. I don't think it can fit like this perfectly.

**Comment by thienmenh294** [comment]
can i get the 2d coordinates projected on the screen of the point ? then can calculate

**Comment by holance** [comment]
You need to calculate the camera parameters that all your meshes that can fit into the camera frustum, then set those parameters to the camera.

**Comment by thienmenh294** [comment]
The 3D coordinates of the point are constant but the 2D coordinates change when the model is rotated, so I want to get the 2D coordinates. Can I do it with sharpdx?

**Comment by holance** [comment]
Use `Viewport3DX.Project`.

**Comment by thienmenh294** [comment]
Can I make dashed lines in helixtoolkit.wpf.sharpdx?

**Comment by holance** [comment]
Yes, check out line shading demo for details. You need to provide a dash texture for your line material

**Comment by thienmenh294** [comment]
I open the second window, then open up a model. Then turn off the second window. When I want to reopen that second window, there is an error
![Capture](https://user-images.githubusercontent.com/67280714/95460546-0f44e700-09b0-11eb-8a77-3680bb3cc5bf.PNG)

**Comment by thienmenh294** [comment]
how to fix it?

**Comment by holance** [comment]
Make sure to set your window data context to null after closing it.

**Comment by thienmenh294** [comment]
Thank you!

**Comment by thienmenh294** [comment]
((MeshGeometryModel3D)DieCreationViewModel.svm.GroupModelSource[0, 0][0]).Transform = new TranslateTransform3D(new Vector3D(0, 10, 0));
After transforming, can I get the new coordinates of the position?

**Comment by thienmenh294** [comment]
![Capture](https://user-images.githubusercontent.com/67280714/95544031-077b5600-0a35-11eb-8691-cd8418c63081.PNG)
![Capture2](https://user-images.githubusercontent.com/67280714/95544037-0b0edd00-0a35-11eb-938a-a49ecc16f534.PNG)
When I click choose the point in frontside , how do I always choose the point in front or always choose the point in back?

**Comment by holance** [comment]
Set `MeshGeometry3D.ReturnMultipleHitsOnHitTest = true` to return multiple hit test from same model. Then you need to sort the hit test results by hit distance and figure out the front point or back point you want to choose.
