### ISSUE TITLE
Multi light source shadow throwing

### ISSUE THREAD

**Issue by MiroslavJ** [helix-toolkit/helix-toolkit#1399]
Hey guys,
I am working with WPF Helix toolkit and I am using ShadowMap3D to throw shadow. However if I have more light sources my ShadowMap is using only the first DirectionalLight to throw shadow. Is there any way to get it working for a few different light sources? Also I've noticed that it works only for DirectionalLight. Can my PointLight3D or SpotLight3D throw shadow as well ? Thanks.

**Comment by holance** [comment]
Currently it only support one light source due to performance consideration. 
It supports direction light and spot light. It picks the first light in the list as light source. You need to move spot light above directional light to use the spot light as source.

**Comment by MiroslavJ** [comment]
Thanks for your answer @holance . Just one more question if it's not a problem: I have directional light that is going through mesh where IsTransparent = true but in material color alpha channel is set to 0.5 (so it's kind of semi-transparent). It seems like it's not affecting the light going through (the light is not darker). If I set IsTransparent = false the light can not go through that mesh at all. Is this supported in WPF helix? If not any ideas how could I solve it. Thanks a lot for your help.

**Comment by holance** [comment]
Shadow map doesn't support semi transparent mesh right now.

**Comment by MiroslavJ** [comment]
ok, thanks @holance
