### ISSUE TITLE
How to get the mesh of a stl file?

### ISSUE THREAD

**Issue by Terminatorder1** [helix-toolkit/helix-toolkit#1400]
Hello,

How can i get the mesh of a stl file ?

This is what i want to do:

i click on my model and recive a hit result mesh. This mesh i want to compare to all the other meshes in my model.
How can i process all meshes form my model ?

**Comment by holance** [comment]
You need to traverse the scene graph

**Comment by Terminatorder1** [comment]
can u make a example ?

**Comment by Terminatorder1** [comment]
Visual3DHelper.Traverse<GeometryModel3D>(
                h_viewport.Children,
                (geometryModel, transform) =>
                {
                    var mesh = (MeshGeometry3D)geometryModel.Geometry;
                });

Its working! thank you for the traverse hint!
