### ISSUE TITLE
Create TextureModel from Memory Pointer

### ISSUE THREAD

**Issue by KrabatTilt** [helix-toolkit/helix-toolkit#1403]
Usually i use following code to load and display images from file:

```csharp
MemoryStream ms = await LoadFileAsMemoryStreamAsync("test.jpg");
// ms contains jpg encoded image
((PhongMaterialCore) Model.Material).DiffuseMap = new TextureModel(ms);
```

But now I have a situation where I get the image data uncompressed. I have an IntPtr to memory location, width and heigt in pixel, the PixelFormat and the stride. Is it possible to create a TextureModel from that data?

I found following [example](https://gamedev.stackexchange.com/questions/146902/shortest-path-from-bitmapsource-to-dx11-texture2d) on how to do it in SharpDX from a WriteableBitmapSource. But I cannot find a way to get from Texture2D to HelixToolkit TextureModel.

**Comment by holance** [comment]
Currently you can convert your raw data into color4 array and create the texture model from the color4 array.

**Comment by holance** [comment]
You are compressing your data to a PNG, which is not the raw color data anymore. 
Are you trying to use bitmap format? Or your data is raw color data?

**Comment by lovefri** [comment]
I have a bitmap and want to use it directly. My first attempt was to pass the stream but the MeshNode ends up blank/invisible. 

This was my first attempt:

**Comment by lovefri** [comment]
using (var stream = new MemoryStream())
            {
                bitmap.Save(stream, System.Drawing.Imaging.ImageFormat.Bmp);


                var mat = new HelixToolkit.Wpf.SharpDX.Model.PBRMaterialCore()
                {

                    //AlbedoColor = new SharpDX.Color4(1, 1, 1, 1), // Set to something other than black
                    //AlbedoMap = new TextureModel(imageFile),
                    //AlbedoMapFilePath = Path.GetFileName(imageFile),

                    AlbedoColor = new SharpDX.Color4(1, 1, 1, 1),
                    AlbedoMap = new TextureModel(stream),
                    EnableTessellation = false
                };



                meshNode.Material = mat;
                meshNode.RenderWireframe = false;
            }


            meshNode.Geometry = mesh;

            return meshNode;

**Comment by holance** [comment]
using (var stream = new MemoryStream())
You are disposed the stream before helix toolkit can use it.

**Comment by lovefri** [comment]
ah. I thought that the bitmap was stored in the meshnode.Material eaven after the stream closed. The plan waas to return a meshNode and in another function add that to :  ViewportViewModel.GroupModel.AddNode(meshNode);

Are you saying that the stream needs to be open until the ViewPort gets the mesh?

**Comment by holance** [comment]
Yes, it needs to be wait until it gets converted to a texture map. There is a setting to allow helix toolkit to automatically dispose the stream once done with it.

**Comment by lovefri** [comment]
Tackar :)
