### ISSUE TITLE
[Question] High DPI Rendering

### ISSUE THREAD

**Issue by taoyouh** [helix-toolkit/helix-toolkit#1404]
I am running my app on a high-dpi (200% DPI) display, and I found that my Viewport3DX is blurry (including the coordinate at bottom right). In the following screenshot, the ruler is rendered by XAML grids and is clear, but the Viewport3DX is blurry.
![image](https://user-images.githubusercontent.com/11157438/93902067-bf1c2280-fd29-11ea-82c3-28b9c0436789.png)

Are there any guidelines for displaying a high DPI Viewport3DX?

I am using HelixToolkit.Wpf.SharpDX 2.12.0 on WPF with .NET Framework 4.8. The sample code is listed here:
```
            <hx:Viewport3DX xmlns:hx="http://helix-toolkit.org/wpf/SharpDX"
                            x:Name="viewport3DX" CameraMode="Inspect" CoordinateSystemHorizontalPosition="0.8"
                            ShowCameraTarget="True" ShowCoordinateSystem="True" ShowViewCube="False" UseDefaultGestures="False">
                <hx:Viewport3DX.EffectsManager>
                    <hx:DefaultEffectsManager />
                </hx:Viewport3DX.EffectsManager>
                <hx:Viewport3DX.Camera>
                    <hx:OrthographicCamera x:Name="cameraX" />
                </hx:Viewport3DX.Camera>
                <hx:GroupModel3D x:Name="groupModelX" />
                <hx:AmbientLight3D Color="White" />
            </hx:Viewport3DX>
```
The screen shot of the sample code is shown below. You can see that the coordinate system is very blurry (compared to the title bar)
![image](https://user-images.githubusercontent.com/11157438/93902722-7b75e880-fd2a-11ea-92e8-09f06aaf117e.png)

**Comment by holance** [comment]
Currently we scale up based on the dpi scaling. I can add a property to let helixtoolkit render at actual resolution.

**Comment by taoyouh** [comment]
@holance Thank you very much for this feature.
