### ISSUE TITLE
Flickering

### ISSUE THREAD

**Issue by Pulsar79** [helix-toolkit/helix-toolkit#1417]
Version: [Example: 2.11]
Package: [Example: HelixToolkit.Wpf.SharpDX]

Good morning. First of all, to say that I love your library, it has many examples and a lot of extra functionality that makes things easier.

But since I started using it, there's something that brings me upside down. I want to use it to do some 2D simulations. Then I put all series of objects, boxes, triangles, circles, with very small height and with a color or texture, and all on the same height, or shifted 0.001 over the previous one and sorted in the list so that first you paint what is below and then the top. But all about the same height because it's 2D.

The case is that sometimes an annoying flicker occurs especially when zooming with the mouse wheel or with the keys. I leave a code example. And the funny thing is, if I use a ortographic camera it doesn't happen, but with perspective it does. I like the perspective camera better because I can modify the height as I please. Ortographic I don't know how to do it.

What's this all about? What incorporates the ortographic camera that always goes well? Can I use the ortographic camera as a perspective camera, to what function do I have to call to change its height? I leave some pictures for you to see what's going on, and the code. The yellow box is above the red one. 

Thanks a lot.

`            <hx:MeshGeometryModel3D x:Name="m1" CullMode="Back"  Geometry="{Binding RectGeometry}" Material="{Binding Material}" />
            <hx:MeshGeometryModel3D  x:Name="m2" CullMode="Back" Geometry="{Binding RectGeometry2}" Material="{Binding Material2}" />
`
`Camera = new PerspectiveCamera()
            {
                Position = new System.Windows.Media.Media3D.Point3D(0, 0, 10),
                LookDirection = new System.Windows.Media.Media3D.Vector3D(0, 0, -10),
                UpDirection = new System.Windows.Media.Media3D.Vector3D(0, 1, 0),
                FarPlaneDistance = 50000000,
                NearPlaneDistance = 0.1,
                

            };`

` Material = PhongMaterials.Red;
            Material2 = PhongMaterials.Yellow;

            builder = new MeshBuilder();
            builder.AddBox(new Vector3(0, 0, 0), 2, 4, 0.00005f);
            RectGeometry = builder.ToMeshGeometry3D();

            builder = new MeshBuilder( );
            builder.AddBox(new Vector3(1, 1, 0.001f), 2, 4, 0.00005f);
            RectGeometry2 = builder.ToMeshGeometry3D();`

Flick
![Flick02](https://user-images.githubusercontent.com/33166445/95299750-7d898c80-087e-11eb-85f3-21e679c9fe8f.jpg)

Flick
![Flick01](https://user-images.githubusercontent.com/33166445/95299751-7e222300-087e-11eb-9a6a-2d2c7ab042ec.jpg)

Red over yellow (wrong)
![Wrong](https://user-images.githubusercontent.com/33166445/95299752-7e222300-087e-11eb-8f5e-65c0970bbd3b.jpg)

Normal and correct view
![Well](https://user-images.githubusercontent.com/33166445/95299754-7ebab980-087e-11eb-8dfc-397a53b53189.jpg)

**Comment by smischke** [comment]
This effect is called [z-fighting](https://en.wikipedia.org/wiki/Z-fighting). Make sure to chose your NearPlaneDistance and FarPlaneDistance according to the z-values you actually use. The z-steps must be great enough. You could also set z to 0 and use the DepthBias property (see GeometryModel3D) to manage precedence.

**Comment by Pulsar79** [comment]
Thank you so much. I had already tried to change the "DepthBias" but I didn't see it having any effect. But also doing what you have told me to set the same "Z" and leaving the size of "Z" at 0.0 works perfectly and has scented the "flickering"
