### ISSUE TITLE
Manipulator Rotation tool doesn't work in Version 2.13.0

### ISSUE THREAD

**Issue by sinaone1** [helix-toolkit/helix-toolkit#1428]
Unfortunately Rotation tool in the Manipulator doesn't work in the "HelixToolkit.Wpf.SharpDX" Version 2.13.0
I checked it already in the Examples "ManipulatorDemo" and it was same.
Do you know what's the problem?
Thank you.

**Comment by holance** [comment]
Found a bug. Workaround is to set `MeshGeometry3D.EnableSmallTriangleHitTestScaling = false`

**Comment by sinaone1** [comment]
Sorry but I installed the HelixToolkit.Wpf.SharpDX by nuget and I checked it and I think we don't have this property in the dll.
Do I need to add something else to my application?
Thank you
