### ISSUE TITLE
SharpDX - Viewport3DX inside WPF ViewBox crash

### ISSUE THREAD

**Issue by Borck** [helix-toolkit/helix-toolkit#1438]
Hello,

I have an issue putting the Viewport3DX of HelixToolkit.Wpf.SharpDX 2.13.1 inside a System.Windows.Controls.ViewBox. The ViewPort3DX is flickering and showing the 3D model multiple times. After some seconds the view port crashes followed by this exception:

![Screenshot 2020-10-21 122514](https://user-images.githubusercontent.com/10433707/96707765-9757c300-1398-11eb-8801-34c28ca1e2b6.png)

This is the content of my main window, the rest of my project is a default .Net Framework 4.7.1 WPF application:

``` XAML
<Grid>
  <Viewbox>
    <hx:Viewport3DX>
      <hx:Viewport3DX.EffectsManager>
        <hx:DefaultEffectsManager />
      </hx:Viewport3DX.EffectsManager>
      <hx:Viewport3DX.Camera>
        <hx:PerspectiveCamera />
      </hx:Viewport3DX.Camera>
      <hx:AmbientLight3D />
    </hx:Viewport3DX>
  </Viewbox>
</Grid>
```

Regards

**Comment by chrkon** [comment]
Hi @Borck, 
I tried to reproduce this, but if I use your XAML code I get only a black square in the center of the Window and I don't see the behaviour you described. Could you give us a more complete example to reproduce the failure?

Kind regards,
Christof

**Comment by chrkon** [comment]
Some facts about the black square I have seen with the source code above:
- If no size is set, the `viewport` will try to fill the parent control. In this case the Viewbox control.
- The `viewbox` control only scales the child element. In this case the Viewport3DX control. 
- The `viewbox` use the size of the child element as base for the scaling, but it gives no size information to the child element. 

Can you see the circle reference?

The size of the `viewport` is not set. So it want to have the available space from the parent, but the `viewbox` delivers no useful information. Without this information the Viewport starts with the minimal values 10, 10. This small area is now scaled to the size of window. So we see only a black square. 

These minimal values for Height and Width are defined in the file `RenderHostBase.cs`

**Comment by Borck** [comment]
Thanks for your reply. I uploaded by minimal example. Sometimes my machine is stucking for some seconds. I have a Ryzen 3700X and a RTX 2070.

[https://github.com/Borck/HelixWPFTest.git](https://github.com/Borck/HelixWPFTest.git)

Hope this helps.

**Comment by chrkon** [comment]
Hi @Borck , thanks for the test project.
I have cloned the project but I see the same behaviour as in my project. Only a black square. (see picture)
You can see at the diagnostic session window (top right), that this instance is now running for 5 minutes without throwing an exception.

![image](https://user-images.githubusercontent.com/456192/97619648-c2898480-1a20-11eb-818f-77035a27eb21.png)

I have a much smaller PC ( i7 930, 2,8 GHz with GeForce GT 730) and I use the Microsoft Visual Studio Community 2019 Preview
Version 16.8.0 Preview 4.0

**Comment by chrkon** [comment]
If you set the Height (or the Width) Property of the `hx:ViewPort3DX` the View changes like this:

![image](https://user-images.githubusercontent.com/456192/97666491-18d8e080-1a7e-11eb-8987-06aa20a08c16.png)

The Height of the Viewport is greater than the Height of the Window. So the ViewBox Control scales the 3D Viewport!

**Comment by Borck** [comment]
When I add the height (or weight), the error is gone. But it may render in higher or lower resolution as needed. This can be critical because of performance and a blurry view. Maybe binding the height or weight to a parent can be a workaround.

Without any height or weight it look like this.

![helixtest](https://user-images.githubusercontent.com/10433707/98728725-28b7c500-239a-11eb-9428-8d752fe29a67.gif)

Regards

**Comment by chrkon** [comment]
I don't know, why the exception is thrown on your system. Perhaps a setting in the options of the debugger?

But that is not the main issue here. Even if you got no exception the black square would also not be better.

As I explained above, the ViewBox control is scaling its content. That is the only function of the ViewBox control. The main purpose of the Viewbox control is to create an unlimited area for its content. The control in the ViewBox can have any size. But without any defined parent size, the Viewport falls back to a size of 10x10. And this viewport is scaled into the screen size of the ViewBox parent element. In this case the content area of the grid (parent of the ViewBox control).

**I don't know why you want to use the ViewBox control**, but I don't like the Idea of binding the size (height/width) of the ViewBox parent (the grid) to the Viewport (the ViewBox child). But you are right, that this could be a workaround. 

If you want to use the size of the grid area for the Helix ViewPort control, just remove the ViewBox control!
```
<Window x:Class="Viewport3DXInViewBoxDemo.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:Viewport3DXInViewBoxDemo"
        xmlns:hx="http://helix-toolkit.org/wpf/SharpDX"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <hx:Viewport3DX>
            <hx:Viewport3DX.EffectsManager>
                <hx:DefaultEffectsManager />
            </hx:Viewport3DX.EffectsManager>
            <hx:Viewport3DX.Camera>
                <hx:PerspectiveCamera />
            </hx:Viewport3DX.Camera>
            <hx:AmbientLight3D />
        </hx:Viewport3DX>
    </Grid>
</Window>
``` 
Without the ViewBox control the ViewPort will fill the window (the grid content area) automatically. 

Could you explain the reason why you want to use the ViewBox control?

Kind regards,
Christof

**Comment by Borck** [comment]
I have the Viewbox above, because it is in an separate abstract class and reused by different view controls like for camera/depth stream and the Viewport3DX to create a generic tile like grid view of different streams.

I solved the problem by moving the Viewbox to the specific controls, except the one with the Viewport3DX which I agree doesn't really need the Viewbox.

I think we can close this. Thx for you efforts.

Regards Christian

**Comment by holance** [comment]
Viewport3DX in viewbox does not know the size, so it keeps growing the resolution until it crashes. Specify the width and height on Viewprot3DX should fix the issue.

**Comment by SwaroopSomanna** [comment]
> Viewport3DX in viewbox does not know the size, so it keeps growing the resolution until it crashes. Specify the width and height on Viewprot3DX should fix the issue.

I'm getting a blank black screen even after setting the height and width of Viewport3DX
