### ISSUE TITLE
MeshGeometryModel3D Displayed Improperly

### ISSUE THREAD

**Issue by McallyD74** [helix-toolkit/helix-toolkit#1444]
![image](https://user-images.githubusercontent.com/63072224/98403761-169ef500-202f-11eb-97e9-001434bdf5c0.png)
The above is what is displayed in the viewport when attempting to view the contents of a voxel octree I made. It appears as though the cubes have inverted normals, but the issue is also more complicated, because some cubes are rendered in front others when they should be hidden. The octree is output the correct information, but I'm likely doing something wrong when constructing cubes to represent the voxels, or I haven't set up a rendering technique correctly.

![image](https://user-images.githubusercontent.com/63072224/98404142-aba1ee00-202f-11eb-9065-16366c2b08ab.png)

**Comment by holance** [comment]
Seems to be z fighting. If you don't want to render cube back face, turn on back face culling.

**Comment by McallyD74** [comment]
I must be inadvertently rendering as semi transparent. How do I fix it?
