### ISSUE TITLE
Question: why are objects displayed black if viewport children are cleared

### ISSUE THREAD

**Issue by ikonuk** [helix-toolkit/helix-toolkit#1448]
I am not sure if this questions is related to the issue #1439. But I am trying to figure out why the objects are black if you include a Viewport.Children.Clear in the window constructor. I am attaching a small project. Everything works out OK If you comment out the line:

pipelayview.Children.Clear();

after 

InitializeComponent();

My motivation behind the question is that I am going to develop a UserControl with similar architecture which will be accessed repeatedly (animation). I was planning to include a Children.Clear in its window constructor.

I. Konuk

[mypipe1debug.zip](https://github.com/helix-toolkit/helix-toolkit/files/5517813/mypipe1debug.zip)

**Comment by chrkon** [comment]
Short Answer:
If you clear all children of the ViewPort, also all lights will be cleared. And without any light you only see black schemes.

**Comment by ikonuk** [comment]
Thanks you very much indeed.
