### ISSUE TITLE
ItemsModel3D ItemsSource list changes not working

### ISSUE THREAD

**Issue by imo44** [helix-toolkit/helix-toolkit#145]
The ItemsModel3D class doesn't handle changes on the underlying list.
E.g. when adding an item to the underlying list which is bound to the ItemsSource property, the ItemsModel3D doesn't reflect this change.

**Comment by lcouz** [comment]
Hello, I see (probably) the same problem with the ItemsVisual3D class in the WPF DataTemplate example.
I quickly modify the code to take an INotifyCollectionChanged collection as Itemsource. Update of Visual3DCollection Children is made on the CollectionChanged event.

**Comment by lcouz** [comment]
I can share thsi quick and dirty code.

**Comment by objorke** [comment]
The quick and dirty solution is merged.
