### ISSUE TITLE
UWP HelixToolkit Initialization  Version 2.13.1

### ISSUE THREAD

**Issue by sdanev** [helix-toolkit/helix-toolkit#1450]
var viewport3DX = new HelixToolkit.UWP.Viewport3DX(); - Throw Exception 

   Exception {"The type initializer for 'HelixToolkit.UWP.BillboardText3D' threw an exception."} System.TypeInitializationException
   at Windows.UI.Xaml.Data.BindingOperations.SetBinding(DependencyObject target, DependencyProperty dp, BindingBase binding)
   at HelixToolkit.UWP.Viewport3DX.SetupBindings()
   .....

   InnerException {"Unable to open file C:\\.....\\bin\\x64\\Debug\\AppX\\Resources\\arial.fnt"} System.Exception {System.IO.IOException}
   at SharpDX.IO.NativeFileStream..ctor(String fileName, NativeFileMode fileMode, NativeFileAccess access, NativeFileShare share)
   at SharpDX.IO.NativeFile.ReadAllBytes(String path)
   at HelixToolkit.UWP.BillboardText3D..cctor()

The problem do not appear at 2.12 and previous version

**Comment by ChrisHonsinger** [comment]
I am not using UWP, but in HelixToolkit.Wpf.SharpDX I noticed I needed to add a reference to Cyotek.Drawing.BitmapFont. 

Perhaps you need a newer or a reference to a font dll.

**Comment by Everyyx** [comment]
I had the same problem when i edit the xaml file, there are Wave tips under "hx:Viewport3DX", vs throw the excption:
严重性	代码	说明	项目	文件	行	禁止显示状态    错误
XDG0062	System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'HelixToolkit.UWP.BillboardText3D' threw an exception. ---> System.IO.IOException: Unable to open file C:\Users\Every\AppData\Local\Microsoft\VisualStudio\16.0_043187c6\Designer\Cache\11173056727x64DC\Resources\arial.fnt ...	SimpleDemo	C:\Users\Every\Desktop\helix-toolkit-develop\helix-toolkit-develop\Source\Examples\UWP\SimpleDemo\MainPage.xaml	71

**Comment by SnowyWreath** [comment]
I'm encountering this issue as well. Occurs in both 2.13.0 and 2.13.1. I'm running UWP (Windows 10 1909). In XAML I just get an exception that says Viewport3DX could not be instantiated when the page is loaded. If I instantiate a Viewport3DX in code, I get the more detailed message about "Resources\arial.fnt" missing.

I resolved the issue by adding a "Resources" folder to my UWP app project. I then added all the files in the attached ZIP to that Resources folder, and set the build action to "Content". My app now runs.

[Resources.zip](https://github.com/helix-toolkit/helix-toolkit/files/5561234/Resources.zip)

**Comment by Everyyx** [comment]
thanks SnowyWreath,I resolved the issue by your help.but there are  still Wave tips under "hx:Viewport3DX", vs throw the excption:
Severity	Code	Description	Project	File	Line	Suppression State
Error	
XDG0062	System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'HelixToolkit.UWP.BillboardText3D' threw an exception. ---> System.IO.FileNotFoundException: Unable to find file ...	test1	C:\Users\Every\Desktop\test1\MainPage.xaml	72	

I'm so helpless！！！！！！！！

**Comment by holance** [comment]
Please try the nightly build
