### ISSUE TITLE
Performance - memory issue

### ISSUE THREAD

**Issue by VE-2016** [helix-toolkit/helix-toolkit#1453]
Hello,

I would like to check library rendering performance. I had created scene with ca 200-300 spheres - and memory usage of the application is over 1GB. The spheres inherit from UIElement3D.  My question is whether is it proper and how to lower memory consumption?

Best regards,
JK

**Comment by holance** [comment]
I believe you should create only single sphere mesh and set it to multiple ui element for rendering.

If you use sharpdx version, you can use instancing.

**Comment by VE-2016** [comment]
Hello,
this solution improves considerably memory requirements - now just below 200MB.

Best regards,
JK
