### ISSUE TITLE
AssimpNet AND HelixToolkit.Wpf.SharpDX.Assimp, Version=2.13.1.0

### ISSUE THREAD

**Issue by ChrisHonsinger** [helix-toolkit/helix-toolkit#1457]
Hello,

I am trying to get HelixToolkit.Wpf.SharpDX.Assimp Version=2.13.1.0 to work with AssimpNet 5.0.0.0 

I upgraded the Helix HelixToolkit.Wpf.SharpDX to the latest version ( Version=2.13.1.0) and began getting an exception.  The exception I receive is provided below.

Apparently, HelixToolkit.Wpf.SharpDX.Assimp Version=2.13.1.0 depends on AssimpNet 5.0.0.0.  The best match I can find on NuGet is  AssimpNet 5.0.0.beta - but won't compile. 

I think the reason I can't get it to compile with AssimpNet -Version 5.0.0-beta1 is because it is labelled  5.0.0-beta1 not  AssimpNet, Version=5.0.0.0.

Perhaps there exists a non beta version? Or do you know what I am missing?

Thank you for any help!

Chris

---
EXCEPTION MESSAGE
InnerException: System.IO.FileLoadException: Could not load file or assembly 'AssimpNet, Version=5.0.0.0, Culture=neutral, PublicKeyToken=0d51b391f59f42a6' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'AssimpNet, Version=5.0.0.0, Culture=neutral, PublicKeyToken=0d51b391f59f42a6'
   at HelixToolkit.Wpf.SharpDX.Assimp.Importer..cctor()

=== Pre-bind state information ===
LOG: DisplayName = AssimpNet, Version=5.0.0.0, Culture=neutral, PublicKeyToken=0d51b391f59f42a6
 (Fully-specified)
LOG: Appbase = file:///C:/binaries/
LOG: Initial PrivatePath = NULL
Calling assembly : HelixToolkit.Wpf.SharpDX.Assimp, Version=2.13.1.0, Culture=neutral, PublicKeyToken=52aa3500039caf0d.

**Comment by eriove** [comment]
I had the same problem. The AssimpNet beta has the wrong version number (4.1.0.0) in the DLL. I solved it with the follwoing assembly redirect (you still have to use the beta NuGet):
```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="AssimpNet.dll"
          culture="en-us" />
        <!-- AssimpNet forgot to update the version number in the file when releasing a new NuGet -->
        <bindingRedirect oldVersion="5.0.0.0" newVersion="4.1.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Comment by ChrisHonsinger** [comment]
eriove - **it worked!**

I want to thank you for your help - I sure many others will find help in your response.

Very best,

Chris
