### ISSUE TITLE
Offset origin within the containing grid

### ISSUE THREAD

**Issue by SwaroopSomanna** [helix-toolkit/helix-toolkit#1459]
I've a grid to which I've added a helix3D viewport. To the viewport I've added a GridLinesVisual3D, a LinesVisual3D and a ViewBox. At runtime I would be adding 3D model files to the viewport which get automatically placed on the GridLinesVisual3D.

Now what I want to achieve is shift the whole set of LinesVisual3D, GridLinesVisual3D and added models a little down within the containing grid. Lets say a shift of Z = -4. And this new Z position should be set as Z=0. I mean I want the Z axis origin to offset to -4. Is this possible?   
Please note, the position of the view box must not change with the change in offset.

**Comment by ikonuk** [comment]
Yes, of course it is possible. Place your (visuals) models in either a ModelVisual3D (or Model3DGroup) object or a class derived from them as children like:

this.Children.Add(myvisual);

and then create a Transform3DGroup object:

var myGroupTransform = new Transform3DGroup();
myGroupTransform.Children.Add(new TranslateTransform3D(new Vector3D(0,0,-4));
this.Transform = myGroupTransform;

**Comment by chrkon** [comment]
Dear @SwaroopSomanna,
you have marked this answer with a ThumbUp emoji. So I think this answer has solved your question, right?
Many thanks to you for this reaction. It feels good to get a feedback. 

Maybe you can close the issue if the answer was helpful. Then it will be easier to get an overview of the open questions.

Kind regards,
Christof
