### ISSUE TITLE
How to dynamically add Element3Ds to a Viewport3DX

### ISSUE THREAD

**Issue by imo44** [helix-toolkit/helix-toolkit#146]
When defining Element3Ds of a Viewport3DX statically (e.g. in XAML), everything works fine.
When I add an Element3D (e.g. a MeshGeometryModel3D) at runtime to the Viewport3DX's Items, a NullReferenceException is thrown in the MeshGeometryModel3D.Render method because it is not attached to the render host.

I can attach the new Element3Ds manually before adding them to the Items list. That works.
But I think that should be handled by the Viewport3DX. For my understanding, the contract of the Viewport3DX is, that I can add Element3Ds to the Items collection. E.g. through a binding.

Thanks for your help.

**Comment by ikeough** [comment]
We have found that for every `GeometryModel3D` object added to the collection which is the `ItemsSource` for the `Viewport3DX`, you need to call `myItem.Attach()`. It would be nicer if you could just add objects to that collection and have `Attach()` called internally.

**Comment by holance** [comment]
Supported in new 2.0
