### ISSUE TITLE
Loading big stl file (100mb) leads to no result

### ISSUE THREAD

**Issue by AndreasReitberger** [helix-toolkit/helix-toolkit#1463]
Hi,
I'm using the `hdx:Viewport3DX` to display stl files in my WPF application. This is working fine for normal stl files (a few mb big).
However once I try to display a bigger file, the `Importer` gets back `null` for the result.

This is how I read the file.

```
private async Task<bool> read3dFile(string path)
        {
            if (path == null)
            {
                return false;
            }
            IsLoadingStl = true;
            bool succeeded = false;
            await Task.Run(() =>
            {
                var loader = new Importer();
                return loader.Load(path, new ImporterConfiguration()
                {
                    EnableParallelProcessing = true,
                });
            }).ContinueWith((result) =>
            {
                if (result.IsCompleted)
                {
                    scene = result.Result;
                    GroupModel.Clear();
                    if (scene != null)
                    {
                        GroupModel.AddNode(scene.Root);
                        succeeded = true;
                    }
                }
                else if (result.IsFaulted && result.Exception != null)
                {
                    MessageBox.Show(result.Exception.Message);
                }
                IsLoadingStl = false;
            }, TaskScheduler.FromCurrentSynchronizationContext());
            Messenger.Default.Send(new NotificationMessage(null, "ZoomToFitStl"));
            IsLoadingStl = false;
            return succeeded;
        }
```

the `result.IsComplete` is true, however the `result.Result` is null.
I tried to read the file below:
https://www.thingiverse.com/thing:2506681

Thank you!

**Comment by holance** [comment]
I am able to load the file successfully using the FileLoadDemo.

**Comment by AndreasReitberger** [comment]
> I am able to load the file successfully using the FileLoadDemo. Which helixtoolkit version are you using? Could you try the latest nightly build?

Hi,
Thanks for your reply. I'm using the latest stable version in my project. I'll try nightly build and report back.

**Comment by AndreasReitberger** [comment]
> I am able to load the file successfully using the FileLoadDemo. Which helixtoolkit version are you using? Could you try the latest nightly build?

Hi again, 
I checked the updates in the nuget manager, however there is no newer build then installed.
Or where to I get the nighly builds for testing?

Thank you,
Andreas

**Comment by holance** [comment]
https://www.myget.org/F/helix-toolkit
Add this as a nuget source

**Comment by AndreasReitberger** [comment]
> https://www.myget.org/F/helix-toolkit

Still not working with the latest version. I guess the problem is based in my code. I'll see if I can figure it out. I'll report back once I've found the issue. Thanks for helping!

**Comment by AndreasReitberger** [comment]
I'm a little bit lost. I compared your sample "FileLoading" project and I cannot figure out what I'm doing different to cause the issue. So I prepared a small test case using my code. Small files are working fine.. just not the Batman.
https://github.com/AndreasReitberger/HelixToolkitDragablz

Thank you,
Andreas

**Comment by holance** [comment]
Seems like you are loading the same file twice. Once using the IxMilia to create a STL object. Then try to use assimp to load again. Maybe the file is locked for reading by IxMilia library, then you try to read the file again using assimp, and failed.

**Comment by AndreasReitberger** [comment]
> Seems like you are loading the same file twice. Once using the IxMilia to create a STL object. Then try to use assimp to load again. Maybe the file is locked for reading by IxMilia library, then you try to read the file again using assimp, and failed.
> I comment out `Model = Load(StlFilePath);` in `Stl.cs` constructor and it is working now.

Hi,
sorry to bother you again with this problem, however the issue is not resloved by removing the mentioned line.
However, I found out, that the file location seems to be the problem.

If I load the stl file from the desktop, it works. However if I use a path from a netdrive, it fails.

Same file once loaded from:
`C:\Users\andyr\Desktop\Jeffy v1.stl`
![image](https://user-images.githubusercontent.com/2952443/105572788-9c425f00-5d59-11eb-9b2a-a0f0f4be4b0c.png)

`U:\01_Aufträge\04_3D_Druck\Früchtl\C\Monteur\Jeffy v1.stl`
![image](https://user-images.githubusercontent.com/2952443/105572840-dc094680-5d59-11eb-82af-6c79557d3ec1.png)

Some further tries I figured out that the "ä,ü" (german special char) in the file path seems to be the problem

Maybe you can look into this again.
Thank you,
Andreas

**Comment by holance** [comment]
Try to hook up `Importer.AssimpExceptionOccurred` event to check if any exception gets thrown during loading.

**Comment by AndreasReitberger** [comment]
> Try to hook up `Importer.AssimpExceptionOccurred` event to check if any exception gets thrown during loading.

Hi @holance 

Yes, an Exception gets thrown.
![image](https://user-images.githubusercontent.com/2952443/105739357-51327280-5f38-11eb-858f-87b19eadea65.png)

Message
Error importing file: Unable to open file "U:\01_Aufträge\04_3D_Druck\Früchtl\Monteur\Jeffy v1.stl".

StackTrace:
   bei Assimp.AssimpContext.ImportFile(String file, PostProcessSteps postProcessFlags)
   bei HelixToolkit.Wpf.SharpDX.Assimp.Importer.Load(String filePath, HelixToolkitScene& scene)

**Comment by holance** [comment]
Does the error only happen while trying to load the file on network drive?

**Comment by AndreasReitberger** [comment]
> Does the error only happen while trying to load the file on network drive?

The netdrive seems not to be the problem, but the chars 'ä','ü','ö'.

U:\01_Aufträge\04_3D_Druck\**Früchtl**\Monteur\Jeffy v1.stl

If I put the file into some other folders without on the special chars, it's working.

**Comment by holance** [comment]
It seems to be assimp to internal issue.

**Comment by AndreasReitberger** [comment]
> It seems to be assimp to internal issue.

Is there something I can do to fix this? Thanks for looking into this matter.
