### ISSUE TITLE
Assimp version in csproj files differ from version in nuspec files (5.0.0-beta1 vs. 4.1.0)

### ISSUE THREAD

**Issue by smischke** [helix-toolkit/helix-toolkit#1464]
The Assimp dependencies in nuspec files use version 4.1.0. The following csproj files have package references to version 5.0.0-beta1. 

Source\Examples\SharpDX.Core\CoreTest\CoreTest.csproj
Source\Examples\WPF.SharpDX\BoneSkinDemo\BoneSkinDemo.csproj
Source\Examples\WPF.SharpDX\FileLoadDemo\FileLoadDemo.csproj
Source\Examples\WPF.SharpDX\MemoryLeakTester\MemoryLeakTester.csproj
Source\HelixToolkit.SharpDX.Core.Assimp\HelixToolkit.SharpDX.Core.Assimp.csproj
Source\HelixToolkit.UWP.Assimp\HelixToolkit.UWP.Assimp.csproj
Source\HelixToolkit.Wpf.SharpDX.Assimp\HelixToolkit.Wpf.SharpDX.Assimp.csproj

Please change them to version 4.1.0 or make it consistent.

**Comment by holance** [comment]
Due to many bugs in 4.1.0, will change nuspec to use 5.0.0-beta.

**Comment by eriove** [comment]
@smischke:
As mentioned in #1457 the AssimpNet beta has the wrong version number in the DLL in the NuGet package so you will need this assembly redirect as well when using the 5.0.0 beta:
```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="AssimpNet.dll"
          culture="en-us" />
        <!-- AssimpNet forgot to update the version number in the file when releasing a new NuGet -->
        <bindingRedirect oldVersion="5.0.0.0" newVersion="4.1.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```
