### ISSUE TITLE
Helix Assimp Disposal

### ISSUE THREAD

**Issue by ChrisHonsinger** [helix-toolkit/helix-toolkit#1471]
When dealing with large OBJ files >300MB, my HelixToolkit.Wpf.SharpDX.Assimp dlls are not released from their calling process. 

My guess is that  I should be Disposing explicitly the HelixToolkit.Wpf.SharpDX.Assimp objects because they are built upon unmanaged code.  Is this true?

If so, does anyone have an example of what I need to do? 

Thank you,

Chris

---

UPDATE: When I wrote the above, my exception handler didn't report any exceptions.  However, shortly afterward I received the following information in an exception folder:

-----------Exception Details on  11/30/2020 2:45:45 PM-----------------
-------------------------------------------------------------------------------------

Log Written Date: 11/30/2020 2:45:45 PM

Error Line No: line 82

Error Message: TypeInitializationException

Exception Type: System.TypeInitializationException

Error Location : The type initializer for 'HelixToolkit.Wpf.SharpDX.Assimp.Importer' threw an exception.

Error Page Url: C:\TDTData\ExceptionLoggerPath\VMImporter

InnerException: System.IO.FileLoadException: Could not load file or assembly 'AssimpNet, Version=5.0.0.0, Culture=neutral, PublicKeyToken=0d51b391f59f42a6' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'AssimpNet, Version=5.0.0.0, Culture=neutral, PublicKeyToken=0d51b391f59f42a6'
   at HelixToolkit.Wpf.SharpDX.Assimp.Importer..cctor()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

--------------------------------*End*------------------------------------------

NOTE A: I am loading multiple instances of the model, each with a different camera view. They are rendered to multiple GPUs. The model used in this case was 450MB.  (OBJ)

This exception occurred at the initialization of the fifth instance. 

NOTE B: I am using four AMD Radeon 9100 Pro's  with 32GB GPU RAM each. 

Using Helix WPF I can load a lot more, but using WPF.SharpDX with SWAP buffer ON - I can only initialize about half without error.  Of course Helix WPF is dreadfully slow.

**Comment by holance** [comment]
I believe there is a bug in current release, which specifies wrong version of AssimpNet. Please try the latest nightly build.

**Comment by ChrisHonsinger** [comment]
Holance, 

I thought their was an issue as well. Before I attempt at using the nightly build, could you look at at issue  #1457, an issue I closed recently -- I had an issue similar to what you are saying, but someone answered my question - and his suggestion worked.

---

Do I need to do any special disposing? Or is the disposing done in your Helix wrapper on AssimpNet?

Thanks for your help again, Holance.

**Comment by holance** [comment]
Helix disposes the assimp object immediately after finishing loading.

**Comment by ChrisHonsinger** [comment]
Thanks -- I shall load the nightly build tomorrow.

As usual, I appreciate your help, Holance.

Chris

**Comment by ChrisHonsinger** [comment]
> Helix disposes the assimp object immediately after finishing loading. The exception from the logs is related to #1457.

Is there a link you could provide me to the output of the nightly build. I am afraid I can find it.

Much appreciated.

**Comment by holance** [comment]
https://www.myget.org/F/helix-toolkit

**Comment by ChrisHonsinger** [comment]
> https://www.myget.org/F/helix-toolkit

Clicking this, shows the xml file:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<service xmlns="http://www.w3.org/2007/app" xmlns:atom="http://www.w3.org/2005/Atom" xml:base="https://www.myget.org/F/helix-toolkit/">
<workspace>
<atom:title>Default</atom:title>
<collection href="Packages">
<atom:title>Packages</atom:title>
</collection>
<collection href="Screenshots">
<atom:title>Screenshots</atom:title>
</collection>
</workspace>
</service

Is there something I need to do to get the fresh dll?

**Comment by holance** [comment]
You need to add the link as an nuget source in visual studio.

**Comment by ChrisHonsinger** [comment]
LOL - OK, thanks!

**Comment by ChrisHonsinger** [comment]
Thanks Holance!
