### ISSUE TITLE
SetValue vs. Set  (in bindable properties) 

### ISSUE THREAD

**Issue by ChrisHonsinger** [helix-toolkit/helix-toolkit#1476]
Many routines in the example area for WPF.SharpDX use:

        protected bool SetValue<T>(ref T backingField, T value, [CallerMemberName]string propertyName = "")
        {
            if (object.Equals(backingField, value))
            {
                return false;
            }

            backingField = value;
            this.OnPropertyChanged(propertyName);
            return true;
        }

rather than: 

      protected void OnPropertyChanged([CallerMemberName]string info = "")
        {
            if (this.PropertyChanged != null)
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(info));
            }
        }

Can someone tell me why?

**Comment by chrkon** [comment]
Hi @ChrisHonsinger, 
if the new value is equal to the backingField we don't need to raise a propertyChanged event, because nothing has changed.

Kind regards,
Christof

**Comment by ChrisHonsinger** [comment]
Christof,

Thank you. 

It appears I need to better understand what a backingField is. 

Chris
