### ISSUE TITLE
Issue with displaying certain files.

### ISSUE THREAD

**Issue by ChrisHonsinger** [helix-toolkit/helix-toolkit#1478]
I am finishing a true 3D display application using  SharpDX.WPF. 

There's two applications. There's a controller program:

![image](https://user-images.githubusercontent.com/4346805/102662357-b088b000-414c-11eb-8bac-0e3271960a71.png)

and there's a worker program.  22 worker instances of the worker program are used at once, each with a rendering reflecting what the eye would see in a true 3D world. These worker instance images are projected using 22 light projectors. Here is a sampling of what's projected:

![image](https://user-images.githubusercontent.com/4346805/102656472-ed9b7500-4141-11eb-9df7-e21f0151cdf0.png)
(the curved nature of the worker images is computed to undo the physical distortions of the projectors, we do this using Helix tone shaders)

As the user moves the model around using the controller program, the worker instances present all the true 3D images on a special screen.  For the 3D model above, we are using OBJ files with jpeg textures.  All is fine when using this type of 3D model.

Now - here's the problem. 

Using glTF 2.0 models from the Kronos group: https://www.khronos.org/gltf/ we get good images on the controller and bad images on the workers. 

![image](https://user-images.githubusercontent.com/4346805/102658530-bb8c1200-4145-11eb-829f-d7cc3331d4a5.png)
(controller GOOD)

![image](https://user-images.githubusercontent.com/4346805/102658627-ea09ed00-4145-11eb-8a60-c1f6fbef546f.png)
(worker BAD - note the blue background was generated to you can see the silhouette )

I am hoping that someone has an idea why this occurs.  

Here's what I think is important to know. The controller program uses MVVM. The worker uses code behind. The worker also uses CompositionTarget rendering. The worker is very simple, after reading the model, it simply reads shared memory from the controller and does a few simple calculations. 

**Here is the worker XAML:**

<Window x:Class="ProjectorWorker.MainWindow"
       
 xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup- 
       compatibility/2006"
        xmlns:hx="http://helix-toolkit.org/wpf/SharpDX"
        xmlns:local="clr-namespace:ProjectorWorker"
        mc:Ignorable="d" ResizeMode="NoResize" WindowStyle="None"  
        Closing="Win_Closing"
        Title="MainWindow" Width="1280" Height="800" 
        Background="Black" ContentRendered="OnContentRendered">
 

    <hx:Viewport3DX Width="1280" Height="800"
            x:Name="view1"
            BackgroundColor="LightGray"
            Camera="{Binding MyCamera}"

            UseDefaultGestures="False"
            ShowCoordinateSystem="False"
            ShowCameraInfo="False"
            ShowViewCube="False"
            ShowFrameRate="False"
            ShowFrameDetails="False"
            EffectsManager="{Binding EffectsManager}"
            ShowCameraTarget="False"
            IsPanEnabled="True"
            EnableSwapChainRendering="True"
            IsMoveEnabled="True">

        <hx:Element3DPresenter Content="{Binding GroupModel}" />
        <hx:PostEffectMeshBorderHighlight EffectName="highlight" />
        <hx:DirectionalLight3D Direction="{Binding 
         MyCamera.LookDirection}" Color="#D6D6D6" />
        <hx:AmbientLight3D Color="#050505" />
    </hx:Viewport3DX>
 

**Here is the worker file IO - note, the file is read in the constructer.** 

        public MainWindow()
        {
           //Path to desired model
            string pathToModel = 
     LastModelPathXML.Load(tdtConstants.FileModelPath).PathToModel;

            groupModel = new GroupModel3D();
            var importer = new HelixToolkit.Wpf.SharpDX.Assimp.Importer();
            var model = importer.Load(pathToModel);
            var nodeGroup = new SceneNodeGroupModel3D();
            nodeGroup.AddNode(model.Root);
            GroupModel.Children.Add(nodeGroup);

            //  This is for the pixel shaders
             EffectsManager = new CustomEffectsManager(graphicsCard);
        
            ProjectorShader = @"C:\TDTData\WarpLuts\Lut" + ProjectorNumber.ToString() + ".tif";
            effect = new NodePostEffectToneMap();
            effect.ToneMap = LoadFileToMemory(ProjectorShader);
            effect.Sharpness = 0;
            effect.Gamma = -1.0f;
            effect.OnSetRenderTechnique = (host) => { return host.EffectsManager[CustomShaderNames.ToneMap]; };

            nodeGroup.AddNode(effect);

            projectorState = ShiftCamera(shmemFromController.Data, ProjectorNumber);

            DataContext = this;

            startCompositionRendering = true;
            System.Windows.Media.CompositionTarget.Rendering += OnRender;
 }

FACTS:
A) The controller code uses substantially the same software provided in the SharpDX.WPF "examples", specifically FileLoadDemo.  That example uses SceneNodeGroupModel3D whereas the worker above uses Group3D.

B) I have tried removing the shader code for the worker and I get the same bad images. 

C) I do not start the Composition rendering until the model has been read. 

D) Look at the worker images that are bad above. Note that visually the appear that the lighting is not working.

If you have any suggestions, I'd really appreciate it.

Chris

**Comment by holance** [comment]
Try to remove the post effect

**Comment by ChrisHonsinger** [comment]
Holance, 

I changed CustomEffectsManager to DefaultEffectsManager. I commented out any effect.XXX intitialization parameter as well.

Result is the same. 

Chris

            groupModel = new GroupModel3D();
            var importer = new HelixToolkit.Wpf.SharpDX.Assimp.Importer();
            var model = importer.Load(pathToModel);
            var nodeGroup = new SceneNodeGroupModel3D();
            nodeGroup.AddNode(model.Root);
            GroupModel.Children.Add(nodeGroup);

            //  This is for the pixel shaders
            EffectsManager = new **DefaultEffectsManager(graphicsCard);**

            **//ProjectorShader = @"C:\TDTData\WarpLuts\Lut" + ProjectorNumber.ToString() + ".tif";
            //effect = new NodePostEffectToneMap();
            //effect.ToneMap = LoadFileToMemory(ProjectorShader);
            //effect.Sharpness = 0;
            //effect.Gamma = -1.0f;
            //effect.OnSetRenderTechnique = (host) => { return host.EffectsManager[CustomShaderNames.ToneMap]; };

            //nodeGroup.AddNode(effect);**

**Comment by holance** [comment]
Try to set the DirectionalLight direction to a fix value and try if it fixes the issue. Seems to be the lighting issue.

**Comment by ChrisHonsinger** [comment]
> Try to set the DirectionalLight direction to a fix value and see if it fixes the issue. Seems to be the lighting issue.

Holance - you saved me again.. Fixed value worked. I'll hold off on trying things until I hear from you.  In absence of a reply I was thinking to cast the camera as a perspective camera (say, in a value converter) and seeing if that works.

Very best - Chris

**Comment by holance** [comment]
Please check your directional light direction binding path. Usually it is caused by incorrect binding.

**Comment by ChrisHonsinger** [comment]
That was it Holance - Thanks!
