### ISSUE TITLE
GridLinesVisual3D in Helix-toolkit-wpf-SharpDX?

### ISSUE THREAD

**Issue by SwaroopSomanna** [helix-toolkit/helix-toolkit#1483]
Helixtollkit-WPF comes with the GridLinesVisual3D but I can't find the same element or any similar one in Helix-toolkit-wpf-SharpDX. Can you please add GridLinesVisual3D to Helix-toolkit-wpf-SharpDX?

**Comment by holance** [comment]
You can use the mesh builder to build the grid yourself.
