### ISSUE TITLE
Additional Post Effect Blending Issues

### ISSUE THREAD

**Issue by SnowyWreath** [helix-toolkit/helix-toolkit#1491]
I'd like to bring up two issues regarding blending in mesh post-effects. Both are related to #1466.

First, #1466 addressed the PostEffectMeshBorderHighlight, but the same issue still exists with the PostEffectMeshOutlineBlur. The image below comes from the PostEffectsDemo project, where I've changed the canvas background to white. Notice how the glow is visible over the floor, but not against the white canvas.
![image](https://user-images.githubusercontent.com/53192301/104741618-742e7c80-5717-11eb-8772-bde749da4474.png)

Second, the fix for #1466 does not work well when the effect's color is not a bold solid color. The image below comes from the UWP SimpleDemo where the canvas background has been set to white, and the post effect color has been changed to #F74A92.
![image](https://user-images.githubusercontent.com/53192301/104742716-c9b75900-5718-11eb-80a5-faeeadb83ea3.png)

#F74A92 should be this color in the image below, but on the canvas it shows up as white with a very narrow band of color at the edge.
![image](https://user-images.githubusercontent.com/53192301/104742855-f66b7080-5718-11eb-8c88-69c7782c31bd.png)

Here's another example of how the effect looked in 2.13.1 vs 2.14.0, both using the #F74A92 color.

![image](https://user-images.githubusercontent.com/53192301/104743041-3c283900-5719-11eb-8b19-48f1a21a9930.png)
2.13.1

![image](https://user-images.githubusercontent.com/53192301/104743088-49452800-5719-11eb-85bf-9dd938399181.png)
2.14.0

**Comment by holance** [comment]
Please try with latest nightly build.

**Comment by SnowyWreath** [comment]
@holance, thanks, it looks much better in the nightly build.
