### ISSUE TITLE
Is there a function to simulate gravity?

### ISSUE THREAD

**Issue by SLKyrim** [helix-toolkit/helix-toolkit#1495]
Thanks for this great work!
By using helix-toolkit, I successfully created a model of a quadruped robot in my WPF application. However,  without gravity, the  robot model can only perform actions that appear to be suspended on the air.
So I am wondering if there is a function to add gravity to the models?

**Comment by holance** [comment]
Currently helix toolkit doesn't support physics simulation, you may want to use other library to simulate the physics and pass the results back to helix toolkit for rendering.

**Comment by SLKyrim** [comment]
Thanks for your suggestion.
