### ISSUE TITLE
UWP NuGet Package error

### ISSUE THREAD

**Issue by JuandreG** [helix-toolkit/helix-toolkit#1505]
I'm having problems with adding the new versions of the UWP Packages.

I get the following error when trying to build my application:

Could not copy the file "C:\Users\Juandre\\.nuget\packages\helixtoolkit.sharpdx.assimp\2.14.0\lib\uap10.0\HelixToolkit.UWP\HelixToolkit.UWP.xr.xml" because it was not found.

I have added all the packages I think is needed:

AssimpNet v5.0.0-beta1
HelixToolkit v2.14.0
HelixToolkit.SharpDX.Assimp v2.14.0
HelixToolkit.SharpDX.Core v2.14.0
HelixToolkit.UWP v2.14.0
SharpDX v4.2.0
SharpDX.Direct3D11 v4.2.0
SharpDX.DXGI v4.2.0
SharpDX.Mathematics v4.2.0

Am I missing something?
My project min and max versions are both Windows 10, version 2004 (10.0; Build 19041)

And I'm hoping for some more UWP examples. An example of post effects in UWP would be greatly appreciated. The reason I'm hoping for an example like this is that I'm working on a Product Viewer of sorts and some nice post effects would go a long way.

**Comment by holance** [comment]
Try to remove this `HelixToolkit.SharpDX.Core v2.14.0`

**Comment by holance** [comment]
Please try the latest nightly build.

**Comment by JuandreG** [comment]
I tried it but I'm still getting the same problem.

I removed the HelixToolkit.SharpDX.Core v2.14.0 but it didn't work.

As soon as I remove the HelixToolkit.SharpDX.Assimp v2.14.0 then it builds. But I can't leave it out because the importer is there.

**Comment by JuandreG** [comment]
All the packages mentioned in the first post work when it's on v2.10.0. Maybe this is useful information to you.

**Comment by holance** [comment]
Have you tried the nightly build

**Comment by JuandreG** [comment]
No, I don't know what the nightly build is.

**Comment by holance** [comment]
https://www.myget.org/F/helix-toolkit

Add this link as new nuget source, and click Pre-release option in visual studio. You should see the nightly build
