### ISSUE TITLE
Best way to make a background image?

### ISSUE THREAD

**Issue by victimized0** [helix-toolkit/helix-toolkit#1506]
Perfomance considered, what's the best way to make a background image that won't be interactive?
Context:
I have a huge hexmap (over 500k hexes, each hex is consisted of 6 vertices and hexes don't share a single vertex because I need to paint over hexes and with shared vertices approach this is impossible afaik).
So when user creates a new project, he gets an empty hexmap of given resolution. So I'm looking to add a feature to use reference image to paint the hexmap. This way the reference image is put on background while hexmap is in the foreground.
I'm using **MeshGeometryModel3D** for the hexmap mesh but I need a way to give it opacity to be able to see the background image.

So the question is, what's the best way to make the background image as well how can I make my hexmap layer transparent (opacity value should be controlled by user or hardcoded, doesn't rly matter atm). Performance should be considered, since I have this huge mesh.

Also, does helix support frustum culling? Will it cull the hexes outside of the camera frustum if I zoom in? As I've mentioned the hexmap grid is a single MeshGeometryModel3D element.

**Comment by holance** [comment]
Are you using HelixToolkit SharpDX version?

**Comment by victimized0** [comment]
I'm 99% sure I'm using Helix.Wpf.SharpDX

**Comment by MrJox** [comment]
Any idea?

**Comment by holance** [comment]
You can separate your hex geometries into several smaller geometries, like 5k hexes each with 100 individual meshes.

**Comment by MrJox** [comment]
Okay that works for the frustum culling.
Any idea on the bitmap background tho?
(writing from my second account)

**Comment by holance** [comment]
you can create a rectangle mesh and assign your bitmap as texture onto the mesh as background.

**Comment by victimized0** [comment]
@holance , Is there a way to make the foreground layer (MeshGeometryModel3D) transparent so I can actually see rectangle mesh with the bitmap that is on the background?
Setting colour alpha per each vertex of the hexgrid mesh doesn't prove to be effective way to do it.

**Comment by victimized0** [comment]
I managed to put the bitmap image on the background of my hexgrid mesh. But there is a problem, bitmap mesh doesn't pass the depth test so I can't really achieve the transparency effect.
Is there a way to turn off Z-test?

**Comment by holance** [comment]
You need to put your bitmap model before hex model in scene graph, so the bitmap model is rendered before hex model.

**Comment by victimized0** [comment]
Yup, did the job
