### ISSUE TITLE
Add bitmap as texture to a plane

### ISSUE THREAD

**Issue by DeshpandeJanhavi** [helix-toolkit/helix-toolkit#1508]
I want to render a 3D plane with texture stored in a bitmap. I tried using setting texture coordinate values to pixel colors I got from bitmap, but the texture is not getting assigned. 
`var texcoords = new Point[rows, columns];
for int(i=0;i<rows;i++)
  for(int j=0; j<columns; j++)
     {
        Color pixelColor = bitmap.GetPixel(i,j);
        texcoord[i,j] = new Point(pixelColor.R/255, pixelColor.R/255);
     }
surfaceMeshBuilder.AddRectangularMesh(Points, texcoord);`

Is there any other way to achieve this? Or is there any way I can directly render bitmap in a 3D scene?

**Comment by holance** [comment]
Texture coordinate is not pixel color.

**Comment by holance** [comment]
Create a quad to display your image.
```
            var b1 = new MeshBuilder();
            b1.AddQuad(new Vector3(10, 10, 0), new Vector3(-10, 10, 0), new Vector3(-10, -10, 0), new Vector3(10, -10, 0));
```

Create a phone material, set the material diffuse map to your bitmap filestream.

**Comment by DeshpandeJanhavi** [comment]
Thank you @holance ! This worked.
