### ISSUE TITLE
Low-level toolkit code should not show MessageBox on exception

### ISSUE THREAD

**Issue by garyjohnson** [helix-toolkit/helix-toolkit#151]
Noticing a couple points in ObjReader (WPF and SharpDX) that eat exceptions and show MessageBoxes. This makes, in my opinion, too many assumptions about how helix is used and how the developer wants to handle these exceptions. Also in most cases the model fails to finish loading anyways so at a glance it doesn't seem useful to eat these errors.

Could we remove these messageboxes and either: 
1) just let the (custom) exceptions raise and allow the user to show custom UI, handle and log, or ignore
2) catch the exceptions but make errors during read available in the form of an Errors property or something similar

I'm sure there are other ways to do this and I'm not sure how concerned we are about backwards compatibility but those are the solutions I could think of in the moment.

I'm happy to submit a PR for this but wanted to talk it through first and make sure this would be a desired change.

**Comment by objorke** [comment]
I think there could be a flag (property or method argument) that defines if exceptions should be thrown or caught!

**Comment by garyjohnson** [comment]
Okay agreed. I'm guessing the default would be to do what it does now in case anyone is relying on it. I'll take a closer look at this when I get a chance and see what kind of effort it would take.

**Comment by holance** [comment]
Done.
