### ISSUE TITLE
Rotating the object from the center point

### ISSUE THREAD

**Issue by saklanmazozgur** [helix-toolkit/helix-toolkit#1511]
Hi,

I can view a 3D object as follows. I want to rotate this object according to certain values, but the object is not rotating from its center point. Object rotates through corner points.

I need to use the RotateAt command instead of the rotate command, but I could not find how to determine the object's center point. Thanks for the information.

`

       private const string MODEL_PATH = "C:\\Users\\SAYKAL-12\\Desktop\\dice.stl";
        
        public MainWindow()
        {
            InitializeComponent();

            ModelVisual3D device3D = new ModelVisual3D();
            device3D.Content = Display3d(MODEL_PATH);
            viewPort3d.Children.Add(device3D);

            var axis = new Vector3D(0, 0, 1);
            var angle = 50;

            var matrix = device3D.Transform.Value;
            matrix.Rotate(new Quaternion(axis, angle));

            device3D.Transform = new MatrixTransform3D(matrix);
        }

        private Model3D Display3d(string model)
        {
            Model3D device = null;
            try
            {
                viewPort3d.RotateGesture = new MouseGesture(MouseAction.LeftClick);

                ModelImporter import = new ModelImporter();

                device = import.Load(model);
            }
            catch (Exception e)
            {
                MessageBox.Show("Exception Error : " + e.StackTrace);
            }
            return device;
        }
`

xaml Code

`        <helix:HelixViewport3D x:Name="viewPort3d" ZoomExtentsWhenLoaded="true" Margin="0,0,0,66" Cursor="Hand" ShowViewCube="True">
            
            <helix:SunLight/>
        </helix:HelixViewport3D>`

**Comment by holance** [comment]
You need to calculate the center point yourself by calculating the center point of the geometry vertices loaded from your model.

**Comment by saklanmazozgur** [comment]
In my question is a clue of how to find the center point. The uploaded file type is .stl. How can I find the center point of this file with helixtoolkit?

**Comment by ju2pom** [comment]
I did it in my own project by finding the bounding sphere. If you have a geometry made of several parts you'll need to merge

**Comment by yziyacakmak** [comment]
You can use Size property of model,

...
var x_middle_point =device3D.Content.Bounds.SizeX/2;
var y_middle_point= device3D.Content.Bounds.SizeY/2;
var z_middle_point= device3D.Content.Bounds.SizeZ/2;
Point3D middlePoint=new Point3D(x_middle_point ,y_middle_point, z_middle_point);
...
