### ISSUE TITLE
Calling ZoomExtents for a ViewPort using a HelixToolkit.Wpf.SharpDX.OrthographicCamera does not work when using MeshGeometryModel3D

### ISSUE THREAD

**Issue by frankneumann** [helix-toolkit/helix-toolkit#1513]
I tried to use a HelixToolkit.Wpf.SharpDX.OrthographicCamera for displaying a MeshGeometryModel3D.
With this combination ZoomExtents does not zoom to the bounding box.

**Comment by holance** [comment]
Please try with the latest nightly build.
