### ISSUE TITLE
3D Surface Rendering using contours

### ISSUE THREAD

**Issue by DeshpandeJanhavi** [helix-toolkit/helix-toolkit#1514]
Hello, 
I have a list of contour points for a slice and stack of such slices. I want to generate a smooth surface by joining these points.
I have attached the list of contour points, 3d plot and the expected surface generation. Is there any way I can generate the surface using Helix toolkit in WPF?
![plot](https://user-images.githubusercontent.com/48976280/107461141-608ffd80-6b7f-11eb-9795-d9b31ba3892e.gif)
[contour_1_world_coord.txt](https://github.com/helix-toolkit/helix-toolkit/files/5955710/contour_1_world_coord.txt)
![3DSurface](https://user-images.githubusercontent.com/48976280/107461154-6980cf00-6b7f-11eb-9010-37f1c3ee537a.PNG)

**Comment by holance** [comment]
Helix toolkit sharpdx version has basic volume rendering. You can try to use it. Or you can find other library to do a remeshing based on the point cloud and display like normal mesh using helix toolkit.
