### ISSUE TITLE
How make always in correct point BillboardSingleImage3D when FixedSize = true

### ISSUE THREAD

**Issue by Vjacheslaw** [helix-toolkit/helix-toolkit#1516]
In HelixToolkit.Wpf.BillboardVisual3D it was possible to specify a property VerticalAlignment = VerticalAlignment.Bottom, which means Center BillboardVisual3D always in correct point.

How I can make analog of this function in HelixToolkit.Wpf.SharpDX.BillboardSingleImage3D?
For example  - Demo application 'BillboardDemo':
![image](https://user-images.githubusercontent.com/43916814/107663807-d63dbb80-6c9c-11eb-8c28-211e205d4284.png)

I want "Arctic Ocean" to always be on the border of the sphere, regardless of scale.

**Comment by SKARFX** [comment]
It would be very helpful! 👍
