### ISSUE TITLE
Multiple unique objects

### ISSUE THREAD

**Issue by KlaskSkovby** [helix-toolkit/helix-toolkit#1519]
I have been looking into the building demo where I'm able to select an object and get/set a value. 

Howeach each object are hardcoded into the .xaml.

Is it possible to have a dictionary of object. 
Visualise them and when i click them i get the unique key? 

When i e.g. Addbox multiple time, each of them counts as the same object when i use the method in the building demo

**Comment by holance** [comment]
You can always use code behind to create multiple models containing separate meshes.

**Comment by KlaskSkovby** [comment]
Thanks holance,

I used the Lego case as a good example for this, and it works perfektly
