### ISSUE TITLE
How to load 3DS file in Viewport3DX ?

### ISSUE THREAD

**Issue by TechAspirant** [helix-toolkit/helix-toolkit#1522]
Hello,

Can any one tell me how can I load 3DS file in Viewport3DX C# WPF application ?

HelixToolkit.Wpf.SharpDX.Assimp.Importer reader = new HelixToolkit.Wpf.SharpDX.Assimp.Importer();
HelixToolkit.Wpf.SharpDX.Assimp.HelixToolkitScene scene = reader.Load(<3ds File Path>);
GroupModel.AddNode(scene.Root);

**Comment by holance** [comment]
You can refer to the FIleLoadDemo for details
https://github.com/helix-toolkit/helix-toolkit/tree/develop/Source/Examples/WPF.SharpDX/FileLoadDemo

**Comment by TechAspirant** [comment]
I can see my 3DS file is loaded in scene graph in FileLoadDemo. But it still shows the default file in the viewer and not my 3DS file.
![image](https://user-images.githubusercontent.com/40688461/108622819-52848b80-7461-11eb-962a-bd348ddaa394.png)

**Comment by holance** [comment]
Seems like your model is either too small or the model location is not in the camera frustrum. You may want to rotate the camera around to find the model. Or try to do a zoom extend (ctrl+e).

**Comment by TechAspirant** [comment]
No, It doesn't work.
You can get my 3DS file at this place. Will you please have a look once at your place.
https://drive.google.com/file/d/1BR_wXLe-FGOmP2SSHAHBbPP9gYDnXTI3/view?usp=sharing

**Comment by holance** [comment]
Your model size is big, you need to adjust camera parameters so it can be properly show up. 
```
            Camera = new PerspectiveCamera()
            {
                LookDirection = new System.Windows.Media.Media3D.Vector3D(0, 0, -100),
                Position = new System.Windows.Media.Media3D.Point3D(0, 0, 100),
                UpDirection = new System.Windows.Media.Media3D.Vector3D(0, 1, 0),
                FarPlaneDistance = 50000,
                NearPlaneDistance = 1f
            };
```

**Comment by TechAspirant** [comment]
Have you tried at your place.
Does the change you mention work at your end.

**Comment by TechAspirant** [comment]
Is it possible to remive the background and have white background in the sample app.

**Comment by holance** [comment]
Uncheck the environment map check box on top right to remove the background.
Assimp importer only supports Viewport3DX for now.
You can try to use the existing StudioReader for HelixViewport3D.
