### ISSUE TITLE
Relative source binding for WPF SharpDX Group Model

### ISSUE THREAD

**Issue by DeshpandeJanhavi** [helix-toolkit/helix-toolkit#1525]
Hello,
I am trying to bind an observable collection of elements 3D to GroupModel using a relative source
`<hx:GroupModel3D ItemsSource="{Binding RelativeSource={RelativeSource AncestorType=UserControl}, Path=VolumePropertyPath, diag:PresentationTraceSources.TraceLevel=High}"></hx:GroupModel3D>`

But I am facing error: Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.UserControl', AncestorLevel='1'', BindingExpression:Path=VolumeMaterialSource; DataItem=null; target element is 'GroupModel3D'; target property is 'ItemsSource'

How to resolve this? Is there any other way of binding through relative source to GroupModel3D?

Edit:
I have observed that this binding works sometimes and fails most of the times with above mentioned error. How to resolve this unreliability? Am I missing something?

**Comment by holance** [comment]
Doesn't seem to be related to helix toolkit. It's wpf binding issue. You may want to check wpf related document or upload a sample project. Otherwise without knowing how your project is structured, it's not possible to help debug this issue.
