### ISSUE TITLE
How to input a image to hx2D:Button2D

### ISSUE THREAD

**Issue by zhichangxuexi** [helix-toolkit/helix-toolkit#1530]
Hello,Recently I was developing a helix based project，I want to input a image to hx2D:Button2D,but I write code like this,VS2019 software will report an error:
  <hx2D:Button2D Name="TestButton"  Margin="5" HorizontalAlignment="Center" 
        Command="hx:ViewportCommands.ZoomExtents">
                            <hx2D:Button2D.Content2D>
                                <hx2D:StackPanel2D>
                                   <hx2D:ImageModel2D VerticalAlignment="Center" HorizontalAlignment="Center" 
                                           Width="100" Height="100" 
                                           ImageStream="{Binding VM2D.ImageStream}">
                        </hx2D:ImageModel2D>
                                </hx2D:StackPanel2D>
                            </hx2D:Button2D.Content2D>
                        </hx2D:Button2D>

Could you help me?Thanks

**Comment by holance** [comment]
You can use wpf control directly. 2D control in helix toolkit has not been fully tested yet.
