### ISSUE TITLE
Can HelixToolkit wpf elements be used within HelixToolkit SharpDX viewport?

### ISSUE THREAD

**Issue by SwaroopSomanna** [helix-toolkit/helix-toolkit#1538]
Let's say I want to use the GridVisuals3D or an other element (which is part of HelixToolkit wpf) in a Viewport3DX. What are the downsides of using it in such a way?

**Comment by holance** [comment]
You can't use wpf model in sharpdx version.

**Comment by SwaroopSomanna** [comment]
> You can't use wpf model in sharpdx version.

So i have to create my own elements (like the GridVisuals3D) that are not available for SharpDX version for use in the SharpDX version?

**Comment by holance** [comment]
Yes.

**Comment by SwaroopSomanna** [comment]
> Yes. Usually just use mesh builder to rebuild mesh when property changes. You can either create your own view model or a new model which wraps the basic geometry model.

Ok. But why aren't the wpf version's elements included in the sharpDX version?

**Comment by holance** [comment]
We don't have bandwidth to implement and maintain all these models.

**Comment by SwaroopSomanna** [comment]
Ok.
