### ISSUE TITLE
D3DCompiller_xx.dll missing.

### ISSUE THREAD

**Issue by ikeough** [helix-toolkit/helix-toolkit#154]
We have tried the SharpDX Helix3D component on a broad range of systems with different versions of Windows, DirectX, etc. and we've found several issues.

- Some users were getting a "D3DCompiler_43.dll" missing error. This was resolved by installing the DirectX runtime components.
- After installing the DirectX runtime components some users were then getting a message that "sharpdx_direct3d11_1_effects_x64.dll" could not be found. This file isn't included in Helix, but IS part of SharpDX. 
- After including the "sharpdx_direct3d11_1_effects_x64.dll" in the install, some users were then getting a "D3DCompiler_44.dll" missing error.

These issues can be found here:
https://github.com/DynamoDS/Dynamo/issues/4367
https://github.com/DynamoDS/Dynamo/issues/4211

**Comment by objorke** [comment]
Should these dlls be included in the NuGet package? Is there a version issue (v43 or v44)? What about writing a wiki page about what to install/require for a release that is using this component?

**Comment by ikeough** [comment]
I've read every issue on SharpDX's repo, including [this one](https://github.com/sharpdx/SharpDX/issues/468), which points to the problem directly. Strangely, that issue is closed, but the problem persists.

**Comment by micampbell** [comment]
Try installing (or re-installing) DirectX: http://www.microsoft.com/en-us/download/details.aspx?id=35

**Comment by ikeough** [comment]
@micampbell Reinstalling DirectX does not solve that problem, although you do have to make sure that the users have the DirectX runtime components installed (as specified on the SharpDX installation page). 

I can confirm that upgrading the version of SharpDX used by Helix has solved this problem for all users who were having it. I will submit a pull request with the updates to the newer SharpDX packages after we get the next release of [Dynamo](https://github.com/DynamoDS/Dynamo) out the door.
