### ISSUE TITLE
Unable to Run UWP Simple Demo

### ISSUE THREAD

**Issue by QilongTang** [helix-toolkit/helix-toolkit#1541]
Hi,

I am recently trying to look at the possibility of using Helix-toolkit as a combination of [uno platform](https://platform.uno/) so that I can make a cross platform app which displays geometry.

However, when trying to run the UWP simple demo, I run into the following error while everything builds fine.
![image](https://user-images.githubusercontent.com/3942418/111210516-b81cf100-85a3-11eb-9b96-06c6e4969b3a.png)

Can you help me address this? And if any of you know any existing example how helix-toolkit is used in UWP, please share with me. Much appreciated!

Cheers,
Aaron-

**Comment by holance** [comment]
Try to restore the nuget package. 
Uno may not be compatible with helix toolkit. Helix toolkit relies on direct x, which is only available on windows.

**Comment by QilongTang** [comment]
Thanks, I found the following console messages: 
NU1201: Project HelixToolkit.UWP is not compatible with uap10.0.17763 (UAP,Version=v10.0.17763). Project HelixToolkit.UWP supports: uap10.0.18362 (UAP,Version=v10.0.18362)

I guess I will need to update my Windows 10 to address this?

**Comment by holance** [comment]
Seems like it.

**Comment by QilongTang** [comment]
Since it is most likely issue on my end, closing it for now
