### ISSUE TITLE
UWP high RAM usage

### ISSUE THREAD

**Issue by JuandreG** [helix-toolkit/helix-toolkit#1542]
Hello.

I'm using a Element3DPresenter control and it's Content property binds to a SceneNodeGroupModel3D to where I add models dynamically. Basically I pick a model and it gets added to the SceneNodeGroupModel3D and displayed by the Element3DPresenter in a Viewport3DX control.

All my models are .glb files and the sizes vary from between 500kb to 16mb.

When I load these models dynamically it results in high RAM usage. When I add all the models I need to add the application would use up to 8gb of RAM. And when I navigate away from the page containing the Viewport3DX, Element3DPresenter controls and the SceneNodeGroupModel3D property and calling EffectsManager.Dispose() the RAM doesn't get cleared. Maybe after a few navigation's has taken place it would clear some of it but not all, not even half.

Am I missing something? Is there a best practice I can follow? How can I manually clear all the model data when navigating away, if that is possible?

**Comment by holance** [comment]
Are you loading same model multiple times? How many models do you need to load?

**Comment by JuandreG** [comment]
There is 2 models that I load about 8 times but they are quite small. In total I load about 50 to 70 models. Most of them are small in size but a few are larger in size.

**Comment by holance** [comment]
Try to avoid loading duplicate meshes. Geometry can be shared between multiple models.
Most of the memories are occupied by geometry itself for hit testing. If you don't need hit testing, you can call 'Geometry3D.SetAsTransient()' after immediately after loading the meshes.

Turn off the octree may save some memory as well.

**Comment by JuandreG** [comment]
I'll give that a try and come back to you, thank you very much!

**Comment by JuandreG** [comment]
I'm using SceneNode though, how would I call Geometry3D.SetAsTransient() on SceneNode?

**Comment by JuandreG** [comment]
![Capture](https://user-images.githubusercontent.com/54146697/111582051-f0e6e100-87c2-11eb-9c12-b79122f812a6.JPG)

This is how I load the models. "groupModel" is of type SceneNodeGroupModel3D

**Comment by holance** [comment]
'(MeshNode.Geometry as MeshGeomerty3D).SetAsTransient()'

**Comment by JuandreG** [comment]
![Capture2](https://user-images.githubusercontent.com/54146697/111586226-2bec1300-87c9-11eb-824a-b3b24b0f3894.JPG)

After I added your suggestion. Still high RAM usage.

Maybe I'm doing something wrong somewhere

**Comment by holance** [comment]
What's the ram usage if you loads your models in other software like blender?

**Comment by JuandreG** [comment]
I don't have blender. But I dohave the standard Windows 10 3D Viewer. When I open the models there the usage is very low. With 3D Viewer I can only open 1 model. In 3D Viewer it uses about 158mb of RAM. I open the same model in HelixToolkit and it uses 1.1gb.

**Comment by holance** [comment]
Could you share a sample model?

**Comment by JuandreG** [comment]
How would I share it with you? I do have a sample I can share

**Comment by JuandreG** [comment]
Is there maybe something I can do when creating the EffectsManager to manage resources better? I just create DefaultEffectsManager but then I pass the AdapterIndex of the graphics card with the most memory. I'm then using the graphics card for the Viewport3DX.

**Comment by holance** [comment]
You can try to upload the same in this thread.

**Comment by JuandreG** [comment]
I tried adding it here but no luck.

**Comment by holance** [comment]
You can create a repo and upload there

**Comment by JuandreG** [comment]
I don't believe my models are the problem. I generated n fbx file from HelixToolkit/Assimp that was 385mb in size. I opened that model in 3D Viewer and it only used 128mb of RAM. I open the same model with HelixToolkit and 4.7gb of RAM was used. Can I make it more dependant on the graphics card in some way?

**Comment by holance** [comment]
Does your model have a lot of textures?

**Comment by holance** [comment]
Please upload your big model. Otherwise it is hard for me to debug the issue.

**Comment by JuandreG** [comment]
I'll find a place to upload the model and tell you when I have it ready. I found that the memory does get cleared but only a while after closing the view containing the Viewport3DX. Not directly after it closes.

**Comment by holance** [comment]
You need to manually call garbage collection if you want to release memory immediately

**Comment by JuandreG** [comment]
I tried that too. I'll try all 4 generations and come back to you.

**Comment by JuandreG** [comment]
That worked to some extent. But still not immediately.

I'm sure it's me doing something wrong and there is nothing wrong with your toolkit. I'll debug further and post my findings here. You don't need to worry about this anymore.

Thanks for all your inputs.

Amazing piece of work is this toolkit.

**Comment by holance** [comment]
I found out in some cases texture is being duplicated. If you have time, I still want you to upload the sample model so I can do more debugging.
