### ISSUE TITLE
DiffuseMaterial with enableAutoGenMipMap = false

### ISSUE THREAD

**Issue by sjc9999** [helix-toolkit/helix-toolkit#1552]
How do I create a DiffuseMaterial with enableAutoGenMipMap  = false?

I have tried to find an example on how to do this but have been unsuccessful.

Thanks

oh by the way I been using the BillboardVerticalAlignment and BillboardHorizontalAlignment and it works great, thanks for adding it.

**Comment by sjc9999** [comment]
I think I founded it, I did this, and now my texture is not blurry:

                    SamplerStateDescription samplerStateDescription = new SamplerStateDescription()
                    {
                        AddressU = TextureAddressMode.Wrap,
                        AddressV = TextureAddressMode.Wrap,
                        AddressW = TextureAddressMode.Wrap,
                    };

                    MemoryStream memoryStream = new MemoryStream();
                    file.CopyTo(memoryStream);

                    diffuseMaterial = new DiffuseMaterial
                    {
                        DiffuseMap = memoryStream,
                        DiffuseMapSampler = samplerStateDescription,
                    };

**Comment by holance** [comment]
Setting ’SamplerStateDescription.MaximumLod = 0' should do the job.
