### ISSUE TITLE
LineGeometryModel3D Bounds not updating when LineGeometry3D.IsDynamic = true

### ISSUE THREAD

**Issue by sjc9999** [helix-toolkit/helix-toolkit#1555]
I'm using with LineGeometry3D with IsDynamic = true as shown here:

LineGeometry3D lineGeometry = new LineGeometry3D()
{
	PreDefinedVertexCount = steps,
	PreDefinedIndexCount = (steps - 1) * 2,
	IsDynamic = true,
};

LineGeometryModel3D lineGeometryModel = new LineGeometryModel3D()
{
	Geometry = lineGeometry,
	Color = Colors.Violet,
	Thickness = 1.7,
};

When I update the LineGeometry3D Positions and Indices the Bounds update as shown here:

lineGeometry	{HelixToolkit.SharpDX.Core.LineGeometry3D}
	Bound	{Minimum:X:-2.4942286 Y:-1.0346919 Z:-0.5175258 Maximum:X:-0.03416315 Y:0.90985554 Z:0.6107951}	
	BoundingSphere	{Center:X:-1.5894607 Y:-0.20421538 Z:-0.0045135114 Radius:1.8362526}	

But the LineGeometryModel3D doesn't update as shown here:

lineGeometryModel	{HelixToolkit.Wpf.SharpDX.LineGeometryModel3D}
	Bounds	{Minimum:X:0 Y:0 Z:0 Maximum:X:0 Y:0 Z:0}	
	BoundsSphere	{Center:X:0 Y:0 Z:0 Radius:0}	
	BoundsSphereWithTransform	{Center:X:0 Y:0 Z:0 Radius:0}	
	BoundsWithTransform	{Minimum:X:0 Y:0 Z:0 Maximum:X:0 Y:0 Z:0}	
	
Everything works fine as long as the camera is pointed to 0,0,0 and the rotation is around that point
but if I focus and rotate on a point on the line the line disappears / reappears as I rotate and zoom in / out

I have tried calling these methods on LineGeometry3D but it makes no difference:

UpdateVertices();
UpdateTriangles();
UpdateBounds();

I can send you a test solution I created if you want.

**Comment by holance** [comment]
Please upload the sample.

**Comment by sjc9999** [comment]
OK here is the code please see the readme.txt

[DynamicTest.zip](https://github.com/helix-toolkit/helix-toolkit/files/6257821/DynamicTest.zip)
