### ISSUE TITLE
Shadows UWP

### ISSUE THREAD

**Issue by JuandreG** [helix-toolkit/helix-toolkit#1557]
Hello!

I'm using the same Viewport3DX for multiple purposes. My scenario is I open a model in the Viewport and it has shadows. But as soon as I load multiple models in the same Viewport then the shadows disappear. 

Eg: 
![Single](https://user-images.githubusercontent.com/54146697/114195193-8acc2480-9950-11eb-85bc-11968038639a.JPG)
![Context](https://user-images.githubusercontent.com/54146697/114195205-8e5fab80-9950-11eb-955f-c14cf173993f.JPG)

The first picture is when it's the only model in the Viewport. The second is when it is added to a collection of models in the Viewport.

All models are added to a SceneNodeGroupModel3D property.

In the Viewport I have an Element3DPresenter and binding the Content property to the SceneNodeGroupModel3D property.
I also have a ShadowMap3D item with no properties set.

**Comment by holance** [comment]
You may want to adjust ShadowMap properties according to your model size. ShadowMap internally uses an orthographic camera to render by default. If your model size is changed significantly, the camera may no longer be able to render your model properly.

**Comment by JuandreG** [comment]
I'll give that a try thanks!

**Comment by holance** [comment]
Added a feature to automatically covers complete scene with ShadowMap. You can try the latest nightly build and use `ShadowMap3D.AutoCoverCompleteScene = true` to enable this feature. This may help your case.
