### ISSUE TITLE
ZoomExtentsWhenLoaded of Viewport3DX does not work 

### ISSUE THREAD

**Issue by springile** [helix-toolkit/helix-toolkit#1564]
Hi 

In example, FileLoadDemo, in "helix-toolkit-develop\Source\Examples\WPF.SharpDX\FileLoadDemo"
I added ZoomExtentsWhenLoaded, there is no effect.

e.g. open file car.3ds, car is still too big and I have zoom out to see the full car.
       <hx:Viewport3DX
            x:Name="view"
            Grid.Row="1"
            BackgroundColor="#595959"
            Camera="{Binding Camera}"
            CameraMode="Inspect"
            CameraRotationMode="Trackball"
            EffectsManager="{Binding EffectsManager}"
            EnableSwapChainRendering="True"
            ZoomExtentsWhenLoaded="True"

Please help.

John.

**Comment by holance** [comment]
`ZoomExtentsWhenLoaded` only takes effect when viewport is first being loaded. Once you change your model, you need to manually call `Viewport3DX.ZoomExtents()` to do the zoom extent again.

**Comment by springile** [comment]
Hi Holance

Ok, I see.

But when should ZoomExtents() be called?

This is the code I'm using:
viewport.ZoomExtents()； is just end of LoadAsync. but it does not work.

	private void LoadAsync(string model3DPath)
		{
			Task.Run(() =>
			{
				var loader = new Importer();
				return loader.Load(model3DPath);
			}).ContinueWith((result) =>
			{
				if (result.IsCompleted)
				{
					scene = result.Result;
					Animations.Clear();
					GroupModel.Clear();
					if (scene != null)
					{
						if (scene.Root != null)
						{
							foreach (var node in scene.Root.Traverse())
							{
								if (node is MaterialGeometryNode m)
								{
									if (m.Material is PBRMaterialCore pbr)
									{
										pbr.RenderEnvironmentMap = RenderEnvironmentMap;
									}
									else if (m.Material is PhongMaterialCore phong)
									{
										phong.RenderEnvironmentMap = RenderEnvironmentMap;
									}
								}
							}
						}
						GroupModel.AddNode(scene.Root);
						if (scene.HasAnimation)
						{
							foreach (var ani in scene.Animations)
							{
								Animations.Add(ani);
							}
						}
						foreach (var n in scene.Root.Traverse())
						{
							n.Tag = new AttachedNodeViewModel(n);
						}
					}
                                        viewport.ZoomExtents();
				}
				else if (result.IsFaulted && result.Exception != null)
				{
					//MessageBox.Show(result.Exception.Message);
				}
			}, TaskScheduler.FromCurrentSynchronizationContext());
		}
Please help.

Thanks .
