### ISSUE TITLE
when should ZoomExtents() be called

### ISSUE THREAD

**Issue by springile** [helix-toolkit/helix-toolkit#1566]
Hi Holance

When should ZoomExtents() be called? the right time to call. 

This is the code I'm using:
viewport.ZoomExtents()； is at just end of LoadAsync. but it does not work.

private void LoadAsync(string model3DPath)
	{
		Task.Run(() =>
		{
			var loader = new Importer();
			return loader.Load(model3DPath);
		}).ContinueWith((result) =>
		{
			if (result.IsCompleted)
			{
				scene = result.Result;
				Animations.Clear();
				GroupModel.Clear();
				if (scene != null)
				{
					if (scene.Root != null)
					{
						foreach (var node in scene.Root.Traverse())
						{
							if (node is MaterialGeometryNode m)
							{
								if (m.Material is PBRMaterialCore pbr)
								{
									pbr.RenderEnvironmentMap = RenderEnvironmentMap;
								}
								else if (m.Material is PhongMaterialCore phong)
								{
									phong.RenderEnvironmentMap = RenderEnvironmentMap;
								}
							}
						}
					}
					GroupModel.AddNode(scene.Root);
					if (scene.HasAnimation)
					{
						foreach (var ani in scene.Animations)
						{
							Animations.Add(ani);
						}
					}
					foreach (var n in scene.Root.Traverse())
					{
						n.Tag = new AttachedNodeViewModel(n);
					}
				}
                                    viewport.ZoomExtents();
			}
			else if (result.IsFaulted && result.Exception != null)
			{
				//MessageBox.Show(result.Exception.Message);
			}
		}, TaskScheduler.FromCurrentSynchronizationContext());
	}
Please help.

Thanks .

John

**Comment by holance** [comment]
Try using main dispatch with background priority to call.

**Comment by springile** [comment]
Holance

It works.

Thanks.

John
