### ISSUE TITLE
how to make BillboardText3D show top ，thit is to say, BillboardText3D isn't occluded by the model?

### ISSUE THREAD

**Issue by zhichangxuexi** [helix-toolkit/helix-toolkit#1572]
![image](https://user-images.githubusercontent.com/40328051/116323291-4239b580-a7f0-11eb-9d42-a0efa3496e79.png)

Just like this picture above，how to make BillboardText3D show top ，thit is to say, BillboardText3D isn't occluded by the model in helix.sharpDx?

thanks

**Comment by holance** [comment]
It's not possible for now.

**Comment by chrkon** [comment]
As @holance mentioned, this is not possible at the moment, but I have a simmilar requirement for my actual project. So It would be a nice feature.

If you don't need the SwapChainRendering (EnableSwapChainRendering="False") then you can use the idea of a 2D overlay canvas.  There is a example in the WPF part ([ExampleBrowser, Example "Overlay"](https://github.com/helix-toolkit/helix-toolkit/tree/develop/Source/Examples/WPF/ExampleBrowser/Examples/Overlay)). I have used this in a previous project and it has worked very well. I think this should be possible with the SharpDX part, too.

**Comment by holance** [comment]
Added 'TopMostGroup3D' to support this feature.
