### ISSUE TITLE
How move the model by Manipulator in sharpdx

### ISSUE THREAD

**Issue by sinaone1** [helix-toolkit/helix-toolkit#1575]
I rotated 15 degrees my Manipulator in y axis to be aligned with my model, But when I move the manipulator instead of move the model to manipulator direction it goes the world space y axis not local axis.
How can I fix it?
This is my code 
`   tranformManupulatorMaster.EnableRotation = true;
    tranformManupulatorMaster.EnableScaling = false;
    tranformManupulatorMaster.CenterOffset = new Vector3(getCenter.X, getCenter.Y, getCenter.Z);
RotateTransform3D myRotateTransform = new RotateTransform3D(new AxisAngleRotation3D(new Vector3D(0, 1, 0), -modelAngle), new Point3D(getCenter.X, getCenter.Y, getCenter.Z));
    var binding = new Binding("");
    binding.Source = container;
    tranformManupulatorMaster.SetBinding(MyTranslateManipulator3D.TargetProperty, binding);
    tranformManupulatorMaster.Transform = myRotateTransform;
    // Add to containerMaster
    containerMaster3D.Children.Add(tranformManupulatorMaster);`

**Comment by holance** [comment]
Could you upload a sample project for your issue?

**Comment by sinaone1** [comment]
Sure
I uploaded the example here and if you move the manipulator , it goes to right direction but 3d model goes to a wrong direction and it doesn't follow manipulator.
[Example.zip](https://github.com/helix-toolkit/helix-toolkit/files/6413078/Example.zip)

**Comment by holance** [comment]
The manipulator currently does not support self transform, the three arrows in manipulator are aligned on xyz coordinates.

**Comment by sinaone1** [comment]
Oh ok no there is not any way to do that no?

**Comment by holance** [comment]
You can try to create your own manipulate to do it.

**Comment by sinaone1** [comment]
Oh ok thank you
