### ISSUE TITLE
SharpDX alternative to Wpf CoordinateSystemVisual3D?

### ISSUE THREAD

**Issue by SHOEGAZEssb** [helix-toolkit/helix-toolkit#1580]
Hi I am looking to put a coordinate system in the center of each of my models to show their rotation in the viewport.
Helix wpf has the CoordinateSystemVisual3D, does Helix.Wpf.SharpDX have something similar?

Cheers,
Tim

**Comment by holance** [comment]
https://github.com/helix-toolkit/helix-toolkit/tree/develop/Source/Examples/WPF.SharpDX/CustomViewCubeDemo
Please refer to CustomViewCubeDemo for detail.

**Comment by SHOEGAZEssb** [comment]
Thank you! Worked perfectly
