### ISSUE TITLE
Arrow on top of tube

### ISSUE THREAD

**Issue by matthiaswerner2** [helix-toolkit/helix-toolkit#1581]
Hey,

i calculated a circle path from point A to B (via point C).
How can i add an arrow on the top?

`  private TubeVisual3D VisualizeCurve(Point3D src, Point3D dest, Point3D circ)
        {
            //Create new tubevisual3d and initalize
            var tube = new TubeVisual3D()
            {
                Material = MaterialHelper.CreateMaterial(AppConstants.LineColor),
                Diameter = AppConstants.LaneDiameter,
                ThetaDiv = 16
            };

            // calculate radius of dest <-> circle
            var rad = Math.Pow((Math.Pow(circ.X - src.X, 2) + Math.Pow(circ.Y - src.Y, 2) + Math.Pow(circ.Z - src.Z, 2)), 0.5);

            // calculate vectors from circle to source and destination
            var v1 = src - circ;
            var v2 = dest - circ;

            // get crossproducts of the vectors 
            var z = Vector3D.CrossProduct(v1, v2);
            var x = v1;
            var y = Vector3D.CrossProduct(x, z);

            // normalization
            x.Normalize();
            y.Normalize();

            // calculation of new vectorproducts
            double v2X = Vector3D.DotProduct(v2, x);
            double v2Y = Vector3D.DotProduct(v2, y);
            double v2A = Math.Atan2(v2Y, v2X);

            // draw pointcollection of 100 intermediated points 
            const int n = 100;
            var pts = new Point3DCollection();
            double da = v2A / (n - 1);

            for (int i = 0; i < n; i++)
            {
                double a = i * da;
                Vector3D v = x * Math.Cos(a) + y * Math.Sin(a);
                double r = rad;
                var p = circ + v * r;
                pts.Add(p);
            }

            // set path of tube to the created points
            tube.Path = pts;

            return tube;
        }`

Maybe someone can help me.

Thanks a lot.

**Comment by matthiaswerner2** [comment]
> 
> 
> Hey,
> 
> i calculated a circle path from point A to B (via point C).
> How can i add an arrow on the top?
> 
> ` private TubeVisual3D VisualizeCurve(Point3D src, Point3D dest, Point3D circ)
> {
> //Create new tubevisual3d and initalize
> var tube = new TubeVisual3D()
> {
> Material = MaterialHelper.CreateMaterial(AppConstants.LineColor),
> Diameter = AppConstants.LaneDiameter,
> ThetaDiv = 16
> };
> 
> ```
>         // calculate radius of dest <-> circle
>         var rad = Math.Pow((Math.Pow(circ.X - src.X, 2) + Math.Pow(circ.Y - src.Y, 2) + Math.Pow(circ.Z - src.Z, 2)), 0.5);
> 
>         // calculate vectors from circle to source and destination
>         var v1 = src - circ;
>         var v2 = dest - circ;
> 
>         // get crossproducts of the vectors 
>         var z = Vector3D.CrossProduct(v1, v2);
>         var x = v1;
>         var y = Vector3D.CrossProduct(x, z);
> 
>         // normalization
>         x.Normalize();
>         y.Normalize();
> 
>         // calculation of new vectorproducts
>         double v2X = Vector3D.DotProduct(v2, x);
>         double v2Y = Vector3D.DotProduct(v2, y);
>         double v2A = Math.Atan2(v2Y, v2X);
> 
>         // draw pointcollection of 100 intermediated points 
>         const int n = 100;
>         var pts = new Point3DCollection();
>         double da = v2A / (n - 1);
> 
>         for (int i = 0; i < n; i++)
>         {
>             double a = i * da;
>             Vector3D v = x * Math.Cos(a) + y * Math.Sin(a);
>             double r = rad;
>             var p = circ + v * r;
>             pts.Add(p);
>         }
> 
>         // set path of tube to the created points
>         tube.Path = pts;
> 
>         return tube;
>     }`
> ```
> 
> Maybe someone can help me.
> 
> Thanks a lot.

**Comment by holance** [comment]
Create your own tube visual (copy the tube visual source code) and adds an arrow at the end of the tube.
