### ISSUE TITLE
Helix Simple Demo - Empty screen with no error

### ISSUE THREAD

**Issue by Dereen** [helix-toolkit/helix-toolkit#1589]
Hello,

im a WPF develeper and I want to use Helix toolkit for my project. I downloaded this repository and tried to run Simple Demo from Visual Studio 19. Installed latest DirectX 12.

This is what i get
![SimpleDemoScreenshot](https://user-images.githubusercontent.com/8763089/118820829-ea561200-b8b6-11eb-9a72-7274b104b9e5.PNG)

No compile error
No runtime error 
Nothing only changing FPS in down left corner.

Output from Visualt studia:
`'SimpleDemo.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimpleDemo.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\operator\Documents\helix-toolkit-develop\Source\Examples\WPF\SimpleDemo\bin\Debug\SimpleDemo.exe'. Symbols loaded.
'SimpleDemo.exe' (CLR v4.0.30319: SimpleDemo.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimpleDemo.exe' (CLR v4.0.30319: SimpleDemo.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimpleDemo.exe' (CLR v4.0.30319: SimpleDemo.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimpleDemo.exe' (CLR v4.0.30319: SimpleDemo.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimpleDemo.exe' (CLR v4.0.30319: SimpleDemo.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimpleDemo.exe' (CLR v4.0.30319: SimpleDemo.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimpleDemo.exe' (CLR v4.0.30319: SimpleDemo.exe): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\PrivateAssemblies\Runtime\Microsoft.VisualStudio.Debugger.Runtime.Desktop.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Step into: Stepping over non-user code 'ExampleBrowser.App..ctor'
'SimpleDemo.exe' (CLR v4.0.30319: SimpleDemo.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimpleDemo.exe' (CLR v4.0.30319: SimpleDemo.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Step into: Stepping over non-user code 'ExampleBrowser.App.InitializeComponent'
'SimpleDemo.exe' (CLR v4.0.30319: SimpleDemo.exe): Loaded 'C:\Users\operator\Documents\helix-toolkit-develop\Source\Examples\WPF\SimpleDemo\bin\Debug\HelixToolkit.Wpf.dll'. Symbols loaded.
'SimpleDemo.exe' (CLR v4.0.30319: SimpleDemo.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimpleDemo.exe' (CLR v4.0.30319: SimpleDemo.exe): Loaded 'c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\xamldiagnostics\Framework\x86\Microsoft.VisualStudio.DesignTools.WpfTap.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimpleDemo.exe' (CLR v4.0.30319: SimpleDemo.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimpleDemo.exe' (CLR v4.0.30319: SimpleDemo.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\SMDiagnostics\v4.0_4.0.0.0__b77a5c561934e089\SMDiagnostics.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimpleDemo.exe' (CLR v4.0.30319: SimpleDemo.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Internals\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Internals.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SimpleDemo.exe' (CLR v4.0.30319: SimpleDemo.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 0x3834 has exited with code 0 (0x0).
The thread 0x381c has exited with code 0 (0x0).`

I added dxdiag result
[DxDiag.txt](https://github.com/helix-toolkit/helix-toolkit/files/6509072/DxDiag.txt)

Thank you for your help.
Valentyn

**Comment by holance** [comment]
Are all other examples showing the same empty screen? Wpf is using directx 9.

**Comment by holance** [comment]
Are you using AMD graphics card? Try to update the driver.

**Comment by Dereen** [comment]
> Are all other examples showing the same empty screen? Wpf is using directx 9.

Yes, all of them are empty screens. Except some menus which arent in rendered by helix toolkit.

**Comment by Dereen** [comment]
> Are all other examples showing the same empty screen? Wpf is using directx 9.

Yes, I tried ExampleBrowser. Every demo was empty, except some menus which arent rendered by helixtoolkit.

> Are you using AMD graphics card? Try to update the driver.

Yes, I updated drivers for chipset and integrated gpu.

**Comment by holance** [comment]
Seems like your system is having issue with dx9 rendering. Helix toolkit wpf uses wpf 3d engine for rendering, it's not a helix toolkit issue.

**Comment by holance** [comment]
You can try to use HelixToolkit.Wpf.SharpDX version instead of HelixToolkit.Wpf.
