### ISSUE TITLE
Convert from WPF to WPF-SharpDX

### ISSUE THREAD

**Issue by ktoonsez** [helix-toolkit/helix-toolkit#1592]
Looking for some guidance on converting from the "http://helix-toolkit.org/wpf" HelixViewport3D to the "http://helix-toolkit.org/wpf/SharpDX" HelixViewport3DX.  As you will see from the pictures below the non-SharpDX one looks great and the SharpDX one looks very all bizarre, I know it has to be due to lighting of coloring issues but I cannot for the life of me figure out what I am doing wrong.  Hope some one here can shed some light on it.  Here are some code snippets and xaml:

Code for colors for non-SharpDX:
            'Init setup

            For Each stlModel As String In stlModels
                Dim materialGroup As New MaterialGroup
                Dim mainColor As Color = Colors.White
                Dim emissMat As EmissiveMaterial = New EmissiveMaterial(New SolidColorBrush(mainColor))
                Dim diffMat As DiffuseMaterial = New DiffuseMaterial(New SolidColorBrush(mainColor))
                Dim specMat As SpecularMaterial = New SpecularMaterial(New SolidColorBrush(mainColor), 100)
                materialGroup.Children.Add(emissMat)
                materialGroup.Children.Add(diffMat)
                materialGroup.Children.Add(specMat)
                Dim link As Model3DGroup = import.Load(stlModel)
                Dim model As GeometryModel3D = TryCast(link.Children(0), GeometryModel3D)
                model.Material = materialGroup
                model.BackMaterial = materialGroup
                Joints.Add(New Joint(link))
                'If i >= 21 And i <= 28 Then
                RA.Children.Add(Joints(Joints.Count - 1).model)
                'End If
                i += 1
            Next

           
            'Change Color
    Private Function changeModelColor(ByVal pModel As GeometryModel3D, ByVal newColor As Color) As Color
        If pModel Is Nothing Then Return oldColor
        Dim previousColor As Color = Colors.Black
        Dim mg As MaterialGroup = CType(pModel.Material, MaterialGroup)

        If mg.Children.Count > 0 Then
            Try
                previousColor = (CType(mg.Children(0), EmissiveMaterial)).Color
                CType(mg.Children(0), EmissiveMaterial).Color = newColor
                CType(mg.Children(1), DiffuseMaterial).Color = newColor
            Catch exc As Exception
                previousColor = oldColor
            End Try
        End If

        Return previousColor
    End Function

Code for SharpDX:
            'Init setup

            For Each stlModel As String In stlModels
                            Dim materialGroup As New MaterialGroup
                            Dim mainColor As Color = Colors.White
                            Dim emissMat As EmissiveMaterial = New EmissiveMaterial(New SolidColorBrush(mainColor))
                            Dim diffMat As DiffuseMaterial = New DiffuseMaterial(New SolidColorBrush(mainColor))
                            Dim specMat As SpecularMaterial = New SpecularMaterial(New SolidColorBrush(mainColor), 100)
                            materialGroup.Children.Add(emissMat)
                            materialGroup.Children.Add(diffMat)
                            materialGroup.Children.Add(specMat)
                            Dim reader As New HelixToolkit.Wpf.SharpDX.StLReader 'HelixToolkit.Wpf.SharpDX.Assimp.Importer
                            Dim models = reader.read(stlModel)
                            Dim PortModel As New MeshGeometryModel3D
                            PortModel.Geometry = models(0).Geometry
                            DirectCast(models(0).Material, HelixToolkit.Wpf.SharpDX.Model.PhongMaterialCore).EmissiveColor = New SharpDX.Color4(emissMat.Color.R, emissMat.Color.G, emissMat.Color.B, emissMat.Color.A)
                            DirectCast(models(0).Material, HelixToolkit.Wpf.SharpDX.Model.PhongMaterialCore).DiffuseColor = New SharpDX.Color4(diffMat.Color.R, diffMat.Color.G, diffMat.Color.B, diffMat.Color.A)
                            DirectCast(models(0).Material, HelixToolkit.Wpf.SharpDX.Model.PhongMaterialCore).SpecularColor = New SharpDX.Color4(specMat.Color.R, specMat.Color.G, specMat.Color.B, specMat.Color.A)
                            PortModel.Material = models(0).Material.ConvertToMaterial()
                            Joints.Add(New Joint(link, PortModel))
                            RA.Children.Add(Joints(Joints.Count - 1).model)
                            viewPort3d.Items.Add(PortModel)
                            i += 1
            Next

'Change Color

    Private Function changeModelColor(ByVal pModel As GeometryModel3D, ByVal newColor As Color) As Color
        If pModel Is Nothing Then Return oldColor
        Dim previousColor As Color = Colors.Black
        Dim mg As MaterialGroup = CType(pModel.Material, MaterialGroup)

        If mg.Children.Count > 0 Then
            Try
                previousColor = (CType(mg.Children(0), EmissiveMaterial)).Color
                DirectCast(meshmodels.Material, HelixToolkit.Wpf.SharpDX.PhongMaterial).EmissiveColor = New SharpDX.Color4(newColor.R, newColor.G, newColor.B, newColor.A / 255)
                DirectCast(meshmodels.Material, HelixToolkit.Wpf.SharpDX.PhongMaterial).DiffuseColor = New SharpDX.Color4(newColor.R, newColor.G, newColor.B, newColor.A / 255)
            Catch exc As Exception
                previousColor = oldColor
            End Try
        End If

        Return previousColor
    End Function

'Xaml Light Setup for NON-SharDX
            <helix:DefaultLights/>

'Xaml Light Setup for SharpDX (Nothing works good, I even captured the ones from the DefaultLights of the NON-SharpDX and still not good)

            <helix:AmbientLight3D Color="#FF1E1E1E" />
            <helix:DirectionalLight3D Color="#BBBBBB" Direction="0.1,1,-1" Name="Light1"/>
            <helix:DirectionalLight3D Color="#333333" Direction="-9834, -9238, -3646" Name="Light2"/>
            <helix:DirectionalLight3D Color="#333333" Direction="-9834, -9238, -3646" Name="Light3"/>
            <helix:DirectionalLight3D Color="#333333" Direction="-9834, -9238, -3646" Name="Light4"/>

non-SharpDX
![non-dx](https://user-images.githubusercontent.com/1626800/119573001-7c9f5f80-bd68-11eb-9b4a-fcb0f6702858.png)

SharpDX 
![dx](https://user-images.githubusercontent.com/1626800/119572999-7c06c900-bd68-11eb-82c0-d3b756ef97e7.png)

**Comment by holance** [comment]
Try to remove the ambient light or make the ambient light color darker.

**Comment by ktoonsez** [comment]
> Try to remove the ambient light or make the ambient light color darker.

No luck with that.

**Comment by holance** [comment]
Try to remove the emissive color, or reduce the emissive color brightness in the material.

**Comment by ktoonsez** [comment]
> Try to remove the emissive color, or reduce the emissive color brightness in the material.

Ooooooh man, that was the trick!!!  That was so huge, thanks so much, removing or reducing the emissive worked great, not the SharpDX looks just as great as the standard!
