### ISSUE TITLE
update problem with assimp

### ISSUE THREAD

**Issue by goldv72** [helix-toolkit/helix-toolkit#1593]
Hello!
I tried updating the program to 2.16.1
received such a message
Unable to resolve dependencies. "AssimpNet 4.1.0" is not compatible with 'HelixToolkit.SharpDX.Assimp 2.16.1 limitation: AssimpNet (> = 5.0.0-beta1)'.

**Comment by holance** [comment]
You need to update the AssimpNet to 5.0.0-beta 1. It is a pre-release.

**Comment by goldv72** [comment]
thanks, holance
i did it
now I have another problem with filenames.
filenames contain Russian letters. Everything was fine before but now the name consists of unreadable characters

**Comment by eriove** [comment]
> 
> 
> thanks, holance
> i did it
> now I have another problem with filenames.
> filenames contain Russian letters. Everything was fine before but now the name consists of unreadable characters

That's unfortunately a known bug in Assimp, see https://github.com/assimp/assimp/issues/3340

We're copying files to the temp folder and renaming them as a workaround right now

**Comment by goldv72** [comment]
thanks again
