### ISSUE TITLE
Memory leak when changing model

### ISSUE THREAD

**Issue by bouazaoui** [helix-toolkit/helix-toolkit#1596]
How to resolve the memory leak when i change model, the memory leak is substantial when the switch is between huge stl models.

[helix-toolkit forked](https://github.com/bouazaoui/helix-toolkit)
[use case when changing model](https://github.com/bouazaoui/helix-toolkit/blob/develop/Source/Examples/WPF.SharpDX/MeshSimplification/MainViewModel.cs)

**Comment by holance** [comment]
Sometimes it's just the GC delayed releasing the memory. How much memory leak have you seen?

**Comment by bouazaoui** [comment]
With a stl file who weighs 80mb, and another file with 61kb, when i reselect the biggest file, memory usage increase and not released.
![memoryleak](https://user-images.githubusercontent.com/17064603/120934857-57173c00-c700-11eb-8a97-c5e949a04278.gif)

**Comment by holance** [comment]
You can try to run with the vs performance profiler -> memory usage. And check where the leak is. There is a "force GC" button.

**Comment by holance** [comment]
Please try with latest nightly build. If you still getting the same result, please upload the stl files you are using for testing, so I can try to reproduce on my end.

**Comment by bouazaoui** [comment]
Sorry in this use case, there isn't a memory leak, it occurs when i have a master-détail, and the detail view has a viewpot for viewing model.
Without master detail : 
![image](https://user-images.githubusercontent.com/17064603/120979317-c713d980-c775-11eb-8099-3982ddaaff57.png)

[Rapport20210607-0939.zip](https://github.com/helix-toolkit/helix-toolkit/files/6606915/Rapport20210607-0939.zip)

**Comment by bouazaoui** [comment]
> Please try with latest nightly build. If you still getting the same result, please upload the stl files you are using for testing, so I can try to reproduce on my end.

I have pushed the huge stl :-)

**Comment by holance** [comment]
Where's the file you pushed?

**Comment by bouazaoui** [comment]
https://github.com/bouazaoui/helix-toolkit/tree/develop/Models/stl/binary/lens.stl

**Comment by holance** [comment]
I tested using FileLoadDemo, and did not see any memory leak. Not sure how the viewport is being used in your code. Are you creating new viewport for each new model loaded? Or reusing the same viewport?

**Comment by bouazaoui** [comment]
In my viewmodel, i added this code to clean objects, it's now better.
![image](https://user-images.githubusercontent.com/17064603/121319933-f90b7400-c90c-11eb-8935-51a4bb3c10c2.png)
