### ISSUE TITLE
Helix-toolkit reunion path?

### ISSUE THREAD

**Issue by GeorgeS2019** [helix-toolkit/helix-toolkit#1598]
Currently Reunion 0.8 is now available with SwapChainPanel included for WinForm/WPF and UWP.

<img src="https://user-images.githubusercontent.com/49812372/124972954-3c9bef80-e02b-11eb-9977-c842bd2c977a.png" alt="Project Reunion" width="800" height="300">

Since Helix toolkit UWP Viewport is based on the [UWP SwapChainPanel.](https://github.com/helix-toolkit/helix-toolkit/issues/1188) I just curious is there interest to feature one or a few Helix-toolkit examples making use of the **Project Reunion 0.8 [SwapChainPanel](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.SwapChainPanel?view=winrt-20348)**.

**Comment by holance** [comment]
I could not find the SwapChainPanel in Reunion project.

**Comment by SnowyWreath** [comment]
Seems like it should be there; they're calling it the "Windows App SDK" now...

https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.swapchainpanel?view=winui-3.0

**Comment by miquik** [comment]
I just finish to convert UWP version to Project Reunion. It barely works, but there is much more work to do expecially in event handling

**Comment by miquik** [comment]
Here's my fork with a working example: [Helix Toolkit - WinUI](https://github.com/miquik/helix-toolkit); it seems to works well

**Comment by holance** [comment]
Is WinUI compatible with UWP? Or their namespaces are the same?

**Comment by miquik** [comment]
> 
> 
> Is WinUI compatible with UWP? Or their namespaces are the same?

I modified UWP project to use with WinUI (I replace UWP namespace with WinUI) for simplicity, so currently I can't merge it with main helix toolkit project. Anyway, with a little work, both versions (UWP and WinUI) can coexist.
WinUI version currently only works in Windows - Desktop (x86 and x64); I *think* this is a limitation of Project Reunion so far

**Comment by holance** [comment]
Helix toolkit can only work on windows anyway, since directx only exists on windows.

**Comment by miquik** [comment]
Yes, you are right. Only Desktop

**Comment by holance** [comment]
Go ahead to create a pull request. :)
