### ISSUE TITLE
Billboards with Rotation property

### ISSUE THREAD

**Issue by objorke** [helix-toolkit/helix-toolkit#16]
**This issue was imported from [CodePlex](http://helixtoolkit.codeplex.com/workitem/9978)**

**[JardarM](http://www.codeplex.com/site/users/view/JardarM)** wrote 2013-02-05 at 12:35
Make the bilboard rotatable. Now billboards can only be vertical. Thus a transform(2d) property might make sense to add.

**Comment by holance** [comment]
Implemented in sharpdx version
