### ISSUE TITLE
View crash when using 3 monitors

### ISSUE THREAD

**Issue by gregorsGit** [helix-toolkit/helix-toolkit#1600]
Hi,

when i use 3 monitors with my notebook I get this crash.

![multipleMonitors](https://user-images.githubusercontent.com/34306200/122348200-31cdcd80-cf4b-11eb-8279-a7c678cb7eb6.png)

The graphic drivers are all up to date. 
System: Win10-64Bit 2019 with intel onboard and nvidia graphics-card.

What can i do to avoid this crash?

**Comment by holance** [comment]
Under what condition did it crashed? Moving the viewport crossing the monitors?

**Comment by gregorsGit** [comment]
It crashes directy when starting. 
One solution for me was to poweroff the 3. monitor.
In some cases it helps to define an other main monitor. (not praticable)
I am using the latest version of helix sharpdx.

**Comment by holance** [comment]
Could you try to force your program to run on the Nvidia graphics card and test if it still crashes?

**Comment by gregorsGit** [comment]
Hi,
sorry for the late response.
When I use NVIDIA SystemConrolPanel and say:
My Application should use NVIDIA Highperformance GPU, than it works.

**Comment by holance** [comment]
https://github.com/helix-toolkit/helix-toolkit/wiki/Tips-on-performance-optimization-(WPF.SharpDX-and-UWP)#2-laptops-with-nvidia-optimus-dual-graphics-cardhelixtoolkitsharpdx-only

Please refer to the link above to use external graphics card for your application.
