### ISSUE TITLE
How get axisPlaneGridModel3D point

### ISSUE THREAD

**Issue by shao200** [helix-toolkit/helix-toolkit#1609]
I want to drag the model to the point of the corresponding Axis PlaneGridModel3D face, and I can't get the point of axis Planegridmodel3d by clicking on the event.

**Comment by shao200** [comment]
Currently, I can only drag the model when I automatically locate it at the center point.

**Comment by holance** [comment]
Currently axisPlaneGridModel3D does not support hit test yet.

**Comment by shao200** [comment]
> Currently axisPlaneGridModel3D does not support hit test yet.

Thanks for your advice. How do I get the space point for that face by clicking?

**Comment by shao200** [comment]
Thank you, I've found a solution. You do not need to add new features
