### ISSUE TITLE
Helix SharpDX is unable to specify Warp driver.

### ISSUE THREAD

**Issue by ikeough** [helix-toolkit/helix-toolkit#161]
There is code in `Effects.cs` to create a device of type `DriverType.Warp` but it doesn't work. That is, if you disable the other logic in that file for finding the best adapter and just specify warp, you get an exception in `DX11ImageSource.SetRenderTargetDX11` stating "incorrect parameter". I assume from the fact that this code exists that it worked for someone, but I can't get it to work. This means that Helix3D doesn't draw anything in situtations where a hardware adapter is not available (remote desktop, Fusion, etc.)

**Comment by ikeough** [comment]
Update 1:
The failure to create a `Texture` in `SetRenderTargetDX11` is due to `colordescNMS` having `ResourceOptionFlags.Shared`. This is not supported by WARP. Unfortunately, if I set that to `None`, the failure goes away but I get a blank texture.

**Comment by JeremyAnsel** [comment]
According to MSDN:
> Starting with Direct3D 11.1 WARP devices support:
> - All Direct3D feature levels from 9.1 through to 11.1
> - Shared surfaces. That is, you can fully share surfaces between WARP devices, as well as between WARP devices in different processes.

> When you run a virtual machine (VM), Hyper-V, with your graphics processing unit (GPU) disabled, or without a display driver, you get a WARP device. This WARP device can run the full Windows experience. This WARP device also supports running legacy apps that use DirectDraw or running apps that use Direct3D 3 through Direct3D 11.1.

I think that surfaces can't be shared between DX11 WARP devices and DX9 devices.
To support WARP devices, a good way would be to replace the `D3DImage` with a `HwndHost` or a `WindowsFormsHwnd`.

**Comment by smischke** [comment]
One of the top features of HelixToolkit.Wpf.SharpDX is the solution of airspace problems when combining WPF and DirectX (even with MSAA). Making Viewport3DX "heavyweight" would kill this feature. It might be useful as an optional fallback though.

**Comment by ikeough** [comment]
@JeremyAnsel If it was true that surface couldn't be shared between these devices, then that would be a nice, simple explanation. But, if I disable my hardware adapter completely (you can do this in Windows 8), I get WARP and Helix runs great! I just can't figure out how to create a WARP device in code so that it works.

**Comment by JeremyAnsel** [comment]
There are two WARP adapters. They are called `"Microsoft Basic Render Driver"`, `VendorId=0x1414` & `DeviceId=0x8C`.

When one creates a D3D11 device with WARP driver type, the runtime chooses the render only WARP adapter, which is the last adapter enumerated by a DXGI factory.
When ones specifies HARDWARE driver type, the runtime choose the default (primary) adapter, which is the first enumerated adapter. When a primary adapter is not present or is disabled, the system replaces it with a `"Microsoft Basic Render Driver"`.

The adapter obtained by specifying WARP driver type and the adapter obtained by specifying HARDWARE driver type on systems without enabled hardware graphic card are not the same. It is confusing that they have the same description, VendorId and DeviceId. They both use the warp rasterizer.

**Comment by ikeough** [comment]
Thanks for the discussion all. I see @JeremyAnsel has added some fixes to `HelixToolkit.Wpf.SharpDX`, and I understand the limitations better now. Closing...
