### ISSUE TITLE
How to switch between rendering types?

### ISSUE THREAD

**Issue by SwaroopSomanna** [helix-toolkit/helix-toolkit#1610]
I'm using HelixToolKit-SharpDX and I want to be able to switch between software rendering and hardware (DirectX) rendering. Is it possible for me to make HelixToolKit-SharpDX to use either of the rendering types at my choice?

**Comment by holance** [comment]
Currently we don't provide function to change to software rendering. Also software rendering only supports by swap chain. If you want to try it out, you can change this [line](https://github.com/helix-toolkit/helix-toolkit/blob/10259e61edc5b3fed79a728f0aed88d32a769b5b/Source/HelixToolkit.SharpDX.Shared/ShaderManager/EffectsManager.cs#L292) to 
```
device = new global::SharpDX.Direct3D11.Device(DriverType.Warp, DeviceCreationFlags.BgraSupport);
```
