### ISSUE TITLE
HitTest and multiple instances identification

### ISSUE THREAD

**Issue by CBenghi** [helix-toolkit/helix-toolkit#1612]
Hello,

thanks for the outstanding library.
I have a question around the identification of models via HitTesting when reusing geometries with `BatchedMeshGeometryConfig` at different transforms. This is due to an attempt to improve performance.

Let's say I have two instances in the view, sharing the same `Geometry3D`, but with different transforms, belonging to the same BatchedMeshGeometryModel3D.

In the HitTest result I get the `Geometry3D` and information about the the point being hit, but I don't know how to discriminate which of the two instances resulted in a hit. 
Is there a solution to get that information?

I've thought of computing the distance from the hit point to the transformed bound sphere, but I see ways in which this might fail for complex shapes close to each other.

I was thinking of adding information in the hit-test results about the transform used for the hit. 
If this makes sense, let me know, and I'll write a PR, otherwise please advise on alternative options.

Thanks,
Claudio

**Comment by holance** [comment]
Currently we don't have the information needed if same geometries is being used with different transforms. You are welcome to submit a PR, or I can also do it.

**Comment by CBenghi** [comment]
Hi @holance,

this is great, it does everything I needed.
Sorry I did not make it in time to submit a PR, I was very busy on some other project, but I hope to be able to contribute to Helix in the future.

Many thanks for your help.
Claudio
