### ISSUE TITLE
Orthographic Camera Flips Look Direction

### ISSUE THREAD

**Issue by SnowyWreath** [helix-toolkit/helix-toolkit#1616]
When using an orthographic camera and with "ZoomAroundMouseDownPoint" = "True", zooming in on an object will eventually cause the camera to flip its look direction.

When you zoom into blank space, the length of the look direction vector decreases towards zero. But when you zoom into an object, the look direction vector length drops more rapidly, eventually crossing zero, at which point the direction flips, and the length (distance from position to target) actually begins increasing (even though the "width" of the camera is still decreasing).

I'm observing this in a UWP app.

Attached is a little test app in which you can witness the behavior. I've added custom camera info text which shows the length of the up and look direction vectors, so you can see what the length does as you zoom.

In this screenshot, the look distance is initially 100, as is the width. Note the view cube, showing Up, Left, and Front.
![image](https://user-images.githubusercontent.com/53192301/126854269-1f6a9ef4-0dd3-42ee-95a4-c454923393f8.png)

In this second screenshot, I've started zooming in on a block. The width and look length have both decreased. The view cube is still showing Up, Left, Front.
![image](https://user-images.githubusercontent.com/53192301/126854299-0cf4206a-c6c4-4e95-bd41-52dd8fe4ebb1.png)

Here I tried to catch it right before it crosses over.
![image](https://user-images.githubusercontent.com/53192301/126854329-5471b688-0639-4ceb-9197-cecb4ee20d41.png)

And this is immediately after crossing over. The camera is now facing the other direction. Note how the view cube shows Down, Right, and Back.
![image](https://user-images.githubusercontent.com/53192301/126854336-2244b6d7-1aa1-4ab2-b5d1-d2a3bd400404.png)

If I continue my zoom, the width has gotten very small, and the Look direction has gotten larger again.
![image](https://user-images.githubusercontent.com/53192301/126854365-0a0290fc-d537-4454-adfb-cc064b86a288.png)

Here is the source code.
[OrthoDemo.zip](https://github.com/helix-toolkit/helix-toolkit/files/6871768/OrthoDemo.zip)

**Comment by holance** [comment]
You are setting camera near plane to a negative value, which is invalid.

**Comment by holance** [comment]
There is a bug in camera zooming, I will fix it.
