### ISSUE TITLE
Viewport3DX - how to colorize a wiremesh by texture ?

### ISSUE THREAD

**Issue by chrkon** [helix-toolkit/helix-toolkit#1617]
Hello @holance, many thanks for adding the walkaround mode for the orthographic camera. 
I just want to contribute more on this awsome project, but instead I have an additional question.

The picture shows a colored model. The colors are defined by texture coordinates. It looks grey because I have activated the wiremesh. The mesh color (grey) dominates because I had zoomed out.

![image](https://user-images.githubusercontent.com/456192/126943649-c7857ab6-d7f7-4a9c-adb5-91b855226b58.png)
Is it possible to use the texture information to color the mesh edges like this ? 

![image](https://user-images.githubusercontent.com/456192/126944217-65d79a32-ed41-45e1-bc28-ac134817572d.png)
(The image was rendered in a different Tool)

Kind regards,
Christof

**Comment by holance** [comment]
Set `MeshGeometryModel3D.FillMode = Wireframe`.
