### ISSUE TITLE
Perhaps memory issue on BillboardImage3D.  How can I handle this correctly?

### ISSUE THREAD

**Issue by chrkon** [helix-toolkit/helix-toolkit#1618]
Hello,
I think have found an issue regarding billboardImage3D. But perhaps I just handle in wrongly. 

In our application we have a Viewport3DX.  Inside the Viewport there are multiple models defined. The models have markers at various positions and at each marker a short text should be shown. This is simmilar to the BillboardDemo project.

Because the font of each Textline could be different, I used the same approach as in the BatchedText part of the Demo. I add all Texts and then I create one BillboardImage3d with the Extension Method `texts.ToBillboardImage3D(EffectsMamager)`. For this it seems to be fine.

Now I have a second requirement. The models are moving. They change their positions indepently from each other. Because of this I have to change the Positions of the marker labels, too. I have done this using the same routine. So every time one model was moved, all Texts are created at the new position and a new BillboardImage3D was created using the `.ToBillboardImage3D` function.  This redraw occures every 20ms. First it seemed to be OK, because everything was working. 

But after some minutes the Application becomes slower. After some invetigations with an memory profiler I found that unmanaged memory consumption is rising. It seems that the `.ToBillBoard3D` extension method takes memory without freeing the previous used memory.

To check/reproduce this I have added a timer to the BillboardDemo, which calls the AddBatched Method every 20 ms. 
```
// Insert this into MainViewModel.cs (Line 149) of Demo project 'SharpDX / Examples / WPF / BillboardDemo'
            var time = new Timer(20);
            time.Elapsed += (sender, args) => AddBatchedText();
            time.Enabled = true;
```
This is the result I get in the memory profiler:
![image](https://user-images.githubusercontent.com/456192/126986731-aff10c0d-62df-439d-8f53-3e6e7ede69fa.png)

Is this an issue in the Helix Toolkit or do I something wrong in the usage? 

I am open to any tips.

Kind regards,
Christof

**Comment by holance** [comment]
Do you need to change text each frame? Or just moving the billboard positions?

You can use this if only positions are changed:
```
                    foreach (var f in BatchedText.ImageInfos)
                    {
                        f.Position = /* new position*/
                    }
                    BatchedText.Invalidate();
```

**Comment by chrkon** [comment]
@holance Thanks for the fast answer. 
Changing just the position works fine. This is the memory profiler result:

![image](https://user-images.githubusercontent.com/456192/127032648-79654d0c-022d-48fd-9efb-b0b270e97a38.png)

I will check if I can implement this into our actual model.

**Comment by chrkon** [comment]
@holance I have checked this and repositioning is not the only issue. Some marker Texts are showing the actual position of the marker. And if the element is moved, the text must be changed. So I have to render it again.  And every new rendering takes additional memory. Is there a way to release the used unmanaged memory?

**Comment by holance** [comment]
I think you need to separate the text info into different types. For those texts need to be changed, use BillboardText3D. Otherwise generating image in real time will always be a huge performance hit. Also I think the memory leak is actually caused by dotnet memory streams and other objects not being released on-time by garbage collection.

**Comment by chrkon** [comment]
Many thanks, for your answer and your time.
I will try to restructure our Text Models.
