### ISSUE TITLE
MeshGeometryModel3D make fixed size

### ISSUE THREAD

**Issue by sjc9999** [helix-toolkit/helix-toolkit#1620]
I have a MeshGeometryModel3D that I would like to keep a constant size regardless of camera zoom.  It still needs to move on zoom but not change size.  It will also pan and rotate with the camera.

Any suggestions?

**Comment by holance** [comment]
You can add the geometry into a `ScreenSpaceGroup3D`. Checkout the customViewCube demo for details.

**Comment by sjc9999** [comment]
ScreenSpacedGroup3D seems to use a different camera.  I want to use the same camera with all its features (pan, rotate, etc) except have the MeshGeometryModel3D be a constant size regardless of the camera zoom.  The MeshGeometryModel3D needs to be part of the scene with all my other objects that do resize.

Previously when using SharpDX I used a unit vector at the specified position and looked at its size in projection view space and then scaled the model so that it would always be the same size in projection view space.

**Comment by holance** [comment]
ScreenSpacedGroup3D has an absolute position mode
