### ISSUE TITLE
how to download helix SharpDX and use projects???

### ISSUE THREAD

**Issue by Zaug49** [helix-toolkit/helix-toolkit#1622]
how to download helix SharpDX and use projects???

**Comment by chrkon** [comment]
Hi @Zaug49,
if you want to use it as component in an own project take a look to this page (and the sub pages which are linked on this page):
[Helix Toolkit WIKI - Getting Started](https://github.com/helix-toolkit/helix-toolkit/wiki/Getting-started-with-WPF-and-SharpDX )

If you want to run the example projects just fork this repository with git and open the visual studio solution files in the "source" folder. Open **HelixToolkit.SharpDX.sln** for the SharpDX examples and **HelixToolkit.Wpf.sln** for the WPF based examples.

Kind regards,
Christof

**Comment by Zaug49** [comment]
well, how do we do Shadow Mapping in helixtoolkit wpf?

**Comment by Zaug49** [comment]
@chrkon

**Comment by Zaug49** [comment]
not sharpdx

**Comment by holance** [comment]
There's no shadow map in wpf version

**Comment by Zaug49** [comment]
:(

**Comment by chrkon** [comment]
@Zaug49 Why do you want to use the WPF version?

**Comment by Zaug49** [comment]
not know :)))) Only download project template and learn using wpf version ; i want change sharpdx ; but can not make

**Comment by chrkon** [comment]
Hi @Zaug49, 
if you just want to get more knowledge about the Helix ToolKit I recommend to start with the examples. Take a look on the solutions I mentioned above. 

- In the WPF solution select the Project "Example Browser" as start project and run it.
- In the SharpDX Solution you have to select one of the different projects as start project before you can run the selected sample.

The WPF part and the SharpDX part have different objectives. They are **not** interchangeable. See the [wiki pages](https://github.com/helix-toolkit/helix-toolkit/wiki) for more information.

Kind regards,
Christof

**Comment by Zaug49** [comment]
thx @chrkon
