### ISSUE TITLE
How to catch a Viewport3DX exception ?

### ISSUE THREAD

**Issue by chrkon** [helix-toolkit/helix-toolkit#1629]
Hello helix community, hello @holance, 
I am using the latest version of HelixToolkit.SharpDX.Core.Wpf. The main window has a setup like a cad aplication (a grid with three Viewport3DX controls). All three viewports are using the same EffectManager instance and each Viewport has it's own SceneNodeGroupModel3D which is rendered by a Element3DPresenter Control. All viewports are renderred with the Setting:
-  EnableSwapChainRendering="False"

because I have some overlay elements. (not visible in the picture)

Sometimes one of the Viewport3DX controls crashes. (I can not publish the real screen, so I made a sketch from it):
![image](https://user-images.githubusercontent.com/456192/130742982-60c71c51-c63b-4c49-8a4e-c3d5a050e65d.png)
This is the message in the top right view:
![image](https://user-images.githubusercontent.com/456192/130743079-9427b6ba-f3e1-4f25-89a6-d7f1f784f2e8.png)

The program itself is not affected. Everything still works. Only one 3D view crashed with this message.  So I think have two options.
1) search and find the error
1) detect this crash and replace the crashed Viewport3DX with a new Instance.

All three views show the same data (common data Model, different ViewModels). But the visual settings are different. So one view could show the Mesh, another could show the Mesh with a transparency effect and the third could show just a wireframe. So even if the code and the data are the same I have a lot of different parameter to check. So I have tried option 1 for some days now. 

I already have an exception handling in the application, which will catch all unhandled exceptions. But this crash is not catched. So I assume this happens deep inside of the HelixToolkit. Perhaps in the ShardDX code?

Now my Question: **How can I detect this state. If I don't find the error I have only option 2. Does anybody know, how I can catch this kind of exception?**

Kind regards, 
Christof

**Comment by holance** [comment]
Which material you are using?
