### ISSUE TITLE
HelixToolkit.Wpf.SharpDX.Core.Components.ConstantBufferComponent.Upload NullReferenceException

### ISSUE THREAD

**Issue by KillaOR** [helix-toolkit/helix-toolkit#1630]
I am sometimes getting below error while rotate
![photo1629883337](https://user-images.githubusercontent.com/57344123/130767668-70ec5704-0586-4d3d-aba7-1eb9e3eec2e0.jpeg)
Any idea about the error?

**Comment by holance** [comment]
Which material you are using?

**Comment by KillaOR** [comment]
I tried loading objects without changing any properties. I also got an error when rotating.

**Comment by holance** [comment]
Are you loading objects during rotating?

**Comment by KillaOR** [comment]
Rotation after loading.
Loading code:
```
public SceneNodeGroupModel3D Some3DObject { get; } = new SceneNodeGroupModel3D();

private void LoadModels()
{
Dispatcher.BeginInvoke(DispatcherPriority.Normal,
                (ThreadStart)delegate ()
                {
                    var importer = new Importer();
                    Some3DObject.AddNode(importer.Load(@"Some3DObject.obj").Root);
                }
            );
}
```

XAML:
```
<HelixToolkit:Viewport3DX>
            <!-- ........ -->
            <HelixToolkit:Element3DPresenter Content="{Binding Some3DObject }" />
</HelixToolkit:Viewport3DX>
```

**Comment by holance** [comment]
I am unable to reproduce this issue. Could you help me to upload a simple sample project to reproduce the issue?

**Comment by KillaOR** [comment]
I too unable to reproduce this issue on my computer. The error appears only on the computer where the program is installed.

**Comment by eriove** [comment]
What I've done in similar cases when I couldn't figure out why something was null was adding very defensive null checks in the top method of the call stack (where the exception is thrown). In my experience the call in the next frame will have all properties/fields non null so this is most likely quite safe to do just do nothing when null values are found.

**Comment by holance** [comment]
Added a lock guard for the constant buffer. Need some help to test whether it fixes the issue.

**Comment by KillaOR** [comment]
> Added a lock guard for the constant buffer. Need some help to test whether it fixes the issue.

After 30 minutes of testing, the error did not appear.
