### ISSUE TITLE
Model Centroid UWP

### ISSUE THREAD

**Issue by JuandreG** [helix-toolkit/helix-toolkit#1631]
Hello again.

Some of the models I use were exported from a bigger model's context and as such inherit the bigger model's centroid. I would like to know if it is possible to calculate a model's center of mass and set the model's centroid to that result using HelixToolkit in UWP and I would go about doing this?

Thanks!

**Comment by holance** [comment]
Not sure what you are trying to do here. Centroid is a single point. Are you trying to move the model centroid to the origin (0,0,0)?
You need to do translation transform.
