### ISSUE TITLE
I used alpha values to make a glass and found a new transparent glass that could look at the previous glass. However, the previous glass could not see the glass behind it.

### ISSUE THREAD

**Issue by shao200** [helix-toolkit/helix-toolkit#1637]
I used alpha values to make a glass and found a new transparent glass that could look at the previous glass. However, the previous glass could not see the glass behind it.

**Comment by holance** [comment]
If you are using helix toolkit wpf, you need to use sorted group to sort the semi transparent object.

If you are using helix toolkit sharpdx version, you can set MeshGeometry3D.IsTransparent =true to use order independent rendering.

**Comment by shao200** [comment]
Thank you very much. Well，
