### ISSUE TITLE
Can I provide more line types in LineBuilder?

### ISSUE THREAD

**Issue by shao200** [helix-toolkit/helix-toolkit#1642]
Can I provide more line types in LineBuilder? Like arc, Bezier curve, etc.?

**Comment by holance** [comment]
You can implement your own algorithm to generate the lines.

**Comment by shao200** [comment]
> You can implement your own algorithm to generate the lines. For a curve, just consist of many small line segments.

Thank you, and I used a static method to create an AddExtrudedSegments method, where both ends are closed with AddPolygon, which would normally be fine, but, using a static method, I reported an error saying that the array exceeded the value. Why is that?
  public static void AddAllExtrude(this MeshBuilder builder, IList<Vector2> points, Vector3 axisx,  Vector3 p0, Vector3 p1)
        {
           
            var vp10 = (p1 - p0);
            vp10.Normalize();
            axisx.Normalize();
            var asiy = Vector3.Cross(axisx, vp10);
            asiy.Normalize();
            builder.AddExtrudedSegments(points, axisx, p0, p1);
            //builder.AddPolygon(points, axisx, asiy, p0);
            //builder.AddPolygon(points, axisx, asiy, p1);
           
        }

**Comment by holance** [comment]
Are you trying to add lines or add geometries? Line uses LineBuilder.

**Comment by shao200** [comment]
add geometries,

**Comment by holance** [comment]
Could you provide the exact parameters passing into your function?
