### ISSUE TITLE
UWP Example

### ISSUE THREAD

**Issue by JuandreG** [helix-toolkit/helix-toolkit#1648]
Hello.

Can you please add some more functionality to the UWP example? Like how to use the TransformManipulator3D control in UWP. The SharpDX example shows how to use it when the HitTestResult.ModelHit is MeshGeometryModel3D but in UWP we work with SceneNode because of the conversion after importing a model using Assimp.

If I convert my SceneNodes into MeshGeometryModel3D items I have multiple models instead of 1 model that I imported. And I cannot see a way to combine these MeshGeometryModel3D items so the best way to manipulate the entire model would probably be to manipulate the SceneNode. Unless there is a way to combine multiple MeshGeometryModel3D items into 1 single MeshGeometryModel3D?

I have progressed very well with my project but I'm stuck now because I can't figure out how to use the TransformManipulator3D in UWP with SceneNodes.

Kind regards.

**Comment by holance** [comment]
You can set `TransformManipulator3D.Target` to `SceneNodeGroupModel3D`, which contains the root scene node imported from Assimp. Then it should be able to manipulate complete scene graph under the `SceneNodeGroupModel3D`.

**Comment by JuandreG** [comment]
That worked perfectly thank you!

Is there a way to manipulate the different SceneNode items in the SceneNodeGroupModel3D separately? I populate the SceneNodeGroupModel3D with multiple SceneNode items that I would like manipulate separately. I change the target of TransformManipulator3D using the Viewport3DX OnMouse3DDown event. In my case the HitTestResult.Modelhit is of type HelixToolkit.UWP.Model.Scene.MeshNode. I can't bind the TransformManipulator3D's target property to the MeshNode that is returned.

**Comment by holance** [comment]
You can copy the manipulator source code and change the target to scene node type, it should be able to manipulate the scene node.

**Comment by JuandreG** [comment]
That worked perfectly, again thank you.

Now my target is type SceneNode and the HitTestResult.ModelHit is SceneNode so assignment does happen successfully. With this I have the option of going up the tree to manipulate the parent instead of the SceneNode that was clicked.

Thank you very much!
