### ISSUE TITLE
UWP Shadow

### ISSUE THREAD

**Issue by JuandreG** [helix-toolkit/helix-toolkit#1649]
Hello again.

I have 2 questions about shadows.

1: Why is the shadows that are casted on the inside of the model displayed on the outside too? How would I go about fixing this?

Inside:
![Inside](https://user-images.githubusercontent.com/54146697/134324341-7011466b-bec1-4370-8195-4a51d428dd0a.JPG)

Outside:
![Outside](https://user-images.githubusercontent.com/54146697/134324383-f247177d-6bee-4677-a17b-f67141966798.JPG)

2: How can I get the shadow to be smooth and not show the stripes that it is showing?

This is how I create the ShadowMap3D:

`var shadow = new ShadowMap3D();
shadow.AutoCoverCompleteScene = true;
shadow.Intensity = 0.3;
shadow.IsSceneDynamic = true;`

Then I add the shadow.SceneNode to a SceneNodeGroupModel3D.

**Comment by holance** [comment]
You probably want to adjust the shadow bias to reduce the stripes.

**Comment by JuandreG** [comment]
I removed the packages from my project and reinstalled them but the shadows are still showing on the back of the objects.

Maybe I'm doing something wrong, did I update the packages correctly? I just uninstalled them then reinstalled them.

I'm also using 2 directional lights, can tis cause issues?

**Comment by holance** [comment]
Is the model single layer or double layer? Could you provide the model for us to do the test?

**Comment by JuandreG** [comment]
I can send you a model yes. Where can I send it to?

**Comment by holance** [comment]
You can upload in this issue or send to my email lunci.app@gmail.com.

**Comment by JuandreG** [comment]
I sent the file via email. Was not able to upload it here.

**Comment by holance** [comment]
I am not able to reproduce the issue with your model. Could you provide your light setup?
One side with shadow.
![image](https://user-images.githubusercontent.com/905577/135151502-56af225e-968b-48fc-befa-0fd176189d6a.png)

Other side without shadow.
![image](https://user-images.githubusercontent.com/905577/135151549-d0bdc9af-8e31-4305-b82c-789fe801ef72.png)

**Comment by JuandreG** [comment]
Here are the lights I add. I add the to SceneNodeGroupModel3D.

`var light1 = new DirectionalLight3D();
                    light1.Direction = new SharpDX.Vector3(-213, -266, -308);
                    light1.Color = Windows.UI.Colors.White;

GroupModel.AddNode(light1.SceneNode);`

`var light2 = new DirectionalLight3D();
                    light2.Direction = new SharpDX.Vector3(213, 266, 308);
                    light2.Color = Windows.UI.Colors.White;

GroupModel.AddNode(light2.SceneNode);`

This is how I open the model before adding it to SceneNodeGroupModel3D.

`using (var assimpContext = new AssimpContext())
                {
                    var group = new SceneNodeGroupModel3D();

                    using (var stream = new MemoryStream())
                    {
                        await stream.WriteAsync(bytes, 0, bytes.Length);
                        stream.Seek(0, SeekOrigin.Begin);

                        var assimpScene = assimpContext.ImportFileFromStream(stream, "glb");

                        using (var importer = new Importer())
                        {
                            importer.ToHelixToolkitScene(assimpScene, out HelixToolkitScene helixScene);

                            if (helixScene != null)
                            {
                                var matrix = new SharpDX.Matrix();
                                matrix = helixScene.Root.ModelMatrix;
                                matrix.ScaleVector = new SharpDX.Vector3(100, 100, 100);

                                helixScene.Root.ModelMatrix = matrix;
                            }

                            foreach (var item in helixScene.Root.Traverse())
                            {
                                if (item is MeshNode m)
                                {
                                    m.IsThrowingShadow = true;
                                    m.IsMSAAEnabled = true;
                                    m.CullMode = SharpDX.Direct3D11.CullMode.Back;

                                    (m.Material as PBRMaterialCore).RenderShadowMap = true;
                                    (m.Material as PBRMaterialCore).MetallicFactor = 0.3f;
                                    (m.Material as PBRMaterialCore).AmbientOcclusionFactor = 2.5f;
                                    (m.Material as PBRMaterialCore).ReflectanceFactor = 0.8f;
                                    (m.Material as PBRMaterialCore).EnableAutoTangent = true;
                                    (m.Material as PBRMaterialCore).RenderIrradianceMap = true;
                                    (m.Material as PBRMaterialCore).RenderNormalMap = false;
                                    (m.Material as PBRMaterialCore).RenderEnvironmentMap = false;
                                    (m.Material as PBRMaterialCore).RenderAmbientOcclusionMap = true;
                                    (m.Material as PBRMaterialCore).RenderAlbedoMap = true;
                                    (m.Material as PBRMaterialCore).RenderRoughnessMetallicMap = true;
                                    (m.Material as PBRMaterialCore).RoughnessFactor = 0.3f;
                                    (m.Material as PBRMaterialCore).ClearCoatRoughness = 0.5f;
                                    (m.Material as PBRMaterialCore).ClearCoatStrength = 2.0f;
                                }
                            }

                            group.AddNode(helixScene.Root);
                        }
                    }

                    return group;
                }`

Thank you for your help.

**Comment by JuandreG** [comment]
This is what the model looks like when I open it:
![1](https://user-images.githubusercontent.com/54146697/135209124-c76c592e-6dc1-4acd-8535-40bbc346bead.JPG)
![2](https://user-images.githubusercontent.com/54146697/135209129-1c1ac452-b97d-410a-8115-a14e1f626497.JPG)

**Comment by holance** [comment]
Which version are you using?

**Comment by JuandreG** [comment]
I'm using v2.18.0. "Date Published: Sunday, September 5, 2021". But after your fix #1652 I did remove all my packages and reinstalled them from nuget.

**Comment by holance** [comment]
You need to install nightly build, the fix is not in 2.18.0

**Comment by JuandreG** [comment]
I installed the nightly build but still the same problem. I installed from https://www.myget.org/F/helix-toolkit v2.19.0-revert-1634-win-0001

**Comment by holance** [comment]
The latest nightly build is 2.19.0-alpha.36

**Comment by JuandreG** [comment]
Works perfectly with that version. Thank you very much.
