### ISSUE TITLE
 .net core reference iusse 

### ISSUE THREAD

**Issue by AMT-Cheif** [helix-toolkit/helix-toolkit#1650]
I'm trying to port a .net framework app to .net core (3.1), so I get the packages from nuget helixtoolkit, helixtoolkit.core.wpf and helixtoolkit.core.sharpdx. But the regefence in xaml, that I copied here: http://docs.helix-toolkit.org/en/lat...t-to-your-xaml is not correct. errors desappear if I reference xmlns:HelixToolkit="http://helix-toolkit.org/wpf", but app not show anything and crash. What am I missing?
here the xaml:
````
<UserControl x:Class="UCGraph3D"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:local="clr-namespace:MyApp"
                xmlns:HelixToolkit="http://helix-toolkit.org/wpf" 
             mc:Ignorable="d" 
              d:DesignHeight="685" d:DesignWidth="1277"   Background="#ff323130">
    <Grid>
        <HelixToolkit:HelixViewport3D Name="myviewport" ZoomExtentsWhenLoaded="True"  Background="Black"  ShowCoordinateSystem="True" >
            <!-- Remember to add light to the scene -->
            <HelixToolkit:SunLight/>
            <ModelVisual3D>
                <ModelVisual3D.Content>
                    <GeometryModel3D x:Name="myGeometryModel3D">

                        <GeometryModel3D.Geometry>
                            <MeshGeometry3D x:Name="myMeshGeometry3D"
                   
                                            TextureCoordinates="0.5 0.8 2 3 ">



                            </MeshGeometry3D>
                        </GeometryModel3D.Geometry >
                        <GeometryModel3D.Material>
                            <MaterialGroup>
                                <DiffuseMaterial>
                                    <DiffuseMaterial.Brush>

                                        <LinearGradientBrush StartPoint="0,0.5" EndPoint="2,2">
                                            <LinearGradientBrush.GradientStops>
                                                <GradientStop Color="green" Offset="0.1" />
                                                <GradientStop Color="yellow" Offset="0.5" />
                                                <GradientStop Color="red" Offset="1" />
                                                <GradientStop Color="Blue" Offset="2" />
                                            </LinearGradientBrush.GradientStops>
                                        </LinearGradientBrush>
                                    </DiffuseMaterial.Brush>
                                </DiffuseMaterial>
                            </MaterialGroup>
                        </GeometryModel3D.Material>
                    </GeometryModel3D>
                </ModelVisual3D.Content>
            </ModelVisual3D>



            <HelixToolkit:GridLinesVisual3D x:Name="mygridX"  Width="10" Length="10" MinorDistance="1" MajorDistance="1" Thickness="0.01" Fill="#FF03F921"  LengthDirection="1,0,0" Normal="0,0,1"/>
            <HelixToolkit:GridLinesVisual3D x:Name="mygridY"  Width="10" Length="10" MinorDistance="1" MajorDistance="1" Thickness="0.01" Fill="#FF03F921" LengthDirection="0,0,1" Normal="1,0,0"/>
            <HelixToolkit:GridLinesVisual3D x:Name="mygridZ"  Width="10" Length="10" MinorDistance="1" MajorDistance="1" Thickness="0.01" Fill="#FF03F921" LengthDirection="1,0,0" Normal="0,1,0" />

            <HelixToolkit:BillboardTextVisual3D Position="11 0 0" Text="X" Foreground="Yellow"/>
            <HelixToolkit:BillboardTextVisual3D Position="0 11 0" Text="Y" Foreground="Yellow" />
            <HelixToolkit:BillboardTextVisual3D Position="0 0 11" Text="Z"  Foreground="Yellow"/>
        </HelixToolkit:HelixViewport3D>
    </Grid>
</UserControl>
```

**Comment by holance** [comment]
Seems like you are using non sharpdx version of helix toolkit, you don't need the helixtoolkit.sharpdx.core package. Only helixtoolkit.core.wpf is needed.

**Comment by AMT-Cheif** [comment]
I removed the all the package and add only the helixtoolkit.sharpdx.core and the intellisense add for me the xmlns:HelixToolkit="http://helix-toolkit.org/wpf" but the app still crash immediatly.

**Comment by holance** [comment]
You need helixtoolkit.core.wpf

**Comment by AMT-Cheif** [comment]
Sorry, i typed wrong the last message.
In my test app I have only helixtoolkit.core.wpf package, but the app still crash.

**Comment by holance** [comment]
Are you able to catch any exception?

**Comment by AMT-Cheif** [comment]
No, I attached vs project to reproduce the iusse.
[MyApp.zip](https://github.com/helix-toolkit/helix-toolkit/files/7224965/MyApp.zip)

**Comment by AMT-Cheif** [comment]
I just found that it must be a driver iusse, because if i run the same project outside of the VMWare VM that I use to develop,
it work fine. It also work on another VM that have not VM Video Driver installed(but the generic from Windows 10). Thanks for your patience and support.

**Comment by AMT-Cheif** [comment]
I have a last question: 
I made a small app that take a binary log (basically an array of byte), and draw a 3d chart with it like the first picture, by calculating the triangles needed to draw it. Because it's a chart, I would like to see the lines between this values, like I sketch with paint in the second picture. Is it possible? Which is the best way to go with? Next step would be implement a sort of manipulation of the chart values, like user select a point and change it. If I correctly understand I need to use the hit test for this, right?
![1](https://user-images.githubusercontent.com/82973069/134682231-e3932397-c42b-44cc-8a65-391756923f2d.png)
![2](https://user-images.githubusercontent.com/82973069/134682242-bd3456a3-0cb3-443c-bfca-aaf5117636f4.png)

**Comment by holance** [comment]
You may want to overlap a line geometry to show the lines on top of your geometry. Or dynamically generate a texture with lines and assign to the geometry.
