### ISSUE TITLE
Can PostEffectMeshBorderHighlight retain the culling effect

### ISSUE THREAD

**Issue by Zhuangkh** [helix-toolkit/helix-toolkit#1651]
When the `DrawMode` of `PostEffectMeshBorderHighlight` is set to `OutlineMode.Separated`, the border of each Element is well calculated and displayed. But it loses the effect of culling elements from each other.

Can the `PostEffectMeshBorderHighlight` retain the culling effect? Like this:

![image](https://user-images.githubusercontent.com/30818313/134662622-ceddb741-06c2-4753-961b-0f40e3952835.png)

**Comment by holance** [comment]
it is not possible for now.

**Comment by Zhuangkh** [comment]
I tried to write a custom effect manager, and applied the custom `DepthStencilStateDescription`:

``` CSharp
public static readonly DepthStencilStateDescription CustomMeshOutline = new DepthStencilStateDescription()
{
    IsDepthEnabled = true,
    IsStencilEnabled = true,
    DepthWriteMask = DepthWriteMask.All,
    DepthComparison = Comparison.Less,
    StencilWriteMask = 0xFF,
    StencilReadMask = 0,
    BackFace = new DepthStencilOperationDescription()
    {
        PassOperation = StencilOperation.Replace,
        Comparison = Comparison.Always,
        DepthFailOperation = StencilOperation.Replace,
        FailOperation = StencilOperation.Keep
    },
    FrontFace = new DepthStencilOperationDescription()
    {
        PassOperation = StencilOperation.Replace,
        Comparison = Comparison.Always,
        DepthFailOperation = StencilOperation.Replace,
        FailOperation = StencilOperation.Keep
    }
};
```
![image](https://user-images.githubusercontent.com/30818313/134781881-a679cd60-f3bc-4734-a0e5-33b4c4594b7b.png)

There are still problems with the depth detection results in some angles, like this:

![image](https://user-images.githubusercontent.com/30818313/134781914-989ee322-8bf9-41e5-be26-a8de43aa2f3e.png)

Do you have any feasible suggestions?

**Comment by holance** [comment]
I don't think it can be solved by changing depth stencil setting.
