### ISSUE TITLE
OIT for models with partially transparent textures

### ISSUE THREAD

**Issue by iBowie** [helix-toolkit/helix-toolkit#1654]
Right now only option is either to set 'IsTransparent' to true, which makes whole model semi-transparent, which does not fit my case, or add models in correct order, which is unfortunately is not fitting for me either as models i use usually do not have such order in mind. Can we have OIT support for models with partially transparent textures? Like, some parts of the texture are not transparent at all, some have transparency but not empty, and some are empty.

Thanks in advance!

**Comment by iBowie** [comment]
Thanks for the suggestion, but i've tried this SortingGroupModel3D with different settings and it didn't give me an expected result, moreover, it broke built-in models which i designed with this issue in mind (adding partially transparent models after non-transparent ones). Imported models also performed not better, but in some cases even worse.

To add to this: my app has no idea if this exact model should be partially transparent or not because model format i import does not have this info, and resorting to IsTransparent does not help me because it would make app pretty much unusable (app's purpose is to allow users to edit and draw on textures directly on 3D model, and making whole model half transparent would be frustrating to use)

**Comment by holance** [comment]
We implemented classic depth peeling for OIT rendering, probably this is what you need. You can mark all models which may have transparency as `IsTransparent = true`. Depth peeling algorithm should handle correctly.
