### ISSUE TITLE
Where is the HelixToolkit.WinUI package?

### ISSUE THREAD

**Issue by yoshiask** [helix-toolkit/helix-toolkit#1680]
Howdy,
I want to try out this library in my app utilizing the Windows App SDK, but it does not appear that the `HelixToolkit.WinUI` library is available on NuGet. I also checked the build artifacts on AppVeyor and didn't see anything there. Are there plans to release compiled versions of this library?
Thanks.

**Comment by holance** [comment]
I will create an nuget build later.

**Comment by holance** [comment]
Added in PR #1682
