### ISSUE TITLE
How to remove the sawtooth of 3D model？？？

### ISSUE THREAD

**Issue by sunxuyang6** [helix-toolkit/helix-toolkit#1684]
When our 3D model is displayed, many jagged edges will appear. No matter how I adjust "nearplanedifference" and "farplanedifference", I can't eliminate these jagged edges.

Is there any configuration or method to solve this problem?
![1](https://user-images.githubusercontent.com/80435731/143826818-bc7e55c8-535d-4f89-b1af-e7d30af9c96f.PNG)

**Comment by holance** [comment]
You need to turn on anti-aliasing, either FXAA or MSAA.

**Comment by sunxuyang6** [comment]
Thank you very much for your advice. I have achieved very ideal results through MSAA!

> You need to turn on anti-aliasing, either FXAA or MSAA. Such as `Viewport3DX.FXAALevel = Medium`.

**Comment by holance** [comment]
MSAA may cause performance issue if the scene contains too many models and uses post effect.

**Comment by SwaroopSomanna** [comment]
> MSAA may cause performance issue if the scene contains too many models and uses post effect.

Any documentation on using MSAA and FSAA?

**Comment by holance** [comment]
There's no documentations. To use them, just set the desired settings on the Viewport3DX.
