### ISSUE TITLE
Can HelixToolkit.Core.WPF be used and deployed on a linux system？

### ISSUE THREAD

**Issue by MagicUrban** [helix-toolkit/helix-toolkit#1688]
Helllo, as HelixToolkit.Core.WPF is based on .NETCoreApp 3.1, I would like to maker sure whether it can be used and deployed on a linux system. Thank you!

**Comment by holance** [comment]
It only supports windows since it's using direct x.

**Comment by MagicUrban** [comment]
Thank you! Can you recommand 3D procedual geometry modeling library in .net core for Linux? Best wishes.

**Comment by holance** [comment]
I am not an expert on meshing, so can't really give you a recommendation for this one.
