### ISSUE TITLE
Show/hide shadowmap

### ISSUE THREAD

**Issue by ju2pom** [helix-toolkit/helix-toolkit#1691]
In my application I'd like to have an option to enable/disable shadow map.
I'm using the WPF integration.
Sadly it does not seem to work.

Changing Viewport3DX.IsShadowMappingEnabled at runtime does nothing.
Removing the ShadowMap3D node from the viewport does not help.
I also tried to call `InvalidateScenegraph` because I saw in the source code that it was cleaning up some stuffs.

It easy to check since it's broken even in the sample `ShadowMapDemo`.

**Comment by holance** [comment]
Work around is to set each materials' `RenderShadowMap` property to false.

**Comment by ju2pom** [comment]
I did another workaround by setting the intensity to 1 on the shadow map to avoid traversing all scene nodes.
By the way, is there a reason why the intensity = 0 is maximum shadow and intensity = 1 is no shadow?

Thanks for the super quick answer and the fix (not tested yet)

**Comment by holance** [comment]
Probably a bug on intensity, will check it out.
