### ISSUE TITLE
MeshBuilder.AddTube FrontCap and BackCap 

### ISSUE THREAD

**Issue by dwpessoa** [helix-toolkit/helix-toolkit#1694]
Hi! Thanks for this great library!...

When using `MeshBuilder.AddTube` to extrude the section below I noticed that the ends of the extrusion don't exactly match. The extrusion is OK, the "problem" is only in the  `FrontCap` and `BackCap`.

This happens with other profiles as well... looks like a plane with edges starting from the origin (which is my lower left corner) to all another points in the section.

Is this a bug or am I using it the wrong way? 

![Sem título](https://user-images.githubusercontent.com/11081462/146586356-3ed1508e-3cce-48ea-a614-972a74038d64.png)

![Screenshot_2](https://user-images.githubusercontent.com/11081462/146586403-1ab147c8-1ce5-4206-8e12-6426c2292233.png)

To replicate the problem (Helixtoolkit.Wpf v2.20.0): 
```
PointCollection section = new PointCollection {
                    new Point(0, 10),
                    new Point(0, 20),
                    new Point(30, 20),
                    new Point(30, 30),
                    new Point(40, 30),
                    new Point(40, 0),
                    new Point(30, 0),
                    new Point(30, 10),
                    new Point(0, 10)                    
                };

MeshBuilder meshBuilder = new MeshBuilder();

var path = new List<Point3D>(); 
var angles = new List<double>(); 
var diameters = new List<double>();
var tubeClosed = false; 
var sectionClosed = true; 
var withCaps = true; 
var sectionX = new Vector3D(0, 0, 1);
Material color = return new DiffuseMaterial((SolidColorBrush)(new BrushConverter().ConvertFrom("#bfff00")));

diameters.Add(2);

path.Add(new Point3D(0, 40, 0));
path.Add(new Point3D(0, 0, 0));

for (int i = 0; i < path.Count; i++)
{
	angles.Add(0);
}

meshBuilder.AddTube(path, angles, null, diameters, section, sectionX, tubeClosed, sectionClosed, withCaps, withCaps);
GeometryModel3D model = new GeometryModel3D(meshBuilder.ToMesh(), color);
myModel3D.Content = model;
```

**Comment by holance** [comment]
It's a bug. We only tested the cap on circle shape tube.

**Comment by dwpessoa** [comment]
Thanks @holance, I followed the recommendation and subdivided my path into some convex shapes.
