### ISSUE TITLE
Find rotation matrix of the surface on STL?

### ISSUE THREAD

**Issue by alperensimsek** [helix-toolkit/helix-toolkit#1695]
Hi!

I use 3D STL files in my project. I need to find the rotation matrix of the surface that I click on the model. Do you have any opinion on this?
I really need help.

Thank you in advance!

ps. using wpf.

**Comment by alperensimsek** [comment]
As an example, I prepared a small demo program. I can get the normal results, but I have no idea how to convert them to angles and get a rotation matrix.

[AskDemo.zip](https://github.com/helix-toolkit/helix-toolkit/files/7744898/AskDemo.zip)

**Comment by holance** [comment]
Not sure what you mean by rotation matrix of surface. The rotation matrix applies to the geometry model as Transform property. You can get the model from the hit result and get the transform matrix from the model.

**Comment by alperensimsek** [comment]
I've tried that. Unfortunately the matrix of the model is identify matrix because i've never transformed the model.  
![Screenshot_1](https://user-images.githubusercontent.com/51800545/146878347-a1437557-beaa-4d77-8fda-66c02c4d16d2.png)

I exactly want to add a new box when i click the surface below my drawing. But i couldn't make it :(

**Comment by holance** [comment]
You probably want to do something like this:

```
        public void Select(Viewport3DHelper.HitResult hit)
        {
            var normal = hit.Normal;
            X = normal.X;
            Y = normal.Y;
            Z = normal.Z;


            var unitX = new Vector3D(1, 0, 0);
            var axis = Vector3D.CrossProduct(unitX, normal);
            axis.Normalize();
            var dot = Vector3D.DotProduct(unitX, normal);
            var angle = Math.Acos(dot) / Math.PI * 180;
            var axisRotation = new AxisAngleRotation3D(axis, angle);
            var rotationMatrix = new RotateTransform3D(axisRotation);
            var translation = new TranslateTransform3D(hit.Position.X, hit.Position.Y, hit.Position.Z);
            var transform = new Transform3DGroup();
            transform.Children.Add(rotationMatrix);
            transform.Children.Add(translation);

            var builder = new MeshBuilder();
            builder.AddBox(new Point3D(2.5, 0, 0), 5, 5, 5);
            var model = new ModelVisual3D
            {
                Content = new GeometryModel3D
                {
                    Geometry = builder.ToMesh(),
                    Material = MaterialHelper.CreateMaterial(Brushes.Red)
                },
                Transform = transform
            };
            Objects.Add(model);
        }
```

**Comment by alperensimsek** [comment]
Yeah! I really need something like that. Thank you so much, you are a lifesaver. 😊

If possible, can you also share the mathematical equation? It helps a lot too.
