### ISSUE TITLE
Helix Toolkit recently added tube objects in WPF application, are not firing events or reacts on mouse interaction?

### ISSUE THREAD

**Issue by zoran55zoki** [helix-toolkit/helix-toolkit#1696]
I am using WPF application with Helix Toolkit, where I dynamically add multiple 3D objects into the Viewport. The Visuals of the objects are added successfully, but some of the recently added objects (in this case tube objects) are not firing events, neither show their appropriate tooltip message. After some interaction with the GUI of the app and adding new additional 3D objects to the Viewport, the old already added objects are firing events and show their tooltip message... Also I have noticed that if I add some other new 3D objects and if I rotate the camera with right button pressed of the mouse, they are coming responsive!

So what Is causing this problem? Is it there some rendering or camera problem or something else?

I am using this code about the Viewport with SortingVisual3D where all of the objects are added behind the transparent surface:
```
<helix:HelixViewport3D Grid.Column="0" Grid.Row="1" Grid.RowSpan="10" Background="GhostWhite"  Name="_viewport"  ShowFrameRate="True"  ShowTriangleCountInfo="True" ShowViewCube="True"  IsHitTestVisible="True" CalculateCursorPosition="True" ShowCoordinateSystem="True" >

<helix:DefaultLights/>

<helix:SortingVisual3D x:Name="sortingVisual1"  Method="BoundingBoxCorners" IsSorting="True"  SortingFrequency="4"  >
                <helix:MeshGeometryVisual3D x:Name="_cubeObjects">
                </helix:MeshGeometryVisual3D>         `       
`
                <helix:MeshGeometryVisual3D x:Name="_tubeObjects">

                </helix:MeshGeometryVisual3D>             

               //Transparent surface

                <helix:MeshGeometryVisual3D x:Name="_transparentSurface"  >

                </helix:MeshGeometryVisual3D>            

            </helix:SortingVisual3D>
        </helix:HelixViewport3D>`



```
This is how I dynamically add the objects:
```
AddObject tubeObject = new AddObject(points3dCollection, "Tube Object", tubeDiameter, 36, objectMaterial);
                                     
                   tubeObject.MouseLeftButtonDown += new MouseButtonEventHandler(tubeObjectClick);
                    tubeObject.IsHitTestVisible = true;              
                    tubeObject.SetName("Tube Object");

 ContainerUIElement3D cui = new ContainerUIElement3D();               
                cui.Children.Add(tubeObject);
                _tubeObjects.Children.Add(cui);
```
This is the class AddObject definition:
```

class AddObject : UIElement3D,INotifyCollectionChanged
    {       

        private readonly Timer _timer;
        private readonly ToolTip _toolTip;

        public AddObject DataContext { get; }
            
      
        public AddObject(Point3DCollection path, string objectName, double diametar_1, int thetaDiv, Material material)
        {
            MeshBuilder builder = new MeshBuilder();       
                           
               
                List<Point3D> list = new List<Point3D>();

                for (int i = 0; i < path.Count; i++)
                {

                    list.Add(path[i]);

                }               

                list = CanonicalSplineHelper.CreateSpline(list, 0.5, null, false, 0.9);
            
                builder.AddTube(list, diametar_1, thetaDiv, false, true, true);          
           
                GeometryModel3D model = new GeometryModel3D(builder.ToMesh(), material);             
                model.SetName(objectName);
                Visual3DModel = model;            
             
                _toolTip = new ToolTip();
              
                _timer = new Timer { AutoReset = false };
                _timer.Elapsed += ShowToolTip;

                DataContext = this;        
          


        }

 public event NotifyCollectionChangedEventHandler CollectionChanged
        {
            add
            {
                ((INotifyCollectionChanged)DataContext).CollectionChanged += value;
            }

            remove
            {
                ((INotifyCollectionChanged)DataContext).CollectionChanged -= value;
            }
        }

        public object ToolTipContent { get { return _toolTip.Content; } set { _toolTip.Content = value; } }    

        private void ShowToolTip(object sender, ElapsedEventArgs e)
        {
            _timer.Stop();
            if (_toolTip != null)
                _toolTip.Dispatcher.Invoke(new Action(() => { _toolTip.IsOpen = true; }));
        }

       protected override void OnMouseEnter(MouseEventArgs e)
        {
            base.OnMouseEnter(e);

            var gm = Visual3DModel as GeometryModel3D;        

            gm.Material = gm.Material == materialtype ? Materials.Yellow : materialtype;

            if (_toolTip != null)
            {
                _toolTip.IsOpen = true;
                _toolTip.Content = gm.GetName().ToString().Trim() + " vein "; }
            //  _timer.Interval = ToolTipService.GetInitialShowDelay(Application.Current.MainWindow);
            _timer.Interval = 50;
            _timer.Start();          

            e.Handled = true;
        }

        protected override void OnMouseLeave(MouseEventArgs e)
        {
            base.OnMouseLeave(e);

            var gm = Visual3DModel as GeometryModel3D;
            gm.Material = gm.Material == materialtype ? Materials.Yellow : materialtype;

            _timer.Stop();
            if (_toolTip != null)
            { _toolTip.IsOpen = false;
                _toolTip.Content = "";            
            }           

            e.Handled = true;

        }

}
```

What should I check at first? Any idea is welcomed ! Please help !

**Comment by holance** [comment]
Probably you can try to call invalidate visual after adding objects.

**Comment by zoran55zoki** [comment]
I have tried to use InvalidateVisual() after adding every single object, but the result is  same. There is not immediate reaction of the framework or noticeable change. 
Using the method  "BoundingSphereSurface" instead of BoundingBoxCorners" for  the sortingvisual3d, makes the reaction almost impossible or very occasional...  I  believe this is somehow related with the sorting..  Any other idea or suggestion  about this problem?

**Comment by holance** [comment]
Have you tried without sorting group?

**Comment by zoran55zoki** [comment]
I have tried to move the MeshGeometryVisual3D _tubeObjects out of the SortingVisual3D, but the result is even worse (there is not firing event for the first or next tubes) and I don't get any immediate response from already added tube object. I have also tried  not to use ContainerUIElement3D while I add objects, but  the result is same.

My project consists of transparent cylinder with some tubes inside that cylinder, where I have to attach/add some objects by user click's on that tubes inside. Also I have to draw/attach some tubes on the  wall of the transparent surface from the cylinder with a shape generated by user clicks on that surface. So, in a that way I have to switch  the transparent  surface property IsHitTestVisible  from true to false and vice versa.
When I will attach tubes at the transparent surface, only the first tube is firing event immediately  (and show's their tooltip message ) but the next tube objects do not respond immediately. They fire events after some interaction with the GUI of the application and I don't now why that is happening exactly in that way. 

The tubes inside and the recently added objects must be visible through the transparent surface, so  it is important to use SortingVisual3D  while the user have an interaction with the  objects inside of the cylinder.

I am trying to solve this problem for more than a month, so any idea is welcomed...

![Tubes transparent surface](https://user-images.githubusercontent.com/96602024/147565025-c7064e15-4e1e-40cf-a7e2-b1dacbca7b0e.jpg)

**Comment by holance** [comment]
Sorting visual is used to sort multiple transparent objects. For non transparent objects, what you need is a group before the transparent ones so they are rendered before transparent objects.

**Comment by zoran55zoki** [comment]
So I have tried  not to use the Sorting Visual or precisely I have moved the object's Xaml code directly into the Viewport:

```
<helix:HelixViewport3D Grid.Column="0" Grid.Row="1" Grid.RowSpan="10" Background="GhostWhite"  Name="_viewport"  ShowFrameRate="True"  ShowTriangleCountInfo="True" ShowViewCube="True"  IsHitTestVisible="True" CalculateCursorPosition="True" ShowCoordinateSystem="True" >

<helix:DefaultLights/>

                <helix:MeshGeometryVisual3D x:Name="_cubeObjects">
                </helix:MeshGeometryVisual3D>         `       
`
                <helix:MeshGeometryVisual3D x:Name="_tubeObjects">

                </helix:MeshGeometryVisual3D>             

               //Transparent surface

                <helix:MeshGeometryVisual3D x:Name="_transparentSurface"  >

                </helix:MeshGeometryVisual3D>         
         
        </helix:HelixViewport3D>`
```
Yes the transparent cylinder is only object and  can also be used in this way, but there is  not a result of  a event's triggering problem. I have also  called InvalidateVisual() but there is not improvement to the firing events or visualization of the object's tooltip OnMouseHover... 
Is it this  problem of InvalidateVisual() function  or some framework's rendering problem?

I think this  proposed implementation is even worse...
Using of the SortingVisual solves somehow this problem but on  a limited cases or in a limited conditions. After the first insertion of a tube object on the wall of a transparent cylinder, the new tube objects are not  hit visible or their tooltip is not shown immediately (or  as I have explained on the previous message after some time of interaction with the application's GUI or with  change of the camera look direction with mouse scroll button or right mouse button pressed). 

So, what is causing this problem? What have to be checked? 

Is it there something what I am doing wrong? Please, let me know !

**Comment by holance** [comment]
Are you able to upload an sample project to demonstrate the issue?

**Comment by holance** [comment]
Inside our [wpf lego demo](https://github.com/helix-toolkit/helix-toolkit/tree/develop/Source/Examples/WPF/ExampleBrowser/Examples/Lego), hit test works as expected. 
Please upload a demo project so we can help investigate the issue.

**Comment by zoran55zoki** [comment]
So, here: [https://github.com/zoran55zoki/SimpleDrawingTubesApp/tree/main/WPFObjectsAppTest](url) is the sample code of the project where you can spot the issue.
https://github.com/zoran55zoki/SimpleDrawingTubesApp/tree/main/WPFObjectsAppTest

This demo project is simplified version from the full project and it took me some time to do the changes, but the issue still remains in this demo version. 

The issue is described on the previous comments. 

I have notice that when I draw multiple tubes on the surface of the transparent cylinder, the responsiveness (  rendering or events firing) is very difficult. Also usually if I draw tube on the back side of the wall of transparent cylinder or shadowed side, the events are not fired or you can't have interaction with the tubes.

The usage of the app is simple and is described into the read me file.
The issue can be easily spotted, if you try to draw one Main Tube and multiple each other connected tubes. Also try to draw multiple Main tubes on front (lighted) and back (shadowed) side of the transparent cylinder.

Please let me know for any idea, how to solve this issue !
![Photo 2](https://user-images.githubusercontent.com/96602024/149051955-4b68ecbd-e8d2-476a-ba46-8a8f8754f5a1.jpg)

**Comment by holance** [comment]
The sample project is missing TransparentCylinder class.

**Comment by zoran55zoki** [comment]
My apologies I didn't notice that, it was an error during the upload  on github ...  
I have uploaded zipped version of the project. Now you can take a look at the full project.

You can also download through google drive here: [https://drive.google.com/drive/folders/1pHUEAOYK0UVa8Y-TR-BAB2nIpxEpPA-X?usp=sharing](url)

**Comment by zoran55zoki** [comment]
Do you have an idea how to solve this issue or what is causing this problem ? I hope you have successfully opened the project !

**Comment by holance** [comment]
Seems like the mouse events are handled by the wpf framework. Probably not a helix toolkit issue. Will do more investigation when I have time.

**Comment by zoran55zoki** [comment]
Yes but only at the beginning. After that the mouse events are not responding immediately. I use the same event handlers all the time. After couple interactions with the application GUI or  changes of the camera view (using zoom in or out) the event handlers are alive again.  But it happens accidently, so the app couldn't work properly. On my opinion, probably there is a whole in notification of the framework with the helix toolkit or something related with that. 
Any alternative to solve this problem is welcomed !

 This is very important for me or I will have to start searching for alternatives...

**Comment by ehtick** [comment]
The demo draws a cylinder with caps, when clicking on the screen the cylinder is always clicked on first. The tube are inside the cylinder so if you want to do something like this you should use an other method.

When you want to click through the objects on the screen use the ResultCallback function you already created. In this all the objects that are in the ray are hit. if you click on the tube then you will hit cylinder, tube,.... cylinder.

in this function you can pass this when other functions are active, such as adding the points to draw a new tube.

so what i did is

            _viewport.MouseLeftButtonDown += _viewport_MouseLeftButtonDown;


        private void _viewport_MouseLeftButtonDown(object sender, MouseButtonEventArgs e)
        {
            MouseHitTest(sender, e);
        }


        public void MouseHitTest(object sender, MouseButtonEventArgs args)
        {
            Point mousePos = args.GetPosition(_viewport);
            PointHitTestParameters hitParams = new PointHitTestParameters(mousePos);
            VisualTreeHelper.HitTest(_viewport, null, ResultCallback, hitParams);
        }

in tube 

        public void ShowTooltip()
        {
            var gm = Visual3DModel as GeometryModel3D;

            gm.Material = gm.Material == materialtype ? Materials.Yellow : materialtype;

            if (_toolTip != null)
            {
                _toolTip.IsOpen = true;
                _toolTip.Content = gm.GetName().ToString().Trim() + " tube";
            }

            _timer.Interval = 1000; // 50 is very short is in millisecs !
            _timer.Start();

        }

// should be false because it closes it.
        private void ShowToolTip(object sender, ElapsedEventArgs e)
        {
            _timer.Stop();
            if (_toolTip != null)
                _toolTip.Dispatcher.Invoke(new Action(() => { _toolTip.IsOpen = false; }));
        }


Maybe this helps a bit, i am sure that the problem is not in Helix :)

**Comment by zoran55zoki** [comment]
Thank you Edyy for your suggestions, but the problem/bug isn't  clicking through the objects... Clicking on the objects works only on the limited number  of insertion of tubes, or  more precisely when I draw/insert multiple connected tubes on the surface of the cylinder. In that way, the recently  inserted  tubes doesn't respond immediately on mouse events (mouse hover or mouse clicks). The mouse events are not firing their event handlers.  If you hover your mouse arrow over  the recently inserted tubes, the tube doesn't change the color in yellow. It happens randomly after some interaction with the GUI, change of the camera view (zoom in/out) or after insertion of the new tubes on different positions. 

I want  immediately to continue with insertion  of new connected tubes on the recently inserted  tubes. Just like on the previous image ( at first is drawn  the main blue tube, after that on the blue tube is connected the red tube, on the  red tube is connected the yellow tube etc. )

Any idea is welcomed  !

**Comment by zoran55zoki** [comment]
Here on this [Link](https://drive.google.com/file/d/14blnR-Z1COHn3aF9C0AQ5jl2117TSf8e/view?usp=sharing) you can  see the video of  connected tubes insertion and visually spot the problem/bug. I hope the video quality is enough to describe the app problem.

**Comment by holance** [comment]
Change `MeshGeometryVisual3D` to `ContainerUIElement3D` for grouping fixed the issue.
