### ISSUE TITLE
Different texture scale between Helix-toolkit & other Gltf viewer

### ISSUE THREAD

**Issue by minogram** [helix-toolkit/helix-toolkit#1697]
I really love Helix-toolkit and want to display my glTF using Helix WPF + SharpDX.
I think, helix-toolkit is different with other glTF viewer to show tile texture.
Is there any way to import this correctly? 

I attached my gltf file.
[000001.gltf.zip](https://github.com/helix-toolkit/helix-toolkit/files/7792647/000001.gltf.zip)

Screenshot using Helix-toolkit (Assimp import with default configuration)
![Snipaste_2021-12-30_19-54-21](https://user-images.githubusercontent.com/296403/147746574-c31ae698-7bf2-47bf-80af-22ed17025b66.png)

Texture Zoom-in same gray area is
![Snipaste_2021-12-30_19-56-17](https://user-images.githubusercontent.com/296403/147746706-e7a12809-edeb-4f5c-9aae-5b310fdbc3db.png)

But, Windows 11 3D model viewer shows
![Snipaste_2021-12-30_19-52-59](https://user-images.githubusercontent.com/296403/147746761-c10aa904-6ab2-4d41-9cee-cd6e84bd0a5b.png)

glTF webviewer (gltf-viewer.donmccurdy.com) shows
![Snipaste_2021-12-30_20-06-29](https://user-images.githubusercontent.com/296403/147746805-873e6a7b-f7b1-4b37-8dd2-fa28691ac94e.png)

**Comment by holance** [comment]
Probably you can try to change the sampler property on material to use wrapping mode
