### ISSUE TITLE
Render order

### ISSUE THREAD

**Issue by sjc9999** [helix-toolkit/helix-toolkit#1698]
I am using the WPF SharpDX version
I have two issues:
1. Boxes don't look right when rotated
2. RenderOrder has no effect

I have three boxes I created with MeshBuilder they have different widths and heights but the same depth.  All three boxes are located at the same point.  With no rotation they look fine but when I rotate the camera they don't.
I have tried using the MeshGeometryModel3D RenderOrder but this has no effect.  I would expect that if the biggest box has the highest RenderOrder I would not see the smaller two boxes.

![NonRotated](https://user-images.githubusercontent.com/23642863/149154813-ee7ac3f6-76fc-4d7b-bd7d-eb9e076400e3.png)
![Rotated](https://user-images.githubusercontent.com/23642863/149154866-e295b096-abc8-4b9d-a650-0f83b1c30821.png)
.

**Comment by holance** [comment]
Usually you want to avoid having overlapping surface, otherwise it is causing z fighting due to floating point error. You can try to adjust depth bias on Mesh geometry model 3d to try to reduce z fighting.

**Comment by sjc9999** [comment]
depth bias fixed it thanks
