### ISSUE TITLE
Visual3D with DepthOffset feature

### ISSUE THREAD

**Issue by AnakinCN** [helix-toolkit/helix-toolkit#1705]
Hi,

I need a feature, don't know whether this requirement is strong enough for you to add this feature:

Is it possible to add DepthOffset attributes to common Visual3D? Since sometimes you need a Visual3D to be in the front and always seen.

Thank you. No problem if it is denied.

**Comment by holance** [comment]
We are not able to support it in helix toolkit wpf since the rendering is still using wpf rendering engine.

You can switch to use helix toolkit sharpdx version.
