### ISSUE TITLE
NPE On net6.0-windows

### ISSUE THREAD

**Issue by Warpten** [helix-toolkit/helix-toolkit#1707]
**Version**: 2.20.1
**Package**: HelixToolkit.Wpf.SharpDX
**Issue**: NPE thrown when clicking the viewport on net6.0-windows.

![](https://i.imgur.com/PHT1ro6.png)

From little I can see, `OnAttach` is not called. Not sure what I can do to help identify the issue. Let me know if you need any more specific information, happy to help.

**Reproduce Steps**:

1. Build & Run https://github.com/Warpten/helix-toolkit-issue
2. Click the viewport anywhere.

Cheers

**Comment by holance** [comment]
You didn't set the Effects manager on Viewport3DX

**Comment by Warpten** [comment]
Oh, I did not realize that was required. Would be nice to have some validation of the viewport state somehow, that indeed fixed it. Thanks!
