### ISSUE TITLE
Mouse event order (manipulation vs camera rotation).

### ISSUE THREAD

**Issue by CBenghi** [helix-toolkit/helix-toolkit#1712]
Hello team,

As always kudos on the brilliant work.

I've got a question on mouse events for WPF on SharpDX.

I'm trying to create an editing interface that allows the movement of a manipulator on left mouse click, but also model rotation with the same button.

The CrossSectionDemo is a good starting point for this, if you just change the gesture of rotation from left to right click.
https://github.com/helix-toolkit/helix-toolkit/blob/c8fc0d99445330a9e449bc5ae5ad8f6b945ef7bb/Source/Examples/WPF.SharpDX/CrossSectionDemo/MainWindow.xaml#L46

``` cs
<MouseBinding Command="hx:ViewportCommands.Rotate" Gesture="LeftClick" /> 
```

What happens is that as the planes are manipulated, the view is also rotated.
Debugging the code it feels like the rotation of the view happens before the rotation of the plane, so changing the `Handled` property is not enough to prevent the camera rotation.

Is there a right way to configure the viewer so that the camera rotation only happens if I'm not manipulating the cutting plane?

Thanks,
Claudio

**Comment by CBenghi** [comment]
**Update:**

I think that it's possible to stop the processing of further events by changing `OriginalInputEventArgs.Handled` that you get casting `e` to `Mouse3DEventArgs`. But I'll have to confirm tomorrow.

Thanks,
Claudio

**Comment by holance** [comment]
Adds an event in the manipulator like this:
```
public event EventHandler<BoolArgs> OnManipulating;
```
Trigger this event in `OnXXXMouse3DDown` like this:
```
 OnManipulating?.Invoke(this, BoolArgs.TrueArgs);
```
Trigger this event in `OnXXXMouse3DUp` in manipulator code like this:
```
OnManipulating?.Invoke(this, BoolArgs.FalseArgs);
```

Externally, handles this event to enable/disable rotation for Viewport3DX:
```
        private void Manipulator_OnManipulating(object sender, HelixToolkit.Wpf.SharpDX.BoolArgs e)
        {
            viewport3DX.IsRotationEnabled = !e.Value;
        }
```

**Comment by CBenghi** [comment]
thanks @holance,

concurrently to your response I was editing my update above.
I've got is sorted by setting the `Handled` property of the `OriginalInputEventArgs` instance.

What do you think of changing the `Handled` propery as suggested above?

**Comment by holance** [comment]
You can try that as well.

**Comment by CBenghi** [comment]
Hello @holance,

I've put a PR #1715, that changes the `Handled` property as proposed above.
I'm not 100% sure of its quality, though, what do you think?
Happy to amend the PR following any suggestions you might have.

Thanks,
Claudio
