### ISSUE TITLE
Doubleside material

### ISSUE THREAD

**Issue by goldv72** [helix-toolkit/helix-toolkit#1716]
Hello!
please show how to create PhongMaterialCore from RGBA and make it double sided

PhongMaterialCore material = new PhongMaterialCore()
            {
                Name = color.Name,
                DiffuseColor = new SharpDX.Color4(color.Red, color.Green, color.Blue, color.Alpha),
            };

**Comment by holance** [comment]
Use two mesh geometry model 3d, set same geometry to both of them. Then set first one cull mode to back, second one cull mode to front and invert normal to true.

**Comment by goldv72** [comment]
Thanks, its works
