### ISSUE TITLE
very big cooordinates

### ISSUE THREAD

**Issue by goldv72** [helix-toolkit/helix-toolkit#1718]
Hi!
sometimes I work with very large coordinates.
I reproduced the situation in FileLoadDemo with this code snippet (it works with any file)

                if (result.IsCompleted)
                {
                    scene = result.Result;
                    
                    SharpDX.Matrix rootMatrix = scene.Root.ModelMatrix; 
                    rootMatrix.M41 = 500000;
                    rootMatrix.M42 = 100000;
                    scene.Root.ModelMatrix = rootMatrix;

image degrades!!! what do you advise?

PS: please insert row 
loader.Configuration.ImportMaterialType = MaterialType.BlinnPhong;

**Comment by goldv72** [comment]
upd:
500000 still good but 1e+6 is already bad

**Comment by holance** [comment]
You need to scale your scene to be smaller. Otherwise you are getting floating point errors.

**Comment by eriove** [comment]
There is a discussion in [this issue](https://github.com/dotnet/runtime/issues/24168#issuecomment-1025902200) regarding large coordinates in 3d with floating point numbers which might be useful.

**Comment by goldv72** [comment]
Thanks a lot.
I load CAD-models in IFC-format, some made in WCS 
it has very large coordinates, for example (2360000000.0,317000000.0,0.) mm.
but bounds are not enormous (100,200,50 may be)
I divide it to 1000, translate to MinCorner and recalculate all points to absolute coordinates. i.e. all ModelMatrix equal {I} after that
