### ISSUE TITLE
ScreenSpacedGroup3D sharing depth with other meshes.

### ISSUE THREAD

**Issue by CBenghi** [helix-toolkit/helix-toolkit#1723]
Hello,

I've got a question on `ScreenSpacedGroup3D`.

I'm using it with `Mode = ScreenSpacedMode.AbsolutePosition3D` to display an interaction object with constant size with respect to the screen.
This works, and displays the geometry on top of the rest of the model.

Is there a way for the geometry to share the same z-buffer than the model? 
I would want it to be hidden if it goes behind another mesh.

Thanks,
Claudio

**Comment by holance** [comment]
It can't be shared since the meshes are being rendered using a completely different camera. Sharing z buffer will cause incorrect rendering.

**Comment by CBenghi** [comment]
Thanks @holance,
is there another approach to scale independent elements in the toolkit?
Thanks,
Claudio

**Comment by holance** [comment]
You can always do scale transform on the model, you just need to figure out the math on changing the scale transform corresponding to the camera changes.
