### ISSUE TITLE
Bind camera to Element3D

### ISSUE THREAD

**Issue by loegelmarc** [helix-toolkit/helix-toolkit#1725]
Hello,

I have a question. Is there already a way to bind the viewport camera to the transformation of an Element3D (GroupModel3D or MeshGeometryModel3D)?

I have a deeply nested model structure and would like to have the camera follow an object with an offset. Since transformations of the object's parents are animated I would need to react to changes in the absolute transformation of my object to adjust the camera.

Is there an easy way to do this?

Thanks in advance
Marc

**Comment by holance** [comment]
Not for now, you probably have to calculate the camera movement yourself when transform changes.
