### ISSUE TITLE
Manipulate SceneNodeGroupModel3D Successfully and but Export Incorrectly

### ISSUE THREAD

**Issue by Yu-Ru** [helix-toolkit/helix-toolkit#1732]
Hi there! I am stuck at this problem for a week and really eager for some help. 

My purpose is 1) to generate multiple MeshGeometryModel3D models and manipulate them by using UITranslateManipulator3D/UIRotateManipulator3D. After manipulation, 2) I need to export the translated/rotated models to a .dae file. 

For the first part, I can successfully generated the models and play around with the manipulators. Below is the code I have implemented. As an example, a new sphere model will be created at origin whenever a button is clicked calling the method AddSphere(). After, six manipulators are then created and bound to the sphere model. All the models are added to a SceneNodeGroupModel3D, GroupModel, to be displayed in the viewport (`<hx:Element3DPresenter Content="{Binding GroupModel}"/>` in XAML). Up to now, the models can be successfully generated and manipulated. The transformation of each model can also be verified with `GroupModel.GroupNode.Items[index].ModelMatrix`.

		private void AddSphere(object parameter)
        {
            MeshBuilder mbuilder = new MeshBuilder();
            mbuilder.AddSphere(new SharpDX.Vector3(0, 0, 0), 5);  
            MeshGeometryModel3D Model = new MeshGeometryModel3D()
            {
                Geometry = mbuilder.ToMeshGeometry3D(),
                Material = new PhongMaterial() { DiffuseColor = new SharpDX.Color4(1f, 0, 0, 0.2f) }
            };

            UITranslateManipulator3D TransX = new UITranslateManipulator3D() { ... }; // the trivials are neglected
            UITranslateManipulator3D TransY = new UITranslateManipulator3D() { ... };
            UITranslateManipulator3D TransZ = new UITranslateManipulator3D() { ... };
            TransX.Bind(Model);
            TransY.Bind(Model);
            TransZ.Bind(Model);

            UIRotateManipulator3D RotX = new UIRotateManipulator3D() { ... };
            UIRotateManipulator3D RotY = new UIRotateManipulator3D() { ... };
            UIRotateManipulator3D RotZ = new UIRotateManipulator3D() { ... };
            RotX.Bind(Model);
            RotY.Bind(Model);
            RotZ.Bind(Model);

            // GroupModel is an instance of class SceneNodeGroupModel3D
            GroupModel.AddNode(Model.SceneNode);
            GroupModel.AddNode(TransX.SceneNode);
            GroupModel.AddNode(TransY.SceneNode);
            GroupModel.AddNode(TransZ.SceneNode);
            GroupModel.AddNode(RotX.SceneNode);
            GroupModel.AddNode(RotY.SceneNode);
            GroupModel.AddNode(RotZ.SceneNode);
        }

However, all the transformed models cannot be exported correctly. They all return to origin. I am using HelixToolkitScene to contain the GroupNode. Below is the code for export. 

        private void Export(object parameter)
        {
            // Add "GroupModel" to scene:            
            scene = new HelixToolkitScene(GroupModel.GroupNode);
            ...
            HelixToolkit.SharpDX.Core.Assimp.Exporter exporter = new HelixToolkit.SharpDX.Core.Assimp.Exporter(); 
            exporter.ExportToFile(path, scene, id);
            ...
        }
        
I realize that when instancing HelixToolkitScene with the GroupNode, all the SceneNodes can be added to `scene.Root`. Nevertheless, the transforms of each model are NOT. When I print out `scene.Root.ModelMatrix`, it shows "identity," which I suspect the reason why all the models are sent back to origin. If I set the ModelMatrix to some other values, e.g., `scene.Root.ModelMatrix = GroupModel.GroupNode.Items[0].ModelMatrix`, all the exported models are transformed according to the given Matrix. But what I need is different spheres should be in different positions, as transformed by its own manipulators.

I am not sure if there is any step missing. Or am I even in the right track to fulfill this function? Any help or suggestion will be very much appreciated. 

Manipulation of models in WPF
![image](https://user-images.githubusercontent.com/25654595/158846999-41a2cec9-92a4-4d3f-8764-a7ea43d1a278.png)

All the exported models, including manipulators, are located at origin. There are 21 (3*7) nodes in the scene.
![image](https://user-images.githubusercontent.com/25654595/158847388-322e560d-f34e-424c-80f1-5efdbbfa7308.png)

**Comment by Yu-Ru** [comment]
Hi holance,

Many thanks for the suggestion. I just tried your method but failed. 

Do you mean I need to create three GroupModels, suppose I have three Spheres, and use their own manipulators to transform; in the end, I shall somehow combine all the individual GroupModel to scene.Root? If so, would you please guide me how I can put all the GroupModels into one scene and export them? Because when instancing a HelixToolkitScene, a SceneNode or a GroupNode entity must be there as an input argument. I have tried creating a new GroupNode to add the three GroupModel.GroupNode child nodes. Unfortunately, the exported file still receive no success. 

P.S. If I export one model at a time, yes the model will be transformed correctly. But this only happens when there is only one model in the scene. In my example, I still struggle exporting multiple models in one scene with correct transforms.

**Comment by Yu-Ru** [comment]
Hi Lunci,

Thanks for the reply. I am exporting the 3D model to a Collada format. Yes, after some trials I notice that the scene.Root.ModelMatrix will apply to all the group nodes. The individual model matrix which is given by the manipulators will be neglected. This is exactly where I am stuck.

取得 iOS 版 Outlook<https://aka.ms/o0ukef>
________________________________
寄件者: Lunci ***@***.***>
寄件日期: Tuesday, March 22, 2022 3:13:55 AM
收件者: helix-toolkit/helix-toolkit ***@***.***>
副本: Yu-Ru ***@***.***>; Author ***@***.***>
主旨: Re: [helix-toolkit/helix-toolkit] Manipulate SceneNodeGroupModel3D Successfully and but Export Incorrectly (Issue #1732)


Which format you are exporting to? Some formats are really old and does not support transform.
Also scene.Root.ModelMatrix is the GroupNode. You are transforming individual model matrix, it does not affect the GroupNode.

**Comment by holance** [comment]
Are you able to share your project?

**Comment by Yu-Ru** [comment]
Yes. The file is attached as below.

[SimpleSharpDXWPFCore-main.zip](https://github.com/helix-toolkit/helix-toolkit/files/8321715/SimpleSharpDXWPFCore-main.zip)

**Comment by holance** [comment]
[SimpleSharpDXWPFCore-main.zip](https://github.com/helix-toolkit/helix-toolkit/files/8330147/SimpleSharpDXWPFCore-main.zip)
There are some limitations in current release and unable to bind to the group model. I just copied the source code and change the binding type to allow manipulator to bind to a `GroupModel3D`. 

This change should work.

**Comment by Yu-Ru** [comment]
It works!!! Thank you so much, @holance. Just wondering, will the modification be merged in the future release?

**Comment by holance** [comment]
Already merged
