### ISSUE TITLE
MeshBuilder & MeshNode with CullMode problems

### ISSUE THREAD

**Issue by Wannak** [helix-toolkit/helix-toolkit#1733]
Hi,

I am having issue when I am trying to render some models. I have alot of models to render (more than 1000) inside a complexe GroupModel structure (Ex. Root -> Human -> Organs -> xxx, xxx, Kidney, xxx, etc.). The problems come where every model has is triangles mesh and some models are completly inverted (see image for reference).

![image](https://user-images.githubusercontent.com/15036215/159496944-d77fefe7-0f8d-498c-93b1-c95a7cf735ef.png)

How i draw the triangles and put them into a mesh node:

![image](https://user-images.githubusercontent.com/15036215/159500384-08e52597-b709-4aaf-984f-f3af3b8251f6.png)

As you can see, I put CullMode to None to be able to draw both side but I always have one that is black (The back one).

What am I doing wrong?

Specs:
1. HelixToolkit SharpDx

Thanks,

Gab

**Comment by holance** [comment]
Try to check whether those black models' triangle winding order are counter clockwise and their normal values are facing outward.

**Comment by Wannak** [comment]
Have you already done something similar?

**Comment by holance** [comment]
Usually you want to make sure the winding order is correct from your model source. Normal values can be calculated later.

**Comment by Wannak** [comment]
Thanks alot for you help.

I Figured something for it to work with the double MeshNode grouped in a GroupNode to make it work.
I tried it previously but I miss placed some variables.

Here the result:
![image](https://user-images.githubusercontent.com/15036215/159544171-86822f8d-3319-41ca-8b85-450039bfdd56.png)

Here the code for others:
![image](https://user-images.githubusercontent.com/15036215/159544846-260fc016-0d92-4e42-882e-f3d90d940fcf.png)
![image](https://user-images.githubusercontent.com/15036215/159544992-0e75a810-e538-4f09-aab2-07708bf285da.png)
