### ISSUE TITLE
CoordinateSystemLabel issue

### ISSUE THREAD

**Issue by AnakinCN** [helix-toolkit/helix-toolkit#1736]
In SharpDX.WPF, the CoordinateSystem label can't show Chinese language. And also longer label beyond the CoordinateSystem area  would be cropped, which can't be adjusted.

**Comment by holance** [comment]
You can create your own coordinate system with Chinese characters. You need to use the billboard examples in Billboard demo and combine with ScreenSpacedGroup to create your own one.

**Comment by holance** [comment]
Updated the demo to include custom coordinate system:
https://github.com/helix-toolkit/helix-toolkit/blob/develop/Source/Examples/WPF.SharpDX/BillboardDemo/MainViewModel.cs#L154
