### ISSUE TITLE
weird obj file rendering

### ISSUE THREAD

**Issue by seishinkouki** [helix-toolkit/helix-toolkit#1737]
i got a situation that it seems the more triangles, the darker the shadow, did i miss something?

thanks for any clue!
image in wpf
![Snipaste_2022-03-26_17-16-50](https://user-images.githubusercontent.com/8842321/160233417-5cb09d14-2c7a-4c8b-923b-ec196124cd75.png)

image in windows 3Dviewer (normal):
![Snipaste_2022-03-26_17-19-55](https://user-images.githubusercontent.com/8842321/160233443-d8153f2e-2da5-44a2-8f8b-74534879b859.png)

image in windows 3Dviewer (with mesh displayed)
![Snipaste_2022-03-26_17-19-42](https://user-images.githubusercontent.com/8842321/160233475-7ba04ccf-1b85-44b8-8fee-bab318d1eba8.png)

xaml:
```
<HelixToolkit:HelixViewport3D ZoomExtentsWhenLoaded="True" Grid.Row="1" IsHeadLightEnabled="False">
                    <HelixToolkit:DefaultLights/>
                    <ModelVisual3D Content="{Binding MyModelGroup}">
                    </ModelVisual3D>
                    <HelixToolkit:GridLinesVisual3D Width="8" Length="8" MinorDistance="1" MajorDistance="1" Thickness="0.01"/>
</HelixToolkit:HelixViewport3D>
```

**Comment by holance** [comment]
Probably the normal values from the model are not correct.

**Comment by seishinkouki** [comment]
> Probably the normal values from the model are not correct.

thanks for your replay
well, in fact there is no normal values in obj file and the normal index in face is also empty, is this the cause?

**Comment by holance** [comment]
You can try to call 'MeshGeometry3D.CalculateNormals' after import the obj and check if it improves the rendering.

**Comment by seishinkouki** [comment]
i tried blew, but unfortunately it seems doesn't work
```
ObjReader CurrentHelixObjReader = new();
var mmg = CurrentHelixObjReader.Read(@".\some.obj");
MyModelGroup = new Model3DGroup();
foreach (var obj in mmg.Children)
{
    var GM = (GeometryModel3D)obj;
    var MESH = (MeshGeometry3D)GM.Geometry;
    MESH.Normals = MESH.CalculateNormals();
    var _model = new GeometryModel3D
    {
        Geometry = MESH,
        Material = GM.Material,
        BackMaterial = GM.Material,
    };
    MyModelGroup.Children.Add(_model);
}
```

**Comment by holance** [comment]
Could you provide the mesh data?

**Comment by seishinkouki** [comment]
[temp.zip](https://github.com/helix-toolkit/helix-toolkit/files/8357571/temp.zip)

**Comment by holance** [comment]
It's definitely normal value issues. Windows 3D viewer does not use normal value for rendering.
You either switch to helixtoolkit sharpdx version and enable `FlatShading` mode in material or have to fix the normals from the model.

**Comment by seishinkouki** [comment]
thanks a lot, i'll try sharpdx version.
