### ISSUE TITLE
Rendering semi transparent objecs: disappear on zoom

### ISSUE THREAD

**Issue by DeshpandeJanhavi** [helix-toolkit/helix-toolkit#1738]
I am using SortingVisual3D with sorting method "BoundingBoxCorners" and sorting frequency 2 for rendering overlapping semi transparent objects. On zooming in, the outer objects (near to camera) are visible but the inner objects (far from camera) disappear. Following are the snapshots of original and zoomed rendered objects. 
![originalsize](https://user-images.githubusercontent.com/48976280/161507254-cda17371-05fc-4fdb-ab00-f2548ab82623.png)
![zoomed](https://user-images.githubusercontent.com/48976280/161507288-3ab9a699-e6da-4fe8-b8c2-5369c7728bdb.png)
The inner objects are visible again after zooming in further inside the outer objects. How to make inner objects visible even after zooming?

**Comment by holance** [comment]
Instead of using sorting visual, try to put inner objects in front of outer objects manually in visual tree.

**Comment by DeshpandeJanhavi** [comment]
@holance Do the objects have to be sorted based on distance of their surface from camera? And the nearest object has to be placed last in the visual tree?

**Comment by holance** [comment]
For transparent objects, yes.

**Comment by DeshpandeJanhavi** [comment]
Thank you @holance,  adding inner objects before outer objects in visual tree solve the problem of disappearance on zooming.

**Comment by holance** [comment]
You can try to use the order independent rendering in Helixtoolkit SharpDX version. Otherwise, you have to do sorting if multiple semi-transparent objects are intersecting with each other.

**Comment by DeshpandeJanhavi** [comment]
Thank you! sorting objects worked!!
