### ISSUE TITLE
HelixViewport3d Ctrl + C

### ISSUE THREAD

**Issue by FolmerBrem** [helix-toolkit/helix-toolkit#1740]
I am using HelixToolkit.Wpf in a WPF / .Net Framework 4.7.2 application. I am trying to make a copy-paste functionality. To achive it, I have the following code in my xaml file:

```
<KeyBinding Key="C" Modifiers="Control" Command="{Binding CopyCommand}" />
<KeyBinding Key="V" Modifiers="Control" Command="{Binding PasteCommand}" />
``` 

The `PasteCommand` is called as expected, but the `CopyCommand` is not.

When profiling the app, I can see that large MemoryStreams are created when I type Ctrl+C on the keyboard and I can see that the CPU is spending a lot of time in `HelixToolkit.Wpf.HelixViewport3D.Copy()`. I think it is copying the screen view as a bitmap or something like that.

It looks to me like the "Ctrl+C" is already pre-assigned behind the scenes, but I cannot find any documentation about it.

***How would you overwrite this key binding to call my own copy code?***

**Comment by holance** [comment]
Try this: `viewport.CommandBindings.RemoveAt(0);`

**Comment by FolmerBrem** [comment]
Thanks. That worked
