### ISSUE TITLE
HelixToolkit.Wpf, TubeVisual3D, big diameter display problem

### ISSUE THREAD

**Issue by MagicUrban** [helix-toolkit/helix-toolkit#1742]
Hello, the problem happens in Workitem10054 in HelixToolkit.Wpf ExampleBrowser project.
The orginal diameter  of the TubeVisual3D is 0.03, the effect is fine.
While the diameter is changed to 3， the effect seems that the pipe is inconsistent.
![260428e7c90cc23b1544ecfae91bf7a](https://user-images.githubusercontent.com/56432942/163185715-562decc4-08f5-4b0c-8e58-3074be902f6b.png)
![07d09829bfc1009fd7a9dee45a7cbc2](https://user-images.githubusercontent.com/56432942/163185786-53ba7a58-7d65-4e78-a173-3af24a0b3b5c.png)
Any help? Thank you.

**Comment by holance** [comment]
The problem is the diameter at 90 degree bending is not the same (it is a ellipse with smaller diameter on the plane as the 90 degree bending) as the diameter of the tube. To solve this, you have to create a smooth transition at the bending to reduce the misshape on the tube.
