### ISSUE TITLE
Scene and Meshnode

### ISSUE THREAD

**Issue by lovefri** [helix-toolkit/helix-toolkit#1748]
I have a project class containing MeshNodes inside the class terrain that I later show in a viewport by adding them to a: public SceneNodeGroupModel3D GroupModel. 

- I save the MEshNodes (named mesh) via   var e = exp.ExportToFile(meshFileName, mesh,"obj");
- Later I am able to load the samae file as a scene and use that scene directly och create a mesh from:

            HelixToolkit.Wpf.SharpDX.Assimp.Importer importer = new HelixToolkit.Wpf.SharpDX.Assimp.Importer();
            var mo = importer.Load(meshFileName);
            MeshNode mesh = (MeshNode)mo.Root.Items[0].Items[0];

            MeshNode meshToReturn = new MeshNode() { Geometry = mesh.Geometry , Material = mesh.Material, };

Question 1: As I understand it is possible to export the mesh as a scene since the meshNode is a sceneNode, but how do I create a scene from my meshNOde? Do I need a new class inhereting from scene? 

My problem arises when i try to redraw all meshnodes (foreach terrain in project):
       _viewport3DViewModel.GroupModel.AddNode(terrain.TerrainMesh);// the MeschNode that later will be exported to file 
        in this case some the meshnodes seems to loose som informatin about their positions in relation to each other.
          
If I do this after loading the same meshfiles from file and in to a scene the position information is intact.       
                _viewport3DViewModel.GroupModel.AddNode(terrain.Scene.Root); // the scene loaded from an exporter MEshNode
                
CAn you see why it works with scene.root and not the TerrainMesh (a MEshNode)?  /What I have missed in terms of how to use a scene in relation to SceneNodeGroupModel3D and meshNode.

**Comment by holance** [comment]
https://github.com/helix-toolkit/helix-toolkit/wiki/3D-Formats-Compatibility-issue-with-HelixToolkit

**Comment by lovefri** [comment]
Not the same, but still useful. 

A general question (questions): 
I have a SceneNodeGroupModel3D to which I ad MEshNodes and it seems to work fine. Do I even need the Scene? 

can the viewport3dx only show one scene? 

are my meshNOdes attached to the same scene eaven if I dont specify any scene.? 

Does the scene contain the Root or does the root have a scene. 

I guess what I am trying to ask is how to use the Scene, SceneNode/Meshnode and the SceneNodeGroupModel3D in the best way? 

Thanks for answering so quickly to my slightly fussy question :)

**Comment by holance** [comment]
Probably your scene root node contains the transform for your terrain mesh. If you only add mesh, transform info will be missing.
The scene root node is just a group node. There is nothing special about it.

**Comment by lovefri** [comment]
So I have solved all my issues, but the best practice question remains. 


1. "Should" you use The "HelixToolkitScene" class to contain all your MeshNodes or is it just as good(/a matter of taste) to
keep all the meshNodes in another class and add them one by one to a "SceneNodeGroupModel3D" to display in a viewport3dx? 


2. In my import/export I export each mesh, the export creates a Scene containing that mesh and 
when I import I get a Scene back and then extract the MeshNode from it. It works, but does it seem like a stupid 
way to do it?

**Comment by holance** [comment]
1. You probably can just use a group node to contain all the mesh nodes then export them at once using the group node.
2. When you import,
