### ISSUE TITLE
TubeVisual3D Example doesn't work

### ISSUE THREAD

**Issue by interdrift** [helix-toolkit/helix-toolkit#175]
I was trying to use the TubeVisual3D example but that didn't work.

I literally copy paste the code and change the namespaces to match my project name. The result is  an ArgumentOutOfRangeException thrown from ExtrudedVisual3D.

The problem arises when the TubeVisual3D is being constructed it executes the constructor of ExtrudedVisual3D making the Path property non null but still empty.

Here's where the error happens : 

https://github.com/helix-toolkit/helix-toolkit/blob/master/Source/HelixToolkit.Wpf/Visual3Ds/MeshVisuals/ExtrudedVisual3D.cs#L243

Here's a link to the example 

https://github.com/helix-toolkit/helix-toolkit/tree/master/Source/Examples/WPF/ExampleBrowser/Examples/Tube

**Comment by interdrift** [comment]
Can someone give a hand here?

**Comment by ando23** [comment]
I didn't have time yet to test it, but the code seems to be weird:

`if (this.Path == null || this.Path.Count >= 2) { return null; }`
versus
`var forward = this.Path[1] - this.Path[0];`, meaning that Path,Count **must** be at least two.

So, my guess would be that the if should be changed to 
`if (this.Path == null || this.Path.Count < 2) { return null; }`

If I have time, I will test it this evening.

**Comment by ando23** [comment]
As suspected, the comparison is inverted. Changing it to `<` seems to fix the immediate problem.

**Comment by interdrift** [comment]
That seems to solve the problem. I assume you will make a PR?

**Comment by ando23** [comment]
I will as soon as I find out how. (I'm new to git.)

**Comment by interdrift** [comment]
:clap:
