### ISSUE TITLE
Triangle Strip

### ISSUE THREAD

**Issue by tqmitaca** [helix-toolkit/helix-toolkit#1752]
Hi,
we are currently using HelixToolkit in a WPF to create a series of triangle strip with vertex of different color.
In our old application we used OpenGL and our code was like

glBegin(GL_TRIANGLES);
glColor3f( 1, 0, 0 ); // red
glVertex2f( -0.8, -0.8 );
glColor3f( 0, 1, 0 ); // green
glVertex2f( 0.8, -0.8 );
glColor3f( 0, 0, 1 ); // blue
glVertex2f( 0, 0.9 );
glEnd();

Is there an easy way to replicate this code?
we tried with MeshBuilder.AddTriangleStrip but we didn't understand how to assign colors to the vertex.

**Comment by holance** [comment]
There's a Colors property in MeshGeometry3D.

**Comment by tqmitaca** [comment]
Thank you
