### ISSUE TITLE
HelixToolkit.Core.Wpf 2.21.0 -"Teapot" not found assembly in WPF .NET 6.0

### ISSUE THREAD

**Issue by MauNguyenVan** [helix-toolkit/helix-toolkit#1757]
Hi. 
I'm a new member of the learning helix toolkit.  
Now I'm getting issues to add "teapot" to viewport3D -  "Could not load file or assembly 'HelixToolkit.Wpf, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.".  
What's wrong with the teapot or where am I wrong.  
Thank you.

![image](https://user-images.githubusercontent.com/48544354/171413529-b6040300-25a1-44e9-94ed-6813508689c9.png)

**Comment by holance** [comment]
I don't think there is a `Teapot` visual in helixtoolkit wpf. Not sure where you get this example from.

**Comment by holance** [comment]
Probably it's out dated.
