### ISSUE TITLE
WinUI - Viewport reloading on Page Navigation

### ISSUE THREAD

**Issue by giovannapalomba** [helix-toolkit/helix-toolkit#1763]
Hello,
I'm trying to develop a WinUI application where I navigate through different Pages, some of which feature a Viewport3DX to show an ObservableCollection through ItemsModel3D control.

I already set `NavigationCacheMode="Enabled"` to my Pages, so that they do not inizialize every component each time I navigate to any of them. 
However, everytime I navigate to  Pages where a Viewport is featured, every object of my ObservableCollection is created all over again: since I may have quite a lot of objects in my Collection, it may introduce some delay.

Is there a way to specify the RenderOption as you could on WPF? Do you have any suggestion?

Thank you

**Comment by holance** [comment]
Could you provide a sample app for this issue?

**Comment by giovannapalomba** [comment]
Here you go: https://github.com/giovannapalomba/SampleNavigationHelix
 
As you can see, I did not set` NavigationCacheMode="Enabled"` in Page1View ì, so everytime I navigate to that page, it initializes the components all over again.

I put the tag in HelixPageView instead, so it doesn't initialize components. Yet, if you put a breakpoint in the constructor of CustomBox3D, it goes to it everytime I navigate to HelixPageView. Also, something is off about the Visibility property when you navigate the second time. 

I hope it's clearer now, thank you for your time!
