### ISSUE TITLE
RenderEnvironmentMap doesn't work in v2.21.0

### ISSUE THREAD

**Issue by sinaone1** [helix-toolkit/helix-toolkit#1767]
Hello
I had version 2.20.0.0 HelixToolkit.Wpf.SharpDX and in that version I used from PhongMaterial to have reflection and everything was ok, This is my code 

` 
Return New PhongMaterial With {
                      .AmbientColor = Colors.White.ToColor4(),
                      .DiffuseColor = Colors.White.ToColor4(),
                      .SpecularColor = Colors.Black.ToColor4(),
                      .SpecularShininess = 25000,
                      .RenderEnvironmentMap = True,
                      .EnableFlatShading = True
                  }`

But I just updated version to v2.21.0 and now reflection doesn't work.
Could you tell me please something in codes has been changed and I have to change my way to load reflection or there is a bug?
Thank you

**Comment by holance** [comment]
Could you create a sample project to show this issue? I haven't been able to reproduce this issue. 
Could you also try 2.21.1 beta from nightly build?

**Comment by sinaone1** [comment]
Sorry it late to answer but I found the problem
In the old version after you load EnvironmentMap you can set IsRendering and hide background because it will be more prettier I think.
But now in new version if you do that , it will disable also reflection.
I 
attached an example and there is a button and you could test it.
[Example.zip](https://github.com/helix-toolkit/helix-toolkit/files/8896241/Example.zip)
Thank you

**Comment by holance** [comment]
Yes, that is intentional since it doesn't make sense to render environment map on objects without rendering it. What's your use case for not rendering the environment map at the background？

**Comment by sinaone1** [comment]
I have a 3d machine and because focus is just on the machine and I'm using from EnvironmentMap just to be more realistic,So I must hide the background to don't make any confusion to see machine.
Do you think is there any way like the last version that I keep reflection of EnvironmentMap but also don't show that?

**Comment by holance** [comment]
Use `EnvironmentMap.SkipRendering = true` to disable environment map background rendering.

**Comment by sinaone1** [comment]
Thank you so much

**Comment by sinaone1** [comment]
Sorry how can I update the helix to version 2.21.1? 
Because we don't have it in nuget

**Comment by sinaone1** [comment]
Thank you again
