### ISSUE TITLE
render different colors for different faces

### ISSUE THREAD

**Issue by x1y9** [helix-toolkit/helix-toolkit#1780]
I have a single mesh object (about 20,000 faces), can I render different colors for different faces? There are about 50 colors in total, if the WPF version can't do it, can the SharpDX version?

**Comment by holance** [comment]
In SharpDX version, you can assign `MeshGeometry3D.Colors` for vertex color. Otherwise you have to use texture with texture coordinates. Also if you want color to be completely different on two nearby faces, you need to separate the shared vertices.
