### ISSUE TITLE
Question: how to add to Showcase

### ISSUE THREAD

**Issue by ikonuk** [helix-toolkit/helix-toolkit#1787]
Dear Colleagues:
I have completed a medium size project using Helix Toolkit. I would like to add some information on the Showcase folder on my project (program executable and user documentation). The program analyzes offshore pipeline laying procedures using FEM. I am attaching some graphics output.

Would you let me know if this would be appropriate and how I should go about?

I. Konuk

![Pipelay_3D_Zoom_12SId copy](https://user-images.githubusercontent.com/44346152/175110818-095a07e3-274f-475a-a5d8-390b5d985a8b.jpg)

 
![Pipelay_3D_103_12SId copy](https://user-images.githubusercontent.com/44346152/175110836-abf3b0ee-814b-44e3-bf8d-86b8f6d203ef.jpg)

**Comment by holance** [comment]
I think you can just edit this wiki page: https://github.com/helix-toolkit/helix-toolkit/wiki/Showcases-(WPF)

**Comment by ikonuk** [comment]
Thanks
