### ISSUE TITLE
Jagged when transparent

### ISSUE THREAD

**Issue by x1y9** [helix-toolkit/helix-toolkit#1789]
I have a Viewport3DX(SharpDX version 2.21.1), when I set a transparent DiffuseMaterial material to the model, I can see the jaggedness at some angles.

![image](https://user-images.githubusercontent.com/26735696/175276873-9d79d264-2d2f-488d-8155-348d769d8b5f.png)

I tried to set up MSAA,FXAA, but could not solve it.
When using the wpf version, I don't have this problem.

**Comment by holance** [comment]
What's your camera parameters? Seems like z fighting.

**Comment by x1y9** [comment]
Camera setting:
```
new PerspectiveCamera()
{
    Position = new Point3D(0, 0, 10),
    LookDirection = new Vector3D(0, 0, -10),
    UpDirection = new Vector3D(0, 1, 0)
}
```

And I tried OrthographicCamera, same result.

**Comment by holance** [comment]
Could you try different material?

**Comment by x1y9** [comment]
Same result for PhongMaterial
![image](https://user-images.githubusercontent.com/26735696/175439917-d267d714-bc2a-4225-b542-62bb5ba44092.png)

the code:
```
public static Material GetMaterial(Color c, double opacity, float factor)
{
   //WPF 
   //return new DiffuseMaterial(new SolidColorBrush(c) {Opacity = opacity});
   
    //sharpdx
    return new PhongMaterial(new PhongMaterialCore()
    {
        DiffuseColor = C4(c,opacity)
    });
}
```

for NormalMaterial, I don't know how to set the color and transparency.

**Comment by holance** [comment]
Are you able to provide the model?

**Comment by gregorsGit** [comment]
Hi,
I have the same issue. 
Only with the newer helix version 2.21.X
In my case it can be solved by setting 
OITRenderMode="SinglePassWeighted"

**Comment by x1y9** [comment]
Thanks @gregorsGit，I tried this, but it didn't work for me.  my Viewport3DX:
```
<hx:Viewport3DX Name="my3D"
              Camera="{Binding camera}"
              EffectsManager="{Binding effectsManager}"
              MouseDown="OnMouseDown"
              MouseMove="OnMouseMove"
              Background="#00000000" 
              BackgroundColor="#00000000"
              ShowCameraTarget="False"
              OITRenderMode="SinglePassWeighted"
              ZoomExtentsWhenLoaded="True"
              CameraRotationMode="Turnball">
```

**Comment by x1y9** [comment]
@holance If I use the bunny.obj, after setting transparency, although there is no jaggedness, but also a lot of strange fragments. Is that normal?

![image](https://user-images.githubusercontent.com/26735696/175500223-8a323beb-bb37-4c25-bf70-9f5f8e553bbc.png)


Also, could you tell me how to determine if the normals are correct, or how to recalculate the normals?
My code for loading the mesh:
```
public static void LoadObjMesh(SceneNodeGroupModel3D parent,  string path)
{
    var objs = new ObjReader().Read(path);
    parent.Clear();
    foreach (var obj in objs)
    {
        parent.AddNode(new MeshNode
        {
            Geometry = obj.Geometry,
        });
    }
}
```

**Comment by holance** [comment]
Those artifacts are due to overlapping triangles from back faces. You can try to set `MeshGeometryModel3D.IsTransparent = true` after setting the model as semi-transparent to use transparent pass.

**Comment by x1y9** [comment]
Thank you very much, this does solve two of my problems, but introduces a new one.

The background of Viewport3DX is also transparent (by Background="#00000000" and BackgroundColor="#00000000"), but this transparency will not work as long as MeshGeometryModel3D.IsTransparent is set to true.

![image](https://user-images.githubusercontent.com/26735696/175810121-7042005d-cfd7-4dc5-87c7-f90a9e604727.png)
![image](https://user-images.githubusercontent.com/26735696/175810156-40892267-2708-4906-9c83-73a30c1b178c.png)

**Comment by x1y9** [comment]
ok, I got around this problem by using DynamicResource.
```
<hx:Viewport3DX 
        Background="{DynamicResource BaseBrush}"
        BackgroundColor="{DynamicResource BaseColor}"
```
