### ISSUE TITLE
Drag and Drop problem with helixtoolkit

### ISSUE THREAD

**Issue by Rubenman16** [helix-toolkit/helix-toolkit#1796]
Hi everyone, I have a problem with my 3D model viewing app. When the model is very large, the drag and drop operation creates the problem shown in the video. Can you help me? a thousand thanks

https://user-images.githubusercontent.com/49437202/179194090-f1ccd4d7-f83f-44c2-8859-1bf57d9c9690.mp4

**Comment by holance** [comment]
Which library are you using? Wpf or sharpdx?

**Comment by Rubenman16** [comment]
Wpf

Ottenere Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by holance** [comment]
Looks like you are using a lot of billboards. Probably that's why the performance is bad. You may have to switch to sharpdx version.

**Comment by Rubenman16** [comment]
Ok thanks a lot, I'll try to follow your advice

**Comment by Rubenman16** [comment]
@holance sorry, what are billboards? thx

**Comment by holance** [comment]
Text floating above the model
