### ISSUE TITLE
Rendering to ImageSource offscreen and possibly in seperate thread

### ISSUE THREAD

**Issue by benjamin-9T** [helix-toolkit/helix-toolkit#1797]
I am using Helix 3D to visualize some components in our 3D view.
On the side, I also need to render hundreds of small images, and was wondering if I can do this in a seperate thread and then store the results in a ImageSources.

I searched the web up and down and found some solutions using HostVisual, however, I did not manage to get it to work. SO any help would be highly appreciated.

**Comment by holance** [comment]
https://github.com/helix-toolkit/helix-toolkit/blob/develop/Source/Examples/SharpDX.Core/OffScreenRendering/Renderer.cs
I created this demo for offscreen rendering. 

Probably you need to use the nightly build, or have to copy the latest viewportcore source into your own repo if you want to use the release version.

**Comment by benjamin-9T** [comment]
If I see this correctly, this only works for .Net Core/Standard projects. Is there an option for .Net Framework 4.7.2 too?

**Comment by holance** [comment]
4.7.2 supports dot net standard 2.0. So it works too.

**Comment by benjamin-9T** [comment]
Works like a charm. The problem was sitting in front of the screen. Is there a plan, when you release the next version that implements this as nuget?

**Comment by holance** [comment]
This will be in next release, just don't have an exact date for next release yet.

**Comment by benjamin-9T** [comment]
Hi @holance I tried this now with 2.22.0 Unfortunately the image stays white. When I render using a Window for renderig (Initialize the SharpDX with a Window handle) all works great.
My second issue is that I cannot set the Background as transparent. Do you have another trick for me?

**Comment by holance** [comment]
Transparent background only available on sharpdx wpf version

**Comment by benjamin-9T** [comment]
Ok, I found a workaround for the transparency. However, the example in https://github.com/helix-toolkit/helix-toolkit/blob/develop/Source/Examples/SharpDX.Core/OffScreenRendering/Renderer.cs does not work, all is empty. Is there something I can do here?

**Comment by benjamin-9T** [comment]
All is working now. Thanks for all the tips!
