### ISSUE TITLE
TorusVisual3D

### ISSUE THREAD

**Issue by juno-craft** [helix-toolkit/helix-toolkit#180]
Hi guys, I'm really thankful for this amazing package.

It would be really great if anyone is willing to throw a torus implementation as a Visual3D like this one here ;

http://docs.autodesk.com/ACD/2010/ENU/AutoCAD%202010%20User%20Documentation/index.html?url=WS1a9193826455f5ffa23ce210c4a30acaf-688d.htm,topicNumber=d0e94758

**Comment by interdrift** [comment]
Now that I think more about it this could probably be done by using the PipeVisual3D.

**Comment by Iluvatar82** [comment]
Hey guys,
sorry, I am new to Git, so please be tolerant when I made something wrong here.
I wanted to help a little and created a new branch called **torusvisual3d-branch** via the desktop app. Then I did some coding and committed the changes I made to that branch.

The branch includes a modified MeshBuilder (added a GetCircleSegment function and a AddTorus function), a TorusVisual3D and a new simple Project (in the Example Browser).

I am just now sure how you can now see my additions.
