### ISSUE TITLE
RenderWireframe method in MeshGeometryModel3D (SharpDX) versus MeshGeometry3D (WPF)

### ISSUE THREAD

**Issue by ikonuk** [helix-toolkit/helix-toolkit#1803]
Is it feasible to implement RenderWireframe method somewhere in the basic WPF branch of Helix Toolkit?

I may be naive, but I see a fairly simple example here http://csharphelper.com/howtos/howto_WPF_3D_wireframe.html.

**Comment by holance** [comment]
Since you already have the example code, why not just use it?

**Comment by ikonuk** [comment]
OK. Thanks.
