### ISSUE TITLE
IndexOutOfRangeException in OnCreateHelixMeshWithBones while loading glb file in FileLoadDemo

### ISSUE THREAD

**Issue by christiantippner** [helix-toolkit/helix-toolkit#1805]
Hi,
i want test a glb object with animation in HelixToolkit. When i load my glb file in the FileLoadDemo Example the Application crashes with IndexOutOfRangeException  in the method OnCreateHelixMeshWithBones  on line 224 in file ImporterPartial_Mesh.cs.

My 3d object is in the attachment. 
What is wrong with the glb file. The 3D Viewer from Microsoft can load it!

Thanks for helping me.

[2022.07.21 Box.zip](https://github.com/helix-toolkit/helix-toolkit/files/9165035/2022.07.21.Box.zip)

**Comment by holance** [comment]
There is an index out of range in one of the bone weight index number. I put a fix to prevent index out of range exception, but you probably still want to fix the issue in your glb so the animation can be played correctly.
