### ISSUE TITLE
DataTemplate with literal or static value breaks bindings

### ISSUE THREAD

**Issue by MoSkinny** [helix-toolkit/helix-toolkit#1808]
Hello,
Our apps make pretty heavy use of the toolkit and recently we've upgraded from HelixToolkit to HelixToolkit SharpDX. We rely on DataTemplates and a DataTemplateSelector to dynamically load the correct visuals for a collection of view model items. After upgrading and updating our solution we have an issue where some visuals defined in our templates are being displayed at the origin (0,0,0) instead of at the Point3D values that they are bound to in the data template. When I use snoop I can see that the correct values are set, but the visual is still displayed at the origin. If I update the Point3D value from my application or from within snoop the visual is immediately displayed in the correct position.

I've spend a considerable amount of time trying to pinpoint the issue and I think I've found it. I've created an example project that makes use of a template selector and data templates to demonstrate. You can run it and click the "Create ViewModels..." button. Notice that in that app.xaml file where my DataTemplates are defined there are 2 Sphere shapes defined: a yellow sphere with the Radius set to a literal value; and a turquoise sphere with the Radius bound to a ViewModel property. The yellow Sphere with a literal value does not initially display at the ShapeCenter values location, it displays at the origin. This same behavior exists if the radius is assigned a StaticResource value instead of a literal value. We didn't notice this issue with HelixToolkit, but only after updating to SharpDX.

I've also hard coded a small red sphere in the MainWindow.xaml... this is where the yellow sphere should be displayed initially. It seems like the literal value interferes with the initial bindings.  Can you confirm this is a bug or explain how to address this so that all values bound or assigned to the shape are drawn accurately when they are first displayed?

A work around is to force all values to be bound to properties on our view models (like in the CustomTemplate), which is not always ideal for us; or to force a property changed event for every item displayed on the property bound to the Center after the viewport is loaded, which seems like a bit of a hack. 

Thank you so much for all the work on this project. 

![image](https://user-images.githubusercontent.com/5541870/181122319-614cbadb-c54f-4054-8d5f-8f72ee82764f.png)
[LiteralValuesBreakBindings.zip](https://github.com/helix-toolkit/helix-toolkit/files/9193697/LiteralValuesBreakBindings.zip)

**Comment by holance** [comment]
Where did you set the location of the yellow sphere?

**Comment by MoSkinny** [comment]
@holance Sorry, I didn't highlight that. The yellow sphere is created in MainWindow.xaml.cs in the CreateButton_Click() handler
`items.Add(new SphereViewModel() { ShapeCenter = new System.Windows.Media.Media3D.Point3D(10, 10, 10), Radius = 3 });`
So the position should be 10,10,10
Looks like I also set the Radius property there but that's ignored since I'm setting it directly in the 'SphereTemplate'

**Comment by holance** [comment]
The problem is in the `MyDataTempalte.cs` where you are binding the `sourceItem.Geometry` to `destinationItem.Geometry`, where the geometry in `sourceItem` was created before binding to the view model and the center is zeros.
You probably want to add this ` ignoreDP |= string.Compare("Geometry", dp.Name, true) == 0;` in `MyDataTemplate.cs` line 210.

Also I feel you probably want to change how things get created. Just don't use template, it is hard to debug and make things so complicated. 

Also, you are duplicating a lot of resources. For example, you can just share single sphere geometry across all sphere models and use transform to manipulate its location and size. Instead, you are creating sphere geometries again and again and wasting memories.

**Comment by MoSkinny** [comment]
@holance Thank you for your time! Your fix resolved that issue right away. 

As for your suggestions, that is something we will have to consider. Debugging those issues is definitely complicated... If I understand your comments correctly, you're suggesting we remove the data templates and selector and move that display logic into View Models or another C# class that is used by the view models to create/manage the visual/geometries and bindings in C#. Then use Instancing (like in the example demo) to reduce the number of of geometries we create. Is that accurate? 

I can see the benefits of instancing and that was on my list of things to investigating after upgrading to SharpDX and I also wondered how to reuse/clone AssImp models so don't need to load them for each instance. Currently we use MEF as a plugin/extensibility framework. We (or even users) can define and add new 'types' (ViewModels and Visuals) for our application... and then we were using the DataTemplate3D and TemplatedItemsModel3D to register names with the visuals so that keyframes that referenced Transforms defined in our Data Template could be added to a WPF Storyboard. The storyboard managed and control animations of our visuals based on some generated data. From what I can see in the instancing demo when you animate all the visuals are re-created with locations defined by a matrix used as the transform. So we would be replacing a storyboard with custom logic to mange the animation playback and timing as well. This seems like quite a bit of a shift from some of the logic we have and it will take me some time to understand the pros/cons and rework. If you have thoughts, references, or suggestions. I'm all ears :)

Thanks again for the help!

**Comment by holance** [comment]
You don't really need to use instancing (although this is more efficient),  just assign same sphere geometry for all sphere models, then create transform for each model you want to display.
