### ISSUE TITLE
How to override on mouse click for Visual3D objects?

### ISSUE THREAD

**Issue by interdrift** [helix-toolkit/helix-toolkit#181]
Is there a way to override the On Mouse down event for a Visual3D object. What I'm mainly interested in is overriding the behavior for a SphereVisual3D on mouse click.

**Comment by objorke** [comment]
Please use the forum or gitter for questions :-)

**Comment by objorke** [comment]
`SphereVisual3D` is based on `ModelVisual3D`. Should we change it to a UI visual?

**Comment by interdrift** [comment]
Changing it to UI Visual could have some implications on the performance.
