### ISSUE TITLE
Any plans for .NET MAUI or OpenGL?

### ISSUE THREAD

**Issue by mihai-ene-public** [helix-toolkit/helix-toolkit#1819]
Are there any plans to port this toolkit on other frameworks such as MAUI, or maybe other frameworks/platform such as OpenGL?

The benefit would be that we could deploy on other platforms such as Mac or Linux.

I'm using your project in my open source project, btw, and I love it :)

**Comment by holance** [comment]
No plans for now due to limited resources.

**Comment by denttool** [comment]
Hello,

Do you have any plan for porting this toolkit on .NET MAUI? If yes, is there an estimate?

Thanks
Ali
