### ISSUE TITLE
Render order & "hit" order

### ISSUE THREAD

**Issue by GABowers** [helix-toolkit/helix-toolkit#1828]
I have a project in HelixToolkit WPF that uses a CombinedManipulator on an object. I also add another "main" object to the scene in XAML that encloses that smaller one.

I've found that if I add the smaller object and CombinedManipulator to the scene AFTER the main object (so in the constructor of my datacontext/ViewModel), they become invisible and can't be moved (the same issue exists if they're after main object in XAML).

If I add them to the XAML before the main object, they remain visible beneath the larger object...however they don't catch mouse events, GetMouseCaptured in particular (I found none of the other events worked on a TranslationManipulator).

How would I ensure the mouse event is captured by that object within another?

**Comment by holance** [comment]
HelixToolkit WPF uses wpf internal hit test, we don't have control of it. You probably can try to set IsHitTestVisible to false on the large object.

This can be solved If you use HelixToolkit sharpdx versions.

**Comment by GABowers** [comment]
> HelixToolkit WPF uses wpf internal hit test, we don't have control of it. You probably can try to set IsHitTestVisible to false on the large object.
> 
> This can be solved If you use HelixToolkit sharpdx versions.

Okay thanks, I'll try that.

I was going to use the SharpDX version but I wasn't able to find an easy way to have a simple non-infinite grid at the x-y plane, while the regular WPF version has the `GridLinesVisual3D` element.

**Comment by holance** [comment]
You can create a grid with line builder

**Comment by GABowers** [comment]
> You can create a grid with line builder

Okay thanks, I was able to get that working.

With that in mind, how do I fix the main issue--moving a Manipulator/capturing hits inside of a larger object--in SharpDX?

**Comment by holance** [comment]
Yep, seem like there is no `IsHitTestVisible` property in WPF. Probably you have to use SharpDX version.

**Comment by GABowers** [comment]
Okay thanks. With SharpDX I was able to set IsHitTestVisible to false for the larger outside object and move the Manipulator within.
