### ISSUE TITLE
How to pick points from HelixToolkit.Wpf.SharpDX.PointGeometryModel3D?

### ISSUE THREAD

**Issue by watanabeyyy** [helix-toolkit/helix-toolkit#1829]
Is it possible to interactively pick points from HelixToolkit.Wpf.SharpDX.PointGeometryModel3D that is displayed in HelixToolkit.Wpf.SharpDX.Viewport3DX?
I would like to select points (multiple points) from the point cloud displayed in the GUI by mouse click and obtain the coordinates.

**Comment by holance** [comment]
You can hook up the `pointGeometryModel3D.Mouse3DDown` event and get the `MouseDown3DEventArgs.HitTestResult`. Then you can figure out which point it is being hit.

**Comment by watanabeyyy** [comment]
Thanks for the reply.
I achieved the desired behavior.
