### ISSUE TITLE
ViewCubeVisual3D: Left and Right are (probably) swapped

### ISSUE THREAD

**Issue by ando23** [helix-toolkit/helix-toolkit#183]
It seems that the left and right side of the view cube are swapped:
![image](https://cloud.githubusercontent.com/assets/13274270/9249749/1b17e790-41c8-11e5-9233-7fe45d42aa6b.png)

While **F**ront and **U**p correspond to the model, the cube shows **R**ight where it should be left.

Source\HelixToolkit.Wpf\Visual3Ds\Composite\ViewCubeVisual3D.cs, function UpdateVisuals(), line 340+
I think that `LeftText` and `RightText` are in the wrong order. Variable `right` should be renamed to `left` and it all makes sense:

    this.AddCubeFace(vecFront, vecUp, frontColor, this.FrontText);
    this.AddCubeFace(-vecFront, vecUp, frontColor, this.BackText);
    this.AddCubeFace(vecLeft, vecUp, rightColor, this.LeftText);
    this.AddCubeFace(-vecLeft, vecUp, rightColor, this.RightText);
    this.AddCubeFace(vecUp, vecLeft, upColor, this.TopText);
    this.AddCubeFace(-vecUp, -vecLeft, upColor, this.BottomText);

**Comment by shao200** [comment]
https://cloud.githubusercontent.com/assets/13274270/9249749/1b17e790-41c8-11e5-9233-7fe45d42aa6b.png

**Comment by objorke** [comment]
good catch :-) I think you are right!

**Comment by ando23** [comment]
OK then, I will make a PR for it.

**Comment by objorke** [comment]
:+1:
