### ISSUE TITLE
Remove Postion Box/ Rotation box at bottom right corner

### ISSUE THREAD

**Issue by Zefan-Wang** [helix-toolkit/helix-toolkit#1831]
Hi all,

I would like to remove the rotation indicator/ box at the bottom right corner of the 3d model because it keeps showing the wrong orientation of my 3d model.

Any ideas on how to do this? Thanks.

![image](https://user-images.githubusercontent.com/99153119/191154177-d0418d4c-27db-4ee4-9966-fd788e5f312c.png)

**Comment by holance** [comment]
Viewport.showviewcube= false.
