### ISSUE TITLE
Camera position Update ShadowmapDemo

### ISSUE THREAD

**Issue by lovefri** [helix-toolkit/helix-toolkit#1839]
In the ShadowMapDemo I made a button and a command to change teh position of camera1 (a camera controlling shadows).

<hx:CameraModel3D x:Name="lightCamera" Camera="{Binding Camera1}" />

This function changes the value of the camera1 position in the viewmodel:

        private void setCamreaPosition(object parameter)
        {
            Camera1.Position = new Point3D(Camera1.Position.X + 1, Camera1.Position.Y, Camera1.Position.Z);

        }
        
As long as there is a direct binding to Camera1.Position (not just camera) like this: 

            <hx:SpotLight3D
                x:Name="spotLight"
                Direction="{Binding Camera1.LookDirection, Mode=OneWay}"
                OuterAngle="{Binding Camera1.FieldOfView}"
                Position="{Binding Camera1.Position, Mode=OneWay}"
                Range="{Binding Camera1.FarPlaneDistance}"
                Color="{Binding DirectionalLightColor}" />
                
changes in Camera1.Position will trigger the view and update directly and all works fine, but how to trigger changes if no element is bound directly to Camera1.Position only to Camera1 like this:
<hx:CameraModel3D x:Name="lightCamera" Camera="{Binding Camera1}" />

The solution I see right now is to let something bind directly to Camera1. Position eaven if I dont need it or to "new" Camera1 when its members are changed. This does not feel like the best solution though. 

Is there a better way to make the view trigger on changes made in subproperties such as the camers position or should a better way be added to helix? 

If it was unclear I want teh view with a binding to Camera1 to update when a change is made to Camera1.Something i the viewmodel.

**Comment by holance** [comment]
Probably you can try to manually trigger the property changed event in your view model as workaround. 
Or you can create your own CameraModel3D and hookup the property change listeners.

**Comment by lovefri** [comment]
Manually trigger an Onpropertychanged that trigger the Propertychanged event was my first approach:

            Camera1.Position = new Point3D(Camera1.Position.X + 1, Camera1.Position.Y, Camera1.Position.Z);
            OnPropertyChanged(nameof(Camera1));
            
It seems to trigger the event in:

        protected void OnPropertyChanged([CallerMemberName]string info = "")
        {
            if (this.PropertyChanged != null)
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(info));
            }
        }
But this is what suprised me that the viewport still does not react when Onpropertychanged() is triggered. As soon as i scroll in the viewport, make camera1 = new or trigger another property it works. Thats why I wondered if there wa something weird with the perspective camera. 

maby I will implement a Camera of my own as suggested.

**Comment by holance** [comment]
You can just modify this and hookup those property change events:

**Comment by lovefri** [comment]
Are u saying that I should Create a Cameramodel3d (modified as I want) and Bind the LightCamera to that new CameraModel3d.Camrea instead of Camera1 as shown below? 

            <hx:ShadowMap3D
                x:Name="shadowMap"
                LightCamera="{Binding Camera1}"
                Resolution="{Binding ShadowMapResolution}" IsSceneDynamic="True"/>
                
It seems like a property bound directly to the view needs to be updated either way?

**Comment by holance** [comment]
I think I probably misunderstood your question, are you trying not to bind the camera property to a spotlight?
Shadowmap is using spotlight to cast shadow, camera1 is just used to control the spotlight parameters.

**Comment by lovefri** [comment]
If i bind to a spotlight like this: 
            <hx:SpotLight3D
                x:Name="spotLight"
                Direction="{Binding Camera1.LookDirection, Mode=OneWay}"
                OuterAngle="{Binding Camera1.FieldOfView}"
                Position="{Binding Camera1.Position, Mode=OneWay}"
                Range="{Binding Camera1.FarPlaneDistance}"
                Color="{Binding DirectionalLightColor}" />

Then everything works just as I want since the binding to Camera1.Position (not just Camera1) solves the issue and makes the view update when I change Camera1.Position in code. 

The problem arises when I have a directional ligth instead of the spotliht and thereby nothing binding directly to Camrea1.Position. 

What I want is for this shadowmap to update When I update Camera1.Position i my viewmodel:
            <hx:ShadowMap3D
                x:Name="shadowMap2"
                LightCamera="{Binding Camera1}"
                Resolution="{Binding ShadowMapResolution}" IsSceneDynamic="True"/>

It updates the way I want if something binds to Camera1.Position directly 
or I do a "new" Camera1
or if I trigger anything else in the view or scroll etc. 

So I Have the Binding to Camera1 that dont seem to listen to changes is the subproperty Position. 

It seemed a bit odd since other properties seems to update fine.

**Comment by holance** [comment]
Probably you can try to call any Model3D.SceneNode.InvalidateRender in the view model after updating the camera property.

**Comment by lovefri** [comment]
If I add a SceneNodeGroupModel and trigger InvalidateRender it works :
        private void SetCameraFunc(object sender)
        {
            Camera1.Position = new Point3D(Camera1.Position.X + 1, Camera1.Position.Y, Camera1.Position.Z);
            OnPropertyChanged(nameof(Camera1)); // This does not work, as mentioned
            AGeometryModel3DForTest.SceneNode.InvalidateRender();//This does nothing
            GroupModel.SceneNode.InvalidateRender();//This works fine.

So there are a few workarounds like the ones I mentioned in previous comment, but If 
you figure out why it is not enough with this:
            Camera1.Position = new Point3D(Camera1.Position.X + 1, Camera1.Position.Y, Camera1.Position.Z);
            OnPropertyChanged(nameof(Camera1)); // This does not work, as mentioned
or just this:
            Camera1.Position = new Point3D(Camera1.Position.X + 1, Camera1.Position.Y, Camera1.Position.Z);

I would love to hear :)

**Comment by holance** [comment]
Because the there is no property change event gets hookup in shadow map for camera binding. I will fix this in next release.

**Comment by lovefri** [comment]
Woho! Thanks
