### ISSUE TITLE
Crash when runing on a VM with 3D acceleration

### ISSUE THREAD

**Issue by PIUM-arc** [helix-toolkit/helix-toolkit#1842]
I tried to execute the SimpleDemo on a virtual machine (I'm using VMWare) with the 3D acceleration enabled but it crash at the opening. 
When the 3D acceleration is disabled everything works fine. 
I tried to find some informations on what's the difference when the 3D acceleration is enabled but i don't find anything usefull. 
Do you have any idea on what could cause the crash ?

**Comment by holance** [comment]
What's the stack trace from the crash?

**Comment by PIUM-arc** [comment]
`'SimpleDemo.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. 
'SimpleDemo.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\Demo_en\Desktop\helix-toolkit-develop\Source\Examples\WPF\SimpleDemo\bin\Release\SimpleDemo.exe'. Symbols loaded.
'SimpleDemo.exe' (CLR v4.0.30319: SimpleDemo.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll'. 
'SimpleDemo.exe' (CLR v4.0.30319: SimpleDemo.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll'. 
'SimpleDemo.exe' (CLR v4.0.30319: SimpleDemo.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. 
'SimpleDemo.exe' (CLR v4.0.30319: SimpleDemo.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. 
'SimpleDemo.exe' (CLR v4.0.30319: SimpleDemo.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll'. 
'SimpleDemo.exe' (CLR v4.0.30319: SimpleDemo.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll'. 
'SimpleDemo.exe' (CLR v4.0.30319: SimpleDemo.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. 
'SimpleDemo.exe' (CLR v4.0.30319: SimpleDemo.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. 
'SimpleDemo.exe' (CLR v4.0.30319: SimpleDemo.exe): Loaded 'C:\Users\Demo_en\Desktop\helix-toolkit-develop\Source\Examples\WPF\SimpleDemo\bin\Release\HelixToolkit.Wpf.dll'. Symbols loaded.
Source Link data for HelixToolkit.Wpf.dll failed to parse or does not conform to the schema: {"documents":{}}
'SimpleDemo.exe' (CLR v4.0.30319: SimpleDemo.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll'. 
'SimpleDemo.exe' (CLR v4.0.30319: SimpleDemo.exe): Loaded 'c:\program files\microsoft visual studio\2022\community\common7\ide\commonextensions\microsoft\xamldiagnostics\Framework\x64\Microsoft.VisualStudio.DesignTools.WpfTap.dll'. 
'SimpleDemo.exe' (CLR v4.0.30319: SimpleDemo.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll'. 
'SimpleDemo.exe' (CLR v4.0.30319: SimpleDemo.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\SMDiagnostics\v4.0_4.0.0.0__b77a5c561934e089\SMDiagnostics.dll'. 
'SimpleDemo.exe' (CLR v4.0.30319: SimpleDemo.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Internals\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Internals.dll'. 
'SimpleDemo.exe' (CLR v4.0.30319: SimpleDemo.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll'. 
'SimpleDemo.exe' (CLR v4.0.30319: SimpleDemo.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll'. 
Panic: VERIFY d:\build\ob\bora-16387846\bora-vmsoft\build\release-x64\svga\wddm\src\usermode\wddmcmdbuf.cpp:763
The program '[7320] SimpleDemo.exe' has exited with code 1 (0x1).
`

Here it is.

**Comment by PIUM-arc** [comment]
I have created a WPF application to test and I have the same issue. 
The application is really basic with only an HelixViewport3D in my MainWindow (no binding with model or anything) and the 2 Nuget packages HelixToolkit and HelixToolkit.Wpf.

Is there any dependance or anything that can cause the crash when the 3D acceleration is enabled in the VM ? I don't find a lot of information on what change when the 3D acceleration is enabled but it looks like it has an impact on the helixToolkit packages. 

I have the following stack : 
`'WPFHelix.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. 
'WPFHelix.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\Demo_en\Desktop\WPFHelix\WPFHelix\bin\Release\net48\WPFHelix.exe'. Symbols loaded.
'WPFHelix.exe' (CLR v4.0.30319: WPFHelix.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll'. 
'WPFHelix.exe' (CLR v4.0.30319: WPFHelix.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll'. 
'WPFHelix.exe' (CLR v4.0.30319: WPFHelix.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. 
'WPFHelix.exe' (CLR v4.0.30319: WPFHelix.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. 
'WPFHelix.exe' (CLR v4.0.30319: WPFHelix.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll'. 
'WPFHelix.exe' (CLR v4.0.30319: WPFHelix.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll'. 
'WPFHelix.exe' (CLR v4.0.30319: WPFHelix.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. 
'WPFHelix.exe' (CLR v4.0.30319: WPFHelix.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. 
'WPFHelix.exe' (CLR v4.0.30319: WPFHelix.exe): Loaded 'C:\Users\Demo_en\Desktop\WPFHelix\WPFHelix\bin\Release\net48\HelixToolkit.Wpf.dll'. 
'WPFHelix.exe' (CLR v4.0.30319: WPFHelix.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll'. 
'WPFHelix.exe' (CLR v4.0.30319: WPFHelix.exe): Loaded 'c:\program files\microsoft visual studio\2022\community\common7\ide\commonextensions\microsoft\xamldiagnostics\Framework\x64\Microsoft.VisualStudio.DesignTools.WpfTap.dll'. 
'WPFHelix.exe' (CLR v4.0.30319: WPFHelix.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll'. 
'WPFHelix.exe' (CLR v4.0.30319: WPFHelix.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\SMDiagnostics\v4.0_4.0.0.0__b77a5c561934e089\SMDiagnostics.dll'. 
'WPFHelix.exe' (CLR v4.0.30319: WPFHelix.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Internals\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Internals.dll'. 
'WPFHelix.exe' (CLR v4.0.30319: WPFHelix.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll'. 
'WPFHelix.exe' (CLR v4.0.30319: WPFHelix.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll'. 
The program '[8988] WPFHelix.exe' has exited with code 1 (0x1).`

**Comment by holance** [comment]
Are you able to run wpf app without HelixToolkit?

**Comment by PIUM-arc** [comment]
Yes I have no issue when runing a WPF app that doesn't use HelixToolkit.

**Comment by holance** [comment]
You can try to create a 3D app without helixtoolkit. Just copy paste the xaml into your app at the end of the page below:
https://learn.microsoft.com/en-us/dotnet/desktop/wpf/graphics-multimedia/3-d-graphics-overview?view=netframeworkdesktop-4.8

**Comment by PIUM-arc** [comment]
Thanks for the link. I tried and I crash, so the issue doesn't come from Helixtoolkit itself.
So I will have to continue to dig on this. If you have any clue of what could be the issue that would help me a lot. 
Thanks.

**Comment by Pedrodeo** [comment]
Edit : We finally found the issue, the VM was built in an old WMWare Workstation environment, causing issues when using the 3D acceleration. 
Thanks for the time anyway.
