### ISSUE TITLE
Transparancy doesn't work anymore

### ISSUE THREAD

**Issue by Wannak** [helix-toolkit/helix-toolkit#1850]
Hi,

Since update 2.21, IsTransparent method on a MeshNode doesn't work anymore.

![image](https://user-images.githubusercontent.com/15036215/199985268-f477fdc9-cfb9-4a47-a19f-d469db737be5.png)

This is prety straight forward, a bool proprety that send true but the MeshNode is not updating is Transparancy state with IsTransparent.

Does the way of updating Transparancy state of a MeshNode have changed or is it a bug?

Thanks for your time,

Gab

**Comment by holance** [comment]
You can try to fallback to old behavior by setting `Viewport3DX.OITRenderMode=OITRenderType.SinglePassWeighted`.
May I ask what is your machine configuration?

**Comment by holance** [comment]
Are all computers not working with `Viewport3DX.OITRenderMode=OITRenderType.DepthPeeling`?

**Comment by Wannak** [comment]
The 2 tested didn't showed the transparancy anymore. 
Pretty recent laptops (less than 3 years old).

Maybe my problem is that I have 2 MeshNode that share the same MeshGeometry3D, one for each side.
