### ISSUE TITLE
Using Assimp requires WPF or UWP?

### ISSUE THREAD

**Issue by mbreckon** [helix-toolkit/helix-toolkit#1855]
I'm working in a WinForms .NET 4.7 app so I'm using the HelixToolkit.SharpDX.Core package and working at the scene node level rather than with the WPF geometry objects. I would like to use the Assimp importer but the HelixToolkit.SharpDX.Assimp package provides a version of the importer that returns objects for the WPF side of things. I can't see a way to convert these easily and it also requires dependencies on the WPF packages (e.g Presentation.dll). 

I'll find a way around it for now (I only require an STL at this monent) but I'm wondering if it might be necessary to split the HelikToolkit.SharpDX.Assimp into HelixToolkit.SharpDX.Assimp.Core, HelixToolkit.SharpDX.Assimp.Wpf, HelixToolkit.SharpDX.Assimp.UWP?

**Comment by holance** [comment]
Probably because how HelixToolkit.SharpDX.Assimp nuget package determines the platform by .net version. One workaround you can try is to create an empty .net standard 2.0 project and adds helixtoolkit assimp package, then it should install correct package for HelixToolkit.SharpDX.Core.

**Comment by mbreckon** [comment]
Thanks. Not sure when I'll confirm that approach (I just reverted to StlReader for the moment) but I can see from the Nuget package folder structure that it should work (the .Core dll is in the netstandard folder and the WPF one is in the .NET46).

**Comment by mbreckon** [comment]
I can confirm that this does work around the issue.
