### ISSUE TITLE
How to avoid the overpainting effect?

### ISSUE THREAD

**Issue by AFriendlyGuy** [helix-toolkit/helix-toolkit#1856]
I am using the HelixToolkit.WinUI nuget package (2.22.0) and I have an red opaque mesh (and some black lines) within a semi-transparent grey mesh. Partially the result is as I want but partially (surrounded by the blue line in the attached picture), somehow some triangles of the inner mesh are drawn above the lines and the outer mesh. How is that? How can I avoid this? I looked for hours for an effect causing this but I did not find anything.
It does not depend on the outer mesh. The outer mesh just makes the effect more visible.
![grafik](https://user-images.githubusercontent.com/93993757/202499432-9f710fad-b79a-42ac-950d-2fbd8f350f88.png)
The red mesh is created by
```
  var result = new MeshNode {
                    Geometry = getMeshGeometry3D(),
                    Material = new DiffuseMaterial() {
                      Name = "RedMesh",
                      EnableFlatShading = true,
                      DiffuseColor = DiffuseMaterials.ToColor(1, 0, 0),
                    },
                    IsDepthClipEnabled = false,
                    CullMode = SharpDX.Direct3D11.CullMode.Front,
                };
```

**Comment by holance** [comment]
Make sure the semi transparent mesh is drawn after any opaque meshes.

**Comment by AFriendlyGuy** [comment]
If the semi-transparent mesh is not drawn at all, the effect remains:
![grafik](https://user-images.githubusercontent.com/93993757/202505080-9361cf2f-faf6-464d-a3f2-967d4342b777.png)
The black lines should be drawn over all edges of the red mesh, but the disappear at the same places where the semi-transparent mesh disappears.

**Comment by holance** [comment]
Are you trying to draw wireframe manually over the mesh?

**Comment by holance** [comment]
Another question, what's the purpose for setting `CullMode = SharpDX.Direct3D11.CullMode.Front` ?

**Comment by AFriendlyGuy** [comment]
Without the `CullMode` setting, some defects appear: 
![grafik](https://user-images.githubusercontent.com/93993757/202658991-ac8e2a76-8a54-44d9-ac7a-d4dca0721fee.png)
And with depth clip enabled, it looks like this:
![grafik](https://user-images.githubusercontent.com/93993757/202659526-17bde9e9-cbfd-4856-9643-094243183057.png)
The black lines are kind of a wireframe but not exactly, because some edges of the wireframe are omitted, for instance, edges between coplanar triangles.

**Comment by holance** [comment]
When creating the black lines, probably you want to create a small offset on surface normal direction so the red mesh surface will not be overlapping with the black lines. Another way you can try is to tweak the depth bias on the black line mesh node.

**Comment by AFriendlyGuy** [comment]
Well, even if I add a significant offset, there is still the effect, that parts of the lines (and the semi-transparent mesh) are missing:
![grafik](https://user-images.githubusercontent.com/93993757/202857207-732d07c4-d8a4-4d02-b418-0fa43ab496f6.png)

**Comment by AFriendlyGuy** [comment]
I will try to prepare a sample project on Monday.

**Comment by AFriendlyGuy** [comment]
Here is the sample:
[HelixToolkitSample.zip](https://github.com/helix-toolkit/helix-toolkit/files/10056942/HelixToolkitSample.zip)
Run it in the unpackaged version.

**Comment by holance** [comment]
Seems like the mesh winding order is not consistent in the SampleData.json.

**Comment by AFriendlyGuy** [comment]
Why does depth clipping remove the lines in front instead of the lines in the back? Do I miss something here?

Furthermore, I checked the winding with this piece of code:
```c#
bool checkWinding(Mesh.Triangle t)  {
    var p1 = mesh.Vertices[(int)t.P1];
    var p2 = mesh.Vertices[(int)t.P2];
    var p3 = mesh.Vertices[(int)t.P3];
    var e1 = p2 - p1;
    var e2 = p3 - p1;            
    var normal = Vector3.Cross(e1, e2);
    var n = mesh.Normals[(int)t.N];
    var windingOrder = Vector3.Dot(n, normal);
    return windingOrder > 0;
}
            
var sum = mesh.Vertices.Aggregate((a, b) => (a + b));
var mean = sum / mesh.Vertices.Count;
foreach(var t in mesh.Triangles) {
    var p1 = mesh.Vertices[(int)t.P1];
    var n = mesh.Normals[(int)t.N];
    var p = Vector3.Dot(n, p1 - mean);
    if (p < 0)
        throw new System.InvalidOperationException();           
    if (checkWinding(t))
        throw new System.InvalidOperationException();
}
```
Since it does not throw, the normals are consistent and the winding is it too.

**Comment by holance** [comment]
ok, I think I found the issue. 
1. Your mesh winding order is Clockwise, so you need to set `MeshNode.FrontCCW = false` for the mesh imported from json. Then you should be able to use `CullMode=Back`.
2. The `direction` you set at line 74 is {0, 0, 1}, which is too close to the object, that's why you are getting the weird effect because part of the object is behind the near plane of the camera. If you increase the value to {0, 0, 15}, it should fix the issue.
3.  Try to set Camera position/LookDirection/Width directly instead of using `Camera.AnimateTo`.
4.  Remove any depth clipping settings.

**Comment by AFriendlyGuy** [comment]
So, the main problem was the distance between mesh and camera position. I would have thought I tried different values for that, but maybe there were other settings wrong at the time. Thanks for your help!
