### ISSUE TITLE
how to improve load 3ds speed.

### ISSUE THREAD

**Issue by chenhao86** [helix-toolkit/helix-toolkit#1857]
sharpDx 2.20

  

There are many models in viewport, using Assimp.Importer load file. the model file is the same, the transformation when loading into the viewport is different. 

How to improve the loading speed. It takes 3 seconds to load 25 and 7 seconds to load 53. 
I found load one file to use 100ms. 
file size about 900kb.

```c#
  if (!File.Exists(filepath))
  {
      return false;
  }
  
  Importer importer = new Importer();
  importer.Configuration.GlobalScale = s_scale;
  importer.Configuration.BuildOctree = false;
  importer.Configuration.EnableParallelProcessing = true;
  importer.Configuration.ImportAnimations = false;
  importer.Configuration.ForceCullMode = false;
  importer.Configuration.AddsPostEffectForSkeleton = false;

  HelixToolkitScene hts = importer.Load(filepath);

  if (default != obj)
  {
    foreach (var n in hts.Root.Traverse())
    {
        n.Tag = obj;
    }
  } 

  SceneNodeGroupModel3D scm = new SceneNodeGroupModel3D();
  scm.AddNode(hts.Root);

  return scm;
```

**Comment by holance** [comment]
You can use share same Geometry3D and set different transforms so you only need to load the model once.

**Comment by chenhao86** [comment]
thks for u reply,i try it.

**Comment by holance** [comment]
Are you applying transformation in your own code?

**Comment by chenhao86** [comment]
yes,

**Comment by holance** [comment]
You can just share the `MeshNode.Geometry` object for all meshes with same geometry but with different Transforms.
Or you can do instancing if meshes with same geometry are using same material by setting `MeshNode.Instances = AllTransformsArray`.

**Comment by chenhao86** [comment]
thks, i try it.

**Comment by chenhao86** [comment]
i cache Assimp.Scene object in memory,speed increased a lot.

```c#
Scene assimpScene = default;
if (!FmCacheHelper.TryGet(filePath, out assimpScene))
{
    assimpScene = importer.ImportFile(filePath, postProcess);
    if (IsCache)
    {
         FmCacheHelper.TryAdd(filePath, assimpScene);
    }
}
```
