### ISSUE TITLE
Error Unknown build error, 'Index (zero based) after update HelixSharpDX 2.21.1 to 2.22.0

### ISSUE THREAD

**Issue by SinaDevelopper** [helix-toolkit/helix-toolkit#1858]
I'm using HelixToolkit and HelixToolkit.SharpDX and HelixToolkit.SharpDX.Assimp DLLs in my WPF application
Also I'm using Net.Framework.4.7.2
My old version was 2.21.1 and everything was fine then I just updated it to 2.22.0 and it gives a lot of errors to these parts of my project

> <VisualTransition GeneratedDuration="0:0:0.3" To="MouseOver">
    <VisualTransition.GeneratedEasingFunction>
        <ExponentialEase EasingMode="EaseOut"/>
    </VisualTransition.GeneratedEasingFunction>
</VisualTransition>

Error is this :

> Severity	Code	Description	Project	File	Line	Suppression State
Error		Unknown build error, 'Index (zero based) must be greater than or equal to zero and less than the size of the argument list.

Nothing didn't changed and I just updated the version , Can you please check why it's happening?
Thank you

**Comment by holance** [comment]
I don't think we use this part of code in the helixtoolkit project. We do change the logging in helixtoolkit in 2.22.0 with Microsoft.Extensions.Logging.Abstractions. If you are using nuget to update your project, it shouldn't cause any issue.

**Comment by SinaDevelopper** [comment]
Yes I updated it by nuget but it's really weird why it happened because before I updated different versions and always was ok.

**Comment by holance** [comment]
Is it working once you revert back to older version?

**Comment by SinaDevelopper** [comment]
> Is it working once you revert back to older version?

I did it and everything works very well

**Comment by holance** [comment]
Could you try to create a simple brand new project and test whether it works or not?

**Comment by SinaDevelopper** [comment]
Problem was about WPFToolkit because after update the Helixtoolkit to 2.22.0 I removed it and everything works well.
Thank you
