### ISSUE TITLE
Glitchy Viewport, windows 11

### ISSUE THREAD

**Issue by antithing** [helix-toolkit/helix-toolkit#1862]
Hi, and thank you for this toolkit, I have been using it for a few years now.

However, i just moved to Windows 11, and i am seeing very glitchy and unusable behavior. This is what the WPF CameraControl example looks like when i open it on my Windows 11 laptop;

![image](https://user-images.githubusercontent.com/11506730/203998303-fd6bba76-04dc-4fe7-bd75-8cd613923fb5.png)

I am on a RTX 3080 GPU, with the latest drivers (I have also tried rolling back drivers). 

Do you have any idea why this might be happening?

Thanks!

**Comment by holance** [comment]
Which HelixToolkit package are you using? HelixToolkit.WPF?

**Comment by antithing** [comment]
Hi, thanks for getting back to me. That's right, it's the wpf package.

**Comment by holance** [comment]
I am unable to reproduce on my win11 machine. Since wpf package is using WPF rendering engine, we don't have a way to debug this issue. Feels like driver compatibility issue.

**Comment by antithing** [comment]
Weird, indeed I only see this on my laptop (msi stealth, rtx 3080)  on a desktop the same code is fine.

I'll play around with rolling back drivers and try to find the cause.

On another note, if I need to load a thousand objects into the viewport, would sharpdx be a better idea than straight wpf?

Thanks!

**Comment by holance** [comment]
Really depends. If all the meshes are different, then performance differences won't be noticable. But if you want to draw same mesh a thousand times on different locations, sharpdx version supports instancing. 

Or if you need to draw many lines/points/billboards, sharpdx version is the one you want to use.

**Comment by JamesTingle** [comment]
I have the same symptom.  I have recently got a new laptop, running Windows 11, with a RTX3060 GPU.  I see the exact same thing when I open up helixtoolkit viewports

Everything was fine on my old laptop, windows 10, but on windows 11 it doesn't work.

Can anyone suggest anything?

**Comment by antithing** [comment]
Hey, I ended up switching to the wpf. Sharpdx module of this toolkit, seems to have resolved the problem.

**Comment by JamesTingle** [comment]
This appears to affect the embedded Intel graphics only.  If I force the application to use the dedicated RTX3060 GPU everything is fine.

It looks to be an incompatibility somewhere between Windows 11, Intel Xe drivers, and the HelixToolkit WPF solution - quite where, I don't know!

**Comment by holance** [comment]
Feels like the intel driver compatibility with dx9

**Comment by powerstrong** [comment]
I encountered this issue yesterday. It had the same symptoms when I was using Intel Graphics Driver version 30, but after manually updating to version 31, the problem was resolved.
I'm using MS Surface pro 9.
I downloaded the driver from :
https://www.intel.co.kr/content/www/kr/ko/download/726609/intel-arc-iris-xe-graphics-whql-windows.html
<img width="814" alt="image" src="https://github.com/helix-toolkit/helix-toolkit/assets/55138258/264d764e-5375-4324-9cde-6705845b6712">
