### ISSUE TITLE
sharpdx has similar Media3D.MaterialGroup?

### ISSUE THREAD

**Issue by chenhao86** [helix-toolkit/helix-toolkit#1866]
in wpf, i can combine multiple imageMaterial with Media3D.MaterialGroup , Material can be in a specific area of one side. there are similar Media3D.MaterialGroup in sharpedx  and material can a small area of one site.

**Comment by holance** [comment]
There is no material group in SharpDX. You can create multiple `MeshGeometryModel3D` and set their geometry to be the same `Geometry3D`, then set different material to them, so they can be layered similar to how `MaterialGroup` does.
