### ISSUE TITLE
How to export textures in FBX or OBJ

### ISSUE THREAD

**Issue by SinaDevelopper** [helix-toolkit/helix-toolkit#1872]
I was reading the examples and I found this code to export the root as a obj or fbx file

> HelixToolkit.Wpf.SharpDX.Assimp.Exporter exporter = new HelixToolkit.Wpf.SharpDX.Assimp.Exporter();
var errorCode = exporter.ExportToFile(@"E:\aaa.obj", containerMaster3D, "obj");
MessageBox.Show(errorCode.ToString() );

But problem is when I export it , it doesn't export my textures that I have in the scene.
Do I have activate something to export also Textures?
I attached here an example and you can check it.
[Example.zip](https://github.com/helix-toolkit/helix-toolkit/files/10244728/Example.zip)

**Comment by holance** [comment]
You will need to implement texture export by yourself for each material. And specify such as `PhongMaterialCore.xxFilePath` for each texture in materials, so the exporter will embed the texture path into the exported file.

**Comment by SinaDevelopper** [comment]
Ok thank you

**Comment by SinaDevelopper** [comment]
Ok thank you I will check it then
