### ISSUE TITLE
Need Help for Click on BillboardTextVisual3D

### ISSUE THREAD

**Issue by gurucharansingh11** [helix-toolkit/helix-toolkit#1873]
My requirement is to display a button in Visual3D space which always faces a camera. I came across HelixToolKit recently and i am quite amazed by its reach functionality. I used BillboardTextVisual3D and it perfectly faces the camera always. I replaced the TextBlock control in the VisualChanged method of BillboardTextVisual3D.cs to Button. But not able to attach the click or MouseDoubleClick event. Later i got to know that control is used just for the purpose of rendering on the image and thus not able to attach Click/MouseDoubleClick event. Can anyone guide me towards achieving click on a control which always faces the camera? Sorry if it is a lame question.

**Comment by holance** [comment]
You need to hookup mouse event on viewport level, then use following to get the visual being hit:
```
            var v = viewport.FindNearestVisual(e.GetPosition(sender as IInputElement));
            if(v is BillboardVisual3D bill)
            {
                    // Do something.
            }
```

**Comment by gurucharansingh11** [comment]
Dear Lunci,

Your short and crisp reply made my day.

Thank you so much
-Gurucharan
