### ISSUE TITLE
hello，How to operate HelixToolkit.Wpf.SharpDX

### ISSUE THREAD

**Issue by joy-A** [helix-toolkit/helix-toolkit#1878]
Hello, the author. The first time I used HelixToolkit.Wpf.SharpDX, I have successfully loaded the obj model. Now I want to zoom in, zoom out or pan it. I should do so. Is there any relevant api document? Forgive me for my poor English

**Comment by holance** [comment]
There are several APIs on Viewport3DX such as `AddZoomForce`, `AddRotateForce`, `AddPanForce` etc. If you want fine control on these operations, you can always set camera parameters (`Position`, `LookDirection` and `UpDirection`) directly.
