### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by xingzhenlu** [helix-toolkit/helix-toolkit#1881]
Dear @holance !<br>
I have encountered a memory leak problem. Please help me look at my [Demo](https://github.com/xingzhenlu/helix-toolkit-demo) (runtime is dotnet 6.0). Although I have disposed all the objects I can think of！<br>
<br>
How to trigger:<br>
1、Click the menu item named "UserControl1";<br>
2、After the scene is loaded, use the mouse wheel to zoom repeatedly and try many times;<br>
3、After that, switch to another menu item.<br>

This is the state when the program start:<br>
![status1](https://user-images.githubusercontent.com/10683684/213347498-6b69c5ab-3677-4e24-9bc0-50613b0545d4.png)

This is the status after the program switches the menu:<br>
![status2-0](https://user-images.githubusercontent.com/10683684/213347816-ffc75672-1ff9-428d-bcd1-081d90a17cd1.png)
![status2-1](https://user-images.githubusercontent.com/10683684/213347867-fa55312d-5803-4e07-a75e-abde21e4a11b.png)
![status2-2](https://user-images.githubusercontent.com/10683684/213347881-770231f6-ebfe-48ec-8ecf-c48479b89841.png)

Please forgive my poor English,Thank you!

**Comment by holance** [comment]
Seems like there is a memory leak while enabling the swap chain, you can disable it for now.

**Comment by xingzhenlu** [comment]
Dear @holance !
Your method can't solve the problem.These days I have tried several software (or frameworks, mostly game engines) to load this relatively complex 3D model.

1. The [godot](https://godotengine.org/) program needs about 350Mb of memory to load this model.
![11](https://user-images.githubusercontent.com/10683684/215968137-5d8563d2-abd1-4b75-a1dd-86ab34b13e68.png)

2. The [unity3d](https://unity.com/) program needs about 111Mb of memory to load this model.
![22](https://user-images.githubusercontent.com/10683684/215968166-a19ba7fb-e7f7-4a51-9515-db64afb9d9d2.png)

3. The [Stride](https://www.stride3d.net/) program needs about 300Mb of memory to load this model.
![33](https://user-images.githubusercontent.com/10683684/215968326-a9a17f47-b62c-46af-b523-839e03eec418.png)

I want to use these game engines to develop a scene simulation program, and then embed it in the wpf program to communicate with processes through named pipes or shared memory. These solutions are indeed feasible, and there are many online reference materials. Compared with the Helix-toolkit component development model, the development experience is very poor, and the size of the packaged file is also relatively large. For graphic programming, I am a novice. Do you have any good suggestions?

**Comment by holance** [comment]
Game engine frees up the memory once data being uploaded into GPU if you only used them for visualization. Helixtoolkit maintains a copy of the original data in memory for such as hit testing and so on (like user can retrieve the entire mesh data at anytime). That's why there is a big differences on memory usage. 

Also most of game engine is written in C++ which has their own memory collection model. HelixToolkit uses standard .net GC, which may take a while for it to collect all the garbages even if you call `GC.Collect()`. You can toggle between after clicking `UserControl1` in your demo, then switching between `UserControl2` and `UserControl3` couple times, you will see memory continue to drop several times.

**Comment by holance** [comment]
If you don't need hit test etc, you can set `loader.Configuration.BuildOctree = false;` before `loader.Load` and 
```
            foreach (var node in scene.Root.Traverse())
            {
                if (node is MeshNode mesh)
                {
                    mesh.Geometry.SetAsTransient();
                }
            }
```
before attaching `EffectsManager` to reduce some memory.

**Comment by xingzhenlu** [comment]
Dear @holance
Thank you for your patience!

I want to obtain the elevation (elevation) of a region from the open Google Geographic Information interface, generate a terrain in the 3D scene, place some photovoltaic matrices on the terrain, and then set the sun's altitude and azimuth to analyze the occlusion. The terrain is generally large, and there are many photovoltaic matrices. Do you think that if I use Helix-toolkit components, Can I meet these requirements?

In addition, I have several small questions:
1. Is there an [airspace ](https://github.com/dotnet/wpf/issues/152) problem with HelixToolkit.SharpDX.Core.Wpf?
2. SharpDX has stopped updating. Is [Silk.NET](https://github.com/dotnet/Silk.NET) a substitute for the future, or are they not a concept?

**Comment by holance** [comment]
HelixToolkit doesn't have the air space issue. Since HelixToolkit sharpdx is based on directx 11 api, it's really stable, though sharpdx has been achieved, I wouldn't expect any change is needed.

I am not familiar with photovoltaic matrices, do you have any examples about it?

**Comment by xingzhenlu** [comment]
Some pictures about photovoltaic matrices(Maybe called solar panels or PV array):
![1](https://user-images.githubusercontent.com/10683684/216245668-6b9a1ef8-9e8e-4b51-8ef7-d94756fb8ec6.png)
![2](https://user-images.githubusercontent.com/10683684/216245684-e911dd74-d562-4a88-80ec-2734ae809d86.jpg)
![3](https://user-images.githubusercontent.com/10683684/216245692-992abb37-505a-4e96-aebb-b94dc79ba8b8.jpeg)

**Comment by holance** [comment]
If you have the entire scene model, you can try to put it in helixtoolkit. I think rendering shouldn't be an issue. But if you want photo realistic rendering with all those shadows, Helixtoolkit won't be able to do it.

**Comment by xingzhenlu** [comment]
Thank you for your patience!
