### ISSUE TITLE
Instancing is very slow with large objects

### ISSUE THREAD

**Issue by gregorsGit** [helix-toolkit/helix-toolkit#1890]
Hi,
I wondering about the framerate using WPF.SharpDX with instancing. (V2.23.0)
Taking your Instancing-Demo on an Intel-HD Graphics Card with FHD-resolution.
The framerate is about 55-60fps.
Now I change the line 76 in the MainViewModel.cs
`b1.AddBox(new Vector3(0, 0, 0), 50, 50, 50, BoxFaces.All);`
To get larger objects.
The count and everything else is the same!
The framerate is now about 4-6fps.

Why is the size of the objects sutch a big factor for the framerate.
I would have assumed that it was primarily the number.

Is this behavior normal or a bug?

Thanks

**Comment by holance** [comment]
There are two performance factors you want to consider, one is CPU bound, one is GPU bound. Instancing is used to solve CPU bound, where it reduces draw calls significantly (CPU uploads data to GPU). However, when you increase object size, GPU has to render much much more pixels per object per instance. For your case, it is more like to be GPU bound.

**Comment by gregorsGit** [comment]
Okay. 
Is there something I can modify to optimize the framerate?
* nearplane/farplane distance.
* EnableRenderFrustum = true
With an NVidia 1050 I get framerates about 30fps.
Thanks.

**Comment by gregorsGit** [comment]
I tested something else.
When I use many InstancingMeshGeometryModel3D with max 1000 parameters for each.
The frame rate for my Intel graphics improve significantly.
This will work for me.
