### ISSUE TITLE
Invert Mouse Zoom

### ISSUE THREAD

**Issue by LHofschlaeger** [helix-toolkit/helix-toolkit#1891]
I want to invert scrolling. For PageUp and PageDown it was easy by setting the PageUpDownZoomSensitivity to -1.
For mouse scrolling i tryed to set the ZoomSensitivity to -1 with no effect.

For PageUp and PageDown the PageUpDownZoomSensitivity is mulitplyed in the OnKeyDown Event 

https://github.com/helix-toolkit/helix-toolkit/blob/b5cdf1bf2fed2e19ebb158211e466c2bcb159c20/Source/HelixToolkit.Wpf.SharpDX.Shared/Controls/CameraController.cs#L1385-L1392

The OnMouseWheel event dose not use the ZoomSensitivity. 
https://github.com/helix-toolkit/helix-toolkit/blob/b5cdf1bf2fed2e19ebb158211e466c2bcb159c20/Source/HelixToolkit.Wpf.SharpDX.Shared/Controls/CameraController.cs#L1443-L1451

Is this on purpose? If so how do I invert the mouse wheele camara zoom? Should i create an PullRequst to fix it?

**Comment by holance** [comment]
`ZoomSensitivity` is being used in ZoomHandler. I changed `Viewport3DX.ZoomSensitivity = -1` and is able to revert the mouse wheel action.
