### ISSUE TITLE
Transparent Rendering Offscreen

### ISSUE THREAD

**Issue by Steph55** [helix-toolkit/helix-toolkit#1893]
I have been experimenting with the Toolkit and I find it very nice! Now I’m trying to render offscreen, but the transparency of the regions containing no object is lost. I have set the BackgroundColor of the ViewportCore to transparent. After I have called viewportCore.RenderHost.UpdateAndRender(), I get the DXGI surface of viewport.RenderHost.RenderBuffer.BackBuffer.Resource and I then use CreateBitmapFromDxgiSurface(), and finally I render the resulting D2D bitmap. The image is ok, but there is no transparency. Is there something else I should have done with the viewport?

Thanks!

**Comment by holance** [comment]
Bitmap does not support transparency.

**Comment by Steph55** [comment]
Thank you very much for your answer! However, Direct2D bitmaps do support transparency (BGRA). However, I have discovered the problem: I was using FXAA. I don't why, but it works perfectly without it, even with SSAO or MSAA.

**Comment by holance** [comment]
Yes, FXAA doesn't support transparency as well

**Comment by Steph55** [comment]
Thank you Lunci, your help is very appreciated!
