### ISSUE TITLE
Per Vertex Coloring and 3D

### ISSUE THREAD

**Issue by ofirmagen** [helix-toolkit/helix-toolkit#1894]
Hello -- I have a stream of vertices (vertices, faces and normals) coming in from our backend, and I use SharpDX to render this anatomical structure on the screen. My task was to color this structure with per vertex coloring, and I do so like this, where GetColor returns a simple Color4 object:

```
            var collection = new Color4Collection();
            foreach (var vert in meshBuilder.Positions)
            {
                if (xMax - xMin > 0)
                {
                    collection.Add(GetColor(updatedVert.X, xMin, xMax, 0.2, 0.7));
                }
            }

          AnatomyMesh.Colors = collection;
```
This works great, but now the issue is that it looks very flat. I need it to look like a 3D object that it is. Before I started this task, we were using a PhongMaterial, and it looked much better, but now since I need to use a VertColorMaterial, I don't know how to make it look less flat.

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/1186781/217696412-8d345fb1-ab09-4594-bc20-9506d0da3dbf.png)

I read in a previous post this: _"Assign texture coordinates for each vertices and assign a gradient texture map as diffuse map in material."_ but I don't know how to do this. Is there an example of how to combine this with VertColorMaterial?

Thanks.

**Comment by holance** [comment]
You can use either PhongMaterial or Diffuse Material and set property VertColorBlendingFactor = 1

**Comment by ofirmagen** [comment]
> 

Thanks. VertColorBlendingFactor is a property on what object? I can't find it in the HelixToolkit.SharpDX solution.

**Comment by holance** [comment]
`PhongMaterial.VertexColorBlendingFactor` and `DiffuseMaterial.VertexColorBlendingFactor`.

**Comment by ofirmagen** [comment]
> `PhongMaterial.VertexColorBlendingFactor` and `DiffuseMaterial.VertexColorBlendingFactor`.

Excellent!! Thank you very much!!
