### ISSUE TITLE
hello,I want to use HelixToolkit.Wpf.SharpDX to display a transparent color picture in the control. What should I do

### ISSUE THREAD

**Issue by joy-A** [helix-toolkit/helix-toolkit#1898]
The following is the code I use, but it doesn't seem to work. It always shows a white background
                    
                  ` BitmapImage bi = new BitmapImage();
                    bi.BeginInit();
                    bi.UriSource = new Uri(@"Resources/image/blueBackground.jpg", UriKind.RelativeOrAbsolute);
                    bi.EndInit();

                    var axisTxt = new BillboardSingleImage3D(bi)
                    { 
                        Center = item.OriginCenter.ToVector3(), 
                    };`

**Comment by Steph55** [comment]
Bitmap images are not transparent. Try using a transparent png image and the following command: 

new BillboardSingleImage3D(TextureModel.Create(pngPath), width, height);

**Comment by joy-A** [comment]
感谢帮助，这是我使用的方法
   Bitmap png;
            using (FileStream fs = new FileStream("Resources/image/" + CoalPileImagePath, FileMode.Open))
            {
                png = new Bitmap(fs);
            }
            using (var ms = new MemoryStream())
            {
                png.Save(ms, ImageFormat.Png);
                PngStream = new MemoryStream(ms.ToArray());
            }
