### ISSUE TITLE
Using SwapChain like Avalonia

### ISSUE THREAD

**Issue by gregorsGit** [helix-toolkit/helix-toolkit#1899]
Hi,
is it possible to use the code of the swapchain D3D from avalonia to get a better performace with overlaying controls..
https://github.com/AvaloniaUI/Avalonia/blob/master/samples/GpuInterop/D3DDemo/D3D11Swapchain.cs

Comparable request:
https://github.com/helix-toolkit/helix-toolkit/issues/1188

**Comment by holance** [comment]
It is the same as `EnableSwapChain` in `Viewport3DX`. As long as you are using WPF, swapchain will not support overlay controls, unless microsoft change WPF rendering engine, which is not likely. If you want to use swapchain natively, UWP and WINUI both support it.
