### ISSUE TITLE
Mouse Scrollwheel zoom stopped working in  2.23.0

### ISSUE THREAD

**Issue by DirkKramer** [helix-toolkit/helix-toolkit#1903]
I upgraded the Nuget package from 2.17.0 to 2.23.0 and the zoom (with mouse scrollwheel) stopped working.

For now I reverted back to 2.17.0 where it works fine. Just wanted to let you know.

**Comment by holance** [comment]
Unable to reproduce this issue, would you mind create a sample project? Feels like probably some settings combination causes the issue.

**Comment by DirkKramer** [comment]
No problem, here is the link: [https://github.com/DirkKramer/HelixMouseWheelZoomTest](url)

**Comment by holance** [comment]
This is not a bug. Basically you are using Orthographic camera, and use CameraMode = WalkAround. When Orthographic camera moves, it does not change its width value, and the object size in the view will not be changed. To zoom with orthographic camera, width has to be changed.

You need to use perspective camera with `CameraMode = WalkAround` to achieve the zooming effect.

**Comment by DirkKramer** [comment]
Okay thanks for your reply. I will change my settings accordingly.  Strange that this worked with 2.17.0 though.

**Comment by holance** [comment]
2.17 has wrong implementation which incorrectly changes the width for orthographic camera.
