### ISSUE TITLE
Upgrade to `.net7`

### ISSUE THREAD

**Issue by AndreasReitberger** [helix-toolkit/helix-toolkit#1904]
Are there any plans to update the library to work with `.net7`? I currently need to upgrade an application (WPF, NetFramework 4.8) to `net7` using the `Upgrade Assistant` from Microsoft.
This works out fine, only this dependency is not supported however which blocks the upgrade.

So I started to also upgrade this project using the `Upgrade Assistant`  (https://dotnet.microsoft.com/en-us/platform/upgrade-assistant).
Most is working out fine, however some shared classes are not found anymore after the upgrade.
I'll attach a draft PR to this issue, so maybe there is a little chance that you might have a look to it.

https://github.com/AndreasReitberger/helix-toolkit/pull/1

**Comment by holance** [comment]
HelixToolkit.Core.Wpf, HelixToolkit.SharpDX.Core, HelixToolkit.SharpDX.Core.Wpf, HelixToolkit.WinUI packages support.net6 and above.

**Comment by AndreasReitberger** [comment]
Yes, but those two not.

```xaml
<Reference Include="HelixToolkit.Wpf.SharpDX, Version=2.23.0.0, Culture=neutral, PublicKeyToken=52aa3500039caf0d, processorArchitecture=MSIL">
      <HintPath>..\packages\HelixToolkit.Wpf.SharpDX.2.23.0\lib\net462\HelixToolkit.Wpf.SharpDX.dll</HintPath>
    </Reference>
    <Reference Include="HelixToolkit.Wpf.SharpDX.Assimp, Version=2.23.0.0, Culture=neutral, PublicKeyToken=52aa3500039caf0d, processorArchitecture=MSIL">
      <HintPath>..\packages\HelixToolkit.SharpDX.Assimp.2.23.0\lib\net46\HelixToolkit.Wpf.SharpDX.Assimp.dll</HintPath>
```

Any chance those get updated as well?

**Comment by holance** [comment]
You need to replace them with the core ones.

**Comment by AndreasReitberger** [comment]
Ok, I see. I'll try that. Thank you!

**Comment by AndreasReitberger** [comment]
Im currently facing a problem while migrating to the `Core` packages.
There is no package for `HelixToolkit.SharpDX.Core.Assimp` [HelixToolkit.SharpDX.Core.Assimp](https://github.com/helix-toolkit/helix-toolkit/tree/develop/Source/HelixToolkit.SharpDX.Core.Assimp)
In your example, you are using a project reference to this library.
https://github.com/helix-toolkit/helix-toolkit/blob/bc5bf2bbb7333722e936644c1027c78e3c7c28a0/Source/HelixToolkit.SharpDX.Core.sln#L18

**Comment by holance** [comment]
The binary is included in `HelixToolkit.SharpDX.Assimp` nuget package. But there is a problem where .net framework will by default using the one for .net 4.6. The workaround is to create a `.netstandard 2.0` above library and use `HelixToolkit.SharpDX.Assimp`, then it will use the correct `HelixToolkit.SharpDX.Core.Assimp` version.

**Comment by AndreasReitberger** [comment]
Now, as suggested by you, the integration of the core version worked. 
Thank you!
