### ISSUE TITLE
Unable to select MeshGeometryModel3D after applying scales, rotates, and transforms in xaml. The FindHits method does not return for transformed MeshGeometryModel3D, especially when they are large. 

### ISSUE THREAD

**Issue by weazel02** [helix-toolkit/helix-toolkit#1914]
```
<core3dxShapes:Cylinder3DX` Material="{Binding Path=ActiveMaterial}" Visibility="{Binding Path=IsTranslationalVisualVisible, Converter={StaticResource AppBoolToVisibilityConverter}}">
 <core3dxShapes:Cylinder3DX.Transform>
   <Transform3DGroup>
    <ScaleTransform3D ScaleX="2"
       ScaleY="2"
       ScaleZ="50" />
<TranslateTransform3D OffsetX="{Binding Path=CenterOfGravity.X, Converter={StaticResource LengthInchConverter}}"
                                          OffsetY="{Binding Path=CenterOfGravity.Y, Converter={StaticResource LengthInchConverter}}"
                                          OffsetZ="{Binding Path=CenterOfGravity.Z, Converter={StaticResource LengthInchConverter}}" />
  </Transform3DGroup>
</core3dxShapes:Cylinder3DX.Transform>
</core3dxShapes:Cylinder3DX>
```

We create and modify our customized shapes using DataTemplates in Xaml. After scaling an object and transforming as such we are unable to click the outer edges of a shape. When I dove deeper it seems like BoundsWithTransform has the correct bounding box however the FindHits method does not return a verified hit within the customized cylinder. If we don't apply any scales or transforms in xaml then all the clicks work appropriately.

**Comment by holance** [comment]
Are you able to create a sample project so I can debug?

**Comment by weazel02** [comment]
[HitTestZScaleDemo.zip](https://github.com/helix-toolkit/helix-toolkit/files/10959628/HitTestZScaleDemo.zip)

This demo allows you to click on the Create_ViewModels button that will spawn a Box3D model. The Box is scaled in App.xaml. You will notice that when you click on the outer edges of the shape FindHits does not return a value thus a message box appears displaying the shape was not selected, if you click near the center of the shape FindHits does return a value and then a message box will appear saying the shape is clicked.

**Comment by weazel02** [comment]
We have noticed this mainly occurs when the ScaleTransform3D is a large value in the Y or Z axis.

**Comment by lx19920404** [comment]
I have the same problem as above, but this problem is probabilistic.

**Comment by holance** [comment]
Please try nightly build 2.24.0-alpha0027.

**Comment by MoSkinny** [comment]
@holance I see the nightly build 2.24.0-alpha0002 but not 0027. Just checking to make sure 0002 is the version you meant?
Thanks for all the help!

**Comment by holance** [comment]
The nightly upload is broken, you can manually download from https://ci.appveyor.com/project/holance/helix-toolkit-qqf1e/build/artifacts

**Comment by holance** [comment]
New nightly build feed link: https://www.myget.org/F/helixtoolkit-nightly

**Comment by weazel02** [comment]
Hey, it looks like the update you made fixed the issue with the single click logic we were experiencing. Thanks! We did have a follow up question about how we should check to see if a MeshGeometryModel3D falls within a rectangle selection space. Previously we were using the MeshGeometryModel3D.Geometry.Positions list to generate a 2D point and check to see if it fell within the rectangle selection space. However, after our change to SharpDX we noticed that the Positions list seems to be pointing at the geometries original position about the orgin (0,0,0) and is not updated after a Scale, Transform, or Rotate is applied via Xaml.. Are we using the correct list to verify it's location or is there a better solution you are aware of
![image](https://user-images.githubusercontent.com/9726798/227323428-32d3fa07-26dc-4cfd-8357-220afac1856a.png)

**Comment by holance** [comment]
You need to multiply each vertex with `SceneNode.TotalModelMatrix` of the model.

**Comment by weazel02** [comment]
So we used a method from a post you commented on in 2018 (https://github.com/helix-toolkit/helix-toolkit/issues/793). We modified it for some recursion that we need when iterating the visual tree. screenMatrix is just _viewPort.GetScreenViewProjectionMatrix() and CheckRectContainsPositions sees if the generated point is contained within our drag selection rectangle. Are you suggesting I take the Vector3 v defiend here and multiply it by the TotalModelMatrix of the model? Also could you clarify the "six vertices from BoundsWithTransform" as its not immediately clear to us what you are referring to. I see the min and max vertices but nothing more. 

![image](https://user-images.githubusercontent.com/9726798/227384090-c7fa994b-e86b-455f-89a0-23eea758e753.png)


private object FindViewModelInSelectionRectangle(MeshGeometryModel3D elementMesh, SharpDX.Matrix screenMatrix)
        {
            Matrix3D elementMatrix = elementMesh.Transform.Value;
            foreach (Vector3 v in elementMesh.Geometry.Positions)
            {
                SharpDX.Matrix m3 = elementMatrix.ToMatrix() * screenMatrix;
                Point3D p3D = m3.ToMatrix3D().Transform(new Point3D(v.X, v.Y, v.Z));
                var p2D = new System.Windows.Point(p3D.X, p3D.Y);

                if (CheckRectContainsPositions(_selectionRect, p2D))
                {
                    var itemsModel3d = elementMesh.Parent as ItemsModel3D;
                    return FindTaggedViewModel(itemsModel3d);
                }
            }
            return null;
        }

**Comment by holance** [comment]
Yes, you need to transform all vertices into world space, which is what `TotalModelMatrix` does. Otherwise you are just transforming them locally.

An axis align bounding box can be represented by two points, which are min and max. You need to create its 6 points from min/max.
