### ISSUE TITLE
NodeAnimationUpdater with absolute timestamps

### ISSUE THREAD

**Issue by Steph55** [helix-toolkit/helix-toolkit#1918]
I need to be able to set the animation timestamp using an absolute time, or, said differently, I need to be able to set the animation at any timestamp without having set it to the previous timestamp before. But this is not actually possible with NodeAnimationUpdater because it uses the variable accumulatedTime which depends on the previous timestamp. It is actually possible to do it with the other animation updaters by using the following calls:
```
animationUpdater.Reset();
animationUpdater.Update(StartTickValue, Frequency);
animationUpdater.Update(absoluteTimeStamp + StartTickValue, Frequency);
```
But this fails with NodeAnimationUpdater, not only because of accumulatedTime, but also because of the following lines which fail with an absolute time greater then the animation  duration in the loop repeat mode, since it always bring the animation to its starts no matter the timestamp:
```
if (accumulatedTime >= Animation.EndTime)
{
     Reset();
}
```
Could I make a pull request to fix these problems, removing completely the need for accumulatedTime?

**Comment by holance** [comment]
Sure, you are welcome to create pr.

**Comment by Steph55** [comment]
I don't know if it is possible to reopen a closed issue, but this problem is still not completely solved.

I made numerous tests and it seems that it takes exactly two calls to animationUpdater.Update() to view the correct animation frame on the screen. Furthermore, these calls must be separated by a direct3D rendering phase otherwise the second call is useless. This problem is therefore not caused by NodeAnimationUpdater code but it seems to be inherent to the rendering pipeline. However, my knowledge in this field is very limited and I cannot figure out why things work out this way.

What I need is real time animations based on precise frames. Is there a way to achieve this, some possible code to call after animationUpdater.Update() or other code modifications, so that I can specify the precise animation frame to render at the next screen rendering?

**Comment by holance** [comment]
You can try to call Viewport3DX.InvalidateRender() to trigger rendering.

**Comment by Steph55** [comment]
With some more tests, I see that this is still not enough, because the TotalModelMatrixInternal (in CompuiteTransformMatrix()) of the top parents must be updated first so that they are applied correctly to their children, then the second level of parents should be updated and so on down to the nodes. I wonder what is the best way to do this and where...?

**Comment by holance** [comment]
You don't need to call `ComputeTransformMatrix()` if viewport is actively rendering. All matrices will be updated automatically during rendering call.

**Comment by Steph55** [comment]
Thank you Holance! It is true that ComputeTransformMatrix() is called automatically in the rendering process. However, it is not called in the correct order! If you have a complex model with many parenting levels, the following lines in ComputeTransformMatrix():
````
parent.TryGetTarget(out var target);
TotalModelMatrixInternal = modelMatrix * (target == null ? Matrix.Identity : target.TotalModelMatrixInternal);
````
rely on the fact that the parent TotalModelMatrixInternal has already been updated, while, in fact, it might not have been. This causes no problem when you render more than one time, since all the TotalModelMatrixInternal are updated at one moment or another in the first rendering call and the model is rendered correctly in the second rendering call, but it doesn't work when you need to present an exact animation frame with only one rendering call. This is needed in my project since I need real time animation with the ability to specify any animation frame without any precise order.

**Comment by holance** [comment]
I don't think your statement is correct. There's only one thread doing animation and rendering. And matrix are always updated from parent to child in render loop before rendering. If order is incorrect, then none of the animation will work correctly.

**Comment by Steph55** [comment]
I'm glad to read that nodes are expected to be correctly ordered! However, ordering them, like in my pull requests, seems the only way to make the animation frames render correctly in one render pass. So I made a demo for you to try by yourself. I just modified the FileLoadDemo from your exemples. In this modified version, the model loads automatically and all parameters are also set automatically. Just use the buttons "Draw frame 1",  "Draw frame 2",  "Draw frame 3" and you will see that the first time you click one, you will need to click it two more times to see the real frame. From then on, you can click any of these buttons and you will see that you will need to click them twice to see the real frame. I have also added another button for continuous drawing.

[FileLoadDemo.zip](https://github.com/helix-toolkit/helix-toolkit/files/11068962/FileLoadDemo.zip)

**Comment by Steph55** [comment]
Please note that this demo does not work as "stand alone", but needs to be inside the Helix Toolkit Solution since it relies on the Wpf DemoCore.

**Comment by holance** [comment]
Please try this PR: https://github.com/helix-toolkit/helix-toolkit/pull/1931.
You can get the package from: https://ci.appveyor.com/project/holance/helix-toolkit-qqf1e/builds/46668633/artifacts

**Comment by Steph55** [comment]
Thank you! I must leave soon for a few days, but I will certainly try your changes next week!

**Comment by Steph55** [comment]
This PR seems to correct the problem, thank you very much!
