### ISSUE TITLE
Incomplete Dispose() method in Element3DCore class

### ISSUE THREAD

**Issue by giovannapalomba** [helix-toolkit/helix-toolkit#1925]
Hi, I have a multiple-page application and almost each page has two different viewport showing different ItemsModel3D showing lists of custom objects... I was wondering what happens when I change page? Is everything referenced as a weak reference? 

I'm trying to investigate a memory leak  and I think the problem could be the Dispose() method of the class Element3DCore being incomplete:
````
protected virtual void Dispose(bool disposing)
{
    if (!disposedValue)
    {
        if (disposing)
        {
            Disposer.RemoveAndDispose(ref sceneNode);
            // TODO: dispose managed state (managed objects).
        }

        // TODO: free unmanaged resources (unmanaged objects) and override a finalizer below.
        // TODO: set large fields to null.

        disposedValue = true;
    }
}
````

I'm using HelixToolkit for WinUI.

**Comment by holance** [comment]
Please try the latest nightly build, we fixed a memory leak issue in winUi package recently.

**Comment by giovannapalomba** [comment]
Do you mean 2.24.0-alpha0002? It's the latest release I see in myget, it goes back to November 2022.. 
I don't see many improvements, am I missing something?

**Comment by holance** [comment]
https://ci.appveyor.com/project/holance/helix-toolkit-qqf1e/build/artifacts

**Comment by holance** [comment]
It should be on myget feed

**Comment by holance** [comment]
Yes, the myget feed upload was broken, will fix it.

**Comment by holance** [comment]
New nightly build feed link: https://www.myget.org/F/helixtoolkit-nightly

**Comment by giovannapalomba** [comment]
I tried it, I still think something is off with the Dispose method of ItemsModel3D class... could it be the events unsubscription?
I created a custom class where I unsubscribe from every event when I navigate to another page and it works better

**Comment by holance** [comment]
Did you call GC.Collect after switching tabs?

**Comment by giovannapalomba** [comment]
No I didn't try.. should I force the garbage collector? Am I expected to explicitly dispose the viewport and its children too?

**Comment by holance** [comment]
If you want to test memory leak, you should force gc. You only need to dispose Viewport3DX.

**Comment by holance** [comment]
You should be able to get the stack trace

**Comment by holance** [comment]
If possible, you can create a small sample project and I can debug the issue.

**Comment by holance** [comment]
I fixed the crash. 
Here is the code I modified for testing:
```
        protected override void OnNavigatedFrom(NavigationEventArgs e)
        {
            viewport?.EffectsManager?.Dispose();
            viewport?.Dispose();
            GC.Collect();
            GC.WaitForFullGCComplete();
        }
```

Few things to improve:
1. Make `EffectsManager` to be a singleton, so it can be reused without disposing it. EffectsManager contains many graphics related resources and can be reused. Creating it for each tab is wasting resources and slow.
2. Don't make far field distance infinite, it will cause rendering issue.

**Comment by giovannapalomba** [comment]
Thank you for the fix and the tips!

The only thing that keep bothering me is this point: 

> If you put a break point on CustomBox3D, line 57 and you select another color in the ComboBox, you can see that older pages keep their references. So, if you navigate to the same page 4 times, you will get 4 notifications. 

I mean, is that a bigger problem related with disposing the whole page? Or is it the correct behavior?

**Comment by giovannapalomba** [comment]
Also, is it correct that I cannot call viewport.Dispose if viewport.IsLoaded == false?

**Comment by holance** [comment]
> Thank you for the fix and the tips!
> 
> The only thing that keep bothering me is this point:
> 
> > If you put a break point on CustomBox3D, line 57 and you select another color in the ComboBox, you can see that older pages keep their references. So, if you navigate to the same page 4 times, you will get 4 notifications.
> 
> I mean, is that a bigger problem related with disposing the whole page? Or is it the correct behavior?

Fixed.

**Comment by holance** [comment]
> Also, is it correct that I cannot call viewport.Dispose if viewport.IsLoaded == false?

You can always call dispose when viewport is no longer being used.

**Comment by giovannapalomba** [comment]
Works great, thanks!
