### ISSUE TITLE
Loaded image buried in background

### ISSUE THREAD

**Issue by Kim-Hyungmin** [helix-toolkit/helix-toolkit#1932]
I don't know how to search for this phenomenon, so I post it here.

After setting CoreWpfTest in the HelixToolkit.SharpDX solution as a startup project, when I load the 3ds file I have, it gets buried in the background like my Image.

Image did not fully loaded and when I zoomed out, my 3D model is buried in background Gray color. 
![Buried-in-BG](https://user-images.githubusercontent.com/52476449/229431729-51df55c6-fac7-4e05-82db-a453fd6dfa20.png)

How can this be resolved?

**Comment by holance** [comment]
Increase the fat field distance value in camera property, or scaling down the model size

**Comment by Kim-Hyungmin** [comment]
I Increase FarPlaneDistance, and Its solved! Thank you for your help.
