### ISSUE TITLE
ViewPort / ViewCube default direction

### ISSUE THREAD

**Issue by onslauth** [helix-toolkit/helix-toolkit#1933]
Hi,

I would like to say that this is a great project especially for doing 3D in the new AppSDK ( WInUI ). I have managed to get it all working and it is running great.

I would like to know if there is a way to start the ViewPort3DX so that it is facing Front "F" according to the ViewCube. By default it starts with the back "B" view showing.

**Comment by holance** [comment]
You can either change the camera look direction or use custom viewcube texture to flip front and back

**Comment by onslauth** [comment]
Would you be able to point me to an example of changing the look direction? I believe I tried it but it didn't seem to have any effect.

**Comment by holance** [comment]
You need to change both camera position and look direction

**Comment by onslauth** [comment]
I have a camera setup as:
```C#
public Camera Camera = new OrthographicCamera( ) { 
            NearPlaneDistance = 1e-2, 
            FarPlaneDistance = 1e4, 
            Position = new SharpDX.Vector3( 0, -5, 0 ), 
            UpDirection = new SharpDX.Vector3( 0, 0, 1 ) 
};
```

The `ViewPort3DX` has a `ModelUpDirection` set to `( 0, 0, 1 )`.

And I have set the `ViewPort3DX.LookAt` value to `( 0, 0, 0 )`.

This starts with the view as:
![image](https://user-images.githubusercontent.com/44875/230015710-1b1ff690-69ba-4596-9220-b9a6fc60dd0c.png)

This looks like the camera is actually at `( 0, 0, -5 )`.

If I inspect the Camera object says it is at position `( 0, -5, 0 )` with a Target of `( 0, -5, -5 )`. 

How would I achieve the effect so that the camera is looking at point `( 0, 0, 0 )` with the X-Axis positive to the right, and Z-Axis positive upwards?

**Comment by onslauth** [comment]
Thank you @MauNguyenVan for the reply. 

After all this I noticed that I had never bound the Camera object created in the code to the control. It is now working correctly. Thank you for the help.
