### ISSUE TITLE
Uniform Light

### ISSUE THREAD

**Issue by onslauth** [helix-toolkit/helix-toolkit#1937]
I am trying to create a view with a uniform light, i.e. there shouldn't be any change in surface color and no shadows.

These are the values I am using taken from reading the examples and previous tickets:
```XAML

   <hx:AmbientLight3D Color="White" />
   <hx:DirectionalLight3D Direction="{ Binding ElementName=MainSwapChainPanel, Path=Camera.LookDirection}" Color="White" />
```

And I am creating the objects as follows:
```C#

var green = PhongMaterials.Green; 
green.EnableFlatShading = true;

var s1 = new MeshBuilder( );

s1.AddCubeFace( new SharpDX.Vector3( 1, 0, 0 ), new SharpDX.Vector3( 1, 0, 0 ), new SharpDX.Vector3( 0, 0, 1 ), 0, 5, 5 );

var mesh_geometry = s1.ToMeshGeometry3D( );
MeshGeometryModel3D mesh = new MeshGeometryModel3D( )
{
      Geometry = mesh_geometry,
      Material = green,
};

this.MainSwapChainPanel.Items.Add( mesh );

```

However the display doesn't produce a single consistent color:
![image](https://user-images.githubusercontent.com/44875/230311359-b92cc3f5-05c4-4f5c-9e7c-2c6dee90f52a.png)

![image](https://user-images.githubusercontent.com/44875/230311397-ad3226fe-ceca-4754-9c53-3aa7748f2a6c.png)

What I would like to achieve is something like the red grid where it is a single color without shading. Or failing that, something similar to the ViewCube?

**Comment by onslauth** [comment]
> A face have a front face and a back face, the front face is represented by face's normal vector

What does that have to do with creating a scene with uniform light where there is no variation in color? For example the bottom right ViewCube.

**Comment by holance** [comment]
You can use DiffuseMaterial with `DiffuseMaterial.EnableUnLit = true`.
