### ISSUE TITLE
Does Helix Toolkit work with .NET 7?

### ISSUE THREAD

**Issue by uzername** [helix-toolkit/helix-toolkit#1939]
I have succesfully used Helix Toolkit with .Net Framework 4.8, it was great. But my new project is on .NET 7 platform (targeted Windows, WPF), because .NET 7 is really recent. Does HelixToolkit work with .NET 7 platform? I have checked, https://www.nuget.org/packages/HelixToolkit.Wpf/2.23.0 , HelixToolkit.WPF is targeted on .NET Framework. I know that .NET 7 includes all the features from .NET Framework. Should I use this package: https://www.nuget.org/packages/HelixToolkit.Core.Wpf/2.23.0 ?

**Comment by holance** [comment]
You need to use core.wpf versions for.net 6 and above.
