### ISSUE TITLE
Issue Scaling Complex SceneNodeGroupModel3D with many MeshNode children. Unable to determine outer bounds of parent object SceneNodeGroupModel3D

### ISSUE THREAD

**Issue by weazel02** [helix-toolkit/helix-toolkit#1944]
Hey, we are using HelixToolKit to scale, transform, and rotate 3D models and are currently looking for a solution to scale custom loaded 3D Models by knowing the outer bounds of a complex 3D object. Some models we created ourselves but some are read in via an via an .obj file and then loaded as a HelixToolkitScene/SceneNodeGroupModel3D using the Assimp Importer. We have to traverse very deep in the tree to find a nested GroupNode that contains the Bounds/BoundsWithTransform of each child MeshNode. Our scaling solution needs to know the original dimensions/bounds of the entire model to scale the entire item as one (vs scaling the child mesh nodes individually). Even then its hard to create a solution that uniformly scales all children appropriately. Is there a way we can extract the BoundingBox to a group of MeshNodes? In our selection logic, we noticed that you all have defined code for highlighting a model that only highlights the outer bounds of the geometry. We were wondering if something similar could be done to calculate the BoundingBox for the entire geometry at the SceneNodeGroupModel3D level?
![image](https://user-images.githubusercontent.com/9726798/232583861-787e4bca-dd52-4a32-a93b-3560bb12a11e.png)
![image](https://user-images.githubusercontent.com/9726798/232583896-09badca8-43d4-41c6-938a-e7325ecf4a39.png)

**Comment by holance** [comment]
You can traverse the tree to combine all the bounding box and do scaling on top group node. I don't understand why you need to scale individual mesh nodes.

**Comment by weazel02** [comment]
Could you give a simple example of how you would combine the two bounding boxes?

**Comment by holance** [comment]
@weazel02 Use `BoundingBox.Merge`.
@MauNguyenVan Highlight only available in sharpdx versions.

**Comment by holance** [comment]
@weazel02 Use `BoundingBox.Merge`.
@MauNguyenVan Highlight only available in sharpdx versions.
