### ISSUE TITLE
Model is black when using Meshbuilder AddTube

### ISSUE THREAD

**Issue by DirkKramer** [helix-toolkit/helix-toolkit#1947]
I have a custom material which works on all meshes except when I use the AddTube method from meshbuilder.

Here is the link to the repository to check it out:
(rightcombobox can toggle between different shapes)

[ChainMesh](https://github.com/DirkKramer/ChainMesh)

I tried using invertnormals and other cullmodes but nothing changes.

**Comment by holance** [comment]
The issue is texture coordinate generation is not supported(not implemented) for adding tubes.
