### ISSUE TITLE
[Feature Request] MeshNode.Backmaterial property

### ISSUE THREAD

**Issue by DevTechProfile** [helix-toolkit/helix-toolkit#1948]
Having a back material property for HelixToolkit.Wpf.SharpDX.MeshNode would be great. It would helpful to be able to identify the inner surface of a model or issues with the direction of normals.

**Comment by holance** [comment]
You can create two mesh node with same Geometry3D, one for front with `CullMode = Back`, one for back with `CullMode = front` and `InvertNormal = true`.

**Comment by DevTechProfile** [comment]
This approach could meet the requirements but in many cases we have very large models. Memory is a critical thing...

**Comment by holance** [comment]
As long as you are using same geometry3d, memory is shared.

**Comment by DevTechProfile** [comment]
Thanks for the tips, it works, but you have manage two models. A BackMatrial property would be more elegant.
