### ISSUE TITLE
[HelixToolkit WPF] HelixViewport3D display model is quite weird when press home key with HelixViewport3D.ModelUpDirection is a value different Vector3D(0, 0, 1)

### ISSUE THREAD

**Issue by MauNguyenVan** [helix-toolkit/helix-toolkit#1949]
I think the viewport has an issue. that is when we press home key,  the camera controll allway reset to deffault is `camera.UpDirection = new Vector3D(0, 0, 1);`.
So if HelixViewport3D.ModelUpDirection is a value different Vector3D(0, 0, 1). the viewport display model is quite weird.

I only guess like that. but have no idea it could influent any other feature .
and I think we should update like below, to each time we press home, the camera has  camera.UpDirection== HelixViewport3D.ModelUpDirection.

https://github.com/helix-toolkit/helix-toolkit/blob/67ae8ebd348454259c31ffd22b6d149678495810/Source/HelixToolkit.Wpf.Shared/Controls/CameraController/CameraController.cs#L2464-L2471

https://github.com/helix-toolkit/helix-toolkit/blob/67ae8ebd348454259c31ffd22b6d149678495810/Source/HelixToolkit.Wpf.Shared/Controls/CameraController/CameraController.cs#L1667-L1670

=>fixed
``` csharp
        private void ResetCameraHandler(object sender, ExecutedRoutedEventArgs e)
        {
            if (this.IsPanEnabled && this.IsZoomEnabled && this.CameraMode != CameraMode.FixedPosition)
            {
                this.StopAnimations();
                this.ResetCamera();
                this.ResetCameraUpDirection(); // add this function in to here
            }
        }
```

**Comment by holance** [comment]
I think the better way is just override the home press shortcut and set your own camera default parameters outside Helixtoolkit.
