### ISSUE TITLE
Punch a hole in a flat plate

### ISSUE THREAD

**Issue by Zhaosf007** [helix-toolkit/helix-toolkit#1950]
After I draw a flat plate, how can I make a hole in it?
[img][(https://github.com/Zhaosf007/img/2023-04-21_12-05-36.jpg)](https://github.com/Zhaosf007/imgg/blob/main/2023-04-21_12-05-36.jpg)

**Comment by holance** [comment]
You need to use other library for advanced meshing operation.

**Comment by Zhaosf007** [comment]
Thanks
