### ISSUE TITLE
helix wpf | Anti aliasing support for the WPF version 

### ISSUE THREAD

**Issue by omaramen99** [helix-toolkit/helix-toolkit#1958]
Is it possible to smooth the edges in this image using for example FXAA?
I'm using the wpf version not the sharpDX.
![snp](https://user-images.githubusercontent.com/56793975/236234025-287cddac-23d0-42ec-a5d1-dc00ef49b7d0.png)

**Comment by holance** [comment]
There's no way to support it since it uses wpf rendering engine.
