### ISSUE TITLE
HelixToolkit.MeshBuilder.AddPipes(IList<Vector3D> points...) should be change to HelixToolkit.MeshBuilder.AddPipes(IList<Point3D> points...)

### ISSUE THREAD

**Issue by MauNguyenVan** [helix-toolkit/helix-toolkit#1983]
https://github.com/helix-toolkit/helix-toolkit/blob/e2d3261204d7cfca93e4cee28b9ce9b60e6aea73/Source/HelixToolkit.Shared/Geometry/MeshBuilder.cs#L2022-L2028

I think using `IList<Vector3D> points` is not necessary, have any reason to use Vector3D rather than Point3D in this case.
It should be changed to  `IList<Point3D> points`

**Comment by holance** [comment]
It's ok to change it to `IList<Point3D> points`.
