### ISSUE TITLE
Transparent Background in ViewPort3DX with Transparent MeshGeometryModel3D objects

### ISSUE THREAD

**Issue by mcoleataar** [helix-toolkit/helix-toolkit#1986]
Currently our ViewPort3DX utilizes a `LinearGradientBrush` for the `Background` and the `BackgroundColor` parameter uses `#00000000`.  This allows us to display custom gradient for our background. Our ViewPort3DX contains a number of objects that inherit from `MeshGeometryModel3D` and we have started to utilize the `IsTransparent` property. The problem is that anytime one of these objects `IsTransparent` is set to true, the `BackgroundColor` of the ViewPort3DX loses its transparency and becomes black. Is there a way to have a transparent background color along side transparent `MeshGeometryModel3D` objects?

It is worth noting that I have reviewed the solutions on https://github.com/helix-toolkit/helix-toolkit/issues/1233 and none of them seems to resolve the issue.

**Comment by holance** [comment]
Try to set OITRenderMode to None in viewport3DX.

**Comment by mcoleataar** [comment]
Thanks for the feedback! Setting OITRenderMode to `None` seemed to work, but some objects that were set to be transparent failed to act transparent. I did however try setting the OITRenderMode to `SinglePassWeighted` and that allowed all the objects with `IsTransparent` to be transparent and allowed the gradient background to show. Thanks again for your help!
