### ISSUE TITLE
Update branch after pull request

### ISSUE THREAD

**Issue by MauNguyenVan** [helix-toolkit/helix-toolkit#1988]
here are my working process on git/ GitHub
1. Fork a repository `helix-toolkit/develop`
2. Create my new branch `AEC/improve-component`, then commit there.
3. Create a pull request from `AEC/improve-component` => `helix-toolkit/develop`.
4. Now I want to Update `AEC/improve-component`  history commits the same as `helix-toolkit/develop`.  
I use `update branch` on GitHub but it makes history quite messy,   
How can I update the code base and history commit from `helix-toolkit/develop` to `AEC/improve-component` to continue developing??

- Here is after you approved my pull request.

![image](https://github.com/helix-toolkit/helix-toolkit/assets/48544354/a6bf6d6a-dac4-4726-a8fd-4fbc096005eb)

- And history committing of them. they are the same code base

![image](https://github.com/helix-toolkit/helix-toolkit/assets/48544354/b57e3197-b01a-4142-ae39-adf272dd209b)

- And after I `update branch` (by GitHub button). the history commits are not the same `helix-develop` branch.

![image](https://github.com/helix-toolkit/helix-toolkit/assets/48544354/fdd79b36-d264-4771-9945-0e24f51254b4)
- Details history commits after the update, it is so messy.
![image](https://github.com/helix-toolkit/helix-toolkit/assets/48544354/525bc216-749d-4c04-9bdc-a088c45ccd79)

**Comment by holance** [comment]
Use sync fork button.

**Comment by holance** [comment]
If it shows 4 commits ahead, just do git reset head~4 in local repo to be the same as develop head, and do a force push origin.
