### ISSUE TITLE
ZoomExtents in Helix SharpDX works differntly

### ISSUE THREAD

**Issue by MiChiSm** [helix-toolkit/helix-toolkit#1995]
We used Zoom Extends (e.g.ZoomExtentsWhenLoaded) in Helixtoolkit WPF version and it worked fine. 
With SharpDX WPF version I have the problem that it works differently. For this I modified LineShadingDemo so that only 4 lines (a square) are drawn. Now when I call the ZoomExtends function I would expect the square to always fill roughly the full ViewPort. That's not the case. If I just widen the window and call ZoomExtends then the square gets smaller. If I make the window narrower then even the square disappears. 

Am I misunderstanding something or am I doing something different than the Helix WPF version?

**Comment by MiChiSm** [comment]
If I make the window wider, the graphic gets smaller and smaller. If I drag the window up, the graphic gets bigger and bigger. The graphic is only always enlarged correctly if the proportions are the same.

**Comment by MiChiSm** [comment]
This problem only exists when PerspectiveCamera is used. However, with an OrthographicCamera, ZoomExtents works correctly. I think it's a Helix SharpDX bug.

**Comment by holance** [comment]
> 

Are you talking about zoom extent after resizing the window?

**Comment by MiChiSm** [comment]
Yes. After resizing window a call always zoom extent function (Ctrl+E).

**Comment by holance** [comment]
Please try the new implementation in nightly build

**Comment by MiChiSm** [comment]
I tested the version. It works fine.
