### ISSUE TITLE
Which class implement ` CoordinateSystem`of HelixViewport3D Wpf.

### ISSUE THREAD

**Issue by MauNguyenVan** [helix-toolkit/helix-toolkit#1996]
See the code below, `PartCoordinateView` seems a reference to the `CoordinateSystem`  of Helixviewport3D but  I do not find the origin code class implementing ` CoordinateSystem`.
Note: I check `CoordinateSystemVisual3D.cs` but they are not related. I deleted `CoordinateSystemVisual3D.cs` but `Helixviewport3D` still work well

How can I find the class that did that?

https://github.com/helix-toolkit/helix-toolkit/blob/29ed77c34ce2ca3ce5291a9bcbe49f52d5037433/Source/HelixToolkit.Wpf.Shared/Controls/HelixViewport3D.cs#L915

https://github.com/helix-toolkit/helix-toolkit/blob/29ed77c34ce2ca3ce5291a9bcbe49f52d5037433/Source/HelixToolkit.Wpf.Shared/Controls/HelixViewport3D.cs#L3398

**Comment by holance** [comment]
It is implemented as separate viewport at here: https://github.com/helix-toolkit/helix-toolkit/blob/29ed77c34ce2ca3ce5291a9bcbe49f52d5037433/Source/HelixToolkit.Wpf.Shared/Themes/Generic.xaml#L118
