### ISSUE TITLE
Question about 0.75 number in `CameraExtensions.ZoomExtents()` ?

### ISSUE THREAD

**Issue by MauNguyenVan** [helix-toolkit/helix-toolkit#1998]
What is the 0.75 number in this line meaning? I think it should be 0.5  followed by Pythagorean theorem

https://github.com/helix-toolkit/helix-toolkit/blob/29ed77c34ce2ca3ce5291a9bcbe49f52d5037433/Source/HelixToolkit.UWP.Shared/Controls/CameraExtensions.cs#L455-L457

https://github.com/helix-toolkit/helix-toolkit/blob/29ed77c34ce2ca3ce5291a9bcbe49f52d5037433/Source/HelixToolkit.SharpDX.Core/Extensions/CameraExtension.cs#L306-L308

https://github.com/helix-toolkit/helix-toolkit/blob/29ed77c34ce2ca3ce5291a9bcbe49f52d5037433/Source/HelixToolkit.Wpf.SharpDX.Shared/Controls/CameraExtensions.cs#L577-L579

**Comment by holance** [comment]
Fixed in #2003
