### ISSUE TITLE
Obj export doesn't export correct transform/rotation

### ISSUE THREAD

**Issue by objorke** [helix-toolkit/helix-toolkit#20]
**This issue was imported from [CodePlex](http://helixtoolkit.codeplex.com/workitem/9984)**

**[AlexanderPD](http://www.codeplex.com/site/users/view/AlexanderPD)** wrote 2013-03-30 at 12:59
Hi, i'm exporting my model with a normal

<pre><code>exporter.Export(Model);</code></pre>

My Model is a Model3DGroup with some Children, every Children has a custom Transform3DGroup.

Every Transform3DGroup has different transform and rotate value (saved as childs of that Transform3DGroup).

When i import the exported model transform and rotation values are different from the model in viewport! Rotation seems to be resetted and transform set some model in different places (seems like only 1 axis is wrong)

The global model is also rotated and transformed but fix it manually during the obj load.

Can you fix those bugs? 

Thank you all for your great work, Helix 3D Toolkit rocks!

**[objo](http://www.codeplex.com/site/users/view/objo)** wrote 2013-04-15 at 12:31
Can you create some code (preferably a unit test) that reproduces this error?

The "ExportDemo" in the "ExampleBrowser" creates an .obj file with a hierarchy of transformed groups. I verified this in Octane render when I created the example, but I see MeshLab has problems importing the file...

**Comment by tree1891** [comment]
I have same issue.
Original has a box and a cylinder.
Also Exported has other models than original.

[exported.zip](https://github.com/helix-toolkit/helix-toolkit/files/2221669/exported.zip)
![exported](https://user-images.githubusercontent.com/1282201/43112547-31ef127a-8f29-11e8-9837-9a3e840b6bcf.PNG)
![original](https://user-images.githubusercontent.com/1282201/43112548-325ca54c-8f29-11e8-9c9e-41a7d55ab1c1.PNG)
![exported_2](https://user-images.githubusercontent.com/1282201/43112550-33dd31fc-8f29-11e8-859d-250a37a44a7a.PNG)

**Comment by ww34ww34ww34** [comment]
Hi Everyone. I had the same issue. Than I found the reason.
In the file ObjExporter at line 74 there is a variable
 this.SwitchYZ = true;

Just setting this variable to false the object will be exported in the correct Way.

You can set also it from your instance of ObjExporter. For example in example project "EXPORT " in the file Viewport3DHelper you can just modify the function "ExportObj" (line1046)

 ```
     var e = new ObjExporter
            {
                TextureFolder = dir,
                FileCreator = f => File.Create(System.IO.Path.Combine(dir, f))
            };
            using (var stream = File.Create(path))
            {
                e.MaterialsFile = System.IO.Path.ChangeExtension(filename, ".mtl");
                **e.SwitchYZ = false;**
                e.Export(view, stream);
            }
```

**Comment by tree1891** [comment]
It is not fixed.
