### ISSUE TITLE
Model materials

### ISSUE THREAD

**Issue by JuandreG** [helix-toolkit/helix-toolkit#2000]
Hi again.

Something else I'm trying out is to load a glb model then combine all the instances into 1 model of type `MeshGeometryModel3D`. The issue I'm having is I would like to preserve the material/colors of the glb file. I was able to create 1 `MeshGeometryModel3D` but now I cannot find how to reapply the materials extracted when traversing through the `HelixToolkitScene.Root` because I am only able to apply 1 material to the newly create `MeshGeometryModel3D`.

Is there a way I can also combine the materials extracted then apply that material to the resulting `MeshGeometryModel3D` or is there another way I don't know of?

**Comment by holance** [comment]
You can't merge materials unless you only care about the diffuse color, then you can assign vertex color as diffuse color, then use vertColorBlendingFactor =1 to use vertex color as diffuse color.

**Comment by JuandreG** [comment]
Okay thank you.

So basically if I care about the material I need a model for every instance of a material?

**Comment by holance** [comment]
Yes
