### ISSUE TITLE
sharpdx remove model issue?

### ISSUE THREAD

**Issue by MichaelCHF** [helix-toolkit/helix-toolkit#2001]
when i use sharpdx v2.24,i found i can not remove model immediately.
how can i do? thank you!

![image](https://github.com/helix-toolkit/helix-toolkit/assets/23250857/fdbf175e-7c40-4e73-a054-a027133820c9)

**Comment by holance** [comment]
You can workaround it by calling `Viewport3DX.InvalidateRender()` after removing item.
