### ISSUE TITLE
Animation speed bug after commit of Change animation updater to absolute timestamp based. (#1931)   @holance holance committed on Apr 4

### ISSUE THREAD

**Issue by weihuajiang** [helix-toolkit/helix-toolkit#2008]
after this commit, the speed of animation is very slow. This commit brought a bug into the project

**Comment by holance** [comment]
If animation is slow, you can always increase the speed by multiplying a factor on elapsed time.

**Comment by weihuajiang** [comment]
ok, I just do in that way
