### ISSUE TITLE
Boolean Operations on Mesh Geometries

### ISSUE THREAD

**Issue by nsmela** [helix-toolkit/helix-toolkit#2009]
Would it be feasible to implement this research article in this library?

[Simple and Robust Boolean Operations for Triangulated Surfaces](https://www.mdpi.com/2227-7390/11/12/2713#:~:text=Mesh%20reconstruction%20involves%20employing%20Boolean,reconstruct%20the%20desired%20geometric%20models.)

> Step 1: The first step of the proposed method involves searching for candidate intersected triangle pairs. To optimize computational efficiency, a robust and rapid search algorithm is employed to identify potentially intersected triangles. In this study, we utilize the octree structure [[47](https://www.mdpi.com/2227-7390/11/12/2713#B47-mathematics-11-02713)], which enables efficient location and identification of these candidate pairs.
Step 2: Once the candidate intersected triangle pairs have been identified, the next step is to compute the intersection line for each pair. To achieve this, we adopt the algorithm developed by Möller [[48](https://www.mdpi.com/2227-7390/11/12/2713#B48-mathematics-11-02713)], known for its robustness and efficiency. In scenarios where a large number of triangle pairs require intersection calculations, parallel computation techniques based on OpenMP [[49](https://www.mdpi.com/2227-7390/11/12/2713#B49-mathematics-11-02713)] are implemented to enhance performance.
Step 3: After calculating the intersection lines, the next task is to merge and renumber all vertices, as well as update and clear the meshes. The intersection process generates new vertices, while the intersected triangles undergo re-triangulation. To ensure a valid topology, all vertices are merged and renumbered, and all triangles are updated accordingly. This step guarantees the maintenance of a consistent and accurate mesh representation.
Step 4: The fourth step of the proposed method involves connecting the computed intersection lines into closed or open loops. After computing the intersections for each pair of triangles, a set of discrete edges is obtained. These edges need to be connected to form closed or open-oriented loops. If there is no closed loop present on an intersected surface, it indicates that no closed block bounded by triangular facets will be formed.
Step 5: The next step is to obtain sub-surfaces based on the closed loops. A sub-surface comprises the closed loop and all of its incident triangles. The edges of a closed loop are designated as the advancing front, and a new surface is “grown” based on the topology until the number of faces in the sub-surface ceases to increase.
Step 6: Finally, the method proceeds to assemble and distinguish sub-blocks. Sub-blocks can be easily created by assembling related sub-surfaces. Additionally, the boundary closed loops generated in Step 4 can be utilized to represent sub-surfaces. Assembling and distinguishing operations are performed based on these boundary-closed loops.

Or is there already a better option to use boolean operations in Helix Toolkit?

**Comment by holance** [comment]
Helix toolkit is more for visualization. If you need advanced meshing operation, there are other libraries available. Or you can implement it yourself and welcome to contribute to the project.

**Comment by nsmela** [comment]
Sounds good. Which libraries are recommended? I've tried a few, but none have been effective. My best results were from geometry3sharp, but it does it through marching cubes.

**Comment by holance** [comment]
Probably you may want to consider some c++ library like mesh lab.
