### ISSUE TITLE
ViewPort crashes if child elements have a NULL transform

### ISSUE THREAD

**Issue by 0x53A** [helix-toolkit/helix-toolkit#201]
NuGetPackage HelixToolkit.Wpf Version 2015.1.593

==============

I am currently trying to create a viewer for a simple geometry file format.
The loading kind of works (I messed up something with the transforms, all elements are over each other).

I can zoom / pan, etc normally.

If I wildly click inside the viewport (left mouse button and/or middle mouse button), it crashes hard.

==========

An unhandled exception of type 'System.ArgumentException' occurred in PresentationCore.dll
Additional information: Der Wert NULL kann der Auflistung nicht hinzugefügt werden. 	

===========
Edit: the callstack was incomplete, please see second post.

**Comment by objorke** [comment]
This line? https://github.com/helix-toolkit/helix-toolkit/blob/master/Source/HelixToolkit.Wpf/Helpers/Viewport3DHelper.cs#L362

Please include details about how to reproduce the error here. Can you also reproduce with one of the example applications?

**Comment by 0x53A** [comment]
@objorke  yes exactly.
I haven't been able to reproduce it with a sample application.

===================

I think I found what I did wrong.

I was setting GeometryModel3D.Transform to either null or a value.
It stopped crashing when i changed that to only either set it to a value or let it keep it's default value (default is a MatrixTransform with Identity-Matrix).

====
Also, my original callstack was incomplete, because of a try-catch.
After enabling break on first-chance, the debugger stopped at
Transform3DHelper (https://github.com/helix-toolkit/helix-toolkit/blob/fc1ed36bd706665f7cca7b8fb865e75596963502/Source/HelixToolkit.Wpf/Helpers/Transform3DHelper.cs) line 34.

If null is an invalid value for Transform, then this is my mistake and should be closed.
If null is a valid value, then a null-check could be added to Transform3DHelper.CombineTransform

**Comment by objorke** [comment]
Yes, maybe we should add a null check.
Not sure if it is a valid value, but if it shows up correctly then we should support it.
https://msdn.microsoft.com/en-us/library/system.windows.media.media3d.model3d.transform(v=vs.110).aspx

Thanks for pointing this out.

It should be easy to create a small example to verify this bug.

**Comment by 0x53A** [comment]
I have created a repro at https://github.com/0x53A/helix-crash

**Comment by yauron** [comment]
(maybe not the same but...) by running xBim.xplorer (it use HelixTollkit.wpf), i manipulate a kind of sphere that void visual objects to cut them down in a plan, and this happend :  
- a HelixToolkit.Wpf.Visual3DHelper.GetTransform(Visual3D visual) dans C:\projects\helix-toolkit\Source\HelixToolkit.Wpf\Helpers\Visual3DHelper.cs:ligne 169
