### ISSUE TITLE
Questions on working with PointCloud scene in SharpDX

### ISSUE THREAD

**Issue by Vince0911** [helix-toolkit/helix-toolkit#2010]
hi, I am using Wpf.SharpDX  to test some application on point cloud, with e.g. load and visualization, intersection operation.and I have two questions in this process.
1.  Visualizaition performance:  
here I have two .ply files which has 2 million and 7 million points. and I got 40 fps with 2 million points, and 10 fps with 7 million points scene. so I want to know if there is some techniques to impove visual performance when I got massive amount of point clous.
Codes is pretty simple , in xmal, a PointGeometryModel3D object  is binding with parse data in back-end

2.  PointCloud intersection and TransformManipulator3D
I am trying to get all points inside a box, and this box is manipulated by user with TransformManipulator3D, 
normally I can go over all points to check if its xyz is within box to get target points ,but I think this is low efficent, is there any high efficent way to do it in libary？
and for TransformManipulator3D, its target binding with  box, and yet can manipulator pose/size of box, and here I want TransformManipulator3D pose is transfoming same way with box(size no change) ,this is more intuitive when user work on this.I try to binding TransformManipulator3D `s transform with box transform, but failed. is any way to do this.

**Comment by Vince0911** [comment]
@holance  Hi, here is my reply.
1.  Do all points belong to single PointGeometry3D?  --Yes, I load a ply file, and I load all points to a single PointGeometry3D object,and thanks for your hint, later I will test the performance that a ply file points data into serval PointGeometry3D objects.
What's your GPU model for testing?  --it`s Nvidia Quadro T1000 4GB for laptop , sample had sent via mail.
2. Are you trying to resize a portion of points inside the box? -- I am trying to get all the points inside the box(it`s like cut some points out of the box)
here is origin point cloud

![orginPointCloud](https://github.com/helix-toolkit/helix-toolkit/assets/122248896/d59676bc-e1a6-4b4b-8e56-9408ec10cc6f)

then I add a Box in scene, and to obtain all the points in it

![PointCloudwithBox](https://github.com/helix-toolkit/helix-toolkit/assets/122248896/865a1d47-2a13-4720-a809-864e5ae9ec47)

3. about manipulator ,I want to manipulator pose keep same with box
at first ,the manipulator is binding with Box,
![orginPose](https://github.com/helix-toolkit/helix-toolkit/assets/122248896/3af7e8be-a7b9-4f00-9163-1e1af3a8d296)
 and when I do some transfrom(e.g. rotate), the box yet is rotated, but manipulator pose keeps still, I want it also rotate with Box

![box_rotate](https://github.com/helix-toolkit/helix-toolkit/assets/122248896/a9a85315-ebfa-436c-b2fb-16c75633a425)

thanks

**Comment by holance** [comment]
If you are using laptop, you need to make sure your app is running with the discrete graphics card, otherwise it runs with the integrated one and that's why you are having performance issue.

**Comment by holance** [comment]
Keeping the manipulator same rotation is difficult., since the current manipulator is designed to accommodate general use-cases, for your special case, you need to create your own manipulator.

**Comment by Vince0911** [comment]
@holance  Hi， For performance issue, I force app to work on discrete card, it performs nice and okay now.
I get a new thing on zooming, apperance is when I use middle key on mouse to zoom in/out , the scene will keep smooth scrolling for a while after I leave midde key.(it`s like scroll a webpage with laptop touchpad, page would keep scrolling even after your fingure left touchpad), so is there any setting in viewport3DX to stop this transition animation.

![GIF Smooth Scrolling](https://github.com/helix-toolkit/helix-toolkit/assets/122248896/c69c3097-afda-4ce6-84f6-a6c4480c5241)

**Comment by holance** [comment]
Set `Viewport3DX.IsInertiaEnabled = false`.
