### ISSUE TITLE
can i get GroupModel3D child euler 

### ISSUE THREAD

**Issue by MichaelCHF** [helix-toolkit/helix-toolkit#2013]
when i transform the groupmodel3d
,can i get child element euler?thanks!
i use  sharpdx

**Comment by holance** [comment]
You can get it from '.SceneNode.TotalModelMatrix'.

**Comment by MichaelCHF** [comment]
thanks for your help!
but how can i get  the correct value?

**Comment by holance** [comment]
Does SceneNode.ComputeTransformMatrix() not work?

**Comment by MichaelCHF** [comment]
I just test all child.SceneNode.ComputeTransformMatrix() to compute total  boundingbox,the result is not correct.
but i test groupmodel3d.SceneNode.ComputeTransformMatrix() first, it fine,  thanks!

**Comment by MichaelCHF** [comment]
I just test all child.SceneNode.ComputeTransformMatrix() to compute total  boundingbox,the result is not correct.
but i test groupmodel3d.SceneNode.ComputeTransformMatrix() first, it fine,  thanks!

**Comment by holance** [comment]
You can use UpdateAllTransformMatrix extension method on root node to update the entire scene.
