### ISSUE TITLE
WinUI TextVisual3D

### ISSUE THREAD

**Issue by onslauth** [helix-toolkit/helix-toolkit#2015]
Currently have a project working and have been using BillboardText3D, however I would like to use TextVisual3D and see that is does not appear to be part of either `HelixToolkit` or `HelixToolkit.WinUI` package.

Is there anyway that this can be done, or is only BillboardText3D supported?

**Comment by holance** [comment]
You can implement your own TextVisual3D, since it's just quad with a text texture.
