### ISSUE TITLE
[HelixToolkit WPF] Some questions about SelectionCommands.

### ISSUE THREAD

**Issue by MauNguyenVan** [helix-toolkit/helix-toolkit#2018]
1. I see this comment at here, why we do not support it, I see that, if we allow it, the logic is not wrong  

`//We do not handle the point selection, unless no models are selected. If no models are selected, we clear the `
`existing selection. `

https://github.com/helix-toolkit/helix-toolkit/blob/90e6d2660010c893cdca8a6994ee9cf91af23faa/Source/HelixToolkit.Wpf.Shared/SelectionCommands/RectangleSelectionCommand.cs#L96-L114

2. If I want to create a Combined Selection command = PointSelectionCommand + RectangleSelectionCommand
I want to implement my class like this. but I see it  is seem not possible cause some method is protected.
How can i do that???

```csharp
    public class CombinedSelectionCommand : SelectionCommand
    {

        private readonly PointSelectionCommand _pointSelectionCommand;
        private readonly RectangleSelectionCommand _rectangleSelectionCommand;

       public RectangleSelectionCommand(Viewport3D viewport, EventHandler<ModelsSelectedEventArgs> modelsSelectedEventHandler, EventHandler<VisualsSelectedEventArgs> visualsSelectedEventHandler)
      : base(viewport, modelsSelectedEventHandler, visualsSelectedEventHandler)
 {
 }
/// Call somes method from  _pointSelectionCommand or _rectangleSelectionCommand but not posible
}
```
I can only use Nuget package from you, have not allow fork and build a custom from this project

**Comment by holance** [comment]
No idea, probably it wanted to distinguish between general mesh vs point models.
