### ISSUE TITLE
PointGeometryModel3D setting Color for every point

### ISSUE THREAD

**Issue by vo1s** [helix-toolkit/helix-toolkit#2021]
Hello, I am new to Helix-toolkit, I want to make it's own color for every point:
```
 public void Add(IEnumerable<SharedTool.Contour.Point3D> positions)
        {
            var colors = new List<Color4>();
            foreach (var point in positions)
            {
                colors.Add(new Color4(point.PointColor.R, point.PointColor.G, point.PointColor.B, point.PointColor.A));
            }

            foreach (var point in positions)
            {
                var element = new PointGeometryModel3D()
                {
                    Geometry = new PointGeometry3D()
                    {
                        Positions = new Vector3Collection(positions.ToVector3Collection()),
                        Colors = new Color4Collection(colors)
                    },
                    
                };
                _transforms.Add(element.Transform);
                Elements.Add(element);
            }
        }
```
Point3d is:
```
 public Point3D(double x, double y, double z, byte intensity, Color colorr)
        {
            X = x;
            Y = y;
            Z = z;
            Intensity = intensity;
            PointColor = colorr;
        }
```

Basically, program going out of memory every time I start it. But if I put one color for every point, everything is fine. Please help.

**Comment by holance** [comment]
You are creating PointGeometryModel3D() for all the points multiple times. Your second foreach loop is redundant.

**Comment by vo1s** [comment]
Okay, thank you. But the way I try to add a color to each point is suitable?

**Comment by holance** [comment]
Set `PointGeometryModel3D.EnableColorBlending = true`.

**Comment by vo1s** [comment]
Still have black points displayed.

**Comment by holance** [comment]
Set `BlendingFactor  = 1`.

**Comment by vo1s** [comment]
I have this logic of creating a point:
```
                    double minNormalizedY = 0.0;
                    double maxNormalizedY = 1.0;
                    double normalizedY = (point.Y - (-35)) / (460.0 - (-35));
                    byte r = (byte)(normalizedY * 255);
                    byte g = 0;
                    byte b = (byte)((1 - normalizedY) * 255);
                    var mainColor = Color.FromArgb(255, r, g, b);
                    result.Add(new SharedTool.Contour.Point3D
                    {
                        X = point.X,
                        Y = point.Y,
                        Z = dZ,
                        Intensity = point.Intensity,
                        PointColor = mainColor
                    });
                }
```
What i am trying to do is creating point cloud with points colored from red to blue depending on how high the point is. So if the points are on top then it should be red, in the middle it should smth between red an blue, and the lowest points will be blue. After setting `EnableColorBlending = false` and `PointGeometryModel3D.Color = White` I get this picture:
![Screenshot_1](https://github.com/helix-toolkit/helix-toolkit/assets/46219207/32f7bc21-4837-4e08-91be-395b4af13889)
The pink color appears. Please help me.

**Comment by holance** [comment]
Could you set a break point to check whether the color values are correct during color generation?

**Comment by vo1s** [comment]
How do i normalize it?
