### ISSUE TITLE
[HelixToolkit.Wpf] billboard support display with custom angle

### ISSUE THREAD

**Issue by MauNguyenVan** [helix-toolkit/helix-toolkit#2026]
Does HelixToolkit.Wpf has any way to display billboard with custom angle.  
 If it is not supported currently, please give me some advice/samples/ideas.   
 I will implement and contribute this feature to this project again.  
 Thanks

![image](https://github.com/helix-toolkit/helix-toolkit/assets/48544354/247f551b-a6b7-4f1d-b6f4-8c2e514cb312)

**Comment by JeremyAnsel** [comment]
Hello,
You can take a look at:
- BillboardTextItem / BillboardTextGroupVisual3D
- SpatialTextItem / TextGroupVisual3D

With SpatialTextItem you can set TextDirection and UpDirection.

With BillboardTextGroupVisual3D, the Content property is a Model3DGroup. The Childen property of the group is a collection of GeometryModel3D. The GeometryModel3D model has a property named Transform. You can define a rotation by setting the Transform property.

**Comment by holance** [comment]
Have you not encountered performance issue with so many lines/billboards in your scene?

**Comment by holance** [comment]
You can play with `textBlock.LayoutTransform = new RotateTransform(90);`

**Comment by holance** [comment]
You probably can try to use another layout container like grid to include the textblock and measure its size, so it resizes itself according to the child size.

**Comment by holance** [comment]
You need to figure out the width and height of the bitmap after rotating.

**Comment by holance** [comment]
From your image, the bitmap size is not correct. The height of the bitmap is too small to render the rotated element.

**Comment by holance** [comment]
You need to figure out the axis aligned bounding box of the rotated element, it's nothing to do with the bitmap. Bitmap can't be rotated

**Comment by holance** [comment]
You need to set the rotation origin of the text block

**Comment by holance** [comment]
Prefer to use layout transform. Set origin to 0.5,0.5

**Comment by holance** [comment]
You're rotating layout, but setting render transform origin, that's why it's not working. You need to set the layout transform origin.

**Comment by holance** [comment]
When rendering things in 3d, you need to make sure the things behind a semi transparent mesh get rendered first. Otherwise depth buffer will ignore the things behind it.

**Comment by holance** [comment]
https://newarteest.wordpress.com/2021/02/26/transparency-with-depth-sorting/
