### ISSUE TITLE
Pan in a single direction WinUI

### ISSUE THREAD

**Issue by giovannapalomba** [helix-toolkit/helix-toolkit#2028]
Hi! Is there a way to limit pan to just one direction? 
I'd like to move my camera only in the X axis, so I should set to zero other coordinates. What event could I catch?

**Comment by holance** [comment]
You can set `UpDownPanSensitivity` or `LeftRightPanSensitivity` to zero for the direction you don't want to pan.

**Comment by giovannapalomba** [comment]
I had already tried it, it doesn't work..

**Comment by holance** [comment]
Currently this feature is not supported.
