### ISSUE TITLE
import model question？Sharpdx

### ISSUE THREAD

**Issue by MichaelCHF** [helix-toolkit/helix-toolkit#2029]
I test Import model use [FiLeLoadDemo]，I Found 2 issues:

1. i found the texture image is not correct
FiLeLoadDemo import:
[3dsmodel.zip](https://github.com/helix-toolkit/helix-toolkit/files/12974598/3dsmodel.zip)

![1697595539542](https://github.com/helix-toolkit/helix-toolkit/assets/23250857/4ea8b92e-a828-423f-9d5d-d7cc606eaccb)

threejs import:
![1697595681414](https://github.com/helix-toolkit/helix-toolkit/assets/23250857/bf390ceb-6158-49a8-b13b-3f57b3aeeef0)

2. after import a obj model，when i zoom out the model，i found the camera is PerspectiveCamera，the model surface have  black shades，
    change to OrthographicCamera work well.

![1697596093687](https://github.com/helix-toolkit/helix-toolkit/assets/23250857/c9e46133-8c89-4094-8b1f-824f21fc23db)

![1697596231483](https://github.com/helix-toolkit/helix-toolkit/assets/23250857/c8e168c8-58f0-4609-97e1-ba59591427e8)

3.when id import obj file, how can i import  the mtl file?

wish your help,thanks!

**Comment by holance** [comment]
For 1, the texture is loaded correctly on my side.
![image](https://github.com/helix-toolkit/helix-toolkit/assets/905577/2bd1e041-33a4-43be-bab8-c0395613872f)

For 2, it is caused by z-fighting. You need to set a reasonable range in perspective camera near field distance and far field distance.

For 3, obj file should contains the mtl file path and mtl files will be loaded automatically.

**Comment by MichaelCHF** [comment]
thank you for your reply!

for 2，how can i got the reasonable range in perspective camera by FarPlaneDistance and NearPlaneDistance，I tried to increase the FarPlaneDistance  = 100000，but it didnot work.
![1697684285937](https://github.com/helix-toolkit/helix-toolkit/assets/23250857/003551b0-8890-4cf7-8817-2ac8e44109f8)
![1697684505710](https://github.com/helix-toolkit/helix-toolkit/assets/23250857/4e92cf17-9d0e-4f02-a2d0-3c771a9de5d7)
[part1.zip](https://github.com/helix-toolkit/helix-toolkit/files/13037198/part1.zip)
[part2.zip](https://github.com/helix-toolkit/helix-toolkit/files/13037203/part2.zip)

Is there a way to import model contains unicode encoding(the filename or file content contains a non-ascii encoding) ?
![1697685094988](https://github.com/helix-toolkit/helix-toolkit/assets/23250857/109c6460-e271-43dd-8e6e-c4f8eb0c8f2e)

**Comment by holance** [comment]
You need to either increase the near field distance or decrease the far field distance, so that the range between near field and far field is less than 1e6.
We are using assimp library for importing models, so not sure whether it supports unicode.

**Comment by MichaelCHF** [comment]
thanks for your help，when i increase the NearPlaneDistance value to 1000，this problem solved.
