### ISSUE TITLE
Render text to texture

### ISSUE THREAD

**Issue by onslauth** [helix-toolkit/helix-toolkit#2031]
Hi,

Is there an example somewhere of rendering text to a texture?

**Comment by holance** [comment]
Do you mean render 2D text to an image?
You can use wpf component directly: https://github.com/helix-toolkit/helix-toolkit/blob/ab525814d5e3cd9408cb19932f0eac59db748dc7/Source/HelixToolkit.Wpf.Shared/Visual3Ds/Text/BillboardTextVisual3D.cs#L330

Or you can use sharpdx: https://github.com/helix-toolkit/helix-toolkit/blob/ab525814d5e3cd9408cb19932f0eac59db748dc7/Source/HelixToolkit.SharpDX.Shared/Extensions/BitmapExtensions.cs#L273

**Comment by holance** [comment]
You can try this extension method: https://github.com/helix-toolkit/helix-toolkit/blob/ab525814d5e3cd9408cb19932f0eac59db748dc7/Source/HelixToolkit.SharpDX.Shared/Extensions/BitmapExtensions.cs#L35
