### ISSUE TITLE
Obj's file .mtl doesn't load when file is stored in a same folder as application.

### ISSUE THREAD

**Issue by Tenchiken80** [helix-toolkit/helix-toolkit#2032]
I traced this issue to a method with `public static string GetFullPath(string basePath, string path) ` signature in file **ObjReader.cs.** 
If `basePath` argument is null or whitespace, this method returns empty string, then method `private void LoadMaterialLib(string mtlFile)` checks if file "" exists, finds that it doesn't, and subsequently ignores .mtl file that lies in the same folder.

**Comment by holance** [comment]
You are welcome to fix the issue and submit the PR.
