### ISSUE TITLE
texture is not displayed when using PhongMaterial

### ISSUE THREAD

**Issue by ShiinaRinne** [helix-toolkit/helix-toolkit#2034]
I am trying to create a material for custom toon shading.
In the first step, I referred to some code in the demo and used `PhongMaterial` to render a model,  but I don't know why the texture won't display. 
May I ask if there are some important configurations missing?

I compared the code in the demo, but I don't have experience in XAML and Windows Forms development. 
I apologize for not being able to identify the issue by myself, and I hope to get your help~

<img src="https://github.com/helix-toolkit/helix-toolkit/assets/45081750/ab0a2b54-a9cd-41ff-94dc-3b6161ddb0cd" height=500 width=500></img>

`ViewPanel.xaml`
```csharp
    <hx:Viewport3DX
            x:Name="view2"
            EnableD2DRendering="False"
            ShowCoordinateSystem="True"
            ShowFrameRate="True"
            ShowCameraInfo="True"
            ShowFrameDetails="True"
            ShowViewCube="True"
            EffectsManager="{Binding SREffectsManager}"
            UseDefaultGestures="True">
            
            <hx:GroupModel3D 
                x:Name="PreviewModel2"
                ItemsSource="{Binding ModelGeometry}"
                >
            </hx:GroupModel3D>
            
            <hx:AmbientLight3D 
                Color="{Binding AmbientLightColor}"/>
            <hx:DirectionalLight3D 
                Color="{Binding DirectionalLightColor}" 
                Direction = "{Binding DirectionalLightDirection}"/>
        </hx:Viewport3DX>
```

`MainViewModel.cs`
```
        public Element3DCollection ModelGeometry { get; private set; }
        public DefaultEffectsManager SREffectsManager { get; set; }
        // ...

            SREffectsManager = new DefaultEffectsManager();
            
            AmbientLightColor = new Color4(0.1f, 0.1f, 0.1f, 1.0f);
            DirectionalLightColor = Color.White;
            DirectionalLightDirection = new Vector3(-2, -5, -2);

                var mesh = new MeshGeometry3D
                {
                    Positions = new Vector3Collection(format_.vertex_list.vertex.Select(x => rotationMatrix.Transform(x.pos).ToVector3())),
                    Indices = new IntCollection(indices),
                    TextureCoordinates = new Vector2Collection(format_.vertex_list.vertex.Select(x => x.uv.ToVector2()))
                };

                PhongMaterial material;
                var textureIndex = format_.material_list.material[i].usually_texture_index;
                  var textureModel = TextureModel.Create(Path.Combine(format_.meta_header.folder, format_.texture_list.texture_file[textureIndex]));
                  material = new PhongMaterial
                  {
                      AmbientColor = Colors.Gray.ToColor4(),
                      DiffuseColor = new Color4(1f, 1f, 1f, 1.0f),
                      SpecularColor = Colors.White.ToColor4(),
                      SpecularShininess = 1f,
                      DiffuseMap = textureModel
                  };
                    
                var model = new MeshGeometryModel3D { Geometry = mesh, Material = material};
                if (ModelGeometry == null)
                {
                    ModelGeometry = new Element3DCollection();
                }

                ModelGeometry.Add(model);

```

**Comment by holance** [comment]
Make sure the model normal is calculated. From your code, I didn't see the normals are assigned.

**Comment by ShiinaRinne** [comment]
```
var mesh = new MeshGeometry3D
{
    Positions = new Vector3Collection(format_.vertex_list.vertex.Select(x => rotationMatrix.Transform(x.pos).ToVector3())),
    Indices = new IntCollection(indices),
    TextureCoordinates = new Vector2Collection(format_.vertex_list.vertex.Select(x => x.uv.ToVector2())),
};
mesh.Normals = MeshGeometryHelper.CalculateNormals(mesh);
Console.WriteLine($"normalCount: {mesh.Normals.Count}");
```
I tried to directly use this function to calculate but get the same result.

![image](https://github.com/helix-toolkit/helix-toolkit/assets/45081750/9154d57c-6e64-4532-9eb1-2c429e3758b0)
![image](https://github.com/helix-toolkit/helix-toolkit/assets/45081750/8df057d2-17bd-4056-992a-fc9c28c33f6d)

**Comment by holance** [comment]
What's the result if you use the FileDemo from the examples?

**Comment by ShiinaRinne** [comment]
Since I am currently using a model with PMX format, it seems that I am unable to directly open it using the 'File Load Demo'
![image](https://github.com/helix-toolkit/helix-toolkit/assets/45081750/b8734467-12db-47d8-8a6f-798b7349b339)

**Comment by holance** [comment]
What's the result if you don't set the diffuse texture? Does the model get rendered as white?

**Comment by ShiinaRinne** [comment]
unfortunately, it is totally black
```
material = new PhongMaterial
{
    DiffuseColor = new Color4(1.0f, 1.0f, 1.0f, 1.0f),
    // DiffuseMap = textureModel,
};
```

![image](https://github.com/helix-toolkit/helix-toolkit/assets/45081750/4600b27c-5d7a-4f05-8b7f-931a2ec69072)


---
if use `DiffuseMaterial`, it will  render correctly
```
DiffuseMaterial diffuseMaterial = new DiffuseMaterial();
diffuseMaterial.DiffuseMap = textureModel;
var model = new MeshGeometryModel3D { Geometry = mesh, Material = diffuseMaterial};
```
![image](https://github.com/helix-toolkit/helix-toolkit/assets/45081750/3a3f634f-2c2e-4744-9d68-b46ae51b0765)

**Comment by holance** [comment]
Feels like some issue with the lighting, will debug the issue.

**Comment by ShiinaRinne** [comment]
https://github.com/ShiinaManatsu/QuickLook.Plugin.HelixViewer
I am expanding on this project to adapt to SharpDX and customize shaders. 
If necessary, I can upload my modified files
But it also needs to download the [Quicklook](https://github.com/QL-Win/QuickLook) project to run
![image](https://github.com/helix-toolkit/helix-toolkit/assets/45081750/3ad39db8-cd75-457c-8166-d37de11a31d6)

**Comment by holance** [comment]
Seems like it is caused by the reflection color. Did you set any reflection color in the phong material?

**Comment by holance** [comment]
Here is the result for the fbx file you provided after correcting the texutre file names and disabling the `RenderEnvironmentMap` in FileLoadDemo line 348. 
![image](https://github.com/helix-toolkit/helix-toolkit/assets/905577/74b0a72d-e147-47b2-8736-1a624e7ab6e4)

**Comment by ShiinaRinne** [comment]
Is it setting `ReflectiveColor `? These are all the parameters I used but still got the same result
```
material = new PhongMaterial
                    {
                        DiffuseMap = textureModel,
                        ReflectiveColor = new Color4(1.0f,0.5f,0.5f,1.0f),
                        SpecularColor = Color4.White,
                        AmbientColor = Color4.White,
                        SpecularShininess = 10f
                    };
```
![image](https://github.com/helix-toolkit/helix-toolkit/assets/45081750/fc56f654-8e00-4071-855f-760c18d46529)


---
> Here is the result for the fbx file you provided after correcting the texutre file names and disabling the `RenderEnvironmentMap` in FileLoadDemo line 348. 

It seems to be an issue with naming in Chinese characters, I will try again later

**Comment by ShiinaRinne** [comment]
It seems `FileLoadDemo` does support PMX models and can be imported correctly
I think I'll need to study the code of this demo later
![image](https://github.com/helix-toolkit/helix-toolkit/assets/45081750/409856cd-ec7b-4762-ab97-391ea098deae)

**Comment by holance** [comment]
Check your directional light binding. Feels like your directional light is not working

**Comment by ShiinaRinne** [comment]
It seems that the binding was successful in Rider. 
Since `ModelGeometry` can be displayed, I think `DirectionalLight` should also be fine
![image](https://github.com/helix-toolkit/helix-toolkit/assets/45081750/06e31420-ea0c-45be-b35d-b4462a3bdfed)

**Comment by holance** [comment]
Did you assign directional light color and direction inside the view model constructor?

**Comment by ShiinaRinne** [comment]
Yes, I have set them at the beginning of the code
```
public MainViewModel(string path)
        {
            SREffectsManager = new DefaultEffectsManager();
            
            AmbientLightColor = new Color4(0.1f, 0.1f, 0.1f, 1.0f);
            DirectionalLightColor = Color.White;
            DirectionalLightDirection = new Vector3(-2, -5, -2);
            
            
            format_ = LoadPmxMaterials(path);
            MeshCreationInfo creation_info = CreateMeshCreationInfoSingle();
...
```

**Comment by holance** [comment]
Are you using sharpdx.wpf or winui package?

**Comment by ShiinaRinne** [comment]
I think I might not have used these two packages
Now I have uploaded the code for this project
https://github.com/ShiinaRinne/QuickLook/blob/mmd-viewer/QuickLook.Plugin/QuickLook.Plugin.HelixPMXViewer/MainViewModel.cs

Mainly in these three files:: `HelixViewerPanel.xaml`, `HelixViewerPanel.xaml.cs`, `MainViewModel.cs`

**Comment by holance** [comment]
Helix toolkit.wpf.sharpdx requires using Media.Color and Vector3D for Model3D bindings. Your view model uses sharpdx.color4 and sharpdx.Vector3D, which is the reason your directional light is not working.

**Comment by ShiinaRinne** [comment]
![image](https://github.com/helix-toolkit/helix-toolkit/assets/45081750/17a1deb6-a29c-49de-aabf-87c9690522c3)
Thank you very much~ Now it displays correctly, although it's quite ugly now.
I'm really sorry for troubling you with such a basic issue for so long XD
