### ISSUE TITLE
GridLinesVisual3D deteriorates ModelVisual3D

### ISSUE THREAD

**Issue by kutay-kiren** [helix-toolkit/helix-toolkit#2036]
When the GridLinesVisual3D is visible, it deteriorates the ModelVisual3D. When I changed the Visibility property to false, it looks normal. You can see the deterioration from the robot arm logo.

![Abb1](https://github.com/helix-toolkit/helix-toolkit/assets/60151867/e97b4ef0-3ddb-4519-bfc1-964dea88bd01)
![Abb2](https://github.com/helix-toolkit/helix-toolkit/assets/60151867/8cbf6962-38cc-4c1d-bfe5-6dfa5788f82c)

**Comment by holance** [comment]
Seems like z fighting. Try to reduce range between near field and far field distances.

**Comment by kutay-kiren** [comment]
Thank you holance, you are great. I changed the values and it works now.
