### ISSUE TITLE
HelixToolkit demo doesn't work

### ISSUE THREAD

**Issue by EdoardoNagliati** [helix-toolkit/helix-toolkit#2038]
Hi everybody, I would like to learn using HelixToolkit for my apps, so I started to cloning the repository and launching the available examples. However I can't understand why I've some problems with the graphics: I attach some screenshot to show you.
I'm using the last version of Visual Studio 22
Thanks in advance.

![image](https://github.com/helix-toolkit/helix-toolkit/assets/132692405/a5bf4383-afc5-4e2c-9438-6aa6ff982567)
![image](https://github.com/helix-toolkit/helix-toolkit/assets/132692405/af2cd183-c9f2-4da2-bf65-569e8f48c3ff)
![image](https://github.com/helix-toolkit/helix-toolkit/assets/132692405/e52545f9-562f-4a4b-9a73-3fbe25fbdf9c)

**Comment by holance** [comment]
Are you using intel arc GPU?

**Comment by holance** [comment]
Graphic issue in helixtoolkit.wpf is caused by driver compatibility issue with direct x 9. It's using wpf 3d rendering, which is not related to Helix toolkit.

**Comment by EdoardoNagliati** [comment]
The problem is bound to my intel iris Xe. I solved following this issue: https://github.com/dotnet/wpf/issues/7076 downloading the last Intel driver
