### ISSUE TITLE
Tag property for Visual3D.

### ISSUE THREAD

**Issue by Tenchiken80** [helix-toolkit/helix-toolkit#2044]
Good day!

Is there a specific (i.e. conceptual) reason for absence of Tag property (akin to WPF's FrameworkElement) in Visual3D class? 
It could be really useful while selecting objects.

It's not a hard thing to implement, obviously, I can do it myself and PR, if it will be desired.

**Comment by holance** [comment]
Welcome a PR. Thanks.

**Comment by Tenchiken80** [comment]
I'm sorry, I found that this is on microsoft's part of the code, and while I find this strange, it is impossible to change from Helix toolkit.

Once again, I'm sorry for taking your time.
