### ISSUE TITLE
BillboardTextVisual3D made bad performance  [Helixtoolkit WPF]

### ISSUE THREAD

**Issue by MauNguyenVan** [helix-toolkit/helix-toolkit#2045]
Using BillboardTextVisual3D made bad performance for app.
I can't create to much BillboardTextVisual3D instances.
How to fix it.

**Comment by holance** [comment]
I believe I mentioned to you few months ago that you will get bad performance if you are using too many billboards/lines. You need use sharpdx if you need better performance. We created sharpdx versions for a reason.

**Comment by holance** [comment]
Wpf 3d rendering engine doesn't support screen spaced rendering such as billboard/ lines. Helix toolkit uses algorithms to generate meshes in realtime to mimic screen space rendering, which are done in CPU. The more billboard/lines, the more CPU costs.
