### ISSUE TITLE
Child node movement By SharpDX

### ISSUE THREAD

**Issue by 666wwx** [helix-toolkit/helix-toolkit#2047]
Can SceneNode be moved? I can't find relevant properties to set. I imported a model using Importer, but I need to move the internal nodes of the model.

**Comment by 666wwx** [comment]
Yes, are there any relevant use cases, such as moving a certain distance in a specific direction? Does it support animations?

**Comment by holance** [comment]
You need to create your own transform matrix and assign to it. There's some functions in Matrix class you can use to create basic transforms.

**Comment by 666wwx** [comment]
Can you provide relevant sample code? I haven't used it before, thank you very much ！

**Comment by 666wwx** [comment]
Modifying the M43 attribute, the node did indeed move, but I had no way to achieve the animation effect .

**Comment by holance** [comment]
You need to create your own animation system to update every frame.

**Comment by 666wwx** [comment]
This is a bit difficult for me. Can you provide relevant code cases? Thank you

**Comment by holance** [comment]
If you are using `Helixtoolkit.Wpf.SharpDX`, you can try to use wpf transform3D animation like this demo: https://github.com/helix-toolkit/helix-toolkit/blob/develop/Source/Examples/WPF.SharpDX/LightingDemo/MainViewModel.cs#L229

Otherwise you have to create your own way. You can hookup the [CompositionTarget.Rendering](https://learn.microsoft.com/en-us/dotnet/api/system.windows.media.compositiontarget.rendering?view=windowsdesktop-7.0) event and update the matrix in each frame.

**Comment by 666wwx** [comment]
I have no problem implementing animation using the method you mentioned for SceneNodeGroupModel3D, but I cannot implement animation on its child node SceneNode and have no attributes to use. I have implemented a simple animation system using Stopwatch, but the situation of blockages is not ideal. I think this scenario is often used, and I haven't found the correct way to use it yet. Thank you very much for your help!!!

**Comment by holance** [comment]
You need to use composition target instead of stop watch.

**Comment by 666wwx** [comment]
I don't understand. Do you have any relevant code cases? Thank you

**Comment by 666wwx** [comment]
If SceneNode can also have the Transform attribute, I think it would be friendly to us

**Comment by holance** [comment]
You can use `Transform3D.Value.ToMatrix()` to get the matrix.

**Comment by 666wwx** [comment]
> DoubleAnimation durationProperty = new DoubleAnimation();
                    TranslateTransform3D translateTransform = new TranslateTransform3D();
                    durationProperty.From = 0;
                    durationProperty.To = 300 * 1;
                    durationProperty.Duration = TimeSpan.FromMilliseconds(5000);
                    Transform3DGroup transform3DGroup = new Transform3DGroup();
                    //Matrix matrix3 = node.ModelMatrix;
                    Matrix3D matrix3 = node.ModelMatrix.ToMatrix3D();
                    Vector3D offset = new Vector3D(matrix3.OffsetX, matrix3.OffsetY, matrix3.OffsetZ);
                    transform3DGroup.Children.Add(new TranslateTransform3D(offset));
                    transform3DGroup.Children.Add(translateTransform);
                    node.ModelMatrix = transform3DGroup.Value.ToMatrix();
                    translateTransform.BeginAnimation(TranslateTransform3D.OffsetZProperty, durationProperty);

**

I tried using this method to achieve animation, but it didn't work.
Can you help me check it? Thank you!

**

**Comment by 666wwx** [comment]
Can the loaded model only move the entire object, and internal child nodes cannot be operated on? If only the ModelMatrix attribute can be used, I think this is unfriendly. Or expose the internal model to us.

**Comment by holance** [comment]
I'm not sure what you mean by internal model. Model hierarch is defined by the model file, Helix toolkit construct the scene graph based on the model file you provided. You can iterate into children of a scene node and transform the child node.

**Comment by 666wwx** [comment]
Sorry, I didn't display the complete code

>   foreach (SceneNode node in StackerModel.SceneNode.Traverse())
            {
                if (node.Name.Equals("2"))
                {
                    DoubleAnimation durationProperty = new DoubleAnimation();
                    TranslateTransform3D translateTransform = new TranslateTransform3D();
                    durationProperty.From = 0;
                    durationProperty.To = 300 * 1;
                    durationProperty.Duration = TimeSpan.FromMilliseconds(5000);
                    Transform3DGroup transform3DGroup = new Transform3DGroup();
                    Matrix3D matrix3 = node.ModelMatrix.ToMatrix3D();
                    Vector3D offset = new Vector3D(matrix3.OffsetX, matrix3.OffsetY, matrix3.OffsetZ);
                    transform3DGroup.Children.Add(new TranslateTransform3D(offset));
                    transform3DGroup.Children.Add(translateTransform);
                    node.ModelMatrix = transform3DGroup.Value.ToMatrix();
                    translateTransform.BeginAnimation(TranslateTransform3D.OffsetZProperty, durationProperty);
                }  }

 I obtained the node I wanted to move by traversing the model object, such as one of the axes of a six axis robot, but this node does not seem to have a Transform attribute, making it very difficult to use the ModelMatrix attribute.

**Comment by holance** [comment]
You can try to use `Transform3D.Changed` event and assign the new value to the `ModelMatrix`.

**Comment by 666wwx** [comment]
Not very ideal

![Stacker](https://github.com/helix-toolkit/helix-toolkit/assets/62783945/36f3ddc2-0870-4520-bce5-6a3aa4ec38f4)

**Comment by 666wwx** [comment]
Using this event is not stable, there is a small chance of success, and it is likely that one will not be able to complete the entire movement. Unable to accurately stay at the target position. If paired with multiple animations, it is not possible, but it is possible in the NOSharpDX version.

**Comment by 666wwx** [comment]
The ideal scenario is to complete the entire movement, but it is not. 
The distance I gave was precise, just reaching the top, but he only moved to the middle.
![图片](https://github.com/helix-toolkit/helix-toolkit/assets/62783945/dc4b0621-01ca-4923-884f-e8a292173fd9)

**Comment by 666wwx** [comment]
Another issue is that adding the AddNode method to the SceneNodeGroupModel3D object does not seem to trigger rendering, but the clear method is acceptable.

**Comment by holance** [comment]
Is your translateTransform created on stack? It may get GC in the middle of the animation.
