### ISSUE TITLE
WinUI app does not stop after main window closes since version 2.24

### ISSUE THREAD

**Issue by AFriendlyGuy** [helix-toolkit/helix-toolkit#2048]
After upgrading from version 2.23 to 2.24 my application does not stop after the user closes the main window. I could reproduce the behaviour with the winui ModelViewer example in this repo.

I think this might relate to https://github.com/microsoft/microsoft-ui-xaml/issues/7193 and is primarily an issue of winui. But since this problem is not solved for more than a year, it would be nice to have a workaround other than sticking to an old version of helix-toolkit.

**Comment by AFriendlyGuy** [comment]
I observed the behaviour with windows app sdk version 1.4.231115000 and 1.2.230217.4. If it is really related to the issue linked above, it should be there since at least 1.1.

**Comment by holance** [comment]
Can you create a sample project for me to debug this issue?

**Comment by holance** [comment]
You need to hookup the window closed event and dispose the viewport3DX. Seems like WinUI doesn't trigger the UI unloaded event while closing the main window, which causes some thread inside viewport3DX not able to exit properly.

**Comment by AFriendlyGuy** [comment]
Calling dispose on the viewport did the trick. Thanks!
