### ISSUE TITLE
 Viewport screen shaking

### ISSUE THREAD

**Issue by 666wwx** [helix-toolkit/helix-toolkit#2049]
###  When I zoom in on the camera, the viewport will experience severe shaking. I don't know if the camera settings are correct.

![Stack](https://github.com/helix-toolkit/helix-toolkit/assets/62783945/d7cadb11-5b05-4a7f-a316-3d95f24b4116)

MyCode:

>  Camera = new OrthographicCamera()
            {
                Position = new System.Windows.Media.Media3D.Point3D(-300, 600, 700),
                LookDirection = new System.Windows.Media.Media3D.Vector3D(0, -0.5, -0.5),
                UpDirection = new System.Windows.Media.Media3D.Vector3D(0, 0, -1),
                FarPlaneDistance = 10000,
                NearPlaneDistance = 0.01,
                Width = 1000
            };

I hope you can help me. Thank you very much !!!

**Comment by holance** [comment]
Try to increase the near plane distance to 0.1 for example and test it again.

**Comment by 666wwx** [comment]
Unable to solve the problem, the shaking amplitude has decreased. But there are still some, and when zoomed in, the viewport cannot pan.

**Comment by holance** [comment]
Try to increate the `Viewport3DX.ZoomDistanceLimitNear` to 1f for example.

**Comment by 666wwx** [comment]
Thank you very much. This is possible.
