### ISSUE TITLE
ObjExporter appears to be broken

### ISSUE THREAD

**Issue by bsee08** [helix-toolkit/helix-toolkit#205]
This is sample code I'm using to test ObjExporter. I get an exception from the stream that the path parameter is null.  Am I misunderstanding how to use the function?

	var modelImporter = new ModelImporter();
	Model3DGroup modelGroup = new Model3DGroup();
	modelGroup.Children.Add(modelImporter.Load(@"C:\Users\bsee\Downloads\simpleExistingModel.obj"));

	ObjExporter exporter = new ObjExporter();
	exporter.ExportNormals = true;

	//Todo: Why is this showing that the stream path is null?
	using (Stream filestream = File.Create(@"C:\Users\bsee\Downloads\exportedModel.obj"))
	{
		exporter.Export(modelGroup, filestream);
	}

**Comment by Preffer** [comment]
I have the same result and has confirmed it is a bug.
Because `ObjExporter.MaterialsFile` will be used to create material file, but lack a default value mechanism, so it will be null by default and throw the exception.

**Comment by objorke** [comment]
I think the current design is that you should specify the MaterialsFile property, and not depend on a default value. Would it be better if the Export method got two streams and the name of the materials file?

**Comment by glasspusher** [comment]
When I wrote an obj exporter plugin for Inventor, I just saved out the .mtl file with the same name as the .obj file.  If you choose to set a default file name, this might be a good way to go.

**Comment by objorke** [comment]
I agree that a default name of the .mtl file is good. But then I think we should require the filename of the obj file to be specified (not get it from a FileStream).

**Comment by Preffer** [comment]
I have update the patch that if it is a `FileStream`, now it is safe to get the filename, or else it will keep the old behavior.

**Comment by objorke** [comment]
I want to move the exporters to portable code at some point, then we cannot use FileStream.
I think the current solution where you specify the name of the materials file in the `ObjExporter` is OK. The unit tests were hiding the exceptions, I am fixing this now.

**Comment by objorke** [comment]
See the updated unit tests.

**Comment by objorke** [comment]
The `MaterialsFile` must be set.
I added a null ref check and the `ObjExporter` now throws an exception if `MaterialsFile` is not set.
