### ISSUE TITLE
SceneNodeGroupModel3D  Re rendering

### ISSUE THREAD

**Issue by 666wwx** [helix-toolkit/helix-toolkit#2050]
Another question is how to make the subset re render if it adds new elements.
I tried to assign a new object to the SceneNodeGroupModel3D property, but a fatal error occurred directly.
![284759728-1c1f6167-0709-427d-8eaa-a1f67201827b](https://github.com/helix-toolkit/helix-toolkit/assets/62783945/ccbff14d-ba44-4a20-a983-3a3e353778db)

**Comment by holance** [comment]
Could you provide the code you used to add the new elements? Are you using different thread to add new elements?

**Comment by 666wwx** [comment]
### It is indeed not in the same thread.  I refer to the sample code, but it would be better if I could use cloning.


>    public void LoadLightModel()
        {
            var syncContext = SynchronizationContext.Current;
            Task.Run(() =>
            {
                var loader = new Importer();
                loader.Configuration.ImportMaterialType = MaterialType.Auto;
                loader.Configuration.GlobalScale = 28f;
                var scene = loader.Load(PINK_LIGHTING_PATH);
                scene.Root.Attach(EffectsManager); 
                scene.Root.UpdateAllTransformMatrix();
                if (scene.Root.TryGetBound(out var bound))
                {
                    syncContext.Post((o) => { ModelBound = bound; }, null);
                }
                if (scene.Root.TryGetCentroid(out var centroid))
                {
                    syncContext.Post((o) => { ModelCentroid = centroid.ToPoint3D(); }, null);
                }
                return scene;
            }).ContinueWith((result) =>
            {
                if (result.IsCompleted)
                {
                    scene2 = result.Result;
                    var oldNode = LightModel.SceneNode.Items.ToArray();
                    Task.Run(() =>
                    {
                        foreach (var node in oldNode)
                        { node.Dispose(); }
                    });
                    if (scene2 != null)
                    {
                        if (scene2.Root != null)
                        {
                            foreach (var node in scene2.Root.Traverse())
                            {
                                if (node is MaterialGeometryNode m)
                                {
                                    if (m.Material is PBRMaterialCore pbr)
                                    {
                                        pbr.RenderEnvironmentMap = RenderEnvironmentMap;
                                    }
                                    else if (m.Material is PhongMaterialCore phong)
                                    {
                                        phong.RenderEnvironmentMap = RenderEnvironmentMap;
                                    }
                                }
                            }
                        }
                        LightModel.AddNode(scene2.Root);
                    }
                }
                else if (result.IsFaulted && result.Exception != null)
                {
                    MessageBox.Show(result.Exception.Message);
                }
            }, TaskScheduler.FromCurrentSynchronizationContext());
            TranslateTransform3D transform3D = shelf1.GetLocButtomTransform(3, 3, new Vector3D(0, 0, 0));
            Matrix matrix = transform3D.ToMatrix();
            scene2.Root.ModelMatrix = matrix;
        }
