### ISSUE TITLE
Proposal: Helix Toolkit v3

### ISSUE THREAD

**Issue by JeremyAnsel** [helix-toolkit/helix-toolkit#2051]
Hello,
Here is a proposal for the next version (3.0) of the Helix Toolkit.
I've rewritten the Source directory.

https://github.com/JeremyAnsel/helix-toolkit/tree/wip_v3

Most projects target net6.0, net48, netstandard2.0 when possible. The Wpf projects target net6.0-windows and net48. The WinUI projects target net6.0-windows10.0.19041.0 (TargetPlatformMinVersion is 10.0.17763.0).

Global properties for the solution are in the Directory.Build.props file.
The documentation uses the docfx tool. It is generated in the Documentation directory. Use build-doc.cmd to build the documentation.
The Examples directory contains the examples for Wpf, Wpf.SharpDX, Wpf.SharpDX.Core, WinUI.SharpDX.

The projects are:
- HelixToolkit
- HelixToolkit.Tests
- HelixToolkit.Assimp
- HelixToolkit.Assimp.Tests
- HelixToolkit.Wpf
- HelixToolkit.Wpf.Tests
- HelixToolkit.Wpf.TDxInput
- HelixToolkit.Wpf.TDxInput.Tests
- HelixToolkit.Native.ShaderBuilder
- HelixToolkit.SharpDX
- HelixToolkit.SharpDX.Tests
- HelixToolkit.SharpDX.Assimp
- HelixToolkit.SharpDX.Assimp.Tests
- HelixToolkit.SharpDX.SharedModel
- HelixToolkit.Wpf.SharpDX
- HelixToolkit.Wpf.SharpDX.Tests
- HelixToolkit.WinUI.SharpDX
- HelixToolkit.WinUI.SharpDX.Tests

Each project is linked to a Tests project. All projects except the test projects are source linked. All projects reference the CommunityToolkit nuget package and the DependencyPropertyGenerator nuget package. The ImplicitUsings and Nullable properties are enabled. The LangVersion is 11.0. The projects reference the PolySharp nuget package to be able to use the latest language features with older runtimes.

The HelixToolkit project contains code which is not dependent on Wpf or SharpDX, like the MeshBuilder. It uses the types defined in the System.Numerics namespace.
The HelixToolkit.Assimp project is currently empty. It can be implemented in the future with code to import meshes from the Assimp toolkit into data structures defined in the HelixToolkit project.
The HelixToolkit.Wpf project contains Wpf related code. It references the HelixToolkit project.
The HelixToolkit.Wpf.TDxInput project contains code from the previous version of the HelixToolkit.Wpf.Input project.
The HelixToolkit.Native.ShaderBuilder project contains all the shaders code used by the SharpDX projects.
The HelixToolkit.SharpDX project contains SharpDX related code. It references the HelixToolkit project.
The HelixToolkit.SharpDX.Assimp project contains Assimp code for SharpDX.
The HelixToolkit.Wpf.SharpDX project contains SharpDX code for WPF.
The HelixToolkit.WinUI.SharpDX project contains SharpDX code for WinUI.
The HelixToolkit.SharpDX.SharedModel project contains code shared between WPF and WinUI.

WPF structure:
```mermaid
graph TD
    hx[HelixToolkit] --> hxWpf[HelixToolkit.Wpf]
    wpf[WPF Framework] --> hxWpf
```

SharpDX structure:
```mermaid
graph TD
    hx[HelixToolkit] --> hxdx[HelixToolkit.SharpDX]
    dx11[DirectX11 Engine] --> hxdx
    hxdx --> hxAssimp[HelixToolkit.SharpDX.Assimp]
    hxdx --> hxWpf[HelixToolkit.Wpf.SharpDX]
    hxdx --> hxWinUI[HelixToolkit.WinUI.SharpDX]
```

**Comment by holance** [comment]
Nice, will take a look next week.

**Comment by holance** [comment]
Merged your branch into https://github.com/helix-toolkit/helix-toolkit/tree/develop3.x. Thanks for contribution.

**Comment by JeremyAnsel** [comment]
Thank you
