### ISSUE TITLE
Clipping on a PointGeometryModel3D object.

### ISSUE THREAD

**Issue by whogoesthere** [helix-toolkit/helix-toolkit#2052]
I have a HelixToolkitDX application which will load a Lightwave OBJ model, creates point cloud(s) given a LIDAR located at a user nominated point and displays the point clouds, loaded model and a LIDAR representation into a WPF window. Everything works really well except for plotting the point clouds on the model. The point clouds disappear (clip) when the user zooms below a given distance however the rest of the scene remains visible. The relevant Viewport3DXpart follows. I've tried numerous permutations of the Near and Far plane distance for the perspective camera with no impact. Would really appreciate some guidance at this point.

           <hx:Viewport3DX DockPanel.Dock="Top"
                x:Name="ViewPort3DX"
                ShowCoordinateSystem="True"
                InfiniteSpin="True"
                EffectsManager="{Binding EffectsManager}"
                EnableSwapChainRendering="True"
                EnableD2DRendering="False"
                FXAALevel="High"
                EnableDeferredRendering="False"
            >
                <hx:Viewport3DX.InputBindings>
                    <KeyBinding Key="B" Command="hx:ViewportCommands.BackView" />
                    <KeyBinding Key="F" Command="hx:ViewportCommands.FrontView" />
                    <KeyBinding Key="U" Command="hx:ViewportCommands.TopView" />
                    <KeyBinding Key="D" Command="hx:ViewportCommands.BottomView" />
                    <KeyBinding Key="L" Command="hx:ViewportCommands.LeftView" />
                    <KeyBinding Key="R" Command="hx:ViewportCommands.RightView" />
                    <KeyBinding  Command="hx:ViewportCommands.ZoomExtents" Gesture="Control+E" />
                    <MouseBinding Command="hx:ViewportCommands.Rotate" Gesture="RightClick" />
                    <MouseBinding Command="hx:ViewportCommands.Zoom" Gesture="MiddleClick" />
                    <MouseBinding Command="hx:ViewportCommands.Pan" Gesture="LeftClick" />
                </hx:Viewport3DX.InputBindings>

                <hx:Viewport3DX.Camera>
                    <hx:PerspectiveCamera
                        Position= "-30, 30,-30"
                        LookDirection="30,-30,30"
                        UpDirection="0,1,0"
                        NearPlaneDistance= "0"
                        FarPlaneDistance="Infinity" 
                        />
                </hx:Viewport3DX.Camera>

                <hx:AmbientLight3D />

                <hx:LineGeometryModel3D
                    Geometry ="{Binding Grid}"
                    Thickness="{Binding GridLineThickness}"
                    Transform="{Binding GridTransform}"
                    Color    ="{Binding GridColor}"
                />

                <hx:Element3DPresenter Content="{Binding GroupModelOrigin}"/>
                <hx:Element3DPresenter Content="{Binding GroupModelLIDAR}" />
                <hx:Element3DPresenter Content="{Binding GroupModelHull}"  />

                <hx:PointGeometryModel3D  
                        Figure="Ellipse"
                        FigureRatio="1"
                        Geometry="{Binding Geometry_Pri}"
                        Size="{Binding LIDAR_PointSize}"
                        Color="Red"
                        />
                
                <hx:PointGeometryModel3D
                        Figure="Ellipse"
                        FigureRatio="1"
                        Geometry="{Binding Geometry_Sec}"
                        Size="{Binding LIDAR_PointSize}"
                        Color="Blue"/>

            </hx:Viewport3DX>

**Comment by holance** [comment]
Not sure how big is your scene, but usually you need to set a reasonable range on near/far plane distance, otherwise may cause floating point errors.

**Comment by whogoesthere** [comment]
Thanks Holance. I've tried every permutation of the near far plane distance I can think of but it has no effect on the problem. The other scene components remain visible but both point Clouds (PointGeometryModel3D) simply disappear when the camera gets too close to them even though one cloud is markedly smaller (dimensionally) than the second cloud.

**Comment by holance** [comment]
Try with 'Viewport3DX.EnableFrustumTest = false'

**Comment by whogoesthere** [comment]
Wow... you're a hero!
There's no property for EnableFrustumTest but I used EnableRenderFrustum="False" in the XAML and its working!
I don't even know what a render frustrum is :-)
