### ISSUE TITLE
Can't use Mouse.GetPosition on Viewport3DX

### ISSUE THREAD

**Issue by MrJox** [helix-toolkit/helix-toolkit#2053]
Hi,

My application is a hexgrid painter. I am trying to implement runtime coordinates output. There is no problem to do that via OnMouseDown or OnMouseUp events, however both require user input (such as pressing a mouse button). Since WPF naturally doesn't support OnMouseOver events, I was trying to implement a workaround. The idea was to create a timer that elapses every second and use Mouse.GetPosition() method to retrieve current mouse position, relative to the Viewport3DX control.

Sadly, this does not work. The moment I hover my cursor over the VIewport3DX control, the mouse coordinates will change to window position, relative to the viewport control origin. I can get it to work by setting EnableSwapChainRenderer = False, however in that case the viewport stops being interactible (cant paint, cant pan, cant zoom) and it has negative performance impact.

Is there any solution to this?

**Comment by MrJox** [comment]
My problem is not performance, I brought it up because I read in Wiki that it's best to avoid rendering anything on top of Viewport3DX as it may have negative performance impact.

My problem is I can't get Mouse.GetPosition(relative to viewport) to yield correct mouse coordinates. Instead, I get window location coordinates, related to the viewport

**Comment by holance** [comment]
Wpf has mouse enter/exit event for its elements, you should be able to use it to determine whether it is mouse over or not. If you didn't experience any performance issues, just disable the swap chain, otherwise will complicate things.

**Comment by MrJox** [comment]
Mouse leave / enter event only triggers once a mouse enters the viewport and once a mouse leaves it. I need to get mouse position for every second a mouse is over the viewport in order to display real-time mouse coordinates in world-space.

I get achieve this result if I disable swap chain rendering, however in that case the viewport becomes non-interactive. Zoom / pan / paint and other other operations stop working when I disable swap chain rendering.

Again, I'm trying to display world-space "pixel" coordinates of a hex on a hexmap that mouse is over at real time.

**Comment by holance** [comment]
I'm not sure why Zoom / pan / paint and other other operations stop working if you disable swap chain rendering. Did you put another layer on top of the viewport? Have you tried wpf mouse move event?

**Comment by holance** [comment]
Then I am not sure why zoom is not working as you mentioned.

**Comment by MrJox** [comment]
Another bug that is rooted to the same problem: MouseLeave and MouseEnter events for Viewport3DX only trigger when user clicks with their mouse on the viewport element. It does not trigger if user simply hovers over the Viewport3DX UI element, without clicking their mouse.

Here's my Viewport settings:

`    <hx:Viewport3DX x:Name="viewport"
                    BackgroundColor="{StaticResource BackgroundDarkV0}"
                    EffectsManager="{Binding EffectsManager}"
                    Camera="{Binding Camera}"
                    UseDefaultGestures="False"
                    ShowViewCube="False"
                    Orthographic="True"
                    EnableSSAO="False"
                    FXAALevel="None"
                    EnableAutoOctreeUpdate="True"
                    EnableRenderFrustum="True"
                    EnableSwapChainRendering="True"
                    EnableD2DRendering="False"
                    EnableMouseButtonHitTest="True"
                    IsRotationEnabled="False"
                    IsThreeFingerPanningEnabled="False"
                    IsTouchRotateEnabled="False"
                    IsChangeFieldOfViewEnabled="False"
                    IsShadowMappingEnabled="False"
                    IsHitTestVisible="False"
                    PreviewMouseDown="Viewport_PreviewMouseDown"
                    MouseMove="Viewport_MouseMove"
                    MouseUp="Viewport_MouseUp"
                    MouseWheel="Viewport_MouseWheel"
                    FrameRateText="{Binding Source={x:Static local:LoggerViewModel.Instance},
                                            Path=FPS,
                                            Mode=TwoWay}">

        <hx:Viewport3DX.InputBindings>
            <MouseBinding Command="{Binding LeftClick}" Gesture="LeftClick"/>
            <MouseBinding Command="hx:ViewportCommands.Zoom" Gesture="MiddleClick"/>
            <MouseBinding Command="hx:ViewportCommands.Pan" Gesture="RightClick"/>
        </hx:Viewport3DX.InputBindings>

        <hx:AmbientLight3D Color="#414141"
                           IsHitTestVisible="False" />
        
        <hx:DirectionalLight3D Direction="-1, -1, 0"
                               IsHitTestVisible="False" />
        
        
        <hx:MeshGeometryModel3D CullMode="Back"
                                IsHitTestVisible="True"
                                Material="{Binding GridOutlineMaterial}"
                                Geometry="{Binding GridOutlineGeometry}" />

    </hx:Viewport3DX>
`

**Comment by MrJox** [comment]
Okay I found the solution.

The problem was in combination of these two settings:

```
                    EnableSwapChainRendering="True"
                    IsHitTestVisible="False"
```

When both settings are removed (or set to default value), the Viewport3DX UI element properly reacts to all mouse events.
