### ISSUE TITLE
Viewport3DX has memory leaks 

### ISSUE THREAD

**Issue by SuperYF-86** [helix-toolkit/helix-toolkit#2060]
Multiple Viewport3DXs sharing a single EffectsManager can improve loading speed, but it can also lead to memory leaks. I'm not sure if this is a bug or if I haven't found the right way to dispose the Viewport3DX?

![%C6Y9K7)X91WBZU_ N413IV](https://github.com/helix-toolkit/helix-toolkit/assets/72618639/1931604e-bcd0-4924-81d6-9acf0f55b552)

Some resources never seem to get cleaned up when sharing EffectsManager.
![~NPW1KAF7UZP{U1Y~VDOKU8](https://github.com/helix-toolkit/helix-toolkit/assets/72618639/e3d40ae8-5dcd-4602-8b1b-f89acee7d5b2)
![2R VGB89%MR@OYFHR46S58S](https://github.com/helix-toolkit/helix-toolkit/assets/72618639/6146de05-99f8-4230-8673-0f609931d6d0)

This is the demo project：
[ViewportMemoryLeakTest.zip](https://github.com/helix-toolkit/helix-toolkit/files/13528297/ViewportMemoryLeakTest.zip)

**Comment by holance** [comment]
Yes, there are some internal caches for things like shaders etc. So as long as the memory is not keeping increment each time you load an new scene, it should be ok.

**Comment by SuperYF-86** [comment]
> Yes, there are some internal caches for things like shaders etc. So as long as the memory is not keeping increment each time you load an new scene, it should be ok.

 
I add a PointNode for each Viewport3DX.
    
![cd](https://github.com/helix-toolkit/helix-toolkit/assets/72618639/e79d17a9-48f0-4511-a666-4a9d5fda9444)

 <hx:Element3DPresenter Content="{Binding Root }" />

![pts_sc](https://github.com/helix-toolkit/helix-toolkit/assets/72618639/f9ca894c-c632-4ba1-ab3e-e241cb975dc9)

It is indeed not possible to release resources correctly when Viewport3DX shares the EffectsManager.

![fine](https://github.com/helix-toolkit/helix-toolkit/assets/72618639/54a8851f-3274-4184-a230-854fa5974d85)

![leak1](https://github.com/helix-toolkit/helix-toolkit/assets/72618639/17c5731e-8451-4042-852c-014a5584b0ad)

![leak2](https://github.com/helix-toolkit/helix-toolkit/assets/72618639/5ec499d9-5dde-4049-8f56-36b2d2a5631f)

demo:
[ViewportMemoryLeakTest.zip](https://github.com/helix-toolkit/helix-toolkit/files/13536969/ViewportMemoryLeakTest.zip)

**Comment by holance** [comment]
I don't see there is any memory leaks. For your tests, you didn't dispose the effects manager after closing all the windows. Like I said, effects manager creates a set of cache automatically to improve performance. It is not memory leak.

Here is the memory usage for the shared effects manager:
![image](https://github.com/helix-toolkit/helix-toolkit/assets/905577/1d201b5f-ad3b-4ea7-98d5-e3f5500da312)
You can see every time you create and close all windows, memory went back to the same level. Of course, it won't be back to the level at the beginning because of the caching. You can dispose the effects manager if you really need to release all resources.

**Comment by SuperYF-86** [comment]
> I don't see there is any memory leaks. For your tests, you didn't dispose the effects manager after closing all the windows. Like I said, effects manager creates a set of cache automatically to improve performance. It is not memory leak.
> 
> Here is the memory usage for the shared effects manager: ![image](https://private-user-images.githubusercontent.com/905577/288066437-1d201b5f-ad3b-4ea7-98d5-e3f5500da312.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MTUzNzksIm5iZiI6MTcwMTgxNTA3OSwicGF0aCI6Ii85MDU1NzcvMjg4MDY2NDM3LTFkMjAxYjVmLWFkM2ItNGVhNy05OGQ1LWUzZjU1MDBkYTMxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNVQyMjI0MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MmVmZGZiODA2NWM2ZjY4NDI5YzE2MzQ3MmYwYjliMDY0ZmRmNTZjMmM4YTYwMDJhOTI4YjA3MDgxYzU5YjgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.S4otScQkW3Aq0O0pGf3yPAasi14HVlCIJiTKIw4lwpY) You can see every time you create and close all windows, memory went back to the same level. Of course, it won't be back to the level at the beginning because of the caching. You can dispose the effects manager if you really need to release all resources.

You're right, it shouldn't be a memory leak. Because memory usage doesn't increase indefinitely.

Viewport3DX seems to follow some kind of lazy pattern. It doesn't actively update unless the rendering interface has changed.

I have observed that when a Viewport3DX Camera has changed, some resources are being freed up quickly.

![res_01](https://github.com/helix-toolkit/helix-toolkit/assets/72618639/eb21e35b-6feb-4a2f-bc2c-cd1c73d8a923)

I guess when I need to actively release resources, I need to make sure that at least one active Viewport3DX exists in the current project, or create a new one. Trigger its internal resource release mechanism by updating its rendering state.

I don't know if this approach is officially recommended, but at least it works for my project.

Anyway thanks for your reply, it helps me a lot.

**Comment by pantosh** [comment]
This file has a worrying comment in the Dispose method:
`Source/HelixToolkit.SharpDX.SharedModel/Element3D/Abstract/Element3DCore.cs`

```
            protected virtual void Dispose(bool disposing)
            {
                if (!disposedValue)
                {
                    if (disposing)
                    {
                        Disposer.RemoveAndDispose(ref sceneNode);
                        // TODO: dispose managed state (managed objects).
                    }

                    // TODO: free unmanaged resources (unmanaged objects) and override a finalizer below.
                    // TODO: set large fields to null.

                    disposedValue = true;
                }
            }
```

**Comment by holance** [comment]
Those comments are auto-generated by intelli-sense when you ask it to generate dispose pattern.

**Comment by pantosh** [comment]
@holance the default effect manager is definitely leaking. Please reopen this issue.

The following graph shows a clear leak after the initial cache initialization jump:
![image](https://github.com/user-attachments/assets/1533f2f4-0e47-4378-980b-e0b8e18e1de2)

```
            var n = 1000;
            for (int i = 0; i < n; i++)
            {
                using var effectManager = new DefaultEffectsManager();
                await Task.Delay(10);
                GC.Collect();
            }
```
