### ISSUE TITLE
Problem with adding SceneNode to SceneNodeGroupModel3D

### ISSUE THREAD

**Issue by 666wwx** [helix-toolkit/helix-toolkit#2065]
![图片](https://github.com/helix-toolkit/helix-toolkit/assets/62783945/6d5ac7ac-3e4c-457e-a15d-2b92f39ff7c7)

**Comment by holance** [comment]
You can't add same node to multiple parents.

**Comment by 666wwx** [comment]
Thank you very much. The issue has been resolved
