### ISSUE TITLE
How does the camera navigate through objects without being obstructed ？

### ISSUE THREAD

**Issue by 666wwx** [helix-toolkit/helix-toolkit#2069]
Can the camera shuttle between objects? When I zoom in and out, it seems to be blocked.

**Comment by holance** [comment]
`Viewport3DX.CameraMode="WalkAround"`

**Comment by 666wwx** [comment]
The rotation of the mouse scroll wheel cannot penetrate objects, does it require moving the camera to do so?

**Comment by 666wwx** [comment]
thank you very much!
