### ISSUE TITLE
Question about sync git commit

### ISSUE THREAD

**Issue by MauNguyenVan** [helix-toolkit/helix-toolkit#2070]
Hello, I have a question.
 As my track for this repo, this library has a plan to update to version 3.0 (if possible) with change in structural code
 I have seen commit it  develop3.x and develop branch.
 
 How do you change the structure code for develop3.x while syncing all commits from develop branch?
 I'm curious about  the way you  can do that
 
 
![image](https://github.com/helix-toolkit/helix-toolkit/assets/48544354/bd9e603d-cf48-41a3-bc0d-2e15d014ea23)

**Comment by holance** [comment]
We probably will manual sync changes between these two branches until v3 is stable. I wouldn't expect too many changes for now.
