### ISSUE TITLE
How to load GLB or GLTF models?

### ISSUE THREAD

**Issue by 666wwx** [helix-toolkit/helix-toolkit#2080]
I encountered an issue while trying to load.

**Comment by 666wwx** [comment]
System "Attempting to read or write to protected memory. This usually indicates that other memory is damaged."

**Comment by holance** [comment]
Please provide the model you are having issues. Feel like the error is coming from assimp lib.

**Comment by 666wwx** [comment]
![图片](https://github.com/helix-toolkit/helix-toolkit/assets/62783945/6de666b5-291c-46c0-93ac-4942ec0db1a0)

**Comment by 666wwx** [comment]
Uploading this model is not supported

**Comment by 666wwx** [comment]
Is there any other way to share with you

**Comment by holance** [comment]
You can drag the file into the comment text box.

**Comment by 666wwx** [comment]
[GoodShelves.zip](https://github.com/helix-toolkit/helix-toolkit/files/13655107/GoodShelves.zip)
Compressed it a bit

**Comment by 666wwx** [comment]
Is Importer still compatible with. net7 ？

**Comment by 666wwx** [comment]
Is there any progress? thank you.

**Comment by holance** [comment]
The error is coming from assimp library, there is nothing we can do about it. I also can't open your model file using windows paint3D as well.
