### ISSUE TITLE
Overlapping lines distortion

### ISSUE THREAD

**Issue by kutay-kiren** [helix-toolkit/helix-toolkit#2096]
I am using HelixToolkit.Wpf package. I want to show trace points. Therefore, I store the points in a Point3DCollection and bind LinesVisual3D to the collection. However, if the lines overlap, it looks distorted. The lines should look orange, but the distorted lines look yellow.

                <h:LinesVisual3D Color="#E37430" Thickness="2">
                    <h:LinesVisual3D.Points>
                        <Binding Path="DataContext.Trace_Points" RelativeSource="{RelativeSource AncestorType={x:Type View:SimView}}"/>
                    </h:LinesVisual3D.Points>
                </h:LinesVisual3D>

On the left side there are overlapping lines, on the right side there is a single line. Is there any way to show overlapping lines without distortion?

![image](https://github.com/helix-toolkit/helix-toolkit/assets/60151867/7d266e76-c800-4c63-b577-e369f2c7333a)

**Comment by holance** [comment]
It's called z-fighting. Overlapping geometries may cause artifacts if they are on same position.

**Comment by kutay-kiren** [comment]
Is there any way to solve this for the same position?

**Comment by holance** [comment]
You can try to use Helixtoolkit SharpDX version with depth bias support.
