### ISSUE TITLE
[V3, SharpDX] The ToMeshGeometry3D method makes extra copies

### ISSUE THREAD

**Issue by JeremyAnsel** [helix-toolkit/helix-toolkit#2103]
| Method                                   | Mean     | Error | Allocated   |
|----------------------------------------- |---------:|------:|------------:|
| SharpDX_ToMeshGeometry3D_TriangleIndices | 228.8 ms |    NA | 313352240 B |
| SharpDX_ToMeshGeometry3D_Indices         | 172.7 ms |    NA |           - |

In `HelixToolkit.SharpDX.MeshGeometry3D` setting the `TriangleIndices` collection creates a new collection:
```cs
    [IgnoreDataMember]
    public IntCollection? TriangleIndices
    {
        get
        {
            return base.Indices;
        }
        set
        {
            base.Indices = ((value == null) ? null : new IntCollection(value));
        }
    }
```
Setting the `Indices` collection in the `Geometry3D` base class doesn't create a new collection.

**Comment by holance** [comment]
Fixed in #2102
