### ISSUE TITLE
[V3] Assign the wrong value in `BoundingBoxExtensions` at Maths.  

### ISSUE THREAD

**Issue by MauNguyenVan** [helix-toolkit/helix-toolkit#2107]
Assign the wrong value in `BoundingBoxExtensions` at Maths.  

https://github.com/helix-toolkit/helix-toolkit/blob/61893737c2e663b2bb7e214772f367d018601606/Source/HelixToolkit.Maths/BoundingBoxExtensions.cs#L45-L46

**Comment by holance** [comment]
> Assign the wrong value in `BoundingBoxExtensions` at Maths.
> 
> https://github.com/helix-toolkit/helix-toolkit/blob/61893737c2e663b2bb7e214772f367d018601606/Source/HelixToolkit.Maths/BoundingBoxExtensions.cs#L45-L46

What do you mean by wrong value?

**Comment by holance** [comment]
> ` public uint Value;` whether should be readonly or get modifier . I'm not sure, It's just a question
> 
> https://github.com/helix-toolkit/helix-toolkit/blob/61893737c2e663b2bb7e214772f367d018601606/Source/HelixToolkit.Maths/Bool32Bit.cs#L8-L11

You can't use setter/getter with struct layout.

**Comment by holance** [comment]
This is the translation of the center of the bounding box
