### ISSUE TITLE
Is it possible to render the content of a Viewport3DX to a bitmap without the parent WPF window containing the Viewport3DX being open or visible?

### ISSUE THREAD

**Issue by whogoesthere** [helix-toolkit/helix-toolkit#2113]

**Comment by holance** [comment]
https://github.com/helix-toolkit/helix-toolkit/tree/develop/Source/Examples/SharpDX.Core/OffScreenRendering

**Comment by whogoesthere** [comment]
I understand this is for SharpDX.Core and I am using WPF.SharpDX. There doesn't appear to be an equivalent in the WPF.SharpDX library?

**Comment by holance** [comment]
You can use same code with Wpf.SharpDX with slightly different namespace.
