### ISSUE TITLE
Unexpected rendering with OITRenderMode = SinglePassWeighted for semi-transparent models with alpha=1

### ISSUE THREAD

**Issue by cleosia** [helix-toolkit/helix-toolkit#2115]
Hello,

I have an app displaying several meshes (instances of MeshGeometryModel3D). The user can use sliders to modify each mesh's transparency independently, between 0 and 100%. Since meshes shapes roughly look like nested half-spheres, and the user can freely move the camera, I use HelixToolkit.Wpf.SharpDX order-independent transparency.

Yet, when I use the SinglePassWeighted mode, I noticed meshes with an alpha value = 1 are actually transparent as soon as IsTransparent=true, as in the screenshot below (inspired from the OrderIndependantTransparentRendering example):

![image](https://github.com/helix-toolkit/helix-toolkit/assets/85127128/b95d50c9-6a99-4ee8-9233-045dd8c10fab)

Of course, this can be bypassed by setting IsTransparent=false when alpha=1, but the rendering is quite different in this case, as shown below (the green surface looks more "shiny"):

![image](https://github.com/helix-toolkit/helix-toolkit/assets/85127128/d5bd7367-796d-4e1c-906e-25236ad0eed1)

Therefore, when the user smoothly increases the alpha value up to 1, there is a sudden "jump" in the rendering. Such "jump" does not occur with OITRenderMode = DepthPeeling (but then I face another issue).

Is this behavior expected? Is there a way to bypass it?
Thanks for your help!

**Comment by holance** [comment]
Single pass is a rough estimate for transparency rendering, so there is no way to fix this issue.

**Comment by cleosia** [comment]
Thanks for your answer. So I will focus on DepthPeeling mode (for which I have a different issue - see #2116).
Thanks.
