### ISSUE TITLE
Additive Rendering

### ISSUE THREAD

**Issue by miccTronic** [helix-toolkit/helix-toolkit#2119]
Hi, I've got a 3D visualization project using HelixToolkit SharpDX Core version.
In my case, I have numberous pre-given textures that are supposed to be translucent, but need to be rendered additively. I.e. they do **not** have an alpha channel, but instead the darker, the more translucent the material is (as is the idea of additive blending). They are mainly lightrays, halos, and this kind of thing.

I found that the DefaultBlendStateDescriptions.AdditiveBlend type in HelixToolkit does exactly that type of blending, and I created a RenderingTechnique (copied from DefaultEffectsManager) that changes the blending mode for the Phong shader (my default material) to this BlendStateDescription.
While this renders the material itself properly, it however also hides (some) geometry behind. I guess this is as expected when I set IsTransparent = False for the node because of the ordering. However, if I set IsTransparent = True, it no longer does the alpha blending (I am using OITMode = SimpleWeighted for the viewport). I assume that for the OIT pipeline to work with this other blend mode, I need to change more than the blend mode for the phong shader (DefaultPassNames.Default). I saw that OIT uses 1-2 other shader passes, with their own blend modes (with multiple render targets), but I have no idea how I would need to adjust those.

So the general question is: how can I make translucent (OIT) rendering work with additive (or any other) blend mode? Without OIT, additive rendering is quite useless.

Thanks for any hints you can give.

**Comment by holance** [comment]
You need to disable the depth test by setting depth stencil description to `DSSNoDepthNoStencil`.

**Comment by miccTronic** [comment]
Thanks a lot holance, that works perfectly for me! :-)
