### ISSUE TITLE
V3 HelixToolkit.Geometry namespace is not consistency

### ISSUE THREAD

**Issue by MauNguyenVan** [helix-toolkit/helix-toolkit#2128]
I see in V3 [HelixToolkit.Geometry](https://github.com/helix-toolkit/helix-toolkit/tree/develop3/Source/HelixToolkit.Geometry)
namespace is not consistency some classes use `﻿namespace HelixToolkit;` some others use `﻿namespace HelixToolkit.Geometry;`.
So what namespase do you intend to set for HelixToolkit.Geometry project. I want to  change it but not sure your idea

https://github.com/helix-toolkit/helix-toolkit/blob/c4cfeba391efac210bf481d250865cb5b6a9fa8a/Source/HelixToolkit.Geometry/Geometry/MeshFaces.cs#L1-L8

https://github.com/helix-toolkit/helix-toolkit/blob/c4cfeba391efac210bf481d250865cb5b6a9fa8a/Source/HelixToolkit.Geometry/Geometry/MeshSimplification.cs#L1-L11  

https://github.com/helix-toolkit/helix-toolkit/blob/c4cfeba391efac210bf481d250865cb5b6a9fa8a/Source/HelixToolkit.Geometry/Geometry/MeshGeometry3D.cs#L1-L8  

https://github.com/helix-toolkit/helix-toolkit/blob/c4cfeba391efac210bf481d250865cb5b6a9fa8a/Source/HelixToolkit.Geometry/Geometry/PolygonEdge.cs#L1-L7

**Comment by holance** [comment]
Change to HelixToolkit.Geometry.

**Comment by holance** [comment]
SharpDX project is ok for now.
