### ISSUE TITLE
Helixtoolkit.WPF V3, Panning  does not working well when zoom-in in  Viewport3D 

### ISSUE THREAD

**Issue by MauNguyenVan** [helix-toolkit/helix-toolkit#2140]
I see in Hippo Wpf example, panning does not work when i zoom-in, 
in develop-branch is working well, but v3 is not.
Could you help me resolve it.
See my record in V3.

https://github.com/helix-toolkit/helix-toolkit/assets/48544354/57d486e4-6e0e-4bc9-83ea-941cd359d9e8

**Comment by holance** [comment]
You need to set a limit to disallow zooming near camera target.

**Comment by holance** [comment]
In V2, the ray plane intersection calculation is wrong.

**Comment by holance** [comment]
You can create a line intersect plane function instead of using ray intersect plane if you want the old way.
