### ISSUE TITLE
Helixtoolkit.WPF V3, zomming does not working well when zoom-in in Viewport3D of Building Example

### ISSUE THREAD

**Issue by MauNguyenVan** [helix-toolkit/helix-toolkit#2147]
In Building Example, camera zooming does not work well (shaking and zoom to an other position)when zoom-in to near max in Viewport3D of 
When zoom-in to near max, the Viewport3D becomes shaking. and still not panning.  
### Illustrate
https://github.com/helix-toolkit/helix-toolkit/assets/48544354/c1afd887-232d-4c93-9b0e-6713e8db9e94    

Thank you.  

### Reproduce.  

https://github.com/helix-toolkit/helix-toolkit/assets/48544354/858c4abe-610d-4446-b071-20a73bcc3eb9

For panning bugs.

https://github.com/helix-toolkit/helix-toolkit/assets/48544354/f6d6822c-3e20-4631-ba3d-16eda32f98c7

**Comment by holance** [comment]
You will need to fix the bug yourself. I don't plan to spend time on fixing bugs in wpf package anymore. Basically the bug is caused by camera position too close to the camera target.

**Comment by holance** [comment]
Shaking is caused by the camera position too close to the target, and causes floating point errors. You will need to limit how close camera can zoom in when near the camera position.
