### ISSUE TITLE
Issue with FrameDetails not being shown in Viewport3DX in WinUI3

### ISSUE THREAD

**Issue by JIHOON-OHH** [helix-toolkit/helix-toolkit#2150]
Even if you set the value to True to check FrameDetail in WinUI3, it is not displayed on the page.

**Comment by holance** [comment]
You can get the details from Viewport3dx.RenderDetailOutput string property.

**Comment by JIHOON-OHH** [comment]
Thank you for your reply! If you don't mind, could you briefly give me some example code?

**Comment by JIHOON-OHH** [comment]
> You can get the details from Viewport3dx.RenderDetailOutput string property and display it with your own code.

Thank you for your reply! If you don't mind, could you briefly give me some example code?
