### ISSUE TITLE
3D Models Light Reflection

### ISSUE THREAD

**Issue by JIHOON-OHH** [helix-toolkit/helix-toolkit#2151]
I would like to remove lighting reflection from a 3D model imported using the Importer.

Is there a way to prevent the lighting from reflecting?

**Comment by holance** [comment]
You can set all material to be diffuse material and enable unlit property.
```
                        foreach (var node in scene.Root.Traverse())
                        {
                            if (node is MaterialGeometryNode m)
                            {
                                
                                if (m.Material is PBRMaterialCore pbr)
                                {
                                    var diffuse = new DiffuseMaterialCore() { EnableUnLit = true };
                                    diffuse.DiffuseColor = pbr.AlbedoColor;          
                                    m.Material = diffuse;
                                }
                                else if (m.Material is PhongMaterialCore phong)
                                {
                                    var diffuse = new DiffuseMaterialCore() { EnableUnLit = true };
                                    diffuse.DiffuseColor = phong.DiffuseColor;
                                    m.Material = diffuse;
                                }
                                else if (m.Material is DiffuseMaterialCore diffuse)
                                {
                                    diffuse.EnableUnLit = true;
                                }
                            }
                        }
```

**Comment by JIHOON-OHH** [comment]
> 모든 재료를 확산 재료로 설정하고 조명 없음 속성을 활성화할 수 있습니다.
> 
> ```
>                         foreach (var node in scene.Root.Traverse())
>                         {
>                             if (node is MaterialGeometryNode m)
>                             {
>                                 
>                                 if (m.Material is PBRMaterialCore pbr)
>                                 {
>                                     var diffuse = new DiffuseMaterialCore() { EnableUnLit = true };
>                                     diffuse.DiffuseColor = pbr.AlbedoColor;          
>                                     m.Material = diffuse;
>                                 }
>                                 else if (m.Material is PhongMaterialCore phong)
>                                 {
>                                     var diffuse = new DiffuseMaterialCore() { EnableUnLit = true };
>                                     diffuse.DiffuseColor = phong.DiffuseColor;
>                                     m.Material = diffuse;
>                                 }
>                                 else if (m.Material is DiffuseMaterialCore diffuse)
>                                 {
>                                     diffuse.EnableUnLit = true;
>                                 }
>                             }
>                         }
> ```

If there is a texture applied to the model, is it possible to remove the light reflection of the texture through code?

**Comment by holance** [comment]
You can set the texture to the new material.
