### ISSUE TITLE
.NET 8 compatibility

### ISSUE THREAD

**Issue by giovannapalomba** [helix-toolkit/helix-toolkit#2166]
Hi, 
I'm thinking about upgrading my WinUI project from .NET 6 to .NET 8. Is Helix ready yet to upgrade?

**Comment by ArieRiezebos** [comment]
I think so, I'm running Helix without any problems on .NET 8 (sharpdx/wpf and traditional wpf). I think most (all?) .NET Core versions are backwards compatible anyway.
