### ISSUE TITLE
HelixToolkit v3 load failure with an Exception System.Windows.Markup.XamlParseException in ExampleBrowser 

### ISSUE THREAD

**Issue by MauNguyenVan** [helix-toolkit/helix-toolkit#2174]
### Reproduce:
- Open ExampleBrowser (Examples\Wpf.SharpDX\ExampleBrowser)
- Select `Issue 1044` `Issue 1048 and 1052` `Issue 1047-1`  `Issue 1047-1`

### Result
- Expect result: Load successful
- Actual result: Load failure with throw an exception `System.Windows.Markup.XamlParseException: `    
And I guess in other places have the same error related to `System.Windows.Markup.XamlParseException`
![devenv_8w346iLmEg](https://github.com/helix-toolkit/helix-toolkit/assets/48544354/fce55117-c773-45d6-b5c5-917730b9f750)

**Comment by JeremyAnsel** [comment]
Hello,
This exception happens because the `TypeConverter` attribute was removed on the collection classes in #2084 .
