### ISSUE TITLE
Now I am rendering thousands of shelves, with products on each layer, and the rendering process is quite slow. How should I optimize it?

### ISSUE THREAD

**Issue by zhw1992** [helix-toolkit/helix-toolkit#2176]

**Comment by holance** [comment]
Try to use instancing as much as possible to reduce draw calls. Use lightweight materials such as diffuse material if you don't need realistic lighting.

**Comment by zhw1992** [comment]
@holance 
Could you please provide a demo that reduces the number of drawing calls?

**Comment by zhw1992** [comment]
@holance

**Comment by holance** [comment]
Only available in SharpDX version
