### ISSUE TITLE
How to create shape from given a path and section.

### ISSUE THREAD

**Issue by MauNguyenVan** [helix-toolkit/helix-toolkit#2182]
Does helix have any way to create a shape from a given path and  profile (section)   

![image](https://github.com/helix-toolkit/helix-toolkit/assets/48544354/b7a35ff1-9dba-434a-8110-8c6c8372918a)

**Comment by holance** [comment]
https://github.com/helix-toolkit/helix-toolkit/blob/c0403ec86ac405d1cb89dc2e99da5323ed8ee227/Source/HelixToolkit.Geometry/Geometry/MeshBuilder.cs#L3514

Is this what you want?
