### ISSUE TITLE
MeshBuilder.AddRectangularMesh(BoxFaces plane,...) the parameter `plane` was never used.

### ISSUE THREAD

**Issue by MauNguyenVan** [helix-toolkit/helix-toolkit#2183]
MeshBuilder with `public void AddRectangularMesh(BoxFaces plane,...)`
the parameter `plane` was never used.

 Do we have missing any logic related to this function?

in develop3   
https://github.com/helix-toolkit/helix-toolkit/blob/c0403ec86ac405d1cb89dc2e99da5323ed8ee227/Source/HelixToolkit.Geometry/Geometry/MeshBuilder.cs#L2354

in develop   
https://github.com/helix-toolkit/helix-toolkit/blob/c096f11be2958d328a2f56340246ae0eb61b0106/Source/HelixToolkit.Shared/Geometry/MeshBuilder.cs#L2538C49-L2538C54

**Comment by holance** [comment]
You can remove it. Seems redundant.
