### ISSUE TITLE
WPF app hangs on closing versions 2.24 and 2.25

### ISSUE THREAD

**Issue by sjc9999** [helix-toolkit/helix-toolkit#2185]
I'm running in the following environment:
WPF .net 6 or 8
DevExpress.Wpf 22.2.3 or 23.2.5
HelixToolkit.dll
HelixToolkit.SharpDX.Core.dll
HelixToolkit.SharpDX.Core.Wpf.dll

When I use HelixToolkit version 2.23 the application closes normally.
When I use HelixToolkit version 2.24 or 2.25 the application hangs in an endless loop when closing with the following call stack (.net 6):

System.Private.CoreLib.dll!System.Threading.WaitHandle.WaitOneNoCheck(int millisecondsTimeout) Line 141	
System.Private.CoreLib.dll!System.Threading.WaitHandle.WaitOne(int millisecondsTimeout) Line 129	
System.Private.CoreLib.dll!System.Diagnostics.Tracing.CounterGroup.PollForValues() Line 231	
System.Private.CoreLib.dll!System.Threading.Thread.StartCallback() Line 390

Any ideas what the problem is?

**Comment by holance** [comment]
Try to call Viewport3DX.dispose in app closing event.

**Comment by sjc9999** [comment]
worked thanks
