### ISSUE TITLE
Wrong logic in HelixToolkit.MeshBuilder.GetCircle

### ISSUE THREAD

**Issue by MauNguyenVan** [helix-toolkit/helix-toolkit#2186]
### V2 and V3:  

https://github.com/helix-toolkit/helix-toolkit/blob/c096f11be2958d328a2f56340246ae0eb61b0106/Source/HelixToolkit.Shared/Geometry/MeshBuilder.cs#L453-L467

https://github.com/helix-toolkit/helix-toolkit/blob/c096f11be2958d328a2f56340246ae0eb61b0106/Source/HelixToolkit.Shared/Geometry/MeshBuilder.cs#L467-L500

As my understand: 
1. the comment and logic are opposite ` /// If true, the last point will not be at the same position than the first one. `
2. Logic in (below), when `closed =true` it allway return lacking an value (due to device by num) and  redundant an edge
```cs
         var num = closed ? thetaDiv : thetaDiv - 1; 
         for (var i = 0; i < thetaDiv; i++) /// should be num+1 Note: circle device by thetaDiv means it has n Edge or n+1 point. But here, allways has n point. 
         { 
             var theta = (DoubleOrSingle)Math.PI * 2 * ((DoubleOrSingle)i / num); // should be device by thetaDiv  in stead of num
```
3. I have no idea what case i will use `closed =true`. I think it is redundant

**Comment by holance** [comment]
There are several places uses `closed=true`, like https://github.com/helix-toolkit/helix-toolkit/blob/c096f11be2958d328a2f56340246ae0eb61b0106/Source/HelixToolkit.Shared/Geometry/MeshBuilder.cs#L1211
and https://github.com/helix-toolkit/helix-toolkit/blob/c096f11be2958d328a2f56340246ae0eb61b0106/Source/HelixToolkit.Shared/Geometry/MeshBuilder.cs#L3116

**Comment by holance** [comment]
Probably we can change `closed` to `opened`.
