### ISSUE TITLE
Draw Lines

### ISSUE THREAD

**Issue by vinicius121** [helix-toolkit/helix-toolkit#2190]
### 
   HelixToolkit.WPF.SharpDX
   
   
I'm trying add lines to the point cloud (the normals). I'm reading the point cloud data from a .ply file with the following format:
(x, y, z, nx, ny, nz)
```
9.147512e+01 -3.246689e+02 5.622181e+00 6.800402e-03 -2.303728e-01 9.730787e-01
9.370869e+01 -3.246543e+02 5.559606e+00 1.640028e-02 -2.521703e-01 9.675439e-01
9.640428e+01 -3.246372e+02 5.541724e+00 1.540117e-02 -2.571268e-01 9.662549e-01
```
First I add to the viewport the point cloud model (`viewport.Items.Add(pointGeometryModel);`). Then, to add to the point cloud visualization the lines, I have implemented the following:
```
private void PlotNormals(List<Vector3> points, List<Vector3> normals ) 
{

    // Create LineGeometry3D for normals
    var lineModels = new List<LineGeometryModel3D>();
    for (int i = 0; i < points.Count; i++)
    {
        var startPoint = points[i];
        var endPoint = Vector3.Add(startPoint, normals[i]); // Adjust line length as needed
        //var endPoint2 = new Vector3(startPoint.X + normals[i].X, startPoint.Y + normals[i].Y, (startPoint.Z + normals[i].Z) * (float)1.5);
        var linePoints = new Vector3Collection
        {
            startPoint,
            endPoint
        };
        //LineArrowHeadMaterial
        var lineModel = new LineGeometryModel3D
        {
            Geometry = new LineGeometry3D { Positions = linePoints },
            Thickness = 3.0, // Adjust line thickness as needed
            Color = Colors.Black // Adjust line color as needed
        };
        lineModels.Add(lineModel);
    }

    // Add models to viewport
    //viewport.Items.Add(pointModel);
    foreach (var lineModel in lineModels)
    {
        viewport.Items.Add(lineModel);
    }
}
```

However, the result visualization only shows the point cloud:
![image](https://github.com/helix-toolkit/helix-toolkit/assets/28484866/9b2f4945-08f8-42e4-a681-975cd1207ae0)

What am I missing?

**Comment by holance** [comment]
Line model needs both vertices and line indices. You can set `LineGeometry3D.Positions` to your point cloud and create line indices on `LineGeometry3D.Indices`. Also try to use single `LineGeometry3D` to do contain all the lines you want to render, otherwise you will run into bad performance issue.

**Comment by vinicius121** [comment]
Thanks! It works now.
