### ISSUE TITLE
Disable vsync

### ISSUE THREAD

**Issue by moonway-dev** [helix-toolkit/helix-toolkit#2191]
How to disable vsync in SharpDX viewport?
Any solutions

**Comment by holance** [comment]
Why do you want to disable it?

**Comment by moonway-dev** [comment]
> Why do you want to disable it?

I want to see maximum FPS in busy scenes.
I'm developing a small framework for quickly working on maps for one project.
This feature would be useful

**Comment by moonway-dev** [comment]
> Are you using Sharpdx wpf package?

Yeah

**Comment by holance** [comment]
Wpf package relays on wpf render thread to control the frame rate, there's no way to disable vsync.
