### ISSUE TITLE
[Question]What the best way to show face selection ?

### ISSUE THREAD

**Issue by softinitializing** [helix-toolkit/helix-toolkit#2192]
I want to display the selected Faces when the hittest returns a triangel 
my idea is to Create a MeshGeometryModel3D bound to empty MeshGeometry3D That updates each time a hittest returns something
 ```
` <hx:MeshGeometryModel3D
     x:Name="SSelectedTriangles"
     DepthBias="-10"
     Geometry="{Binding View3DModel.SelectionManeger.SelectedTrianglePolyline,Mode=TwoWay,UpdateSourceTrigger=PropertyChanged}"
     IsHitTestVisible="False"
     IsRendering="{Binding View3DModel.InteractionMode, ConverterParameter={x:Static Include:InteractionMode.Edit}, Converter={StaticResource EnumToBoolConverter}}"
     IsTransparent="True"
     Material="{Binding View3DModel.SelectionManeger.SelectedTriangleMaterial}" />
`
```
```
` private MeshGeometry3D _selectedTrianglePolyline;
 public MeshGeometry3D SelectedTrianglePolyline
 {
     get { return _selectedTrianglePolyline; }
     set { if (SetProperty(ref _selectedTrianglePolyline, value)) { } }
 }
         public void SelectTriangle(MeshGeometry3D geometry, int triangleIndex)
        {
            if (SelectedFaces.Any(x => x.Index == triangleIndex))
                return;

            MeshGeometry3D line = new MeshGeometry3D
            {
                Normals = SelectedTrianglePolyline.Normals,
                TextureCoordinates = SelectedTrianglePolyline.TextureCoordinates,
                Colors = SelectedTrianglePolyline.Colors,
                Positions = SelectedTrianglePolyline.Positions,
                Indices = SelectedTrianglePolyline.Indices
            };

            if (triangleIndex >= 0)
            {
                int i = triangleIndex * 3;
                Vector3 p1,
                    p2,
                    p3;

                int index1 = geometry.Indices[i];
                int index2 = geometry.Indices[i + 1];
                int index3 = geometry.Indices[i + 2];
                SelectedFaces.Add(new Face(index1, index2, index3, triangleIndex));
                p1 = geometry.Positions[index1];
                p2 = geometry.Positions[index2];
                p3 = geometry.Positions[index3];

                if (geometry.Normals != null && geometry.Normals.Count == geometry.Positions.Count)
                {
                    // we can offset the Polyline so it will not be fighting for Z-depth with the object
                    // This way the selection lines will be drawn on top of the selected object
                    Vector3 n1 = geometry.Normals[index1];
                    n1.Normalize();

                    Vector3 n2 = geometry.Normals[index2];
                    n2.Normalize();

                    Vector3 n3 = geometry.Normals[index2];
                    n3.Normalize();

                    p1 += n1 * _selectedTriangleOffset;
                    p2 += n2 * _selectedTriangleOffset;
                    p3 += n3 * _selectedTriangleOffset;
                }
              
                AddTriangle(line, p1, p2, p3);
                SelectedTrianglePolyline = line;

                IsVisible = true;
            }
            else
            {
                IsVisible = false;
            }

           
        }
                public void SelectTrianglesExternal(MeshGeometry3D geometry, int[] Indeices)
                {
                //batch selection
}

        
`
```
![Screenshot 2024-04-01 213407](https://github.com/helix-toolkit/helix-toolkit/assets/140674898/c5d2a6c9-e22a-405b-a921-e7ba72a3abbd)

While This works, it doesn't perform well when the mesh has a huge number of primitives 
is there a better way to do this?

**Comment by holance** [comment]
Instead of creating `MeshGeometry3D` every time, use same `MeshGeometry3D` and only update its properties.
You can add new faces into existing `MeshGeometry3D.Positions` or `MeshGeometry3D.Indices`. Then call `MeshGeometry3D.UpdateVertices()` or `MeshGeometry3D.UpdateTriangles()` etc once you done modifying it.

**Comment by softinitializing** [comment]
i tried to use 
` ```
AddTriangle(SelectedTrianglePolyline, p1, p2, p3);//Adds a new Triangle by adding p1,p2,p3 to the positions collection
 SelectedTrianglePolyline.UpdateVertices();
```
`
To update the geometry of the existing MeshGeometry3D  SelectedTrianglePolyline but it didn't work correctly 
the faces appear only when the camera at a certain angle, i am not sure why would this happen i only changed those two lines
![test12](https://github.com/helix-toolkit/helix-toolkit/assets/140674898/1a98904f-57fd-47d3-acfa-00c91fc0c6cd)


- you mean to make a copy of the selected mesh once selected but without indices and update the indices when a selection is made , i will try that .

**Comment by holance** [comment]
Try to move the selection model in xaml after the target model.

**Comment by softinitializing** [comment]
i tried that but still the same 
` <hx:GroupModel3D
     x:Name="Meshes"
     IsHitTestVisible="{Binding ActiveSelectionMode, ConverterParameter={x:Static Include:ObjectSelectionMode.Mesh}, Converter={StaticResource EnumToBoolConverter}}"
     IsRendering="{Binding Preferences.IsShow3dEnabled}"
     RenderOrder="10"
     Visibility="{Binding Preferences.IsShow3dEnabled, Converter={StaticResource BoolToVisibilityConverter}}">
     <hx:ItemsModel3D x:Name="MeshModels" ItemsSource="{Binding MyFlverViewModel.Meshes}">
         <hx:ItemsModel3D.ItemTemplate>
             <DataTemplate DataType="{x:Type Models:MeshNodeViewModel}">
                 <hx:ItemsModel3D>
                     <hx:MeshGeometryModel3D
                         CullMode="{Binding Visualizers.Cull}"
                         DepthBias="-10"
                         Geometry="{Binding Visualizers.Geometry}"
                         IsRendering="{Binding IsVisible}"
                         IsSelected="{Binding IsSelected}"
                         IsThrowingShadow="False"
                         Material="{Binding Visualizers.SurfaceMaterial}"
                         PostEffects="{Binding PostEffects}"
                         RenderWireframe="{Binding Visualizers.RenderWireFrame}"
                         Tag="{Binding}"
                         Transform="{Binding Transform, Mode=TwoWay}"
                         Visibility="{Binding IsVisible, Converter={StaticResource BoolToVisibilityConverter}}"
                         WireframeColor="Black" />
                 </hx:ItemsModel3D>
             </DataTemplate>
         </hx:ItemsModel3D.ItemTemplate>
     </hx:ItemsModel3D>
 </hx:GroupModel3D>
 <hx:MeshGeometryModel3D
     x:Name="SSelectedTriangles"
     DepthBias="-1000"
     Geometry="{Binding View3DModel.SelectionManeger.SelectedTrianglePolyline, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"
     IsHitTestVisible="False"
     IsRendering="{Binding View3DModel.InteractionMode, ConverterParameter={x:Static Include:InteractionMode.Edit}, Converter={StaticResource EnumToBoolConverter}}"
     IsTransparent="True"
     Material="{Binding View3DModel.SelectionManeger.SelectedTriangleMaterial}" />`

**Comment by holance** [comment]
Set IsTransparent=false

**Comment by softinitializing** [comment]
> Set IsTransparent=false

Still the same

**Comment by holance** [comment]
I created this example, and it works fine. What's your camera parameters?

https://github.com/holance/helix-toolkit/tree/develop3-lunci-dev/Source/Examples/WPF.SharpDX/TriangleSelection

**Comment by holance** [comment]
Remove render order as well

**Comment by softinitializing** [comment]
thanks
