### ISSUE TITLE
Applications using Helix-Toolkit.Wpf.SharpDX don't shut down properly

### ISSUE THREAD

**Issue by Colliflower** [helix-toolkit/helix-toolkit#2201]
I found that as soon as I instantiated a window with a Viewport3D in it, the process would remain open after closing the window. I tracked it down to the AsyncActionThread jobThread member. It's not a background thread so the as long as the thread remains active the process won't shutdown. Setting IsBackground to true seems to fix the issue but I'm not sure if there's an intended way to have the thread complete without this change.

**Comment by holance** [comment]
Call Viewport3DX.Dispose in window shutdown event

**Comment by parched** [comment]
@holance I hit this too in a WinUI app. I didn't see Viewport3DX.Dipose called in the samples, is it just omitted for brevity, or did I miss something?

**Comment by holance** [comment]
> @holance I hit this too in a WinUI app. I didn't see Viewport3DX.Dipose called in the samples, is it just omitted for brevity, or did I miss something?

It's omitted in the sample.

**Comment by LyndonGingerich** [comment]
Could these threads be made background threads? Are they supposed to keep the process open?
