### ISSUE TITLE
 use  PostEffectMeshBorderHighlight   zoom delay

### ISSUE THREAD

**Issue by lif-enable** [helix-toolkit/helix-toolkit#2202]
I use PostEffectMeshBorderHighlight   display mesh outline,  meshnode count >1000， There is a significant delay when zoom scene
code
`<hx:Viewport3DX
            Grid.Column="0"
            Grid.Row="0"
            
            x:Name="view1"
            Camera="{Binding Camera}"
            EffectsManager="{Binding EffectsManager}"
            Title="{Binding Title}"
            SubTitle="{Binding SubTitle}"
                InfoForeground="Blue"
              
            ShowCoordinateSystem="True"
         
        
            
            EnableDesignModeRendering="true"
                IsInertiaEnabled="True"
             
            EnableRenderOrder="True"
            EnableMouseButtonHitTest="True"
             IsManipulationEnabled="False"
                ShowCameraInfo="False"
                ShowCameraTarget="False"
           MSAA="Disable" 
                     EnableSwapChainRendering="True"
            FXAALevel="Low" 
            FixedRotationPoint="{Binding ModelCentroid}"
            FixedRotationPointEnabled="True" 
                EnableRenderFrustum="True"
                UseDefaultGestures="False"  
                    >
                   
                    <hx:Viewport3DX.InputBindings>
                        <KeyBinding Key="B" Command="hx:ViewportCommands.BackView" />
                        <KeyBinding Key="F" Command="hx:ViewportCommands.FrontView" />
                        <KeyBinding Key="U" Command="hx:ViewportCommands.TopView" />
                        <KeyBinding Key="D" Command="hx:ViewportCommands.BottomView" />
                        <KeyBinding Key="L" Command="hx:ViewportCommands.LeftView" />
                        <KeyBinding Key="R" Command="hx:ViewportCommands.RightView" />
                        <KeyBinding Command="hx:ViewportCommands.ZoomExtents" Gesture="Control+E" />
                        <MouseBinding Command="hx:ViewportCommands.Rotate" Gesture="RightClick" />
                        <MouseBinding Command="hx:ViewportCommands.Zoom" Gesture="MiddleClick" />
                        <MouseBinding Command="hx:ViewportCommands.Pan" Gesture="LeftClick" />
                    </hx:Viewport3DX.InputBindings>
             
                    <hx:AmbientLight3D Color="White" /> 
             
                    <hx:PostEffectMeshBorderHighlight
                            DrawMode="Separated"
                            
                            EffectName="highlight"
                            IsHitTestVisible="False"   />
                    <hx:PostEffectMeshOutlineBlur
                           
                            NumberOfBlurPass="2"
                            EffectName="blur"
                            IsHitTestVisible="False"   />
                    <hx:Element3DPresenter    Content="{Binding GroupModel}"   >

                    </hx:Element3DPresenter>

                </hx:Viewport3DX>
`

**Comment by holance** [comment]
You need to reduce number of mesh nodes. No sure why you need to highlight so many of them. Could you provide more context of what you are trying to do?

**Comment by lif-enable** [comment]
model is a  machine with shell 、parts 。。。。,and user need click  some inner face to set params 。

**Comment by lif-enable** [comment]
I use material opacity + border help user find face

**Comment by holance** [comment]
What's the graphics card are you using?

**Comment by lif-enable** [comment]
NV T600 Laptop

**Comment by holance** [comment]
Make sure your program is running on the external graphics card.

**Comment by holance** [comment]
Also if you set draw mode to separate, it's gonna be much slower.

**Comment by lif-enable** [comment]
> 此外，如果您将绘制模式设置为分离，则速度会慢得多。



> Make sure your program is running on the external graphics card.

yes,i disabled inter graphics card

**Comment by lif-enable** [comment]
> Also if you set draw mode to separate, it's gonna be much slower.
if I create some groupnode , how to display groupnode border?

**Comment by holance** [comment]
Group border is not supported at this moment.
