### ISSUE TITLE
Subtract overlapping parts of two 3D models

### ISSUE THREAD

**Issue by JIHOON-OHH** [helix-toolkit/helix-toolkit#2204]
Hello, first of all, thank you for providing such a great library. 

I am developing using HelixToolkit.SharpDX.WinUI library in WinUI3 environment.

I would like to obtain a model with the overlapping parts between two 3D models removed. Is there a way to do this?

**Comment by JIHOON-OHH** [comment]
> You need to use other meshing library for this kind of advanced meshing operations.

So, is there a way to draw a polygon with an open interior like a 3D donut shape? Like the picture below

<img width="378" alt="OpenPolygon" src="https://github.com/helix-toolkit/helix-toolkit/assets/67642878/6bcdaf2c-ef98-447d-a008-98a1d5503e16">

**Comment by holance** [comment]
I believe you can just draw some triangles yourself to achieve this.
