### ISSUE TITLE
Compatibility issues of Helixtoolkit.Wpf with .NET 8 (NU1701), discussion on Long-term Support and Migration Strategy 

### ISSUE THREAD

**Issue by sebkraemer** [helix-toolkit/helix-toolkit#2217]
Version: 2.25.0

Package: HelixToolkit.Wpf

Issue: I'm seeking guidance/feedback and community support for migrating HelixToolkit.Wpf to .NET 8.0. The compiler issues the following:
```
warning NU1701: Package 'HelixToolkit.Wpf 2.25.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net8.0-windows7.0'. This package may not be fully compatible with your project.
```

Reproduce Steps:
  1. Create a windows project with target .NET 8.0.
  2. Add Helixtoolkit.Wpf with NuGet as dependency.

I am evaluating the use of Helix-Toolkit and the HelixToolkit.Wpf or possibly SharpDX.Wpf components for an upcoming project. It shall be based on WPF, and I want to start the project based on .net8. I noticed that the existing nuget package is only built for .net framework 4.6.

The initial tests and migration steps for HelixToolkit.Wpf were successful, however I got the aforementioned compiler warning. The successful part is limited to the wpf component only, not  I also encountered significant challenges when trying to update other dependent projects within the same solution, esp. tests and examples projects.  The samples use the `propertytools.wpf` component which is .net framework based and apparently not really maintained any more. Wpf.Input complains with `Cannot add reference 'TDx.TDxInput.dll' to project 'HelixToolkit.Wpf.Input' because their target frameworks are incompatible.`

I'm now wondering if going forward with helixtoolkit solution is an option. I would appreciate any insights, shared experiences, or advice on handling this situation, especially:
- Are there already plans/discussions to migrate the wpf components to .NET8?
- Is there community interest and support for ongoing and future .NET versions?
- Do you know of any compatibility issues with .NET 8.0 that could impact the usage of HelixToolkit.Wpf or SharpDX.Wpf?

Thank you for any guidance you can provide!

**Comment by sebkraemer** [comment]
Apparently, issue #100 already talks about modernizing `HelixToolkit.Wpf.Input`.

**Comment by holance** [comment]
You need to use Helixtoolkit.core.wpf

**Comment by sebkraemer** [comment]
Thank you for the quick reply and sorry for the late feedback. That worked. I was somehow confused by the "core" in the name.
