### ISSUE TITLE
HelixToolkit SharpDX see through material

### ISSUE THREAD

**Issue by KlaskSkovby** [helix-toolkit/helix-toolkit#2232]
I'm using helixtoolkit SharpDX, but i have an issue where i can see some items through the material.

I have added a hitbox, and put this material on it. 

      var transparentMaterial = new PhongMaterial
      {
          DiffuseColor = new Color4(1, 1, 1, 0.5f),
      };

if i look from the front all other object of the same type is invisble but all other objects can be seen.
if i look from the back there is no issue and the objects are seen. 

![2024-06-09 07_49_17](https://github.com/helix-toolkit/helix-toolkit/assets/33638395/d287e8aa-39df-4b06-818a-72b1596ba7d7)

![2024-06-09 07_49_12](https://github.com/helix-toolkit/helix-toolkit/assets/33638395/62ee8511-3c8f-4118-a401-4470c002bf00)

![2024-06-09 07_49_31](https://github.com/helix-toolkit/helix-toolkit/assets/33638395/ecc23e54-e97a-4e34-a43a-a285d9c6ee86)

**Comment by holance** [comment]
You need to make sure transparent objects are rendered after opaque objects. Either set 'IsTransparent=true' in MeshGeometryModel3D to use transparent pass, or move its location after opaque objects if you only have single transparent object.
