### ISSUE TITLE
Problem rotating bones with Wpf.SharpDX

### ISSUE THREAD

**Issue by sdgbdsgudukgdd** [helix-toolkit/helix-toolkit#2235]
I'm currently coding an animation engine and I want to be able to rotate the bones of any given model I import (I'm mostly working with .pmx and .fbx files) but it doesn't seem to be doing anything. It displays the skeleton:

![image](https://github.com/helix-toolkit/helix-toolkit/assets/138142688/0dab1e37-af20-46c7-bebb-2cc7e607e883)

but whenever I click on a bone in it, not only does it not change colors to let you know it has been selected, but it doesn't rotate anything. It does seem to detect the bones and their names but it selects them "wrong"; like I could be clicking on the ear of a model and it will select the spine and claim it is rotating it, but I can't see anything. Thoughts?

Here's the console output:
`Camera adjusted: Position=-3,814697265625E-06;-89,0589065551758;422,181945800781, LookDirection=0;0;-461,878631591797, UpDirection=0;1;0, Width=461,878631591797
Selected bone: spine_01
Rotated bone: spine_01
Rotated bone: spine_01
Rotated bone: spine_01
Rotated bone: spine_01
Rotated bone: spine_01
...ad nauseam`
Here's the relevant part of the code:
`private void HandleMouseDown(object sender, SceneNodeMouseDownArgs e)
        {
            var result = e.HitResult;
            if (result == null)
            {
                Console.WriteLine("HitResult is null");
                return;
            }
        }

        private bool showSkeleton = false;
        public bool ShowSkeleton
        {
            set
            {
                if (SetProperty(ref showSkeleton, value))
                {
                    foreach (var m in skeletonNodes)
                    {
                        m.Visible = value;
                    }
                }
            }
        }

        public void StartAnimation()
        {
            initTimeStamp = Stopwatch.GetTimestamp();
            compositeHelper.Rendering += CompositeHelper_Rendering;
            IsPlaying = true;
        }

        private Bone selectedBone;
        private bool hasSelectedBone;

        public bool HasSelectedBone
        {
            get => hasSelectedBone;
            private set => SetProperty(ref hasSelectedBone, value);
        }

        public void SelectBone(Point mousePosition, Viewport3DX viewport)
        {
            var hitTestResults = viewport.FindHits(mousePosition);
            if (hitTestResults != null && hitTestResults.Count > 0)
            {
                var hitTestResult = hitTestResults[0]; // Select the first hit
                if (hitTestResult.ModelHit is BoneSkinMeshNode boneSkinMeshNode)
                {
                    foreach (var bone in boneSkinMeshNode.Bones)
                    {
                        if (!hasSelectedBone)
                        {
                            selectedBone = bone;
                            hasSelectedBone = true;
                            UpdateBoneVisual(selectedBone);
                            Console.WriteLine($"Selected bone: {selectedBone.Name}");
                            break;
                        }
                    }
                }
            }
        }

        public void RotateSelectedBone(double deltaX, double deltaY)
        {
            if (hasSelectedBone)
            {
                // Apply rotation based on mouse delta
                var transformMatrix = selectedBone.Node.ModelMatrix;
                var rotationY = Matrix.RotationY((float)deltaX * 0.01f); // Adjust rotation speed as needed
                var rotationX = Matrix.RotationX((float)deltaY * 0.01f); // Adjust rotation speed as needed
                selectedBone.Node.ModelMatrix = transformMatrix * rotationY * rotationX;
                selectedBone.Node.UpdateAllTransformMatrix();
                Console.WriteLine($"Rotated bone: {selectedBone.Name}");
            }
        }

        public void ClearBoneSelection()
        {
            if (hasSelectedBone)
            {
                ResetBoneVisual(selectedBone);
                hasSelectedBone = false;
            }
        }

        private void UpdateBoneVisual(Bone bone)
        {
            if (bone.Node is MeshNode meshNode)
            {
                meshNode.WireframeColor = new Color4(1, 0, 0, 1); // Change color to red
            }
        }

        private void ResetBoneVisual(Bone bone)
        {
            if (bone.Node is MeshNode meshNode)
            {
                meshNode.WireframeColor = new Color4(0, 0, 1, 1); // Change color back to blue
            }
        }`

**Comment by holance** [comment]
Please upload a sample project, otherwise it's hard to debug

**Comment by sdgbdsgudukgdd** [comment]
@holance I can't figure out how to push a project to this website so for now all I have is this MEGA link with the entire code: **https://mega.nz/file/d4p0kBrC#NeUnTmpVOJG6vHurQtTs10HRgLpHHk3_c85uQ5_CFAY** Helix code is in Form3.cs and MainViewModel.cs which can be accessed from the main app from Insert > 3D model reference

**Comment by sdgbdsgudukgdd** [comment]
I can't compare bones to null values and I'm not even sure I'd need to directly manipulate the mesh for this one. I'm drawing a blank here

**Comment by holance** [comment]
Any instruction on how to load the model you are trying to manipulate? Could you provide a sample model I can use?

**Comment by holance** [comment]
If you need to find the bone you selected, you need to use hit result triangle index to find corresponding vertex index, then find the bone id associated with the vertex. Then you can properly get the bone you want to manipulate. The bone skeleton mesh doesn't do hit test and it is just visual only. If you want to get hit test from bone skeleton mesh directly, you will need to generate your own skeleton mesh and associate bone id with it.

**Comment by sdgbdsgudukgdd** [comment]
Currently I'm using this mannequin model: https://www.deviantart.com/download/922225539/df92hs3-e130a5ca-2b37-4c4f-86bd-f8a7ea4a1e7f.zip?token=da5ceff4d0a9939760722fbc1fb78dd08f13e78a&ts=1718301791 You have to change the name of the pmx file and the directory it's extracted in to use ASCII english characters, otherwise the program won't recognize it properly

**Comment by sdgbdsgudukgdd** [comment]
Also lemme try to do what you just told me

**Comment by holance** [comment]
It is better to generate the bone skeleton mesh using your own code. You can refer to the skeleton mesh generation code in https://github.com/helix-toolkit/helix-toolkit/blob/6d84cb10c67f05cf4b1fb3c6a0762501ebc489fb/Source/HelixToolkit.SharpDX.Shared/Model/Geometry/BoneSkinnedMeshGeometry3D.cs#L95

**Comment by holance** [comment]
Here is the sample code for select bone, but it is not able to handle the case when vertex has multiple bones associated with it.
```
        public void SelectBone(Point mousePosition, Viewport3DX viewport)
        {
            var hitTestResults = viewport.FindHits(mousePosition);
            if (hitTestResults != null && hitTestResults.Count > 0)
            {
                var hitTestResult = hitTestResults[0]; // Select the first hit
                if (hitTestResult.ModelHit is BoneSkinMeshNode boneSkinMeshNode && hitTestResult.Geometry is BoneSkinnedMeshGeometry3D mesh)
                {
                    var p0 = hitTestResult.TriangleIndices.Item1;
                    var boneIds = new BoneIds[] {mesh.VertexBoneIds[p0], mesh.VertexBoneIds[p0], mesh.VertexBoneIds[p0], mesh.VertexBoneIds[p0] };
                    foreach (var boneId in boneIds)
                    {
                        if (boneId.Bone1 >= 0 && boneId.Weights.X > 0)
                        {
                            if (!hasSelectedBone)
                            {
                                selectedBone = boneSkinMeshNode.Bones[boneId.Bone1];
                                
                                hasSelectedBone = true;
                                UpdateBoneVisual(selectedBone);
                                Console.WriteLine($"Selected bone: {selectedBone.Name}");
                                break;
                            }
                        }
                    }
                }
            }
        }
```
