### ISSUE TITLE
.NET8 version WPF SharpDX Core  [AxisPlaneGridModel3D] does not appear on the screen.

### ISSUE THREAD

**Issue by harangsa79** [helix-toolkit/helix-toolkit#2240]
My development environment is the latest version of Sharpdx Core WPF.
In WPF in .NET 8, AxisPlaneGridModel3D does not appear on the screen even if you set it in the XAML designer and in code behind.
Other than that, everything displays fine on the screen.

ex)
//Xaml designer
< hx:AxisPlaneGridModel3D />

//Code Behind
var axisGrid = new AxisPlaneGridModel3D();
Hx_ViewPort3Dx.Items.Add(axisGrid);

Neither of the two codes above are displayed on the screen.

**Comment by holance** [comment]
Please upload a sample project so we can debug.

**Comment by harangsa79** [comment]
Sorry, but it's very simple.

Create a new .NET 8 WPF project

with nugget package
- CommunityToolkit.Mvvm
- HelixToolkit.SharpDX.Assimp
- HelixToolkit.SharpDX.Core.Wpf
- Microsoft.Extensions.Hosting
-WPF-UI

- System.Net.Http (automatically installed)
- Sysytem.Text.RegularExpresstions (automatically installed)


Install these 5 packages:

In Xaml Designer

< hx:Viewport3DX
 ShowCameraInfo="True"
 ShowCameraTarget="True"
 ShowCoordinateSystem="True"
 ShowFrameDetails="True"
 ShowFrameRate="True"
 ShowTriangleCountInfo="True"
 ShowViewCube="True"
 MSAA="Maximum"

 ZoomExtentsWhenLoaded="True"
 CameraMode="Inspect"
 CameraRotationMode="Trackball"
 Name="Hx_ViewPort3Dx">

 <hx:DirectionalLight3D Color="White" Direction="1, 3, 1" />

 <AxisPlaneGridModel3D />

<hx:Viewport3DX>

That's it.

Of course, in the code behind

 var perCamera = new PerspectiveCamera();
 perCamera.FarPlaneDistance = double.PositiveInfinity;
 perCamera.Position = new WPF.Point3D(0, 0, 0);

 Hx_ViewPort3Dx.Camera = perCamera;

 Hx_ViewPort3Dx.EffectsManager = new DefaultEffectsManager();

I've done all the basic settings.
It can be displayed well by loading it as an external obj file.

However, only 'AxisPlaneGridModel3D' is not displayed on the screen.

As a test, I also created a Tube with MeshBuilder, and it displays well.
Only 'AxisPlaneGridModel3D' does not appear on the screen.

**Comment by harangsa79** [comment]
I'm writing down the additional information I found in hopes that it will be helpful.


After writing this in the code behind:

 AxisPlaneGridModel3D axisPlaneGridModel3D = new AxisPlaneGridModel3D();
 Hx_ViewPort3Dx.Items.Add(axisPlaneGridModel3D);



I set breakpoints with debug in the two methods below, but confirmed that they were not called.

protected override SceneNode OnCreateSceneNode()
{ <- Breakpoint not hit
 return new AxisPlaneGridNode();
}

protected override void AssignDefaultValuesToSceneNode(SceneNode node)
{ <- breakpoint
 base.AssignDefaultValuesToSceneNode(node); Doesn't jam
 var n = node as AxisPlaneGridNode;
 n.AutoSpacing = AutoSpacing;
 n.GridSpacing = (float)GridSpacing;
 n.GridThickness = (float)GridThickness;
 n.FadingFactor = (float)FadingFactor;
 n.PlaneColor = PlaneColor.ToColor4();
 n.GridColor = GridColor.ToColor4();
 n.RenderShadowMap = RenderShadowMap;
 n.UpAxis = UpAxis;
 n.Offset = (float)Offset;
 n.AutoSpacingRate = (float)AutoSpacingRate;
 n.GridPattern = GridPattern;
}

**Comment by harangsa79** [comment]
Identifying the problem is very simple.
Just in case, I wrote the settings I tested at length above.

I did a quick test this morning.

Create a .NET 8 version WPF project
 Just install SharpDX Helix and set the basic settings.

And in Xaml Designer

< hx:Viewport3DX >
           < AxisPlaneGridModel3D />
< /hx:Viewport3DX>

You can check the problem just by creating the code like this.
 Only <AxisPlaneGridModel3D /> is not displayed on the screen.

All other elements are displayed normally.

**Comment by holance** [comment]
It works fine from my test. What's your camera parameter?

**Comment by harangsa79** [comment]
As you said, I think it's a camera issue.

In the xaml code behind:

PerspectiveCamera perspectiveCamera = new PerspectiveCamera();
perspectiveCamera.NearPlaneDistance = 0;
perspectiveCamera.FarPlaneDistance = double.PositiveInfinity;
Hx_Viewpoer3DX.Camera = perspectiveCamera;

I deleted this part and can only see it now.

But is there a problem with this camera settings?

It doesn't seem like there's anything special about it.
Other elements also displayed on the screen without issue.

**Comment by holance** [comment]
Don't set nearplane = 0 and far plane = infinity. It causes floating point error. Try to set them in a reasonable range of your scene size.

**Comment by harangsa79** [comment]
감사합니다.^^
