### ISSUE TITLE
ModelUpDirection in ViewPortCore

### ISSUE THREAD

**Issue by whogoesthere** [helix-toolkit/helix-toolkit#2248]
I've used HelixToolkit.Wpf.SharpDX.ViewPort3DX to create a scene. Everything works as I'd expect. Now I'm trying to use HelixToolkit.Wpf.SharpDX.ViewportCore to implement the same functionality without the having to create a window. 

In my WPF window implementation I use ModelUpDirection="0,0,1" and everything works as I'd expect. However, the ViewPortCore does not have an equivalent property. How do I set  ViewPortCore to reflect the same ViewPort3DX functionality?

**Comment by holance** [comment]
This property is in camera controller, if you are controlling the camera manually, you don't need to use it.
