### ISSUE TITLE
How to adjust color settings with Helix toolkit?

### ISSUE THREAD

**Issue by demirsuleyman** [helix-toolkit/helix-toolkit#2249]
When I read the .obj file, the resulting image is displayed more bright and high contrast than normal, how can I fix this?

![1](https://github.com/helix-toolkit/helix-toolkit/assets/96020421/90eb205e-73fc-4041-91b9-861a6de46d9d)
![2](https://github.com/helix-toolkit/helix-toolkit/assets/96020421/dfa55633-397c-4fac-b094-1d428dde0f66)

The first image I took myself and the second image I took with Windows 3D Viewer, the difference is obvious.

Thank you in advance for your help.
@holance

**Comment by holance** [comment]
What's your lighting setup?

**Comment by demirsuleyman** [comment]
private DirectionalLight sceneLight;
sceneLight = new DirectionalLight(Colors.Gray, new Vector3D(0, -1, 0));
helixViewport.Children.Add(new ModelVisual3D { Content = sceneLight });
lightRotationSlider.ValueChanged += LightRotationSlider_ValueChanged;
private void LightRotationSlider_ValueChanged(object sender, RoutedPropertyChangedEventArgs<double> e)
{
    double angleDegrees = e.NewValue;
    double angleRadians = angleDegrees * Math.PI / 180.0;

    double y = Math.Sin(angleRadians);
    double z = Math.Cos(angleRadians);
    sceneLight.Direction = new Vector3D(-1, y, z);
}

These are all my light settings.

**Comment by demirsuleyman** [comment]
@holance

**Comment by holance** [comment]
Please provide a sample project and the model so I can debug.

**Comment by demirsuleyman** [comment]
Are there any steps to tell me if there is anything I need to change or add in these settings? @holance

**Comment by demirsuleyman** [comment]
@holance

**Comment by holance** [comment]
You can adjust material properties.
