### ISSUE TITLE
Unable to run TessellationDemo

### ISSUE THREAD

**Issue by vedamsudhakar** [helix-toolkit/helix-toolkit#225]
Build the tessellation sample application provided under the following path:
<b>helix-toolkit/Source/Examples/WPF.SharpDX/TessellationDemo/</b>
When I run the application , i did not see any model rendering.  refer screenshot.
![modelmissing](https://cloud.githubusercontent.com/assets/16100107/11500520/b699ca12-9853-11e5-9cab-623c9677782b.jpg)

Tested with RenderPNTriangles  and RenderPNQuads also.
Please help me,

**Comment by objorke** [comment]
I could not reproduce the issue. Did you modify the example with a new combo box?

**Comment by smischke** [comment]
Please try one of the issues in the example browser. It has a better error reporting. 
![hxsdxexception](https://cloud.githubusercontent.com/assets/8622962/11532518/970442e8-9904-11e5-9175-8238a3a19089.png)

Have you installed the DirectX Runtime?
https://download.microsoft.com/download/8/4/A/84A35BF1-DAFE-4AE8-82AF-AD2AE20B6B14/directx_Jun2010_redist.exe

**Comment by vedamsudhakar** [comment]
Actually I am getting index Out of range exception with Quads as default option. So I changed to Triangles as a default Mesh Topology.
@smischke: Yes I am running in Windows 10.

**Comment by vedamsudhakar** [comment]
@objorke : Also  PRECOMPILED_SHADERS is removed from conditional compilation symbols ( <b>HelixToolkit.Wpf.SharpDX<b> project). 
I thinking that tessellation effect is not properly compiling. please help me.

**Comment by vedamsudhakar** [comment]
Hi Stefan Mischke,

I am aware of those kind of exceptions.
but this time it is not giving any exceptions just model rendering is
missed.
In this rotating mouse wheel to zoom in and zoom out , camera info also is
updating.
Please help I need tessellation sample to run.



On Wed, Dec 2, 2015 at 7:37 PM, Stefan Mischke <notifications@github.com>
wrote:

> Please try one of the issues in the example browser. It has a better error
> reporting.
> [image: hxsdxexception]
> <https://cloud.githubusercontent.com/assets/8622962/11532518/970442e8-9904-11e5-9175-8238a3a19089.png>
>
> Have you installed the DirectX Runtime?
>
> https://download.microsoft.com/download/8/4/A/84A35BF1-DAFE-4AE8-82AF-AD2AE20B6B14/directx_Jun2010_redist.exe
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/helix-toolkit/helix-toolkit/issues/225#issuecomment-161305444>
> .
>



-- 
vedam sudhakar

**Comment by vedamsudhakar** [comment]
@objorke : can you please send your running tessellation sample

**Comment by vedamsudhakar** [comment]
Hi I found the rendering problem. 
<code>if (geometry == null)</code> in Attach(IRenderHost host) in PNPatchGeometryModel3D class
it should be <code>if(geometry!=null)</code>

**Comment by objorke** [comment]
Please create a PR if this is something that should be fixed.
