### ISSUE TITLE
HelixToolkit. MeshBuilder is incorrect textureCoordinates 

### ISSUE THREAD

**Issue by MauNguyenVan** [helix-toolkit/helix-toolkit#2254]
I have used MeshBuilder.AddTriangle()  with texture material
https://github.com/helix-toolkit/helix-toolkit/blob/8c9d56d157ceee30a802aa81bbdddc53bd819de6/Source/HelixToolkit.Geometry/Geometry/MeshBuilder.cs#L3221
with:
p0= (0,0,0)  
p1= (1,0,0)  
p2= (0,1,0)  
uv0=(0,0)  
uv1=(1,0)  
uv2=(0,1)   

You can get my reproduced at here   
https://github.com/AEC-Technologies/helix-toolkit/blob/c55326154b867a36043df969ba8ccf72c461a1da/Source/Examples/WPF/ExampleBrowser/Examples/MeshBuilderSample/MainWindow.xaml.cs#L163
IMO, the correct result is displaying the texture normally,   
but acture result is opposite, it seems buggy
![image](https://github.com/user-attachments/assets/4eb61c71-c38a-4b8e-a998-0dcf0ebaf727)

The expect result
![image](https://github.com/user-attachments/assets/0d00c118-38a2-475d-9321-10bd2c4b4565)

@holance , I guest it's wrong in method `MeshBuilder.ToMesh()` because using other  method `MeshBuilder.AddTube` will have the same incorrect result. it is complex, So I do not find out how to fix it

**Comment by holance** [comment]
https://learn.microsoft.com/en-us/windows/win32/direct3d9/texture-coordinates

Please refer to the direct x uv. Seems like you are confused with opengl uv.

**Comment by holance** [comment]
Some doesn't support texture coordinates
