### ISSUE TITLE
How to adjust AxisPlaneGridModel3D width and height in WinUI3?

### ISSUE THREAD

**Issue by JIHOON-OHH** [helix-toolkit/helix-toolkit#2259]
Is there a way to adjust the width and height of an AxisPlaneGridModel3D?

I tried changing the width and height values ​​in the properties, but it didn't reflect.

If there's something I'm missing, please let me know.

**Comment by holance** [comment]
What are you trying to achieve?

**Comment by JIHOON-OHH** [comment]
> What are you trying to achieve?

<img width="960" alt="제목 없음" src="https://github.com/user-attachments/assets/e196d9b1-91a7-433f-a27c-6abc842cb002">

I want to reduce the AxisPlaneGrid, which is widely present in the picture above, to the area of ​​the red square.

**Comment by holance** [comment]
Axis plane grid is generated in shader, it's border is infinite. You can generate your own grid with lines if you need only a specific area.

**Comment by JIHOON-OHH** [comment]
> Axis plane grid is generated in shader, it's border is infinite. You can generate your own grid with lines if you need only a specific area.

Thanks for your reply. Have a nice day!
