### ISSUE TITLE
Enable/disable depth (Z) testing

### ISSUE THREAD

**Issue by aparajit-pratap** [helix-toolkit/helix-toolkit#226]
Is there a way to enable/disable depth (Z) testing so that I can create overlay graphics that always stay on top of geometry?

**Comment by objorke** [comment]
Is this for WPF3D or SharpDX?

**Comment by objorke** [comment]
It is possible it can be implemented in the SharpDX based component, but not in the WPF3D, I think.

You could add another layer of Viewport3D...

**Comment by aparajit-pratap** [comment]
I was referring to SharpDX.

**Comment by smischke** [comment]
You could use the "GeometryModel3D.DepthBias" property (set it to -1000). If you need more control, you have to derive from i.e. "MeshGeometryModel3D" and override "OnRasterStateChanged()".

**Comment by aparajit-pratap** [comment]
Thanks @smischke I'll try this approach!
