### ISSUE TITLE
I can't get CullMode.None working

### ISSUE THREAD

**Issue by KlaskSkovby** [helix-toolkit/helix-toolkit#2264]
So i have this plane i want to be able to see the material from both sides.
I create the plane like this and set the CullMode.None but without effect.
`
 public class WorkingPlane: GroupModel3D
    {
        public PhongMaterial PlaneMaterial { private set; get; } 
        private readonly static Geometry3D workingplane;
        private readonly MeshGeometryModel3D PlaneModel;
        static WorkingPlane()
        {
            var b1 = new MeshBuilder();
            b1.AddQuad(new Vector3(-1, 0, -1), new Vector3(1, 0, -1), new Vector3(1, 0, 1), new Vector3(-1, 0, 1));
            workingplane = b1.ToMeshGeometry3D();
        }

        public WorkingPlane() 
        {
            PlaneMaterial = new PhongMaterial
            {
                DiffuseColor = Colors.Red.ToColor4(),
                AmbientColor = Colors.Red.ToColor4(),
                ReflectiveColor = Colors.Red.ToColor4(),
                SpecularColor = Colors.Red.ToColor4()
            };
            PlaneModel = new MeshGeometryModel3D()
            {
                Geometry = workingplane,
                Material = PlaneMaterial,
                CullMode = SharpDX.Direct3D11.CullMode.None
            };

            this.Children.Add(PlaneModel);
        }
    }
    `
    
    My light is bound to the camera lookdirection
    <hx:DirectionalLight3D Direction="{Binding Camera.LookDirection}" Color="{Binding DirectionalLightColor}" />
   `
           // camera setup
        this.Camera = new PerspectiveCamera
        { 
            Position = new Point3D(1.5, -5, 0.25), 
            LookDirection = new Vector3D(0, 1, 0), 
            UpDirection = new Vector3D(0, 0, 1),
            FarPlaneDistance = 100,
            NearPlaneDistance = 0.01,
        };
`
From front and from back
![2024-08-24 09_25_09](https://github.com/user-attachments/assets/83a7ce23-992b-4960-8735-2c516c1b1372)
![2024-08-24 09_25_28](https://github.com/user-attachments/assets/75a67a0d-9626-4e1a-b7fa-720107962a70)

Is this a bug or am i doing something wrong?

**Comment by KlaskSkovby** [comment]
Sorry.

was an error from my side the, light was not bound correctly to the camera

**Comment by KlaskSkovby** [comment]
So the title is wrong as the cullmode.none works.

but its the light that doesnt show on the other side of the object

If i set the Directional light direction to 0;-1;0 then i can see the material on both sides of the object
if i how ever mode the light around with my camera lookdirection it will only show the material on one side,

This is with the directional light bound to the camera lookdirection from both sides. 
(here the other models in the view gets the light and the plane doesnt)
![2024-08-24 11_06_29](https://github.com/user-attachments/assets/ea4d20d3-68e3-4fd2-89d4-8c719a568792)
![2024-08-24 11_06_09](https://github.com/user-attachments/assets/bcad9b05-d649-4067-8a30-3dce3956e586)


This is with the directional light with fixed value 
(here the plane  has light on both sides and the other models in the view doesnt)
public System.Windows.Media.Media3D.Vector3D CameraLookDirection { get; set; } = new(0, 1, 0);
![2024-08-24 11_07_10](https://github.com/user-attachments/assets/331cc1b5-8693-41e3-8278-a95ad7fed49a)
![2024-08-24 11_07_28](https://github.com/user-attachments/assets/5f4d86b1-eeb1-4a75-8859-6bef44700892)

**Comment by KlaskSkovby** [comment]
I need to add two planes with change of direction

        private readonly MeshGeometryModel3D PlaneModelFront;
        private readonly MeshGeometryModel3D PlaneModelBack;
        static WorkingPlane()
        {
            var b1 = new MeshBuilder();
            b1.AddQuad(new Vector3(-1, 0, -1), new Vector3(1, 0, -1), new Vector3(1, 0, 1), new Vector3(-1, 0, 1));
            var b2 = new MeshBuilder();
            b2.AddQuad(new Vector3(-1, 0, -1), new Vector3(-1, 0, 1), new Vector3(1, 0, 1), new Vector3(1, 0, -1));
            workingplane = b1.ToMeshGeometry3D();
            workingplane2 = b2.ToMeshGeometry3D();
        }

        public WorkingPlane() 
        {
            PlaneMaterial = new PhongMaterial
            {
                DiffuseColor = Colors.Red.ToColor4(),
                AmbientColor = Colors.Red.ToColor4(),
                ReflectiveColor = Colors.Red.ToColor4(),
                SpecularColor = Colors.Red.ToColor4()
            };
            PlaneModelFront = new MeshGeometryModel3D()
            {
                Geometry = workingplane,
                Material = PlaneMaterial,
                CullMode = SharpDX.Direct3D11.CullMode.Back,
            };

            PlaneModelBack = new MeshGeometryModel3D()
            {
                Geometry = workingplane2,
                Material = PlaneMaterial,
                CullMode = SharpDX.Direct3D11.CullMode.Back,
            };

            this.Children.Add(PlaneModelFront);
            this.Children.Add(PlaneModelBack);
        }

**Comment by holance** [comment]
Or you can try to use DiffuseMaterial so it doesn't rely on the lights
