### ISSUE TITLE
LineGeometryModel3D instancing change color

### ISSUE THREAD

**Issue by KlaskSkovby** [helix-toolkit/helix-toolkit#2266]
Im using SharpDX to draw multiple lines with the instancing of the lines

Right now all the lines have the same Color.
            this.LineGeometryModel3D.Color = Colors.LightBlue;
            
 Is it however possible to change color of some lines with InstanceParameter ? similar to what the InstancingDemo does with the cubes

**Comment by holance** [comment]
There's no color parameter support for line instancing. Since line drawing is fairly cheap, you can probably just use single line mesh with different vertex colors instead of using instancing.

**Comment by KlaskSkovby** [comment]
Ok, I created an extra LineGeometryModel3D for other colors, and using the same Geometry line mesh.
Performance didn't take a hit, so this is a good option.
