### ISSUE TITLE
AddPolygon cause ArgumentNullException

### ISSUE THREAD

**Issue by EdoardoNagliati** [helix-toolkit/helix-toolkit#2267]
Good morning, everyone.
In my program, I'm trying to use Helix.SharpDX and I need to execute the following lines of code:

MeshBuilder mesh = new MeshBuilder(true, false);
mesh.AddPolygon(Mth.Point3DListToVector3(points));

Points is a list of Vector3 with more than 4 elements, and therefore, in the MeshBuilder class, the AddTriangleFan(points) function is called, but it throws an exception because the list of <Vector3D> fanNormals is not passed as a parameter.

I know one solution would be to create the object MeshBuilder(false), but in this way, the normals are not generated, and I need them to correctly illuminate the objects (which are using a PhongMaterial).

What could be the solution? With HelixToolkit.Wpf, I used a DiffuseMaterial, which did not require the calculation of normals, but with SharpDX, there doesn't seem to be a similar material.

Thanks in advance.

**Comment by EdoardoNagliati** [comment]
Sorry, but I can't find the function CalculateNormals(). Do I miss any namespace?

**Comment by holance** [comment]
https://github.com/helix-toolkit/helix-toolkit/blob/5115d4d98c336173c1b58008ac28a830b801d931/Source/HelixToolkit.Shared/Geometry/MeshGeometryHelper.cs#L62

**Comment by EdoardoNagliati** [comment]
Thanks for your help.
