### ISSUE TITLE
Viewport3DX does not work on .NET 8

### ISSUE THREAD

**Issue by MiroslavJ** [helix-toolkit/helix-toolkit#2269]
Hi helix-toolkit team. I try to upgrade my application to .NET8 standard. I use HelixToolkit.Wpf.SharpDX and it seems like it does not support .NET8. Is there any workaround for this ? Thank you.

**Comment by ArieRiezebos** [comment]
What are your symptoms? I have a .NET 8 project using the same and it works fine.

**Comment by MiroslavJ** [comment]
I am not sure are you able to see my uploaded image but I am getting warning triangles next to the listed package (Helix.Toolit.Wpf.SharpDX)

![helix dot net 8](https://github.com/user-attachments/assets/50a6cc5b-b2d6-4c65-a891-96b3488e87ad)

**Comment by ArieRiezebos** [comment]
Can you post a screenshot of your csproj file?
This is mine:
![image](https://github.com/user-attachments/assets/d8d20403-4e1a-4d34-ae27-f0694f07dfa6)

**Comment by MiroslavJ** [comment]
I would say pretty much the same, looks like this:

![image](https://github.com/user-attachments/assets/2102244a-b6d8-4218-b161-9f6d402e0962)

**Comment by ArieRiezebos** [comment]
Which visual studio version are you using? And what are the exact messages the triangles show and what are the errors shown when you compile the solution?

**Comment by MiroslavJ** [comment]
My VS version is 2022 v 17.11.4, the package issue warning sounds like: Package 'HelixToolkit.Wpf.SharpDX 2.25.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net8.0-windows7.0'. This package may not be fully compatible with your project. And the weird thing is that I am not really getting any useful compile errors (just a few xaml properties binding errors that I usually get because of the data connection). I have the projects in .NET4.8 and I use upgrade option in VS to switch it to .NET8. I had a few similar packages issues but after reinstall or upgrade packages it disappeared. The only thing I can not get rid of is this package issue. I thought that Helix does not support .NET8 at all, but if you say it works on your side maybe it's the upgrade issue. I simply can not build the project.

**Comment by ArieRiezebos** [comment]
Maybe only reference SharpDx.Core and not the other two packages to see if that allows you to build.

**Comment by MiroslavJ** [comment]
ok thans will let you know

**Comment by holance** [comment]
Please use .core packages for net8

**Comment by MiroslavJ** [comment]
Thank you guys for your help. After removing all internal issues related with .NET upgrade it turned out that HelixToolki.Wpf.SharpDX actually works. Then only thing is that I am still getting that package compatibility warning. Eventually I will switch to .core packages.
