### ISSUE TITLE
Is there a way to do a Point3D hit testing.

### ISSUE THREAD

**Issue by KlaskSkovby** [helix-toolkit/helix-toolkit#2270]
I have a point3D, is there a way to do a hit test of that 3d point and return which mesh it hits?

**Comment by holance** [comment]
Hit test already includes point hit test.

**Comment by KlaskSkovby** [comment]
Hey again.

but the hit test is only from a projected 2d screen point to the 3d view.
what i'm looking for is to check if a 3d point in the given space hits any model.

**Comment by holance** [comment]
A 3d point doesn't have any size and direction. Are you trying to test whether the point is inside a mesh? On mesh surface?
