### ISSUE TITLE
MeshGeometryModel3D can support multi color?

### ISSUE THREAD

**Issue by RyugaRyuzaki** [helix-toolkit/helix-toolkit#2272]
Hi i have a MeshGeometryModel3D with triangleIndex, each triangle has color [r,g,b,a] can MeshGeometryModel3D  support this ? Sorry, i'm newbie. many thank

**Comment by holance** [comment]
Helix toolkit sharpdx version supports vertex colors, not triangle colors.

**Comment by RyugaRyuzaki** [comment]
> Helix toolkit sharpdx version supports vertex colors, not triangle colors.

MeshGeometryModel3D does not have  vertex colors.

**Comment by holance** [comment]
You need to set it in MeshGeometry3D along with vertices/positions. Then use VertColorMaterial to display.
