### ISSUE TITLE
Memory leak with SpritePackerBase

### ISSUE THREAD

**Issue by KlaskSkovby** [helix-toolkit/helix-toolkit#2273]
My program generates alot of Packed text images. 

I use the image packer like so, so it dispose afterwards.
using (TextInfoExtPacker imagePacker = new TextInfoExtPacker(effectsManager))
{

}

However I get a memory leak.

When i look inside the 
TextInfoExtPacker  : SpritePackerBase

then the SpritePackerBase Dispose doesnt look finished
I have no idea how to fix the Dispose for this class. 

    #region IDisposable Support
    private bool disposedValue = false; // To detect redundant calls

    void Dispose(bool disposing)
    {
        if (!disposedValue)
        {
            if (disposing)
            {
                // TODO: dispose managed state (managed objects).
            }

            // TODO: free unmanaged resources (unmanaged objects) and override a finalizer below.
            // TODO: set large fields to null.

            disposedValue = true;
        }
    }

    // TODO: override a finalizer only if Dispose(bool disposing) above has code to free unmanaged resources.
    // ~ImagePacker() {
    //   // Do not change this code. Put cleanup code in Dispose(bool disposing) above.
    //   Dispose(false);
    // }

    // This code added to correctly implement the disposable pattern.
    public void Dispose()
    {
        // Do not change this code. Put cleanup code in Dispose(bool disposing) above.
        Dispose(true);
        // TODO: uncomment the following line if the finalizer is overridden above.
        // GC.SuppressFinalize(this);
    }
    #endregion

**Comment by holance** [comment]
Please upload a sample project so we can debug

**Comment by KlaskSkovby** [comment]
Sure ill try to put together a sample project this week and upload

**Comment by KlaskSkovby** [comment]
[TestProjectHelixToolkit.zip](https://github.com/user-attachments/files/17368363/TestProjectHelixToolkit.zip)

I have create a very simple test of this

![image](https://github.com/user-attachments/assets/f17fce63-e2d4-4e3c-b1d0-84422cbb0746)

two buttons 
1.  1 time update plotting 100 numbers.
2.  loops 100 updates to fill up Memory faster

1 time 
![image](https://github.com/user-attachments/assets/d133ca3e-3c03-4376-8328-b8a5aacafad9)


5 x 100
![image](https://github.com/user-attachments/assets/010eb8ea-8fc3-4d7d-a2ba-2ceeec23c6f4)

But memory is never released again

**Comment by KlaskSkovby** [comment]
Hey Holance,

I still get the memoryleak with the TestProject if i reference the need update on github.

**Comment by KlaskSkovby** [comment]
Thanks Holance,

It works perfect now :D
