### ISSUE TITLE
PBR (question)

### ISSUE THREAD

**Issue by MichaelCHF** [helix-toolkit/helix-toolkit#2278]
I download a material  zip, It contains AO、Metalness、Roughness images etc，I set AO image to AmbientOcculsionMap，how can i set Metalness or Roughness image ?  only RoughnessMetallicMap property.
I Saw ： If provides RMA map in one texture, set both "RoughnessMetallicMap" and "AmbientOcculsionMap" to the same texture.
It is means  i have to set AO image to RoughnessMetallicMap too?? Or I need to do something special to make these three pictures into one picture?

**Comment by holance** [comment]
You need to at least combine Metallic and Roughness map into one image. Optionally combine AO into same image. Ambient Occlusion as R channel, roughness as G channel, metallness as B channel.
