### ISSUE TITLE
PostEffectMeshOutlineBlur  issue  sharpdx

### ISSUE THREAD

**Issue by MichaelCHF** [helix-toolkit/helix-toolkit#2281]
When i add PostEffectMeshOutlineBlur to  13+ geometries, There is a lag when I rotated the camera by mouse.
What's the reason？Thanks!

//mashGeometryModel3D.PostEffects = "highlight[color:#FFFF00];glow[color:#FFFF10]";     ----**lag**
//mashGeometryModel3D.PostEffects = "highlight[color:#FFFF00]";                                       ----**lag**
mashGeometryModel3D.PostEffects = "glow[color:#FFFF10]";                                                ----**fine**

![image](https://github.com/user-attachments/assets/3384ad7a-0831-4c05-a935-7c309f687e1f)

**Comment by holance** [comment]
You need to change the `PostEffectMeshOutlineBlur.DrawMode` to Merged, otherwise each object needs to do separate pass to draw its outlines, which may causes performance issues.
