### ISSUE TITLE
Interactive point cloud

### ISSUE THREAD

**Issue by githubjanson** [helix-toolkit/helix-toolkit#2284]
I would like to create an interactive chart with a point cloud of 100000 color coded points. User should be able to zoom/pan and also select individual points (to get info). Is this achievable using Helix library?

I have created a point cloud of indiviudally colored points using a PointGeometryModel3D, but there is no support for selecting points.

**Comment by holance** [comment]
Use mouse down handler to do hit test:
```
    public void OnMouseLeftButtonDownHandler(object? sender, System.Windows.Input.MouseButtonEventArgs e)
    {
        var point = e.GetPosition(viewport);
        var hits = viewport.FindHits(point);
     }
```

Then in `hits`, you can check if the model is your point cloud, and the `IndiceStartLocation` is the point index in that geometry.Positions.

**Comment by githubjanson** [comment]
Many thanks for this!
