### ISSUE TITLE
How to create adequate coordinate axes in a Viewport3DX?

### ISSUE THREAD

**Issue by githubjanson** [helix-toolkit/helix-toolkit#2285]
I am using SharpDX/Viewport3DX.

I have a 3D point cloud where I would like to add coordinate axes. But I want the line thickness to render with the same size no matter how I zoom. I can achieve this by setting camera to OrthographicCamera, but I need it to be PerspectiveCamera for the point cloud.

I have browsed the examples, but I can't find any clue there. How can I accomplish this?

**Comment by holance** [comment]
You can set `LineGeometryModel3D.FixedSize = true` (this is default setting) to render line thickness always the same.

**Comment by githubjanson** [comment]
Thanks, but it is not working the way I want. I want to avoid the "perspective" effect on coordinate axes.

![temp5](https://github.com/user-attachments/assets/f82914f0-9245-4760-81cc-cf91b3a07966)

**Comment by holance** [comment]
I am not able to reproduce your issue with LineGeometry. Could you upload your demo project so I can take a look?

**Comment by githubjanson** [comment]
To reproduce:
In the CustomViewCubeDemo project. Change the coordinate axes lengths from 5 to 100 and you will get this effect. 

```
private void InitializeCoordinates()
{
    var builder = new LineBuilder();
    builder.AddLine(Vector3.Zero, Vector3.UnitX * 100);
    builder.AddLine(Vector3.Zero, Vector3.UnitY * 100);
    builder.AddLine(Vector3.Zero, Vector3.UnitZ * 100);
// ...
}
```
I realize that this is perhaps related to how the ScreenSpacedGroup3D is set up, but I am not sure how.

**Comment by githubjanson** [comment]
In a LineGeometryModel3d, it seems that setting FixedSize = true does not work when LineBuilder.AddLine(...) is used to build the geometry. But it works ok for boxes, i.e., LineBuilder.AddBox(...).

**Comment by holance** [comment]
Please try the latest nightly build.

**Comment by githubjanson** [comment]
Ok, thanks. It seems to work now, as intended.

Best from Magnus
________________________________
Från: Lunci ***@***.***>
Skickat: den 19 november 2024 23:24
Till: helix-toolkit/helix-toolkit ***@***.***>
Kopia: githubjanson ***@***.***>; Author ***@***.***>
Ämne: Re: [helix-toolkit/helix-toolkit] How to create adequate coordinate axes in a Viewport3DX? (Issue #2285)


Please try the latest nightly build.
