### ISSUE TITLE
wpf & sharpdx question

### ISSUE THREAD

**Issue by MichaelCHF** [helix-toolkit/helix-toolkit#2288]
I load a tree model,when i rotate camera,i can see the png image background.what can i do both in wpf & sharpdx? thanks!

Incorrect display:
![1732004143514](https://github.com/user-attachments/assets/2a94107f-fae8-47d7-a44d-21d837f2b32b)
the correct display in 3DViewer:
![1732004554704](https://github.com/user-attachments/assets/d7b809fd-3813-4f46-bd83-e81f20ae60ea)
[Tree.zip](https://github.com/user-attachments/files/17811911/Tree.zip)

**Comment by MichaelCHF** [comment]
thanks for your help, sharpdx is ok,how about helixtoolkit.wpf?

**Comment by MichaelCHF** [comment]
![1732241221964](https://github.com/user-attachments/assets/3a24cc77-ef5b-4e61-92c5-17a0b60a02b9)

**Comment by MichaelCHF** [comment]
> thanks for your help, sharpdx is ok,how about helixtoolkit.wpf?

![1732241503255](https://github.com/user-attachments/assets/20cf8ab8-5895-4ca8-8165-472dc23797c2)

**Comment by holance** [comment]
helixtoolkit.wpf doesn't support this.
