### ISSUE TITLE
How to get the projected size of an object?

### ISSUE THREAD

**Issue by githubjanson** [helix-toolkit/helix-toolkit#2300]
How can I get the projected/rendered size of an object like a LineGeometry3D?

The problem I am trying to solve is that I want the "tick resolution" of a coordinate axis to adapt to the perspective. Otherwise it easily gets blurry when perspective is changed. So my plan is to update the model based on its projected size.

![Axis](https://github.com/user-attachments/assets/0b4ff4ba-ae62-4621-ac68-b987632a100d)
![Blurry axis](https://github.com/user-attachments/assets/d010d1fe-eba6-48a2-aaa6-d0e268b4d937)

**Comment by holance** [comment]
You can use viewport3DX.project to project a 3d point onto screen space.

**Comment by githubjanson** [comment]
Great, thanks!

**Comment by githubjanson** [comment]
Great, thanks!
