### ISSUE TITLE
How to make Z-axis as the up axis?

### ISSUE THREAD

**Issue by vincent1912** [helix-toolkit/helix-toolkit#2301]
I noticed that in HelixToolkit.wpf, the Z axis is pointing upwards. But in HelixToolkit.SharpDX.Core, the Y axis is pointing upwards. Is it possible to change any axis to point upwards?

![111111](https://github.com/user-attachments/assets/7f13e219-80e1-43ec-a4de-3afd1f362fa3)
![222222](https://github.com/user-attachments/assets/18c1836f-5bf0-4889-831d-b58c992d75f5)

**Comment by vincent1912** [comment]
I mean modify the up axis when using HelixToolkit.SharpDX.Core.

**Comment by holance** [comment]
Change Viewport3DX.ModelUpDirection
