### ISSUE TITLE
Broken msdn link in documentation

### ISSUE THREAD

**Issue by trymnilsen** [helix-toolkit/helix-toolkit#238]
Noticed a minor issue with a broken link in the [documentation](https://github.com/helix-toolkit/helix-toolkit/blob/master/Source/HelixToolkit.Wpf/Helpers/MeshBuilder.cs#L2539). 
Since the msdn link does not have a version in the url it defaults to latest, which just says "_This topic is no longer available_"

Changing from:
https://msdn.microsoft.com/en-us/library/bb613553.aspx
To:
https://msdn.microsoft.com/en-us/library/bb613553(v=vs.100).aspx

Yields a page with the documentation referenced. Happy to supply a quick pr if you want it fixed

**Comment by objorke** [comment]
Thanks, I have updated the links!
