### ISSUE TITLE
Not distributing the Win8 version to nuget?

### ISSUE THREAD

**Issue by bc3tech** [helix-toolkit/helix-toolkit#239]
[Looking at Nuget.org](https://www.nuget.org/packages?q=HelixToolkit), I don't see the Win8 project (present in source) being pushed. Is there a reason for this?

Presently I'm looking at getting this project (hopefully) building for Windows UWP. Will be submitting a PR if/when this happens. But I was surprised (after trying to pull *any* nuGet proj for this in to my UWP) to see a Win8 project present in the source. Curious why we're not distributing it.

**Comment by objorke** [comment]
Currently, it is only supporting WPF. But it would be great to see UWP support for the DirectX/SharpDX based version!

**Comment by bc3tech** [comment]
Right but the Win8 version should provide it already, though - is there a reason we haven't shipped to GitHub?

**Comment by objorke** [comment]
The Win8 project is just a prototype showing that we could create a viewport similar to the ones in WPF. It does not have enough functionality to be published on NuGet in my opinion.

**Comment by objorke** [comment]
I updated the Win8 project to 8.1. Builds and runs ok on Windows 10.

**Comment by objorke** [comment]
I added #241. I think we should forget about Win8...

**Comment by bc3tech** [comment]
w/ creation of #241 yup. Closed.
