### ISSUE TITLE
SharpDX.DefaultEffectsManager: Not possible to set device / device selection

### ISSUE THREAD

**Issue by MyCodeUsuallyWorksOnMyOwnMachine** [helix-toolkit/helix-toolkit#258]
**Problem:**
In DefaultEffectsManager.cs the logic for selecting the device (the "GetBestAdapter()" and #if DX11 stuff) is completely hardcoded in the constructor. 

It is possible to inherit from DefaultEffectsManager, but that only allows accessing the device afterwards.

I have a case where the device selection code is broken and I have no way to change anything, except copy/pasting the entire DefaultEffectsManager (including the embedded resources) and put that into my own code.

A possible fix could be to add an additional constructor which does the following:

```
public DefaultEffectsManager(IRenderTechniquesManager renderTechniquesManager, global::SharpDX.Direct3D11.Device device)
{
    this.renderTechniquesManager = renderTechniquesManager;
    this.device = device;
    InitEffects();
} 
```

This allows consumers of the DefaultEffectsManager class to implement their own device selection logic, including the option of presenting the choice to end-users, etc.

**Comment by holance** [comment]
New 2.0 allows to pass adapter index into constructor.
