### ISSUE TITLE
ImageViewDemo does not work

### ISSUE THREAD

**Issue by LordBenjamin** [helix-toolkit/helix-toolkit#268]
The ImageViewDemo sample is not working for me - firstly, an NRE due to the `RenderTechniqueManager` not being set, and then the loaded image did not display.

This was fixed by moving the creation of the `RenderTechniqueManager` to before it was used, and changing the various bound properties to notify of property changes. See attached.

[MainViewModel.zip](https://github.com/helix-toolkit/helix-toolkit/files/204123/MainViewModel.zip)

**Comment by smischke** [comment]
Thanks. You can make a pull request if you like. If not, I'll do it at the weekend.

**Comment by holance** [comment]
Fixed.
