### ISSUE TITLE
MeshBuilder.AddQuad creates negated normal vectors

### ISSUE THREAD

**Issue by MichaelEwe** [helix-toolkit/helix-toolkit#271]
Adding a quad using

> p0=(0 0 0), p1=(1 0 0), p2=(1 1 0) and p3=(0 1 0)

gives 4 normal vectors

> n=(0,0,-1)

This is wrong. The correct normal vector would be

> n=(0,0,1)

I think the reason is calculating the crossproduct in `MeshBuilder.cs` with clockwise winding order:
`var w = Vector3D.CrossProduct(p3 - p0, p1 - p0);`

It should be counter clockwise:
`var w = Vector3D.CrossProduct(p1 - p0, p3 - p0);`

`AddTriangle` does it right.

**Comment by JeremyAnsel** [comment]
This was fixed by #274 so this can be closed.
