### ISSUE TITLE
How to change texture/draw on certain areas of an imported obejct with Helixtool?

### ISSUE THREAD

**Issue by georgianamanolache** [helix-toolkit/helix-toolkit#273]
Hello,

I would like to only change material in certain parts of my imported object. I want to simulate brain activity. I am using an imported .obj and I would like to draw/change texture of the object only on the right side. Is that possible within Helixtoolkit?

**Comment by objorke** [comment]
I think this is a question for http://forum.helix-toolkit.org/
I don't think this is a bug or new feature...

**Comment by objorke** [comment]
I found this one :-)
http://forum.helix-toolkit.org/topics/1126-how-to-change-texturedraw-on-certain-areas-of-an-imported-obejct-with-helixtool/
Can we close the issue here?

**Comment by holance** [comment]
Close for now.
