### ISSUE TITLE
Helix Forum not available?

### ISSUE THREAD

**Issue by SteveReilly** [helix-toolkit/helix-toolkit#280]
When I try to access http://forum.helix-toolkit.org/, I get the following message:

This site can’t be reached

The webpage at http://forum.helix-toolkit.org/ might be temporarily down or it may have moved permanently to a new web address.

???

Steve

**Comment by daxpandhi** [comment]
http://helix-toolkit.org/ is down as well.

**Comment by objorke** [comment]
The domain is registered with Arvixe. I have created a support ticket, they say they are working on it...

**Comment by daxpandhi** [comment]
@objorke - if you ever want to create a mirror site, I'd be happy to sponsor it. :)

**Comment by Equinoxae** [comment]
Some news ?

**Comment by paynterf** [comment]
Great news that helix toolkit lives!  Link for the new site?

**Comment by objorke** [comment]
http://www.helix-toolkit.org/
http://helix-toolkit.org/ (forwarding, should work soon)
http://forum.helix-toolkit.org/
http://docs.helix-toolkit.org/
