### ISSUE TITLE
Viewport3DX and PointGeometry3DModel geometry update

### ISSUE THREAD

**Issue by DaveNW16HD** [helix-toolkit/helix-toolkit#288]
Hi

I'm trying to update my PointGeometry3DModel  model based on user input. I notice IPropertyChange doesn't work when binding PointGeometry3D from a view model. What's the correct way to re-render Viewport3DX when a geometry has changed ?

**Comment by objorke** [comment]
is this a bug? I think the property change callback should handle this https://github.com/helix-toolkit/helix-toolkit/blob/master/Source/HelixToolkit.Wpf.SharpDX/Model/Elements3D/AbstractElements3D/GeometryModel3D.cs#L47

**Comment by cokemal** [comment]
I use ReAttach Method of the Viewport3DX after geometry changes. It works just fine.
