### ISSUE TITLE
Add AddRotateForce with rotationPoint

### ISSUE THREAD

**Issue by jotschgl** [helix-toolkit/helix-toolkit#291]
Currently the method AddRotateForce in Viewport3DX and CameraController (WPF & SharpDX) always uses the CameraTarget as rotation Point. Event if CameraMode is set to WalkAround. I would suggest to implement a method with rotationPoint3D

**Comment by holance** [comment]
Implemented FixedRotationPoint and FixedRotationPointEnabled. Then you can specify the rotation point to rotate.
