### ISSUE TITLE
Obj files import and cursor position in HelixToolkit.Wpf.SharpDX

### ISSUE THREAD

**Issue by IgorGrechka** [helix-toolkit/helix-toolkit#294]
Hello guys! Thank you for great toolkit!

I have 2 questions, maybe anyone can help me:

**First:** I want to import obj model (with textures) and display it in Viewport3DX. How to do it correctly?
Now I have next:

  `ObjReader Reader = new HelixToolkit.Wpf.SharpDX.ObjReader();`
  `List<Object3D> objs = Reader.Read(ModelPath);`

After reading `objs` variable contains near 1000 objects. What shall be the next steps to to display model in viewport?

**Second:** And one more question: How to receive cursor position in Viewport3DX. Is there some property like `CursorPosition` in HelixViewport3D?

Thank you in advance!

**Comment by objorke** [comment]
Please use the forum for questions :-) The issues section should be used for bugs and new features

**Comment by IgorGrechka** [comment]
Thank you for reply! I will ask on the forum!

**Comment by IgorGrechka** [comment]
Maibe you can add small example to examples library with importing obj files in SharpDX. It can be very helpful for beginners (like me). :-)

**Comment by objorke** [comment]
Yes, there should be an example! Please make one! :-)

**Comment by SiNeumann** [comment]
I have FileLoadDemo(3ds,obj) prepared locally,I'll try to merge it next weekend and create a pull request
