### ISSUE TITLE
Model becomes blurred,how to set V-sync to lock 60pfs

### ISSUE THREAD

**Issue by xlp100** [helix-toolkit/helix-toolkit#304]
A few minutes later,Model becomes blurred.
for example:

this is start exe model display:
![starexe](https://cloud.githubusercontent.com/assets/4033455/18499753/6bc728b4-7a74-11e6-8c6b-148bd334754e.png)

this is a few minutes later model display:
![fewminuteslater](https://cloud.githubusercontent.com/assets/4033455/18499754/6da66f96-7a74-11e6-9a6b-cdff01961fe9.png)

**During this time I do not have anything.**

**Comment by holance** [comment]
This is not caused by v-sync.
