### ISSUE TITLE
How to load and display 3d file (obj, 3ds etc...) in SharpDX?

### ISSUE THREAD

**Issue by mk48** [helix-toolkit/helix-toolkit#319]
I can easily import a 3D model in Helix toolkit, like the following.

```
HelixToolkit.Wpf.ModelImporter mimp = new HelixToolkit.Wpf.ModelImporter();
System.Windows.Media.Media3D.Model3DGroup m3dGroup = mimp.Load(@"C:\3dmodels\myfile.3ds");
```

How to load and display the same '3ds' file in Helix-SharpDX?

**Comment by Iluvatar82** [comment]
I think you just create the Viewport3DX as you usually would (check the examples) and in XAML you add a GroupModel3D into your viewport, like this:
`
        <hx:Viewport3DX x:Name="viewport" Camera="{Binding Camera}" RenderTechnique="{Binding RenderTechnique}">
            <hx:GroupModel3D x:Name="loadedModels"></hx:GroupModel3D>
        </hx:Viewport3DX>
`
When you load your *.3DS File you do something like this:

`
            var reader = new HelixToolkit.Wpf.SharpDX.StudioReader();
            var m3dGroup = reader.Read(@"C:\3dmodels\myfile.3ds");


            foreach (var model in o3dGroup)
            {
                var sharpModel = new MeshGeometryModel3D()
                {
                    Geometry = model.Geometry,
                    Material = model.Material,
                    Name = model.Name,
                    Transform = new MatrixTransform3D(model.Transform.ToMatrix3D()),
                };
                loadedModels.Children.Add(sharpModel);
            }
`
The same steps were performed in the **FileLoadDemo** (also have a look at the function AttachModelList in den MainViewModel class)...

**Comment by mk48** [comment]
Thanks @Iluvatar82 ,
It seems that the 'NuGet' doesn't have the latest version of Helix tool kit.
I installed this tool(ver: 2015.1.715) kit using nuget package manager.
This version doesn't have StudioReader class. But its available in the source.

by the way, where can I get the latest DLLs of Helix-SharpDX?

**Comment by mk48** [comment]
It's working fine now. I am using the myget.org packages in Visual Studio to get the latest helix packages.
here is a simple tutorial for how to use myget.org in VS2015
http://mkumaran.net/blog/2016/11/myget-org-visual-studio-2015/
