### ISSUE TITLE
Where should I start from? And an obsolete content report

### ISSUE THREAD

**Issue by wky2014** [helix-toolkit/helix-toolkit#321]
First of all, thank you very very much for your toolkit! It would be really helpful for there are very little resources about SharpDX on UWP.

I would like to know how to use this toolkit, which function should I call first from my XAML page? I have tried `Viewport3DX()` (constructor), but it didn't raise the event `Loaded`, and certainly I can't raise it myself.

And I report the `DisplayProperties` class used in the `Viewport3DXLoaded` method is obsolete now. VS2015 suggest it should be replaced by DisplayInformation, and it seems to be requiring an instantiation.

**Comment by BetaRavener** [comment]
I think this should be helpful https://github.com/helix-toolkit/helix-toolkit/wiki/Getting-started-with-WPF-3D.

The way I used to create scene was kind of mixed approach. I defined the Viewport in XAML and specified all it's properties, but the scene itself was created in code. To do this, you need to get reference of Viewport that is already defined in XAML, not construct a new one. One of the ways to do this is to give a name to the Viewport `<hx:Viewport3DX Name="ViewportDx" ...` and then get reference to it in code, `var hVpDx = FindName("ViewportDx") as Viewport3DX;`.
You can do this in `.cs` file of XAML (e.g `MainWindow.xaml` has `MainWindow.xaml.cs`) and continue on building the scene as described in tutorial.

**Comment by Iluvatar82** [comment]
I think you need to use **x:Name** instead of **Name** in the XAML file to be able to reference it in the code-behind file.
[http://stackoverflow.com/a/1128660/2252268](url)
[https://msdn.microsoft.com/de-de/library/ms752290(v=vs.110).aspx](url)
It seems **Name** is just a property of the super-class FrameworkElement.

**Comment by wky2014** [comment]
@BetaRavener You mean to make a new viewport in xaml in place of a SwapChainPanel?

**Comment by BetaRavener** [comment]
@wky2014 The SwapChainPanel should be completely hidden from you by Viewport3DX Control. So yes, you should only have a Viewport3DX in your XAML and either build your scene directly in XAML or get refence to it in code and continue building the scene there.

I have only personal experience with doing this in WPF but considering the similarities it should work the same in UWP. Moreover, if you take look at the source code, the SwapChainPanel is still there, it's just [private field of Viewport3DX](https://github.com/helix-toolkit/helix-toolkit/blob/d7ed105536c62fa7706c9af31dcc63a0c2b6b5b6/Source/HelixToolkit.UWP/Controls/Viewport3DX.cs). Basically, you just need to define the scene and Helix will take care of all the updates and rendering.

**Comment by wky2014** [comment]
@BetaRavener Ah, I see how it works now. Thank you again for your explanation. And you may want to pay attention to the situation I raised about the DisplayInformation.

**Comment by wky2014** [comment]
@BetaRavener Do I have to Install it on Nuget to have the control? Currently there's no UWP toolkit yet. Can't I just add reference to a different project and use it in XAML page? And how do I do that, since now I can use the Viewport class in cs files but not XAML.

**Comment by BetaRavener** [comment]
As I said, I have no personal experience with UWP part of the toolkit. I've looked at the activity and it seems it may be just an experiment from some time ago, that's probably the reason it doesn't have Nuget package. Anyway if you still want to try and get it running, you should just clone the repository, build the UWP part of it and reference it from your application. If there are no issues, you should be able to [create reference to the UWP project with `xmlns`.](https://msdn.microsoft.com/cs-cz/library/bb514546(v=vs.90).aspx). Then you should be able to define the Viewport in XAML.

**Comment by wky2014** [comment]
Yeah, thank you. I just have problem referencing it right now. I'll find my way. @BetaRavener

**Comment by wky2014** [comment]
@BetaRavener It turns out that it is because I didn't build the project before compiling. Now the problem seems to be solved. Why do I need to build before compiling while in other cases I do not need to do that?

**Comment by BetaRavener** [comment]
I think this discussion is no more Helix related so you should seek help from tutorials on UWP. Just to get facts straight, Building == Compiling (+ linking and other stuff), so your post doesn't make much sense. I don't know what your problem was, usually you need to build to get XAML model updated if it references other projects. Anyway, glad that you made it working, good job.

**Comment by objorke** [comment]
I don´t think this is an issue, can we close it?

**Comment by wky2014** [comment]
@objorke Go ahead
