### ISSUE TITLE
Upload HelixToolkit to Nuget

### ISSUE THREAD

**Issue by JeremyAnsel** [helix-toolkit/helix-toolkit#323]
Since #301, the librairies are no longer published to NuGet.

**Comment by objorke** [comment]
No, the package is uploaded to myget instead:
https://github.com/helix-toolkit/helix-toolkit/blob/master/appveyor.yml#L40

But I agree, there should be a new release on NuGet soon!

**Comment by objorke** [comment]
https://github.com/helix-toolkit/helix-toolkit/milestone/1

**Comment by JeremyAnsel** [comment]
The MyGet feed seems to be empty.

![npe_myget_helixtoolkit](https://cloud.githubusercontent.com/assets/9573196/19982386/341de524-a206-11e6-8761-79bb3127e605.PNG)

**Comment by JeremyAnsel** [comment]
The packages are now uploaded to MyGet:

![npe_myget_helixtoolkit2](https://cloud.githubusercontent.com/assets/9573196/20032611/0e79aa7c-a38e-11e6-958b-044c00927a29.PNG)

**Comment by JeremyAnsel** [comment]
V1.0.0 is published to NuGet:
- https://www.nuget.org/packages/HelixToolkit/1.0.0
- https://www.nuget.org/packages/HelixToolkit.Wpf/1.0.0
- https://www.nuget.org/packages/HelixToolkit.Wpf.SharpDX/1.0.0
