### ISSUE TITLE
Is a tube made from TubeVisual3D always hollow?

### ISSUE THREAD

**Issue by DragonPat0219** [helix-toolkit/helix-toolkit#326]

**Comment by DragonPat0219** [comment]
How to make a tube non-hollow with VisualTube3D

**Comment by holance** [comment]
If you just want to close the holes at both ends of the tube, you can use the section to close the holes or manually add thin pipes to close the holes

**Comment by DragonPat0219** [comment]
I tried using section  to create a circle, however, the circle still hollow. I just want to cap two ends. could you tell me how you would use section to close the hole?

**Comment by holance** [comment]
Seems like the simple way is to using add pipe to close the hole. You can extend the TubeVisual3D and override the Tessellate(). Copy the codes in ExtrudedVisual3D, before the final ToMeshGeometry3D. Manual add two thin pipe into the builder using AddPipe. 

Or use two PipeVisual3D to add pipe externally.

**Comment by DragonPat0219** [comment]
Thank you so much for helping.
But adding pipes to both end would only work if points in the path are close to each other, so we can use first two points and last two points to create a thin pipe. however, in my case, my points are not close to each other, if I still use first and last two points, the pipe would be a long pipe. However, if i use only the first point or last point, I need to figure out position of another point at the path that is close to the first or last point. If I don't do that, the pipes would always straight and won't have a same orientation as my tubes have.

**Comment by holance** [comment]
You can calculate the normal of the last two points, then last point
+normal.normalize() *0.1 to get the other point you need to create the
pipe.

**Comment by holance** [comment]
I meant the vector of last two points (v[last-1]-v[last]).

**Comment by Iluvatar82** [comment]
I am working on an additional DependencyProperty for the TubeVisual3D that allows the automatic creation of caps for a TubeVisual3D (it just a two triangle-fan at the beginning and the end). I thought this was the easiest way to solve the problem.
I didn't make the pull request yet, because I also add some additions to the MeshBuilder from other issues as well.

**Comment by DragonPat0219** [comment]
If the caps could be created automatically, that will be awesome because in my case, my tube will be able to change its orientation, so it will be too much calculation for adding pipe to both ends. When do you think you can pull request?

**Comment by Iluvatar82** [comment]
Is the solution from #355 working for you?

**Comment by DragonPat0219** [comment]
How to update the helixtoolkit library? The one I am having does not have
AddCaps method yet.
