### ISSUE TITLE
Camera controller for UWP

### ISSUE THREAD

**Issue by KySpace** [helix-toolkit/helix-toolkit#337]
There seems to be no camera controls in HelixToolkit for UWP. If I want to build one myself, where do you suggest to build it, in the Viewport or as an Item? And how is it going to interact with the control events and the objects? Thank you.

**Comment by objorke** [comment]
Right, the UWP project is not doing anything useful yet. I think it should contain the same scene graph as the SharpDX project (shared code?). Camera manipulation should also be moved from the WPF project to a portable or shared project. The SharpDX project still use the WPF camera controller, I think.

**Comment by wky2014** [comment]
Finally somebody answering this. Well, I built it myself in the Target Base class, feeling the WPF is too large and I'm afraid things may occur that I can't handle. It worked fine up till now, for some simple features, just the code may not be that organized for I'm not a pro.

**Comment by holance** [comment]
Done.
