### ISSUE TITLE
ZoomRectangle not displayed

### ISSUE THREAD

**Issue by ipfreely42** [helix-toolkit/helix-toolkit#338]
There seems to be a problem with displaying the zoom rectangle. I believe the issue is caused by the following call within **Viewport3DX.ShowZoomRectangle(Rect rect)**:
`if (this.rectangleAdorner != null)
            {
                return;
            }`
If I replace the return call with `this.HideZoomRectangle();` everything works as expected. Please note, this problem only affects the drawing of the rectangle. The actual zooming operation works fine.

Is this a bug or am I doing something wrong here?

**Comment by holance** [comment]
Fixed.
