### ISSUE TITLE
Why can't I put the viewport in a stackpanel [UWP]

### ISSUE THREAD

**Issue by KySpace** [helix-toolkit/helix-toolkit#342]
Whenever I put it in a stackpanel, or canvas, or maybe some other controls that is not a grid, I get unhandled exception. Is it designed to be so or is it a bug? I even try to put the whole thing in a different frame and it doesn't work. What should I do?

**Comment by wky2014** [comment]
A possible fix for this issue is to use measure and arrangement method before getting the ActualHeight and ActualWidth properties, thus avoiding using the properties before they are calculated, which yields only their default values zero, leading to malfunctioning parameters for creating swapchain.

**Comment by JeremyAnsel** [comment]
The exception indicates that the height of the viewport is 0.
You can set the `Width` and `Height` properties of the viewport to avoid that.
