### ISSUE TITLE
Are there any ways to hide half or quarter of a tube (create from TubeVisual3D)?

### ISSUE THREAD

**Issue by DragonPat0219** [helix-toolkit/helix-toolkit#344]
Any methods in HelixToolKit.Wpf can do this?

**Comment by holance** [comment]
Use two TubeVisual3D, each one uses half of the paths, then you can hide either of them.

**Comment by objorke** [comment]
It should be possible to use `ExtrudedVisual3D`. Use a quarter circle for the `Section` property.

**Comment by objorke** [comment]
can we close this issue?
