### ISSUE TITLE
GitVersion is not bumping versions

### ISSUE THREAD

**Issue by kthyholdt** [helix-toolkit/helix-toolkit#356]
I see that the gitversion.yml file is forcing GitVersion to version all builds to 1.0.0. So all packages on MyGet is also called 1.0.0, making it hard to update the packages with NuGet.
Since you have changed to GitVersion and SemVer it might be a good idea to use a develop branch as a default branch, and use master only for stable releases. That way you can let GitVersion do its thing and call the packages 1.0.0-unstable-xxx on MyGet/NuGet making it a lot easier to update the package.

**Comment by objorke** [comment]
agree, let us switch to gitflow. I created `develop` and made it default. Protected `master`.

**Comment by kthyholdt** [comment]
Sounds great. The gitversion.yml file is still causing trouble here. Might be better to delete this, and bump versions using tags.

If you tag the current commit with 'git tag -a v1.0 -m "version 1.0"' and push it 
with 'git push --follow-tags' then the release branch will be tagged as 1.0.0, and develop will be incremented automatically to 1.1.0-unstableXXX.

**Comment by kthyholdt** [comment]
The unstable bumping is working great now. Could you delete the 1.0.0 stable package from MyGet? Since this is marked as stable 1.0.0, NuGet wants to update to this instead of the latest unstable 1.0.0 version. So anyone unfamiliar with this thread will probably just install the "stable" 1.0.0 version and not get any of the updates until stable 1.1 is released.

**Comment by objorke** [comment]
I have unlisted the three 1.0.0 packages
