### ISSUE TITLE
What about an Octree

### ISSUE THREAD

**Issue by Iluvatar82** [helix-toolkit/helix-toolkit#376]
Well, I am still implementing the HalfEdge Datastructure (#336) , but I think this would be really nice and I didn't find an implementation in the package.
We could use an Octree to speed-up quite some things like implementing an automatic "view frustum culling" or speed-up the mouse-hit test a lot (I like to speed things up :) ).

I could have used this in my maser thesis because with a few hundred to thousand shapes the hit-test was sometimes the slowest part of my developed application (even with BoundingBox tests first).

What do you think about it?

Apart from the mentioned applicaitons of the Octrees, it would be simple to also use this for a simple Raycaster.... just sayin' :)

**Comment by objorke** [comment]
This will only help performance when most of the scene is outside the view, right? And if the whole model is fit inside the view, there will be no difference?

**Comment by holance** [comment]
Current implementation seems like to have performance impact if zooms into the scene(most of geometries are actually outside the viewport, but gets a little sluggish during rotation). 
It will be really nice if the automatic "view frustum culling" can help to improve the performance.

**Comment by Iluvatar82** [comment]
@objorke yes that's true. It basically checks if an object lies inside the view frustum and skips rendering for the rest. We could make it optional to avoid any unnecessary calculations (but with a Octree, there are not many...). I implemented it once (without an Octree) for **dynamic cubemap generation** where I needed to render the 6 faces of the cube in a separate pass (long time ago) and in that case it also helped to speed things up really a lot.

@holance I am not quite sure if the zoom-behavior can be solved with view frustum culling, but maybe it will improve things, I don't know in this case

(P.S: at the moment I will focus on the HalfEdge implementation (which already works) and add some features like the possibility to remove geometry / calculate some of the helper functions more easily / some subdivision schemes / ...
I just wanted to know if you would like an Octree / VFC implemented at all :) )

When it comes to culling, there are a lot more more advanced approaches out there also, like CHC++, Portal Culling, etc., also Shadow-Mapping (PCF, VSM, Tiled SM, Trapezoidal SM, LSPSM, Temporal SM...) and AO... Just tell me what you like :) hehe

**Comment by holance** [comment]
@Iluvatar82 I am currently implementing the Octree for hit test. If you have time, we can discuss about its implementation and do it together. I already make the GeometryModel3D working with the octree. 

You can get the source from my fork [Repository](https://github.com/holance/helix-toolkit)

**Comment by holance** [comment]
Initial check in for Octree, refer  to  #408

**Comment by holance** [comment]
Octree has been implemented for variety of geometry models. Close this for now. If further request or implementation needed, please open new issues.
