### ISSUE TITLE
How to turn off anti-aliasing?

### ISSUE THREAD

**Issue by kozintsev** [helix-toolkit/helix-toolkit#378]
Hello!
If you have time, you could not answer the question?
Have any way to control the display quality? For example.
How to turn off anti-aliasing?
Thanks!

**Comment by holance** [comment]
Which version? Is it sharpdx? If it is sharpdx version, set the MSAA = Disable in Viewport3DX.

**Comment by kozintsev** [comment]
I use HelixViewport3D. SharpDX better?

**Comment by holance** [comment]
If wpf, please refer to http://stackoverflow.com/questions/5219835/how-to-using-anti-aliasing-in-wpf-3d.
SharpDX version is still under development, stable version has not been released yet.

**Comment by kozintsev** [comment]
Thanks!
