### ISSUE TITLE
Can I rotate an simple object like I do it with .BeginAnimation under wpf c#?

### ISSUE THREAD

**Issue by GuillermoGorlo** [helix-toolkit/helix-toolkit#392]
Hello, I want to rotate an object with helix only with c# code, in wpf to rotate an image for example I do this 
```csharp
DoubleAnimation da = new DoubleAnimation(); 
            da.From = 0; 
            da.To = 50;
            da.Duration = new Duration(TimeSpan.FromSeconds(10)); 
            RotateTransform rt = new RotateTransform(); 
            Control.RenderTransform = rt;
            rt.BeginAnimation(RotateTransform.AngleProperty, da);
```

I try 

```csharp
 AxisAngleRotation3D ax3d;
            ax3d = new AxisAngleRotation3D(new Vector3D(0, 0, 1),1);
            RotateTransform3D myRotateTransform = new RotateTransform3D(ax3d);
            device3D.Transform = myRotateTransform;
            ax3d.Angle += 32;
```

This code works fine but the object moves from a non-displacement thing that does not happen with doubleanimation. Somebody knows how to move an object with displacement?

**Comment by holance** [comment]
Try to refer the example of Wind Turbine in WPF example. It uses OnCompositionTargetRendering to do the animation.

**Comment by objorke** [comment]
Isn´t this a general WPF question? If it is not a bug or feature request it should be closed, in my opinion.

**Comment by holance** [comment]
Agree. Closed.
