### ISSUE TITLE
3DS file is getting loaded twice (using StudioReader)

### ISSUE THREAD

**Issue by mk48** [helix-toolkit/helix-toolkit#409]
I am using StudioReader to load 3DS file. But it seems the file is getting loaded twice.

```
    public class Machine : GroupModel3D
    {
        public Machine()
        {
            string strFullFilePath = @"C:\Crane.3DS";

            var reader = new HelixToolkit.Wpf.SharpDX.StudioReader();
            var m3dGrp = reader.Read(strFullFilePath);

            foreach (var model in m3dGrp)
            {
                var sharpModel = new MeshGeometryModel3D()
                {
                    Geometry = model.Geometry,
                    Material = model.Material,
                };

                this.Children.Add(sharpModel);
            }

            RotateTransform3D rotate3D = new RotateTransform3D();
            rotate3D.Rotation = new AxisAngleRotation3D(new Vector3D(0, 1, 0), 90);

            Transform3DGroup transform3DGroup = new Transform3DGroup();
            transform3DGroup.Children.Add(rotate3D);

            this.Transform = transform3DGroup;

        }
    }
```

XAML

```
        <hx:Viewport3DX
            Name="viewPort3D"
            ShowCameraInfo="True"
            >

            <hx:AmbientLight3D/>
            <hx:DirectionalLight3D Direction = "-2,-5,-2"/>
            <local3D:Machine></local3D:Machine>

        </hx:Viewport3DX>
```

output:

![image](https://cloud.githubusercontent.com/assets/3082469/21767959/f86153e2-d69c-11e6-811b-42f7c3f5f446.png)

The 3DS file is loaded twice and the the Transform of 90 degree is applied one machine. 

Is that a bug or Am I doing anything wrong here..?

I am using latest version (V1.0.0-unstable1119) built on: 9-Jan-2017

**Comment by holance** [comment]
Did you check if your 3DS file has duplicate models inside? I use FileLoadDemo to load some 3DS files, did not experience this issue.

**Comment by mk48** [comment]
I checked the 3DS file and it's fine. 

Could you please make a small change in the FileLoadDemo code and run? (I am getting some compile errors in Example codes in my system!)

in the 'AttachModelList()' function, change the 'this.ModelTransform' to like the following

```
RotateTransform3D rotate3D = new RotateTransform3D();
rotate3D.Rotation = new AxisAngleRotation3D(new Vector3D(0, 0, 1), 90);
Transform3DGroup transform3DGroup = new Transform3DGroup();
transform3DGroup.Children.Add(rotate3D);
this.ModelTransform.Transform = transform3DGroup;
```

**Comment by holance** [comment]
I made the changes and it is still loading ok. Could you share your 3DS model?

**Comment by holance** [comment]
Seems like your model cut half in the middle for me? Maybe that's why you think it has been loaded twice?

**Comment by mk48** [comment]
below is my 3DS file
[Crane.3DS.zip](https://github.com/helix-toolkit/helix-toolkit/files/695478/Crane.3DS.zip)

below is my sample project which I tried to load 3DS. (VS 2015)
[helix.zip](https://github.com/helix-toolkit/helix-toolkit/files/695483/helix.zip)

**Comment by holance** [comment]
The model did not load twice, it is because you set the transform3DGroup in GroupModel3D, causes the model split into half. If you set transform3DGroup to each MeshGeometryModel3D, everything works fine.

**Comment by mk48** [comment]
It's working fine after your suggestion. Thanks.
