### ISSUE TITLE
Issue with lighting after update #390

### ISSUE THREAD

**Issue by kthyholdt** [helix-toolkit/helix-toolkit#412]
There is an issue with lighting after the update to SharpDX 3.1.1 when using normal maps.

See pictures from lighting example in link below with before and after pictures. in the first two, the issue is most noticeable on the two small balls. On the next two, you can clearly see it on most surfaces.

https://postimg.org/gallery/e51ag9l6/

**Comment by holance** [comment]
Seems like it is caused by not using mipmap properly.

**Comment by holance** [comment]
@JeremyAnsel Seems like there is an issue in SharpDX.Toolkit you port into the project. The mips level is always 1 instead of 11 from old version after loading the bitmap.

**Comment by holance** [comment]
The easy fix is change all maps properties in Material to stream(more versatile, then we can load bmp, dds, jpeg, etc), convert all jpg into dds with mipmap(a lot of tools can do it) and load the dds stream into texture directly. I will check in the changes once I finished. 

If anyone has better ideas, please let me know.
