### ISSUE TITLE
How to display proper error message for DXGI_ERROR_UNSUPPORTED error?

### ISSUE THREAD

**Issue by mk48** [helix-toolkit/helix-toolkit#413]
If I don't have any suitable graphics card (Video card which is not able to handle DirectX operations). I am getting the below error in screen.

```
SharpDX.SharpDXException: HRESULT: [0x887A0004], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_UNSUPPORTED/Unsupported], Message: Unknown
   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.GetSupportedFeatureLevel(Adapter adapter)
   at HelixToolkit.Wpf.SharpDX.DefaultEffectsManager.GetBestAdapter(Int32& bestAdapterIndex)
   at HelixToolkit.Wpf.SharpDX.DefaultEffectsManager..ctor(IRenderTechniquesManager renderTechniquesManager)
   at HelixToolkit.Wpf.SharpDX.DPFCanvas.StartD3D()
   at HelixToolkit.Wpf.SharpDX.DPFCanvas.OnLoaded(Object sender, RoutedEventArgs e)
```

![image](https://cloud.githubusercontent.com/assets/3082469/21845233/d788fee6-d817-11e6-9b2f-979782d1e3b8.png)

Is there anyway to get this error in code and display a message box to user?

something like following

Window load event:

```
if (graphics card not supported )
{
    msgbox ("proper error message to user");
    hide the helix-sharpDX control
}
else
{
    load the 3D model
}
```

**Comment by mk48** [comment]
I got two solutions, but not sure which is better.

solution 1:

```
try
{
    renderTechniquesManager = new DefaultRenderTechniquesManager();
    DefaultEffectsManager ef = new DefaultEffectsManager(renderTechniquesManager);
}
catch(Exception ex)
{
    //video card not supported
}
```

solution 2:
```
try
{
    var fl = SharpDX.Direct3D11.Device.GetSupportedFeatureLevel();
}
catch(Exception ex)
{
    //video card not supported
}
```

in solution 1, 'DefaultEffectsManager' constructor is doing some work to find better adapter. So I hope solution 1 would be better.

Can anyone please suggest which would be the best way of handling this?

**Comment by smischke** [comment]
You can prevent the error message by two ways:
1. By binding the property "Viewport3DX.RenderException" to a property of your view model. "Viewport3DX" detects if the property is bound and will not show the error message if so.
2. By handling the event "Viewport3DX.RenderExceptionOccured"

See: https://github.com/helix-toolkit/helix-toolkit/blob/develop/Source/HelixToolkit.Wpf.SharpDX/Controls/Viewport3DX.cs#L1346
