### ISSUE TITLE
DPFCanvas OnRenderSizeChanged crash Application on Startup

### ISSUE THREAD

**Issue by alanturing88** [helix-toolkit/helix-toolkit#415]
Hi,

I have a issue in DPFCanvas. Sometimes my application crash on startup with error 

_KeyNotFoundException_

in constructor of _DeferredLightingVariables_

I looked into the code and saw that the error happens in the _DPFCanvas.cs_ _OnRenderSizeChanged_ function near line 714.

```
if (RenderTechnique == deferred) //<- RenderTechnique & deferred are null
   {                             // and InitBuffers(...) will be called! 
     deferredRenderer.InitBuffers(this, Format.R32G32B32A32_Float);
   }
if (RenderTechnique == gbuffer)
  {
    deferredRenderer.InitBuffers(this, Format.B8G8R8A8_UNorm);
  }
 ```

I inserted:
```
if (surfaceD3D != null) 
 {
    if (RenderTechnique == null)
                        return;
```

and it is working...

Is that a proper way to resolve that issue?

Regards

Sascha

**Comment by holance** [comment]
I think it should work. I will put this fix in, thanks.
