### ISSUE TITLE
Transparency Help!! See text for detail

### ISSUE THREAD

**Issue by DragonPat0219** [helix-toolkit/helix-toolkit#422]
Can any one tell me why the transparency doesn't work? There are so many grid like image through out the tubes ( shown in image 1. I used  Color.FromArgb(10, 0, 0, 255) to make the tube transparent. I can see the adjacent tubes, but I can't see the grids inside the tube, or I can't even see the grid at the front when I rotated the view (see image 2).

Also, I use TubeVisual3D for the tubes.

![capture_ink_li](https://cloud.githubusercontent.com/assets/23266767/21959596/d86b091a-da99-11e6-9852-50ff39a35184.jpg)
                                                                           **Image 1**
![2](https://cloud.githubusercontent.com/assets/23266767/21959597/de61fc5c-da99-11e6-9827-d6a2fe10f075.PNG)
                                                                            **Image 2**

**Comment by holance** [comment]
Use SortingVisual(will have performance impact) or move the grid visual  in front of tubevisual in xaml.

**Comment by DragonPat0219** [comment]
Could you explain a little bit more? I am new to this. Also, do you know what is the reasons, which are making the transparency doesn't work?
Thanks

**Comment by holance** [comment]
This is a common problem for all graphics rendering. You can search for z buffer and alpha blending for details
