### ISSUE TITLE
SharpDX usage?

### ISSUE THREAD

**Issue by Mmokhtar** [helix-toolkit/helix-toolkit#437]
I used HelixToolkit in my WPF application in order to render some "extremely large" 3D models(up to 5,000,000 points). When I got to that limit, the model got rendered really slowly. Is the HelixToolkit + SharpDX version capable of handling this/ number of points? The SharpDX documentation seems to be all marked as "TODO"... Where should I start??

**Comment by holance** [comment]
Everything has limit. You can try to render this model using SharpDX. But I would suggest to downsample your model, since 5m points may look like the same as 5k points. Or partition your model into many smaller models and render them on demand.

**Comment by Mmokhtar** [comment]
Thank you so much for your fast response. My model is generated by the marching cubes algorithm. The main reason why I am not decimating the mesh is not how it looks like in the program. It is because the model is going to be 3D printed, and I don't want to reduce the quality of the printed model. This is a medical program, and the printed 3D model is going to be used to perform surgeries, so I can't decimate the model.

**Comment by holance** [comment]
You can decimate for displaying only right? You can still use the original model for printing.

**Comment by Mmokhtar** [comment]
How didn't I think about that??! You're a boss! Thank you so much!!

**Comment by Iluvatar82** [comment]
In my experience it is better to have one object containing a lot of points rather than many simple objects. From a performance point-of-view at least. In my master thesis I had thousands of objects at first, but all the render-calls led to a bad performance. Then I merged all models with the same materials and the result rendered much better :)
