### ISSUE TITLE
Camera restriction – suggesting changes in code

### ISSUE THREAD

**Issue by mk48** [helix-toolkit/helix-toolkit#453]
I think camera restriction is not available currently.

I checked the code and made the changes locally.
Can someone please implement the same in the repository?

**Need**
Restrict the camera rotation.
Example: while viewing a car model, don’t allow mouse rotation to go down.

**Changes**
Create 6 new dependency properties
X range – MinX & MaxX
Y range – MinY & MaxY
Z range – MinZ & MaxZ

File: HelixToolkit.Wpf.SharpDX\Controls\Viewport3DX.cs
Function: ViewCubeClicked()
```
            if (newPosition.X >= MinX && newPosition.X <= MaxX && ……..)
            {
                pc.AnimateTo(newPosition, e.LookDirection, e.UpDirection, 500);
            }
```
Function: SetView()
Same if() before AnimateTo()

File: HelixToolkit.Wpf.SharpDX\Controls\MouseHandlers\RotateHandler.cs
Function: RotateTrackball()
```
            if (newPosition.X >= MinX && newPosition.X <= MaxX && ……..)
            {
                this.Camera.LookDirection = newTarget - newPosition;
                if (this.CameraMode == CameraMode.Inspect)
                {
                    this.Camera.Position = newPosition;
                }

                this.Camera.UpDirection = newUpDirection;
            }
```
The same change should be applied in all camera rotation mode.

**Comment by holance** [comment]
I think you can bind the camera position and do the limit in viewmodel

**Comment by mk48** [comment]
I set like following, but the CameraPosition is not getting sett in ViewModel.
I put break-point in CameraPosition property in ViewModel but is not getting hit.

```
        <HX:Viewport3DX CameraRotationMode="Trackball" >          
            <HX:Viewport3DX.Camera>                
                <HX:PerspectiveCamera Position="{Binding CameraPosition}" 
                                                  UpDirection="{Binding CameraUpDirection}"
                                                  LookDirection="{Binding CameraLookDirection}"
                                                  FarPlaneDistance="100000"/>
            </HX:Viewport3DX.Camera>
        </HX:Viewport3DX>
```

**Comment by holance** [comment]
You need to check the debug output for any binding errors. Make sure position type is System.Window.Media3D.Point3D

**Comment by mk48** [comment]
There is no binding error and the Position type is System.Windows.Media.Media3D.Point3D

Viewmodel construction I can set the position and the camera is set to that position.
After that, If I rotate using mouse then it doesn't affect the ViewModel's position property.

**Comment by mk48** [comment]
May I do pull request for this enhancement ?

**Comment by holance** [comment]
I am actually doing the position binding without any problem. You can try to refer to the example DynamicTextureDemo to bind the camera and setup your position binding using code behind.

**Comment by mk48** [comment]
TwoWay binding is working fine

```
 <HX:PerspectiveCamera Position="{Binding CameraPosition, Mode=TwoWay}" 
                                                  UpDirection="{Binding CameraUpDirection, Mode=TwoWay}"
                                                  LookDirection="{Binding CameraLookDirection, Mode=TwoWay}"
                                                  FarPlaneDistance="100000"/>
```

by default WPF has two-way binding, but I don't know how this is not working if 'Mode' is not specified in XAML.

**Comment by mk48** [comment]
I am still having small issue, 

I can restrict the camera position in ViewModel's set property, but the camera's Target is getting changed while rotating.

@holance Could you please share your code for camera restriction?

**Comment by holance** [comment]
Do you mean you want to restrict the camera rotation angle?

**Comment by mk48** [comment]
Yes, I want to control the rotation angle.

for an example, I have a car model and want to control the camera that should not go down.

**Comment by mk48** [comment]
I want to do the following. I have a car model and should not allow the camera to look from bottom.

If you have solution for this please share. If not please consider my proposed solution.

![image](https://cloud.githubusercontent.com/assets/3082469/24603240/9ee31760-187d-11e7-85ff-44d9d2b9fc8f.png)

**Comment by holance** [comment]
Seems like what you need is to restrict camera position

**Comment by mk48** [comment]
yes, I did what you suggested (control camera position in view model), while doing the camera target is getting changed. So I don't know what's the proper solution for this. If you have any, please share.

**Comment by holance** [comment]
A temp solution would be (if using LightingDemo). If up direction is 0,1,0

        private Point3D cameraLocation = new Point3D(8, 9, 7);
        public Point3D CameraLocation
        {
            set
            {            
                if (value.Y < 0)
                {
                    cameraLocation = new Point3D(cameraLocation.X, 0, cameraLocation.Z);
                    OnPropertyChanged();
                }
                else
                {
                    SetValue(ref cameraLocation, value, nameof(CameraLocation));
                }
            }
            get
            {
                return cameraLocation;
            }
        }

        private Vector3D lookDirection = new Vector3D(-5, -12, -5);
        public Vector3D LookDirection
        {
            set
            {            
                if (CameraLocation.Y <= 0)
                {
                    lookDirection = -new Vector3D(cameraLocation.X, cameraLocation.Y, cameraLocation.Z);
                    OnPropertyChanged();
                }
                else
                {
                    SetValue(ref lookDirection, value, nameof(LookDirection));
                }               
            }
            get
            {
                return lookDirection;
            }
        }

        private Vector3D upDirection = new Vector3D(0,1,0);
        public Vector3D UpDirection
        {
            set
            {
                var look = upDirection;
                if (CameraLocation.Y <= 0)
                {
                    upDirection = new Vector3D(0, 1, 0);
                    OnPropertyChanged();
                }
                else
                {
                    SetValue(ref upDirection, value, nameof(UpDirection));
                }
            }
            get
            {
                return upDirection;
            }
        }

You can also limit by create a custom camera.

**Comment by mk48** [comment]
I created a custom camera, but still not helping.

when i simply rotate, the object goes down (target is getting changed)
see the below screen.

![rotate](https://cloud.githubusercontent.com/assets/3082469/24857690/cf7c3026-1e06-11e7-8fbe-18bc37c2594d.gif)

Below is my code.
Could you please copy paste the same in a new project and try to figure it...?!

MainWindow.Xaml

```
<Window x:Class="HelixCameraControl.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:HelixCameraControl"
        mc:Ignorable="d"
        xmlns:HX="clr-namespace:HelixToolkit.Wpf.SharpDX;assembly=HelixToolkit.Wpf.SharpDX"
        Title="MainWindow" Height="350" Width="525">
    <Grid>
        <HX:Viewport3DX Name="viewPort3Dx"
                        CameraRotationMode="Trackball"  
                        RenderTechnique="{Binding RenderTechnique}"
                        ZoomDistanceLimitFar="200"
                        Camera="{Binding MyCamera}"
                        ShowCameraInfo="True"
                        >
            
            <HX:AmbientLight3D Color="1,1,1,1"/>
            <HX:DirectionalLight3D Direction="2,2,10" />
            <HX:DirectionalLight3D Direction="-2,-1,1" />
            
            <HX:MeshGeometryModel3D Geometry="{Binding MGeometryModel}" 
                                    Transform="{Binding MTransform}" 
                                    Material="{Binding MMaterial}"/>
        </HX:Viewport3DX>
    </Grid>
</Window>
```


MainViewModel.cs
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using HelixToolkit.Wpf.SharpDX;
using Media3D = System.Windows.Media.Media3D;

namespace HelixCameraControl
{
    class MainViewModel : Notify
    {
        private RenderTechnique renderTechnique;

        private MeshGeometry3D mGeometryModel;
        private Media3D.Transform3D mTransform;
        private PhongMaterial mMaterial;

        public MainViewModel()
        {
            //// ----------------------------------------------------- Render techniques -----------------------------------------------------
            this.RenderTechniquesManager = new DefaultRenderTechniquesManager();
            this.RenderTechnique = this.RenderTechniquesManager.RenderTechniques[DefaultRenderTechniqueNames.Blinn];

            this.MyCamera = new MyRestrictedCamera();

            //------------- Box
            var mb = new MeshBuilder();
            mb.AddBox(new SharpDX.Vector3(0, 0, 0), 5, 5, 5);
            this.MGeometryModel = mb.ToMeshGeometry3D();
            this.MMaterial = new PhongMaterial
            {
                DiffuseColor = SharpDX.Color.Yellow,
                AmbientColor = SharpDX.Color.Black,
                ReflectiveColor = SharpDX.Color.Yellow
            };
            this.MTransform = new Media3D.TranslateTransform3D(0, 0, 0);
        }

        public IRenderTechniquesManager RenderTechniquesManager { get; protected set; }

        public RenderTechnique RenderTechnique
        {
            get
            {
                return this.renderTechnique;
            }

            set
            {
                this.renderTechnique = value;
                this.OnPropertyChanged(nameof(this.RenderTechnique));
            }
        }

        public MyRestrictedCamera MyCamera { get; set; }


        public MeshGeometry3D MGeometryModel
        {
            get
            {
                return this.mGeometryModel;
            }

            set
            {
                this.mGeometryModel = value;
                this.OnPropertyChanged(nameof(this.MGeometryModel));
            }
        }

        public Media3D.Transform3D MTransform
        {
            get
            {
                return this.mTransform;
            }

            set
            {
                this.mTransform = value;
                this.OnPropertyChanged(nameof(this.MTransform));
            }
        }

        public PhongMaterial MMaterial
        {
            get
            {
                return this.mMaterial;
            }

            set
            {
                this.mMaterial = value;
                this.OnPropertyChanged(nameof(this.MMaterial));
            }
        }
    }
}

```

MyRestrictedCamera.cs
```

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Media.Media3D;

namespace HelixCameraControl
{
    public class MyRestrictedCamera : HelixToolkit.Wpf.SharpDX.PerspectiveCamera
    {
        private Vector3D up;
        private Vector3D look;

        public override Point3D Position
        {
            get
            {
                return base.Position;
            }

            set
            {
                if (value.Z >= 0)
                {
                    base.Position = value;
                }
            }
        }
        public override Vector3D LookDirection
        {
            get
            {
                return base.LookDirection;
            }

            set
            {
                if (base.Position.Z >= 0)
                {
                    this.look = value;
                    base.LookDirection = value;
                }
                else
                {
                    base.LookDirection = this.look;
                }
            }
        }

        public override Vector3D UpDirection
        {
            get
            {
                return base.UpDirection;
            }

            set
            {
                if (base.Position.Z >= 0)
                {
                    this.up = value;
                    base.UpDirection = value;
                }
                else
                {
                    base.UpDirection = this.up;
                }
            }
        }
    }
}

````

Notify.cs

```
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HelixCameraControl
{
    public class Notify : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged(string info)
        {
            this.PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(info));
        }
    }
}

```

**Comment by mk48** [comment]
I am suggesting a nice and clean solution for this problem

1. Before assigning a new position to camera, call a action/delegate/event with new position as a parameter.
2. That event can be handled in ViewModel.
3. User can validate the new position and set "e.Handled = True" if restricted.
4. Back to our code, check e.Handled value, if allowed then set the new position.

More details:
That event should be triggered from RotateHandler.cs

- RotateTurnball()
- RotateTurntable()
- RotateTrackball()

In the above functions after got the 'newPosition', call the event then check the e.Handled then proceed further.

Also the event should be triggered from CameraExtensions.AnimateTo() function.

If the suggested solution is OK then please implement the same else may I do pull request?

**Comment by holance** [comment]
Try this

    public class CustomCamera : PerspectiveCamera
    {
        public override Point3D Position
        {
            set
            {
                if (value.Y < 0)
                {
                    base.Position = new Point3D(base.Position.X, 0, base.Position.Z);
                }
                else
                {
                    base.Position = value;
                }
            }
            get
            {
                return base.Position;
            }
        }

        public override Vector3D LookDirection
        {
            set
            {
                if (Position.Y <= 0)
                {

                }
                else
                {
                    base.LookDirection = value;
                }
            }
            get
            {
                return base.LookDirection;
            }
        }

        public override Vector3D UpDirection
        {
            set
            {
                if (Position.Y <= 0)
                {

                }
                else
                {
                    base.UpDirection = value;
                }
            }
            get
            {
                return base.UpDirection;
            }
        }
    }

**Comment by mk48** [comment]
@holance thanks for the code:thumbsup:, but still having some glitz while rotating.:worried:

However, I managed like the following, It's working fine and having one small problem.:pensive:

After window loads, if ctrl+E (zoom extends) is pressed without start rotating then the whole model is getting disappeared including the view cube 

```
namespace HelixCameraControl
{
    public class MyRestrictedCamera : HelixToolkit.Wpf.SharpDX.PerspectiveCamera
    {
        private Vector3D newLookDir;
        private bool isLocked;

        public MyRestrictedCamera()
        {
            base.Position = new Point3D(20, 20, 20);
            base.LookDirection = new Vector3D(-20, -20, -20);
            base.UpDirection = new Vector3D(0, 1, 0);
        }
        
        public override Point3D Position
        {
            get
            {
                return base.Position;
            }

            set
            {
                if (value.Z >= 0)
                {
                    base.LookDirection = this.newLookDir;
                    base.Position = value;
                    this.isLocked = false;
                }
                else
                {
                    this.isLocked = true;
                }
            }
        }
        public override Vector3D LookDirection
        {
            get
            {
                return base.LookDirection;
            }

            set
            {
                this.newLookDir = value;
            }
        }

        public override Vector3D UpDirection
        {
            get
            {
                return base.UpDirection;
            }

            set
            {
                if (!this.isLocked)
                {
                    base.UpDirection = value;
                }
            }
        }

    }
}

```

**Comment by holance** [comment]
Because you did not set the base.LookDirection at the beginning. So the base.LookDirection = 0,0,0. which causes error.

**Comment by mk48** [comment]
@holance Yes, I didn't set the LookDirection at first :sunglasses:, because when a new position is set, lookdirection is assigned first then only position and upDirection is set `RotateHandler.RotateTrackball()` so when I get a new lookDirection, it is just saved in a private variable; in position set, position is validated and if that's ok then assign the previously stored lookDirection to it's base. :wink:

lookDirection is not set first always, that's the problem.
in `CameraExtensions.AnimateTo()` position is set first :sweat:
so 'ZoomtoExtends' and view cube click having problems.

but now I have done some small changes to fix that too.
below code is working fine :thumbsup:

 ```
public class MyRestrictedCamera : HelixToolkit.Wpf.SharpDX.PerspectiveCamera
    {
        private Vector3D oldLookDir;
        private bool isLocked;

        public MyRestrictedCamera()
        {
            base.Position = new Point3D(20, 20, 20);
            base.LookDirection = new Vector3D(-20, -20, -20);
            base.UpDirection = new Vector3D(0, 1, 0);
        }        
        
        public override Point3D Position
        {
            get
            {
                return base.Position;
            }

            set
            {
                if (value.Z >= 0)
                {
                    base.Position = value;
                    this.isLocked = false;
                }
                else
                {
                    this.isLocked = true;
                    base.LookDirection = this.oldLookDir;
                }
            }
        }
        public override Vector3D LookDirection
        {
            get
            {
                return base.LookDirection;
            }

            set
            {
                this.oldLookDir = base.LookDirection;
                base.LookDirection = value;
            }
        }

        public override Vector3D UpDirection
        {
            get
            {
                return base.UpDirection;
            }

            set
            {
                if (!this.isLocked)
                {
                    base.UpDirection = value;
                }
            }
        }

    }
```

**Comment by mk48** [comment]
@holance Is it a good way of controlling camera position? or any idea to make the changes in source? If source change is required then I will keep this open else close.

**Comment by holance** [comment]
I think it is good for now. May need a lot of changes if we really need to support more sophisticated camera control like in those game engines.

**Comment by mk48** [comment]
Ok, I will close this for now.
