### ISSUE TITLE
Does IHitable interface need to inherit the IInputElement and IVisible interfaces (SharpDX)?

### ISSUE THREAD

**Issue by kthyholdt** [helix-toolkit/helix-toolkit#456]
The question is in the title.
The IInputElement makes it a mess to implement the IHitable interface for custom models, and I can't see from the code that it is needed. I've tried to remove it, and hit testing still works as it should.

Is this something that is left over from the old implementation? And can it be removed?

**Comment by holance** [comment]
Yes, we don't need it to be specified in IHitable. It has been included in FrameworkElement, which is the base class of all models.
