### ISSUE TITLE
OrthographicCamera is broken (SharpDX)

### ISSUE THREAD

**Issue by Raukk** [helix-toolkit/helix-toolkit#467]
I am trying to use an Orthographic camera but it doesn't draw correctly.

To test I added it to TemplateDemo.
Added Code:
            <hx:Viewport3DX.Camera>
                <hx:OrthographicCamera NearPlaneDistance="0.1" FarPlaneDistance="Infinity" Position="20,0,0" LookDirection="1,0,0" UpDirection="0,0,1" Width="20"/>
            </hx:Viewport3DX.Camera>

It draws the first object (sphere) is on top even though from the side view it should be in the middle with a cube on top.
 
![ortho](https://cloud.githubusercontent.com/assets/11621499/24583134/70be0750-1706-11e7-9a1b-9ee390eff2b1.png)

**Comment by holance** [comment]
Could you upload the side view screen shot? Thanks.

**Comment by Raukk** [comment]
Literally only changed those 3 lines.
Maybe my DirectX is buggered, I had the Windows 10 issue at first.

![ortho](https://cloud.githubusercontent.com/assets/11621499/24684103/34994734-1969-11e7-997e-c6a2f02b2b07.png)


`<Window x:Class="TemplateDemo.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:hx="http://helix-toolkit.org/wpf/SharpDX"
        Title="Template demo" Height="350" Width="525">
    <Window.Resources>
        <DataTemplate x:Key="Template1">
            <hx:MeshGeometryModel3D Geometry="{Binding Geometry}" Transform="{Binding Transform}" Material="{Binding Material}"/>
        </DataTemplate>
    </Window.Resources>
    <Grid>
        <hx:Viewport3DX >
            <hx:Viewport3DX.Camera>
                <hx:OrthographicCamera NearPlaneDistance="0.1" FarPlaneDistance="Infinity" Position="20,0,0" LookDirection="1,0,0" UpDirection="0,0,1" Width="20"/>
            </hx:Viewport3DX.Camera>
            <hx:AmbientLight3D />
            <hx:DirectionalLight3D Direction = "-2,-5,-2"/>
            <hx:ItemsModel3D ItemTemplate="{StaticResource Template1}" ItemsSource="{Binding Items}"/>
        </hx:Viewport3DX>
    </Grid>
</Window>
`

**Comment by holance** [comment]
Ok, there is a bug when using FarPlaneDistance = Infinity. Try to set to a large number instead of Infinity

**Comment by holance** [comment]
<hx:OrthographicCamera NearPlaneDistance="0.1" FarPlaneDistance="1000" Position="20,0,0" LookDirection="-20,0,0" UpDirection="0,1,0" Width="20"/>

This should works as expected.

**Comment by Raukk** [comment]
It does fix it.
Sadly, a lot of stackoverflow questions say to use Infinity (because of clipping).

**Comment by holance** [comment]
Not necessarily true. In orthographic camera, if the far plane becomes infinity, the depth test floating point precision will become inaccurate (since the near/far plane are scale into 0-1 range). That's why you saw the ball is in front of the box.

**Comment by Raukk** [comment]
Intriguing, but not easily apparent for someone new to Helix.
Would it be possible to throw an ArgumentException, or NotFiniteNumberException, or similar if either the near or far plane are set to Infinity/NegativeInfinity on an Orthographic Camera. Have the Exception message explain the "near/far plane are scale into 0-1 range" to anyone who assumes that near/far plane would work the same for Perspective and Orthographic.

**Comment by holance** [comment]
I will fix both. Perspective camera allows infinity, but needs special handling. Thanks for finding the bug :)

**Comment by Raukk** [comment]
No problem, glad I could help. Thanks for your work on this great Toolkit.
