### ISSUE TITLE
Run animations from file

### ISSUE THREAD

**Issue by paytime** [helix-toolkit/helix-toolkit#469]
Greetings,

Is it possible to create a model AND animate it in a 3D-program first and then run the same animation in code or is the only way of animating here by doing it in the code directly?

Best regards!

**Comment by holance** [comment]
Do you mean creating animation in software like Maya and run in Helix Toolkit?

**Comment by paytime** [comment]
Yes

**Comment by holance** [comment]
I think currently helix toolkit does not have these kind of animation interpreter yet.

**Comment by mk48** [comment]
@paytime direct animation from model is not supported yet.
Please use 'Transform3DGroup' in code to animate.

**Comment by paytime** [comment]
Ok thx for your answers!

Best regards
