### ISSUE TITLE
How to use tile images in Material ?

### ISSUE THREAD

**Issue by mk48** [helix-toolkit/helix-toolkit#471]
In Helix-SharpDX
I have a small size image and want to display in floor model as 'tiles'.
How to display image as tiles in a model?

Below lines from LightingDemo
```
            this.FloorMaterial = new PhongMaterial
            {
                AmbientColor = Color.Gray,
                DiffuseColor = new Color4(0.75f, 0.75f, 0.75f, 1.0f),
                SpecularColor = Color.White,
                SpecularShininess = 100f,
                DiffuseMap = new FileStream(new System.Uri(@"TextureCheckerboard2.jpg", System.UriKind.RelativeOrAbsolute).ToString(), FileMode.Open),
                NormalMap = ModelMaterial.NormalMap
            };
```

In Helix-WPF we can do that using Brush, but how to do in SharpDX?
like following,

![image](https://cloud.githubusercontent.com/assets/3082469/25270154/304a3db4-269d-11e7-91a6-7fe780c0ebb6.png)

**Comment by holance** [comment]
For lighting demo. Add following code before b2.ToMeshGeometry3D to create tiles. Basically you need to set texture coordinates larger than 1 to create repeating effect.

for(int i=0; i<b2.TextureCoordinates.Count; ++i)
            {
                b2.TextureCoordinates[i] = new Vector2(b2.TextureCoordinates[i].X * 10, b2.TextureCoordinates[i].Y * 10);
            }
