### ISSUE TITLE
Issue creating polygons

### ISSUE THREAD

**Issue by imekon** [helix-toolkit/helix-toolkit#472]
I've attached files that shows an issue with polygons with MeshBuilder

[HelixMeshIssue.zip](https://github.com/helix-toolkit/helix-toolkit/files/947285/HelixMeshIssue.zip)

Instead of getting a simple flat strip, I get flickering shapes as extra triangles added?

**Comment by holance** [comment]
You need to add polygon for every 3 positions. Otherwise it will use all vertices to create a trianglefan.
Something like this:

for(int i=0; i<_points.count; i+=3)
meshBuilder.AddPolygon(_points.skip(i).take(3));

**Comment by imekon** [comment]
This works for me:

`var triangles = MathsLibrary.Triangulate(surface.Points);

foreach (var triangle in triangles)
{
      meshBuilder.AddTriangle(triangle.Points[0], triangle.Points[1], triangle.Points[2]);
}`

Luckily I have a polygon to triangle library 8)

AddPolygon works for smaller "simpler" polygons.
