### ISSUE TITLE
OBJ File Invalid polygon

### ISSUE THREAD

**Issue by farhankhwaja** [helix-toolkit/helix-toolkit#473]
I tried importing an OBJ file using HelixToolkit WPF and while doing so I get the below error:

`Invalid polygon.`

But when I open this file in Unity/Assimp Viewer everything loads fine and i don't see any error there. Is this specific to Helix??

I have attached the files. 
[Aventador.zip](https://github.com/helix-toolkit/helix-toolkit/files/963167/Aventador.zip)

The details of the model are:
Vertices : 341634
Triangles : 182324

**Comment by JeremyAnsel** [comment]
'Avent.mtl' contains invalid map file paths.
