### ISSUE TITLE
Cannot create an instance of "Visual3DCollection".

### ISSUE THREAD

**Issue by glasspusher** [helix-toolkit/helix-toolkit#474]
I have recently upgraded to VS 2017.  After using it for awhile I get this error, though it doesn't break the build or cause a program crash.  Program works just fine.  See screen shot for a visual.

![screenshot](https://cloud.githubusercontent.com/assets/11830911/25546149/a83798a2-2c16-11e7-9b00-c9684434a441.png)

So a few things.  i had to change target from any cpu to x64 for a math library I'm using, and doing that broke some stuff but was easily fixed, I had to allow .NET v2.0 to be called from v4.0.

When I went to make some gui changes I noticed the squiggles, I didn't catch it before because the program still worked.

So after some digging I think this happens because the designer runs the constructor for helix whenever it needs to display it in design mode. Within its constructor, something throws an exception. Sometimes this does not mean necessarily that the exception will be thrown during runtime. So I think we need a way to allow the designer show the window but also not alter the code that runs correctly at runtime.

Maybe something like:

```
public Constructor()
{
    InitializeComponent();
    if (!System.ComponentModel.DesignerProperties.GetIsInDesignMode(this))
    {
        //Code that throws the exception
    }
}
```

I haven't tried this yet as I am running the current NuGet package.  I'll clone the repo and make this change and test.  The only thing this might break is you have a scene built in the xaml, it wont show at design time.

If I switch to x86 and rebuild, I don't get the error, but it seems that I need to switch targets and clean/rebuild to get it to work.

Other things:
Win10
VS 2017
helixtoolkit.wpf 2015.1.715.0

Thanks, let me know if anymore info is needed.

**Comment by randolpho** [comment]
I have the same problem in VS 2015. 

I suspect the issue may be that HelixViewport3D wraps a viewport and has the Children property wrap the viewport's Children property, but doesn't offer a setter property. 

```C#
        public Visual3DCollection Children
        {
            get
            {
                return this.viewport.Children;
            }
        }
```
[Source](https://github.com/helix-toolkit/helix-toolkit/blob/develop/Source/HelixToolkit.Wpf/Controls/HelixViewport3D.cs#L1295-L1301)

However, just wrapping the viewport's setter may not do the trick, as HelixViewpord3D *also* makes use of the Children property in the constructor:

```C#
            this.viewport = new Viewport3D();
            // headlight
            this.lights = new Model3DGroup();
            this.viewport.Children.Add(new ModelVisual3D { Content = this.lights });
```
[Source](https://github.com/helix-toolkit/helix-toolkit/blob/develop/Source/HelixToolkit.Wpf/Controls/HelixViewport3D.cs#L1010)

The lights would be lost as XAML loads, instantiating and setting the children property.

**Comment by Enduteri** [comment]
I have same issue in VS2015, changing target cpu to x86 fixes the problem but like in my case I need to use it along other x64 library

**Comment by vova1987** [comment]
Confirmed to be happening on VS 2015 with target x64.
Are there any workarounds?

**Comment by holance** [comment]
Visual studio has issue with xaml under x64, not Helix toolkit issue. Close for now.
