### ISSUE TITLE
Names of models

### ISSUE THREAD

**Issue by Chesh02** [helix-toolkit/helix-toolkit#483]
Hi, i'm new with HelixToolKit and i have an issue.
I have a model with different small models and names on it.
Now i have model viewer.
I want to search small models and highlight it.
How to do this?
I didn't found any "name" parameter in Model3D.

**Comment by xlp100** [comment]
hi Chesh02 ：
 you can use DependencyProperty  to  define a field. 
eg:
 model.SetValue(GeomertyDependencyProperty.NameProperty, "your_value");
