### ISSUE TITLE
Artifacts, shader bugs ?

### ISSUE THREAD

**Issue by N4rk0** [helix-toolkit/helix-toolkit#488]
Try the environment mapping demo, SharpDX mode.
Graphic board Geforce GTX 965M.
![helixtoolkitbug](https://user-images.githubusercontent.com/180771/26967103-3ff031f2-4cfd-11e7-9029-33c7e0578529.PNG)
In this picture you can see that one part of the model is not correctly rendered. It's very clear if you use a transparent material like this but it's still there if you use a solid material ( you will notic some small crackes ).
Does this happen only to me?

**Comment by smischke** [comment]
Looks like there is some kind of threshold angle. Maybe shininess?

**Comment by N4rk0** [comment]
It's just default material defined in PhongMaterials, i didn't change anything

**Comment by N4rk0** [comment]
Also if you use solid material there are artifacts.
![helixtoolkitbug2](https://user-images.githubusercontent.com/180771/27029836-471ae6ce-4f6a-11e7-991d-0f6b39036b22.PNG)

**Comment by holance** [comment]
It is caused by the MSAA. Disable IsMultisampleEnabled on MeshGeometryModel3D will fix it.
Suggest to disable IsMultisampleEnabled on all models which does not have obvious aliasing issue.

**Comment by N4rk0** [comment]
Setting IsMultisampleEnabled to false solved the issue for Copper material but the result didn't change for obsidian (first picture).

**Comment by holance** [comment]
Graphics debugger only works for native c++, not managed code

**Comment by JeremyAnsel** [comment]
Does the graphics debugger work if you remove `UseDefaultGestures` and `Viewport3DX.InputBindings` in `EnvironmentMapDemo\MainWindow.xaml`?

**Comment by holance** [comment]
For the first issue. Because you unchecked the Render Environment Map. So the map is not rendered on the mesh. The mesh becomes semi transparent due to the material you selected, and the back of the mesh is causing the visual artifacts. 

To avoid this kind of artifacts, set the CullMode = Back on the MeshGeometryModel3D. You need to install the SharpDX.Direct3D11 nuget package to see the option in xaml.

**Comment by N4rk0** [comment]
Yes, i just found it this morning and i was going to write it here.
Probably it depends on which order the triangles are are rendered.
You see are darker surface when backside triangles are rendered first ( and so they are sampled when the front side triangles are rendered ) so enabling back face culling solves the issue.

As for the Graphic Debugger, you can actually use it for .net projects, try it with vanilla sharpDX project or MonoGame...it works.

**Comment by holance** [comment]
Because WPF needs to use D3DImage to present instead of using native SwapChain, the debugger won't work. Really hope microsoft can update the wpf architecture, but seems like they are more focusing on the other areas.

**Comment by N4rk0** [comment]
I think that this issue can be closed :)

**Comment by wgnheart** [comment]
@frabul  I have the same issue on my program. But enabling face culling does solve it completely, there still has few artifacts. And is it nvidia's bug? Because it does not happen on intel's card.

**Comment by holance** [comment]
> @frabul I have the same issue on my program. But enabling face culling does solve it completely, there still has few artifacts. And is it nvidia's bug? Because it does not happen on intel's card.

Try to enable back face culling.

**Comment by wgnheart** [comment]
> > @frabul I have the same issue on my program. But enabling face culling does solve it completely, there still has few artifacts. And is it nvidia's bug? Because it does not happen on intel's card.
> 
> Try to enable back face culling.

My fault, I lost "not". I have already try to enable back face culling. Most of artifacts disappear, but there still has few artifacts. 

Why it only happen on Nvidia cards?

**Comment by holance** [comment]
> > > @frabul I have the same issue on my program. But enabling face culling does solve it completely, there still has few artifacts. And is it nvidia's bug? Because it does not happen on intel's card.
> > 
> > 
> > Try to enable back face culling.
> 
> My fault, I lost "not". I have already try to enable back face culling. Most of artifacts disappear, but there still has few artifacts.
> 
> Why it only happen on Nvidia cards?

Are you using MSAA?

**Comment by wgnheart** [comment]
Yes, I enable MSAA. I want to solve the artifacts problem when MSAA enabled.
