### ISSUE TITLE
How to load .obj files using wpf application? 

### ISSUE THREAD

**Issue by psvramaraju** [helix-toolkit/helix-toolkit#490]
Hello!!! 
I am working on importing 3d .obj files using helix toolkit in wpf form. But I am unable to do it. I am able to load 3d .stl files successfully. Can someone help me in getting through this. 

Here is my code:

using HelixToolkit.Wpf;
using System;
using System.IO;
using System.Windows;
using System.Windows.Input;
using System.Windows.Media.Media3D;
namespace Display3DModel
{
    public partial class MainWindow : Window
    {
        private const string MODEL_PATH = "D:/vs/display3D-master/Display3DModel/bicycle.stl";
        public object FilDia { get; private set; }
        public MainWindow()
        {
            InitializeComponent();
            Model3DGroup MdlGrp = null; 

            ModelVisual3D device3D = new ModelVisual3D();
            device3D.Content = Display3d(MODEL_PATH);
            // Add to view port
            viewPort3d.Children.Add(device3D);
         
        }
        private Model3D Display3d(string model)
        {
            Model3D device = null;
            try
            {
                Console.WriteLine("Hello!!!");        
                viewPort3d.RotateGesture = new MouseGesture(MouseAction.LeftClick);                        
                ModelImporter import = new ModelImporter();  
                device = import.Load(model);
            }
            catch (Exception e)
            {
                MessageBox.Show("Exception Error : " + e.StackTrace);
            }
            return device;
        }   
    }
}

**Comment by zhongbodong** [comment]
maybe you should replace Model3D to Model3DGroup

**Comment by zhongbodong** [comment]
`  public MainWindow()
        {
            InitializeComponent();
            ModelImporter import = new ModelImporter();
            Model3DGroup model1 = import.Load(@"C:\Users\Administrator\Desktop\test\file.3ds");
            model.Content = model1;
        }`
xmal:
`  <helix:HelixViewport3D >
            <helix:HelixViewport3D.Camera>
                <PerspectiveCamera  />
            </helix:HelixViewport3D.Camera>
            <helix:DefaultLights></helix:DefaultLights>
            <ModelVisual3D x:Name="model"></ModelVisual3D>
        </helix:HelixViewport3D>`
it works

**Comment by mk48** [comment]
@psvramaraju  is it solved the problem? if yes then please close this thread :+1:
