### ISSUE TITLE
How to load STL file in Helixtoolkit.SharpDX?

### ISSUE THREAD

**Issue by pipited07** [helix-toolkit/helix-toolkit#509]
Hello! Everyone.I'm using Helixtoolkit in my c# WPF project. And It seems my model is so huge that the performance is very bad.(I loaded a human skull model). Here is the way I load the model

```
ModelImporter import = new ModelImporter();
_modleGroup = import.Load(modelpath);
```
I want to use Helixtoolkit.SharpDX to show the model in Viewport3DX, I think it will be better on performance.

The sample code only can load.obj and .3ds file. I tried to load the stl file but got error(return garbled message).It seems Helixtoolkit.SharpDX doesn't provide the STLReader like:

```
var reader = new StudioReader();
var reader = new ObjReader();
```
Does anyway to load the STL file in Viewport3DX?

**Comment by holance** [comment]
What's your model size? If your model contains many small models, try to merge them into single large model. You can also convert WPF model into SharpDX model very easily. Just an array copy.

**Comment by pipited07** [comment]
@holance  My model is about 1.6million triangles. Could you teach me how to convert WPF model into the SharpDX? I can read stl file by the function from Helixtoolkit.WPF which return the Model3DGroup but I don't know how to convert it  into the  List<Object3D>.  Object3D is one class in the Helixtoolkit.WPF.sharpDX. Actually, I have never used SharpDX, so if you know the way to load a STL model in Viewport3DX. Hope you can teach me , I will very appreciate!

**Comment by holance** [comment]
Model3DGroup has children, it is the list of all child models. You can easily convert a model used in WPF into MeshGeometry3D used in HelixToolKit SharpDX version. 

The problem is do you really need to display all the models with 1.6m triangles at the same time?

**Comment by pipited07** [comment]
@holance  Thank for your reply. Yes, I need to display all the models in the same time. Actually, I tried to simplify the triangular mesh and the performance is very good. but I can't let user to simply model everytime  use my program. As if your opinion, I read the sample code FileLoadDemo in HelixToolKit SharpDX. HelixToolKit SharpDX used the MeshGeometryModel3D , which is  a self define object. Is it similar between MeshGeometry3D and MeshGeometryModel3D ?

**Comment by holance** [comment]
It is very similar.

**Comment by pipited07** [comment]
@holance   Thanks for your reply. I convert the model into one major ,so the Children in Model3DGroup  actually only have one. Here is the code. I don't know if I misunderstanding your suggestion.
I really don't know how to transform between between MeshGeometry3D and MeshGeometryModel3D.
Could you tell me how to modify the two line below  in comment?  Sorry for the trivial question.

```
StLReader r = new HelixToolkit.Wpf.StLReader();
Model3DGroup model3dgroup = r.Read(path);

            for (int i = 0; i < model3dgroup.Children.Count; i++) 
            {
                System.Windows.Media.Media3D.GeometryModel3D temp = model3dgroup.Children[i] as System.Windows.Media.Media3D.GeometryModel3D;
                var s = new MeshGeometryModel3D
                {                    
                    //Geometry = temp.Geometry,
                    //Material = temp.Material,
                };
                this.ModelGeometry.Add(s);
                s.Attach(modelView.RenderHost);
            }
```

**Comment by holance** [comment]
Copy System.Windows.Media.Media3D.MeshGeometry3D positions(double), indices, normals to HelixToolkit.WPF.SharpDX.MeshGeometry3D positions(float), indices, normals. You also need to convert material to PhongMaterial in SharpDX version.

**Comment by pipited07** [comment]
@holance  Thanks for your instruction. Now I radically fix my problem. Thank you for the time and patience you help solve my problem. I really appreciate that.

**Comment by holance** [comment]
No problem.

**Comment by jj21065** [comment]
What a critical issue!
