### ISSUE TITLE
HelixToolkit.Wpf.SharpDX refers SharpDX.Mathematics v4.0.1.0 but default installation refers v3.1.1.0

### ISSUE THREAD

**Issue by mk48** [helix-toolkit/helix-toolkit#514]
having below compilation error in the latest version

![image](https://user-images.githubusercontent.com/3082469/28571257-a405fcc2-715f-11e7-8a24-8ad01d9d4dbe.png)

Error: CS1705
Assembly 'HelixToolkit.Wpf.SharpDX' with identity 'HelixToolkit.Wpf.SharpDX, Version=1.0.0.0, Culture=neutral, PublicKeyToken=52aa3500039caf0d' uses 'SharpDX.Mathematics, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1' which has a higher version than referenced assembly 'SharpDX.Mathematics' with identity 'SharpDX.Mathematics, Version=3.1.1.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1'

**Comment by holance** [comment]
You need to update your project sharpdx version

**Comment by holance** [comment]
Fixed at #515
