### ISSUE TITLE
Trackball vs Turnball CameraRotationMode

### ISSUE THREAD

**Issue by mplisov** [helix-toolkit/helix-toolkit#516]
Could you please explain difference in Trackball vs Turnball CameraRotationModes. 
 Documentation possible error - 
For Turnball stated "Turntable using three axes (look direction, right direction and up direction (on the left/right edges))."

**Comment by holance** [comment]
Trackball uses whole viewport as a ball for rotation. Turnball uses left/right side of the viewport and up/down movement for rotation.
