### ISSUE TITLE
How do I import the latest version to current project?

### ISSUE THREAD

**Issue by pipited07** [helix-toolkit/helix-toolkit#517]
I downloaded the Helixtoolkit.wpf and Helixtoolkit.wpf.sharpdx by the NuGet as the tutorial. Now I use some feature from the sample code that Nuget doesn't seems to have. For example , I want to do the multiple view port  in my project, but it don't have the property "EnableSharedModelMode". So, I want to import the latest version of Helixtoolkit.wpf.sharpdx. I don't know if it just replace the HelixToolkit.Wpf.SharpDX.dll. Becasue I did that and have some error. I want to know what's the standard way to import the latest version from github in VisualStudio.

**Comment by holance** [comment]
You need to get the latest unstable version from https://www.myget.org/F/helix-toolkit

**Comment by pipited07** [comment]
Ok, thanks for your reply.
