### ISSUE TITLE
No download links for older versions

### ISSUE THREAD

**Issue by minexew** [helix-toolkit/helix-toolkit#518]
I'm currently trying to compile a program that depends on `HelixToolkit, Version=2011.10.1.0`.

However, I've been unable to find a download link (either source or binary) for that version. Could anyone point me in the right direction?

Thanks.

**Comment by JeremyAnsel** [comment]
The older versions are still on NuGet:
- https://www.nuget.org/packages/HelixToolkit/2011.10.1
- https://www.nuget.org/packages/HelixToolkit.Wpf/2011.10.1
- https://www.nuget.org/packages/HelixToolkit.Wpf.SharpDX/2011.10.1

**Comment by minexew** [comment]
Ah, didn't know unlisted packages/versions were a thing.

By the way, did I overlook something, or is there really no way to discover these without knowing the exact version in advance?

**Comment by objorke** [comment]
The unlisted packages can always be restored but we don't want the v2000... versions listed as they will conflict with new semver version numbers (v1.0....)

**Comment by mjkkirschner** [comment]
Hi - I know this is an odd request, though related to this issue -  I would like to use a version of helix toolkit that references sharp.dx > 3.0 - since the older versions are unlisted - I cannot find one (if it exists). 
I am trying to avoid moving up to 1.x etc.
It appears this might have existed since it appears sharpx 3.1 was referenced in 2016 timeframe.
thanks for any help.

**Comment by holance** [comment]
Try to use this command to download the old version through nuget CLI:
dotnet add package HelixToolkit.Wpf.SharpDX --version 2015.1.715

**Comment by mjkkirschner** [comment]
thanks @holance - much appreciate your response - when I look at the dependencies of this version it shows sharpdx of >=2.6.3 on nuget - is this just incorrect info in the nuspec?

**Comment by holance** [comment]
This is correct. This is the last version before releasing 1.0.
