### ISSUE TITLE
NotImplementedException in ModelContainer3DX

### ISSUE THREAD

**Issue by pipited07** [helix-toolkit/helix-toolkit#522]
I implemented a multiview by imitating the sample code LightingDemo. When I added ModelContainer3DX in my xaml, the design view showed
 **"Notimplementedexception the method or operation is not implemented" at HelixToolkit.Wpf.SharpDX.ModelContainer3DX.get_EnableRenderFrustum()**

I thought It was my binding problem at initial, but when I continuously clicked (or highlighted) the area of ModelContainer3DX on the VS xaml editor in the sample code(LightingDemo), it showed the same error.
How did that happen? 
ps: It would restore after cleaning solution until the cursor located again in the area of ModelContainer3DX .

**Comment by holance** [comment]
Will fix in next merge
