### ISSUE TITLE
Can not implement a UserControl in another project 

### ISSUE THREAD

**Issue by pipited07** [helix-toolkit/helix-toolkit#523]
I create "Controls" project which contains a UserControl that include some Viewport3DX. Both project import the latest version.
Here is the picture:
![000](https://user-images.githubusercontent.com/22461372/28782881-21656028-7641-11e7-868e-2c60b5612047.png)

However, when I tried to assign the ViewModel to the UserControl , the MainWindow would show the error "**Unable to load DLL 'sharpdx_direct3d11_1_effects_x86.dll': The specified module could not be found**"
But if I remove comment "this.DataContext=this" and add comment to "this.DataContext = new ViewPort()", it would not show the error.
![111](https://user-images.githubusercontent.com/22461372/28783060-ad6db318-7641-11e7-99d7-5b26291ccf4c.png)

The designer of MainWindow show 
![222](https://user-images.githubusercontent.com/22461372/28783561-4fada934-7643-11e7-984a-b53d516a8b24.png)

Does anybody know how I can solve this issue? Thanks in advance.

**Comment by holance** [comment]
Did you set those three effect dll to copy to the build location?

**Comment by pipited07** [comment]
@holance  Yes, I surely post three effect in bin file(both project). Actually , I  posted  everywhere I can think about.

**Comment by holance** [comment]
What is in your view model?

**Comment by pipited07** [comment]
@holance  I thought it is the same question with #522 
Because it would show the error if I created the instance of DefaultEffectsManager in my viewmodel  class.
However, it all be fine after I updated library. Very appreciate your reply. Thank you.
