### ISSUE TITLE
Can set the Width and NearPlainDistance to Camera in HelixToolkit.Wpf.SharpDX?

### ISSUE THREAD

**Issue by pipited07** [helix-toolkit/helix-toolkit#525]
I used  OrthographicCamera in HelixToolkit.Wpf.SharpDX and it seems no Width and NearPlainDistance can be modified like in WPF. I need to adjust the model to a suitable position, if there is no Width and NearPlainDistance, I can not modify the proportion of the model in viewport and my model would be clipped. How can I deal with this problem?
PS:I use the latest version of HelixToolkit.Wpf.SharpDX.

**Comment by holance** [comment]
It has both width and nearplaindistance properties. Did you forget to cast your camera variable to OrthographicCamera ?

**Comment by pipited07** [comment]
@holance  Yes,you're right. It's my big mistake. Thanks for you reply.
