### ISSUE TITLE
How to implement DirectionalHeadLight in HelixToolkit.Wpf.SharpDX?

### ISSUE THREAD

**Issue by pipited07** [helix-toolkit/helix-toolkit#527]
I used DirectionalHeadLight in my program. No matter I changed the camera position the light follow the camera to illuminate just like a "HeadLight". So ,is the  position of DirectionalHeadLight relative the position of camera ? 
If I want to implement a "HeadLight" in HelixToolkit.Wpf.SharpDX, how do I change the direction of the light with camera change position? Sorry, I'm a wpf beginner. Could anyone taught me how to bind it in xaml or other better way?

**Comment by holance** [comment]
Please refer to demo BoneSkinDemo, function SetupCameraBinding

**Comment by pipited07** [comment]
@holance  Thank you. It's very helpful.
