### ISSUE TITLE
MSAA now defaults to disabled

### ISSUE THREAD

**Issue by kthyholdt** [helix-toolkit/helix-toolkit#530]
MSAA used to default to Maximum, now it defaults to Disabled, and can not be overridden by setting 

MainViewport.MSAA = MSAALevel.Maximum;

This is running on a Nvidia 1070, so it should be able to handle this.
Its working fine with v1.0.0-unstable1398.

**Comment by holance** [comment]
You can manually set it to Maximum. Just create a new class inherit the viewport, set the msaa property to Maximum. Or set it in Xaml.

Not everyone has high performance video card, I don't want to let developer who is new to helixtoolkit suffer the performance issue before they know there's a MSAA option.

**Comment by holance** [comment]
Issue fixed. MainViewport.MSAA = MSAALevel.Maximum;
