### ISSUE TITLE
Is it possible to change the coordinate system/direction in Helix-SharpDX?

### ISSUE THREAD

**Issue by mk48** [helix-toolkit/helix-toolkit#534]
I created a rectangle mesh and displaying X,Y & Z value on mouse move. In TOP view the bottom left corner is (0,0,0) and Y value goes UP direction.
Is it possible to change the Y direction downwards? which means changing the (0,0,0) as top left corner.

I can transform my 3D object, but that will change my Y value as negative. Is it possible without transforming the object. :thinking: 

It is same like LEFT/RIGHT hand coordinate system, but the change in Y axis :confused:

**Comment by holance** [comment]
You can use bind a transformation matrix for your model. Or change the world matrix #535 to flip the entire world.
