### ISSUE TITLE
1.0.0 release?

### ISSUE THREAD

**Issue by Bebere** [helix-toolkit/helix-toolkit#536]
I'd have a question: what is currently blocking a 1.0.0 release? [Its milestone](https://github.com/helix-toolkit/helix-toolkit/milestone/1) is stating that all related issues are closed.

**Comment by holance** [comment]
@objorke I think the SharpDX version is stable enough to have a stable release.

**Comment by objorke** [comment]
Great! @holance - can you take care of this?
I suggest the following process: https://github.com/helix-toolkit/helix-toolkit/wiki/Release-process
(feel free to improve the page!)
I can give you access to push the packages to nuget.org!

**Comment by holance** [comment]
@objorke My nuget user name is holance.

**Comment by holance** [comment]
@objorke Hi, what's the next release version do you want to put in? On nuget it is 2015.1.715, do you want to keep the similar version format? Or start from 1.0.0 from current setting.

**Comment by objorke** [comment]
1. We should push build artifacts from https://ci.appveyor.com/project/objorke/helix-toolkit/build/artifacts
2. Both packages should be published at the same time
3. The old (v2015) packages should be unlisted from nuget.org

**Comment by objorke** [comment]
I added the tasks from the release-process wiki page on #565

**Comment by objorke** [comment]
We will release when #565 is complete!
