### ISSUE TITLE
How do I change the transparency of FileModelVisual3D?

### ISSUE THREAD

**Issue by NaBian** [helix-toolkit/helix-toolkit#539]
Such as the title

**Comment by Background0** [comment]
The Opacity value (which corresponds to the transparency you're looking for) can be found, after the model is loaded, in: 
- _[FileModelVisual3D](https://github.com/helix-toolkit/helix-toolkit/blob/develop/Source/HelixToolkit.Wpf/Visual3Ds/Composite/FileModelVisual3D.cs)_
  - Visual3DModel (of type _[Model3DGroup](https://msdn.microsoft.com/fr-fr/library/system.windows.media.media3d.model3dgroup(v=vs.110).aspx)_)
    - Children (of type _[Model3DCollection](https://msdn.microsoft.com/en-us/library/system.windows.media.media3d.model3dcollection(v=vs.110).aspx)_ which contains one or several _[GeometryModel3D](https://msdn.microsoft.com/fr-fr/library/system.windows.media.media3d.geometrymodel3d(v=vs.110).aspx)_)
      - Material (of type _[MaterialGroup](https://msdn.microsoft.com/en-us/library/system.windows.media.media3d.materialgroup(v=vs.110).aspx)_, and which can be null)
        - Children (of type _[MaterialCollection](https://msdn.microsoft.com/en-us/library/system.windows.media.media3d.materialcollection(v=vs.85).aspx)_ which contains a _[DiffuseMaterial](https://msdn.microsoft.com/en-us/library/system.windows.media.media3d.diffusematerial(v=vs.110).aspx)_ and a _[SpecularMaterial](https://msdn.microsoft.com/en-us/library/system.windows.media.media3d.specularmaterial(v=vs.110).aspx)_)
          - Brush (of type _[Brush](https://msdn.microsoft.com/fr-fr/library/system.windows.media.brush(v=vs.95).aspx)_)
            - Opacity (value between 0.0 and 1.0)

However, Opacity is in readOnly mode, as well as Brush and Children of Material. So the simplest way is to redefine the Material of each _[GeometryModel3D](https://msdn.microsoft.com/fr-fr/library/system.windows.media.media3d.geometrymodel3d(v=vs.110).aspx)_ in Visual3DModel.Children as follow : 

```
private void setMaterials()
        {
            if(this.Visual3DModel != null)
            {
                foreach(GeometryModel3D geoModel3D in ((Model3DGroup)this.Visual3DModel).Children)
                {
                    MaterialExtension me = new MaterialExtension(Colors.DarkGray);
                    me.Opacity = 0.2;
                    geoModel3D.Material = (MaterialGroup)me.ProvideValue(null);
                }
            }
        }
```

Remarks : 
- _[MaterialExtension](https://github.com/helix-toolkit/helix-toolkit/blob/develop/Source/HelixToolkit.Wpf/MarkupExtensions/MaterialExtension.cs)_ allows you to also modify the SpecularIntensity and the SpecularPower of your object, which affect the light reflexion.
- You might also want to redefine the BackMaterial of each _[GeometryModel3D](https://msdn.microsoft.com/fr-fr/library/system.windows.media.media3d.geometrymodel3d(v=vs.110).aspx)_, according to your application.

**Comment by objorke** [comment]
Thanks @Background0 !

**Comment by NaBian** [comment]
thanks @Background0
