### ISSUE TITLE
Update NuGet package

### ISSUE THREAD

**Issue by yohsk10** [helix-toolkit/helix-toolkit#540]
Hi,

I have a question about the NuGet package of HelixToolkit.WPF. I notice that the last package was released on May 2016 but some fix were made since the last package.
Have you abandoned the NuGet deployment or are you waiting for a more stable version ?

Thanks in advance !

**Comment by holance** [comment]
You can download the latest unstable version from myget. I think it is stable enough for use now. Still waiting for the original owner to publish the stable version.

**Comment by yohsk10** [comment]
Ok, thanks for response !
