### ISSUE TITLE
How do I refresh the view automatically?

### ISSUE THREAD

**Issue by pipited07** [helix-toolkit/helix-toolkit#541]
I used HelixToolkit.Wpf.SharpDX to implement multiple viewport and they share one ModelContainer3DX. I want to one model move by specific matrix. The code is below :
It only show the new position when I rotate or zoom the model, so I think the reason is I didn't refresh the view actively. I don't know the function can refresh the view. Can any one teach me?

```

public partial class MainView : Window
{
        public MeshGeometryModel3D  myMeshGeometry ;
        public MainView()
        {  
           InitializeComponent();
           myMeshGeometry = LoadSTL(string path);
           sharedContainer.Items.Add(myMeshGeometry);
        }
        private void move_Click(object sender, RoutedEventArgs e)
        {
           myMeshGeometry.PushMatrix(new SharpDX.Matrix(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, -100, -100, 100, 1)); 
        }    
}

```

**Comment by holance** [comment]
You need to use Transform property

**Comment by pipited07** [comment]
@holance Thanks,it work.
