### ISSUE TITLE
About transparency setting 

### ISSUE THREAD

**Issue by pipited07** [helix-toolkit/helix-toolkit#542]
My model had different transparency effect in different angle. The back of the model can be seen in Figure 1, but Figure 2 does not work. I think it may be the z-buffer question. Is there any good way to solve this problem in sharpdx.wpf version? Is close the depth test a right way?But how?
Or any setting I didn't use, I just set the alpha value of diffuse color in PhongMaterial.
Figure 1
![10](https://user-images.githubusercontent.com/22461372/30326049-c02dd648-97f9-11e7-84a9-2b92202a521c.png)

Figure 2
![11](https://user-images.githubusercontent.com/22461372/30326054-c3c9e68e-97f9-11e7-937e-99e1eff589ca.png)

**Comment by holance** [comment]
Render the back face first (set Cull mode to front face) , then render the front face (set Cull mode to back face). 

If need to avoid using two mesh geometry model 3d, you can to Override the  meshgeometrymodel3d on draw call to render twice with two different raster states.

**Comment by pipited07** [comment]
@holance I tried to fix the problem recently. I adopt your first advice, so I load two plane(one set front and another set back). Here is the image.

Figure1
![image](https://user-images.githubusercontent.com/22461372/30813882-335f9cfe-a241-11e7-8c99-944dab0167e4.png)
Figure2
![image](https://user-images.githubusercontent.com/22461372/30813854-25bcb276-a241-11e7-8027-c6634e4f62a9.png)


The first question is the back of the plane is black. It seems the model have no back color, but I can't find the property in PhongMaterial.  
Second, the image1 shows that I still cannot see through the plane.
Third, I don't want to load the model everytime use the transparency, but I don't know how to override on draw call. Is any sample to get start?

**Comment by holance** [comment]
Are you trying to do the transparency on plane or the skull model? You need to use two plane or a think box, otherwise the normal has only one direction, that's why the back of the plane is black.

You need to set the opacity in material colors to be semi-transparent so the plane becomes semi-transparent.

**Comment by holance** [comment]
If you want semi-transparent for your model. Get latest build and do following:
            <hx:MeshGeometryModel3D
                CullMode="Back" InvertNormal="True" FrontCounterClockwise="False"            
                Geometry="{Binding Model}"
                Material="{Binding ModelBackMaterial}"
                />
            <hx:MeshGeometryModel3D
                CullMode="Back"
                Geometry="{Binding Model}"
                Material="{Binding ModelMaterial}"
                />

Make sure the material diffuse color alpha set to semi transparent.

**Comment by pipited07** [comment]
@holance  Really appreciate your reply.
I'm trying to do the transparency both on plane and the skull model. I take your recommendation(draw both side of model) and draw something like:
![image](https://user-images.githubusercontent.com/22461372/31052685-73a4f59e-a6be-11e7-84d5-977cb37788b6.png)
![image](https://user-images.githubusercontent.com/22461372/31052687-761ec052-a6be-11e7-90c3-996927505622.png)


It seems look good when render single object.
But if draw more models which are more complicated (normal vector is not continuous) would show that
![image](https://user-images.githubusercontent.com/22461372/31052731-b29c40f8-a6bf-11e7-8ef5-551a68c8e9cc.png)
![image](https://user-images.githubusercontent.com/22461372/31052734-c3dee9d8-a6bf-11e7-9297-082647a1414d.png)


I couldn't see the yellow model behind the blue, and it would show something unusual when the angle change slightly like:
figure5
![image](https://user-images.githubusercontent.com/22461372/31052901-419a53aa-a6c3-11e7-830c-a921528212c4.png)
figure6
![image](https://user-images.githubusercontent.com/22461372/31052902-46f5c276-a6c3-11e7-8b18-a67e3b33c5d1.png)


My ideal result is like:
figure7
![image](https://user-images.githubusercontent.com/22461372/31052918-a36dd494-a6c3-11e7-86a3-61cfb7e86d21.png)


I have two question. First, about the transparent plane, I think close the light effect to the plane is one solution, but I don't know if you can implement the function in the library or I just draw thin box mentioned above.
Second, I think the problem in figure5, figure6 is about the drawing order. Is any better solution to implement like figure7?
Thank you for the time and patience you help solve my problem. I really appreciate that.

**Comment by holance** [comment]
You need to draw the yellow model before transparency model. Usually all non transparency models are drawn first, then draw transparency models. For transparency models, order is important.

**Comment by holance** [comment]
In figure 7, seems like you don't need to see the back faces? Then just use single meshgeometrymodel3d and Cull its back faces.
