### ISSUE TITLE
New sample code had some error 

### ISSUE THREAD

**Issue by pipited07** [helix-toolkit/helix-toolkit#544]
As title here is the snapshot, is any error?

![image](https://user-images.githubusercontent.com/22461372/30422963-fe73d044-9973-11e7-9a5c-9c5d17d36cc1.png)

**Comment by holance** [comment]
Did you restore the nuget package for this project? Seems like the sharpdx packages are not restored

**Comment by pipited07** [comment]
![image](https://user-images.githubusercontent.com/22461372/30588770-9d9f64d6-9d6a-11e7-82c8-1845cc50dc46.png)

@holance 
If delete MeshGeometryModel  and paste would show error in OctreeDemo sample code.

**Comment by holance** [comment]
It is Ok as long as you can run it. If you build it, the error will be gone.

**Comment by pipited07** [comment]
OK, thanks for your reply.
