### ISSUE TITLE
Create a simple gridlines in HelixSharpDX?

### ISSUE THREAD

**Issue by antithing** [helix-toolkit/helix-toolkit#548]
I am trying to move my project from helix standard to helix SharpDx, and am stuck on the very first hurdle.

What is the equivalent to:

`            <HelixToolkit:GridLinesVisual3D Width="100" Length="100" MinorDistance="1" MajorDistance="5" Thickness="0.05" />`

?

I have tried:

`            <hx:LineGeometryModel3D x:Name="grid"  Geometry="{Binding Grid}"  Transform = "{Binding GridTransform}"   Color="{Binding GridColor}"/>`

with:

```
 //grid
        public LineGeometry3D Grid { get; private set; }
        public Transform3D GridTransform { get; private set; }
        public SharpDX.Color GridColor { get; private set; }

 this.Grid = LineBuilder.GenerateGrid();
            this.GridColor = SharpDX.Color.Black;
            this.GridTransform = new TranslateTransform3D(-5, -1, -5);
```

But I see nothing in the viewport.

Thank you!

**Comment by SwaroopSomanna** [comment]
Why is this issue closed without a solution to the issue ?
