### ISSUE TITLE
Consistent and esthetic coding style and XmlDoc

### ISSUE THREAD

**Issue by smischke** [helix-toolkit/helix-toolkit#555]
I am a fan of clean, readable code. The SharpDX part has always been a mess and although it's becoming more powerful and mature with every contribution, each contributor has a different opinion (or none) about code formatting. I suggest a code cleanup to become constistent with the original style of the WPF part introduced by @objorke using modern [StyleCopAnalyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers). The XmlDoc also needs to be completed. I would volunteer for these tasks if my proposal is approved.

**Comment by holance** [comment]
Sure, go ahead.

**Comment by holance** [comment]
Since many things has been changed for 2.0. If any one wants to help about the code styling or documentation, please resubmit a new request.
