### ISSUE TITLE
Some problem about model share after update

### ISSUE THREAD

**Issue by pipited07** [helix-toolkit/helix-toolkit#556]
I have a multiview application. After I update the library, I got this error.

![image](https://user-images.githubusercontent.com/22461372/31044464-662b4a88-a602-11e7-9510-ce1ced932015.png)
the error :object reference not set to an instance of an object.(Sorry, I tried to change the language to English)

So, I tried to reproduce the error. Here is the code:
XAML:
```
<Grid Background="#FFE5E5E5" Margin="1">
        <hx:ModelContainer3DX x:Name="sharedContainer"  RenderTechnique="{Binding RenderTechnique}">
        </hx:ModelContainer3DX>
        <hx:Viewport3DX  x:Name="viewport3"
                        ShowViewCube="True"                         
                        Background="Black" Margin="1" 
                        Camera="{Binding Camera3}"                                               
                        EnableSharedModelMode="True"
                        SharedModelContainer="{Binding ElementName=sharedContainer}"
                        Grid.Column="1" Grid.Row="1">
            <hx:AmbientLight3D />            
        </hx:Viewport3DX>
    </Grid>
```
The code will show the same error with my application, and I pretty sure that I implemented the Camera3 property. I found that if I remove "EnableSharedModelMode="True" ,it would be no error. Or if I remove the "AmbientLight3D", it would be no error,too. I don't know how to do, does anyone have the same problem?

ps: I didn't update the version for a long time, so problem is not necessarily from the recent commit.

**Comment by holance** [comment]
Bind the effect manager to your view model. The modelcontainer will need to manually assign the effect manager either from view model binding or code behind. Let the user to handle the life of the effect manager to avoid memory leak.

**Comment by pipited07** [comment]
@holance Thank you. It work!!! Really appreciate your reply.
