### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by objorke** [helix-toolkit/helix-toolkit#565]
- [x] check that all issues on release page are solved
- [x] check that change log is up to date
- [x] check that all examples are working (if not, an issue should be created)
- [x] check both WPF and SharpDX
- [x] create release branch (gitflow)
- [x] test that packages are working (create a simple project, install packages)
- [x] tag and merge to master (gitflow)
- [x] push stable packages to nuget.org (use .nupkg artifacts from appveyor)

**Comment by holance** [comment]
@objorke I don't have authorization to merge into master.

**Comment by objorke** [comment]
I created a PR from the release branch to `master` #569, then merged back to `develop` #570.
Organization and repo admins should have push access, but I think using PRs for these tasks work quite well. I have updated the release process wiki.

Build artifacts for v1.0.0:
https://ci.appveyor.com/project/objorke/helix-toolkit/build/1.0.0.build.919/artifacts

@holance Can you push all 3 to nuget?

Can we also update the description of the tag?
https://github.com/helix-toolkit/helix-toolkit/releases/tag/v1.0.0

**Comment by holance** [comment]
@objorke Done ;)
