### ISSUE TITLE
About closing the light 

### ISSUE THREAD

**Issue by pipited07** [helix-toolkit/helix-toolkit#566]
I want to draw two plane to express some symmetric surface on a skull model. The result is below 
![image](https://user-images.githubusercontent.com/22461372/31478562-cbb36774-af43-11e7-9ffa-69ae423e78cd.png)
The image shows that the plane become dark when the camera is not at the normal direction of the plane.
This is another angle of view:
![image](https://user-images.githubusercontent.com/22461372/31478633-481d0838-af44-11e7-9088-12a69dc11573.png)

I use OpenGL in another program. Here is the effect what I want, I close the light when draw the plane.
![image](https://user-images.githubusercontent.com/22461372/31478655-7cd02402-af44-11e7-8c6c-4f27d66ba9db.png)

I want to know if there is anyway to implement the effect especially close the light for specific object.

**Comment by holance** [comment]
You need to use a different shader to render the plane. 
Create your own class, inherit from MeshGeometryModel3D.
Override 
        protected override RenderTechnique SetRenderTechnique(IRenderHost host)
        {
            return host.EffectsManager.RenderTechniquesManager.RenderTechniques[DefaultRenderTechniqueNames.Colors];
        }

Assign the vertex colors in MeshGeometry3D.Colors.

**Comment by pipited07** [comment]
@holance  Sorry, I have never used the ShaprDX. Could you please provide a sample code or describe more  details about using another shader after inheriting from MeshGeometryModel3D. ?

**Comment by pipited07** [comment]
@holance  Thanks for your reply. Now I can draw the plane what I want. But there is another problem, I can't use the class inheriting from MeshGeometryModel3D in xaml. The error message shows "The name does not exist in the namespace error in XAML", so I find way to fix, like [this](https://stackoverflow.com/questions/14665713/the-name-does-not-exist-in-the-namespace-error-in-xaml), or [this](https://stackoverflow.com/questions/38579936/the-name-does-not-exist-in-the-namespace-clr-namespace). It still could compile, even the error exists.
Anyway, I add the model in codebehind. I want to know if there is a way to have different model class in a ObservableCollection used in ModelContainer like DraggableGeometryModel3D, MeshGeometryModel3D. I think that is very convenient to manage model  in the viewport.

**Comment by holance** [comment]
You can use a GroupModel3D and bind its itemssource to your observablecollection.

**Comment by pipited07** [comment]
@holance  I don't know if I misunderstand what you mean.
xaml:
```
<hx:ModelContainer3DX x:Name="sharedContainer"  RenderTechnique="{Binding RenderTechnique}" EffectsManager="{Binding EffectsManager}" Margin="1" Grid.Row="1">
            <hx:GroupModel3D x:Name="groupmodel"   ItemsSource="{Binding ModelCollection}">
                <hx:MeshGeometryModel3D x:Name="model1" Geometry="{Binding Model}" Transform = "{Binding Model1Transform}" Material="{Binding Material1}" />
            </hx:GroupModel3D>
            <hx:AmbientLight3D Color="{Binding AmbientLightColor}"/>

            <hx:DirectionalLight3D Color="{Binding DirectionalLightColor}" Direction = "{Binding DirectionalLightDirection}"/>
</hx:ModelContainer3DX>
<hx:Viewport3DX  x:Name="viewport1" .... />
</hx:Viewport3DX>
<hx:Viewport3DX  x:Name="viewport2" .... />
</hx:Viewport3DX>
<hx:Viewport3DX  x:Name="viewport3" .... />
</hx:Viewport3DX>

```

Code behind:

        private ObservableCollection<MeshGeometryModel3D> modelCollection = new ObservableCollection<MeshGeometryModel3D>();

        public ObservableCollection<MeshGeometryModel3D> ModelCollection
        {
            get
            {
                return modelCollection;
            }

            private set
            {
                SetValue(ref modelCollection, value);
            }
        }

I add model in ModelColletion at run time, but no model appears.

**Comment by holance** [comment]
I tried and it is working fine. Please check any binding error. Did you put your modelcollection in view model or code behind? Also move all light models before any other models.

**Comment by pipited07** [comment]
@holance  I make another new WPF project, and assign the MainWindow to the DataContext for convenience. Anyway, I tried three way to add model to make sure  which step is wrong. But the result is same.

1. Bind ItemSource of GroupModel3D in ModelContainer     
binding property: ObservableCollection<DataModel> Items  (The DataModel is the same as sample code in OctreeDemo )

2. Bind ItemSource of ItemsModel3D in ModelContainer
binding property: ObservableCollection<MeshGeometryModel3D> GroupModelSource

3. Add directly to the ModelContainer 

XAMl:
```
<hx:ModelContainer3DX x:Name="sharedContainer"  RenderTechnique="{Binding RenderTechnique}" EffectsManager="{Binding EffectsManager}" Margin="1,1,-1,1">
            <hx:DirectionalLight3D Direction="{Binding Light1Direction}" Color="{Binding Light1Color}" />
            <hx:AmbientLight3D Color="{Binding AmbientLightColor}"/>
            <hx:GroupModel3D x:Name="groupmodel"   ItemsSource="{Binding GroupModelSource}"/>
            <hx:ItemsModel3D  ItemsSource="{Binding Items}">
                <hx:ItemsModel3D.ItemTemplate>
                    <DataTemplate>
                        <hx:MeshGeometryModel3D
                            CullMode="Back" ReuseVertexArrayBuffer="True"
                            Geometry="{Binding Model}"
                            Material="{Binding Material}"
                            Transform="{Binding DynamicTransform}" />
                    </DataTemplate>
                </hx:ItemsModel3D.ItemTemplate>
            </hx:ItemsModel3D>            
        </hx:ModelContainer3DX>

```

Code behind:

```
    private void button_Click(object sender, RoutedEventArgs e)
        {

            //add Model by using ItemsSource of GroupModel3D            
            var b1 = new MeshBuilder();
            b1.AddSphere(new Vector3(-10f + rnd.Next() % 10, -10f + rnd.Next() % 10, -10f + rnd.Next() % 10), 0.3);

            MeshGeometryModel3D model = new MeshGeometryModel3D();
            model.Geometry = b1.ToMeshGeometry3D();           
            model.Transform = new System.Windows.Media.Media3D.MatrixTransform3D();
            model.Material = PhongMaterials.Orange;
            GroupModelSource.Add(model);

            //add Model by using ItemsSource of ItemsModel3D
            var b3 = new MeshBuilder(true, true, true);
            b3.AddSphere(new Vector3(-10f + rnd.Next() % 10, -10f + rnd.Next() % 10, -10f+ rnd.Next()%10), 0.3);

            DataModel datamodel = new DataModel();
            datamodel.Model = b3.ToMeshGeometry3D();
            datamodel.Material = new PhongMaterial() { DiffuseColor = rnd.NextColor().ToColor4() };
            datamodel.DynamicTransform = new System.Windows.Media.Media3D.Transform3DGroup();
            Items.Add(datamodel);

            //add Model directly into ModelContainer
            this.sharedContainer.Items.Add(model);                 
        }
```      

Only bind on ItemSource of ItemsModel3D in ModelContainer (# 2)can work. Do I lost something like swap buffer? If it is convenient, could you send me your test code? My email is _**pipited02@gmail.com**_.

**Comment by holance** [comment]
Try to use ObservableCollection<Element3D> for binding instead of ObservableCollection<MeshGeometryModel3D>

**Comment by holance** [comment]
Use ObservableElement3DCollection for workaround or update the package to the newest unstable version.

**Comment by pipited07** [comment]
@holance  I update to the newest unstable version and it work. However , if I add model into the ModelContainer directly, that still doesn't work. All I need is enough, but I think it is very make sense to add model into ModelContainer. Why can't I do that?

**Comment by holance** [comment]
Currently the model container doesn't observe the model changes. I may implement it in next release.
