### ISSUE TITLE
Position adjustment for 3D objects in HelixViewport3D?

### ISSUE THREAD

**Issue by tommy025** [helix-toolkit/helix-toolkit#576]
Suppose you have a object in a HelixViewport3D control, and you want to allow users to adjust its position via mouse (and keyboard) inputs. It seems this functionality is not yet implemented. I have a few thoughts on this issue and would like discussed with you. Here is what I came up with:

    1.Define a DependencyProperty 'SelectedObject' in the Viewport3D control (be it HelixViewport3D or derived subclasses) and alter its value when a click event on the control (or any children object) is triggered.
    2.Define a boolean AttachedProperty 'AllowReposition' and attach it to any 3D object to be added in the Viewport3D control, to indicate whether or not it can be repositioned via UI inputs.
    3.Add 3D objects (arrows for instance) as 'grips' near the selected object, either aligned or around axes. When the user presses and holds their mouse buttons on these 'grips', the object can move along and rotate around X, Y or Z axis. Apparently these 'grips' need to be specially handled like the ViewCube.

Althought I might need to implement it myself this time, but is there any chance that this could be added in future releases? Any comment and suggestion from you would be appreciated :)

**Comment by holance** [comment]
You can refer to the TranslateManipulator OnMouseDown, OnMouseMove to create your own model to move by mouse.

**Comment by tommy025** [comment]
Amazing! And all I need to do now is to switch the target upon clicked. Really sometimes you just need to ask the right person, thanks again!
