### ISSUE TITLE
ExtrudedText under the Helix.WPF.SharpDX 

### ISSUE THREAD

**Issue by Mitra-M** [helix-toolkit/helix-toolkit#578]
I used the [ExtrudedText ](https://github.com/helix-toolkit/helix-toolkit/tree/master/Source/Examples/WPF/ExampleBrowser/Examples/ExtrudedText)method to make a 3d text from 2d, Now I want to migrate to the Helix.WPF.SharpDX because performance issue.
I tried a lot to convert the ExtrudedText example to the Helix.WPF.SharpDX , But I could not do it, because the HelixToolkit.Wpf.SharpDX.Polygon does not have AddContour method and a lot of error occurs.
(it seems there is not any text tessellation method in the Helix toolkit)
Please help.

**Comment by holance** [comment]
The ExtrudedText is using TriangleNet external library to create the mesh. You can copy the Triangle.dll from WPF ExampleBrowser project and use in your new project. You can reference to Extensions.cs in ExtrudeText project to create the MeshGeometry used by SharpDX version.

**Comment by Mitra-M** [comment]
Thank you for the reply.

this is the ExtrudeText method in  the Extensions.cs : 

` public static class Extensions
    {
        public static void ExtrudeText(this MeshBuilder builder, string text, string font, FontStyle fontStyle, FontWeight fontWeight, double fontSize, Vector3D textDirection, Point3D p0, Point3D p1)
        {
            var outlineList = GetTextOutlines(text, font, fontStyle, fontWeight, fontSize);

            // Build the polygon to mesh (using Triangle.NET to triangulate)
            var polygon = new TriangleNet.Geometry.Polygon();
            int marker = 0;

            foreach (var outlines in outlineList)
            {
                var outerOutline = outlines.OrderBy(x => x.AreaOfSegment()).Last();

                for (int i = 0; i < outlines.Count; i++)
                {
                    var outline = outlines[i];
                    var isHole = i != outlines.Count - 1 && IsPointInPolygon(outerOutline, outline[0]);
                    polygon.AddContour(outline.Select(p => new Vertex(p.X, p.Y)), marker++, isHole);
                    builder.AddExtrudedSegments(outline.ToSegments().ToList(), textDirection, p0, p1);
                }
            }

            var mesher = new GenericMesher();
            var options = new ConstraintOptions();
            var mesh = mesher.Triangulate(polygon, options);

            var u = textDirection;
            u.Normalize();
            var z = p1 - p0;
            z.Normalize();
            var v = Vector3D.CrossProduct(z, u);

            // Convert the triangles
            foreach (var t in mesh.Triangles)
            {
                var v0 = t.GetVertex(0);
                var v1 = t.GetVertex(1);
                var v2 = t.GetVertex(2);

                // Add the top triangle.
                // Project the X/Y vertices onto a plane defined by textdirection, p0 and p1.                
                builder.AddTriangle(v0.Project(p0, u, v, z, 1), v1.Project(p0, u, v, z, 1), v2.Project(p0, u, v, z, 1));
                
                // Add the bottom triangle.
                builder.AddTriangle(v2.Project(p0, u, v, z, 0), v1.Project(p0, u, v, z, 0), v0.Project(p0, u, v, z, 0));
            }
        }
       .........
     `
when I replace the HelixToolkit.Wpf.SharpDX.MeshBuilder insteat of the HelixToolkit.Wpf.MeshBuilder
it get many errors.

I tried some hours but I could not do it.
 I did not find any examples on the Internet.
would you please please please update the ExtrudeText example for the SharpDX version?

**Comment by holance** [comment]
https://github.com/holance/ExtrudedTextHelixSharpDX

**Comment by Mitra-M** [comment]
Wow! ultra fast.
excellent.
I think this is the fastest and best support in the open source world.

I learned a lot from your example.
Thank you very very much!
