### ISSUE TITLE
Can't set the transparent background in Viewport3DX

### ISSUE THREAD

**Issue by pipited07** [helix-toolkit/helix-toolkit#579]
I want a transparent background and set the backgound to "No Brush ". It seems work in the design view.
![image](https://user-images.githubusercontent.com/22461372/32780355-e52c3486-c97b-11e7-8d41-cca37857deaa.png)
But when I execute the program, the viewport become white. Why is that?

**Comment by JeremyAnsel** [comment]
Hello,
Try using `BackgroundColor` instead of `Background`.
```xml
    <Grid Background="Green">
        <hx:Viewport3DX BackgroundColor="0 0 0 0">
        </hx:Viewport3DX>
    </Grid>
```
With this code, the background becomes green.

**Comment by pipited07** [comment]
@JeremyAnsel  It work! Thank you very much.
