### ISSUE TITLE
Bind color of a Visual3D in HelixViewport3D to VM?

### ISSUE THREAD

**Issue by tommy025** [helix-toolkit/helix-toolkit#582]
In a simple project of mine I planned to build a 3D visualizer program following the MVVM design pattern, the XAML codes of the HelixViewport3D is:
`<ht:HelixViewport3D Name="HVpHydroMech" ZoomExtentsWhenLoaded="True">`
    `<htdd:ItemsVisual3D ItemsSource="{Binding ElementName=HVpHydroMech, Path=DataContext.HydroMechAnalIns}">`
        `<htdd:ItemsVisual3D.ItemTemplate>`
            `<htdd:DataTemplate3D>`
                `<hd:TaggedCubeVisual3D Transform="{Binding Path=Transform}" Tag="{Binding}" SideLength="{Binding Path=Size}">`
                    `<hd:TaggedCubeVisual3D.Fill>`
                        `<SolidColorBrush Color="{Binding Path=Colour}"></SolidColorBrush>`
                    `</hd:TaggedCubeVisual3D.Fill>`
                `</hd:TaggedCubeVisual3D>`
            `</htdd:DataTemplate3D>`
       `</htdd:ItemsVisual3D.ItemTemplate>`
    `</htdd:ItemsVisual3D>`
`</ht:HelixViewport3D>`
Here a DataTemplate3D from Helix demos is used to populate the HelixViewport3D with TaggedCubeVisual3D, which is the CubeVisual3D in HelixToolkit.Wpf adding a 'Tag' Dependency property. This tag along with other properties are bind to respective properties in the VM, and everything is good except the Fill property. When run, the program throws a InvalidOperationException saying that 'This Freezable cannot be frozen'. I wonder is there anything wrong with my code or it's simply not allowed?

**Comment by holance** [comment]
You need to bind the Fill to Brush instead of binding the color inside the brush.

**Comment by tommy025** [comment]
I end up with creating a new brush every time the color is changed, not sure if it's the best solution, but it should suffice for now. Thank you!

**Comment by holance** [comment]
Brush is pretty light weight, should not be a problem.
