### ISSUE TITLE
HelixToolkit.Wpf.SharpDX performance (High CPU usage)

### ISSUE THREAD

**Issue by Mitra-M** [helix-toolkit/helix-toolkit#585]
I've tried to make a simple rotating animation of cube/box (with solid color) by using the HelixToolkit.Wpf.SharpDX , but it uses ~%6 CPU!
If I switch rendering to swapchain it drop to ~%1 , but I can't overlay wpf elements on that.

I`ve tested [SharpDX.WPF](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiNgPvBqPrXAhWBDuwKHdfiC2EQFggkMAA&url=https%3A%2F%2Fsharpdxwpf.codeplex.com%2F&usg=AOvVaw14SEL3LjTT9AptRoZYCMjY) project to animate the same cube ,but it uses ~%1 CPU and I can overlay wpf elements on that.

please tell me , what is the problem?

**Comment by holance** [comment]
I think it is because the D3Dimage(has to do a frame copy  using wpf dx9 rendering). For small scene, the wpf animation may have advantage on CPU usage, but on large scene especially with a lot of screen space models(for example billboard, points, lines), you will see a performance hit due to the software rendering using wpf own engine.

For swap chain, this is a known issue to not be able to overlay wpf controls due to two different rendering technique. I am currently working on v 2.0 with support of some basic ui elements rendering using direct2D. 

But my suggestion for now is to move the wpf controls outside the viewport if using swap chain.

**Comment by Mitra-M** [comment]
Thank you for the reply, 
that's weird, because the [SharpDX.WPF](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiNgPvBqPrXAhWBDuwKHdfiC2EQFggkMAA&url=https%3A%2F%2Fsharpdxwpf.codeplex.com%2F&usg=AOvVaw14SEL3LjTT9AptRoZYCMjY)is an old project and I think it is also using the D3Dimage, but its performance is good.

> I am currently working on v 2.0 with support of some basic ui elements rendering using direct2D

Good news.

The Helix features are awesome and I hope you can make its performance better.

**Comment by holance** [comment]
Could you provide me both your test projects? So I can make some profiling and see what's going on.

**Comment by holance** [comment]
Ok, I think I know what's going on. Because in sharpdx version, we are still using the WPF viewport to render the viewbox and coordinate system. You can try to disable them in Viewport3DX and see if the cpu usage goes down.

**Comment by Mitra-M** [comment]
Good catch.

Results of 2 settings:
1- disable the viewbox and coordinate system => CPU 2~3 %

2 - disable the viewbox and coordinate system + EnableDeferredRendering => CPU 0~0.3 %  (WOW)

by settings number 2 CPU usage incredible goes down  :-)  , but rendering is not smooth :-(

it will be great If you can make it smooth .
(sorry for my English)

**Comment by Mitra-M** [comment]
I compiled my project with the settings number 2 in release mode  then:
CPU usage is absolutely **ZERO**  (wow)
But unfortunately rendering is not smooth . 
Is there any way to freeze all SharpDX freezable like brushes ,colores . . . ?

**Comment by holance** [comment]
There is no freezable concept in SharpDX version. Deferred rendering is just an experiment feature (still causing performance issue as long as using the D3Dimage), if you really want performance, swap chain still the best option if you don't need overlapping wpf UIs.

**Comment by Mitra-M** [comment]
I want to try some test to get the best FramRate , so I have another Question:
is the FrameRateText ( ShowFrameRate=true) using the WPF viewport like the viewbox and coordinate system? Is it accurate to measure FramRate in SharpDX mode?

**Comment by Mitra-M** [comment]
It's still vague to me, why the [SharpDX.WPF](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiNgPvBqPrXAhWBDuwKHdfiC2EQFggkMAA&url=https%3A%2F%2Fsharpdxwpf.codeplex.com%2F&usg=AOvVaw14SEL3LjTT9AptRoZYCMjY) project has smoother rendering?
Please have a look at the [Week01D3D11Tutorials](https://sharpdxwpf.codeplex.com/SourceControl/latest#Week01D3D11Tutorials/Week01D3D11Tutorials.csproj) exsample .

**Comment by holance** [comment]
Frame rate text is a plain wpf textbox.

**Comment by Mitra-M** [comment]
Thank you for your time.

**Comment by holance** [comment]
SharpDX.WPF project has smoother rendering is because it did not have any interaction with the wpf animation and inputs. WPF's rendering has dynamic frame rate, but we want constant frame rate during 3D animation, so in helix toolkit sharpdx, we purposely trying to sync with the wpf rendering thread(dynamic)/user input(100hz) and keep a constant frame rate (Default is 60hz) during rendering. 

I think what you see is the synchronization issue, which skips some frames occasionally if the wpf rendering frame rate goes too high(some times goes to 300hz, but you don't really want to render 300 frames/s). The side effect is unsmoothness of the animation. It is not really performance issue.

You can try to set the MaxFPS to 120 in viewport setting and see if you gets better results.

**Comment by Mitra-M** [comment]
Yes , the MaxFPS is what I need.

my above tests was on Win8.1, now I get the better CPU usage on Win10:

1- EnableDeferredRendering="False" ShowViewCube="True" ShowCoordinateSystem="True" IsHitTestVisible="False" RenderOptions.EdgeMode="Unspecified" ClipToBounds="False"   =>% 1.5~2.5  FrameRate=40~57

2- EnableDeferredRendering="True" ShowViewCube="False" ShowCoordinateSystem="False" IsHitTestVisible="False" RenderOptions.EdgeMode="Unspecified" ClipToBounds="False" =>% 0~0.3  FrameRate=35~55

3-   settings number 2 + MaxFPS="120" =>% 1.3~2.3  FrameRate=59~60  (Smooth)

by set MaxFPS to 120 rendering is good , until window not maximize , when I set window to the maximize FrameRate is droped to 30~40

**Comment by Mitra-M** [comment]
I thought SwapChainRendering is smooth, But it does not look like that.

I tested EnableSwapChainRendering="True" with/witout EnableDeferredRendering="True" , but while CPU usage is ~0 ,  rendering is jerky.

**Comment by holance** [comment]
What's your computer configuration?

**Comment by Mitra-M** [comment]
Processor : Intel Core(TM)i7-4790     3.6 GHZ
Ram: 4GB
GPU : AMD Radeon HD 5450   with update driver
OS: Win10   64bit      build 15063  with update drivers
WinSDK  and DXSDK_Jun10 are installed

Note: by using MaxFPS="120" rendering is smooth. (without DeferredRendering and SwapChainRendering)  , so I don't think the problem is in my PC.

**Comment by Mitra-M** [comment]
The FrameRate of your SwapChainRenderingDemo sample is 14~16 FPS on my computer.

**Comment by holance** [comment]
Hmm, that's weird. Even on my 5year old computer, it is 50+ fps on swap
chain demo.

**Comment by holance** [comment]
5 year old laptop

**Comment by Mitra-M** [comment]
I found the problem with your help.  

I tested on my friend's computer :
Corei7 Ram 16GB GPU ASUS-AMD 8GB Win7

Rendering was great. 58~59 HZ  (smooth)
the problem is lazy AMD graphic card.


A good news and a bad news for me:
1 - Helix's performance is excellent in SwapChain mode. :)
2 - I have to buy a new graphics card. :(
.......................................................................................
I have a simple idea: 

1- Instead of WPF ,main app is WinForm
2 - 3D objects are created as WPFUserControl by using Helix ViewportX.
3 - 2D objects are created as several WPFUserControls by using Helix Viewport. 
4 - Host all WPF UserControls (1 and 2) in the main WinForm.

  Do you think is this possible?

 
Thank you so much

**Comment by holance** [comment]
As long as using the swap chain, it will always render on top of other
controls, doesn't matter if using wpf or winform:(

**Comment by holance** [comment]
You can refer to this blog
https://blogs.msdn.microsoft.com/dwayneneed/2013/02/26/mitigating-airspace-issues-in-wpf-applications/

**Comment by Mitra-M** [comment]
That is a good article, Thanks.

I temporary changed my system's GPU with an AMD-HD-5800 (its not my ideal , but its very better than previous )

Now I get very weird results  on the SwapChainRenderingDemo sample:

1- EnableSwapChainRendering with /without EnableDeferredRendering => CPU =% 0.7  FPS=49~51 

2- without EnableSwapChainRendering and EnableDeferredRendering  with /without ShowViewCube => CPU =% 1.6  FPS=60~60.2 (perfect smooth) 

I do not know why, but I'm very very very happy because I can render+overlay right now without using the swap chain. (it is a miracle)

With your help I find a big problem in my computer's hardware  (I always had problems with rendering and CPU usage )

Thank you infinitely, and very thanks to the Helix.
