### ISSUE TITLE
Point3dCollection Performance Issue

### ISSUE THREAD

**Issue by matangpanchal** [helix-toolkit/helix-toolkit#588]
I am using Helixtoolkit.wpf since 3-4 years, till now I was using its older version only, but recently I updated it from the latest nuget package (1.0.0.0) and I found that every visual3d elements are using point3dcollection type to store points where earlier it was list<point3d>. So I changed every instance in In my code where I was assigning list<point3d> to point3d collection, Since then my application is perfoming very poorly. Inface Point3dcollection.add is very slow and it takes much more time then earlier.
So Is there any advantage of Point3dCollection over List<point3d> which I am not aware ? Am I missing something ?

**Comment by objorke** [comment]
I think you could 'unhook' the collection while adding points to it. See e.g. https://blogs.msdn.microsoft.com/timothyc/2006/08/31/optimizing-3d-collections-in-wpf/

**Comment by matangpanchal** [comment]
Your suggestion worked perfectly, only thing is that now I will have to take care this thing everywhere.
