### ISSUE TITLE
Error of loading .obj file

### ISSUE THREAD

**Issue by begun-v-do** [helix-toolkit/helix-toolkit#589]
Hi!
I try to load .obj file to the FileLoadDemo and got the error

> process cannot access the file

After a small research i find that the error appears for the materials which use one texture file (example of model is attached [DICE.zip](https://github.com/helix-toolkit/helix-toolkit/files/1582841/DICE.zip))

The FileStream try to read the texture file for each of material.
As workaround I add static field of dictionary which store paths to texture as key and FileStream as value in the MaterialDefinition class.
Before the loading of new texture file I check that the dictionary is not contain the path of this texture. 
Hope it's helps.

Sorry for my English =)

**Comment by vvs551** [comment]
The problem is in filestreaming 
In my post I give a solution: https://github.com/helix-toolkit/helix-toolkit/issues/590
Unfortunately there is needing to override all object reader, because it has not virtual voids (

**Comment by holance** [comment]
Temp fix the issue in #591 
You can also get the loader code and create your own loader.
