### ISSUE TITLE
Wpf.SharpDX ObjectReader Exceptions

### ISSUE THREAD

**Issue by vvs551** [helix-toolkit/helix-toolkit#590]
There is an exception when ObjectReader is trying to read two or more times a single OBJ file with textures
It's may be needing when you create a scene with the same object in different places (f.e. forest)
The problem is in CreateMaterial
Could you change filestreaming in  this function with something like following? It will help
Thank you

var time = System.Diagnostics.Stopwatch.StartNew();
while (time.ElapsedMilliseconds < 5000)
{
    try {
        mat.DiffuseMap = (this.DiffuseMap == null) ? null : new FileStream(Path.GetFullPath(
                          Path.Combine(texturePath, "./" + this.DiffuseMap)), FileMode.Open, 
                          FileAccess.Read, FileShare.ReadWrite);
        mat.NormalMap = (this.BumpMap == null) ? null : new FileStream(Path.GetFullPath(
                           Path.Combine(texturePath, "./" + this.BumpMap)), FileMode.Open, 
                           FileAccess.Read, FileShare.ReadWrite);
                        return mat;
      }
      catch (IOException e) {
                        // access error
                        if (e.HResult != -2147024864)
                            throw;
       }
}

**Comment by holance** [comment]
Temp fix the issue in #591 
You can also get the loader code and create your own loader.
