### ISSUE TITLE
get bounds of the model on startup

### ISSUE THREAD

**Issue by gregorsGit** [helix-toolkit/helix-toolkit#594]
Hi,
i try to get the bounds of some MeshGeometryModel3D in my viewmodel.
I use the WPF.SharpDX project.
Only when the model is attached, the bounds are correct.
So I can´t calc the correct position for a new MeshGeometryModel3D.
In the WPF project the bounds are set correct on startup.
Is there a way to force recalc bounds from code, even when the renderer is not startet?
Thanks

**Comment by holance** [comment]
You can get the bound from Geometry3D, there is and UpdateBound function to update the model bound. But you will only get the model space bound, not the bound with Transform.

**Comment by gregorsGit** [comment]
In your FindBounds method i miss the bounds from the child-objects.
I modify it like this.

        public static Rect3D FindBounds(this Viewport3DX viewport)
        {
            var bounds = new global::SharpDX.BoundingBox();
            foreach (var element in viewport.Renderables)
            {
                bounds = FindBoundsDeep(element, bounds);              
            }
            return new Rect3D(bounds.Minimum.ToPoint3D(), (bounds.Maximum - bounds.Minimum).ToSize3D());
        }

        private static BoundingBox FindBoundsDeep(object element, BoundingBox bounds)
        {
            BoundingBox currentbounds = bounds;
            var model = element as IBoundable;
            if (model != null)
            {
                var compositeModel3D = element as CompositeModel3D;
                if (compositeModel3D != null)
                {
                    foreach (var item in compositeModel3D.Children)
                    {
                        currentbounds = FindBoundsDeep(item, currentbounds);
                    }
                }
                else
                {                    
                    if (model.Visibility != Visibility.Collapsed)
                    {
                        return global::SharpDX.BoundingBox.Merge(bounds, model.BoundsWithTransform);
                    }
                }
            }
            var groupElement3D = element as GroupElement3D;
            if (groupElement3D != null)
            {
                foreach (var item in groupElement3D.Items)
                {
                    currentbounds =FindBoundsDeep(item, currentbounds);
                }
            }          
            return currentbounds;
        }

**Comment by holance** [comment]
Please check the latest merge #624. Let me know if the find bound works as expected.

**Comment by gregorsGit** [comment]
I try the latest version. 
The bounds are not! relative to zero-point.
I get the min. or the max. position set to (0,0,0).
In the WPF Version I get the offset and the dimensions.

The bounds are set to 0,0,0 initial and not to null.
var bounds = new global::SharpDX.BoundingBox();

**Comment by holance** [comment]
It should be working now.

**Comment by gregorsGit** [comment]
Works now like the WPF part. 
Thanks.
