### ISSUE TITLE
SharpDX version : Clone/Copy a MeshGeometryModel3D at run-time

### ISSUE THREAD

**Issue by Mitra-M** [helix-toolkit/helix-toolkit#595]
Is there a way to clone/copy a MeshGeometryModel3D / MeshGeometry3D at run-time?
If No :
How to implement ICloneable interface for the MeshGeometryModel3D / MeshGeometry3D ?

Please give me guidance.

**Comment by holance** [comment]
Use instancing, check out the instancing example

**Comment by Mitra-M** [comment]
wow ! , instancing classes are great.
 Thank you very much.
