### ISSUE TITLE
WPF SharpDX : Render quality

### ISSUE THREAD

**Issue by Mitra-M** [helix-toolkit/helix-toolkit#600]
I need to animate 3DText (ExtrudedText) with maximum quality in the Viewport3DX.
but edges of 3DText are shaken / blinking even with MSAA="Maximum" and IsMultisampleEnabled = true.
 

you can animate (e.g. rotate Y ) Model3D in the ExtrudedTextHelixSharpDX sample to see this issue.

(With the regular version (not SharpDX) this problem is not there.)

Other than set the MSAA and IsMultisampleEnabled , what should I do?

**Comment by holance** [comment]
First, you need to fix the triangle winding order to counter clock wise in the text extrude extension.
You can use following fixed file.
[Extensions.zip](https://github.com/helix-toolkit/helix-toolkit/files/1628760/Extensions.zip)

Then set MeshGeometryModel3D.CullMode = Back.

Please let me know if there is any improvement.

**Comment by Mitra-M** [comment]
Thank you for the corrected extension file and your support.

While rendering quality improves with set MSAA and IsMultisampleEnabled ,But Unfortunately set "CullMode = Back" does not affect. (at least I can not see any quality improvement in the edges)

 Please tell me that can you see the problem (shake / blink) on your computer?
 Has the CullMode any improvement?

Could [this ](https://www.gamedev.net/forums/topic/647887-how-to-fix-z-fighting-when-drawing-an-edge/)be the problem?

**Comment by holance** [comment]
I did not see the shaking issue. Could you make a screenshot? 
If it is z-fighting, try to set the far field distance of the camera to smaller number or set the depth bias on MeshGeometryModel3D.

**Comment by Mitra-M** [comment]
It seems it s not z-fighting issues, because depth bias does not affect.

I think that is aliasing problem which is sometimes seen like shaking.

Please look at to this video files :
[output.zip](https://github.com/helix-toolkit/helix-toolkit/files/1632658/output.zip)

This image shows my computer graphics card settings :
![gpusettings](https://user-images.githubusercontent.com/17668160/34956623-42ed1d1c-fa3f-11e7-812a-650b1e033e6d.png)

**Comment by holance** [comment]
One issue I notice in the ExtrudedText extension is there are two set of mesh overlapped with each other in order to solve the normal issue. Maybe it is one potential cause of this problem you encountered. 
You can see in this function, it basically adds two duplicate mesh with reversed triangle order. Try to remove one function and see if the shaking is gone. I am not the expert on meshing, may need other people's help to fix this issue.

            foreach (var t in mesh.Triangles)
            {
                var v0 = t.GetVertex(2);
                var v1 = t.GetVertex(1);
                var v2 = t.GetVertex(0);

                // Add the top triangle.
                // Project the X/Y vertices onto a plane defined by textdirection, p0 and p1.                
                builder.AddTriangle(v0.Project(p0, u, v, z, 1), v1.Project(p0, u, v, z, 1), v2.Project(p0, u, v, z, 1));
                
                // Add the bottom triangle.
                builder.AddTriangle(v2.Project(p0, u, v, z, 0), v1.Project(p0, u, v, z, 0), v0.Project(p0, u, v, z, 0));
            }

**Comment by Mitra-M** [comment]
The shaking did not change by remove that functions.

So, For now, I decided to use the Helix-WPF instead of Helix-WPF-SharpDX to render 3D texts.

If the problem is fixed in the future, I will let you know.

Thank You Very Very Much for your time and support.
