### ISSUE TITLE
ZoomExtents currently not work

### ISSUE THREAD

**Issue by gregorsGit** [helix-toolkit/helix-toolkit#623]
Hi,

the current Wpf.SharpDX project have some problems.
I think you know most of them.
1. The ZoomExtents is complete wrong. 
2. Build-errors like:
error MC3074: The tag 'CallMethodAction' does not exist in XML namespace 'http://schemas.microsoft.com/expression/2010/interactions'. Line 115 Position 22.

I like your 3d-Text-Extruder in the simple-demo.  Looks very cool.

**Comment by holance** [comment]
ZoomExtents should be fixed in #624. Please try again.
Not sure about the second one you mentioned. Which project is it?

**Comment by holance** [comment]
Second issue is because you didn't install the VS Blend

**Comment by gregorsGit** [comment]
Ok. 
ZoomExtents ist working now.
One build error is:
WPF.SharpDX\InstancingDemo\MainWindow.xaml(41,22): error MC3074: The tag 'CallMethodAction' does not exist in XML namespace 'http://schemas.microsoft.com/expression/2010/interactions'. Line 41 Position 22.

**Comment by hypodyne** [comment]
That namespace 'http://schemas.microsoft.com/expression/2010/interactions'. is part of a library you can install via nuget. Microsoft.Expression.Interactions or something like that.

**Comment by holance** [comment]
Zoom extent fixed, close this issue
