### ISSUE TITLE
HelixToolkit.SharpDX fail on Intel HD graphic

### ISSUE THREAD

**Issue by slad38** [helix-toolkit/helix-toolkit#628]
HelixToolkit.Wpf.SharpDX v2.x.x fail with Exception Unhandled  on Intel HD graphic adapter 

Tested with. Intel Iris Pro 580  and Iris 5100 
 Windows10 Intel HD Driver Version: 23.20.16.4901(Latest)
Supports Intel(R) Iris(R) graphics, Intel(R) Iris(R) Pro graphics, Intel(R) Iris(R) Plus Graphics, Intel(R) UHD Graphics and Intel(R) HD graphics.

No problem with GeForce graphic adapter.

GeometryBufferModel.cs - line 270

**Exception Unhandled**  
System.AccessViolationException: 'Attempted to read or write protected memory. 
This is often an indication that other memory is corrupt.'

**Comment by holance** [comment]
GeometryBufferModel.cs only exists in new 2.0 develop branch. Please confirm whether you are using 1.1.0 or 2.x.x unstable build. Thanks.

**Comment by slad38** [comment]
Sorry.
 i'm using develop branch.
release v1.1.0 works fine.

**Comment by holance** [comment]
Are you running demo when it happens? I may need more information on this issue. Thanks.

**Comment by slad38** [comment]
Any examples demo fail immediately after splash window started and crashed in 2-3 seconds.
fe. BoneSkinDemo
![boneskindemo](https://user-images.githubusercontent.com/36540486/36327509-d5ea3b10-136f-11e8-9f82-0a7141bd7cb4.JPG)

**Comment by holance** [comment]
Are you be able to run debug build using visual studio? Let me know if there is any exception is thrown.

**Comment by holance** [comment]
I can reproduce this issue now. Will fix soon.

**Comment by holance** [comment]
Please try again.
