### ISSUE TITLE
Error runtime Helix sharpdx (1.1.0)

### ISSUE THREAD

**Issue by salvatore84** [helix-toolkit/helix-toolkit#631]
Hi,

I tryed to run the last demo version of the Helixtoolkit sharpdx (1.1.0) and I got an error when I run demo examples . In the window register events i can read this reference:

5a8aaa69
igd10iumd64.dll
C:\WINDOWS\SYSTEM32\igd10iumd64.dll
357b8cd8-1eec-4837-b401-8142fa623253

This problem there is only on some pcs (notebook). I think it's related to the sharpdx library.

Could you please help me?

Salvatore

**Comment by holance** [comment]
Are you running demo from develop branch or 1.1.0 branch?

**Comment by salvatore84** [comment]
v1.1.0 branch develop 2018-02-06

thanks

**Comment by holance** [comment]
What's your computer configuration?

**Comment by holance** [comment]
Seems like you are using develop branch? Please update to the latest. The 1.1.0 release version is under 1.1.0/release branch. The current develop branch is for next 2.x.

**Comment by salvatore84** [comment]
Thanks,

I tryed to run the last update of develop branch and it's Ok. 

Your framework is very fine! When version 2.0 will be available?

**Comment by holance** [comment]
Still need a lot of test, will be released once it's stable.

**Comment by salvatore84** [comment]
Thanks,

have a good work!
