### ISSUE TITLE
Vertices Positions Snapping to infinity when accessing the mesh

### ISSUE THREAD

**Issue by samhightech** [helix-toolkit/helix-toolkit#644]
![image](https://user-images.githubusercontent.com/36849141/36671450-a9cf98b4-1b0c-11e8-8f9a-264068e8e049.png)

like in the image when I do some operation on the GeometryModel3D transform some positions go crazy in space, what is the logical explination for this ?

**Comment by holance** [comment]
Try to multiply your transform with your model vertex positions to check if any value is wrong.
