### ISSUE TITLE
How can I change the zoom and scrolling speed, and the center point of rotation?

### ISSUE THREAD

**Issue by Super169** [helix-toolkit/helix-toolkit#646]
I have a small project need to display many small 3D models in STL, below is the size & location of the biggest part:

Bounds.Size: {0.101076416671276,0.111662406474352,0.215390831232071}
Bounds.Location: {-0.050395779311657,-0.0633979141712189,0.201827228069305}

I have tried very long time to move the camera to display it in the center, I record the setting and initialize the Camera as below:

            viewPort3d.Camera.LookDirection = new Vector3D(841.296, -659.034, 137.246);
            viewPort3d.Camera.UpDirection = new Vector3D(-0.672, 0.526, 0.522);
            viewPort3d.Camera.Position = new Point3D(-5.798, 4.966, 0.098);

which can show the model in the center of screen, but still very small, less than 1/100 of the screen.

![normal](https://user-images.githubusercontent.com/3852502/36731351-7317bbea-1c05-11e8-94f6-99ba6a66e642.png)

If I apply ScaleTransform3D with 10000 on each axis, it works fine.  But it need to apply such transformation whenever I rotate any parts of the model.  There has some reason that I need to keep the stl with the original size, so I cannot scale the STL in advance.

Even I can display it with proper camera setting as above, but the camera move too fast in this case, and it will easily running out of screen when I scroll or move via the mouse.

I found some suggestion in stackoverflow which may modify the CameraController of viewport3d, and I have modified the program as suggested.  But unfortunately, it return error as CameraController is always null, and I cannot assign a new CaameraController() to it.

I'd like to know if there has any way to change the scrolling/scaling speed, and also set the center point of rotation always in the center of model.

**Comment by holance** [comment]
You need to set your Camera Position to proper location to make the model bigger, not the look direction.

**Comment by holance** [comment]
To manually change rotation point, use FixedRotationPointEnabled =true and FixedRotationPoint properties in Viewport3DX. Manually look at point, use ManualLookAtPoint property

**Comment by Super169** [comment]
I just use the mouse to scroll and move to get the setting as above, I knew that making the camera closer can make it bigger, but up to this setting, whenever I move the mouse (just a little bit), the model will be moved out of screen.    So, even I can get a better position by changing the figure of camera position, it can not be use also.  Is it possible to reduce the scrolling/scaling speed?

For your suggestion of FixedRotationPointEnabled and FixedRotationPoint, may I know how I can change the setting? I'm now using  HelixViewport3D, it's seems that HelixViewport3D does not have such properties, may I know if it can be done in HelixViewport3D?

Thanks a lot.

**Comment by holance** [comment]
It can be done with the same way in viewport 3dx. You can take a look at the helix sharpdx project.

**Comment by holance** [comment]
For zoom speed, you can change ZoomSensitivity property on viewport

**Comment by Super169** [comment]
Thanks a lot.  
Eventually, due to performance issue, I have changed the whole project to use SharpDX.
It works fine now.

**Comment by augre** [comment]
Did you figure out why was CameraController always null?

**Comment by holance** [comment]
Camera controller in wpf version is set in theme.xaml, it is initialized only after Viewport is loaded.
