### ISSUE TITLE
Get bounds of model in MVVM

### ISSUE THREAD

**Issue by gregorsGit** [helix-toolkit/helix-toolkit#648]
Hi,
in WPF I use the function Visual3DHelper.FindBounds(children) to get the bounds 
of models.
With this bounds i calculate new distances between the models in the ViewModel.

In the SharpDX project there is no such function.
I try some things like 
- model.BoundManager.Geometry = model.Geometry;
- call the Update(null) on every model.
to force setting the bounds directly.
But the BoundsWithTransform are mostly not correct.

I need such a function, even when the RenderHost is not attached!
Please help.

**Comment by holance** [comment]
Use Geometry.UpdateBound, then each geometry will have its own local bound. Use boundingbox.Transform to get the transformed bound. You can easily write your own function to get the bounds.

**Comment by gregorsGit** [comment]
Thanks, 
I write a function doing this.
But it was not so easy, iterating all submodels and its transforms.

**Comment by gregorsGit** [comment]
Getting the bounds befor render done is still a problem.
With the following change in HelixToolkit.Wpf.SharpDX.Model.Scene GeometryNode.cs I can get the bounds correct.
 ```
 public Geometry3D Geometry
        {
            set
            {
                var old = geometry;
                if (Set(ref geometry, value))
                {
                    BoundManager.Geometry = value;
                    if (IsAttached)
                    {
                        
                        BufferModelInternal = OnCreateBufferModel(this.GUID, value);
                    }
                    OnGeometryChanged(value, old);
                    InvalidateRender();                   
                }
            }
            get
            {
                return geometry;
            }
        }
```

**Comment by holance** [comment]
Fixed.
