### ISSUE TITLE
Transform Update when GroupModel3D changed

### ISSUE THREAD

**Issue by gregorsGit** [helix-toolkit/helix-toolkit#656]
Hi,
I am not sure, if this is a bug or not.

I have a GroupModel3D or CompositeModel3D in XAML.
```
            <hx:GroupModel3D
                ItemsSource="{Binding CompositeChildren}"
                Transform="{Binding Model3Transform}"               />
```

After the program starts I see the models with its Transform.
When I add on new MeshGeometryModel3D at runtime, the Transform is not applied.
I think the Transform must be applied automatic on ItemChange.

To get this working, I change the GroupModel3D.Transform to a different Value and back again.
For this simple situation it is ok. 
But I have GroupModel3D in GroupModel3D an so on...

**Comment by holance** [comment]
Will fix in next PR
