### ISSUE TITLE
No fxc path found - compile error

### ISSUE THREAD

**Issue by VE-2016** [helix-toolkit/helix-toolkit#660]
Dear Sirs,
During building HelixToolkit.SharpDX the following error is encountered
- No fxc.exe found.
How to remove this error?

Kind regards,
JK

**Comment by holance** [comment]
(Missing fxc.exe issue with newest Windows 10 SDK: Copy fxc.exe in C:\Program Files (x86)\Windows Kits\10\Bin\10.0.xxx\x86 to C:\Program Files (x86)\Windows Kits\10\bin\x86 to fix this issue. Because the HLSL compile tool hard coded the path.)

Laptops with Nvidia Optimus (Dual graphics card)

**Comment by VE-2016** [comment]
That's now everything compiles well. I am glad for getting quick answer. Much success and good ideas in developing excellent and useful  software!

Best regards,
JK
