### ISSUE TITLE
How do I change the viewcube direction?

### ISSUE THREAD

**Issue by pipited07** [helix-toolkit/helix-toolkit#661]
This is a pretty straight forward question. I want  rotate the viewcube 90 degree so that the "D" can be right. Is there any way to do that or better idea?
![image](https://user-images.githubusercontent.com/22461372/37272922-20bb5506-2613-11e8-8ec1-c51459788305.png)

**Comment by jotschgl** [comment]
I suggest to change the ModelUp direction to 0,0,1

**Comment by pipited07** [comment]
@jotschgl  Thank you, it fix my problem.
