### ISSUE TITLE
ParticleSystemDemo screen output

### ISSUE THREAD

**Issue by vvs551** [helix-toolkit/helix-toolkit#665]
Very strange ParticleSystemDemo behavior in HelixToolkit.SharpDX
And nothing happens.. What does it mean?
![particles](https://user-images.githubusercontent.com/14919853/37401526-f84ea62a-2790-11e8-83c4-44497f5a3a71.jpg)

**Comment by holance** [comment]
Is your system using the dual graphics card? Try to use the external graphics card to run the demo. I'm having the same issue with my laptop if running using integrated graphics card. But my another laptop works fine. Still trying to figure out the issue.

**Comment by holance** [comment]
Finally found the issue. Seems like some intel integrated GPU unable to use copy structure count to copy count onto constant buffer directly. But nvidia GPU can do it without problem.  Will fix in next PR.

**Comment by holance** [comment]
Please try again and let me know if it works now.

**Comment by holance** [comment]
If it still happened. Please reopen this issue. Should have been fixed already.

**Comment by vvs551** [comment]
Thank you
It is working for me
