### ISSUE TITLE
Imported OBJ File just blank screen 

### ISSUE THREAD

**Issue by sweti3** [helix-toolkit/helix-toolkit#666]
Hi,

I have build up a project. First i want to import an *.obj file. Then i want to manipulate it. So that the user can drag an drop elements onto the obj file and they stick to their position. Is this possible? 

When i Import an *.obj file it first looks like this:

this is the car i want to import:

![image](https://user-images.githubusercontent.com/13781132/37403233-6cbc7c24-278e-11e8-9bb3-1ab3d5a920b5.png)

Then when i say in the project:
` //Path to the model file
        private const string MODEL_PATH = "natla car.obj";

        public MainWindow()
        {
            InitializeComponent();
            ModelImporter import = new ModelImporter(); Model3DGroup model1 = import.Load(MODEL_PATH); model.Content = model1;

        }
 `  

The Screen looks like this, happening with all my *.obj files. Even Demos from the internet:

![image](https://user-images.githubusercontent.com/13781132/37403274-8f74313a-278e-11e8-86f6-0e8662b2bd92.png)

Can you fix this? Project is attached.
[display3D-master.zip](https://github.com/helix-toolkit/helix-toolkit/files/1811101/display3D-master.zip)

Thanks!!!

**Comment by sweti3** [comment]
Ok I feixed it by myself. Another issue: Can I interact with that *.obj element? I want to do a right click on a specific position of the car and add a rectangle or a custom box with some text fields inside. This box should be attached to the specific position of the car, no matter how i flip the object. Is that possible ?

**Comment by holance** [comment]
Get the hit test result and add a billboard on that hit location.

**Comment by sweti3** [comment]
Ok thanks a lot. Now this works fine for the moment. However, I want to put on some interaction with the Model. whenever i do a rightclick, I spawn a sphere on top of my surface. When i do a double left click on this sphere some menu should pop up or i want a textbox and some dropdown menu on that sphere. How is that possible?
![image](https://user-images.githubusercontent.com/13781132/37447888-63a96d04-2824-11e8-8e01-602bee431372.png)

Searched the whole internet, but found nothing that matches my needs. Am I the only one who wants to do things like that:O?

**Comment by holance** [comment]
The only simple way is just use wpf control on top of the viewport. You can use a popup control at mouse point to show a menu when you click the sphere.

**Comment by sweti3** [comment]
So I tried to use something like this: If the Mouse is inside the bounds of an existing sphere, do not create a new one. Or if it is and there is a right click, open the context menu.

However, I think the mouse is on the "Pixel coordinates" of my screen, and the *.obj object is in "real" x,y,z coordinates. Why do I assume this? 

If the screen is small, i can add several spheres:

![image](https://user-images.githubusercontent.com/13781132/37462186-515ff6fe-2851-11e8-91c8-0296e7de079c.png)


But if I enlarge the window of my application, I can add as many as i want on one spherE:

![image](https://user-images.githubusercontent.com/13781132/37462213-6c4bb93a-2851-11e8-9d1e-c9dfad23f752.png)


Can you help me? Sadly there is no docu available ... Thanks ! !

**Comment by holance** [comment]
You need to do hit test for your sphere.

**Comment by sweti3** [comment]
Okay, can I do that also in the method where I hit test for the obj file and the mouse? Or do I have to create another function therefore? I have a List of Spheres everywhere on the car. How do I perform a hottest on each of them ?



-----Original Message-----

**Comment by holance** [comment]
You can use HelixViewport3D.FindNearestPoint

**Comment by sweti3** [comment]
Is there an example anywhere? FindNEarest Point, what does that exactly? I have my 3D Surface and this method will find the nearest object to the mouse of the type I want or how can I understand this ?

**Comment by holance** [comment]
See helix-toolkit\Source\Examples\WPF\ExampleBrowser\Examples\Lego

**Comment by sweti3** [comment]
Cant open or run the solution:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'HelixToolkit 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0,Profile=Client', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by holance** [comment]
You need to download the source code, and open the helixtoolkit.wpf solution

**Comment by sweti3** [comment]
So I opened the HelixToolkit.Wpf_NET40.csproj and build it. But what then? Thought I can just run your example code?

**Comment by sweti3** [comment]
Ok found it now. So:

`Viewport3DHelper.FindNearestPoint(view1.Viewport, p);`

where p is my mouse position but where can I tell the method, to look for the nearest point (sphere)? When I now use this method, the nearest point on the viewport may also be the car model which is not what i want?

**Comment by sweti3** [comment]
Got it half way with the buildings demo:

![image](https://user-images.githubusercontent.com/13781132/37513507-90e15a34-2905-11e8-9f14-2774ea18c230.png)


Now I have the bounds around the sphere. But how can I realize a doubleclick on it opens up a context menu?! Thanks!

**Comment by sweti3** [comment]
I want to access the .Center Property of the found object but I can´t access it? Why?

![image](https://user-images.githubusercontent.com/13781132/37521981-d3d298fe-2922-11e8-8eb2-844c69ff4223.png)

**Comment by holance** [comment]
Because you need to cast the type back to the sphere model first........

**Comment by sweti3** [comment]
Works fine now, thanks.

**Comment by lucasschoch** [comment]
I'm with the same first issue:
Imported OBJ File just blank screen

How did you solve it?

**Comment by hoseinCode** [comment]
i have same Problem (imported OBJ file using Pywavefront) Just Blank screen and CRASH in pycharm
