### ISSUE TITLE
How to Export and Import a scene (all Spheres on a car e.g.) ? 

### ISSUE THREAD

**Issue by sweti3** [helix-toolkit/helix-toolkit#676]
How can I export and later Import all placed elements, I put on my *.obj file? This would be really neccessary:

![image](https://user-images.githubusercontent.com/13781132/37699974-268c9dcc-2cea-11e8-8a81-23edf4ee94fb.png)

Export seems to work, but how to import this xaml file again ?! Thanks a lot! Attached is the XAML file (as *.zip):
[test123.zip](https://github.com/helix-toolkit/helix-toolkit/files/1832457/test123.zip)

**Comment by sweti3** [comment]
I could not find any function for that now sadly.

**Comment by holance** [comment]
I would suggest you to write your own data serialization to serialize your view model or data.

**Comment by sweti3** [comment]
I did that. However Now I am running into hard problems. I exported everything correctly, the import seems to work aswell. but when I call viewport3D.children.Remove(foundSphere) then It will delete the sphere and the billboard but not the 3D Line, altough it is a child element of the found Sphere. Is this a known bug ?

**Comment by sweti3** [comment]
![image](https://user-images.githubusercontent.com/13781132/37904517-54882794-30fc-11e8-95e2-be53dbcba3a0.png)

**Comment by holance** [comment]
I don't remember there's a bug about this issue. Maybe be 3d line is duplicated under another model?
