### ISSUE TITLE
SwapChainRendering on virtual machine : NullReferenceException

### ISSUE THREAD

**Issue by Aerevia** [helix-toolkit/helix-toolkit#680]
Is SwapChainRendering supported on virtual machines with no gpu ?
I'm using HelixToolkit.Wpf.SharpDX 1.1.0.0

I get this error when starting the app on a virtual machine
![NullReferenceException](https://user-images.githubusercontent.com/13220181/37784534-558cc87c-2df8-11e8-9b85-fdec18ad8a20.PNG)

It supports DirectX11

![capture6](https://user-images.githubusercontent.com/13220181/37784680-abad3200-2df8-11e8-93a1-e69c0ab2bdfd.PNG)
![capture7](https://user-images.githubusercontent.com/13220181/37784682-abe49d26-2df8-11e8-8ca4-3ae1fb1fefed.PNG)

**Comment by holance** [comment]
Is it working without swap chain? I am not sure about the virtual machine, you can try to debug and see if the swap chain is created correctly.

**Comment by Aerevia** [comment]
It works without swapchain enabled but the performance is bad.

Can you guide me a little on how to debug this please? 

I'm hosting a WPF control library in a winforms control library hosted in another software.. (yes, that was the only way to make things work)

**Comment by holance** [comment]
I am not sure how powerful is the virtual graphics card. May be the performance issue is not because of the swapchain, it is the virtual graphics card.  Try to set EnableDeferredRendering = false, and EnableSwapChainRendering = true to see if it works.

**Comment by Aerevia** [comment]
It loads with EnableDeferredRendering = false, and EnableSwapChainRendering = true but it still laggy, can't really fix this without adding a GPU I guess.
