### ISSUE TITLE
Streaming Quaternion rotation data flipping at poles.

### ISSUE THREAD

**Issue by antithing** [helix-toolkit/helix-toolkit#682]
I am tracking an object and streaming rotation data into Helix toolkit Viewport3d as quaternions, and animating a `Model3DGroup`. When I rotate the tracked object on mainly one axis, there is a point in the rotation where I see a 'pop' in the animated object. It flips 180 degrees for one frame or so, then flips back. After logging the data, it is at the point where the W value of the Quaternion switches from positive to negative.

For example, between these two quats causes the flip:

 quat X=-0.114393666 Y=0.021080395 Z=-0.152206704 W=0.021299114
 quat X=-0.237416491 Y=0.035950743 Z=-0.440504611 W=-0.030504957
 
When i plot these rotations, they are very similar, but the values are negated, which is causing the animation to flip between them.

The related code is:
```

Model3DGroup markerGrp = new Model3DGroup ();
 var matrixCam = new Matrix3D();

trans.X = Fiducial.position[0] / 10;
trans.Y = Fiducial.position[1]  / 10; 
trans.Z = Fiducial.position[2] / 10;

quat.X = Fiducial.rotationQuats[0];
quat.Y = Fiducial.rotationQuats[1];
quat.Z = Fiducial.rotationQuats[2] ;
quat.W = Fiducial.rotationQuats[3];

matrixCam.Rotate(quat);
matrixCam.Translate(trans);
       
markerGrp.Transform = new MatrixTransform3D(matrixCam);
                
```

Is there any way I can account for these flips and get rid of them?

I have tried:

```
if(quat.W < 0)
{
quat.X = quat.X * -1;
quat.Y = quat.Y * -1;
quat.Z = quat.Z * -1;
}
```

But I see the same behavior.

thank you.

**Comment by holance** [comment]
Is this [stackoverflow topic](https://stackoverflow.com/questions/42428136/quaternion-is-flipping-sign-for-very-similar-rotations) related to your problem?

**Comment by antithing** [comment]
Thanks for your reply. That is where i got this  from:

```
if(quat.W < 0)
{
quat.X = quat.X * -1;
quat.Y = quat.Y * -1;
quat.Z = quat.Z * -1;
}
```


But I still see the issue
