### ISSUE TITLE
Please add ModelImporter for GLB format as well. That format is quite popular nowadays

### ISSUE THREAD

**Issue by itsmenishantchawla** [helix-toolkit/helix-toolkit#684]

**Comment by holance** [comment]
I am thinking about wrapping a third party library (maybe https://github.com/assimp/assimp) for all the import/export. Help wanted! :)

**Comment by zlzshowtime** [comment]
- If this issue is still open, I'd like to take a crack at it!

**Comment by holance** [comment]
Yes, help wanted:)

**Comment by holance** [comment]
Implemented in Assimp impoter.

**Comment by sylvain44730** [comment]
Hi all ! a lot of very interesting 3D models could be used from sketchfab.com the standard format is gltf2. I am able to open those files in HelixToolkit.SharpDX.WPF.FileLoadDemo exemple. But if i modify original file in blender and save this as gltf2 it seems assimp can t load them. Is there a way to have a standard gltf2 loader in helix ? I would like to help community to develop it but think my lvl is too low... Is gltf2 is compatible with PBR format ? Where could we use Base, Metallic, Roughness composant of gltf2 in helix ? Thanks for help
