### ISSUE TITLE
Render to bitmap image?

### ISSUE THREAD

**Issue by N4rk0** [helix-toolkit/helix-toolkit#692]
Any easy way to render to an image?

**Comment by holance** [comment]
Please check #694. Now the Viewport3DX has the extension to render current screen onto bitmap or save current screen. Is this what you are looking for?

**Comment by N4rk0** [comment]
Hi, thanks for your effort ( for the SortingGroupModel3D issue too ).
I was actually thinking of a more direct way of rendering to an image, without creating a wpf window at all, just using the Viewport3D.
But also this works ok anyway by creating a wpf window ( including a viewport) positioned out of the scree so the user doesn't notice it, taking the shot and closing the window.
