### ISSUE TITLE
Wpf.SharpDX: Out of Memory loading huge 3ds model

### ISSUE THREAD

**Issue by gregorsGit** [helix-toolkit/helix-toolkit#698]
Hi,
I think its not a bug, its more a question. 
This model is extrem bad optimized.
In your fileload example this model is loaded with about 1.5GB RAM usage.
When I load a second model the memory was not cleaned and its crashes mostly. 
On my system.

[holes.zip](https://github.com/helix-toolkit/helix-toolkit/files/1886279/holes.zip)

Your model simplifiyer ist much to slow for models like this.

Question:
What can I change to to reduce the memory-usage?

Thanks

**Comment by holance** [comment]
Your model contains too many small meshes. You need to either merge them into limited number of large meshes or load them separately. If your mesh are the same except at different locations, use instancing.

**Comment by holance** [comment]
Seem like your model having same meshes thousands of times. Use instancing is a the way to go.

**Comment by gregorsGit** [comment]
Hi,
thanks for evaluate this model.
I merge all into only 2 extrem large meshes. This method works for all meshes with the same materials.
This reduces the memory usage round about 50%.
I clean up this code an post it later.

Currently testing the models in your 3ds-Example-Models I found the Ferarri40.3ds is actualy totaly damaged.

Hope I don´t confuse your great work.

**Comment by gregorsGit** [comment]
I try loading the Ferarri40.3ds model in other viewer like blender..
and its deformed/exploded. 
Your transform is correct.

I combine the meshes, after import, with this method. 
[meshcombiner.zip](https://github.com/helix-toolkit/helix-toolkit/files/1923112/meshcombiner.zip)
This reduces the memory about 50%.


Further questions:
Are there any other ways to reduce the memory-footprint?
Like:
IsDepthClipEnabled = true, 
MSAALevel=??
??

Instancing i not possible to automate for me.
Thanks.

**Comment by holance** [comment]
Those settings does not reduce the memory. Only help on rendering. The memory is caused by the large mesh. The only simple way to reduce memory on rendering duplicate meshes is using instancing.
