### ISSUE TITLE
Error with the file paths!

### ISSUE THREAD

**Issue by sweti3** [helix-toolkit/helix-toolkit#700]
Hi, I always run into a non readable error message:

When Reading a Model I get the file path via an open file dialog:

![image](https://user-images.githubusercontent.com/13781132/38484417-d31340c8-3bd6-11e8-8cf5-bf0fcfcec1c8.png)

But I am running into this issue:

![image](https://user-images.githubusercontent.com/13781132/38484428-dcbe6166-3bd6-11e8-99aa-e21c593df109.png)

The path is correct, however the helixtoolkit refufes to open this file ? This is how I create the model3D Group and import the file:

![image](https://user-images.githubusercontent.com/13781132/38484463-fb3373ca-3bd6-11e8-833d-5b4decab9969.png)
![image](https://user-images.githubusercontent.com/13781132/38484470-024b511e-3bd7-11e8-938d-204fb36ed395.png)

But this doesnt work. I need help urgently!

**Comment by holance** [comment]
Seems like there is an error reading your obj file. Are you be able to provide the obj file causing this error?

**Comment by sweti3** [comment]
Sure:
[sclass.zip](https://github.com/helix-toolkit/helix-toolkit/files/1888856/sclass.zip)

**Comment by sweti3** [comment]
I got the error again after rebuilding my project...

**Comment by holance** [comment]
Hmm, i am not getting this error loading your model.
