### ISSUE TITLE
How can I rotate camera to change the position of models？

### ISSUE THREAD

**Issue by younibugudano** [helix-toolkit/helix-toolkit#707]
I rotate the camera to change the position of models in HelixViewport3D for WPF ,with it's coordinate system changes too. In a word, I want to replace RightMouseClick with Buttons and rotate the camera by angle.
![image](https://user-images.githubusercontent.com/34259213/38603867-61ca86c0-3da1-11e8-97fb-6ff4bdc82d9d.png)

Now I have two attempts:
1.
`this.viewPort3d.CameraController.StartSpin(new Vector(10,10),new Point(20,1),new Point3D(0,0,0));`

2.
```
               var updirection = this.viewPort3d.Camera.UpDirection;
                var lookdirection = this.viewPort3d.Camera.LookDirection;
                const double PI_ = 3.1415926;
                double cos45 = Math.Cos(45 / 180 * PI_);
                double sin45 = Math.Sin(45 / 180 * PI_);
                updirection.Normalize();
                lookdirection.Normalize();
                var newVector3d1 = updirection * cos45;
                var double1 = (1 - cos45) * Vector3D.DotProduct(lookdirection, updirection);
                var newVector3d2 = double1 * lookdirection;
                newVector3d1 = Vector3D.Add(newVector3d1, newVector3d2);
                var newvector3 = sin45 * Vector3D.CrossProduct(lookdirection, updirection);
                newvector3 = Vector3D.Add(newVector3d1, newvector3);

                PerspectiveCamera myPCamera = new PerspectiveCamera();

                myPCamera.UpDirection = newvector3;
                myPCamera.LookDirection = new Vector3D(0, 0, -6818.122);
                //myPCamera.LookDirection = lookdirection;
                myPCamera.Position = new Point3D(12.026, -14.059, 7003.243);

                // Define camera's horizontal field of view in degrees.
                myPCamera.FieldOfView = 20;
                this.viewPort3d.Camera = myPCamera;
```
thanks a lot

**Comment by younibugudano** [comment]
![image](https://user-images.githubusercontent.com/34259213/38604208-47aa198a-3da2-11e8-834c-0943b1f437d7.png)
Although the second attempt has achieved  the rotation of camera, the effect is not good.

**Comment by holance** [comment]
I think use Camera.LookAt(Point3D target, Vector3D newLookDirection, Vector3D newUpDirection, double animationTime) is better way to go. 

Not sure about what you mean about the "effect is not good".

By the way, you only needs to set the current camera properties in viewport.camera instead of create a new camera each time you rotate it.

**Comment by younibugudano** [comment]
![image](https://user-images.githubusercontent.com/34259213/38606055-a594b1cc-3da7-11e8-831e-11e7b7b5e7d1.png)
The model's position changes When I click the button. 
I noticed the method before, but I don't want the animationTime Parameter .If I set animationTime=0,it doesn't work.

**Comment by younibugudano** [comment]
And now i don't know how to set the spin Vector3D or spin axis.

**Comment by holance** [comment]
You need to calculate the new camera look direction using your angle and axis.

**Comment by younibugudano** [comment]
I find the resource code in CameraController/RotateHandler.cs 👍  
`
        /// <summary>

        /// The rotate trackball.

        /// </summary>

        /// <param name="p1">

        /// The previous mouse position.

        /// </param>

        /// <param name="p2">

        /// The current mouse position.

        /// </param>

        /// <param name="rotateAround">

        /// The point to rotate around.

        /// </param>

        private void RotateTrackball(Point p1, Point p2, Point3D rotateAround)

        {

            // http://viewport3d.com/trackball.htm

            // http://www.codeplex.com/3DTools/Thread/View.aspx?ThreadId=22310

            var v1 = ProjectToTrackball(p1, this.CameraController.Viewport.ActualWidth, this.CameraController.Viewport.ActualHeight);

            var v2 = ProjectToTrackball(p2, this.CameraController.Viewport.ActualWidth, this.CameraController.Viewport.ActualHeight);



            // transform the trackball coordinates to view space

            var viewZ = this.Camera.LookDirection;

            var viewX = Vector3D.Cross(this.Camera.UpDirection, viewZ);

            var viewY = Vector3D.Cross(viewX, viewZ);

            viewX.Normalize();

            viewY.Normalize();

            viewZ.Normalize();

            var u1 = (viewZ * v1.Z) + (viewX * v1.X) + (viewY * v1.Y);

            var u2 = (viewZ * v2.Z) + (viewX * v2.X) + (viewY * v2.Y);



            // Could also use the Camera ViewMatrix

            // var vm = Viewport3DHelper.GetViewMatrix(this.ActualCamera);

            // vm.Invert();

            // var ct = new MatrixTransform3D(vm);

            // var u1 = ct.Transform(v1);

            // var u2 = ct.Transform(v2);



            // Find the rotation axis and angle

            var axis = Vector3D.Cross(u1, u2);

            if (axis.LengthSquared() < 1e-8)

            {

                return;

            }



            var angle = u1.AngleBetween(u2);



            // Create the transform

            var delta = Quaternion.RotationAxis(axis, -(float)(angle * this.RotationSensitivity * 5));

            var rotate = Matrix.RotationQuaternion(delta);



            // Find vectors relative to the rotate-around point

            var relativeTarget = rotateAround - this.Camera.Target;

            var relativePosition = rotateAround - this.Camera.Position;



            // Rotate the relative vectors

            var newRelativeTarget = Vector3D.Transform(relativeTarget, rotate).ToVector3();

            var newRelativePosition = Vector3D.Transform(relativePosition, rotate).ToVector3();

            var newUpDirection = Vector3D.Transform(this.Camera.UpDirection, rotate).ToVector3();



            // Find new camera position

            var newTarget = rotateAround - newRelativeTarget;

            var newPosition = rotateAround - newRelativePosition;



            this.Camera.LookDirection = newTarget - newPosition;

            if (this.CameraMode == CameraMode.Inspect)

            {

                this.Camera.Position = newPosition;

            }



            this.Camera.UpDirection = newUpDirection;

        }`
        I have solved the issues.Thks
