### ISSUE TITLE
GetScreenViewProjectionMatrix3D returns all zero in HelixToolkit.Wpf.SharpDX

### ISSUE THREAD

**Issue by vvs551** [helix-toolkit/helix-toolkit#708]
Because viewport.GetViewProjectionMatrix() returns
{[M11:0 M12:0 M13:0 M14:0] [M21:0 M22:0 M23:0 M24:0] [M31:0 M32:0 M33:0 M34:0] [M41:0 M42:0 M43:0 M44:0]}
Viewport3DX viewport is good working 
Camera is assigned
There is a last development build

**Comment by holance** [comment]
Is the viewport showing on the screen? You can also get the matrix from Camera directly.

**Comment by vvs551** [comment]
Yes, viewport is showing.
This problem take place when I put GetVewProjection matrix in WPF ContentRendered handler, like in first version of helixtoolkit:
 var presentationSource = PresentationSource.FromVisual((Visual)s);
 presentationSource.ContentRendered += RangeControl_ContentRendered; 
 private void RangeControl_ContentRendered(object sender, EventArgs e)
 {
    var point_2d = ViewportExtensions.Project(viewport, point_3d);
 }

When I move it to window.Loaded handler this problem is out. I hope.. ) Will continue testing..

**Comment by holance** [comment]
RangeControl_ContentRendered does not guarantee the viewport has been fully initialized.

**Comment by vvs551** [comment]
Ok ThankU!

**Comment by holance** [comment]
I Added an OnRendered event in viewport3dx. You can use this event to notify when content is rendered. **But remember to unsubscribe it when not being used. OnRendered is being called after every frame is rendered. ** 

Reopen this if you still experiences zero viewprojection matrix issue.
