### ISSUE TITLE
Support point rendering

### ISSUE THREAD

**Issue by objorke** [helix-toolkit/helix-toolkit#71]
Add support for point rendering in HelixToolkit.Wpf.SharpDX

**Comment by smischke** [comment]
Is someone still working on this? Otherwise I would extend this a little:
- round points
- LineColor + Color
- LineThickness + Thickness (at the moment, it has fixed size as far as I can see)
- hit testing

**Comment by Fireforge** [comment]
I'm also in need of those features @smischke mentioned, specifically changing thickness for the application of displaying point clouds. The points too big for the contours in the point cloud to be visible unless the camera gets really close to the cloud, which renders it almost useless.

**Comment by smischke** [comment]
I've implemented the features above but I haven't done a pull request yet. Monday I'm back in office and I'll do it then.
