### ISSUE TITLE
Prevent billboard rotation toward the camera

### ISSUE THREAD

**Issue by Mitra-M** [helix-toolkit/helix-toolkit#711]
Hi,

First, **Thank you very very much for the great new D2D + SwapChainRendering features** (  and D2DScreenMenuExample)

I need to make a text Ticker/Crawl that it can be rotated in three dimensional space. (Please look at [this picture](https://stackoverflow.com/questions/35830321/wpf-2d-in-3d-view-animations-performance-issue) )

and tell me how can I prevent BillboardTextModel3D to rotation toward the camera?

**Comment by holance** [comment]
You can use a quad mesh instead of a billboard, then you can rotate the same as other meshes

**Comment by Mitra-M** [comment]
OK ,Thanks.

Another question:
Which method do you think has better performance for large (20 kB) text.
1 - Text as texture on a quad mesh.
2 - Text to a polygon
3 - Something else?

**Comment by holance** [comment]
I would prefer texture for performance consideration. You can use high quality image as texture for text, the quality should not be a problem.

**Comment by Mitra-M** [comment]
holance, I learn a lot from you.
Thank you very much.
