### ISSUE TITLE
Change actions of touch gestures

### ISSUE THREAD

**Issue by KrabatTilt** [helix-toolkit/helix-toolkit#716]
I am using Viewport3DX and want to change the actions of certain touch gestures. What I need is a clean distinction between pan and zoom actions. This is no problem when just operation by mouse (LeftClick and MouseWheel) but when it comes to touch input both overlap. By default you need two fingers to pan but unfortunately you always zoom in/out a bit when doing so because zoom and pan action both use two fingers down gesture. 

Is it possible to map the pan action on one finger down and having two fingers for zoom only by built in commands? Or do I have to implement my own Commands for handling that?

**Comment by holance** [comment]
The new version in develop branch fixed this issue. It changes pan to three fingers.

**Comment by KrabatTilt** [comment]
Nice to hear that.

As an intermediate solution I wanted to disable TouchInput completely. But it looks like setting TouchMode="None" does not work.

**Comment by holance** [comment]
There is IsTouchZoomEnabled, you can disable it.
I would suggest to starting using the 2.0 prerelease from myget.

**Comment by holance** [comment]
Fixed in 2.0
