### ISSUE TITLE
BackgroundColor Transparent not working in 2.1.0

### ISSUE THREAD

**Issue by KrabatTilt** [helix-toolkit/helix-toolkit#717]
I migrated a project from version 1.1.0 to 2.1.0-unstable0518. Everything worked fine except that I cannot set the Viewport3DX BackgroundColor to Transparent. It stays white. Is it intended to support Transparent background in the future?
I also checked it in the GroupElementTest Example Project, it does not work.

**Comment by holance** [comment]
Yes, it does not support transparent background for now.

**Comment by holance** [comment]
Ok, thanks for the tips. The issue is actually the Windows.Media.Colors.Transparent = #00FFFFFF. You simply use #00000000 for the BackgroundColor, it will work :)
