### ISSUE TITLE
Сoordinates for ModelVisual3D

### ISSUE THREAD

**Issue by reverse28** [helix-toolkit/helix-toolkit#720]
Good afternoon. It's possible to somehow set the coordinates for ModelVisual3D? I use HelixViewport3D and this [example ](https://www.codeproject.com/tips/882885/webcontrols/WebControls)  ,  but i have many obj-file with the same data but different coordinates. (to make it clearer, I need this to show the components on the PCB)
![image](https://user-images.githubusercontent.com/35262706/38873157-c796bdaa-425d-11e8-8d42-26100323cd07.png)

**Comment by holance** [comment]
Use HelixToolkit.Wpf.SharpDX with instancing matrices is the way you want to use.
