### ISSUE TITLE
Bindings in content of Viewport3DX do not react on DataContextChanged

### ISSUE THREAD

**Issue by KrabatTilt** [helix-toolkit/helix-toolkit#731]
I have a Vieport3DX control which is backed by ViewModel. As content the Viewport contains a DirectionalLight and a GroupModell3D. The GroupModell3D's ItemsSource is bound to an ObservableElement3DCollection (a property of my ViewModel) which contains my models.
The ViewModel is the SelectedItem of a ListView. Now, when I change the the selection I expect the models to be update to. But nothing happens.

``` xaml
<hx:GroupModel3D ItemsSource="{Binding Models}" />
```
The only workaround I found is to bind the GroupModel3D DataContext to the DataContext of the ViewPort as the Viewport recognizes the DataContext change.

``` xaml
<hx:GroupModel3D DataContext="{Binding ElementName=Viewport3Dx, Path=DataContext}" x:Name="ModelGroup" ItemsSource="{Binding Models}"/>
```

I don't know if it is a bug or expected behavior but I know that usually wpf controls pass DataContext changes to their content/childs without explicit binding.

What I haven't checked so far, is if this behavior is only shown by GroupModel3D or by any content inside the Viewport3DX.

**Full Viewport code with workaround:**
``` xaml
 <hx:Viewport3DX x:Name="Viewport3Dx" Grid.Row="0" Grid.Column="0" Grid.RowSpan="2" Grid.ColumnSpan="2"
                        ZoomExtentsWhenLoaded="True" UseDefaultGestures="False" ShowViewCube="False"
                        CameraRotationMode="Turntable" CameraMode="Inspect" IsRotationEnabled="False"
                        Camera="{Binding Camera}"
                        ZoomAroundMouseDownPoint="True"
                        EffectsManager="{Binding EffectsManager}"
                        RenderTechnique="{Binding RenderTechnique}"
                        BackgroundColor="{Binding BackgroundColor}" >
            <hx:Viewport3DX.InputBindings>
                <MouseBinding Gesture="MiddleClick" Command="hx:ViewportCommands.Zoom" />
                <MouseBinding Gesture="LeftClick" Command="hx:ViewportCommands.Pan" />
            </hx:Viewport3DX.InputBindings>
            <hx:DirectionalLight3D Color="{Binding LightColor}" Direction="{Binding LightDirection}" />
            <hx:GroupModel3D DataContext="{Binding ElementName=Viewport3Dx, Path=DataContext}" x:Name="ModelGroup" ItemsSource="{Binding Models}"/>
        </hx:Viewport3DX>
```

**Comment by holance** [comment]
Which version you are using?

**Comment by KrabatTilt** [comment]
sry, forgot that. Its 2.1.0-unstable0518 from MyGet
