### ISSUE TITLE
Get AspectRatio of Viewport3DX

### ISSUE THREAD

**Issue by KrabatTilt** [helix-toolkit/helix-toolkit#747]
I am using Viewport3DX (v. 2.1.0-unstable0642)  in an MVVM application. So I use DataBinding to access the Properties of the Viewport3DX. How can I get ActualWidth and -Height of the Viewport to calculate its AspectRatio. I cannot use ActualWidth and ActualHeight as these are not bindable to a ViewModel.
In know in version 1.1.0 one was able to bind to the RenderHost which also held ActualWidth and -Height properties. But this seems not to be possible any more in v. 2.1.0-unstable0642.

**Comment by holance** [comment]
https://stackoverflow.com/questions/1083224/pushing-read-only-gui-properties-back-into-viewmodel

**Comment by KrabatTilt** [comment]
I tried the first solution with _SizeObserver_ and also the second more general one using _data piping_. Both do not seem to work in my case as I switch the whole DataContext. I already mentioned my situation in issue #731. The DataContext of my Viewport is the SelectedItem of a Listview. When I switch Datacontext, the bindings are not updated and my Height and Width are 0.
I will do some further investigation on that and let you know the results.

**Comment by holance** [comment]
You can use a custom grid to wrap around the viewport, and in your custom grid, add custom dp to pass its actual width/height to your view model.

**Comment by KrabatTilt** [comment]
I tried different approaches, yours included and it did not work. During my investigation I found out that this problem often occurrs when having a custom dependency property located in a usercontrol. Havn found a soultion yet.
I bypassed this issue as I need the aspectratio only in the CameraChanged event to calculate the viewport dimensions from FieldofView. Therefore I added an EventCommandBinding which passes a reference to the Viewport in my Command delegate. This way I can directly grab the inf from the control.

**View**
``` xaml
<hx:Viewport3DX x:Name="Viewport3Dx" Grid.Row="0" Grid.Column="0" Grid.RowSpan="2" Grid.ColumnSpan="2"
                            ZoomExtentsWhenLoaded="True" UseDefaultGestures="False" ShowViewCube="False"
                            CameraRotationMode="Turntable" CameraMode="Inspect" IsRotationEnabled="False"
                            Camera="{Binding Camera}" TouchDown="Viewport3Dx_OnTouchDown"
                            ZoomAroundMouseDownPoint="False" MSAA="Disable" FXAALevel="Ultra"
                            EffectsManager="{Binding EffectsManager}"
                            RenderTechnique="{Binding RenderTechnique}"
                            BackgroundColor="{Binding BackgroundColor}" 
                            ZoomDistanceLimitNear="0.6">
                <hx:Viewport3DX.InputBindings>
                    <MouseBinding Gesture="MiddleClick" Command="hx:ViewportCommands.Zoom" />
                    <MouseBinding Gesture="LeftClick" Command="hx:ViewportCommands.Pan" />
                </hx:Viewport3DX.InputBindings>
                <i:Interaction.Triggers>
                    <i:EventTrigger EventName="CameraChanged">
                        <utils:TriggerActionCommand Command="{Binding PerspectiveChanged}" />
                    </i:EventTrigger>
                </i:Interaction.Triggers>
                <hx:DirectionalLight3D Color="{Binding LightColor}" Direction="{Binding LightDirection}" />
                <hx:GroupModel3D x:Name="ModelGroup" ItemsSource="{Binding Models}" />
            </hx:Viewport3DX>
```
 
ViewModel

``` c#
 public ICommand PerspectiveChanged => _perspectiveChangedCommand ?? (_perspectiveChangedCommand = new DelegateCommand<RoutedEventArgs, object>(ExecuteCameraChanged));

        private void ExecuteCameraChanged(RoutedEventArgs sender)
        {
            if (Camera == null)
                return;

            var vp = (Viewport3DX)sender.Source;
            double aspectRatio = vp.ActualWidth / vp.ActualHeight;

            //Calculate View projection
            double h = Camera.Position.Z * 2;
            double w = h * aspectRatio;
            double x = Camera.Position.X - w / 2.0d;
            double y = Camera.Position.Y - h / 2.0d;
            var r = new Rect(x, y, w, h);

            Console.WriteLine($"VIEW: {r}");
        }
```

**Comment by holance** [comment]
Good to know. Just keep in mind that camera changed event fires anytime the camera property is changed, such as rotation/zooming. Avoid putting heavy codes in this event, otherwise may cause performance issue.
