### ISSUE TITLE
Errors building project.

### ISSUE THREAD

**Issue by Dmitrii2018** [helix-toolkit/helix-toolkit#754]
I have Windows 7 on lapton and latest version helix toolkit.
Can I use Windows 7 for this project or I need only Windows 10?
Getting this error while building:

![image](https://user-images.githubusercontent.com/38795704/39726182-ebb3d912-5256-11e8-96d3-7ab91b2d4b9d.png)

and while starting:

![image](https://user-images.githubusercontent.com/38795704/39725421-6b93ebc0-5254-11e8-98d5-2a87facd710d.png)

**Comment by holance** [comment]
What's the error when you build only HelixToolkit.Wpf.SharpDX project?

**Comment by Dmitrii2018** [comment]
There is error list (first snapshort). It is HelixToolkit.Wpf.SharpDX project.
I tried to build my own simple project and it normally.

**Comment by Dmitrii2018** [comment]
When I try build  HelixToolkit.SharpDX.ShaderBuilder project I have error:
![image](https://user-images.githubusercontent.com/38795704/39752292-a03673ec-52c3-11e8-9aed-5c2b1b4853a6.png)

**Comment by holance** [comment]
You need to install the windows sdk

**Comment by holance** [comment]
Missing fxc.exe issue with newest Windows 10 SDK:

Copy fxc.exe in C:\Program Files (x86)\Windows Kits\10\Bin\10.0.xxx\x86 to C:\Program Files (x86)\Windows Kits\10\bin\x86 to fix this issue. Because the HLSL compile tool hard coded the path.

**Comment by Dmitrii2018** [comment]
I have done it already.

**Comment by Dmitrii2018** [comment]
This problem has really arisen before.

**Comment by holance** [comment]
Please try again using latest source. I change the shader building project to use native project, should solve the fxc missing issue. If still not working, reopen this issue.

**Comment by Dmitrii2018** [comment]
Thank you.
I'll try.

**Comment by Dmitrii2018** [comment]
Still can't build the project HelixToolkit.Wpf.SharpDX.
(Project "HelixToolkit.Wpf" works OK.)
First step it can't find dll files - HelixToolkit.Wpf.SharpDX.dll and DemoCore.dll.
I copied it manualy.
Now there is this error list:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0115	'CustomMeshCore.OnDefaultPassChanged(ShaderPass)': no suitable method found to override	CustomShaderDemo	C:\helix-toolkit-develop\Source\Examples\WPF.SharpDX\CustomShaderDemo\CustomMeshCore.cs	56	Active
Error	CS0115	'CustomMeshCore.OnUpdatePerModelStruct(ref ModelStruct, RenderContext)': no suitable method found to override	CustomShaderDemo	C:\helix-toolkit-develop\Source\Examples\WPF.SharpDX\CustomShaderDemo\CustomMeshCore.cs	82	Active
Error	CS0115	'CustomMeshCore.CanRender(RenderContext)': no suitable method found to override	CustomShaderDemo	C:\helix-toolkit-develop\Source\Examples\WPF.SharpDX\CustomShaderDemo\CustomMeshCore.cs	103	Active
Error	CS0115	'CustomMeshCore.OnRender(RenderContext, DeviceContextProxy)': no suitable method found to override	CustomShaderDemo	C:\helix-toolkit-develop\Source\Examples\WPF.SharpDX\CustomShaderDemo\CustomMeshCore.cs	108	Active
Error	CS0115	'MyLineGeometryModel3D.HitTest(RenderContext, Ray, ref List<HitTestResult>)': no suitable method found to override	ExampleBrowser	C:\helix-toolkit-develop\Source\Examples\WPF.SharpDX\ExampleBrowser\Workitems\Workitem10048\MyLineGeometryModel3D.cs	23	Active
Error	CS8121	An expression of type 'Material' cannot be handled by a pattern of type 'PhongMaterialCore'.	FileLoadDemo	C:\helix-toolkit-develop\Source\Examples\WPF.SharpDX\FileLoadDemo\MainViewModel.cs	130	Active
Error	CS0029	Cannot implicitly convert type 'HelixToolkit.Wpf.SharpDX.Model.PhongMaterialCore' to 'HelixToolkit.Wpf.SharpDX.Material'	FileLoadDemo	C:\helix-toolkit-develop\Source\Examples\WPF.SharpDX\FileLoadDemo\MainViewModel.cs	132	Active
Error	CS0006	Metadata file 'C:\helix-toolkit-develop\Source\Examples\WPF.SharpDX\BoneSkinDemo\bin\Debug\BoneSkinDemo.exe' could not be found	MemoryLeakTester	C:\helix-toolkit-develop\Source\Examples\WPF.SharpDX\MemoryLeakTester\CSC	1	Active
Error	CS0006	Metadata file 'C:\helix-toolkit-develop\Source\Examples\WPF.SharpDX\CustomShaderDemo\bin\Debug\CustomShaderDemo.exe' could not be found	MemoryLeakTester	C:\helix-toolkit-develop\Source\Examples\WPF.SharpDX\MemoryLeakTester\CSC	1	Active
Error	CS0006	Metadata file 'C:\helix-toolkit-develop\Source\Examples\WPF.SharpDX\SimpleDemo\bin\Debug\SimpleDemo.exe' could not be found	MemoryLeakTester	C:\helix-toolkit-develop\Source\Examples\WPF.SharpDX\MemoryLeakTester\CSC	1	Active
Error	CS0246	The type or namespace name 'OITWeightMode' could not be found (are you missing a using directive or an assembly reference?)	OrderIndependantTransparentRendering	C:\helix-toolkit-develop\Source\Examples\WPF.SharpDX\OrderIndependantTransparentRendering\MainViewModel.cs	50	Active
Error	CS8121	An expression of type 'Material' cannot be handled by a pattern of type 'PhongMaterialCore'.	SwapChainRenderingDemo	C:\helix-toolkit-develop\Source\Examples\WPF.SharpDX\SwapChainRenderingDemo\MainViewModel.cs	231	Active
Error	CS0029	Cannot implicitly convert type 'HelixToolkit.Wpf.SharpDX.Model.PhongMaterialCore' to 'HelixToolkit.Wpf.SharpDX.Material'	SwapChainRenderingDemo	C:\helix-toolkit-develop\Source\Examples\WPF.SharpDX\SwapChainRenderingDemo\MainViewModel.cs	233	Active
Error		Invalid Resx file. Could not find file 'C:\helix-toolkit-develop\Source\HelixToolkit.Wpf.SharpDX\resources\psmeshblinnphong.cso'. Line 132, position 5.	HelixToolkit.Wpf.SharpDX	C:\helix-toolkit-develop\Source\HelixToolkit.Wpf.SharpDX\Properties\Resources.resx	132	
Error		The property 'EnableDesignModeRendering' does not exist in XML namespace 'http://helix-toolkit.org/wpf/SharpDX'. Line 27 Position 34.	BoneSkinDemo	C:\helix-toolkit-develop\Source\Examples\WPF.SharpDX\BoneSkinDemo\MainWindow.xaml	27	
Error		The property 'EnableDesignModeRendering' does not exist in XML namespace 'http://helix-toolkit.org/wpf/SharpDX'. Line 53 Position 31.	SimpleDemo	C:\helix-toolkit-develop\Source\Examples\WPF.SharpDX\SimpleDemo\MainWindow.xaml	53	
Warning	CS0168	The variable 'ex' is declared but never used	ImageViewDemo	C:\helix-toolkit-develop\Source\Examples\WPF.SharpDX\ImageViewDemo\MainViewModel.cs	240	Active
Error	MSB8036	The Windows SDK version 10.0.10586.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".	HelixToolkit.Native.ShaderBuilder	C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\Common7\IDE\VC\VCTargets\Platforms\x64\PlatformToolsets\v141\Toolset.targets	36	


It would be great to have system requirements.
Are you sure it will be work on windows 7?


![image](https://user-images.githubusercontent.com/38795704/39863489-6eb5d46a-544f-11e8-946d-99f03258cbff.png)

![image](https://user-images.githubusercontent.com/38795704/39863598-c94f113e-544f-11e8-9d55-4aff9e271d38.png)

**Comment by holance** [comment]
10.0.10586.0 SDK can be install from your visual studio installer. Modify the visual studio 2017 and select the SDK. Or you can retarget to 10.0.17134 you already installed. 

Please let me know if you still cannot build the shader builder project.

**Comment by Dmitrii2018** [comment]
Thank you fo the ansver.
I realize it.
I have opportunity to test project on  my configuration - wind 7.
I'll be glad to solve this issue together.
Waiting for your recommendations.
I'll try to implement your recommendations about SDK and let you know.

**Comment by Dmitrii2018** [comment]
10.0.10586.0 SDK - helped.
The project built normally.
But next problem appeared when starting.
I think it's because of my video card.

![image](https://user-images.githubusercontent.com/38795704/39919991-23f03f5e-551e-11e8-8da2-5972090c006d.png)

**Comment by Dmitrii2018** [comment]
DirectX 11.0

**Comment by Dmitrii2018** [comment]
![image](https://user-images.githubusercontent.com/38795704/39921663-7c6f18e8-5524-11e8-8c26-3257edff5abd.png)

**Comment by holance** [comment]
I put a fix to disable not supported shaders on feature level 10 device. Please try again.

**Comment by Dmitrii2018** [comment]
Last error disappeared but appeared new:
![image](https://user-images.githubusercontent.com/38795704/39936468-3f80bb40-5555-11e8-8c11-39b043437224.png)

If I start EXE file:
![default](https://user-images.githubusercontent.com/38795704/39936501-552f0082-5555-11e8-987e-c80ae415e614.PNG)

**Comment by JeremyAnsel** [comment]
Does it work if you replace `FeatureLevel.Level_10_0` with `FeatureLevel.Level_11_0`?

**Comment by holance** [comment]
Or try Level_10_1.

**Comment by Dmitrii2018** [comment]
You mean I need to fix the code?

**Comment by holance** [comment]
What's the graphic card on your computer?

**Comment by Dmitrii2018** [comment]
laptop - samsung R540.

![image](https://user-images.githubusercontent.com/38795704/39954298-d775ccae-55c5-11e8-8b33-59612d50ee7b.png)

Usually this model has video card:
ATI Mobility Radeon HD 545v.
It support DirectX 10.1.
But I'm not sure in my case.

**Comment by holance** [comment]
I put a fix for the blend state. Please try again. Since your graphic card is old integrated card, the performance may not be good.

**Comment by Dmitrii2018** [comment]
Thank you very much.
The project is working. I know, my computer is not new.
