### ISSUE TITLE
Notification on camera manipulation

### ISSUE THREAD

**Issue by loggie0** [helix-toolkit/helix-toolkit#757]
Hi guys,
I have a scene with a couple of thousands of LineGeometryModel3D instances (I need all of them to be hit testable). This causes some mouse responsiveness issues, poor frame rate while rotating or panning the view (at least on integrated graphic cards). To improve performance I'm thinking about replacing all those line objects with a single one only for the duration of zooming/rotating/panning and after that, rendering all lines normally. That way I would have them hit testable and still get smooth animation.

Are there any events that notify the mouse manipulation is about to start/complete?

**Comment by holance** [comment]
If you are using SharpDX version, the hit test result is a LineHitTestResult, it contains the line index in your model. You can just use single line instance instead of thousands of line models.
