### ISSUE TITLE
Inertia does not work correctly when camera has lefthand coordinate system

### ISSUE THREAD

**Issue by KrabatTilt** [helix-toolkit/helix-toolkit#760]
When I set my camera to use a lefthand corrdinate system (CreateLeftHandSystem = true) and inertia for pan is enabled on gets a strange bouncing effect. I move to the right and the camera shortly also moves to the right but then bounces back to the left. It behaves like a light beam reflected at a mirror. When I set CreateLeftHandSystem = false  everything works as expected.
I think that the InertiaAnimation always assumes a right hand coordinate system.

I am using Viewport3DX, v2.1.0

**Comment by holance** [comment]
We never fully test the left hand system. Prefer to use the right hand rule. I will take a look this issue.
