### ISSUE TITLE
Use manipulator through transparent model

### ISSUE THREAD

**Issue by gregorsGit** [helix-toolkit/helix-toolkit#761]
Hi,
I try to use the UITranslateManipulator3D behind a transparent model. (SharpDX)
The only way to get it work, is to set "IsHitTestVisisble=false" for the model in front.
In some cases I can´t do that. I need this model for other actions/commands. 

Is there an easy way to get all! models below a mouse position?
So I can change HitTest dynamicaly, when I find a UIManipulator below.

Or is there something else I can do in my case.

**Comment by holance** [comment]
You need to do manual hit test. Or create your own ui manipulator. Just refer to the ui manipulator source code, it should be easy

**Comment by holance** [comment]
I wrote a solution for your question. Please take a look at [Implement-always-hit-manipulator](https://github.com/helix-toolkit/helix-toolkit/wiki/Implement-always-hit-manipulator)

**Comment by gregorsGit** [comment]
I try your "AlwaysHitManipulator.".
This is a suiteable soultion for me. It works.
Thanks for the example.

**Comment by benazet** [comment]
I'm trying to do the same with the wpf version of the toolkit( ie not SharpDX). I have small objects i need to move inside bigger transparent objects, but as soon as a transparent object is in front of my manipulator i am blocked.

It seems to be handled very differently in WPF : there is no individual IsHitTestVisible property, and no GroupNode.

To my knowledge, i see two ways to do this in wpf : 
- change the way the MouseDown event is raised, but i can't find where it is implemented, i guess it's in viewport3D
- override the distance calculation of the hit for my manipulators, but i have not found how to do that yet
