### ISSUE TITLE
Meshbuilder.ToMesh has -Infinity .Bounds?

### ISSUE THREAD

**Issue by LDClark** [helix-toolkit/helix-toolkit#762]
I created an empty meshBuilder, and did .AddCylinder to it.  When I create a MeshGeometry3D and look at the .Bounds, it has -Infinity for SizeX, SizeY, and SizeZ.  Any ideas on why it is not a real number?

**Comment by holance** [comment]
You need to call update bound. If you don't call, the engine will call during rendering.

**Comment by LDClark** [comment]
What is the name of the function?  I can't find it.  Thanks
