### ISSUE TITLE
Windows 10 SDK Version

### ISSUE THREAD

**Issue by Diemongo** [helix-toolkit/helix-toolkit#763]
The C++ Project HelixToolkit.Native.ShaderBuilder is pointing at SDK version 10.0.10586.0, and prevented the Helix-solutions from building. I do not have this specific version installed, but a newer version 10.0.17134.0.  In order to get the solutions compiled, I had to select this version manually on the General propertypage in the C++ project. 
Can I persuade you to write a short comment on this in the Project Build description?

**Comment by holance** [comment]
I updated the description on readme.md, it should be clear.
