### ISSUE TITLE
Viewport not updating when rotating

### ISSUE THREAD

**Issue by Isdas** [helix-toolkit/helix-toolkit#767]
Hi

In the latest version of the SharpDX-version I can't get my overrides for mouse move to work. My overrides regarding on mouse down works as before, but it seems like somewere in the code the event for mouse move gets handled and not bubbled up from the user control with the viewport. Is this intentional? Is there any way of subscribing to the mouse move event that doens't supress it?

Best regards
Isdas

**Comment by Isdas** [comment]
I can't seem to get this to work either. PreviewMouseMove also gets handled.

**Comment by holance** [comment]
I am not able to reproduce your problem and I don't see any code in viewport3dx mark the mouse move event to handled. Could you provide an example it does not work?

**Comment by Isdas** [comment]
Got previewmousemove working.

Thanks.

**Comment by holance** [comment]
After you add rotation force, you can do view1.InvalidateRender to trigger the rendering.
The FPS is designed that way. Because viewport only renders if something changed to trigger the re-render(Lazy render). Unless we are having an animation and keeps the viewport rendering, the FPS will show correctly. It is not like game engine which keeps rendering all the time.

**Comment by holance** [comment]
For fixed rotation point, you need to set FixedRotationPointEnabled = true to use it.

**Comment by Isdas** [comment]
No, this doesn't work as expected. I have of course tried to set FixedRotationPoint = true.

I can see that the AddRotateForce in the CameraController uses this.CameraTarget, but can't see that the camera target gets changed when setting the FixedRotationPoint.

I would expect something like this:
![image](https://user-images.githubusercontent.com/5860580/40920817-f40cdeb6-680d-11e8-84c4-94a29e7d211b.png)

**Comment by holance** [comment]
Camera target will not change when using fixed rotation point. These two are decoupled while using fixed rotation point. if you want camera to follow the rotation point, you have to manually set camera look direction from your viewmodel.
