### ISSUE TITLE
How to Import .obj with the associated .mtl ?

### ISSUE THREAD

**Issue by lenien131** [helix-toolkit/helix-toolkit#771]
It´s very urgent.

I can actually load the obj  , but it´s always grey , the textures are missing but I can´t find help anywhere how to load and even apply the textures .

I couldnt find anything in the internet .

Anybody can help in this case ?

**Comment by holance** [comment]
mtl should be loaded automatically.

**Comment by holance** [comment]
Could you provide a sample of your model with mtl?

**Comment by lenien131** [comment]
No solution ?

Does my xmlns code have to contain specific codes like  <GeometryModel3D.Material> to show the mtl ?
Or should it be loaded as soon as I can see obj model in the form ?

**Comment by holance** [comment]
I am not able to render the material even using other tools(blender, etc) to open your model. Are you sure your model data is correct?

**Comment by lenien131** [comment]
When I test it with this tool : http://www.open3mod.com/
It actually works when I use the open3mod programm for my objs.

**Comment by lenien131** [comment]
Gosh I really dont get it how such a tiny obj with mtl can be so difficult to handle..for me.

**Comment by holance** [comment]
Ok, I found the issue. Your model basically has two identical meshes overlapped at each other. One with texture, one does not, and the later one rendered after the one with material and completely covered the one you are looking for.

**Comment by lenien131** [comment]
Oh that makes sense.

How can I now select the one with the textures

**Comment by holance** [comment]
[modelfixed.zip](https://github.com/helix-toolkit/helix-toolkit/files/2051843/modelfixed.zip)
This is the fixed one I export and modified using open3mod.

Basically the one without texture overwrites the one with texture.

**Comment by lenien131** [comment]
Worked now.

But that is given, I have to deal with it somehow like that
I have like 200 files like that which I have to open with just a button click.

Do you know any other simple solution for this "in the coding level" , the tool , open3dmod somehow also showed me the obj with textures.

**Comment by holance** [comment]
You need to have a list to show the models loaded and select which one to show/hide.

**Comment by lenien131** [comment]
I have no clue how to realize that atm.When I select the .obj ,its loaded and when its loaded there are 2 of the same models ,the one with textures and the other is just grey.
