### ISSUE TITLE
Viewport3DX Title and Subtitle are not rendered correctly

### ISSUE THREAD

**Issue by li0nsar3c00l** [helix-toolkit/helix-toolkit#773]
After updating the Subtitle property, the font is vertical.
After resizing the window a bit, everything behaves as it should.

https://i.imgur.com/FMYnZiA.jpg
https://i.imgur.com/3lVNTvf.jpg

**Comment by holance** [comment]
For temporary fix, use wpf textblock to show the title. I will fix later.

**Comment by li0nsar3c00l** [comment]
No worries. But I got some more information for reproducing:
The issue only occurs, when the the property is empty at initialization (nothing is assigned within constructor) and the text is changed dynamically after viewport is rendered. This is obviously also valid for the Title property, since the implementation is the same.

**Comment by li0nsar3c00l** [comment]
Workaround:
Actually initializing the properties inside the constructor of your ViewModel
`Title = string.Empty;
Subtitle = string.Empty;`
or the backing field for the property
`private string _title = string.Empty;`
 solves the issue.
