### ISSUE TITLE
Billboard questions (transparency + adding billboards after initialize)

### ISSUE THREAD

**Issue by Isdas** [helix-toolkit/helix-toolkit#774]
Hi

A small question: When I set the transparency of a billboard to Color.Transparent the billboard gets transparent (great). One small problem I have right now: other billboards that are behind this billboard gets cut. Is there any way of solving this problem? Is it possible to also add a "IsTransparent" property on the billboards?

Picture:
![58b325724f81c573db89b9983dd680bc](https://user-images.githubusercontent.com/5860580/40712034-f08433bc-63fc-11e8-9ee8-d38d5b8b75c4.png)

Also:
TextInfo of the BillboardText3D is an ObservableCollection. If I try to add text in my model after the viewport is initialized (for instance when pressing a button in my application) the text is not displayed. Is there any way of updating the viewport to show this text? (Start the rendering of the billboard).

Best regards
Isdas

**Comment by holance** [comment]
There is a bug which did not subscrible the collection change event by default. The workaround is to assign a new ObservableCollection to BillboardText3D.TextInfo. Then the collection change event will fire if you add new textinfo into the collection.

To solve the transparency issue, there is a IsTransparent property in BillboardTextModel3D, you can try to set it to true. It works fine if all your text color is the same.

**Comment by Isdas** [comment]
Thank you very much for the response. I guessed the Text.Info was a bug, but wasn't able to find a workaround (but your workaround works perfectly).

I can see that the pixel shader for the billboard now discards the pixel if alpha = 0. Will this work for all the different billboards?

Also, a small question: when will you put out a new version on NuGet?

**Comment by holance** [comment]
You can use unstable version from [myget](https://www.myget.org/F/helix-toolkit) or create your own custom shader.
