### ISSUE TITLE
ZoomDistanceLimitNear/-Far does not work correctly

### ISSUE THREAD

**Issue by KrabatTilt** [helix-toolkit/helix-toolkit#777]
Viewport3DX, version 2.1.0

I played a bit around with ZoomDistanceLimitNear and -Far and made following observations:

**IsInertiaEnabled="False"
ZoomDistanceLimitNear = "20"
ZoomDistanceLimitNear = "10000"**

Camera stops zoom in at z = 21.22
Camera stops zoom out z = 8977.1

Limits cannot be reached.

**IsInertiaEnabled="_True_"
ZoomDistanceLimitNear = "20"
ZoomDistanceLimitNear = "10000"**

Camera stops zoom in at z = 20.01
Camera stops zoom out z = 9998.76

Camera stops near limits. But when I then pan around I somehow can go beyond these limits. I found out that this has to do with the inertia animation. When camera is at the e.g. 20 near limit and you try to zoom in further it does not work. But it looks like the inertia animation is running in the background. If you then pan while animation is running I can go step by step below the near limit.

**Comment by holance** [comment]
I fixed the first issue about not reaching limit with inertia off. 
The second issue is due to the panhandler did not check the limits, it is a little bit hard to fix and I will take a look later.

**Comment by holance** [comment]
Should be fixed. Please reopen this issue if the issue still happening.
