### ISSUE TITLE
How to change default position of UICompositeManipulator3D in SharpDx

### ISSUE THREAD

**Issue by SurduseSunil** [helix-toolkit/helix-toolkit#790]
I am trying to use UICompositeManipulator3D in WPF SharpDx. It always gets created at the center of the ViewPort3DX.

I need to draw a 3D box and UICompositeManipulator3D togather and bind manipulator to the box.

In helix there was property called Position was available to set the location of the manipulator.

How I can do the same in SharpDx??

**Comment by holance** [comment]
You need to use the Transform property. You can take a look the [ManipulatorDemo](https://github.com/helix-toolkit/helix-toolkit/tree/develop/Source/Examples/WPF.SharpDX/ManipulatorDemo)
