### ISSUE TITLE
how to display obj previews and front and up view

### ISSUE THREAD

**Issue by lenien131** [helix-toolkit/helix-toolkit#794]
Hi,

can someone help me ... its very urgent.

I am so far , that my program can load objs dynamically . When I open the obj I want to see the 3d model in the up view (have a combobox with up and front view) so when I open it ,it should show me the model in the up view and when i select combobox front , it changes the view.

thanks in advande for any kind of help

**Comment by holance** [comment]
Change your camera position and look direction after loading the model

**Comment by lenien131** [comment]
Yes but how can I access them ,is there any example code for that ?
If I set the view to show me the objs front view first when I load , will it show me the correct up view of any object i open dyncamically ?

I am not very good at coding ,sorry for the somwhow stupid questions.

**Comment by lenien131** [comment]
The code I use atm for the model to rotate via button click.

`var axis = new Vector3D(0, 0, 1);
            var angle = 10;

            var matrix = objmodel.Transform.Value;
            matrix.Rotate(new Quaternion(axis, angle));

            objmodel.Transform = new MatrixTransform3D(matrix);`

I need a similar solution , in case I select up view from my combobox , it sets the model to up view

**Comment by holance** [comment]
You need to create a camera in your view model. And manipulate the camera.

**Comment by lenien131** [comment]
Do you have a sample code how I can get the Up-View of an Model when I press on Button "Up View"

**Comment by xxxGURUxxx** [comment]
`        {
            RendererViewport.HelixViewport.CameraController.CameraLookDirection = new Vector3D(0, -19098.660, 0);

            // set CameraUpDirection property is optional to have better view !! :)
            RendererViewport.HelixViewport.CameraController.CameraUpDirection = new Vector3D(1, 0, 0);

            // or your Target Object 3D Coordinate
            RendererViewport.HelixViewport.CameraController.CameraPosition = new Point3D(1505.891, 21683.950, 6224.737);

            // or your Target Object 3D Coordinate
            RendererViewport.HelixViewport.CameraController.CameraTarget = new Point3D(1505.891, 2585.290, 6224.737);
        }`
