### ISSUE TITLE
SharpDX: Camera movement using keyboard doesn't work when mouse is not moving.

### ISSUE THREAD

**Issue by RandomityGuy** [helix-toolkit/helix-toolkit#796]
I'm having this issue on my project where I can't move the camera when the mouse is not moving.

I need to be able to move the camera to different places most of the time. It's very irritating that I have to move the mouse for the WASD keys I pressed to take action.

Here's something that mostly happens:
I press any of the arrow keys. Didn't move the mouse yet. The camera doesn't move.
Then I press more arrow keys. Still the camera doesn't move.
Now I move the mouse slightly and now the effects of all the keypresses take place and the camera moves suddenly

**Comment by holance** [comment]
This bug has been fixed in develop branch.
