### ISSUE TITLE
Customizable coordinate system/visual cube

### ISSUE THREAD

**Issue by riegaz** [helix-toolkit/helix-toolkit#812]
This is a feature request if it is not possible yet. I would like to change the coordinate system and/or the cube view with a random MeshModel3D.

Is this possible yet? Is this a possible feature?

![image](https://user-images.githubusercontent.com/1749401/41524925-785fc530-72df-11e8-8b88-e4c65836dc3e.png)

**Comment by holance** [comment]
If you are using WPF version. The two views are just two WPF Viewports. You can simply create two viewport yourself, add any model you want and sync the camera rotation. You can refer to the source code, should be very simple to implement.

**Comment by riegaz** [comment]
I'm using the SharpDX version. I have to check for the source.

**Comment by holance** [comment]
[CustomCooridnateSystemDemo.zip](https://github.com/helix-toolkit/helix-toolkit/files/2113367/CustomCooridnateSystemDemo.zip)
I created a simple demo for current version. You need to create a ScreenSpacedGroup3D(will be included in future release) and manually add mesh models into the group. Make sure to set the rendertype to ScreenSpaced. Refer to the demo for details.

**Comment by riegaz** [comment]
Awesome, thanks!

**Comment by riegaz** [comment]
@holance your example works by using the meshbuilder. If I load a STL file and add the Material as you did, both models result in the same (latest added) Material.

`var stlR = new StLReader();

            MemoryStream theMemStream = new MemoryStream(POEMSAnalayzer2.Properties.Resources.model1);
            var ob = stlR.Read(theMemStream);

            var model = new MeshGeometryModel3D() { Geometry = ob.FirstOrDefault().Geometry, Material = DiffuseMaterials.Orange };
            model.SceneNode.RenderType = RenderType.ScreenSpaced;//Make sure to set this in current version.
            coordinateModels.Add(model);


            var theMemStream1 = new MemoryStream(POEMSAnalayzer2.Properties.Resources.model2);
            var ob1 = stlR.Read(theMemStream1);

            var model1 = new MeshGeometryModel3D() { Geometry = ob1.FirstOrDefault().Geometry, Material = DiffuseMaterials.Blue };
            model1.SceneNode.RenderType = RenderType.ScreenSpaced;//Make sure to set this in current version.
            coordinateModels.Add(model1);`

**Comment by riegaz** [comment]
Also, transparency seems to be ignored for these meshes. I added The alpha value and turned trancparency on in the material properties.

**Comment by holance** [comment]
Transparency is order dependent. You need to organize your model order to render non-transparent first, then transparent.
For first issue you mentioned, I am not able to reproduce. Could you provide an example code?

**Comment by riegaz** [comment]
Both, color and transparency combined in this example.


[CustomCooridnateSystemDemo1.zip](https://github.com/helix-toolkit/helix-toolkit/files/2121112/CustomCooridnateSystemDemo1.zip)

**Comment by holance** [comment]
You need to create a new StlReader for second model. If you are using the same StlReader, two models are combined.

**Comment by riegaz** [comment]
Sorry, I did not know that.

Last question, is there a possiblitity to add BillboardsSingleText3D Elements to this ScreenSpacedGroup3D somehow? I tried to create an Observable<BillboardsSingleText3D> but the ScreenSpacedGroup3D  does not offer a DataTemplate option in XAML.

**Comment by holance** [comment]
You can add billboardsingletext3d the same as mesh geometry 3d. DataTemplate is not supported for this one, you may need to add different model type into the ObservableElement3DCollection.

**Comment by riegaz** [comment]
I see, but the billboardsingletext3d does not have a `SceneNode.RenderType`. So I can not set it to `ScreenSpaced`.

**Comment by riegaz** [comment]
Works, creating a `BillboardTextModel3D `from the `BillboardSingleText3D` does it.
