### ISSUE TITLE
3ds import error

### ISSUE THREAD

**Issue by tree1891** [helix-toolkit/helix-toolkit#816]
When import it, exception occurs.

[cube.zip](https://github.com/helix-toolkit/helix-toolkit/files/2133222/cube.zip)

**Comment by JeremyAnsel** [comment]
Hello,
The file seems to be broken.
I've tried to import it using Assimp and it also generates an exception.
Are you sure the model is valid?

**Comment by tree1891** [comment]
Maybe it seems invalid, but it is ok in Hira3DViewer.

**Comment by JeremyAnsel** [comment]
I've tried with Meshellator and the file is fine.

**Comment by JeremyAnsel** [comment]
I think I've fixed the 3ds reader.

![helixtoolkit_3ds_cube](https://user-images.githubusercontent.com/9573196/42128767-5b0b4828-7cb3-11e8-8540-b9eca8b2a1bc.png)

The cube looks fine.
