### ISSUE TITLE
Color change on triangles with a TextureCoordinate gradient on zoom

### ISSUE THREAD

**Issue by riegaz** [helix-toolkit/helix-toolkit#817]
Could someone tell me what is happening? On zooming out, triangles that do show a gradient in the TextureCoordinates start to become faint.

Here you can see what is happening.
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/1749401/41983866-80e93298-7a2f-11e8-8b24-4c65d07331d2.gif)

The DiffuseMap applied to the TextureCoordinates looks as follows:
TextureCoordinates
![image](https://user-images.githubusercontent.com/1749401/41982804-a1d0fe4e-7a2c-11e8-84fb-7c3d320da83e.png)

I apply the TextureCoordinates after setting the DiffuseMap like this:
`model.material = new PhongMaterial() { DiffuseMap = map, SpecularShininess = specShine };`
Afterwards I run through the vertices and assign them.

The faint spots occur exactly where there is a big gradient between the vertices of a single triangle.
![untitled-1](https://user-images.githubusercontent.com/1749401/41983537-b12a867e-7a2e-11e8-9b3b-21cf5911d1cc.png)

**Comment by holance** [comment]
Could you share the model with the texture coordinates?

**Comment by riegaz** [comment]
I try to create a sample project.

Actually, I like the faint of the borders 👍 If someone could tell me how to create such an isochronal map I would highly appreciate it. But this just as a side command.

**Comment by riegaz** [comment]
An ugly sample:

[GradientProblem.zip](https://github.com/helix-toolkit/helix-toolkit/files/2144712/GradientProblem.zip)

**Comment by holance** [comment]
Your color stripe image has a black portion on the left. If you remove the black portion, the color issue goes away.

**Comment by riegaz** [comment]
I know it has the black portion because I added it. I didn't find a big tutorial about TextureCoordinates but why does the black portion influence the gradient? I'm far far away with my coordinates from the black portion.

**Comment by holance** [comment]
I saw your texture coordinates having some value too close to 0.5 on Y, and the texture sampling creates artifacts between the black and the color stripe with mipmaps.

**Comment by riegaz** [comment]
`collection[i] = (new Vector2(0.005f,val));` where val moves from 0.005 to 0.995. So Y changes while X stays constant. So from my understanding I'm far away from the black portion.

`collection[i] = (new Vector2(0.005f,0.0055f));` gives violet.
`collection[i] = (new Vector2(0.005f,0.995f));` gives yellow.

If now you tell me that the image's coordinate system is tilted, I would change my code to `collection[i] = (new Vector2(val,0.005f));` but doing this gives me mostly black triangles cause I'm hoping around in the black portion.

Where am I wrong?

Another question: why `collection[i] = (new Vector2(0.005f,0.005f));` gives me a violet color, while `collection[i] = (new Vector2(0,0));` give a brown one?

**Comment by holance** [comment]
You needs to change the sampler AddressU/V/W to Clamp to prevent sampler sampling the black area. Default is wrap, which means if your X is close to 0 and it samples using bilinear, it will sample the black area.

**Comment by riegaz** [comment]
`PhongMaterial.DiffuseMapSampler = DefaultSampler.PointSamplerWrap` the DefaultSampler is not available.I tried `var material = new PhongMaterial() { DiffuseMap = textStream, DiffuseMapSampler = DefaultSampler.PointSamplerWrap };`

What I want to achieve with the black portion is that I can set some triangles to black with the same image/DiffuseMap. Do you have a better approach?

**Comment by holance** [comment]
You can add the black portion at the bottom of the your color stripe and adjust your texture coordinates.

Or change sampler address UV mode to border, and set the border color in sampler description. Once you set any coordinates outside the range 0-1, it will uses border color automatically.

**Comment by riegaz** [comment]
Works really well! Thanks!

**Comment by riegaz** [comment]
I just wanted to apply your second suggestion, setting the border to black and go beyond 1 for black triangles. However, setting texturecoordinates to XX,1 results in this yellow black dotted region.

Reducing every value bigger than 0.95 solves the problem but distorts my colors accordingly.

Any suggestions? I tried to play with the SamplerSettings but I didn't get a satisfying solution so far.

![image](https://user-images.githubusercontent.com/1749401/43723518-242cddd8-9998-11e8-9b22-2bd762cabe60.png)

**Comment by holance** [comment]
If you want to sample the color strip vertically, choose for example Y coordinate, then set X to 0.5. Avoid sample at the border.

**Comment by riegaz** [comment]
I see your point and I know sampling close to the border is causing the issue. I thought the border solution would be simple without any recalculation required. But it seems to still be a problem. I would be fine changing values smaller 0.01 to 0.01 and bigger than 0.99 to 0.99. However, doing this still shows  errors close to the 0,1 border.

**Comment by holance** [comment]
Could you send a sample with the data having the artifacts?

**Comment by riegaz** [comment]
I tried now to reproduce it within a sample. Took me some time now but the black artifact from values close to 0 or 1 results from `MSAA = "two"`. Could you tell me why?

[TextureCoordinatesArt.zip](https://github.com/helix-toolkit/helix-toolkit/files/2265468/TextureCoordinatesArt.zip)

**Comment by riegaz** [comment]
I see. Playing with FXAA while MSAA is enabled doesn't change anything. Setting FXAA without MSAA enabled looks super bad.

I hoped for a solution without the recalculation of my texture, however it is fine for me if there is no better solution around. Thanks for your help.

**Comment by holance** [comment]
FXAA only works without MSAA. Padding is the only solution.

**Comment by riegaz** [comment]
Thanks!
