### ISSUE TITLE
stl import error

### ISSUE THREAD

**Issue by tree1891** [helix-toolkit/helix-toolkit#827]
It is also ok in Hira3DViewer.

[sample-asc_xy01.zip](https://github.com/helix-toolkit/helix-toolkit/files/2152351/sample-asc_xy01.zip)

**Comment by JeremyAnsel** [comment]
I've fixed the stl reader.

![helixtoolkit_stl_sample](https://user-images.githubusercontent.com/9573196/42134290-ee04f1d0-7d38-11e8-890a-c8ab7274a38f.png)
