### ISSUE TITLE
Unable to change object transform in code after dragging a UITranslateManipulator3D

### ISSUE THREAD

**Issue by damonbla** [helix-toolkit/helix-toolkit#829]
Maybe I'm doing something wrong, but I've come across an issue where I can't move an object with code after touching a UITranslateManipulator3D that was added in the xaml.

I have added three UITranslateManipulator3D objects in the xaml file, one for each axis. The TargetTransform and Transform properties are set to a 3D object that is imported in the c# code. When the program is run, you can click and drag on the manipulators and move the object around in each axis. It works great.

Also in the c# code I have a method of moving the same object's transform with values imported from a file. I'm moving the object by calling RotateTransform3D() with the values in the file, after pushing a button that I added in the xaml. It works great as well.

The problem happens if I combine the two: that is, grab the manipulators to move the object, then click on my button to load the transform values from the file. The object does not move. After doing anything with the manipulators at all, the transform somehow seems to become "locked" and the object can no longer be moved except with the manipulators once they are touched. In fact, even if I first do the movement-in-code method so the object moves fine, then grab a manipulator, the object stops moving with the code and the manipulators have total control again.

Hopefully I've explained this thoroughly enough. I'm glad to give more details if needed.

**Comment by holance** [comment]
Are you using the view model binding for the transform?

**Comment by holance** [comment]
Try to set binding to Mode=TwoWay in xaml.

**Comment by damonbla** [comment]
Hey that worked! To be specific in case anyone else comes across this: I had to change the binding for the Transform for the mesh object to Mode=TwoWay. The manipulators are not set to TwoWay - they don't seem to need it. Thank you @holance!
