### ISSUE TITLE
ZoomExtentsWhenLoaded not work when model transformed

### ISSUE THREAD

**Issue by gregorsGit** [helix-toolkit/helix-toolkit#832]
Hi, 
when starting the Viewport3DX with ZoomExtentsWhenLoaded="True" its only work, when no 
relevant transforms is set.
Reproduce it with two simple models. One with a bigger transform.
`   <hx:MeshGeometryModel3D ` 
`                  x:Name="model"` 
`                 Transform="{Binding Model1Transform}"` 
`                Geometry="{Binding Model}"` 
`                 Material="{Binding RedMaterial}"` 
`                 />` 
`             <hx:MeshGeometryModel3D` 
`                 x:Name="modelWithHugeTransform"` 
`                  Transform="{Binding Model4Transform}"` 
`                 Geometry="{Binding Model}"           `                   
`                 Material="{Binding BlueMaterial}" />`

` Model4Transform = new Media3D.TranslateTransform3D(-40, 0, 0);`

Bug: On Startup you will see only the red model.
So I try to fix it with a small change in  HelixToolkit.Wpf.SharpDX.Model.Scene GeometryNode in the Property Setter.
`  BoundManager.Geometry = value;`
`                    UpdateMatrix();  **<-- Update the MatrixTransform after geo is set.**`
`                   if (IsAttached)`
`                    {                `       
`                        BufferModelInternal = OnCreateBufferModel(this.GUID, value);`
`                    }`

And implement UpdateMatrix() in SceneNode.cs
`      public virtual void UpdateMatrix()`
`        {`
`            if (needMatrixUpdate || forceUpdateTransform)`
`            {`
`                TotalModelMatrix = modelMatrix * parentMatrix;`
`                needMatrixUpdate = false;`
`            }`
`        } ` 

This is only working, when you first set the Transform-Property and then the Geometry-Property. (Order depends)
Please fix this issue.

**Comment by cfrezksa** [comment]
The problem with ZoomExtents was solved, but the problem that the TotalTransformMatrix is not correct after a model has been loaded from disk still remains. If you do some calculations on the model before displaying it, the results will be wrong.
