### ISSUE TITLE
ObjExporter

### ISSUE THREAD

**Issue by EmTschi** [helix-toolkit/helix-toolkit#845]
Hi!
I try to export the viewport with the ObjExporter, but i get empty *.obj and *.mtl files.

`ObjExporter exporter = new ObjExporter(@"C:\bla\blabla.obj");`
`exporter.Export(viewport3DX);`

**Comment by holance** [comment]
You can try to use `exporter.Export(MeshGeometryModel)` instead of export a viewport.

**Comment by JeremyAnsel** [comment]
Hello,
I've fixed the exporter in #850
