### ISSUE TITLE
Rig Model Animate

### ISSUE THREAD

**Issue by Norfo** [helix-toolkit/helix-toolkit#853]
Good day! I want to animate my 3D model of human (model with rig). Is where any decision to do this by this toolkit. If it is possible, can you give any example, please.

**Comment by holance** [comment]
You can use the bone skinny model. But you need to write your own animation engine to provide bone    transform matrices.

**Comment by holance** [comment]
There's a [bone skinny demo](https://github.com/helix-toolkit/helix-toolkit/tree/develop/Source/Examples/WPF.SharpDX/BoneSkinDemo)

**Comment by Norfo** [comment]
Thanks

**Comment by holance** [comment]
Initial check in for keyframe animation support has been done. #879 
BoneSkin demo has been updated to show a simple rig model animation.
