### ISSUE TITLE
ObjExporter export MeshGeometryModel3D fails

### ISSUE THREAD

**Issue by riegaz** [helix-toolkit/helix-toolkit#857]
Because of this https://github.com/helix-toolkit/helix-toolkit/issues/845 I tried to export a exporter.Export(MeshGeometryModel3D) but it fails.

```
var meshi = new MeshGeometryModel3D() { Geometry = model.geometry, Material = model.material }
var exporter = new ObjExporter("C:\meshi.obj");
exporter.ExportNormals = true;
exporter.Export(meshi);
```

Why?

**Comment by riegaz** [comment]
I'm still on the 2.2.0 version available via Nuget.

**Comment by holance** [comment]
You need to correct the file path `var exporter = new ObjExporter(@"C:\meshi.obj");`. And make sure your application has the permission to write to your `c` drive.

**Comment by holance** [comment]
There is a bug in exporter. I will fix it.

**Comment by riegaz** [comment]
Thanks for fixing. Will there be a new nuget version out soon or do I have to add the helix toolkit manually?

**Comment by holance** [comment]
I am planning to release a new version this weekend if there's no severe bug found.
