### ISSUE TITLE
UWP StudioReader : wrong Y texture coordinate

### ISSUE THREAD

**Issue by fmExcense** [helix-toolkit/helix-toolkit#870]
I have experienced an issue with texture mapping when importing a 3DS model which has textures. It seems that the StudioReader implementation in the UWP toolkit does not set correctly the Y coordinate of the texture.

In the file [StudioReader.cs](https://github.com/helix-toolkit/helix-toolkit/blob/develop/Source/HelixToolkit.SharpDX.Shared/Utilities/ImportExport/StudioReader.cs), line 577

`pts.Add(new Vector2(x, y));`

should be replaced with

`pts.Add(new Vector2(x, 1 - y));`

Best,

**Comment by SiNeumann** [comment]
hi,
do you have 3ds testfile regarding this issue

**Comment by fmExcense** [comment]
Yes, here is a 3ds file and a texture file which is not mapped correctly.

[3DS-LoaderWithTexture.zip](https://github.com/helix-toolkit/helix-toolkit/files/2234868/3DS-LoaderWithTexture.zip)

**Comment by SiNeumann** [comment]
Thank you I'll have a look this weekend
