### ISSUE TITLE
SharpDX Viewport3DX transparent background not working

### ISSUE THREAD

**Issue by karl-barkmann** [helix-toolkit/helix-toolkit#877]
Does sharpdx viewport3dx support transparent background?
According to #579 and #867, setting backgroundcolor to #00000000 will make background transparent.
But it is not working to me.
Did I missed anything?

```
            <hx:Viewport3DX x:Name="view1"
                        Grid.Row="0"
                        Margin="0,20,0,0"
                        Background="#00000000"
                        BackgroundColor="#00000000"
                        Camera="{Binding Camera}"
                        CoordinateSystemLabelForeground="#434343"
                        EnableDesignModeRendering="True"
                        EnableSwapChainRendering="True"
                        FXAALevel="Ultra"
                        IsZoomEnabled="True"
                        MSAA="Maximum"
                        ShowCameraInfo="True"
                        ShowCameraTarget="True"
                        ShowCoordinateSystem="True"
                        ShowFrameDetails="True"
                        ShowFrameRate="True"
                        ShowViewCube="True"
                        TextBrush="Black"
                        UseDefaultGestures="False">
               </hx:Viewport3DX>
```
Setting backgroundcolor to #00000000 result in a black background.
![tim 20180730172308](https://user-images.githubusercontent.com/5437253/43389022-4013a548-941d-11e8-87da-9c417a447310.png)

**Comment by JeremyAnsel** [comment]
Hello,
This seems to work:
```c#
    <Grid Background="Green">
        <hx:Viewport3DX Background="#00000000" BackgroundColor="#00000000"
                        FXAALevel="Ultra" MSAA="Maximum"
                        EnableSwapChainRendering="False">
        </hx:Viewport3DX>
    </Grid>
```
The background becomes green:
![capture](https://user-images.githubusercontent.com/9573196/43415882-0e53ceb0-9437-11e8-9739-5109ae121722.PNG)

**Comment by holance** [comment]
MSAA and FXAA are mutually exclusive. FXAA will be disabled if msaa is used.

**Comment by karl-barkmann** [comment]
Thank you, now it worked.

**Comment by wahidrezgui** [comment]
> Hello,
> This seems to work:
> 
> ```cs
>     <Grid Background="Green">
>         <hx:Viewport3DX Background="#00000000" BackgroundColor="#00000000"
>                         FXAALevel="Ultra" MSAA="Maximum"
>                         EnableSwapChainRendering="False">
>         </hx:Viewport3DX>
>     </Grid>
> ```
> 
> The background becomes green:
> ![capture](https://user-images.githubusercontent.com/9573196/43415882-0e53ceb0-9437-11e8-9739-5109ae121722.PNG)



> Hello,
> This seems to work:
> 
> ```cs
>     <Grid Background="Green">
>         <hx:Viewport3DX Background="#00000000" BackgroundColor="#00000000"
>                         FXAALevel="Ultra" MSAA="Maximum"
>                         EnableSwapChainRendering="False">
>         </hx:Viewport3DX>
>     </Grid>
> ```
> 
> The background becomes green:
> ![capture](https://user-images.githubusercontent.com/9573196/43415882-0e53ceb0-9437-11e8-9739-5109ae121722.PNG)

thank you for your help
