### ISSUE TITLE
StudioReader doesn't support KeyFrames

### ISSUE THREAD

**Issue by SiNeumann** [helix-toolkit/helix-toolkit#878]
Currently the StudioReaders WPF and SharpDX ignores keyframes.  I got a file where this is needed as the Keyframes contain additonal transformations as well as  a hierachy (order in which these have to be applied).
Anyway I'm currently working on it, unfortunately the only file I have which has these keyframes I cannot share public. 
For reference check https://github.com/kovacsv/JSModeler/blob/master/src/import/importer3ds.js this parser included the keyframes + the transformation.

So  basically I would like to fire a PR as soon as I am finished. 
If anyone has some testing files I would appreciate it, as I would like to have more than 1 file to test

**Comment by holance** [comment]
I am currently working on the animation key frame support under my own branch
https://github.com/holance/helix-toolkit

The key frame will be stored under BoneSkinnedMeshGeometry3D. You can also check the bone skin demo under my branch. Maybe I will do a initial PR for the key frame support and you can develop the reader base on it.

**Comment by holance** [comment]
The initial merge for keyframe support has been done. You can implement your studio reader to support the keyframes under BoneSkinnedMeshGeometry3D.

**Comment by holance** [comment]
New assimp importer will supports keyframes.#1035
