### ISSUE TITLE
How to set image material in SharpDX?

### ISSUE THREAD

**Issue by riegaz** [helix-toolkit/helix-toolkit#880]
From the WPF example, the following works:

`<t:SphereVisual3D Radius="1" Material="{t:ImageMaterial 'pack://application:,,,/Examples/Earth/earth.jpg'}" ThetaDiv="180" PhiDiv="90" />`

Doing this in code behind works as well in SharpDX:

```
var image = new MemoryStream(ImageToByte(Properties.Resources.aha));
            var mat = new PhongMaterial
            {
                AmbientColor = Colors.Gray.ToColor4(),
                DiffuseColor = Colors.White.ToColor4(),
                SpecularColor = Colors.White.ToColor4(),
                SpecularShininess = 100f,
                DiffuseAlphaMap = image
            };

            var lv = new MeshBuilder(true, true, true);
            lv.AddEllipsoid(new Vector3(0f, 0f, 0f), 1, 1, 1, 275, 180);

var model = new MeshGeometryModel3D() { Geometry = lv.ToMesh(), Material = mat, IsTransparent = true, CullMode = SharpDX.Direct3D11.CullMode.Back };
```

However, when I load a STL file and want to cover it with the earth texture image, The earth image ist projected onto each vertex of each triangle. What do I do wrong?

Wrong projection when loading the image as DiffuseAlphaMap as for the ellipsoid: ![image](https://user-images.githubusercontent.com/1749401/43470518-11f61200-94e9-11e8-8519-3634b9fb049c.png)

Earth image: ![image](https://user-images.githubusercontent.com/1749401/43470109-13296ede-94e8-11e8-8f55-1b24b64080cd.png)

**Comment by holance** [comment]
Check if your model texture coordinates are correct. Use diffuse map instead of diffuse alpha map.

**Comment by riegaz** [comment]
I didn't set the texture coordinates at all, cause this is not required for the first two examples. Why is it needed when loading the geometry from a .stl file? This is what I don't get. If I load a sphere from stl, it does not work but if I create the sphere with the mesbuilder it works.

**Comment by holance** [comment]
Try to use the lastest unstable build, I think there's a bug #870 in studio reader about the texture coordinates which has been fixed in #876.

**Comment by riegaz** [comment]
Thanks @holance . I will try, however, I think my problem my be related to a different problem, which could be simply my understanding. When I create an ellipsoid via the MeshBuilder AddEllipsoid, I can see that the TextureCoordinates have meaningful values. When I load a .stl sphere, I only see a 0,0 1,0 0,1... I'm not sure if this is caused by the mentioned bug. I guess those TextureCoordinates have to be calculated in Meshlab before exporting the .stl file. 

Am I right?

**Comment by holance** [comment]
Yes, if the texture coordinates in your file already wrong, then the mapping will be wrong. You need to make sure this first.

**Comment by riegaz** [comment]
Hm, do you know by chance with which program I can calculate the texture coordinates? Meshlab, Rhino, Blender....for meshlab I didn't find a how to yet.

**Comment by holance** [comment]
I think those tools you mentioned are all capable to do the texturing
