### ISSUE TITLE
Colors in OBJ (without MTL)

### ISSUE THREAD

**Issue by privet56** [helix-toolkit/helix-toolkit#885]
Opening the file
http://privet.bplaced.net/temp/taeyeon_a.obj (is also attached)
in the Demo Viewer, the colors are lost.
Opening the same file in MeshLab, I can see the colors.

See: http://privet.bplaced.net/temp/meshlab.vs.helixtoolkit.png
(on the pic, in the background: Meshlab, foreground: the Helix Demo Viewer, both with the same OBJ file)

What can I do to get the colors in the Helix-toolkit Demo Viewer too?

![meshlabVSDemoViewer](http://privet.bplaced.net/temp/meshlab.vs.helixtoolkit.png)

[taeyeon_a.zip](https://github.com/helix-toolkit/helix-toolkit/files/2254534/taeyeon_a.zip)

![meshlab vs helixtoolkit](https://user-images.githubusercontent.com/15926631/43600296-83ac70b8-968a-11e8-8876-f97f5b882523.png)

**Comment by JeremyAnsel** [comment]
MeshLab uses an extension of the Wavefront Obj format to store per vertex color.

This is not currently suported by HelixToolkit.

See:
- https://github.com/cnr-isti-vclab/vcglib/blob/master/wrap/io_trimesh/import_obj.h
- https://github.com/cnr-isti-vclab/vcglib/blob/master/wrap/io_trimesh/export_obj.h

**Comment by holance** [comment]
I implemented the obj reader to support vertex color reading. But only available for SharpDX version. You also needs to change the material to VertColorMaterial.
![image](https://user-images.githubusercontent.com/905577/43617223-aa530c0a-9675-11e8-8b47-dee23f5f411d.png)

**Comment by privet56** [comment]
Great!
Impressive!
Thank You both for the helpful answers & extension!

[ I would 'Star' the project & community twice if I could! :-)  ]
