### ISSUE TITLE
Viewport3DX is black on app startup

### ISSUE THREAD

**Issue by climber03** [helix-toolkit/helix-toolkit#891]
Hi, i updated HelixToolkit.WPF.SharpDX from 1.1.0 ot 2.3.0 and now the Viewport3DX control is black for a few seconds on application startup. Repro can be done by starting the SimpleDemo in the HelixToolkit.Wpf.ShaprDX solution. The control is then black until the control has loaded. Removing all the models from the Viewport3DX does not help. Is this a bug or do i have to make some changes in my code?

Greets
Michael

**Comment by holance** [comment]
Maybe change both Viewport3DX.Background and Viewport3DX.BackgroundColor to the same color

**Comment by climber03** [comment]
Hi holance, thanks, this fixed the issue!
