### ISSUE TITLE
Coordinate system and view cube are clipped when resizing the Viewport3DX

### ISSUE THREAD

**Issue by climber03** [helix-toolkit/helix-toolkit#892]
Hi, in HelixToolkit.Wpf.SharpDX 2.3.0 the coordinate system and the view cube are clipped when the Viewport3DX control is resized. Repro can be done by starting the SimpleDemo in the HelixToolkit.Wpf.SharpDX solution and then by resizing the window:
![grafik](https://user-images.githubusercontent.com/18352639/43760662-0f5c441c-9a23-11e8-8f49-de2b274a98fe.png)
I saw that the position of these two can now be changed by the CoordinateSystemHorizontalPosition and CoordinateSystemVerticalPosition (and the same for view cube). The value is in percent of the control size (-1 to 1), and thats the problem... Has anyone an idea how to overcome this problem?

Greets
Michael

**Comment by holance** [comment]
You can to adjust the this two relative location values either from code behind or from your viewmodel after resize event. Maybe in future I will implement the corner snapping.

**Comment by holance** [comment]
Fixed
