### ISSUE TITLE
Storyboard not supported?

### ISSUE THREAD

**Issue by karl-barkmann** [helix-toolkit/helix-toolkit#900]
hello,I‘m trying animate elment2d by using storyboard, but the animation can not be started.
Is storyboard supported?
Thank you.

**Comment by holance** [comment]
You mean the element2d under WPF.SharpDX? Or element3D?

**Comment by karl-barkmann** [comment]
Actually, I tried them both. None of them work with storyboard.

**Comment by holance** [comment]
You can use wpf controls instead of element2d as long as you don't need swapchain rendering. I don't know if storyboard supports Transform3D for element3D.

**Comment by karl-barkmann** [comment]
OK.Thank you for your reply.
