### ISSUE TITLE
Rendering lines with light?

### ISSUE THREAD

**Issue by githubjanson** [helix-toolkit/helix-toolkit#901]
I need to render line segments. So I am using LineVisual3D, but I just realised that it doesn't have a Material property or similar, so it doesn't react to light sources (as opposed to GridLinesVisual3D, for instance).

Is there a way to render "light aware" line segments?

Thanks.

**Comment by holance** [comment]
I think you may use something like a tube instead of a line. Line is just a line, it is screenspaced, not sure what kind of effect you want to achieve with lights.

**Comment by githubjanson** [comment]
I am visualizing measurement data, like a sequence of similar profiles made of line segments. When all profiles have the exact same color, it is hard to see and get a "sense" of the data. For example, if a number of profiles together forms a box like shape, you completely miss the 3D effect without light, everything is just a one-colored blob. Hope that made sense? ;-)

**Comment by githubjanson** [comment]
Ok, thanks.
