### ISSUE TITLE
PointGeomatry & VertexArray

### ISSUE THREAD

**Issue by manojsakhare** [helix-toolkit/helix-toolkit#906]
In old SharpDx version we could show points using overriding OnCreateGeometryBuffers method.

I need to change the color of few points dynamically, how I could do it in New SharpDx version???

**Comment by holance** [comment]
Change the PointGeometry3D.Colors for vertex coloring.

**Comment by manojsakhare** [comment]
So if I change the Color4Collection of the Geometry... the colors should automatically update on ViewPort?
If it is not updating, what method I should use? In old version I was able to do that using ViewPort.ReAttach()

**Comment by holance** [comment]
You need to assign a different color4 collection to do update. You can use two collection and swapping them instead of create new one each time for update.

**Comment by holance** [comment]
Could you create and upload a simple demo project?

**Comment by manojsakhare** [comment]
https://www.dropbox.com/s/1pvna3qcbh3hc7q/PointPlot.zip?dl=0

**Comment by holance** [comment]
Ok, the point color is calculated as VertexColor * PointGeometryModel3D.Color. If you need to use individual vertex color, set PointGeometryModel3D.Color = Colors.White.

**Comment by manojsakhare** [comment]
Thanks @holance It worked. 💯
