### ISSUE TITLE
Imported OBJ File just blank screen

### ISSUE THREAD

**Issue by lucasschoch** [helix-toolkit/helix-toolkit#910]
I'm with the same first issue of Imported OBJ File just blank screen #666 but he solve by himself and doesn't share how.
Does anybody can help me ?

**Comment by holance** [comment]
Did you use the file loader demo to load your obj?

**Comment by lucasschoch** [comment]
Yes.
I'm trying to open any demo that loads a OBJ file, but no one is working. It doesn't throw an error or something like it. It just doesn't show anything.
The helixtoolkit examples > BrowserExamples > Examples > ModelViewer doesn't display the "ferrari" too.
I really don't know. looks like there's something missing, like a "show()" or something like it.

**Comment by lucasschoch** [comment]
![image](https://user-images.githubusercontent.com/22839700/44537540-79697780-a6d5-11e8-8ab0-67d129a1971b.png)

**Comment by lucasschoch** [comment]
![image](https://user-images.githubusercontent.com/22839700/44537613-a4ec6200-a6d5-11e8-9f51-671559eaa241.png)

**Comment by lucasschoch** [comment]
It looks like it only work with 3ds objects. OBJ, DAE, MTL... doesn't open. Actually OBJ doesn't throw error, DAE and MTL display errors, what makes me think it will not be possible, the only thing is the OBJ itself, which is the one I need.

**Comment by holance** [comment]
Try the obj under Models/obj. I am loading Obj fine. What's the error you are getting?

**Comment by holance** [comment]
Maybe the file access privilege? Try to run as administrator?

**Comment by lucasschoch** [comment]
Tried. Doesn't work.

**Comment by holance** [comment]
Try the sharpdx version file load demo.

**Comment by holance** [comment]
Or run the sharpdx version Post effects demo and it should load an obj model in the demo

**Comment by lucasschoch** [comment]
When I execute via SharpDX it works, but I couldn't run the example via code, only the executable. The code doesn't compile... humpf... hard day....

**Comment by lucasschoch** [comment]
I got the dlls from the executable folder and it's working now.
Thank you very much my friend @holance

**Comment by holance** [comment]
Please refer to the project build requirement on Readme.md if you are having issue building the project.
