### ISSUE TITLE
Set Meshgeometry Color

### ISSUE THREAD

**Issue by manojsakhare** [helix-toolkit/helix-toolkit#915]
I am using Meshgeometry builder to create geometry for UIScaleManipulator.

I am able to create the geometry, but even though I set the Matrial property, color is always black.

**Comment by holance** [comment]
Did you set the lighting correctly?

**Comment by manojsakhare** [comment]
Yes... The lights are added... other objects gets the color... 

I created a class which is inheriting from UIManipulator3D... I needed a geometry (cylinder & box) to show this manipulator... so added geometry using MeshBuilder... I can see the Geometry but color is always black.

**Comment by holance** [comment]
Check if your geometry normals are calculated. If not, use Geometry3D.Normals = Geometry3D.CalculateNormals();

**Comment by manojsakhare** [comment]
Thanks it worked, could you please also let me know why we needed to do that?

**Comment by holance** [comment]
When you create the meshbuilder, did you pass the first parameter as false on constructor?

**Comment by manojsakhare** [comment]
Yes. Thanks for the help ;-)
