### ISSUE TITLE
stl material issue

### ISSUE THREAD

**Issue by tree1891** [helix-toolkit/helix-toolkit#917]
When export and import with stl, materials is changed.
ex: original is gray, but it is changed to blue after export and import.
![image](https://user-images.githubusercontent.com/1282201/44762270-0cdcf580-ab79-11e8-894f-894bfc1a1a35.png)

**Comment by holance** [comment]
I don't think STL format supports material export. https://en.wikipedia.org/wiki/STL_(file_format)

**Comment by tree1891** [comment]
Blue color is default?

**Comment by holance** [comment]
Possibly. You need to step through the reader code to see what exactly happened.
