### ISSUE TITLE
Is it possible to render the content of a Viewport3DX to an image (png/bmp) with higher DPI?

### ISSUE THREAD

**Issue by climber03** [helix-toolkit/helix-toolkit#920]
Hi, i have a Viewport3DX and want to save the content as an image with a different resolution than the screen (the image should have higher DPI). I need to make an image of my sceen which is then scaled a lot, so just making a sceenhot of my scene will look very pixelated...

Thanks, cheers
Michael

**Comment by holance** [comment]
There's a render bitmap extension function with sizes. Let me know if it works.

**Comment by climber03** [comment]
Hi, thanks for your fast answer! I tried the extension function but the width and height arguments seems to be ignored. The image is alwas saved with the dimensions of the viewport regardless of the width and height arguments of the RenderBitmap mehthod.

Here is the code snipped i used for saving the bitmap as a png:
```
private void SaveViewportImage(double scale, string filename)
{
    var image = view1.RenderBitmap(view1.Width * scale, view1.Height * scale);

    using (var fileStream = new FileStream(filename, FileMode.Create))
    {
        var encoder = new PngBitmapEncoder();
        encoder.Frames.Add(BitmapFrame.Create(image));
        encoder.Save(fileStream);
    }
}
```

I am using HelixToolkit 2.4.0. Is this a bug or am i making something wrong?

Greets
Michael

**Comment by holance** [comment]
Yes, there is a bug in `ResizeAndArrange` checking condition.

Work around is using following codes
```
        public static BitmapSource RenderBitmap(
            this Viewport3DX view, double width, double height)
        {
            double w = view.Width;
            double h = view.Height;
            ResizeAndArrange(view, width, height);
            var rtb = RenderBitmap(view);
            ResizeAndArrange(view, w, h);
            return rtb;
        }
        public static void ResizeAndArrange(this Viewport3DX view, double width, double height)
        {
            view.Width = width;
            view.Height = height;
            if (double.IsNaN(width) || double.IsNaN(height) || view.RenderHost == null || !view.RenderHost.IsRendering)
            {
                return;
            }            
            view.Measure(new Size(width, height));
            view.Arrange(new Rect(0, 0, width, height));
            view.RenderHost.Resize(width, height);
        }
```

**Comment by climber03** [comment]
Hi, thanks, now it works!
