### ISSUE TITLE
Consider removing the "On" prefix from events.

### ISSUE THREAD

**Issue by smischke** [helix-toolkit/helix-toolkit#924]
Most of the newer events have the prefix "On" which is against microsofts naming convention (see [here)](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/event).

As an example, the refactoring of RenderCore.OnInvalidateRenderer could look like this:
Name of method that causes the event: InvalidateRenderer()
Name of event itself: RendererInvalid
Name of method that fires the event (optional): RaiseRendererInvalid() (in this case I would just use InvalidateRenderer() as it is)
Name of virtual event handler method in RenderCore: OnRendererInvalid()
Name of event handler method everywhere else: OnRenderCoreRendererInvalid

If this change is accepted, I volunteer to do the refactoring and make a pull request or someone else may do it.

Here's a list of events that have the prefix "On":
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Core\Abstract\RenderCore.cs(30):        public event EventHandler<EventArgs> OnInvalidateRenderer;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Core\Batching\StaticGeometryBatchingBufferBase.cs(31):        public event EventHandler<EventArgs> OnInvalidateRender;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Core\BoneUploaderCore.cs(19):        public event EventHandler OnBoneChanged;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Core\Buffers\BoneSkinBufferModel.cs(26):        public event EventHandler OnBoneIdBufferUpdated;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Core\Buffers\ElementsBufferModel.cs(24):        public event EventHandler<EventArgs> OnElementChanged;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Core\Buffers\EmptyBufferModel.cs(95):        public event EventHandler OnVertexBufferUpdated;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Core\Buffers\EmptyBufferModel.cs(96):        public event EventHandler OnIndexBufferUpdated;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Core\Buffers\GeometryBufferModel.cs(26):        public event EventHandler OnVertexBufferUpdated;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Core\Buffers\GeometryBufferModel.cs(27):        public event EventHandler OnIndexBufferUpdated;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Core\Components\CoreComponent.cs(13):        public event EventHandler OnInvalidateRender;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Core\ScreenSpacedMeshRenderCore.cs(88):        public event EventHandler<BoolArgs> OnCoordinateSystemChanged;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Core\ShadowMapCore.cs(36):        public event EventHandler<UpdateLightSourceEventArgs> OnUpdateLightSource;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Core2D\Abstract\RenderCore2D.cs(24):        public event EventHandler<EventArgs> OnInvalidateRenderer;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Model\Components\GeometryBoundManager.cs(134):        public event EventHandler<BoundChangeArgs<BoundingBox>> OnBoundChanged;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Model\Components\GeometryBoundManager.cs(136):        public event EventHandler<BoundChangeArgs<BoundingBox>> OnTransformBoundChanged;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Model\Components\GeometryBoundManager.cs(138):        public event EventHandler<BoundChangeArgs<BoundingSphere>> OnBoundSphereChanged;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Model\Components\GeometryBoundManager.cs(140):        public event EventHandler<BoundChangeArgs<BoundingSphere>> OnTransformBoundSphereChanged;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Model\Material\MaterialVariableBase.cs(29):        public event EventHandler OnUpdateNeeded;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Model\Scene\Abstract\GroupNodeBase.cs(61):        public event EventHandler<OnChildNodeChangedArgs> OnAddChildNode;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Model\Scene\Abstract\GroupNodeBase.cs(62):        public event EventHandler<OnChildNodeChangedArgs> OnRemoveChildNode;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Model\Scene\Abstract\GroupNodeBase.cs(63):        public event EventHandler<OnChildNodeChangedArgs> OnClear;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Model\Scene\Abstract\SceneNode.cs(246):        public event EventHandler<TransformArgs> OnTransformChanged;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Model\Scene\Abstract\SceneNode.cs(315):        public event EventHandler<BoolArgs> OnVisibleChanged;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Model\Scene\Abstract\SceneNode.cs(317):        public event EventHandler OnAttached;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Model\Scene\Abstract\SceneNode.cs(319):        public event EventHandler OnDetached;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Model\Scene\Abstract\SceneNode.cs(672):        public event EventHandler<BoundChangeArgs<BoundingBox>> OnBoundChanged;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Model\Scene\Abstract\SceneNode.cs(677):        public event EventHandler<BoundChangeArgs<BoundingBox>> OnTransformBoundChanged;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Model\Scene\Abstract\SceneNode.cs(682):        public event EventHandler<BoundChangeArgs<BoundingSphere>> OnBoundSphereChanged;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Model\Scene\Abstract\SceneNode.cs(687):        public event EventHandler<BoundChangeArgs<BoundingSphere>> OnTransformBoundSphereChanged;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Model\Scene\ViewBoxNode.cs(60):        public event EventHandler<ViewBoxClickedEventArgs> OnViewBoxClicked;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Model\Scene2D\Abstract\SceneNode2D.cs(366):        public event EventHandler<Transform2DArgs> OnTransformChanged;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Model\Scene2D\Abstract\SceneNode2D.cs(375):        public event EventHandler OnAttached;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Model\Scene2D\Abstract\SceneNode2D.cs(380):        public event EventHandler OnDetached;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Model\Scene2D\Abstract\SceneNode2D.cs(385):        public event EventHandler<UpdateEventArgs> OnUpdate;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Render\RenderBuffers\DX11RenderBufferBase.cs(33):        public event EventHandler<Texture2DArgs> OnNewBufferCreated;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Render\RenderBuffers\DX11RenderBufferBase.cs(37):        public event EventHandler<EventArgs> OnDeviceLost;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Render\RenderHost\RenderHostBase.cs(514):        public event EventHandler<Texture2DArgs> OnNewRenderTargetTexture;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Render\RenderHost\RenderHostBase.cs(518):        public event EventHandler OnRendered;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\ShaderManager\EffectsManager.cs(50):        public event EventHandler<EventArgs> OnDisposeResources;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\ShaderManager\EffectsManager.cs(54):        public event EventHandler<EventArgs> OnInvalidateRenderer;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Utilities\FrameStatistics.cs(46):        public event EventHandler<FrameStatisticsArg> OnValueChanged;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Utilities\Octrees\Octree.cs(42):        public event EventHandler<EventArgs> OnHit;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Utilities\Octrees\OctreeManager.cs(31):        public event EventHandler<OctreeArgs> OnOctreeCreated;
helix-toolkit\Source\HelixToolkit.SharpDX.Shared\Utilities\Octrees\StaticOctrees\StaticOctree.cs(238):        public event EventHandler<EventArgs> OnHit;
helix-toolkit\Source\HelixToolkit.SharpDX.SharedModel\Controls\ModelContainer3DX.cs(92):        public event EventHandler<Texture2DArgs> OnNewRenderTargetTexture;
helix-toolkit\Source\HelixToolkit.SharpDX.SharedModel\Controls\ModelContainer3DX.cs(104):        public event EventHandler OnRendered;
helix-toolkit\Source\HelixToolkit.SharpDX.SharedModel\Element2D\Element2DCore.cs(118):        public event EventHandler<SceneNode2DCreatedEventArgs> OnSceneNodeCreated;
helix-toolkit\Source\HelixToolkit.SharpDX.SharedModel\Element3D\Abstract\Element3DCore.cs(105):        public event EventHandler<SceneNodeCreatedEventArgs> OnSceneNodeCreated;
helix-toolkit\Source\HelixToolkit.UWP\Controls\MouseHandlers\MouseInputController.cs(37):        public event EventHandler<PointerRoutedEventArgs> OnStartZoom;
helix-toolkit\Source\HelixToolkit.UWP\Controls\MouseHandlers\MouseInputController.cs(42):        public event EventHandler<PointerRoutedEventArgs> OnStartRotate;
helix-toolkit\Source\HelixToolkit.UWP\Controls\MouseHandlers\MouseInputController.cs(46):        public event EventHandler<PointerRoutedEventArgs> OnStartZoomExtends;
helix-toolkit\Source\HelixToolkit.UWP\Controls\MouseHandlers\MouseInputController.cs(50):        public event EventHandler<PointerRoutedEventArgs> OnStartZoomRectangle;
helix-toolkit\Source\HelixToolkit.UWP\Controls\MouseHandlers\MouseInputController.cs(54):        public event EventHandler<PointerRoutedEventArgs> OnStartPan;
helix-toolkit\Source\HelixToolkit.UWP\Controls\MouseHandlers\MouseInputController.cs(58):        public event EventHandler OnResetCamera;
helix-toolkit\Source\HelixToolkit.UWP\Controls\MouseHandlers\MouseInputController.cs(62):        public event EventHandler<PointerRoutedEventArgs> OnChangeLookAt;
helix-toolkit\Source\HelixToolkit.UWP\Controls\MouseHandlers\MouseInputController.cs(66):        public event EventHandler<PointerRoutedEventArgs> OnChangeFieldOfView;
helix-toolkit\Source\HelixToolkit.UWP\Controls\MouseHandlers\MouseInputController.cs(70):        public event EventHandler OnTopView;
helix-toolkit\Source\HelixToolkit.UWP\Controls\MouseHandlers\MouseInputController.cs(76):        public event EventHandler OnBottomView;
helix-toolkit\Source\HelixToolkit.UWP\Controls\MouseHandlers\MouseInputController.cs(82):        public event EventHandler OnLeftView;
helix-toolkit\Source\HelixToolkit.UWP\Controls\MouseHandlers\MouseInputController.cs(88):        public event EventHandler OnRightView;
helix-toolkit\Source\HelixToolkit.UWP\Controls\MouseHandlers\MouseInputController.cs(94):        public event EventHandler OnFrontView;
helix-toolkit\Source\HelixToolkit.UWP\Controls\MouseHandlers\MouseInputController.cs(100):        public event EventHandler OnBackView;
helix-toolkit\Source\HelixToolkit.UWP\Controls\MouseHandlers\MouseInputController.cs(107):        public event EventHandler<AddForceEventArgs> OnAddRotationForce;
helix-toolkit\Source\HelixToolkit.UWP\Controls\MouseHandlers\MouseInputController.cs(116):        public event EventHandler<AddForceEventArgs> OnAddPanForce;
helix-toolkit\Source\HelixToolkit.UWP\Controls\MouseHandlers\MouseInputController.cs(125):        public event EventHandler<AddForceEventArgs> OnAddZoomForce;
helix-toolkit\Source\HelixToolkit.UWP\Controls\MouseHandlers\MouseInputController.cs(134):        public event EventHandler<AddForceEventArgs> OnAddMoveForce;
helix-toolkit\Source\HelixToolkit.UWP\Controls\MouseHandlers\MouseInputController.cs(143):        public event EventHandler OnRestoreCameraSettings;
helix-toolkit\Source\HelixToolkit.UWP\Controls\Viewport3DX.cs(166):        public event EventHandler OnRendered;
helix-toolkit\Source\HelixToolkit.UWP\Controls\Viewport3DXProperties.cs(19):        public event EventHandler<MouseDown3DEventArgs> OnMouse3DDown;
helix-toolkit\Source\HelixToolkit.UWP\Controls\Viewport3DXProperties.cs(21):        public event EventHandler<MouseUp3DEventArgs> OnMouse3DUp;
helix-toolkit\Source\HelixToolkit.UWP\Controls\Viewport3DXProperties.cs(23):        public event EventHandler<MouseMove3DEventArgs> OnMouse3DMove;
helix-toolkit\Source\HelixToolkit.UWP\Controls\Viewport3DXProperties.cs(28):        public event EventHandler<RelayExceptionEventArgs> RenderExceptionOccurred;
helix-toolkit\Source\HelixToolkit.UWP\Model\Element3D\Abstract\Element3D.cs(125):        public event EventHandler<MouseDown3DEventArgs> OnMouse3DDown;
helix-toolkit\Source\HelixToolkit.UWP\Model\Element3D\Abstract\Element3D.cs(127):        public event EventHandler<MouseUp3DEventArgs> OnMouse3DUp;
helix-toolkit\Source\HelixToolkit.UWP\Model\Element3D\Abstract\Element3D.cs(129):        public event EventHandler<MouseMove3DEventArgs> OnMouse3DMove;
helix-toolkit\Source\HelixToolkit.Wpf.SharpDX\Controls\DX11ImageSourceRenderHost.cs(27):        public event EventHandler<DX11ImageSourceArgs> OnImageSourceChanged;
helix-toolkit\Source\HelixToolkit.Wpf.SharpDX\Controls\Viewport3DX.cs(225):        public event EventHandler OnRendered;
helix-toolkit\Source\HelixToolkit.Wpf.SharpDX\Model\Elements3D\AbstractElements3D\ScreenSpaceMeshGeometry3D.cs(253):        public event EventHandler<ScreenSpaceMoveDirArgs> OnMoveClicked;
helix-toolkit\Source\HelixToolkit.SharpDX.Core\Controls\ViewportCore.cs(16):        public event EventHandler OnStartRendering;
helix-toolkit\Source\HelixToolkit.SharpDX.Core\Controls\ViewportCore.cs(17):        public event EventHandler OnStopRendering;
helix-toolkit\Source\HelixToolkit.SharpDX.Core\Controls\ViewportCore.cs(18):        public event EventHandler<Exception> OnErrorOccurred;

**Comment by holance** [comment]
I am doing some underlying changes to support physics based rendering, I will take care of this later.

**Comment by holance** [comment]
Merged
