### ISSUE TITLE
Does EnableBitmapCache of Element2D improve performance?What is it for?

### ISSUE THREAD

**Issue by karl-barkmann** [helix-toolkit/helix-toolkit#927]
Hello,does EnableBitmapCache of Element2D improve performance?And how?
If not,what is it for?

https://github.com/helix-toolkit/helix-toolkit/wiki/Tips-on-performance-optimization-(WPF.SharpDX-and-UWP) 
The wiki page seems wrote nothing about this.

**Comment by holance** [comment]
Yes. Unless you are using swapchain, otherwise you can still using WPF controls with WPF bitmap caches to improve performance.

**Comment by karl-barkmann** [comment]
Got it.Thanks !
