### ISSUE TITLE
Change mouse cursor over object

### ISSUE THREAD

**Issue by SLucaS1** [helix-toolkit/helix-toolkit#929]
Is it possible to change the cursor when it passes over a certain object in HelixToolkit.Wpf.SharpDX?

In HelixToolkit.Wpf I use a UIElement3D with events OnMouseEnter and OnMouseLeave, but in SharpDX it would seem not to work.

in HelixToolkit.Wpf   

    Protected Overrides Sub OnMouseEnter(ByVal e As MouseEventArgs)
        MyBase.OnMouseEnter(e)
        Mouse.OverrideCursor = Cursors.Hand
    End Sub

    Protected Overrides Sub OnMouseLeave(ByVal e As MouseEventArgs)
        MyBase.OnMouseLeave(e)
         Mouse.OverrideCursor = Nothing
    End Sub

**Comment by holance** [comment]
You can implement this function yourself. Hook up the viewport3dx.MouseMove event, do viewport3dx.HittedSomething or viewport3dx.FindHits in your mouse move event. Just be careful about the performance if you have a lot of objects.

Something like the following:
```
        private void View1_MouseMove(object sender, System.Windows.Input.MouseEventArgs e)
        {
            if (view1.HittedSomething(e))
            {
                Cursor = System.Windows.Input.Cursors.Hand;
            }
            else
            {
                Cursor = System.Windows.Input.Cursors.Arrow;
            }
        }
```

**Comment by SLucaS1** [comment]
it works, thanks
