### ISSUE TITLE
Reset UICompositeManipulator3D Rotation

### ISSUE THREAD

**Issue by manojsakhare** [helix-toolkit/helix-toolkit#931]
How to reset UICompositeManipulator3D rotation??

**Comment by holance** [comment]
Reset the Transform ?

**Comment by manojsakhare** [comment]
Is there any method available?? The manipulator is binded to 3d box... so not sure which tranform needs to be reset? If method is not available, then what object (e.g. RotationTransform3D) should be used to reset? What will the values? I just want reset the rotations

**Comment by manojsakhare** [comment]
I was able to do it with using RotateTransform3D
