### ISSUE TITLE
Add, remove and add same Element3D to ObservableElement3DCollection throws ArgumentException

### ISSUE THREAD

**Issue by climber03** [helix-toolkit/helix-toolkit#932]
Hi, when i add an Element3D (e.g. a MeshGeometryModel3D) to an ObservableElement3DCollection and then remove the element from the collection and add it again, i get an ArgumentException ('SceneNode already attach to a different node') in GroupNodeBase.cs, line 73.

You can repro this by changing these methods in the GroupElementTester example:
```
private MeshGeometryModel3D model;

private void AddGroupModel(object o)
{
    if (model == null)
    {
        model = new MeshGeometryModel3D
        {
            Geometry = SphereModel,
            Material = BlueMaterial,
            Transform = new Media3D.TranslateTransform3D(0, (GroupModelSource.Count + 1) * 2, 0)
        };
    }

    GroupModelSource.Add(model);
}

private void RemoveGroupModel(object o)
{
    if (GroupModelSource.Contains(model))
    {
        GroupModelSource.Remove(model);
    }
}

```

I tested this with HelixToolkit 2.4.0. Is this a bug or do i have to explicitly remove the Element3D from the scene?

Greets,
Michael

**Comment by holance** [comment]
Fixed.

**Comment by climber03** [comment]
Thanks!
