### ISSUE TITLE
How to get/set the Rotation from UICompositeManipulator3D

### ISSUE THREAD

**Issue by manojsakhare** [helix-toolkit/helix-toolkit#937]
How to read rotation (angles) from UICompositeManipulator3D?
I have binded the manipulator to 3d geometry... I need to save the rotation set by the user and use the saved angel information to set the transform once the app is relaunched. What is the best way?

**Comment by holance** [comment]
You can get the transform matrix from Transform3D. Then you can either save the matrix or decompose it to derive the angle/axis from the matrix.

**Comment by manojsakhare** [comment]
How to decompose Matrix3D ?? I think decompose is available with Matrix3

**Comment by holance** [comment]
https://docs.microsoft.com/en-us/dotnet/framework/wpf/graphics-multimedia/3-d-transformations-overview

**Comment by manojsakhare** [comment]
Resolved. Thanks for the help.
