### ISSUE TITLE
How to set rotation value (angle) of UIRotateManipulator3D

### ISSUE THREAD

**Issue by manojsakhare** [helix-toolkit/helix-toolkit#938]
How to set rotation value (angle) of UIRotateManipulator3D object?

OnValueChanged method is not implemented.

**Comment by holance** [comment]
You need to set Transform property with RotationTransform3D.
https://docs.microsoft.com/en-us/dotnet/framework/wpf/graphics-multimedia/3-d-transformations-overview

**Comment by manojsakhare** [comment]
Resolved. Thanks for the help.
