### ISSUE TITLE
System.OutofMemory exception when creating Model from Point Cloud

### ISSUE THREAD

**Issue by bVess12** [helix-toolkit/helix-toolkit#940]
Hello,

I'm trying to use helixtoolkit WPF SharpDx to visualize a large point cloud. I am currently using the MeshBuilder to create a MeshGeometry3D from my ordered points.  When loading a model this way of about 500,000 points, the viewer is constantly using around ~400MB of memory, and when replacing the model with another, the amount of used memory increases. I am unable to get the viewer to release the used memory.  Loading in a model of ~1,000,000 points will result in an OutOfMemory exception, and this will occur after repeatedly loading in smaller models.

I am currently iterating through a 2D array of Vector3s, and creating quads to add to the Meshbuilder, before using the MeshBuilder to create a MeshGeometry3D.

My questions are:
  1.  What is the proper way to create geometry from a point cloud?
   2. What is the proper way to clear the used memory of the viewport?

**Comment by holance** [comment]
If you just want to visualize points, why not use PointGeometry3D directly? Also, you can refer to the dynamic texture demo, the example shows how you can streaming the verts. And refer to [wiki](https://github.com/helix-toolkit/helix-toolkit/wiki/Dynamic-Geometry3D-for-Data-Streaming) for details.

**Comment by bVess12** [comment]
Thanks for the quick reply, I'll take a look at the dynamic texture demo.  The visualization of the points individually makes it very difficult to tell what the user is looking at. I'm trying to create a model and apply a texture to it. I've attached images to clarify.  One is with PointsGeometry3D and one is with MeshGeometry3D. The MeshGeometry3D provids exactly the desired visuals, but the memory usage is through the roof, and it results in an Out of Memory exception pretty quickly.
![mesh](https://user-images.githubusercontent.com/43218369/45450604-bd351880-b6a6-11e8-8102-c19fd45185d3.JPG)
![points](https://user-images.githubusercontent.com/43218369/45450605-bd351880-b6a6-11e8-8058-87a995a732b0.JPG)

**Comment by holance** [comment]
You can try to assign each point with different color. Another way is to create a special shader and do the color assignment in pixel shader.

**Comment by holance** [comment]
Could you provide a simple demo program for your point cloud?

**Comment by holance** [comment]
When you add quad, you added duplicated vertices into the mesh builder for different quads. That's why the size multiplied. Also, if you really want point cloud tessellation, you need different approach instead of adding quads. You can find a lot of different algorithm for point cloud tessellation such as alpha shape etc.

**Comment by holance** [comment]
Since your data is a grid, here is another way to do it. 
```
            Vector3[] p = new Vector3[pointHeights.Length];


            //Iterate through the point cloud
            int width = pointHeights.GetLength(0), height = pointHeights.GetLength(1);
            int count = 0;
            for(int i=0; i < width; ++i)
            {
                for(int j=0; j < height; ++j)
                {
                    p[count++] = new Point3D(i*xSpacing, j * ySpacing, pointHeights[i, j]);
                }
            }
            mb.AddRectangularMesh(p, height);
           MeshModel = mb.ToMeshGeometry3D();
```

**Comment by bVess12** [comment]
Thanks so much! That works infinitely better. It seems to work well on either platform.

In this instance, if I were trying to close the mesh, would I add in the Top/Bottom/Left/Right sides as individual Rectangular Meshes added to the same MeshBuilder?  And if I do, is there a way to "merge" the overlapping vertices that would occur?

**Comment by holance** [comment]
If you just need to add several quads to close the mesh, you can just add the quads. You don't need to worry about the overlapping for only a few vertices.

**Comment by bVess12** [comment]
Excellent, I can't thank you enough for your help. Your viewer goes well above and beyond my expectations, and the quality of your responses exceeds even that.

Thank you.
