### ISSUE TITLE
How to restrict Manipulators used only by Mouse Right Button

### ISSUE THREAD

**Issue by manojsakhare** [helix-toolkit/helix-toolkit#941]
I want to use UICompositeManipulator3D with mouse left button.

How I can restrict Mouse right and middle button?

I tried using MouseMove & MouseDown events, but they don't get invoked (not sure why).

But MouseMove3D and MouseDown3D works fine, but in this case I don't get clicked mouse button information.

**Comment by holance** [comment]
You need to create your own Manipulator. Override the OnMouse3DDown event, use such as `Mouse.LeftButton == MouseButtonState.Pressed` to determine the condition you want.

`MouseMove` and `MouseDown` events are WPF native event for 2D UI. In order for HelixToolkit controls to use XAML, all controls are inherits from `FrameworkContentElement`, which contains a lot of WPF 2D UI properties. But all these properties are not used for 3D elements.

**Comment by manojsakhare** [comment]
It worked thanks..!!
