### ISSUE TITLE
How many parameters are using to control the camera view?

### ISSUE THREAD

**Issue by Super169** [helix-toolkit/helix-toolkit#942]
I'm going to setup the initial view when the application start.

From preivous experience in v1.x, I open the viewport to show camera information, zoom and rotate the screen, so that my target display properly.  Then I record the LookDirection, UpDirection and Position, and add the code in code creation to set the Camera to this postion, then load my object from 3Ds file.  It works fine in 1.0.

But it doesn't work in v2.0, for example, I use the FileLoadDemo to load the object, and I have added the StatusBar to show the camera position information.  

![](https://raw.githubusercontent.com/Super169/images/master/Others/Helix-1.jpg)

Then I set the camera as in view model.  But when I load the same object again, the display is not as expected.

![](https://raw.githubusercontent.com/Super169/images/master/Others/Helix-2.jpg)

It seems that, only set the LookDirection, UpDirection and Postion is not good enough, may I know if there has any other parameter need to be set in order to restore the view as expected.  Thanks a lot.

**Comment by holance** [comment]
For orthographic camera, you need Width.

**Comment by Super169** [comment]
Thanks a lot, it works fine in OrthographicCamera by including the value of Width.

But, may I know if there has similar setting for PerspectiveCamera?  
I have add Camera.Width to statusBar, and it can show the value in OrthographicCamera , but there has no display for PerspectiveCamera, and I cannot set the value to Width as PrespectiveCamera does not have Width.

**Comment by Super169** [comment]
Does it mean that, when using PerspectiveCamera, I cannot set the initial position in this way?

May I know if there has any other way to fix the initial view to expected location if PerspectiveCamera is used?  Thanks.

**Comment by Super169** [comment]
Thanks a lot.  It works now.
