### ISSUE TITLE
3ds Import - Name of the components

### ISSUE THREAD

**Issue by francescobolleri** [helix-toolkit/helix-toolkit#943]
Hello and thanks for this great library!

Suppose you load a 3ds file using FileModelVisual3D.
How to get the components names?

I read in an open issue a similar discussion, but is not clear to me if is implemented or not.
I read about a GetName method, but if i call it from the objects extracted from the FileModelVisual3D  (Model3DGroup, GeometryModel3D, MeshGeometry3D) i always get "null" value.

I am trying with a .3ds model exported from Sketchup.
In the model i have generated some test component, assigning "Component Name".

Thank you very much in advance!

Francesco Bolleri

**Comment by francescobolleri** [comment]
Ok, so definitively is still not implemented.

Should be possible to include this change you describe in the next release of the library?
I prefer to don't alter it creating my own. It will be great if this will be included in the NuGet package available in Visual Studio..

Thanks in any case.
Francesco

**Comment by holance** [comment]
You can simply create your own studio reader in your project, refer to the helixtoolkit source code and fits your needs.

**Comment by francescobolleri** [comment]
Ok.
just to be sure:

Today i just do: 

_ViewPort.Children.Add(new FileModelVisual3D { Source = "myModel.3ds" });_

Writing a "fixed" class StudioReader_WithNames, this will be something like:

_StudioReader_WithNames myReader = new StudioReader_WithNames();
ViewPort.Children.Add(myReader.Read("myModel.3ds"));_

More or less is correct or i'm forgotting something important?

Thanks
Francesco

**Comment by holance** [comment]
I think this is what you need. Let me know if you have any questions.

**Comment by francescobolleri** [comment]
Thanks for your availability.

Should be very useful if you can explain me how to add a model to the viewport when loaded with an explicit usage of the Reader.

Because the Read method of the StudioReader is coming out with a Model3DGroup instance.
But the Add method of the Visual3DCollection Children in HelixViewport3D is expecting an object inherithed from Visual3D class.

I have to read in source code the body of Add method in Visual3DCollection?
Or is possible to wrap around to the Model3DGroup object some VisualClass already prepared for this scope?

Thank you in advance.
Francesco

**Comment by francescobolleri** [comment]
Thanks, but meanwhile i discover this way:

_StudioReaderEx myReader = new StudioReaderEx();
Model3DGroup wholeModel = myReader.Read("myModel.3ds");
foreach(Model3D mod in wholeModel.Children)
{
  ModelVisual3D v = new ModelVisual3D{ Content = mod };
  View3D.Children.Add(v);
}_

Now is all clear.

Thanks for all the support
Francesco
