### ISSUE TITLE
SharpDX View slower now

### ISSUE THREAD

**Issue by gregorsGit** [helix-toolkit/helix-toolkit#947]
Hi,

I see that the latest version Wpf.SharpDX is significant slower, then a one month old version.
After searching, I see the change in RenderHostBase.cs CanRender() was changed from
updateCounter < 2
to 
updateCounter < 6
This makes my performace kill.
Is this possible and wanted?

Thanks

**Comment by holance** [comment]
Then it means your graphic card cannot keep up. What's the graphic card model you are using?

**Comment by gregorsGit** [comment]
I have a NVdia QuadroP3000. 
In the LightingDemo I get ~20 FPS on FHD-Screen.

**Comment by holance** [comment]
Are you running laptop with integrated graphics card? You need to specify to run on Discrete graphic card to get full performance.

**Comment by gregorsGit** [comment]
I use a laptop.
Now I deactivate in the device-manager the intel card.
Then I get about 8 FPS?
Deactivating the NVidia card I get about 40 FPS.
I am confused.
My system is a win10 with latest NVidia driver. 
I disconnect the docking-station and the external monitors.

**Comment by holance** [comment]
Don't deactivate the graphic card in device manager.
You can simply right click the mouse on exe, select Run with graphic processor -> nvidia.
Or go to the nvidia control panel -> manage 3D settings -> prefered graphics processor, select the nvidia one.

**Comment by gregorsGit** [comment]
Ok.
With the NVidia card is the performance ok. Even with updateCounter < 6.

**Comment by gregorsGit** [comment]
Hi,
I reopen this issue. 
On some targets, without NVidia graphics. Onboard Intel-Cards this point is critical.
So please make a property/setting to control this count from outside.
My testmodel has about 2Mil. Triangles!
Without this check i can rotate nearly smooth. With this check it stops permantly.
Thanks.

**Comment by holance** [comment]
I will add the settings.
