### ISSUE TITLE
Emissive Map for PhongMaterial

### ISSUE THREAD

**Issue by liinko** [helix-toolkit/helix-toolkit#948]
I noticed that PhongMaterial now has SpecularColorMap which is great, since I had to manually implement it before, but it has no emissive map.

I also noticed that the new PBR material has an EmissiveMap, but no SpecularColorMap.

Now, I'm not sure if it would even make sense for PBR to have a SpecularColorMap, but can we get the ability to use an EmissiveMap for the regular PhongMaterial?

The models in my project have both a specular color map, and an emissive map, among others already present, I tried adding the EmissiveMap manually as I had done before but ran into some issues with buffer sizes, and I didn't have enough knowledge of hlsl to fix it.

**Comment by holance** [comment]
Sure, will add it in soon

**Comment by liinko** [comment]
Thank you for your quick response, Helix Toolkit has been amazing and easy to use, I really appreciate what you guys do.
