### ISSUE TITLE
Light all model faces regardless of light direction

### ISSUE THREAD

**Issue by S34Qu4K3** [helix-toolkit/helix-toolkit#950]
Hi, I have an small problem, I want to light all the model faces regardless of the light direction. When I create a ExtrudedText with MeshBuilder the fron looks like this
![front](https://user-images.githubusercontent.com/5208600/46338160-b4918b80-c62f-11e8-8042-4c97ed18013d.PNG)
but the back side looks like this due the DirectionalLight in my Viewport
![back_color](https://user-images.githubusercontent.com/5208600/46338195-c70bc500-c62f-11e8-9c36-096b35d054db.PNG)

I tried setting up an AmbientLight but I can't make the back side look like the front one. Even turning off  ShadowMapping the dark side remains. Also RenderShadowMap for the object is set to false

Any help would be appreciated

**Comment by holance** [comment]
Try to bind your direction light direction to camera look direction.

**Comment by S34Qu4K3** [comment]
It look even more darker
![back2](https://user-images.githubusercontent.com/5208600/46357631-93e42880-c665-11e8-833e-0e9d17d5dfca.PNG)
A close solution I found was setting the Emissive Color on the text material and looks pretty decent
![new1](https://user-images.githubusercontent.com/5208600/46357788-e9203a00-c665-11e8-84ee-44a6bf20c0eb.PNG)
![new2](https://user-images.githubusercontent.com/5208600/46357796-ec1b2a80-c665-11e8-96b3-5c2298d8916a.PNG)

There's a way to make an AmbientOcclusion effect with Helixtoolkit and get a better look on the back side of the text (and other models)?

Thank you for the help @holance (and for all your work =))

**Comment by S34Qu4K3** [comment]
Yeah, I'm using sharpdx version, this happens as well in the SimpleDemo
![side1](https://user-images.githubusercontent.com/5208600/46396779-a8b9ce00-c6f0-11e8-9f58-417e097270b2.PNG)
![side2](https://user-images.githubusercontent.com/5208600/46396783-abb4be80-c6f0-11e8-97b1-780ee1adefaf.PNG)

**Comment by holance** [comment]
One issue I noticed is the text model created from HelixToolkit demo has some incorrect normals.
To fix it. you can try to do this
`TextModel.Normals = TextModel.CalculateNormals();`

This should fix the normals.

Then you can combine with ambient light / multiple directional light / Shadow map to achieve the effect you want.

**Comment by holance** [comment]
Have you solved your problem?

**Comment by S34Qu4K3** [comment]
Yesh, calculating the normals and adding another light solver the issue
Thanks a lot

**Comment by S34Qu4K3** [comment]
Hello again @holance i din't want to open another issue, but I'm having similar problems when importing a .3ds with the StudioReader, the faces which are not oriented to the light are black. I can fix this adding more lights but, its possible to set a PhongMaterial which make all the lighting uniform? I tried setting the Diffuse color to white,Ambient Color to white and Render Shadow Map to false but the dark places remain there.

![cap](https://user-images.githubusercontent.com/5208600/46660482-680df900-cbb7-11e8-8e0f-286abded6bb7.PNG)

Best regards

**Comment by holance** [comment]
You need to bind the directional light direction to your camera look direction. So there is at least one directional light is always light up your camera look direction.

**Comment by holance** [comment]
For further questions, you can ask on [Gitter](https://gitter.im/helix-toolkit/helix-toolkit)

**Comment by S34Qu4K3** [comment]
Thanks, binding the look direction to the directional light direction kinda fixes it. I was looking more for an style of ambient occlusion but this solution will work

**Comment by holance** [comment]
Currently we do not support ambient occlusion, realtime ambient occlusion is very expensive.

**Comment by S34Qu4K3** [comment]
And a solution with baked lightmaps would be feasible?

**Comment by holance** [comment]
The new Physics based rendering material supports RMA( Roughness, Metallic, Ambient Occlusion) map. If your model is using PBR material, you can use it directly. Please refer to [RMA channel packing detail](https://github.com/helix-toolkit/helix-toolkit/wiki/Roughness-Metallic-AmbientOcclusion-(RMA)-Map).
