### ISSUE TITLE
Example CustomShaderDemo is broken

### ISSUE THREAD

**Issue by stewienj** [helix-toolkit/helix-toolkit#952]
The example CustomShaderDemo is broken, crashes on startup. The variable bHasEmissiveMap in cbMesh in the file CommonBuffers.hlsl is out by 4 bytes from the one in helix-toolkit library.

When I swapped the following 2 lines it fixed the problem (from https://github.com/helix-toolkit/helix-toolkit/blob/develop/Source/Examples/WPF.SharpDX/CustomShaderDemo/Shaders/CommonBuffers.hlsl)

Before fix:
```
line 65: bool bHasAlphaMap = false; // If using PBR, this is used as HasRMAMap.
line 66: bool bHasEmissiveMap;
```
After fix:
```
line 65: bool bHasEmissiveMap;
line 66: bool bHasAlphaMap = false; // If using PBR, this is used as HasRMAMap.
```

**Comment by holance** [comment]
Yes, forgot to update it. Will fix soon.
