### ISSUE TITLE
Transparent Fill causes mirror glossy finish

### ISSUE THREAD

**Issue by mwpowellhtx** [helix-toolkit/helix-toolkit#96]
I'm not sure why, but when I Fill a RectangleVisual3D (or anything?) with Transparent, I get a glossy, mirror type of finish. So... why is Transparent not... _transparent_ ?

See this example illustrating what I mean:

![rectangle-transparent-fill-reflection-1](https://cloud.githubusercontent.com/assets/1824187/5428061/309f544c-837b-11e4-84b2-e38d9210b740.png)

Possibly this is a function of reflection from lighting source? Which again, seems like a Material/Transparent issue? The same area on the field from an opposite angle: no apparent reflection.

![rectangle-transparent-fill-reflection-2](https://cloud.githubusercontent.com/assets/1824187/5428063/43f099fc-837b-11e4-842d-f8dcd21b8c8a.png)

**Comment by holance** [comment]
Render transparent objects after opaque objects.

**Comment by mwpowellhtx** [comment]
@holance Wow, it's been awhile. Thanks for the heads up and the tip. :+1:
