### ISSUE TITLE
[UWP] Viewport3DX transparent background

### ISSUE THREAD

**Issue by fmExcense** [helix-toolkit/helix-toolkit#961]
Hi,

I know this issue has been answered several times ([#867](https://github.com/helix-toolkit/helix-toolkit/issues/867), [#877](https://github.com/helix-toolkit/helix-toolkit/issues/877), [#717](https://github.com/helix-toolkit/helix-toolkit/issues/717) and [#579](https://github.com/helix-toolkit/helix-toolkit/issues/579)), but none of the solutions i found here seem to work for UWP (2.4.0).

Is it possible to make the Viewport3DX background transparent?

I tried this :

`<Grid>
   <Grid.Background>
       <SolidColorBrush Color="Red"/>
    </Grid.Background>
    <hx:Viewport3DX x:Name="view3D"
                                Background="#00000000"
                                BackgroundColor="#00000000" >
    </hx:Viewport3DX>
</Grid>`

It gives me a black background. Any idea?

Thx

**Comment by holance** [comment]
I don't think UWP supports transparent background. 
What do you want to achieve with transparent background?

**Comment by holance** [comment]
In develop branch, the 2.5 unstable release includes a screen quad model 3D. User can use it to define any background with an image stream. You can try the unstable release from myget feed. And I think the 2.5 release is coming soon.

**Comment by holance** [comment]
2.5 has been released. Close for now.

**Comment by ruben0909** [comment]
Hi, I know this is old, but it doesn`t work in UWP.
Thank you regards.
