### ISSUE TITLE
DeviceEx init exception VMware

### ISSUE THREAD

**Issue by gregorsGit** [helix-toolkit/helix-toolkit#962]
Hi,
I try to start one of your examples on a windows 10 VMware. (ManipulationDemo, Wpf.SharpDX, Lates Source)
In the vm is only one adapter present called VMWare SVGA 3D.
I try to compile it for 64Bit. No changes.
Can someone help me.
Thanks.

--------------------------
> Error
> ---------------------------
> DPFCanvas: Error while starting rendering: HRESULT: [0x8876086C], Module: [SharpDX.Direct3D9], ApiCode: [D3DERR_INVALIDCALL/InvalidCall], Message: Unknown 
>  StackTrace:    bei SharpDX.Result.CheckError()
>    bei SharpDX.Direct3D9.Direct3DEx.CreateDeviceEx(Int32 adapter, DeviceType deviceType, IntPtr hFocusWindow, Int32 behaviorFlags, PresentParameters[] presentationParametersRef, DisplayModeEx[] fullscreenDisplayModeRef, DeviceEx returnedDeviceInterfaceOut)
>    bei HelixToolkit.Wpf.SharpDX.DX11ImageSource.StartD3D() in C:\Projects\Base_Tools\HelixToolkitSharpDX\Source\HelixToolkit.Wpf.SharpDX\Controls\DX11ImageSource.cs:Zeile 124.
>    bei HelixToolkit.Wpf.SharpDX.Controls.DX11ImageSourceRenderHost.DX11ImageSourceRenderer_OnNewBufferCreated(Object sender, Texture2DArgs e) in C:\Projects\Base_Tools\HelixToolkitSharpDX\Source\HelixToolkit.Wpf.SharpDX\Controls\DX11ImageSourceRenderHost.cs:Zeile 56.
>    bei HelixToolkit.Wpf.SharpDX.Render.DX11RenderBufferProxyBase.CreateRenderTarget(Int32 width, Int32 height, MSAALevel msaa) in C:\Projects\Base_Tools\HelixToolkitSharpDX\Source\HelixToolkit.SharpDX.Shared\Render\RenderBuffers\DX11RenderBufferBase.cs:Zeile 205.
>    bei HelixToolkit.Wpf.SharpDX.Render.DX11RenderHostBase.OnInitializeBuffers(DX11RenderBufferProxyBase buffer, IRenderer renderer) in C:\Projects\Base_Tools\HelixToolkitSharpDX\Source\HelixToolkit.SharpDX.Shared\Render\RenderHost\RenderHostBase.cs:Zeile 842.
>    bei HelixToolkit.Wpf.SharpDX.Render.DX11RenderHostBase.StartD3D(Double width, Double height) in C:\Projects\Base_Tools\HelixToolkitSharpDX\Source\HelixToolkit.SharpDX.Shared\Render\RenderHost\RenderHostBase.cs:Zeile 774.
>    bei HelixToolkit.Wpf.SharpDX.DPFCanvas.StartD3D() in C:\Projects\Base_Tools\HelixToolkitSharpDX\Source\HelixToolkit.Wpf.SharpDX\Controls\DPFCanvas.cs:Zeile 164.
>    bei HelixToolkit.Wpf.SharpDX.DPFCanvas.OnLoaded(Object sender, RoutedEventArgs e) in C:\Projects\Base_Tools\HelixToolkitSharpDX\Source\HelixToolkit.Wpf.SharpDX\Controls\DPFCanvas.cs:Zeile 120.
> ---------------------------
> OK   
> -------------------------

**Comment by smischke** [comment]
You need at least VMWare 12, the VM has to be upgraded to V12, you need to install the latest VMWare Tools and enable 3D acceleration.

**Comment by gregorsGit** [comment]
Hi,
I change in the .vmx file
virtualHW.version = "12"
Update VMWare Tools 
And now it starts.

My Vware-Player is version 12.xxx
Thanks.
