### ISSUE TITLE
NullRef Exception in BufferComponent (SharpDX)

### ISSUE THREAD

**Issue by gregorsGit** [helix-toolkit/helix-toolkit#966]
Hi,

sometimes I get this exception from the viewer. 
![grafik](https://user-images.githubusercontent.com/34306200/46858651-07c3c500-ce0c-11e8-819a-c7ba87bced92.png)
What can I do?
Thanks.

**Comment by holance** [comment]
Do you know when this happened?

**Comment by gregorsGit** [comment]
It happens when I zoom in. The scene was already loaded.

**Comment by holance** [comment]
It happens frequently?

**Comment by gregorsGit** [comment]
This is not the first time I see this exception. It happens. See it more then 10x.
After Restart it works mostly.

**Comment by holance** [comment]
I put a fix in, let me know if you still getting this exception.

**Comment by gregorsGit** [comment]
I try this version.
Currently the exception was not thrown.
Thanks.

**Comment by holance** [comment]
Close for not. Reopen if issue happened again.
