### ISSUE TITLE
Ensure wpf objects are disposed on ui thread

### ISSUE THREAD

**Issue by smischke** [helix-toolkit/helix-toolkit#973]
Please take a look at this screenie:

![https://i.imgur.com/cInbYlX.png](https://i.imgur.com/cInbYlX.png)

**Comment by holance** [comment]
Please manually call EffectsManager.Dispose() from UI thread. Use finalizer to dispose effects manager will causes memory leak. Seems like the directx device does not like the finalizer.

Maybe I will remove the destructor from EffectsManager.

I will try to solve this exception.

**Comment by holance** [comment]
Suggest to manually call Dispose instead of relying on Finalizer.
