### ISSUE TITLE
Unexpected "clipping" of lines in Viewport3DX

### ISSUE THREAD

**Issue by githubjanson** [helix-toolkit/helix-toolkit#982]
I am experiencing problems when rendering lines (LineGeometry3D) in Viewport3DX. Lines are "clipping" themselves. Attached image shows an example based on the LineShadingDemo. Using version 2.3.0.

![line clipping 3](https://user-images.githubusercontent.com/7782203/47412660-9d484880-d76c-11e8-9335-c4e2d1afa007.png)

Any thoughts on this? 

Cheers.

**Comment by holance** [comment]
Change its smoothness to 0. Otherwise the edge of the line is trying to be smooth and blending into the background

**Comment by githubjanson** [comment]
Ok. It seems like lines are rendered with the same thickness, no matter of the distance from camera. Is this expected? I would like the grid it to look more like the GridLinesVisual3D that can used in HelixViewport3D. How can I achieve this?

Thanks.

**Comment by holance** [comment]
Currently it only supports render with same thickness. You can try to use tube mesh as lines.

**Comment by holance** [comment]
Line/Point non fixed size support has been merged.
