### ISSUE TITLE
Video in helix-toolkit

### ISSUE THREAD

**Issue by Stakhmi4** [helix-toolkit/helix-toolkit#987]
Can i play video in helix-toolkit?

Standart 3D work fine with VisualBrush and MediaElement

`
<Viewport3D>
	<Viewport3D.Camera>
		<PerspectiveCamera FarPlaneDistance="100"
						   LookDirection="2,-1,-1"
						   UpDirection="0,1,0"
						   NearPlaneDistance="1"
						   Position="-20,15,15"
						   FieldOfView="60">
			</PerspectiveCamera>
	</Viewport3D.Camera>
    <ModelVisual3D>
		<ModelVisual3D.Content>
			<AmbientLight Color="#888888"></AmbientLight>
		</ModelVisual3D.Content>
	</ModelVisual3D>

	<ModelVisual3D>
		<ModelVisual3D.Content>
			<GeometryModel3D x:Name="cubeGeometry">
				<GeometryModel3D.Geometry>
					<MeshGeometry3D Positions="0,0,0 10,0,0 0,10,0 10,10,0
												0,0,0 0,0,10 0,10,0 0,10,10
												0,0,0 10,0,0 0,0,10 10,0,10
												10,0,0 10,10,10 10,0,10 10,10,0
												0,0,10 10,0,10 0,10,10 10,10,10
												0,10,0 0,10,10 10,10,0 10,10,10"
									TriangleIndices="0,2,1 1,2,3
													4,5,6 6,5,7
													8,9,10 9,11,10
													12,13,14 12,15,13
													16,17,18 19,18,17
													20,21,22 22,21,23"
									TextureCoordinates="0,0 0,1 1,0 1,1
														1,1 0,1 1,0 0,0
														0,0 1,0 0,1 1,1
														0,0 1,0 0,1 1,1
														1,1 0,1 1,0 0,0
														1,1 0,1 1,0 0,0"/>
                </GeometryModel3D.Geometry>
				<GeometryModel3D.Material>
					<DiffuseMaterial>
						<DiffuseMaterial.Brush>
							<VisualBrush TileMode="None">
								<VisualBrush.Visual>
									<MediaElement Source="D:\Projects\Temp\HelixVideo3D\HelixVideo3D\Video sample\sample.wmv"
												LoadedBehavior="Play"/>
                                </VisualBrush.Visual>
                            </VisualBrush>
                        </DiffuseMaterial.Brush>
                    </DiffuseMaterial>
                </GeometryModel3D.Material>
            </GeometryModel3D>
        </ModelVisual3D.Content>
        <ModelVisual3D.Transform>
            <RotateTransform3D>
                <RotateTransform3D.Rotation>
                    <AxisAngleRotation3D x:Name="rotate" Axis="0 1 0" />
                </RotateTransform3D.Rotation>
            </RotateTransform3D>
        </ModelVisual3D.Transform>
    </ModelVisual3D>
</Viewport3D>`

**Comment by holance** [comment]
If WPF standard 3D can play, then HelixToolkit.WPF can play too, it is using the WPF standard rendering engine. But SharpDX version does not support yet.
