### ISSUE TITLE
Incompatible NuGet packages

### ISSUE THREAD

**Issue by githubjanson** [helix-toolkit/helix-toolkit#989]
NuGet pacakges are not compatible. Cannot install HelixToolkit 2.5.1 and HelixToolkit.WPF.SharpDX 2.5.1 with HelixToolikt.WPF 2.5.0 (latest).

> Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to find a version of 'HelixToolkit' that is compatible with 'HelixToolkit.Wpf 2.5.0 constraint: HelixToolkit (= 2.5.0)', 'HelixToolkit.Wpf.SharpDX 2.5.1 constraint: HelixToolkit (= 2.5.1)'.			0

**Comment by holance** [comment]
WPF 2.5.1 is uploaded to nuget. Should fix this issue.
