### ISSUE TITLE
How to or which property could control only when mouse down the earth model that makes  it  Rotate?

### ISSUE THREAD

**Issue by BarryJame** [helix-toolkit/helix-toolkit#993]
Please help me out...

**Comment by holance** [comment]
Not sure what you mean. Are you talking about the earth demo in WPF examples?
It is using mouse down to rotate the earth already.

**Comment by BarryJame** [comment]
Yes, thank you for your patience to read my question, I have solved this problem. My problem is "When the WPF Earth Demo is in full screen, I only want to trigger the rotation when the mouse passes over the Earth model. The rest of the space can't be triggered." I am Chinese, and my English is not very good. I didn't read your Code comment carefully, but now I have carefully read it again. I posted the code below and hope to help people with the same problem.
Code:
```
 private void HelixViewPort3D_PreviewMouseMove(object sender, MouseEventArgs e)
        {
            this.HelixViewPort3D.CursorOnElementPosition = this.HelixViewPort3D.FindNearestPoint(e.GetPosition(sender as IInputElement));
            if (this.HelixViewPort3D.CursorOnElementPosition.HasValue)
            {
                //光标在球体上
                this.HelixViewPort3D.Cursor = Cursors.Hand;
                this.HelixViewPort3D.RotateGesture = new MouseGesture(MouseAction.LeftClick);
            }
            else
            {
                this.HelixViewPort3D.Cursor = Cursors.Arrow;
                this.HelixViewPort3D.RotateGesture = new MouseGesture(MouseAction.None);
            }
        }
```

**Comment by BarryJame** [comment]
Yes, thank you for your patience in reading my question, I have solved this problem. My question is "When the WPF Earth demo is full screen, I just want to trigger the rotation when the mouse passes the Earth model. The rest of the background can't trigger any events; I didn't read your code comments carefully, but now I have read it carefully. I posted the following code, hoping to help people solve the same problem.
Here's the code:
```
  /// <summary>
        /// 3D光标移动至球体触发
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void HelixViewPort3D_PreviewMouseMove(object sender, MouseEventArgs e)
        {
            this.HelixViewPort3D.CursorOnElementPosition = this.HelixViewPort3D.FindNearestPoint(e.GetPosition(sender as IInputElement));
            if (this.HelixViewPort3D.CursorOnElementPosition.HasValue)
            {
                //光标在球体上
                this.HelixViewPort3D.Cursor = Cursors.Hand;
                this.HelixViewPort3D.RotateGesture = new MouseGesture(MouseAction.LeftClick);
            }
            else
            {
                this.HelixViewPort3D.Cursor = Cursors.Arrow;
                this.HelixViewPort3D.RotateGesture = new MouseGesture(MouseAction.None);
            }
        }
```

**Comment by holance** [comment]
Nice.
