### ISSUE TITLE
Transparent sorting and materials (SharpDX)

### ISSUE THREAD

**Issue by gregorsGit** [helix-toolkit/helix-toolkit#994]
Hi,
I have a transpartent material and see in some cases a white filling.
Is it possible to get this working with OIT in all view directions?
In my example I change only the order of the two ellements. And then its ok for one direction.
Setting the model with the transparent material to IsTransparent makes it black.
I attach the two files for the SimpleDemo in SharpDX.
Need help.

FrontView:
![grafik](https://user-images.githubusercontent.com/34306200/47991021-4423d180-e0e9-11e8-9afe-2c023ee5cb36.png)

BackView:
![grafik](https://user-images.githubusercontent.com/34306200/47991076-66b5ea80-e0e9-11e8-8443-a0c5eb22911c.png)

IsTransprent=True;
![grafik](https://user-images.githubusercontent.com/34306200/47991266-f52a6c00-e0e9-11e8-8f62-cddd77d59f79.png)

[MainWindow.zip](https://github.com/helix-toolkit/helix-toolkit/files/2547835/MainWindow.zip)

**Comment by holance** [comment]
Please attach the viewmodel as well.

**Comment by gregorsGit** [comment]
Sorry. Here are both files.
[SimpleDemo.zip](https://github.com/helix-toolkit/helix-toolkit/files/2551805/SimpleDemo.zip)
